- documentation/optee_design.md
Updates the pager section of the OP-TEE design document with a
description of the pager.
> pager documentation

- core/include/tee/tee_cryp_concat_kdf.h
- core/tee/sub.mk
- core/tee/tee_cryp_concat_kdf.c
- core/tee/tee_svc_cryp.c
- documentation/extensions/crypto_concat_kdf.md
- lib/libutee/include/tee_api_defines_extensions.h
- lib/libutee/include/utee_defines.h
- lib/libutee/tee_api_operations.c
This is my implementation of Concat KDF. Please ignore the first two commits, they originate from pull request #154 and are better reviewed there.
About testing: I could only find one test vector, in https://tools.ietf.org/html/draft-ietf-jose-json-web-algorithms-37 section C. This test is OK on PLATFORM=vexpress-qemu_virt.
@xiaoqiangdu: I have added your Signed-off-by since I have re-worked some pieces of code that you wrote initially. Let me know if that's a problem.
> Concat kdf

- scripts/setup_qemu_optee.sh
To enable this feature, uncomment the following in setup_qemu_optee.sh
Please note you should install the following packages first
(on Ubuntu 14.04)
$ sudo apt-get install pcscd libpcsclite-dev default-jdk
After environment setup is done, you should install vpcd manually, by
$ cd virtualsmartcard/src/vpcd
$ sudo make install
Open another terminal, and enable Java Card Simulator(jcardsim)
$ java -cp jcardsim.jar org.linaro.seapi.VpcdClient
Then run the qemu, enter the following command in the linux console
(test SE API in API level)
(test SE API internal selftest)
Tested-by: SY Chiu <sy.chiu@linaro.org> (Ubuntu 14.04)
> Setup test environment for Secure Element API

- CHANGELOG.md
Added a new file and wrote the first release notes for tag 0.1.0.
> Add changes-log.md for release notes

- README.md
- scripts/setup_fvp_optee.sh
- scripts/setup_qemu_optee.sh
Setup (FVP / QEMU) are updating accordingly with the
Linux Driver Refactoring
> Linux Driver refactoring

- CHANGELOG.md
> Release notes 0.2.0

- core/arch/arm32/kernel/tee_ta_manager.c
- core/arch/arm32/plat-stm/conf.mk
- core/arch/arm32/tee/arch_svc.c
- core/include/kernel/tee_misc.h
- core/include/kernel/tee_ta_manager.h
- core/include/tee/tee_svc.h
- core/tee/tee_svc.c
- documentation/extensions/extensions.md
- lib/libutee/arch/arm32/utee_syscalls_asm.S
- lib/libutee/include/tee_internal_api_extensions.h
- lib/libutee/include/tee_syscall_numbers.h
- lib/libutee/include/utee_syscalls.h
- lib/libutee/include/utee_types.h
- lib/libutee/tee_api.c
Following extensions are introduced:
- TEE_CacheClean()
- TEE_CacheFlush()
- TEE_CacheInvalidate()
> Internal API extension on Cache Operations

- core/tee/tee_pobj.c
This patch implements this part of the GlobalPlatform Internal Core API v1.1
Multiple handles may be opened on the same object simultaneously using
the functions TEE_OpenPersistentObject or TEE_CreatePersistentObject,
but sharing MUST be explicitly allowed. More precisely, at any one
time the following constraints apply: If more than one handle is opened
on the same object, and if any of these object handles was opened with
the flag TEE_DATA_FLAG_ACCESS_READ, then all the object handles MUST have
been opened with the flag TEE_DATA_FLAG_SHARE_READ. There is a corresponding
constraint with the flags TEE_DATA_FLAG_ACCESS_WRITE and
TEE_DATA_FLAG_SHARE_WRITE. Accessing an object with write-meta rights is
exclusive and can never be shared.
When one of the functions TEE_OpenPersistentObject or …
> Persistent Object Sharing Rules adjust with respect to GP v1.1

- core/arch/arm32/plat-stm/tz_a9init.S
Reviewed-on: https://gerrit.st.com/18519
Tested-by: Pascal BRAND <pascal.brand@st.com>
> [plat-stm] fix/disable cache FullZeroLineWrite support

- core/arch/arm32/kernel/tee_ta_manager.c
- lib/libutee/arch/arm32/user_ta_entry.c
At session open, if a TA instance is found, single session TAs are
busy only if context already handle a session.
At session closure, KeepAlive TA must close all pending session
but not free remaining allocations nor free its context.
From user TA entry code, remove useless "ta_dead" field and insure
heap and math support is only initialized once (for KeepAlive TA not
to re-init these libs).
> Handle "keep alive" TA property

- core/arch/arm32/plat-stm/conf.mk
- core/arch/arm32/plat-stm/link.mk
- core/arch/arm32/plat-sunxi/conf.mk
- core/arch/arm32/plat-sunxi/link.mk
- core/arch/arm32/plat-vexpress/conf.mk
- core/arch/arm32/plat-vexpress/link.mk
- core/arch/arm32/plat-vexpress/platform_config.h
- core/arch/arm32/plat-vexpress/platform_flags.mk
- core/core.mk
- documentation/build_system.md
- mk/compile.mk
- mk/gcc.mk
- mk/lib.mk
- ta/ta.mk
Enables compilation with different compilers for core and user TA.
> Separate compiler for core and user TA

- core/kernel/tee_dispatch.c
- lib/libutee/include/tee_api.h
- lib/libutee/include/tee_api_defines.h
- lib/libutee/include/tee_api_types.h
- lib/libutee/tee_api.c
- lib/libutee/tee_api_arith.c
- lib/libutee/tee_api_objects.c
- lib/libutee/tee_api_operations.c
- lib/libutee/tee_api_property.c
1st pass code update (no deprecated functions)
Change-Id: Ieca5a1ddd81266f5b8839199dbca46a01f96979c
> Global Platform Internal Core API v1.1 update

- core/arch/arm32/plat-stm/platform_flags.mk
- core/arch/arm32/plat-sunxi/platform_flags.mk
> Define CFG_ARM32_user_ta on stm and sunxi

- core/include/tee/tee_svc_storage.h
- core/tee/tee_svc_storage.c
- lib/libutee/include/utee_syscalls.h
- lib/libutee/tee_api_arith.c
- lib/libutee/tee_api_objects.c
- lib/libutee/tee_api_operations.c
- lib/libutee/tee_api_property.c
Change-Id: I5c07d21ece670081014ecc570fa1d80aef813ede
> Update ABI-32bits and v1.1 uint32_t changes

- lib/libutee/tee_user_mem.c
- ta/mk/ta_dev_kit.mk
> Fix runtime issue when CFG_TEE_CORE_USER_MEM_DEBUG=0

- core/arch/arm32/kernel/tee_ta_manager.c
> core/arm32: fix TA cache services

- core/tee/tee_svc_cryp.c
> Fix RSA key pair generation when public exponent is provided

- lib/libutee/tee_api_property.c
update size_t to uint32_t type, panic
> GP Internal Core API v1.1 : review property access functions

- core/arch/arm/kernel/thread.c
- core/arch/arm/mm/core_mmu_lpae.c
- core/arch/arm/plat-stm/conf.mk
- core/arch/arm/plat-sunxi/conf.mk
- core/arch/arm/plat-vexpress/conf.mk
- core/arch/arm/plat-vexpress/entry_a32.S
- core/arch/arm/plat-vexpress/main.c
- core/arch/arm/plat-vexpress/platform_config.h
- ta/arch/arm/link.mk
- ta/mk/ta_dev_kit.mk
Splitting PR#259 into more manageable pieces.
> Cleaning for hikey

- core/arch/arm/include/kernel/misc.h
- core/arch/arm/kernel/misc_a32.S
- core/arch/arm/mm/tee_pager.c
- core/arch/arm/tee/arch_svc.c
> Pager: update abort dump

- core/arch/arm/include/kernel/tee_l2cc_mutex.h
- core/arch/arm/include/mm/core_mmu.h
- core/arch/arm/kernel/tee_l2cc_mutex.c
- core/arch/arm/mm/core_mmu.c
- core/arch/arm/plat-stm/cache_maintenance.c
> arm: l2cc cleanup

- core/arch/arm/kernel/tee_ta_manager.c
Fix the 2-level cache clean/inv/flush sequences.
Current implementation follows recommendations from
http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0246d/Beicdhde.html
Reviewed-by: CIBUILD <smet-aci-builds@lists.codex.cro.st.com>
> Fix TA cache maintenance support

- core/arch/arm/tee/init.c
- core/include/tee/tee_cryp_provider.h
- core/tee/tee_cryp_utl.c
> crypto: initialize with service_init()

- core/arch/arm/kernel/generic_core_bootcfg.c
> generic_core_bootcfg.c: clean comments and messages

- core/arch/arm/kernel/thread.c
Insure vmem allocated for stack protection (an unmaped page at
stack bottom) and effective thread stack vmem are physically
contiguous.
Tested-by: Pascal BRAND <pascal.brand@st.com>
> arm32/pager: fix thread stack allocation in vmem

- core/arch/arm/mm/core_mmu_lpae.c
- core/arch/arm/mm/core_mmu_v7.c
- core/arch/arm/plat-stm/main.c
- core/arch/arm/plat-sunxi/main.c
> Replace read_cpsr() by thread_mask_exceptions

- lib/libutee/include/tee_api_defines.h
- lib/libutee/tee_user_mem.c
- lib/libutee/tee_user_mem.h
update panic reasons
Note : For testing use optee_test with dev/gp11_meme_mngt branch
> GP Internal Core API v1.1 : memory management functions

- .travis.yml
> travis: fix HTTP 404

- lib/libutee/include/utee_defines.h
- lib/libutee/tee_api_objects.c
Vote: For testing use optee_test dev/gp11_generic_obj branch
> GP Internal Core API v1.1 : generic object functions

- README.md
> Add HiKey build instructions to README.md

- core/tee/tee_svc_cryp.c
Reviewed-by: Jean-Michel DELORME <jean-michel.delorme@st.com>
> Object handle flags not reset

- documentation/debug.md
Adding a section in the debug.md file that explains how to enable ftrace
and use it for debugging the kernel module for OP-TEE.
Tested-by: Joakim Bech <joakim.bech@linaro.org> (QEMU, Hikey)
> Doc: Adding ftrace documentation

- core/arch/arm/mm/tee_mm.c
> Fix unaligned lo and hi in tee_mm_init

- scripts/setup_qemu_optee.sh
> Fix qemu script

- core/arch/arm/include/arm64.h
- core/arch/arm/include/kernel/thread.h
- core/arch/arm/include/kernel/vfp.h
- core/arch/arm/kernel/generic_boot.c
- core/arch/arm/kernel/sub.mk
- core/arch/arm/kernel/thread.c
- core/arch/arm/kernel/vfp.c
- core/arch/arm/kernel/vfp_a64.S
- core/arch/arm/plat-hikey/platform_config.h
- core/arch/arm/plat-mediatek/platform_config.h
- core/arch/arm/plat-vexpress/platform_config.h
First commit is just code cleaning. Second one implements CFG_WITH_VFP on arm64.
> arm64: CFG_WITH_VFP

- scripts/setup_mtk_optee.sh
Tested-by: SY Chiu <sy.chiu@linaro.org> (MT8173 EVB)
> Add stable commit for mt8173 kernel patches

- CHANGELOG.md
- scripts/setup_fvp_optee.sh
- scripts/setup_juno_optee.sh
- scripts/setup_mtk_optee.sh
- scripts/setup_qemu_optee.sh
> Release note of 0.3.0 and script updates

- core/arch/arm/include/arm64.h
> arm64: rewrite register access functions with macros

- core/tee/tee_enc_fs.c
- core/tee/tee_svc_storage.c
> File Storage: fix position in case of seek

- core/lib/libtomcrypt/src/pk/ecc/ecc.c
- core/lib/libtomcrypt/src/pk/ecc/ecc_test.c
- core/lib/libtomcrypt/src/pk/ecc/ltc_ecc_mulmod.c
> ECC: Update LTC code from branch develop

- lib/libutee/tee_api_operations.c
add TEE_ALG_DSA_SHA224/TEE_ALG_DSA_SHA256
> GP Internal Core API v1.1 : update TEE_AllocateOperation DSA

- lib/libutee/tee_api_operations.c
add TEE_ALG_ECDSA_Pxxx/TEE_ALG_ECDH_Pxxx
> GP Internal Core API v1.1 : update TEE_AllocateOperation ECC

- lib/libutee/tee_api_objects.c
update return code/panic reasons
> GP Internal Core API v1.1 : update data stream functions

- lib/libutee/tee_api_objects.c
> GP11 : TEE_OpenPersistentObject panic reason

- lib/libutee/tee_api_objects.c
> GP11: po enum functions panic reason

- lib/libutee/tee_api_operations.c
> GP11 : TEE_AllocateOperation panic reason

- lib/libutee/tee_api_operations.c
> GP11 : TEE_FreeOperation panic reason

- lib/libutee/tee_api_operations.c
> GP11 : TEE_ResetOperation panic reason

- lib/libutee/tee_api_operations.c
> GP11 : TEE_SetOperationKey/2 panic reason

- lib/libutee/tee_api_operations.c
> GP11 : Message digest functions panic reason

- lib/libutee/tee_api_operations.c
> GP11 : Symmetric cipher functions panic reason

- lib/libutee/include/tee_api.h
- lib/libutee/tee_api_operations.c
> GP11 : MAC functions fix/panic reason

- core/drivers/pl011.c
Enables Receive Timeout interrupt when initializing a PL011 uart. This
will generate an interrupt very soon after each key press in the
terminal.
> core pl011: enable RT interrupt

- lib/libutee/include/tee_api.h
- lib/libutee/tee_api_operations.c
> GP11 : AE functions fix/panic reason

- core/lib/libtomcrypt/src/tee_ltc_provider.c
- lib/libutee/include/tee_api.h
- lib/libutee/tee_api_operations.c
> GP11 : Asymmetric functions fix/panic reason

- lib/libutee/tee_api_operations.c
> GP11 : Key derivation function fix

- core/include/tee/tee_cryp_provider.h
- core/lib/libtomcrypt/src/tee_ltc_provider.c
- core/sta/ecc_self_tests.c
> ECC: DH implementation and self tests

- scripts/setup_mtk_optee.sh
Signed-off-by: James Kung <james.kung@linaro.org>
Tested-by: James Kung <james.kung@linaro.org> (MT8173 EVB)
> Updating setup_mtk_optee.sh to use public optee_test repository

- core/tee/tee_svc.c
- lib/libutee/tee_api.c
> GP11 : Time functions fix/panic reason

- lib/libutee/include/tee_api.h
- lib/libutee/tee_api_arith.c
> GP11 : TEE Arithmetical API fix/panic reason

- core/sta/ecc_self_tests.c
- core/tee/tee_svc_cryp.c
- lib/libutee/include/tee_api_defines.h
- lib/libutee/include/utee_defines.h
> ECC: ECDSA at GP level

- core/tee/tee_svc_cryp.c
> ECC: ECDH at GP level

- core/lib/libtomcrypt/src/tee_ltc_provider.c
In order to check that all temporary variables, used in
acipher computation, are correctly released,
tee_ltc_acipher_postactions() has been added. It raises
an assert in case some temporary variables have not
been released.
> Add Post-Actions on acipher crypto algorithms

- core/include/tee/tee_cryp_provider.h
- core/lib/libtomcrypt/src/mpa_desc.c
- core/lib/libtomcrypt/src/tee_ltc_provider.c
- core/tee/tee_cryp_concat_kdf.c
- core/tee/tee_cryp_hkdf.c
- core/tee/tee_cryp_pbkdf2.c
- lib/libmpa/include/mpalib.h
- lib/libmpa/mpa_debug.c
- lib/libmpa/mpa_io.c
> Optimize size

- lib/libutee/include/tee_api.h
- lib/libutee/tee_api_operations.c
> GP11 : TEE_GetOperationInfoMultiple

- .travis.yml
http://docs.travis-ci.com/user/migrating-from-legacy/
> Travis: migrate to new container-based infrastructure

- lib/libutee/tee_api_operations.c
As per GlobalPlatform Internal Core API Specification v1.1, section
6.3.2 TEE_DigestDoFinal: "Afterwards the Message Digest operation is
reset to initial state and can be reused".
> tee_svc_hash_final(): reset state before returning to caller

- core/include/kernel/tee_kta_trace.h
> Remove unused macro set/get ta_trace_level

- lib/libutee/include/tee_api.h
- lib/libutee/tee_api_operations.c
> GP11 : operation state handling

- core/kernel/tee_dispatch.c
Removing the malloc to handle the temporary copy
of the params in the tee_dispatch_open_session() function.
They are now allocated in the stack to be coherent with
the tee_dispatch_invoke_command case.
Signed-off-by: Jean-Michel Delorme <jean-michel.delorme@st.com>
> Removing the malloc to handle the temporary copy

- core/arch/arm/kernel/tee_ta_manager.c
- core/arch/arm/mm/tee_mmu.c
- core/include/mm/tee_mmu.h
- core/kernel/tee_dispatch.c
> Fix some types

- core/include/tee/tee_fs.h
- core/tee/tee_fs_common.c
- core/tee/tee_fs_private.h
Signed-off-by: James Kung <james.kung@linaro.org>
Tested-by: James Kung <james.kung@linaro.org> (QEMU, MT8173 EVB)
> Secure Storage: Support extending file size by truncate operation

- .travis.yml
- core/lib/libtomcrypt/src/sub.mk
- core/lib/libtomcrypt/sub.mk
- mk/checkconf.mk
- mk/lib.mk
> Travis: add 64-bit HiKey build

- LICENSE
- Notice.md
`Signed-off-by: Joakim Bech <joakim.bech@linaro.org>`
> Changing from old STM CLA to the new DCO

- core/include/tee/tee_fs.h
- core/include/tee/tee_fs_defs.h
- core/include/tee/tee_obj.h
- core/include/tee/tee_svc_storage.h
- core/tee/tee_fs.c
- core/tee/tee_fs_common.c
- core/tee/tee_fs_private.h
- core/tee/tee_obj.c
- core/tee/tee_svc_cryp.c
- core/tee/tee_svc_storage.c
- lib/libutee/tee_api_objects.c
- ta/ta.mk
Note: For testing, use optee_test branch dev/gp11_trusted_storage_verify
> GP11: trusted storage verify

- README.md
- Add development board suggestion information for community user
- Add Mediatek MT8173 link
> Add development board information

- CHANGELOG.md
> v1.0.0 Release Notes

- CHANGELOG.md
> CHANGELOG: add list of known issues

- core/tee/tee_fs_common.c
> Fix potential memory leak in File Storage

- core/sub.mk
> Remove useless core/mm directory

- core/arch/arm/kernel/tee_ta_manager.c
- core/include/tee/tee_cryp_provider.h
- core/lib/libtomcrypt/src/tee_ltc_provider.c
- core/tee/tee_svc_cryp.c
> Introduce free_rsa_public_key() and free_ecc_public_key()

- core/arch/arm/include/arm32.h
- core/arch/arm/include/mm/core_mmu.h
- core/arch/arm/mm/core_mmu_v7.c
- core/arch/arm/mm/tee_pager.c
> core/arm: trap access flag faults and fix FSR_FS_MASK

- core/arch/arm/include/kernel/tz_proc_def.h
- core/arch/arm/kernel/thread.c
- core/include/kernel/tee_ta_manager.h
- core/include/mm/tee_mm.h
- core/include/mm/tee_mmu_types.h
> Remove unused defines

- mk/checkconf.mk
> mk/checkconf.mk: Add optional reason text to the 'force' macro

- core/arch/arm/include/kernel/mutex.h
- core/arch/arm/include/kernel/thread.h
- core/arch/arm/include/kernel/wait_queue.h
- core/arch/arm/kernel/mutex.c
- core/arch/arm/kernel/tee_ta_manager.c
- core/arch/arm/kernel/thread.c
- core/arch/arm/kernel/wait_queue.c
- core/arch/arm/tee/arch_svc.c
- core/core.mk
- core/include/kernel/tee_ta_manager.h
- core/include/kernel/tee_ta_manager_unpg.h
- core/kernel/tee_dispatch.c
- core/lib/libtomcrypt/include/tomcrypt_custom.h
- core/lib/libtomcrypt/src/tee_ltc_provider.c
- core/tee/tee_svc.c
- lib/libmpa/include/mpalib.h
- lib/libmpa/mpa_mem_static.c
- lib/libutils/isoc/bget_malloc.c
Replaces #533
Addressed review comments and added review tags for reviewed patches.
> Remove big lock take 2

- core/tee/tee_fs_common.c
This is caused by forgetting to store the backup_version of
meta file in open_meta_file(). The backup_version field is
random and this may generate two versions of meta file in TEE
file folder at commit time.
Unfortunately, we didn't handle this case well in tee_fs_common_rename().
If we have two meta files in TEE file folder, one buffer
created by strdup() will leak. It's hard to handle this case
elegantly in current implementation, so we just put an assert here.
We will propose a new design to address this issue later.
Tested-by: SY Chiu <sy.chiu@linaro.org> (QEMU, MT8173 EVB)
> Secure Storage: resolve memory leakage issue

- .travis.yml
- core/tee/tee_fs_common.c
- core/tee/tee_fs_private.h
- mk/config.mk
This patch increases the byte-by-byte read speed
> Secure Storage: implement block cache

- core/arch/arm/kernel/tee_time_ree.c
> Add mutex on time

- core/arch/arm/kernel/tee_ta_manager.c
> Fix tee_ta_rpc_load in case of out of memory

- core/arch/arm/mm/tee_mmu.c
> arm: bugfix compile error in tee_mmu_map()

- core/arch/arm/kernel/thread_a64.S
- core/arch/arm/kernel/thread_private.h
Some cleanup and optimization of arm64 assembly code.
> A64 cleanup

- documentation/optee_design.md
Documents how the different stacks are used, both in ARMv7/Aarch32 and
Aarch64.
> Document the different stacks

- .travis.yml
> Travis: fix typos (s/CFS_BLOCK_CACHE/CFG_BLOCK_CACHE)

- .travis.yml
- core/arch/arm/mm/tee_mm.c
- core/arch/arm/sta/stats.c
- core/include/mm/tee_mm.h
- lib/libutils/isoc/bget_malloc.c
> Stats on allocation

- core/tee/tee_fs_common.c
Following is the issue description:
If we failed to create meta file while creating a new persistent
object. We will leave a empty tee folder in ree filesystem.
Next time when we want to create tee file when the same object id,
it will fail because the folder is already existed.
The patch solves this issue by checking if meta file is existed,
instead of just checking if the folder is existed.
Tested-by: SY Chiu <sy.chiu@linaro.org> (MT8173)
> Addressed the problem mentioned in issue#554

- README.md
> FSL-LS1021A platform is publicly available

- core/arch/arm/include/kernel/static_ta.h
- core/arch/arm/include/kernel/user_ta.h
- core/arch/arm/kernel/kern.ld.S
- core/arch/arm/kernel/link.mk
- core/arch/arm/kernel/static_ta.c
- core/arch/arm/kernel/sub.mk
- core/arch/arm/kernel/tee_ta_manager.c
- core/arch/arm/kernel/user_ta.c
- core/arch/arm/mm/tee_mmu.c
- core/include/keep.h
- core/include/kernel/tee_ta_manager_unpg.h
- core/include/mm/tee_mmu.h
- core/include/tee/tee_obj.h
- core/include/tee/tee_svc_cryp.h
- core/include/tee/tee_svc_storage.h
- core/tee/se/service.c
- core/tee/se/svc.c
- core/tee/tee_obj.c
- core/tee/tee_svc.c
- core/tee/tee_svc_cryp.c
- core/tee/tee_svc_storage.c
- lib/libutils/ext/include/compiler.h
- lib/libutils/ext/include/util.h
Breakout initial commits of https://github.com/OP-TEE/optee_os/pull/592 with review comments addressed.
> Refactor ta man2

- core/tee/tee_fs_key_manager.c
Suggested-by: Collin Elhossari <collin.elhossari@gmail.com>
> Fix final step in SSK generation

- documentation/secure_storage_rpmb.md
> Add RPMB documentation

- core/lib/libtomcrypt/src/mpa_desc.c
> libtomcrypt: mpa_desc.c: check return status of allocations

- core/arch/arm/kernel/user_ta.c
Suggested-by: Jason Lin <Jason.Lin@microsoft.com>
Suggested-by: Paul Swan <Paul.Swan@microsoft.com>
> Validate the TA signed header's img_size

- README.md
> ARM Juno GP testsuite support note

- CHANGELOG.md
- core/arch/arm/plat-imx/platform_config.h
- core/arch/arm/plat-ls/platform_config.h
- core/arch/arm/plat-mediatek/platform_config.h
- core/arch/arm/plat-sunxi/platform_config.h
- core/arch/arm/plat-ti/platform_config.h
- mk/config.mk
> Release Notes 2.0.0

- CHANGELOG.md
> plat-ls: tested with Release 2.0.0

- core/arch/arm/kernel/elf_load.c
- lib/libutils/isoc/include/stdint.h
Suggested-by: Jason Lin <Jason.Lin@microsoft.com>
Suggested-by: Paul Swan <Paul.Swan@microsoft.com>
> Fix potential memory corruptions in elf_load.c when loading TAs

- .travis.yml
- core/arch/arm/include/kernel/thread.h
- core/arch/arm/include/mm/core_mmu.h
- core/arch/arm/include/mm/pgt_cache.h
- core/arch/arm/kernel/thread.c
- core/arch/arm/kernel/thread_private.h
- core/arch/arm/mm/core_mmu.c
- core/arch/arm/mm/core_mmu_lpae.c
- core/arch/arm/mm/core_mmu_private.h
- core/arch/arm/mm/core_mmu_v7.c
- core/arch/arm/mm/pgt_cache.c
- core/arch/arm/mm/sub.mk
- core/arch/arm/mm/tee_mmu.c
- lib/libutils/ext/arch/arm/atomic_a32.S
- lib/libutils/ext/arch/arm/atomic_a64.S
- lib/libutils/ext/arch/arm/sub.mk
- lib/libutils/ext/include/atomic.h
- lib/libutils/ext/sub.mk
- mk/config.mk
The first two patches from https://github.com/OP-TEE/optee_os/pull/689
> 4kta part 1

- core/arch/arm/mm/core_mmu_lpae.c
- core/arch/arm/mm/core_mmu_v7.c
- core/arch/arm/mm/tee_pager.c
- core/include/mm/tee_mmu_types.h
Some small preparations for read write paging
> Pager misc

- core/arch/arm/kernel/tee_ta_manager.c
- core/include/mm/tee_mmu_types.h
- core/tee/tee_svc.c
Bugfixes related to calling static TA from a user TA
> Bugfix calling static TA

- lib/libutee/abort.c
- lib/libutee/include/utee_defines.h
- lib/libutils/ext/include/compiler.h
- lib/libutils/isoc/arch/arm/setjmp_a32.S
- lib/libutils/isoc/arch/arm/setjmp_a64.S
- lib/libutils/isoc/arch/arm/sub.mk
- lib/libutils/isoc/include/setjmp.h
- lib/libutils/isoc/include/stdlib.h
- lib/libutils/isoc/newlib/abs.c
- lib/libutils/isoc/newlib/sub.mk
- ta/ta.mk
Some utilities needed by coming TUI and read-write paging patches.
> Misc utils

- core/tee/tee_svc_storage.c
- lib/libutee/tee_api_objects.c
Fix https://github.com/OP-TEE/optee_os/issues/745
Fix https://github.com/OP-TEE/optee_test/pull/82
> Persistant

- .travis.yml
- core/include/tee/tee_fs.h
- core/include/tee/tee_pobj.h
- core/tee/sub.mk
- core/tee/tee_obj.c
- core/tee/tee_pobj.c
- core/tee/tee_ree_fs.c
- core/tee/tee_rpmb_fs.c
- core/tee/tee_svc_storage.c
- documentation/secure_storage.md
- documentation/secure_storage_rpmb.md
- lib/libutee/include/tee_api_defines_extensions.h
- mk/config.mk
Note: first commit is PR https://github.com/OP-TEE/optee_os/pull/741, please review the second commit.
> Dual FS support

- .travis.yml
> Update travis for gcc5

- core/tee/tee_rpmb_fs.c
- core/tee/tee_svc_cryp.c
- core/tee/tee_svc_storage.c
Fixes https://github.com/OP-TEE/optee_os/issues/840
> Fixes for issue 840

- README.md
It fixes #822 (ramdisk.img size)
Signed-off-by: Miraje Gentilal <miraje.gentilal@hotmail.com>
> ARM Juno GCC5 support note.

- lib/libutee/tui/image_png.c
Fixes https://github.com/OP-TEE/optee_os/issues/848.
> tui: Add __unused

- README.md
> README.md: Add warning for GCC4.9 to GCC5 upgrade

- .travis.yml
- MAINTAINERS.md
- README.md
- core/arch/arm/plat-sprd/conf.mk
- core/arch/arm/plat-sprd/console.c
- core/arch/arm/plat-sprd/kern.ld.S
- core/arch/arm/plat-sprd/link.mk
- core/arch/arm/plat-sprd/main.c
- core/arch/arm/plat-sprd/platform_config.h
- core/arch/arm/plat-sprd/sub.mk
- core/drivers/sprd_uart.c
- core/drivers/sub.mk
- core/include/drivers/sprd_uart.h
Signed-off-by: Aijun Sun <aijun.sun@spreadtrum.com>
> Add support for Spreadtrum SC9860(alias whale2) board

- CHANGELOG.md
- mk/config.mk
> Release Notes of 2.1.0

- core/arch/arm/kernel/generic_boot.c
- core/arch/arm/tee/init.c
Demote a pager message from EMSG to IMSG and reformat it. Also
reformat the end of initialization message.
> Update initialization messages

- README.md
- documentation/rpi3.md
Depends on https://github.com/OP-TEE/manifest/pull/33
> rpi3: Add documentation for Raspberry Pi 3

- core/arch/arm/kernel/thread.c
thread_rpc_alloc_arg() and thread_rpc_alloc_payload() only succeeds if
the allocated shared memory is valid shared memory.
> core: rpc alloc check memory is valid

- .travis.yml
- README.md
- core/arch/arm/plat-d02/conf.mk
- core/arch/arm/plat-d02/kern.ld.S
- core/arch/arm/plat-d02/link.mk
- core/arch/arm/plat-d02/main.c
- core/arch/arm/plat-d02/platform_config.h
- core/arch/arm/plat-d02/sub.mk
- core/drivers/hi16xx_uart.c
- core/drivers/sub.mk
- core/include/drivers/hi16xx_uart.h
This PR adds support for the HiSilicon D02 board.
> HiSilicon D02 port

- core/arch/arm/plat-hikey/main.c
- core/arch/arm/plat-imx/main.c
- core/arch/arm/plat-ls/main.c
- core/arch/arm/plat-mediatek/main.c
- core/arch/arm/plat-ti/main.c
- core/arch/arm/plat-vexpress/main.c
- core/arch/arm/plat-zynqmp/main.c
> Fix reversed order of carriage return and line feed..

- core/tee/tee_rpmb_fs.c
In rpmb_fs_write(), if other session write RPMB between read_fat() and
tee_rpmb_write(), it may write to the same address. So move rpmb_mutex
to fs layer for concurrency scenarios.
Signed-off-by: Lijianhui (Airbak) <airbak.li@hisilicon.com>
[Removed tee_rpmb_read_unlocked(), unlock earlier on a few locations]
> rpmb: move rpmb_mutex to fs layer

- core/tee/tee_sql_fs.c
There is no need to actually allocate a buffer filled with zeroes in
sql_fs_ftruncate(). Instead, update write_block_partial() so that a
NULL data pointer means all null bytes. This eliminates a large (4K)
temporary allocation.
> storage: sqlfs: save memory when sql_fs_ftruncate() extends a file

- core/arch/arm/plat-rpi3/conf.mk
- core/arch/arm/plat-rpi3/kern.ld.S
- core/arch/arm/plat-rpi3/link.mk
- core/arch/arm/plat-rpi3/main.c
- core/arch/arm/plat-rpi3/platform_config.h
- core/arch/arm/plat-rpi3/sub.mk
This is the patch I received from Philip, I've more or less just applied and rebased it.
> plat-rpi3: Merge support for RPi3 to OP-TEEs master branch

- ta/ta.mk
> ta-dev-kit: Remove use of platform_flags.mk

- .travis.yml
> travis: Add RPi3 target

- MAINTAINERS.md
> Add maintainers for D02 and Raspberry Pi3

- README.md
Depends on https://github.com/OP-TEE/manifest/pull/37
> rpi3: refer to new xml-files in documentation

- CHANGELOG.md
> Update CHANGELOG.md for 2.2.0

- core/kernel/panic.c
> core: add unwind stack in panic

- core/arch/arm/include/kernel/thread.h
- core/arch/arm/kernel/thread.c
- core/include/optee_msg_fs.h
- core/include/tee/tee_fs_rpc.h
- core/tee/tee_fs_rpc.c
- core/tee/tee_ree_fs.c
- core/tee/tee_sql_fs.c
Adds new RPC functions for secure storage and starts to use some of them.
Depends on https://github.com/OP-TEE/optee_client/pull/58
> New secure storage RPC functions

- .travis.yml
- scripts/checkpatch.sh
- scripts/checkpatch_inc.sh
Add auxiliary wrapper for convenient check of commit/
changes in staging area/multiple commits with checkpatch.pl
> scripts: add wrapper script for checkpatch

- core/arch/arm/kernel/generic_boot.c
- core/arch/arm/kernel/generic_entry_a32.S
- core/arch/arm/plat-stm/platform_config.h
A fix pager support for armv7.
A fix for PL310 operations during generic boot.
Enable support of pager TEE on plat-stm.
> Fix ARMv7 generic boot against SMP & pager, support pager in plat-stm

- core/arch/arm/kernel/generic_boot.c
- core/arch/arm/mm/tee_pager.c
Picks up the patch from https://github.com/OP-TEE/optee_os/issues/1153 and also fixes another pager issue.
> Pager fixes

- .travis.yml
> .travis.yml: Add Coverity addon

- core/tee/tee_svc_cryp.c
- lib/libutee/tee_api_objects.c
- lib/libutee/tee_api_operations.c
> Coverity fixes

- core/arch/arm/plat-hikey/conf.mk
- core/arch/arm/plat-hikey/hikey_peripherals.h
- core/arch/arm/plat-hikey/main.c
- core/arch/arm/plat-hikey/spi_test.c
- core/arch/arm/plat-hikey/sub.mk
- core/drivers/pl022_spi.c
Tested-by: Victor Chong <victor.chong@linaro.org> (with CFG_SPI_TEST=y)
> hikey: enable spi by default and add sample test code

- README.md
> README: Update outdated text and link

- core/arch/arm/include/kernel/tz_ssvce_def.h
- core/arch/arm/kernel/tz_ssvce_pl310_a32.S
Get number of ways from the PL310 configuration AUX_CTRL[bit#16].
Can someone test on imx ?
> fix for 16-way pl310 

- core/arch/arm/include/mm/core_mmu.h
- core/arch/arm/include/mm/tee_pager.h
- core/arch/arm/kernel/user_ta.c
- core/arch/arm/mm/core_mmu_lpae.c
- core/arch/arm/mm/core_mmu_v7.c
- core/arch/arm/mm/pgt_cache.c
- core/arch/arm/mm/tee_pager.c
- core/tee/tee_pobj.c
Some preparations for paged secure shared memory and some random stuff.
> Misc small changes and fixes

- README.md
> docs: Add build-essential to prerequisites

- documentation/secure_storage.md
- documentation/secure_storage_rpmb.md
Signed-off-by: Andy Green <andy@warmcat.com>
Re: https://github.com/OP-TEE/optee_os/issues/1259
> docs: remove crufty references to removed CFG_ENC_FS

- documentation/secure_storage.md
> docs: secure storage: make clear it is insecure by default

- README.md
> docs: Add ftp-upload to prerequisites

- mk/config.mk
> mk: step up OP-TEE revsion to 2.3.0

- CHANGELOG.md
Update change log, preparing for release 2.3.0.
> Update CHANGELOG.md for 2.3.0

- core/arch/arm/kernel/static_ta.c
- core/arch/arm/mm/mobj.c
Problems discovered while testing the GP socket stuff.
> Mobj bugfix

- core/arch/arm/kernel/user_ta.c
- core/arch/arm/mm/tee_pager.c
Prior to this patch the entire TA code was dcache cleaned and icache invalided
resulting in many unneeded paged faults when the pager is enabled.
With this patch the pager is taken into account. When pager is enabled
only clean dcache and invalide icache for mapped pages.
Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (HiKey)
> core: optimize cache handling in load_elf_segments()

- core/lib/libtomcrypt/src/mpa_desc.c
- core/tee/uuid.c
- lib/libmpa/mpa_shift.c
Fixes errors discovered with CFG_CORE_SANITIZE_UNDEFINED=y
> CFG_CORE_SANITIZE_UNDEFINED=y fixes

- core/arch/arm/kernel/link.mk
- core/arch/arm/mm/mobj.c
- core/arch/arm/mm/pgt_cache.c
- core/arch/arm/mm/tee_mmu.c
- core/arch/arm/mm/tee_pager.c
Fixes https://github.com/OP-TEE/optee_os/issues/1323 (hopefully)
> Secshm fix

- core/arch/arm/plat-ti/conf.mk
- core/arch/arm/plat-ti/platform_config.h
- core/drivers/dra7_rng.c
- core/drivers/sub.mk
- lib/libutils/ext/include/util.h
Add driver for the True Random Number Generator (TRNG) available
on DRA7xx platforms.
> drivers: Add TRNG driver for DRA7

- core/arch/arm/include/kernel/thread.h
- core/arch/arm/kernel/user_ta.c
- core/arch/arm/tee/pta_socket.c
- core/arch/arm/tee/sub.mk
- core/include/kernel/tee_ta_manager.h
- core/include/optee_msg_supplicant.h
- lib/libutee/include/__tee_ipsocket.h
- lib/libutee/include/__tee_isocket_defines.h
- lib/libutee/include/__tee_tcpsocket_defines.h
- lib/libutee/include/__tee_tcpsocket_defines_extensions.h
- lib/libutee/include/__tee_udpsocket_defines.h
- lib/libutee/include/pta_socket.h
- lib/libutee/include/tee_isocket.h
- lib/libutee/include/tee_tcpsocket.h
- lib/libutee/include/tee_udpsocket.h
- lib/libutee/sub.mk
- lib/libutee/tee_api_property.c
- lib/libutee/tee_socket_private.h
- lib/libutee/tee_socket_pta.c
- lib/libutee/tee_tcpudp_socket.c
- mk/config.mk
Depends on https://github.com/OP-TEE/optee_client/pull/74
> Gp socket support

- scripts/checkpatch.sh
If several commit IDs are passed to the script, process them in order.
This helps check several commits in a development branch, for instance:
./scripts/checkpatch.sh `git rev-list master..HEAD`
> checkpatch.sh: accept several commits

- core/arch/arm/include/mm/core_memprot.h
- core/arch/arm/mm/mobj.c
Issue found as part of https://github.com/OP-TEE/optee_os/pull/1348
> core: fix inconsistency in mobj and memory attributes handling 

- mk/config.mk
> Remove unused CFG_REE_FS_BLOCK_CACHE

- core/arch/arm/plat-vexpress/platform_config.h
qemu_armv8 reserves the first 1Mbyte of secure RAM to the ARM-TF.
This change fixes the regression introduced by df05d4ea7d58
that assigned back this 1Mbyte to OP-TEE or SDP memory.
Move SDP test memory pool to the end of the QEMU secure RAM.
Testing SDP on QEMU ARMv7 and ARMv8 now requires https://github.com/OP-TEE/build/pull/133 and https://github.com/linaro-swg/bios_qemu_tz_arm/pull/11
> plat-vexpress: fix secure RAM layout

- documentation/porting_guidelines.md
I think this is a good start for porting guidelines. I'm absolutely sure that there are more things to add and to clarify, but as written here, it at least let the reader know what he or she needs to do when considering creating a real product.
> Create Porting Guidelines

- core/include/tee/tee_fs.h
- core/tee/tee_obj.c
- core/tee/tee_ree_fs.c
- core/tee/tee_rpmb_fs.c
- core/tee/tee_sql_fs.c
- core/tee/tee_svc_storage.c
Needs https://github.com/OP-TEE/optee_test/pull/199 for tests to pass.
> Rearrange FOP->create

- .travis.yml
- MAINTAINERS.md
- README.md
- core/arch/arm/plat-ti/api_monitor_index_a15.h
- core/arch/arm/plat-ti/api_monitor_index_a9.h
- core/arch/arm/plat-ti/conf.mk
- core/arch/arm/plat-ti/main.c
- core/arch/arm/plat-ti/platform_config.h
- core/arch/arm/plat-ti/sm_platform_handler_a15.c
- core/arch/arm/plat-ti/sm_platform_handler_a9.c
- core/arch/arm/plat-ti/sub.mk
- core/arch/arm/plat-ti/ti_pl310.c
- scripts/checkpatch_inc.sh
The AM43xx family includes high-performance processors based on the ARM Cortex-A9 core. Secure targeted application include Portable Data Terminal and Electronic Point of Sale equipment. The first patch in this series is pushed here: #1455
> Add support for the TI AM43xx platform

- core/arch/arm/pta/core_fs_htree_tests.c
- core/include/tee/fs_dirfile.h
- core/include/tee/fs_htree.h
- core/include/tee/tee_fs_key_manager.h
- core/include/tee/tee_fs_rpc.h
- core/include/tee/tee_svc_storage.h
- core/tee/fs_dirfile.c
- core/tee/fs_htree.c
- core/tee/sub.mk
- core/tee/tee_fs_key_manager.c
- core/tee/tee_fs_rpc.c
- core/tee/tee_ree_fs.c
- core/tee/tee_rpmb_fs.c
- core/tee/tee_sql_fs.c
- core/tee/tee_svc_storage.c
Depends on https://github.com/OP-TEE/optee_test/pull/202 for tests to pass
> Introduce new dirfile interface

- core/arch/arm/kernel/thread.c
Delays the RPC arg data allocation until it's needed to avoid doing RPC
when the caller in normal world isn't prepared to handle it.
Should fix https://github.com/OP-TEE/optee_os/issues/1401
> core: thread: allocate RPC arg data on demand

- core/arch/arm/include/mm/core_mmu.h
- core/arch/arm/mm/core_mmu.c
- core/arch/arm/mm/core_mmu_lpae.c
- core/arch/arm/mm/core_mmu_v7.c
This function allows to map list of physical pages to specified virtual
memory address.
> core_mmu: add page map/unmap functions

- Notice.md
> Notice.md: improve description of the sign-off tag

- README.md
> doc: minor: add TI AM57xx to supported platforms

- lib/libutee/tee_api_operations.c
GCM mode of AES algorithm is essentially a stream cipher. It means
that there is no requirements for input data size related to block
size. And every time when AEUpdate is called input data must be
processed and output immediately generated. That is why
it is incorrect to apply for AES GCM the input buffering on
AEUpdate call when size is not multiple of block size.
Signed-off-by: Bogdan Liulko <bogdan.liulko@globallogic.com>
> libutee: Remove buffering for AES GCM

- core/arch/arm/mm/mobj.c
When core needs to validate content before it is used, core must first
move the data in secure memory, then validate it (or not), then access
validated data from secure memory only, not from original shared memory
location.
This change fixes mobj_reg_shm_alloc() so that it checks the validity
of the registered reference after the references are copied into the
secure memory.
This change fixes mobj_mapped_shm_alloc() to use the shm buffer reference
instead of the initial description still located in shared memory.
> core: fix weakness in shm registration

- core/arch/arm/plat-hikey/platform_config.h
> plat-hikey: enable 64-bit paging

- README.md
> README.md: give full PLAFORM string for i.MX6 boards

- core/arch/arm/kernel/mutex.c
cpu_spin_lock_xsave/cpu_spin_unlock_xrestore could be used
to simplify the code.
in __condvar_wait,
```
cpu_spin_unlock(&cv->spin_lock);
cpu_spin_lock(&m->spin_lock);
```
are also replaced with 
```
cpu_spin_unlock_xrestore(&cv->spin_lock, old_itr_status);
old_itr_status = cpu_spin_lock_xsave(&m->spin_lock);
```
> core: arm: mutex: simplify code with xsave/xrestore spin lock

- core/arch/arm/mm/tee_pager.c
When a normal thread takes the pager lock there must be no page faults
while the lock is held. This is has so far been ensured by feeding the
function to the KEEP_PAGER() macro, but this will only take care of the
actual code not stack usage. This patch introduces a new pager lock
function, pager_lock_check_stack() which will make sure that the
estimated needed stack is mapped before the lock is acquired.
> core: pager: avoid page faults with pager lock held

- ta/ta.mk
Add scripts/symbolize.py to the TA dev kit (+ some cleanup).
> Add scripts/symbolize.py to TA dev kit

- core/arch/arm/kernel/generic_boot.c
core: fix overlapping conditions of pagestore load areas
This change copies pagestore remaining part first, from any location to
its target destination before copying pagestore init part to target
destination. This prevents pagestore init copy to corrupt pagestore
remaining part at the location where bootloader loaded it.
As bootloader can load pagestore data anywhere in RAM, it is possible
that it loads it into an area overlapping with the area allocated by
the core to store effective pagestore. To prevent this, use memmove()
to copy the data instead of memcpy().
> core: fix overlapping conditions of pagestore load areas

- README.md
> README.md: fix URLs to HiKey and HiKey960

- core/tee/tee_ree_fs.c
Fixes problem in put_dirh_primitive() when another concurrent has
detected an error and thus closed ree_fs_dirh as a part of error
recovery.
Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (QEMU v8)
> core: REE FS: bugfix error path

- documentation/porting_guidelines.md
ARM64 supports pager. Update the doc accordingly.
Reported by @kevin-peng-hao. Thanks :)
> docs: update porting guidelines regarding pager support

- core/arch/arm/kernel/generic_boot.c
- core/arch/arm/mm/core_mmu_v7.c
Two small patches. Code inspection.
> Misc mmu patch

- core/drivers/pl011.c
It may happen that trace functions are called by OP-TEE when the UART
is disabled by the non-secure OS. In such a case, putc() or flush() are
likely to loop indefinitely, because the UART status register may never
contain the expected value.
Make the code more robust by limiting the loop count. By doing so, we
allow to drop some output rather than hanging the whole system.
Fixes: https://github.com/OP-TEE/optee_os/issues/1863
> pl011: prevent putc() and flush() function from blocking indefinitely

- core/arch/arm/kernel/abort.c
It is perfectly safe to run the call stack unwinding code on a paged TA
as long as we're not processing an abort. Adjust __abort_print()
accordingly.
Prior to this patch, the call stack was missing from TA panics if pager
was enabled.
> pager: allow TA unwind when cause of unwind is not abort

- core/arch/arm/tee/arch_svc.c
This change checks that the userland context pointer is valid before
reading its content.
Note that this change only lowers the chance of malformed TA being
able to crash core or access core memory using crafted context
reference. The stack unwind process being executed from kernel land,
a real fix could require each stack unwind step to verify the memory
references before going further in the execution history.
Therefore this change does not fix the vulnerability of current
TA stack unwind process against core/TA isolation.
> core:unwind: check user context on stack print of panicked TAs

- CHANGELOG.md
> Update CHANGELOG.md for 2.6.0

- core/tee/tee_ree_fs.c
correct the file layout comment in the file. add some comments for better understanding.
issue #1894
> Fix comment in tee_ree_fs.c

- core/arch/arm/include/sm/optee_smc.h
- core/arch/arm/tee/entry_fast.c
- core/arch/arm/tee/sub.mk
- mk/config.mk
> Os rev git sha1

- core/arch/arm/kernel/vfp_a32.S
- core/arch/arm/plat-d02/conf.mk
- core/arch/arm/plat-hikey/conf.mk
- core/arch/arm/plat-imx/conf.mk
- core/arch/arm/plat-ls/conf.mk
- core/arch/arm/plat-marvell/conf.mk
- core/arch/arm/plat-mediatek/conf.mk
- core/arch/arm/plat-rcar/conf.mk
- core/arch/arm/plat-rockchip/conf.mk
- core/arch/arm/plat-rpi3/conf.mk
- core/arch/arm/plat-sam/conf.mk
- core/arch/arm/plat-sprd/conf.mk
- core/arch/arm/plat-stm/conf.mk
- core/arch/arm/plat-sunxi/conf.mk
- core/arch/arm/plat-ti/conf.mk
- core/arch/arm/plat-vexpress/conf.mk
- core/arch/arm/plat-zynq7k/conf.mk
- core/arch/arm/plat-zynqmp/conf.mk
- documentation/porting_guidelines.md
> .fpu neon rather than -mfpu=neon

- core/arch/arm/pta/core_fs_htree_tests.c
Adds negative test for htree.
These tests are intended to replace the entire regression_9xxx family in xtest. 
With this I believe that coverage is increased slightly and the tests themselves are more robust.
> core: add negative tests for htree

- documentation/optee_design.md
Document early TAs introduced by commit d0c636148b3a ("Add support for
early Trusted Applications") and slightly rework the section about normal
TAs.
> Document early TAs

- documentation/optee_design.md
Documentation for https://github.com/OP-TEE/optee_os/pull/1928
> Doc bootstrap ta

- core/arch/arm/mm/tee_mm.c
- Remove double #include <mm/tee_mm.h>
- Put includes into alphabetical order
> tee_mm.c: fix includes section

- lib/libutee/arch/arm/user_ta_entry.c
Fixes issues observed with keep alive single instance TAs:
- TA_CreateEntryPoint() must only be called once,
- TA_DestroyEntryPoint() must not be called when the last session is
closed, because the instance is still alive.
While we're at it, simplify the code a bit by not using a separate
variable (ta_ref_count) to track whether we have sessions or not.
Simply use TAILQ_EMPTY() on the session queue instead.
> libutee: fix TA_CreateEntryPoint() and TA_DestroyEntryPoint()

- core/arch/arm/include/arm32_macros.S
> Asm macros

- core/arch/arm/mm/core_mmu_lpae.c
core_mmu_find_table() calls get_core_pos() so it should mask interrupts
to avoid being re-scheduled to another core.
> core: lpae: mask exceptions during core_mmu_find_table()

- core/arch/arm/sm/sm_a32.S
> Secure monitor spectre updates

- core/arch/arm/include/mm/core_mmu.h
- lib/libutils/ext/include/util.h
> register_sdp_mem() fix

- CHANGELOG.md
> Update CHANGELOG.md for 3.0.0

- core/arch/arm/mm/tee_mmu.c
Protects the global ASID bitfield (g_asid) with a spinlock.
Fixes: 99f969dd6c99 ("core: fine grained tee_ta_mutex locking")
Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (Hikey)
> core: mmu: protect global asid field with a lock

- core/arch/arm/sm/sm_a32.S
> core: sm_a32: add missing isb after scr change

- core/core.mk
- mk/checkconf.mk
- ta/ta.mk
> Generate conf.cmake for TA dev kit

- core/tee/fs_htree.c
- core/tee/tee_cryp_hkdf.c
> Crypto fixes

- core/tee/tadb.c
When tee_tadb_ta_read() has advanced through the entire binary it should
call crypto_authenc_dec_final() to check that the computed tag matches
expected tag. Before this commit that wasn't done.
> core: bugfix tee_tadb_ta_read()

- documentation/copyright_and_license_headers.rst
> Add "no license notice" rule to the file header documentation

- core/lib/libtomcrypt/src/modes/ctr/ctr_encrypt.c
When accel_ctr_encrypt() is not used, accel_ecb_encrypt() is used via
ecb_encrypt() instead. The accel_ecb_encrypt() is frequently called at
every single block process. VFP assembly code called from the
accel_ecb_encrypt() is protected by
tomcrypt_arm_neon_enable()/disable(). FIQ enable/disable and VFP
register save/restore (64bitx32 registers!) to/from memory are done in
the tomcrypt_arm_neon_enable()/disable(). These overhead exist in each
single block process cause the degradation of system performance
eventually. Cases where h/w accelerated AES-CTR did not show any effects
or showed less performance than pure software processing have been
observed.
This patch resolves the issue by increasing utilization rate of
accel_ctr_encrypt().
Signed-off-by: Tetsuya Yoshizaki …
> ltc: ctr: improve performance

- documentation/porting_guidelines.md
Adds a note on the software PRNG weakness in the porting guidelines.
> doc: add a note on PRNG weakness

- README.md
Reported-by: Ohad Netz <ohad.netz@arm.com>
> README.md: fix broken link to MAINTAINERS file

- core/lib/libtomcrypt/src/tee_ltc_provider.c
- core/tee/tee_svc_cryp.c
- lib/libutee/include/tee_arith_internal.h
- lib/libutee/tee_api_arith.c
- lib/libutee/tee_api_property.c
- mk/config.mk
> 4096-bit RSA

- mk/config.mk
> Update revision for release tag 3.1.0-rc1

- core/core.mk
Allows for platform dependent implementations of exported crypto API
Signed-off-by: Darren Roche <darren.broche@gmail.com>
> crypto: Add support for generic platcrypt crypto library

- ta/mk/ta_dev_kit.mk
- ta/ta.mk
> Ta config file updates

- ta/mk/ta_dev_kit.mk
- ta/ta.mk
> Propagate selected CFG_ to TA environment

- core/lib/libtomcrypt/src/tee_ltc_provider.c
> Fix RSA/DSA/ECC signature verification return codes

- lib/libutils/isoc/include/ctype.h
> libutil: provide non-stubbed ctypes.h

- core/drivers/imx_wdog.c
> plat-imx: remove dependency on CFG_DT=y and fix reset on IMX7

- lib/libutils/isoc/bget_malloc.c
> Alloc fixes

- documentation/secure_storage.md
* Did some minor layout changes to the secure_storage.md file.
* Added more slides from linaro connect concerning this topic.
> doc: add slides concerning secure storage, fix layout

- core/arch/arm/kernel/user_ta.c
> Dynamically linked TAs: fix segment mapping

- core/arch/arm/mm/core_mmu.c
core_mmu_(un)map_pages() functions can be called in multiple threads
simultaneously and there is no protection against races.
This patch adds spinlock that ensures that only one core will alter
pagetables at a time.
--- 
This patch fixes the first part of #2327
> mmu: add locking for OP-TEE address space manipulation

- core/arch/arm/kernel/elf_common.h
- core/arch/arm/kernel/elf_load.c
- core/arch/arm/kernel/elf_load_dyn.c
- core/arch/arm/kernel/elf_load_dyn.h
- core/arch/arm/kernel/elf_load_private.h
> TA dynamic link (arm64)

- .shippable.yml
- MAINTAINERS
- README.md
- core/arch/arm/plat-synquacer/conf.mk
- core/arch/arm/plat-synquacer/main.c
- core/arch/arm/plat-synquacer/platform_config.h
- core/arch/arm/plat-synquacer/sub.mk
> synquacer: Add DeveloperBox platform support

- scripts/symbolize.py
Show which file corresponds to each ELF binary in a TA. Symbolic links
are followed, so that dynamic libraries are likely shown with their
user-friendly name (libfoo.so) rather than their UUID (<uuid>.elf) --
see commit 01b8b5ce011d ("TA dev kit: when building a shared library,
create symlink with UUID").
> scripts/symbolize.py: print path of ELF files

- ta/ta.mk
Allows a TA to determine at build time if the targeted OP-TEE supports
run time dynamic linking.
> ta/ta.mk: export CFG_TA_DYNLINK

- core/arch/arm/kernel/user_ta.c
Function `is_user_ta_ctx()` is used by unpaged code. Prior this change,
the whole `user_ta_ops` structure fell into unpaged sections. This change
decreases the unpaged size by several tenths of kB.
Below are extracts from mem_usage.py output on qemu_armv8 with
`CFG_WITH_PAGER=y` and `CFG_TEE_CORE_DEBUG=n`. Check the size of sections
.text and .rodata.
- Before the change:
```
RAM Usage        0E100000 - 0E166000 size 00066000 408 KiB 102 pages
.text            0E100000 - 0E1151E8 size 000151E8  84 KiB
.rodata          0E1151E8 - 0E117BD8 size 000029F0  10 KiB
*hole*           0E117BD8 - 0E118000 size 00000428   1 KiB
.data            0E118000 - 0E11A280 size 00002280   8 KiB
.bss             0E11A280 - 0E11CBD8 size 00002958  10 KiB
.heap1           0E11CBD8 - 0E120000 size 00003428  13 …
```
> core: prevent user_ta resource to be unpaged

- core/include/kernel/tee_ta_manager.h
- core/kernel/tee_ta_manager.c
> tee_ta_manager: remove unused function tee_ta_get_client_id()

- .shippable.yml
- MAINTAINERS
- core/arch/arm/include/kernel/delay.h
- core/arch/arm/include/kernel/tz_ssvce_def.h
- core/arch/arm/kernel/delay.c
- core/arch/arm/plat-sunxi/conf.mk
- core/arch/arm/plat-sunxi/main.c
- core/arch/arm/plat-sunxi/plat_init.S
- core/arch/arm/plat-sunxi/platform_config.h
- core/arch/arm/plat-sunxi/psci.c
- core/arch/arm/plat-sunxi/sub.mk
- core/drivers/serial8250_uart.c
Hi,
I've porting optee for BananaPi0 board. Based on previous sunxi code and together with the AllWinner H3 documentation. Please review the code. 
Thanks.
> Adding plat-sunxi support for BananaPi0 board

- core/tee/tee_svc_cryp.c
objectSize/keySize was not getting updated when an ECDSA/ECDH
object was imported.
Updating the ObjectSize/keySize based on the EC Curve.
Fixes: https://github.com/OP-TEE/optee_os/issues/2386
> core: tee: update objectSize/keySize for ECDSA/ECDH Objects

- mk/config.mk
> Update revision for release tag 3.2.0-rc1

- documentation/crypto.md
Fixes: https://github.com/OP-TEE/optee_os/issues/2418
> Documentation: Fixing links in crypto doc

- core/arch/arm/include/arm64.h
- core/arch/arm/mm/core_mmu.c
- core/arch/arm/mm/core_mmu_lpae.c
- core/arch/arm/mm/core_mmu_private.h
> Max pa fix

- CHANGELOG.md
> Update CHANGELOG.md for 3.2.0

- MAINTAINERS
Signed-off-by: Tao Lu <taolu@marvell.com>
> MAINTAINERS: Change maintainer for Marvell Armada

- mk/aosp_optee.mk
to make it work with Treble enabled builds
Acked-by: Victor Chong <victor.chong@linaro.org>
Signed-off-by: Yongqin Liu <yongqin.liu@linaro.org>
> mk/aosp_optee.mk: move ta files to vendor partition

- core/arch/arm/sm/pm_a32.S
> sm: pm_a32: typo fix

- core/tee/tadb.c
Fixes a panic triggered in tee_tadb_ta_create(). Before this patch
tee_tadb_ta_create() was calling tadb_put() if tee_tadb_open() failed.
This is incorrect as the reference counter hasn't been increased then.
This patch fixes that by only calling tadb_put() once tee_tadb_open()
has succeeded.
> core: fix tee_tadb_ta_create() panic

- scripts/symbolize.py
> symbolize.py improvements

- core/arch/arm/plat-imx/pm/psci.c
Add psci features list for query. The list is based on
current implemented psci functions.
Signed-off-by: Jun Nie <jun.nie@linaro.org>
> core: arm: imx: Support psci feature query

- mk/cleanvars.mk
- ta/arch/arm/link.mk
> mk: cleanvars.mk/link.mk: multiple fixes

- core/arch/arm/include/mm/mobj.h
- core/arch/arm/mm/mobj.c
- core/arch/arm/tee/entry_std.c
> Shm ref count

- core/include/optee_msg.h
OPTEE_MSG_ATTR_FRAGMENT isn't defined. Remove it from comments and replace
with OPTEE_MSG_ATTR_NONCONTIG where applicable.
> optee_msg.h: remove OPTEE_MSG_ATTR_FRAGMENT

- scripts/symbolize.py
Document how the binutils tools (addr2line etc.) are found.
> scripts/symbolize.py: add help text

- core/arch/arm/kernel/abort.c
If an undefined instruction exception is raised from user mode assume it
is a VFP instruction unless VFP already is enabled.
This avoids reading user mode memory while handling an abort which until
now has kept an undiscovered race where a page could become inaccessible
before the abort handler had the chance to read the instruction from the
page.
There is room for false positives. Those will be discovered the next
time the instruction is executed and still causes an undefined
instruction exception. Only this time VFP is already enabled so we know
it's not a VFP instruction. Enabling VFP in vain like this is harmless.
> abort.c: arm32: assume VFP instr if undef

- CHANGELOG.md
> Changelog 3.3.0

- documentation/porting_guidelines.md
The first sentence was duplicated. Remove the repetition.
Set the correct meaning for second sentence.
Signed-off-by: Loys Ollivier <loys.ollivier@gmail.com>
> porting guide: misc sentence fix

- core/arch/arm/plat-imx/conf.mk
- core/drivers/imx_wdog.c
Add support for [Compulab IMX7 SOM](https://www.compulab.com/products/computer-on-modules/cl-som-imx7-freescale-i-mx-7-system-on-module/).
@neilsh-msft
> plat-imx: add mx7dclsom platform flavor

- core/arch/arm/plat-imx/conf.mk
Add support for [i.MX6SoloX Udoo Neo Full](https://shop.udoo.org/usa/neo/udoo-neo-full.html)
@christopherco
> plat-imx: Add i.MX6SoloX Udoo Neo Full platform flavor

- core/arch/arm/mm/mobj.c
> core: mobj.c: sort #includes

- core/lib/libtomcrypt/include/tomcrypt_mp.h
- core/lib/libtomcrypt/include/tomcrypt_mpa.h
- core/lib/libtomcrypt/src/mpa_desc.c
- core/lib/libtomcrypt/src/tee_ltc_provider.c
> Contain LTC libmpa dependencies in mpa_desc.c

- core/arch/arm/kernel/tee_time_arm_cntpct.c
- core/arch/arm/mm/mobj.c
- core/arch/arm/tee/entry_std.c
> Two small cleanups 

- .travis.yml
- scripts/gen_hashed_bin.py
- scripts/gen_ld_sects.py
- scripts/mem_usage.py
- scripts/pem_to_pub_c.py
- scripts/sign.py
- scripts/symbolize.py
- scripts/ta_bin_to_c.py
- scripts/tee_bin_parser.py
> CI: run pep8 on Python scripts

- core/arch/arm/mm/tee_mmu.c
Prior to this patch vm_map() didn't allocate new page tables (PGTs) as
needed, it only checked that it later would be possible to allocate the
needed PGTs.  This is enough if the user_ta_ctx (UTC) isn't active. With
dynamically linked libraries the UTC will be active when vm_map() is
called to make room for the new segments. If the already allocated PGTs
happen to cover even the new memory range it will still work, this is
normally the case with CFG_WITH_LPAE=y since each page table covers 2 MiB.
With CFG_WITH_LPAE=n the page tables only covers 1 MiB and that's not enough
when loading the os_test TA in xtest case 1006.
This patch fixes the problem by instead of just checking that it later
will be possible to allocate needed PGTs, it also allocates the PGTs if
the UTC is active. …
> core: fix bug in vm_map() causing pager panic()

- lib/libmbedtls/mbedtls/include/mbedtls/bignum.h
- lib/libmbedtls/mbedtls/library/bignum.c
Update mbedtls with two commits to help integration in libutee
To make this branch compile we need to merge master into import/mbedtls-2.6.1 again, https://github.com/OP-TEE/optee_os/pull/2678 need to be part of that merge.
> Mbed update

- core/arch/arm/tee/entry_fast.c
These two patches are did when reviewing code. Not go through test.
> misc patches

- lib/libutee/tee_api_arith_mpi.c
mbedtls_mpi_mul_mpi() checks the allocated size of the ouput number
before starting to multiply the numbers. It makes a conservative guess
by requiring the result to be at least as large as the sum of the sizes
of the input numbers. For instance, if A fits in one "limb" and B fits
in two, then the result is expected to have nblimbs = 3 at least.
This is sometimes too restrictive. Consider A = 1 (can be represented
with nblimbs == 1 32-bit words) and B = 0x0FFFFFFFFFFFFFFF (fits in a
bignum with nblimbs == 2 32-bit words). A * B is equal to B and fits
in 2 limbs, but the current code requires 3.
This patch fixes the problem by allocating a big enough temporary
result.
> mbedtls: TEE_BigIntMul(): use temporary

- LICENSE
- documentation/optee_design.md
Related to https://github.com/OP-TEE/optee_os/issues/2771.
> Dual-license OP-TEE headers + license clarification

- core/arch/arm/plat-stm32mp1/conf.mk
- core/arch/arm/plat-stm32mp1/main.c
- core/arch/arm/plat-stm32mp1/platform_config.h
- core/arch/arm/plat-stm32mp1/stm32_util.h
- core/drivers/stm32_gpio.c
- core/drivers/sub.mk
- core/include/drivers/stm32_gpio.h
> Introduce STM32 GPIO driver and integration in platform stm32mp1

- core/arch/arm/mm/core_mmu.c
Overlap region check could be simplified as below:
"(StartA <= EndB) and (StartB <= EndA)"
> core: mm: simplify overlap check

- .shippable.yml
- MAINTAINERS
- core/arch/arm/plat-hisilicon/conf.mk
- core/arch/arm/plat-hisilicon/hi3519av100.h
- core/arch/arm/plat-hisilicon/hi3519av100_plat_init.S
- core/arch/arm/plat-hisilicon/main.c
- core/arch/arm/plat-hisilicon/platform_config.h
- core/arch/arm/plat-hisilicon/psci.c
- core/arch/arm/plat-hisilicon/sub.mk
Hi3519AV100 is a high-performance and low-power 4K
Smart IP Camera SoC designed for IP cameras, action cameras,
panoramic cameras, rear view mirrors, and UAVs. Hi3519A
V100 introduces H.265/H.264 encoding and decoding, with
performance up to 4K x 2K@60 fps and 1080p@240 fps.
For more information:
http://www.hisilicon.com/en/Products/ProductList/Surveillance
This patch has been tested using the following step,
1. Patch the uboot and Linux kernel with OP-TEE support if required
2. build step:
(1) make CROSS_COMPILE=arm-himix200-linux- PLATFORM=hisilicon
PLATFORM_FLAVOR=hi3519av100_demo  (OPTEE-OS build)
(2) make CROSS_COMPILE_HOST=arm-himix200-linux- (OPTEE_CLIENT build)
(3) cross_compile openssl and replace optee_test/host/libopenssl
(4) make CROSS_COMPILE_HOST=arm-himix200-linux- …
> Add support for Hisilicon Hi3519AV100 DEMO board

- lib/libutils/isoc/isalnum.c
- lib/libutils/isoc/iscntrl.c
- lib/libutils/isoc/isgraph.c
- lib/libutils/isoc/islower.c
- lib/libutils/isoc/isprint.c
- lib/libutils/isoc/ispunct.c
- lib/libutils/isoc/sub.mk
- lib/libutils/isoc/toupper.c
Implement missing functions from ctypes.h.
Signed-off-by: Yunjong Jeong <yunjong@kaist.ac.kr>
> libutils: isoc: implement more ctypes functions

- core/arch/arm/plat-ls/conf.mk
Signed-off-by: Pankaj Gupta <pankaj.gupta@nxp.com>
> plat-ls: updated conf.mk to set CFG_USER_TA_TARGETS ?= ta_arm64

- core/drivers/stm32_i2c.c
- core/drivers/sub.mk
- core/include/drivers/stm32_i2c.h
- lib/libutils/ext/include/util.h
> Introduce STM32 I2C driver 

- core/core.mk
- core/crypto/aes-cts.c
- core/crypto/aes-gcm-sw.c
- core/crypto/sub.mk
- core/include/crypto/crypto.h
- core/lib/libtomcrypt/src/tee_ltc_provider.c
- core/lib/libtomcrypt/sub.mk
Some commits that are needed when using mbedtls as primary crypto library, but makes sense one their own.
> Crypt misc

- lib/libmbedtls/mbedtls/include/mbedtls/cipher.h
- lib/libmbedtls/mbedtls/include/mbedtls/cipher_internal.h
- lib/libmbedtls/mbedtls/include/mbedtls/cmac.h
- lib/libmbedtls/mbedtls/library/cipher.c
- lib/libmbedtls/mbedtls/library/cipher_wrap.c
- lib/libmbedtls/mbedtls/library/cmac.c
- lib/libmbedtls/mbedtls/library/md.c
- lib/libmbedtls/mbedtls/library/rsa.c
This pull request replaces https://github.com/OP-TEE/optee_os/pull/2439
I have my doubts about "libmbedtls: fix no CRT issue". Why it's needed (it is needed or some signing fails). Perhaps @edison-ai can shed some light on this.
> Mbed import

- MAINTAINERS
~~Igor no longer works for Linaro and emails to igor.opaniuk@linaro.org~~
~~cannot be delivered. Remove him from the reviewers list.~~
~~Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>~~
[Patch description updated]
> MAINTAINERS: fix Igor Opaniuk's email, make him a Poplar reviewer

- MAINTAINERS
Add Sandeep Tripathy <sandeep.tripathy@broadcom.com> as reviewer.
bcm-optee-feedback-list.pdl@broadcom.com is the mail distribution
list having currently active or interested tee developers within
Broadcom. Keep this entry as a list.
Suggested-by: Jerome Forissier <jerome.forissier@linaro.org>
Signed-off-by: Sandeep Tripathy <sandeep.tripathy@broadcom.com>
> MAINTAINERS: update Broadcom reviewer list

- core/arch/arm/kernel/kern.ld.S
> kern.ld.S improvements

- core/tee/tee_svc_storage.c
After truncating a persistent object, update `dataSize` in the corresponding `TEE_ObjectInfo` structure.
Signed-off-by: Christopher Tam <godtamit@google.com>
Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (QEMU, GP)
> core: storage: set data length after truncation

- core/drivers/pl022_spi.c
- core/drivers/pl061_gpio.c
> pl022 updates/fixes

- core/lib/libtomcrypt/mpi_desc.c
Fixes the preallocation to make room for the actual content also in
crypto_bignum_allocate() by calling mbedtls_mpi_grow().
> core: ltc: fix preallocation of MPI bignums

- lib/libmbedtls/mbedtls/library/bignum.c
Cherry-pick of https://github.com/OP-TEE/optee_os/pull/2954
> Mbed updates

- core/arch/arm/plat-bcm/conf.mk
- core/arch/arm/plat-bcm/main.c
- core/arch/arm/plat-bcm/platform_config.h
-add more device ranges and definitions.
-fix dynamic shm api.
-cleanup plaform def
Signed-off-by: Sandeep Tripathy <sandeep.tripathy@broadcom.com>
> plat-bcm: update platform configurations

- core/arch/arm/plat-bcm/conf.mk
- core/drivers/bcm_gpio.c
- core/drivers/sub.mk
- core/include/drivers/bcm_gpio.h
low level driver for Broadcom IPROC GPIO controller.
Signed-off-by: Sandeep Tripathy <sandeep.tripathy@broadcom.com>
> drivers: bcm_gpio: add IPROC GPIO driver

- core/drivers/stm32_uart.c
- core/include/drivers/stm32_uart.h
> stm32mp1: handle UART pin muxing and suspend

- core/arch/arm/include/mm/mobj.h
- core/arch/arm/kernel/thread.c
- core/kernel/huk_subkey.c
- core/kernel/msg_param.c
- core/lib/libtomcrypt/sub.mk
- core/tee/tee_fs_key_manager.c
- core/tee/tee_svc.c
- core/tee/tee_svc_cryp.c
- core/tee/tee_svc_storage.c
- lib/libutils/ext/include/stdlib_ext.h
- lib/libutils/ext/include/string_ext.h
- lib/libutils/ext/memzero_explicit.c
- lib/libutils/ext/sub.mk
- lib/libutils/isoc/bget.c
- lib/libutils/isoc/bget.h
- lib/libutils/isoc/bget_malloc.c
> Security patches

- .shippable.yml
- core/arch/arm/kernel/ree_fs_ta.c
> Ree fs compile error

- core/drivers/stm32_etzpc.c
- core/include/kernel/pm.h
> stm32_etzpc pm

- core/lib/libtomcrypt/mpa_desc.c
- core/lib/libtomcrypt/mpi_desc.c
- core/tee/tee_ree_fs.c
- lib/libutils/ext/include/mempool.h
- lib/libutils/ext/mempool.c
> Mempool default

- core/arch/arm/plat-stm32mp1/shared_resources.c
- core/drivers/stm32_gpio.c
- core/include/drivers/stm32_gpio.h
> stm32mp1: GPIO enhancement

- lib/libmbedtls/mbedtls/library/bignum.c
- lib/libutee/tee_api_arith_mpi.c
>  libmbedtls: mbedtls_mpi_exp_mod(): reduce stack usage

- .github/issue_template.md
- .github/pull_request_template.md
- core/arch/arm/kernel/pseudo_ta.c
> Spelling fix and GitHub template updates

- core/arch/arm/include/kernel/misc.h
- core/arch/arm/kernel/early_ta.c
- core/arch/arm/kernel/elf_load.h
- core/arch/arm/kernel/ree_fs_ta.c
- core/arch/arm/kernel/secstor_ta.c
- core/arch/arm/mm/tee_mmu.c
- core/arch/arm/mm/tee_pager.c
- core/include/kernel/handle.h
- core/include/kernel/user_ta_store.h
- core/kernel/handle.c
- lib/libutils/ext/include/util.h
- mk/lib.mk
- ta/arch/arm/link_shlib.mk
> Misc small patches from PR #3036

- core/arch/arm/pta/system.c
The tee_vbuf_is_sec() which ends up as core_vbuf_is() doesn't work with
paged user space memory, so instead use tee_mmu_check_access_rights().
This resolves an regression issue found when running with the pager
enabled: https://github.com/OP-TEE/optee_test/pull/349
> PTA: change method for checking memory in derive TA key

- MAINTAINERS
Add Jerome Forissier back to the list of maintainers.
> MAINTAINERS: Update list of maintainers

- core/arch/arm/plat-hikey/main.c
- core/arch/arm/plat-hikey/platform_config.h
> HiKey960: fix for 4G boards and support 6G boards

- core/arch/arm/plat-ti/sm_platform_handler_a15.c
- core/arch/arm/plat-ti/sm_platform_handler_a9.c
$ make -s PLATFORM=ti-dra7xx
core/arch/arm/plat-ti/sm_platform_handler_a15.c:33:6: error: conflicting
types for ‘sm_platform_handler’
bool sm_platform_handler(struct sm_ctx *ctx)
^~~~~~~~~~~~~~~~~~~
In file included from
core/arch/arm/plat-ti/sm_platform_handler_a15.c:30:
core/arch/arm/include/sm/sm.h:122:21: note: previous declaration of
‘sm_platform_handler’ was here
enum sm_handler_ret sm_platform_handler(struct sm_ctx *ctx);
^~~~~~~~~~~~~~~~~~~
make: *** [mk/compile.mk:147:
out/arm-plat-ti/core/arch/arm/plat-ti/sm_platform_handler_a15.o] Error 1
$ make -s PLATFORM=ti-am43xx
core/arch/arm/plat-ti/sm_platform_handler_a9.c:42:6: error: conflicting
types for ‘sm_platform_handler’
bool sm_platform_handler(struct sm_ctx *ctx)
^~~~~~~~~~~~~~~~~~~
In file included from …
> plat-ti: fix build errors

- core/arch/arm/kernel/elf_load_dyn.c
- core/arch/arm/kernel/elf_load_private.h
- core/arch/arm/kernel/user_ta.c
> Use DT_HASH to lookup symbols faster

- core/arch/arm/kernel/mutex.c
- core/arch/arm/kernel/mutex_lockdep.c
- core/arch/arm/kernel/mutex_lockdep.h
- core/arch/arm/pta/core_lockdep_tests.c
- core/include/kernel/lockdep.h
- core/kernel/lockdep.c
> Fix mutex_trylock() with CFG_LOCKDEP=y

- core/mm/file.c
Fixes a race in file_get_by_tag() where a file is just about to be freed
but hasn't been removed from the linked list yet.
Fixes: bae0f170e321 ("core: file: refactor interface to be thread safe")
> core: fix file_get_by_tag()

- CHANGELOG.md
> Update CHANGELOG for 3.6.0

- core/tee/tee_ree_fs.c
Currently there's no check of return value of tee_fs_dirfile_open,
it's reasonable to do this when dir file truely doesn't exist.
However, if tee_fs_dirfile_open fails with other reason, calling
tee_fs_dirfile_open(true..) will overlap the old dir file, thus
file access in the future will fail.
> tee_ree_fs: create dirfile only when it's not found

- core/arch/arm/include/kernel/user_ta.h
- core/arch/arm/include/mm/mobj.h
- core/arch/arm/kernel/user_ta.c
- core/arch/arm/mm/mobj.c
- core/arch/arm/mm/tee_mmu.c
- core/arch/arm/mm/tee_pager.c
- core/arch/arm/pta/system.c
- core/include/mm/tee_mmu.h
- core/include/mm/tee_mmu_types.h
> Remove struct load_seg

- core/tee/tee_rpmb_fs.c
> rpmb: write key only if not yet programmed

- MAINTAINERS
- scripts/get_maintainer.py
A new script inspired from the Linux kernel's `get_maintainer.pl`, and a small fix to `MAINTAINERS`.
> Add scripts/get_maintainer.py

- core/arch/arm/include/arm32.h
- core/arch/arm/include/arm64.h
- core/arch/arm/include/kernel/abort.h
- core/arch/arm/include/kernel/cache_helpers.h
- core/arch/arm/include/kernel/spinlock.h
- core/arch/arm/include/kernel/thread.h
- core/arch/arm/include/kernel/tlb_helpers.h
- core/arch/arm/include/kernel/unwind.h
- core/arch/arm/include/mm/core_mmu.h
- core/arch/arm/include/sm/sm.h
- core/arch/arm/kernel/link.mk
- core/arch/arm/kernel/thread_private.h
- core/arch/arm/plat-imx/imx_pm.h
- core/arch/arm/plat-stm32mp1/drivers/stm32mp1_rcc.h
- core/include/keep.h
- core/include/kernel/asan.h
- core/include/optee_msg.h
- ldelf/include/elf_common.h
- ldelf/link.mk
- lib/libutils/ext/include/util.h
- lib/libutils/isoc/include/stdint.h
- mk/compile.mk
- ta/arch/arm/link.mk
> Replace ASM define

- core/arch/arm/include/kernel/user_ta.h
- core/arch/arm/kernel/user_ta.c
- core/arch/arm/pta/system.c
- ldelf/dl.c
- ldelf/dl.h
- ldelf/ftrace.c
- ldelf/include/ldelf.h
- ldelf/main.c
- ldelf/sub.mk
- ldelf/ta_elf.c
- ldelf/ta_elf.h
- ldelf/ta_elf_rel.c
- lib/libdl/dlfcn.c
- lib/libdl/include/dlfcn.h
- lib/libdl/sub.mk
- lib/libutee/include/pta_system.h
- lib/libutee/include/tee_internal_api_extensions.h
- lib/libutee/sub.mk
- lib/libutee/tee_uuid_from_str.c
- ta/mk/ta_dev_kit.mk
- ta/ta.mk
Supersedes PR #2894. The code was reworked for the new user space loader (ldelf).
> Add support for runtime dynamic linking in TAs (libdl)

- scripts/sign.py
New versions of pycroptodome throw NotImplementedError when calling
size() method if RSA object. This is because this method is
considered insecure. As a workaround we can calculate key size
manually, in the same way as PKCS115_SigScheme does this.
----
The following commit caused this: 
https://github.com/Legrandin/pycryptodome/commit/ab4ed2dcc1de4e96b1d9fcb63f85cdaa92396071
Also you can check https://github.com/Legrandin/pycryptodome/issues/6
This fix is a workaround, hence RFC tag. I think, proper solution would be to calculate signature and check it's real size. But in this case we have chicken and egg problem: header should contain signature size, but  it should be signed itself. We can resolve this by calculation …
> [RFC]scripts/sign.py: fix signature length calculation

- MAINTAINERS
The reviewers/maintainers for some subsystem may be reached on Github
using special team handles. Add them to MAINTAINERS.
> MAINTAINERS: add Github handles for teams

- .shippable.yml
- core/arch/arm/plat-imx/conf.mk
- core/arch/arm/plat-imx/imx-common.c
- core/arch/arm/plat-imx/imx-regs.h
- core/arch/arm/plat-imx/imx.h
- core/arch/arm/plat-imx/main.c
- core/arch/arm/plat-imx/registers/imx8m.h
- core/arch/arm/plat-imx/registers/imx8q.h
- core/drivers/imx_lpuart.c
- core/drivers/imx_uart.c
Hello,
Another PR to do the following:
* Add DT support for UART driver.
* Allow boards to boot with no console.
* Add support for i.MX8 QM/QxP/MN.
* Add myself as i.MX maintainer (with the approval of @MrVan )
Thank you!
> i.MX Support #4

- lib/libutee/arch/arm/ftrace/ftrace.c
- lib/libutee/arch/arm/utee_syscalls_a32.S
- lib/libutee/arch/arm/utee_syscalls_a64.S
- mk/config.mk
Picking two commits from https://github.com/OP-TEE/optee_os/pull/3231.
> Ftrace improvements 2

- MAINTAINERS
- core/crypto/crypto.c
- core/drivers/crypto/crypto_api/drvcrypt.c
- core/drivers/crypto/crypto_api/hash/hash.c
- core/drivers/crypto/crypto_api/hash/sub.mk
- core/drivers/crypto/crypto_api/include/drvcrypt.h
- core/drivers/crypto/crypto_api/include/drvcrypt_hash.h
- core/drivers/crypto/crypto_api/sub.mk
- core/drivers/crypto/sub.mk
- core/drivers/sub.mk
- core/include/crypto/crypto_impl.h
Add a Hash generic cryptographic driver interface connecting TEE Crypto generic APIs to HW driver interface
> core: driver: generic resources for crypto device driver

- scripts/arm32_sysreg.py
- scripts/gen_hashed_bin.py
- scripts/gen_ld_sects.py
- scripts/pem_to_pub_c.py
- scripts/sign.py
- scripts/symbolize.py
- scripts/tee_bin_parser.py
Convert the remaining scripts to python3. Mostly done with 2to3 and
manual adjustements to the code afterwards.
TODO:
Fixes #3111
> scripts: convert remaining scripts to python3

- core/crypto.mk
- core/lib/libtomcrypt/sub.mk
- mk/checkconf.mk
> Build: update cfg-* functions to set variables to 'n' instead of an empty string

- core/tee/tadb.c
This commit changes the way the tadb_db global variable is protected
against concurrent access on creation and deletion. Instead of using an
atomic reference counter (struct refcount) and a mutex, only the mutex
is used and taken unconditionally. The reference count becomes a global
integer protected by the same mutex.
Using a struct refcount was apparently an optimization to avoid taking
the lock unless actual creation or deletion of the tadb_db was needed.
Unfortunately this implementation was causing occasional crashes of the
TEE core (easily reproducible on HiKey running 'xtest 1013' in a loop).
The new implementation is simpler and appears to be rock solid with no
measurable difference in performance.
> core: tadb.c: get rid of atomic reference counting

- core/core.mk
- core/sub.mk
- ldelf/link.mk
- mk/subdir.mk
> Small fixes/improvements with "make clean"

- core/include/drivers/gic.h
Add GIC_SPI helper macro
Signed-off-by: Rayagonda Kokatanur <rayagonda.kokatanur@broadcom.com>
Reviewed-by: Sandeep Tripathy <sandeep.tripathy@broadcom.com>
> drivers: gic: Add GIC_SPI helper macro

- scripts/gen_ldelf_hex.py
Removes a few import lines that are not needed.
> scripts/gen_ldelf_hex.py: remove unused imports

- core/arch/arm/kernel/trace_ext.c
- core/arch/arm/plat-bcm/bcm_elog.c
- core/arch/arm/plat-bcm/bcm_elog.h
- core/arch/arm/plat-bcm/conf.mk
- core/arch/arm/plat-bcm/main.c
- core/arch/arm/plat-bcm/sub.mk
- lib/libutils/ext/include/trace.h
> Add Broadcom Error logging support

- core/arch/arm/plat-bcm/platform_config.h
- core/pta/bcm/sub.mk
- core/pta/bcm/wdt.c
Add PTA for secure watchdog
Signed-off-by: Bharat Kumar Reddy Gooty <bharat.gooty@broadcom.com>
> Add PTA for secure watchdog

- core/pta/bcm/sotp.c
- core/pta/bcm/sub.mk
Add Broadcom SOTP PTA
Signed-off-by: Rahul Gupta <rahul.gupta@broadcom.com>
> Add Broadcom SOTP PTA

- core/arch/arm/include/kernel/generic_boot.h
- core/arch/arm/include/kernel/linker.h
- core/arch/arm/kernel/asm-defines.c
- core/arch/arm/kernel/generic_boot.c
- core/arch/arm/kernel/generic_entry_a32.S
- core/arch/arm/kernel/generic_entry_a64.S
- core/arch/arm/kernel/kern.ld.S
- scripts/gen_tee_bin.py
> ASLR: Embedded data

- core/arch/arm/include/kernel/generic_boot.h
- core/arch/arm/kernel/generic_boot.c
- core/arch/arm/kernel/generic_entry_a32.S
- core/arch/arm/kernel/thread.c
- core/arch/arm/plat-imx/main.c
- core/arch/arm/plat-imx/pm/cpuidle-imx7d.c
- core/arch/arm/plat-imx/pm/imx7_suspend.c
- core/arch/arm/plat-ls/main.c
- core/arch/arm/plat-sam/main.c
- core/arch/arm/plat-stm/main.c
- core/arch/arm/plat-stm/tz_a9init.S
- core/arch/arm/plat-sunxi/main.c
- core/arch/arm/plat-zynq7k/main.c
This PR touches platforms maintained by:
@etienne-lms, @MrVan, @cneveux, @sdininno, @clementfaure, @pangupta, @sahilnxp, @nodeax, , @grandpaul, @Amit-Radur, @OP-TEE/plat-zynq7k
> Fix aslr for ARMv7 smp

- scripts/gen_tee_bin.py
Older versions of pyelftools return symbol and section names as byte
arrays rather than plain strings. As a result, symbols are not found:
$ make
...
GEN     out/arm/core/tee-header_v2.bin
Cannot find symbol _start
core/arch/arm/kernel/link.mk:191: recipe for target 'out/arm/core/tee-header_v2.bin' failed
make[1]: *** [out/arm/core/tee-header_v2.bin] Error 1
(This error was observed when building on Ubuntu 16.04.)
> scripts/gen_tee_bin.py: convert symbol and section name to strings

- core/arch/arm/plat-bcm/platform_config.h
Update Broadcom DRAM2 base and size
> Update Broadcom DRAM2 base and size

- scripts/mem_usage.py
Since commit 5966660c02b3 ("core: move relocation to embedded data
region"), when ASLR is enabled, some sections are stored at the end of
tee.elf for use by gen_tee_bin.py which then discards them. As a
result, they are not present in the final binary and should not be
reported by the memory usage script.
By ignoring any section past the _end_of_ram symbol, we avoid reporting
those discarded sections as well as a hole before them.
Before:
$ make -s CFG_CORE_ASLR=y
$ scripts/mem_usage.py out/arm-plat-vexpress/core/tee.elf
RAM Usage        0E100000 - 0E301E04 size 00201E04 2056 KiB 514 pages
.text            0E100000 - 0E12FA68 size 0002FA68 190 KiB
*hole*           0E12FA68 - 0E130000 size 00000598   1 KiB
.rodata          0E130000 - 0E140598 size 00010598  65 KiB
.gnu.hash        0E140598 …
> mem_usage.py: stop parsing file when _end_of_ram is reached

- scripts/tee_bin_parser.py
> Tee bin parser

- core/arch/arm/include/mm/core_mmu.h
- core/arch/arm/include/mm/mobj.h
- core/arch/arm/kernel/pseudo_ta.c
- core/arch/arm/mm/core_mmu.c
- core/arch/arm/mm/mobj_dyn_shm.c
- lib/libutils/isoc/include/stdint.h
A few patches needed by the future SPCI integration.
> Spci preparations

- core/lib/libtomcrypt/acipher_helpers.h
- core/lib/libtomcrypt/dh.c
- core/lib/libtomcrypt/dsa.c
- core/lib/libtomcrypt/ecc.c
- core/lib/libtomcrypt/rsa.c
- core/lib/libtomcrypt/sm2-pke.c
- core/lib/libtomcrypt/src/pk/ecc/sub.mk
- core/lib/libtomcrypt/sub.mk
> LTC SM2 PKE

- MAINTAINERS
> MAINTAINERS: update a couple of email addresses

- scripts/symbolize.py
Commit 105e09c24479 ("symbolize.py: add support for TEE core ASLR") has
introduced support for ASLR by using addresses relative to the .text
section. To this end, the '-j.text' option is passed to addr2line.
Unfortunately, it happens that addr2line does not like to be given
addresses that are outside the specified section. This can happen when
CFG_WITH_PAGER=y as shown in the following example:
D/TC:4 0 TEE load address @ 0x3f000000
D/TC:4 0 Call stack:
D/TC:4 0  0x000000003f0080ac read_pc at optee_os/core/arch/arm/include/arm64.h:237
D/TC:4 0  0x000000003f062984 ?? ??:0
D/TC:4 0  0x000000003f007be4 wq_wait_final at optee_os/core/arch/arm/kernel/wait_queue.c:88
D/TC:4 0  0x000000003f007698 __mutex_lock at optee_os/core/arch/arm/kernel/mutex.c:57
D/TC:4 0  0x000000003f06c204 ?? ??:0
D/TC:4 …
> symbolize.py: fix stack dump of TEE core with pager

- core/lib/libtomcrypt/sm2-dsa.c
- core/lib/libtomcrypt/sub.mk
Adds support for the SM2 Digital Signature Algorithm [1] for use by
OP-TEE core based on LibTomCrypt.
[1]  http://www.gmbz.org.cn/main/postDetail.html?id=20180724110812
> LTC SM2 DSA

- core/crypto.mk
- core/crypto/crypto.c
- core/include/crypto/crypto.h
- core/lib/libtomcrypt/ecc.c
- core/lib/libtomcrypt/sm2-dsa.c
- core/lib/libtomcrypt/sub.mk
- core/tee/tee_svc_cryp.c
- lib/libutee/include/tee_api_defines.h
- lib/libutee/include/utee_defines.h
- lib/libutee/tee_api_operations.c
Please review only commit "core: crypto add support for SM2 DSA". The other ones are in other PRs.
> core: crypto add support for SM2 DSA

- core/lib/libtomcrypt/sm2-dsa.c
- core/lib/libtomcrypt/sm2-pke.c
> Fix bignum leaks in SM2 code

- core/lib/libtomcrypt/acipher_helpers.h
- core/lib/libtomcrypt/sm2-dsa.c
- core/lib/libtomcrypt/sm2-pke.c
Two patches fixing issues found by IBART ([link](https://optee.mooo.com:5000/logs/OP-TEE/optee_os/3535/363669382/778693b3b02f4f7bba824a2914bd057682815cf9)).
> SM2 bignum fixes

- core/arch/arm/mm/mobj_dyn_shm.c
```
Prior to this patch a struct mobj_reg_shm was initialized with num_pages
* SMALL_PAGE_SIZE without taking page_offset into account. This patch
fixes that by subtracting the result of the multiplication above with
page_offset.
```
> core: fix assigned size of struct mobj_reg_shm

- core/arch/arm/kernel/pseudo_ta.c
- core/arch/arm/mm/mobj.c
- core/arch/arm/mm/mobj_dyn_shm.c
> mobj_get_va() and PTA

- ta/pkcs11/src/entry.c
- ta/pkcs11/src/pkcs11_helpers.c
- ta/pkcs11/src/pkcs11_helpers.h
- ta/pkcs11/src/sub.mk
> Debug traces for TA commands and introduce ID/string helpers

- core/arch/arm/mm/tee_mmu.c
Removes the requirement that length of memory area to unmap must be page
aligned. The supplied length is instead rounded up to the nearest page.
This fixes a regression with CFG_FTRACE_SUPPORT=y:
E/TC:? 0 assertion '!res' failed at core/arch/arm/kernel/user_ta.c:571 <user_ta_dump_ftrace>
Fixes: cffe74d2446b ("core: fix assigned size of struct mobj_reg_shm")
> core: vm_unmap(): remove length alignment requirement

- core/arch/arm/tee/arch_svc.c
In user_ta_handle_svc() as part of handling a syscall there's a lookup
in the syscall table which can be subject to a speculation attack.
load_no_speculate() is used to protect the sensitive lookup.
Another attempt at speculation safe syscall table lookup.
Replaces https://github.com/OP-TEE/optee_os/pull/3484
Relates to https://github.com/OP-TEE/optee_os/issues/3490
> core: protect syscall table lookup from speculation

- .shippable.yml
- core/arch/arm/plat-imx/conf.mk
Add imx6ulzevk platform flavor.
> core: imx: add imx6ulzevk platform flavor

- lib/libutils/ext/ftrace/ftrace.c
- mk/checkconf.mk
- mk/config.mk
- ta/arch/arm/ta.ld.S
A patch to help with ftrace in case a relatively big buffer is used. The first patch is just a minor unrelated improvement.
> Ftrace buffer full improvement

- scripts/symbolize.py
> Symbolize fixes

- core/arch/arm/plat-ls/conf.mk
- core/arch/arm/plat-ls/crypto_conf.mk
- core/arch/arm/plat-ls/platform_config.h
Enable CAAM support for platform LS1046ARDB
Signed-off-by: Priyanka Singh <priyanka.singh@nxp.com>
> core: plat-ls: Enable caam support for platform LS1046ARDB

- core/arch/arm/plat-ls/platform_config.h
Fix GIC offsets for platform LS1046ARDB
Signed-off-by: Priyanka Singh <priyanka.singh@nxp.com>
> core: plat-ls: Fix gic offsets for platform LS1046ARDB

- MAINTAINERS
An extra dot is present in my email address in the "Hisilicon
Hi3519AV100 family" subsystem. Remove it.
> MAINTAINERS: fix my email address

- lib/libutils/ext/include/confine_array_index.h
Add confine_array_index to limit indexes safely without speculation.
> Confine array index

- .shippable.yml
- core/drivers/crypto/caam/caam_jr.c
- core/drivers/crypto/caam/hal/common/hal_cfg.c
- core/drivers/crypto/caam/hal/common/hal_jr.c
- core/drivers/crypto/crypto_api/include/drvcrypt_asn1_oid.h
- core/drivers/crypto/crypto_api/oid/hash_oid.c
Hello!
This patch set:
- Fixes suspend/resume issue in the CAAM driver.
- Fixes compilation warning in CAAM driver.
- Fixes compilation error and warning in crypto driver introduced in the recent RSA pull-request (my bad ...)
Thanks!
> Multiple fixes CAAM and Crypto driver

- ldelf/ta_elf.c
- ldelf/ta_elf_rel.c
> Ldelf fixes/hardening

- ldelf/ta_elf.c
- ldelf/ta_elf_rel.c
> Ldelf fixes

- core/arch/arm/include/mm/core_mmu.h
- core/arch/arm/kernel/thread_a32.S
- core/arch/arm/mm/core_mmu_lpae.c
- core/arch/arm/mm/core_mmu_v7.c
> Core mmu cleanup/optimization

- core/arch/arm/kernel/generic_entry_a32.S
- core/arch/arm/kernel/generic_entry_a64.S
- core/arch/arm/kernel/user_ta.c
- lib/libutee/include/arm64_user_sysreg.h
> Useless #include <elf_common.h> + Clang warnings with <arm64_user_sysreg.h>

- core/arch/arm/plat-imx/crypto_conf.mk
- core/crypto/crypto.c
- core/drivers/crypto/caam/caam_ctrl.c
- core/drivers/crypto/caam/cipher/caam_cipher.c
- core/drivers/crypto/caam/cipher/caam_cipher_xts.c
- core/drivers/crypto/caam/cipher/local.h
- core/drivers/crypto/caam/cipher/sub.mk
- core/drivers/crypto/caam/include/caam_cipher.h
- core/drivers/crypto/caam/include/caam_trace.h
- core/drivers/crypto/caam/sub.mk
- core/drivers/crypto/crypto_api/cipher/cipher.c
- core/drivers/crypto/crypto_api/cipher/sub.mk
- core/drivers/crypto/crypto_api/include/drvcrypt.h
- core/drivers/crypto/crypto_api/include/drvcrypt_cipher.h
- core/drivers/crypto/crypto_api/sub.mk
- core/include/crypto/crypto_impl.h
Hello everyone,
Here is the cipher CAAM driver.
Feedback is always welcomed !
> Cipher implementation for CAAM driver

- ta/pkcs11/src/persistent_token.c
get_db_file_name() and get_pin_file_name() factorize TEE object file
IDs.
open_db_file()/close_db_file(), open_pin_file()/close_pin_file()
manipulate the PIN cipher keys.
> ta: pkcs11: factorize persistent file name

- ta/pkcs11/include/pkcs11_ta.h
- ta/pkcs11/src/entry.c
- ta/pkcs11/src/pkcs11_helpers.h
- ta/pkcs11/src/pkcs11_token.c
- ta/pkcs11/src/pkcs11_token.h
- ta/pkcs11/src/sub.mk
- ta/pkcs11/src/token_capabilities.c
- ta/pkcs11/src/token_capabilities.h
> ta: pkcs11: get mechanism list/info

- core/drivers/stm32_etzpc.c
Correct TZMAs configuration restore sequence at PM resume.
> drivers/stm32_etzpc: fix tzma configuration

- ta/pkcs11/src/persistent_token.c
- ta/pkcs11/src/pkcs11_token.c
- ta/pkcs11/src/serializer.h
> ta: pkcs11: minor cleanup changes

- core/arch/arm/plat-stm32mp1/drivers/stm32mp1_clk.c
Array stm32mp1_clk_gate[] defines the clock resources. This change
adds an attribute to the clocks in stm32mp1_clk_gate array. Clocks
under RCC[TZEN] hardening are tagged SEC and clocks always assigned
to non-secure world as per SoC implementation are tagged N_S.
Non-secure clocks that OP-TEE expects to enable are enabled without
increase of their refcount and, for consistency, are never disabled
by TEE Core. Note that such clocks may be accessed by OP-TEE Core
when the non-secure world is not executing, for example at boot time
or could be when system is suspending/resuming.
> plat-stm32mp1: clock: secure and non-secure gateable clocks

- core/arch/arm/plat-stm32mp1/conf.mk
- core/arch/arm/plat-stm32mp1/nsec-service/stm32mp1_smc.h
- core/arch/arm/plat-stm32mp1/nsec-service/stm32mp1_svc_setup.c
- core/arch/arm/plat-stm32mp1/nsec-service/sub.mk
- core/arch/arm/plat-stm32mp1/sub.mk
Implement secure monitor platform handlers foundations for
platform stm32mp1 to handle SiP SMC services.
> stm32mp1: prepare for SiP SMC services

- core/arch/arm/mm/core_mmu.c
assign_mem_va() missing VA limit check cause TEE panic when
VA exceed the width limit. Add check to catch this case.
> core: arm: core_mmu: fix VA overflow issue in assign_mem_va()

- core/drivers/crypto/caam/hal/common/hal_jr.c
- core/drivers/crypto/caam/include/caam_common.h
> Caam fixes

- core/arch/arm/include/kernel/early_ta.h
- core/arch/arm/kernel/early_ta.c
- core/pta/device.c
- scripts/ta_bin_to_c.py
Rework of https://github.com/OP-TEE/optee_os/pull/3751.
> pta/device: enumerate early TAs

- core/arch/arm/kernel/generic_entry_a64.S
Clang built from the llvm-project master branch (git describe:
llvmorg-11-init-12683-g54b3f91d205) causes the following build error:
```
AS      out/arm/core/arch/arm/kernel/generic_entry_a64.o
core/arch/arm/kernel/generic_entry_a64.S:426:2: error: changed section flags for .identity_map, expected: 0x6
.section .identity_map
^
```
Some information about this error can be found in the description for
LLVM commit 75af9da75572 ("[MC][ELF] Error for sh_type, sh_flags or
sh_entsize change") [1].
The ".section .identity_map" directive does not mention any flags so
since the section name is not a well-known one (.text etc.), the flags
default to none [2]. However, at this point in the source file we
already have emitted code into .text* which has flags "ax" (and type
%progbits), so the line does …
> core: arm64: fix .section directive

- ta/pkcs11/src/pkcs11_token.c
- ta/pkcs11/src/serializer.c
- ta/pkcs11/src/serializer.h
> ta: pkcs11: factorize session handle argument handling

- core/arch/arm/plat-stm32mp1/pm/psci.c
> stm32mp1: fix PSCI_CPU_OFF and bring PSCI_SYSTEM_RESET

- core/drivers/scmi-msg/base.c
- core/drivers/scmi-msg/clock.h
- core/drivers/scmi-msg/entry.c
- core/drivers/scmi-msg/reset_domain.c
- core/include/drivers/scmi-msg.h
> scmi-msg drivers: various fixes

- core/arch/arm/plat-stm32mp1/conf.mk
- core/arch/arm/plat-stm32mp1/drivers/stm32mp1_pmic.c
- core/arch/arm/plat-stm32mp1/drivers/stm32mp1_pmic.h
- core/arch/arm/plat-stm32mp1/drivers/sub.mk
- core/arch/arm/plat-stm32mp1/main.c
- core/arch/arm/plat-stm32mp1/pm/psci.c
- core/arch/arm/plat-stm32mp1/stm32_util.h
Platform PMIC driver for STPMIC1 and implementation of PSCI_SYSTEM_OFF.
> plat-stm32mp1: PMIC and system OFF

- core/drivers/stm32_i2c.c
- core/include/drivers/stm32_i2c.h
> drivers: stm32_i2c: reuse already computed settings and few minor changes

- core/arch/arm/plat-stm32mp1/conf.mk
- core/arch/arm/plat-stm32mp1/main.c
- core/arch/arm/plat-stm32mp1/plat_tzc400.c
- core/arch/arm/plat-stm32mp1/platform_config.h
- core/arch/arm/plat-stm32mp1/sub.mk
- core/drivers/tzc400.c
- core/include/drivers/tzc400.h
> tzc400: allow platform to check TZC400 configuration and use in plat-stm32mp1

- core/arch/arm/plat-ls/conf.mk
- core/arch/arm/plat-ls/crypto_conf.mk
- core/arch/arm/plat-ls/platform_config.h
- core/drivers/crypto/caam/caam_desc.c
- core/drivers/crypto/caam/hal/common/hal_ctrl.c
- core/drivers/crypto/caam/hal/common/hal_rng.c
- core/drivers/crypto/caam/hal/common/registers/version_regs.h
> drivers: caam Fixes for Era 10 and above

- .checkpatch.conf
- scripts/checkpatch_inc.sh
checkpatch.pl can be customized with config for non kernel projects.
Signed-off-by: Maxim Uvarov <maxim.uvarov@linaro.org>
> configure checkpatch

- ldelf/link.mk
- mk/clang.mk
- ta/arch/arm/link.mk
- ta/arch/arm/link_shlib.mk
> Fix clang build

- core/arch/arm/plat-imx/crypto_conf.mk
- core/drivers/crypto/caam/acipher/caam_math.c
- core/drivers/crypto/caam/acipher/caam_rsa.c
- core/drivers/crypto/caam/caam_ctrl.c
- core/drivers/crypto/caam/cipher/caam_cipher.c
- core/drivers/crypto/caam/cipher/caam_cipher_mac.c
- core/drivers/crypto/caam/cipher/caam_cipher_xts.c
- core/drivers/crypto/caam/cipher/local.h
- core/drivers/crypto/caam/cipher/sub.mk
- core/drivers/crypto/caam/hash/caam_hash.c
- core/drivers/crypto/caam/include/caam_cipher.h
- core/drivers/crypto/caam/include/caam_utils_mem.h
- core/drivers/crypto/caam/sub.mk
- core/drivers/crypto/caam/utils/utils_mem.c
- core/drivers/crypto/crypto_api/include/drvcrypt.h
- core/drivers/crypto/crypto_api/include/drvcrypt_mac.h
- core/drivers/crypto/crypto_api/mac/mac.c
Hello,
Here is the CMAC for the CAAM!
Thanks!
> CMAC implementation for CAAM driver

- core/arch/arm/kernel/ree_fs_ta.c
- core/arch/arm/mm/tee_mmu.c
- core/arch/arm/mm/tee_pager.c
- core/crypto/aes-gcm-sw.c
- core/drivers/crypto/crypto_api/acipher/rsa.c
And add NULL ptr deref pretection etc.
> Fix mem leaks and avoid NULL ptr deref

- .github/workflows/stales.yml
GitHub reports [1]:
The workflow is not valid.
.github/workflows/stales.yml (Line: 2, Col: 1): Unexpected value
'description'
This commit removes the description: line to fix the issue and moves
additional text to the name: line.
Link: [1] https://github.com/OP-TEE/optee_os/actions/runs/156017617
Fixes: 50bbda3dd3b2 ("github: add a new actions/workflow file")
> github: fix error in workflow file

- core/arch/arm/include/kernel/mutex.h
- core/arch/arm/include/kernel/thread.h
- core/arch/arm/kernel/mutex.c
- core/arch/arm/kernel/mutex_lockdep.c
- core/arch/arm/kernel/thread.c
- core/arch/arm/kernel/thread_a64.S
- core/include/kernel/tee_ta_manager.h
- core/kernel/tee_ta_manager.c
- lib/libutils/ext/ftrace/ftrace.c
- lib/libutils/ext/include/atomic.h
- lib/libutils/ext/mempool.c
> [RFC 2] Recursive mutexes

- mk/subdir.mk
After processing a sub.mk by subdir.mk also clear aflags-remove-y
together with the rest of the variables to clear.
> subdir.mk: clear aflags-remove-y after processing

- ldelf/unwind_arm32.c
- scripts/symbolize.py
- ta/arch/arm/ta_entry_a32.S
> Unwind fixes

- core/arch/arm/kernel/rpc_io_i2c.c
The number of bytes processed by the REE is returned in p[3] as
defined in the API.
> core: arm: rpc i2c: fix, REE processed bytes

- core/arch/arm/mm/tee_mmu.c
- core/tee/tee_svc_storage.c
- lib/libutee/tee_api_arith_mpi.c
> Some small fixes

- core/include/tee/tee_obj.h
- core/include/tee/tee_pobj.h
- core/tee/tee_pobj.c
- core/tee/tee_svc_storage.c
Depends on https://github.com/OP-TEE/optee_test/pull/444 for tests to pass due to the commit "core: remove struct tee_obj::flags"
> TEE Object updates

- scripts/sign_encrypt.py
+ Update the `sign_encrypt.py` so that it can choose the signing algorithm between PSS and PKCS#1.5.
+ Convert the `if/else` into a `try/except` for the signature check
See also #4081
> scripts/sign_encrypt.py: add flags for the signing algorithm

- core/arch/arm/kernel/user_ta.c
- core/arch/arm/plat-vexpress/vendor_props.c
- core/arch/arm/tee/arch_svc_a32.S
- core/arch/arm/tee/arch_svc_a64.S
- core/include/kernel/user_access.h
- core/include/mm/tee_mmu_types.h
- core/include/tee/tee_svc.h
- core/kernel/sub.mk
- core/kernel/user_access.c
- core/tee/tee_svc.c
- core/tee/tee_svc_cryp.c
- core/tee/tee_svc_storage.c
- lib/libutee/tee_api.c
- lib/libutee/tee_api_objects.c
- lib/libutee/tee_api_operations.c
- lib/libutee/tee_api_panic.c
- lib/libutee/tee_api_private.h
- lib/libutee/tee_api_property.c
- mk/config.mk
Depends on https://github.com/OP-TEE/optee_test/pull/446 for xtest to pass
> Gp 1.1 annotation

- core/arch/arm/kernel/boot.c
QEMU has a /secram@e000000 DT node with secure-status = "okay" and
status = "disabled", in other words: some secure-only memory is
described in the DT. Memory that is not purely non-secure should not be
added to the nsec map. Unfortunately, the commit referenced below
inadvertently added such memory, resulting in a panic on boot:
I/TC: Non-secure external DT found
E/TC:0 0 check_phys_mem_is_outside:332 Non-sec mem (0xe000000:0x100000) overlaps map (type 14 0xe000000:0x100000)
E/TC:0 0 Panic at core/arch/arm/mm/core_mmu.c:336 <check_phys_mem_is_outside>
Change the DT status test to consider only non-secure memory. Also,
rename a couple of functions to make their purpose clear.
Fixes: 721619e8890e ("core: Parse all memory DT nodes")
> core: dt: discover_nsec_memory(): consider only non-secure memory

- core/tee/tee_svc_cryp.c
- lib/libutee/include/tee_api_defines.h
- lib/libutee/tee_api_objects.c
- mk/config.mk
> Gp 1.1 updates

- core/pta/tests/aes_perf.c
- core/tee/tee_svc.c
- lib/libutee/tee_api_operations.c
- lib/libutils/ext/include/compiler.h
- lib/libutils/ext/snprintk.c
> Fallthrough

- core/arch/arm/plat-stm32mp1/scmi_server.c
- core/drivers/scmi-msg/clock.c
- core/drivers/scmi-msg/common.h
- core/drivers/scmi-msg/entry.c
- core/include/drivers/scmi-msg.h
> scmi-msg drivers

- core/drivers/stpmic1.c
- core/include/drivers/stpmic1.h
> drivers: prepare stpmic1 to expose SCMI voltage domains

- core/arch/arm/plat-stm32mp1/drivers/stm32mp1_pmic.c
- core/arch/arm/plat-stm32mp1/stm32_util.h
> plat-stm32mp1: prepare PMIC regus thru SCMI

- core/arch/arm/include/kernel/thread.h
- core/arch/arm/kernel/pseudo_ta.c
- core/arch/arm/kernel/secure_partition.c
- core/arch/arm/kernel/user_ta.c
- core/include/kernel/tee_ta_manager.h
- core/kernel/tee_ta_manager.c
- mk/config.mk
> Refactor some ta mutex usage

- MAINTAINERS
Andrew's email address is bouncing, remove it.
> MAINTAINERS: plat-ti, plat-k3: remove Andrew's address

- core/arch/arm/kernel/thread_a32.S
- core/arch/arm/kernel/thread_a64.S
- core/arch/arm/sm/sm_a32.S
- lib/libutils/ext/include/asm.S
> Function alignment

- core/arch/arm/kernel/thread.c
init_canaries() currently prints the following messages on boot:
...
D/TC:0 0 init_canaries:191 #Stack canaries for stack_abt[3] with top at 0xe19f6f8
D/TC:0 0 init_canaries:191 watch *0xe19f6fc
...
The above text is repeated for each CPU core for both stack_tmp and
stack_abt, as well as for each thread for stack_thread. This is quite
verbose, especially with modern SoCs supporting many cores (16 or 24
is not uncommon). The main purpose is to help with debugging stack
overflows when a debugger is available: when a dead canary is found,
the corrupt stack is shown which allows the developer to set a
watchpoint at the suitable address:
E/TC:0 0 Dead canary at end of 'stack_abt[3]'
In this example, one would set a watchpoint at *0xe19f6fc and re-run the
test to identify at which point the …
> core: do not print canary debug messages on boot

- core/arch/arm/include/mm/core_mmu.h
- core/arch/arm/kernel/boot.c
- core/arch/arm/kernel/secure_partition.c
- core/arch/arm/kernel/thread.c
- core/arch/arm/kernel/user_ta.c
- core/arch/arm/mm/core_mmu.c
- core/arch/arm/mm/mobj.c
- core/arch/arm/mm/mobj_dyn_shm.c
- core/arch/arm/mm/sub.mk
- core/arch/arm/mm/tee_mmu.c
- core/arch/arm/tee/arch_svc.c
- core/arch/arm/tee/svc_cache.c
- core/drivers/crypto/caam/utils/utils_mem.c
- core/include/mm/tee_mmu.h
- core/include/mm/vm.h
- core/kernel/tee_ta_manager.c
- core/kernel/ts_manager.c
- core/kernel/user_access.c
- core/mm/sub.mk
- core/mm/vm.c
- core/pta/benchmark.c
- core/pta/gprof.c
- core/pta/sdp.c
- core/pta/system.c
- core/tee/tee_obj.c
- core/tee/tee_svc.c
- core/tee/tee_svc_cryp.c
- core/tee/tee_svc_storage.c
> Tee mmu refactoring

- ta/pkcs11/src/pkcs11_attributes.c
All optional attributes of an object if not specified in the template
while creating object are  assigned empty value by default in the
current implementation. This works fine for attributes where
specification specifies that default value is not empty or the
attribute is modifiable later.
However for attributes like CKA_ALLOWED_MECHANISM, adding any empty
value results in a failurelater  when attribute of the object are checked
against the mechanism usined in processing crypto operation.
To avoid such errors, split the optional attributes array in 2 parts
- one with the default empty value and ones which don't require the
empty default values. All attributes in the specification
which either should have default value as empty or are allowed to be
modified later by call to …
> [RFC] ta: pkcs11: Handle optional attributes without empty default values

- core/drivers/crypto/caam/acipher/caam_rsa.c
- core/lib/libtomcrypt/rsa.c
- lib/libmbedtls/core/rsa.c
> Fix potential memory leaks in RSA

- core/lib/libtomcrypt/src/pk/dh/dh_make_key.c
> LTC fix DH keygen xsize

- core/arch/arm/kernel/stmm_sp.c
Remove the boolean return value from local functions
stmm_handle_mem_mgr_service(), stmm_handle_storage_service(),
spm_eret_error() and spm_handle_direct_req() that all end
returning to secure partition (StMM) execution.
Rename return_helper() to return_nsec_helper() and remove its
return value as it only prepare a return into normal world.
> core: stmm: remove useless return values to local svc handlers

- core/arch/arm/kernel/kern.ld.S
> Fix for Clang + pager + ASLR (QEMUv8)

- .shippable.yml
- core/arch/arm/plat-mediatek/conf.mk
- core/arch/arm/plat-mediatek/main.c
- core/arch/arm/plat-mediatek/platform_config.h
Add OP-TEE support for MT8183 SoC.
> mediatek: add support for MT8183 SoC

- ta/pkcs11/src/pkcs11_attributes.c
- ta/pkcs11/src/pkcs11_helpers.c
- ta/pkcs11/src/pkcs11_helpers.h
- ta/pkcs11/src/processing.c
- ta/pkcs11/src/processing_symm.c
- ta/pkcs11/src/token_capabilities.c
As I was trying to run some hmac tests from pkcs11test (https://github.com/google/pkcs11test), those were failing earlier. With these fixes, the HMAC hash related tests in pkcs11test pass now.
[----------] 10 tests from HMACs/HmacTest
[ RUN      ] HMACs/HmacTest.SignVerify/0
[       OK ] HMACs/HmacTest.SignVerify/0 (47 ms)
[ RUN      ] HMACs/HmacTest.SignVerify/1
[       OK ] HMACs/HmacTest.SignVerify/1 (41 ms)
[ RUN      ] HMACs/HmacTest.SignVerify/2
[       OK ] HMACs/HmacTest.SignVerify/2 (39 ms)
[ RUN      ] HMACs/HmacTest.SignVerify/3
[       OK ] HMACs/HmacTest.SignVerify/3 (40 ms)
[ RUN      ] HMACs/HmacTest.SignVerify/4
[       OK ] HMACs/HmacTest.SignVerify/4 (41 ms)
[ RUN      ] HMACs/HmacTest.SignFailVerify/0
[       OK ] HMACs/HmacTest.SignFailVerify/0 (43 ms)
[ RUN      ] …
> Key size fixes for HMAC Hash Mechanisms.

- core/include/kernel/tee_time.h
- lib/libutee/include/user_ta_header.h
> Remove unused declarations

- ta/pkcs11/src/entry.c
- ta/pkcs11/src/object.c
- ta/pkcs11/src/pkcs11_attributes.c
- ta/pkcs11/src/pkcs11_helpers.h
- ta/pkcs11/src/pkcs11_token.c
- ta/pkcs11/src/processing.c
- ta/pkcs11/src/processing.h
- ta/pkcs11/src/processing_aes.c
2 fixup commits (2 first in the series) and some minor cleanup changes.
> ta: pkcs11: fix return code and memory leakage + minor cleanup

- core/crypto/aes-cts.c
- core/tee/tee_svc_cryp.c
- lib/libutee/tee_api_operations.c
Takes care of issue https://github.com/OP-TEE/optee_os/issues/4263
> Fix cryp state copy

- ta/pkcs11/src/pkcs11_attributes.c
- ta/pkcs11/src/sanitize_object.c
> PKCS11: Few fixes in error return and sanitizing objects (required for Key Generate Test cases to pass)

- .shippable.yml
Validates the different SE050 configuration options with the Plug And
Trust library.
> shippable: imx8mm/imx6ull - se050 and Plug&Trust library

- ta/pkcs11/src/object.c
- ta/pkcs11/src/pkcs11_attributes.c
> Bug fixes for object type with attribute CKA_PRIVATE

- core/drivers/crypto/se050/core/rsa.c
The supported algorithms for encryption/decryption are:
PKCS1_OAEP
PKCS1_V1_5
Whe using PKCS1_PSS_MGF1 the se050 also has some restrictions on the
hash algorithms that can be used depending on the RSA key size.
Source: Plug And Trust MW documentation, Release v02,14,00 (Apr 03,
2020)
Fixes: https://github.com/OP-TEE/optee_os/issues/4239
> drivers: crypto: se050: limitations on RSA

- ta/pkcs11/src/object.c
Few checks were missing in the implementaion of C_DestroyObject()
as per PKCS#11 Specification. These have been added now.
These checks are
- only session objects can be destroyed during a read only session
- only public objects can be destroyed unless the normal user is
logged in
- Certain objects may not be destroyed. Calling C_DestroyObject on
such objects will result in the CKR_ACTION_PROHIBITED error code.
An application can consult the object's CKA_DESTROYABLE
attribute to determine if an object may be destroyed or not.
> ta: pkcs11: Add more checks before destroying object in a session

- core/tee/tee_rpmb_fs.c
RPMB FS driver may allocates a temporary buffer of size the one provided
by userland caller. These may be big buffer of dozens of kbytes and may
exhaust the heap capacities. Change the implementation to use a 4kByte
temporary buffer to update RPMB data instead of a allocated buffer of
the object target size.
> core: rpmb fs uses mempool for temporary transfer buffers

- core/arch/arm/include/mm/core_mmu.h
- core/arch/arm/kernel/boot.c
- core/arch/arm/mm/core_mmu.c
Fixes https://github.com/OP-TEE/optee_os/issues/4278
> Unmap external dtb

- core/tee/tee_rpmb_fs.c
i tried to optimize `memset()` use rather than a big `memset(blk_buf, 0, TMP_BUF_SIZE);` in the loop.
> core: rpmb: fix initialization of new rpmb data

- ta/pkcs11/include/pkcs11_ta.h
- ta/pkcs11/src/attributes.c
- ta/pkcs11/src/attributes.h
- ta/pkcs11/src/entry.c
- ta/pkcs11/src/object.c
- ta/pkcs11/src/object.h
- ta/pkcs11/src/pkcs11_attributes.c
- ta/pkcs11/src/pkcs11_attributes.h
- ta/pkcs11/src/pkcs11_helpers.c
- ta/pkcs11/src/pkcs11_token.c
- ta/pkcs11/src/pkcs11_token.h
> PKCS11: Support for Object related API's - Find Objects, GetObjectSize, GetAttributeValue

- ta/arch/arm/link.mk
- ta/mk/build-user-ta.mk
> Install in-tree TAs into $(TA_DEV_KIT_DIR)/ta

- lib/libutils/isoc/include/sys/queue.h
Import macro LIST_FOREACH_SAFE from FreeBSD.
> libutils: sys/queue.h: add LIST_FOREACH_SAFE()

- ta/avb/entry.c
```
Use intermediate temporary buffers instead of directly supplying non-secure
buffers to TEE_ReadObjectData()/TEE_CreatePersistentObject().
This fixes TA panics while accessing persistent objects:
E/TC:? 0 TA panicked with code 0xffff0001
E/LD:  Status of TA 023f8f1a-292a-432b-8fc4-de8471358067
...
D/TC:? 0 user_ta_enter:176 tee_user_ta_enter: TA panicked with
code 0xffff0001
Signed-off-by: Igor Opaniuk <igor.opaniuk@foundries.io>
```
> ta: avb: copy data to temporary buffers

- lib/libmbedtls/core/aes_cbc.c
- lib/libmbedtls/core/aes_ctr.c
- lib/libmbedtls/core/aes_ecb.c
- lib/libmbedtls/core/dh.c
- lib/libmbedtls/core/ecc.c
- lib/libmbedtls/core/mbed_helpers.h
- lib/libmbedtls/core/rsa.c
> Fix AES context copy (MBed TLS)

- core/arch/arm/kernel/thread_optee_smc.c
Contiguous shared memory regions need to be considered for allocation
whenever support has been enabled
reopen from: https://github.com/OP-TEE/optee_os/pull/4165 where all the discussion happened but a fix was never delivered.
Without this patch Linux will fail at allocating buffers for I2C when CFG_CORE_DYN_SHM=y (however U-Boot will not)
Since enabling CFG_CORE_DYN_SHM is a requirement for U-boot we can't get around the problem by disabling it as we can do if we want to avoid the kernel allocation issue.
> core: fix shared memory buffer rpc allocation

- core/drivers/crypto/caam/acipher/caam_rsa.c
- core/drivers/crypto/crypto_api/acipher/ecc.c
- core/drivers/crypto/se050/core/cipher.c
- core/drivers/crypto/se050/core/ctr.c
- core/drivers/crypto/se050/core/rsa.c
- core/drivers/crypto/se050/glue/i2c.c
- core/lib/libtomcrypt/ecc.c
- core/lib/libtomcrypt/mpi_desc.c
- core/lib/libtomcrypt/tomcrypt.c
- lib/libmbedtls/core/ecc.c
- lib/libutee/tee_tcpudp_socket.c
> Drop useless & before function names

- core/drivers/crypto/caam/utils/utils_mem.c
Make use of the newly implemented memalign() function for the CAAM
driver.
Remove the previous CAAM memalign() implementation and its associated
debugging structures.
> drivers: caam: make use of generic memalign() implementation

- .shippable.yml
- core/drivers/crypto/se050/adaptors/sub.mk
- core/drivers/crypto/se050/cflags.mk
- core/drivers/crypto/se050/core/sub.mk
- core/drivers/crypto/se050/sub.mk
Track NXP's quaterly Plug-and-Trust updates.
These changes are required to build the latest release .
https://github.com/foundriesio/plug-and-trust
The release
https://github.com/foundriesio/plug-and-trust/tree/v0.0.2
> crypto: se050: Foundries.io Plug-and-Trust update to Release 0.0.2

- ta/pkcs11/src/object.c
- ta/pkcs11/src/pkcs11_attributes.c
- ta/pkcs11/src/pkcs11_token.c
- ta/pkcs11/src/processing.c
- ta/pkcs11/src/processing_symm.c
- ta/pkcs11/src/token_capabilities.c
- ta/pkcs11/src/token_capabilities.h
> ta: pkcs11: Miscellaneous fixes

- core/drivers/crypto/caam/utils/utils_mem.c
Hello,
As discussed with @jenswi-linaro, here are the first two commits of PR https://github.com/OP-TEE/optee_os/pull/4404
Thanks!
> Fixes CAAM memory allocation

- ta/pkcs11/src/sanitize_object.c
> ta: pkcs11: Fix issues when sanitizing and tracing indirect attributes

- ta/trusted_keys/entry.c
Commit e12c9f67d12c ("core: strict buffer check in syscalls following GP 1.1")
has switched to stricter buffer checks to reside in TA private memory.
So accordingly fix buffer allocations corresponding to TEE_GenerateRandom
and TEE_AEDecryptFinal APIs.
> ta: trusted_keys: Fix to align with strict buffer checks

- ta/pkcs11/src/entry.c
- ta/pkcs11/src/pkcs11_attributes.c
- ta/pkcs11/src/pkcs11_attributes.h
- ta/pkcs11/src/processing.c
- ta/pkcs11/src/processing.h
- ta/pkcs11/src/processing_symm.c
> ta: pkcs11: Some fixes and improvements in C_DeriveKey() flow to make it more generic and reusable for C_UnwrapKey()

- core/arch/arm/plat-stm32mp1/main.c
- core/arch/arm/plat-stm32mp1/platform_config.h
> plat-stm32mp1: simplify IO mapping

- core/arch/arm/plat-stm32mp1/scmi_server.c
- core/drivers/scmi-msg/base.c
- core/drivers/scmi-msg/clock.c
- core/drivers/scmi-msg/common.h
- core/drivers/scmi-msg/entry.c
- core/drivers/scmi-msg/reset_domain.c
- core/drivers/scmi-msg/smt.c
- core/drivers/scmi-msg/voltage_domain.c
- core/include/drivers/scmi-msg.h
- mk/config.mk
> scmi-msg: fixes

- ta/pkcs11/src/object.c
- ta/pkcs11/src/pkcs11_attributes.c
> ta: pkcs11 - Fixes for symmetric key and indirect templates

- ta/pkcs11/src/token_capabilities.c
Remove the inline comment that states the implementation does not yet
support any mechanism as is it not true.
> ta: pkcs11: fix comment stating no mechanism is supported

- core/arch/arm/mm/tee_pager.c
- mk/compile.mk
> Pager tblidx

- core/arch/arm/plat-imx/crypto_conf.mk
- core/arch/arm/plat-ls/crypto_conf.mk
- core/drivers/crypto/caam/acipher/caam_ecc.c
- core/drivers/crypto/caam/acipher/sub.mk
- core/drivers/crypto/caam/caam_ctrl.c
- core/drivers/crypto/caam/include/caam_acipher.h
- core/drivers/crypto/caam/include/caam_desc_defines.h
- core/drivers/crypto/caam/include/caam_trace.h
Hello,
Here is the ECC implementation for the CAAM.
Thanks!
> ECC CAAM driver implementation

- core/arch/arm/kernel/thread.c
Use macro THREAD_ID_INVALID instead of -1 in thread.c.
> core: arm: thread: use THREAD_ID_INVALID

- core/arch/arm/plat-stm32mp1/conf.mk
- core/arch/arm/plat-stm32mp1/nsec-service/stm32mp1_svc_setup.c
- core/arch/arm/plat-stm32mp1/sub.mk
- core/drivers/scmi-msg/smt.c
- core/include/drivers/scmi-msg.h
> scmi-msg: stub drivers API functions

- ta/pkcs11/src/object.c
This change remove the hacky handling of whether object was previously in
a list of not. This is replaced by default registering pkcs11 objects
in a temporary list at object creation so it can be blindly removed
from its list when destroyed, and can be safely move to its destination
list (either a session object list or a token object list) when
object is successfully created and registered.
> ta: pkcs11: use a temporary list for object under creation

- core/arch/arm/kernel/entry_a32.S
- core/arch/arm/kernel/misc_a32.S
- core/arch/arm/kernel/misc_a64.S
- lib/libmbedtls/mbedtls/library/md2.c
- lib/libmbedtls/mbedtls/library/md4.c
- lib/libmbedtls/mbedtls/library/md5.c
- lib/libmbedtls/mbedtls/library/ripemd160.c
- lib/libmbedtls/mbedtls/library/sha512.c
- lib/libutils/ext/include/asm.S
> Fix Clang12 warnings

- core/arch/arm/plat-stm32mp1/conf.mk
- core/arch/arm/plat-stm32mp1/drivers/stm32mp1_clk.c
- core/arch/arm/plat-stm32mp1/scmi_server.c
> plat-stm32mp1: fix clock, scmi channel IDs and disable BGET tests

- core/arch/arm/plat-imx/crypto_conf.mk
- core/arch/arm/plat-ls/crypto_conf.mk
- core/drivers/crypto/caam/acipher/caam_dh.c
- core/drivers/crypto/caam/acipher/sub.mk
- core/drivers/crypto/caam/caam_ctrl.c
- core/drivers/crypto/caam/include/caam_acipher.h
- core/drivers/crypto/caam/include/caam_desc_defines.h
- core/drivers/crypto/caam/include/caam_trace.h
- core/drivers/crypto/crypto_api/acipher/dh.c
- core/drivers/crypto/crypto_api/acipher/sub.mk
- core/drivers/crypto/crypto_api/include/drvcrypt.h
- core/drivers/crypto/crypto_api/include/drvcrypt_acipher.h
Hello,
Another crypto contribution : the Diffie-Hellman implementation in the CAAM and the associated layer in the crypto hardware API!
Thanks!
> DH CAAM driver implementation

- core/arch/arm/include/mm/tee_pager.h
- core/arch/arm/mm/tee_pager.c
This is a step preparing to merge struct tee_pager_area with struct vm_region.
> Pager area

- core/arch/arm/plat-imx/crypto_conf.mk
- core/arch/arm/plat-ls/crypto_conf.mk
- core/drivers/crypto/caam/acipher/caam_dsa.c
- core/drivers/crypto/caam/acipher/caam_prime_dsa.c
- core/drivers/crypto/caam/acipher/caam_prime_rsa.c
- core/drivers/crypto/caam/acipher/caam_rsa.c
- core/drivers/crypto/caam/acipher/local.h
- core/drivers/crypto/caam/acipher/sub.mk
- core/drivers/crypto/caam/caam_ctrl.c
- core/drivers/crypto/caam/include/caam_acipher.h
- core/drivers/crypto/caam/include/caam_desc_ccb_defines.h
- core/drivers/crypto/caam/include/caam_desc_defines.h
- core/drivers/crypto/caam/include/caam_desc_helper.h
- core/drivers/crypto/caam/include/caam_trace.h
- core/drivers/crypto/crypto_api/acipher/dsa.c
- core/drivers/crypto/crypto_api/acipher/sub.mk
- core/drivers/crypto/crypto_api/include/drvcrypt.h
- core/drivers/crypto/crypto_api/include/drvcrypt_acipher.h
Hello,
Yet another CAAM driver : DSA implementation and the DSA Crypto API implementation.
Thanks!
> DSA CAAM driver implementation

- .azure-pipelines.yml
- core/arch/arm/plat-imx/conf.mk
- core/arch/arm/plat-imx/imx-regs.h
- core/arch/arm/plat-imx/registers/imx8m.h
- core/drivers/crypto/caam/hal/sub.mk
Hello,
A small pull-request to add the i.MX8MP support.
Thanks!
> Add the support for i.MX8MP

- core/tee/tee_rpmb_fs.c
- mk/config.mk
Add a short description for some CFG_RPMB_* configuration switches
not described anywhere.
> config: add description for CFG_RPMB_* config switches

- core/arch/arm/kernel/boot.c
- core/arch/arm/kernel/entry_a32.S
- core/arch/arm/kernel/entry_a64.S
> Ffa updates

- core/arch/arm/kernel/spmc_sp_handler.c
Found some small errors in the FF-A spmc_sp_handler.
This Pull request fixes these.
> FF-A: spmc_sp_handler fixes

- core/arch/arm/kernel/thread_a32.S
- lib/libutils/isoc/bget_malloc.c
> Small fixes

- core/arch/arm/plat-imx/registers/imx8m.h
- core/drivers/imx_i2c.c
Add support for iMX8MQ.
Signed-off-by: David Griego <david.griego@foundries.io>
> drivers: imx_i2c: add support for MX8MQ

- core/arch/arm/include/kernel/stmm_sp.h
- core/arch/arm/kernel/kern.ld.S
- core/arch/arm/kernel/link_dummies_paged.c
- core/arch/arm/kernel/secure_partition.c
- core/arch/arm/kernel/stmm_sp.c
- core/arch/arm/mm/mobj_dyn_shm.c
- core/arch/arm/mm/mobj_ffa.c
- core/arch/arm/mm/tee_pager.c
- core/include/kernel/wait_queue.h
- core/kernel/user_ta.c
- core/kernel/wait_queue.c
- core/mm/fobj.c
- core/mm/mobj.c
- lib/libutils/ext/include/compiler.h
This removes about 7 kB of unpaged code and data from QEMU virt.
> Unpaged partitioning

- core/include/signed_hdr.h
- core/kernel/ree_fs_ta.c
> Shdr parsing fix

- .azure-pipelines.yml
Some cleanup in the Azure CI script. No functional change.
> Azure CI updates

- core/arch/arm/plat-imx/drivers/imx_csu.c
Reserve the RNGB to the TrustZone.
Reviewed-by: Rouven Czerwinski <r.czerwinski@pengutronix.de>
> drivers: csu: RNGB TZ reservation on imx6ull/sl/sll

- core/arch/arm/plat-stm32mp1/conf.mk
- core/arch/arm/plat-stm32mp1/shared_resources.c
> plat-stm32mp1: fix helper function and increase CFG_DTB_MAX_SIZE

- CHANGELOG.md
Update CHANGELOG for 3.14.0 and collect Tested-by tags.
> Update CHANGELOG.md for 3.14.0

- ta/pkcs11/src/persistent_token.c
> ta: pkcs11: Remove dual crypto operations from token capability

- MAINTAINERS
manish.tomar@nxp.com is bouncing. His GitHub handle (@manishtomarnxp)
has had no activity since March 2020 and I found no way to reach him.
So, remove him from MAINTAINERS.
> MAINTAINERS: remove reviewer of ls_gpio.c and ls_dspi.c

- lib/libutee/tee_api.c
The GlobalPlatform TEE internal api specification mentions the following
about zero sized buffer allocations:
"The value returned is undefined but guaranteed to be different from NULL.
The Trusted Application SHALL NOT access the returned pointer.
The Trusted Application SHOULD panic if the memory pointed to by such a pointer is accessed for
either read or write"
But, we would never observe a TA panic because a zero size is internally
translated to 1 and finally to (2 * sizeof(long)) in the bget() function.
This patch handles this aspect so to naturally pass size=0 too across
the different layers.
Signed-off-by: Sadiq Hussain <sadiq.muchumarri@intel.com>
> libutils: Handle zero-sized buffer allocations

- core/arch/arm/plat-imx/crypto_conf.mk
- core/drivers/crypto/caam/caam_jr.c
- core/drivers/crypto/caam/caam_rng.c
- core/drivers/crypto/caam/hal/common/hal_ctrl.c
- core/drivers/crypto/caam/hal/common/hal_rng.c
- core/drivers/crypto/caam/hal/common/registers/rng_regs.h
- core/drivers/crypto/caam/hal/common/registers/version_regs.h
- core/drivers/crypto/caam/hal/imx_6_7/hal_clk_mx6.c
- core/drivers/crypto/caam/hal/imx_6_7/hal_clk_mx7.c
- core/drivers/crypto/caam/hal/imx_6_7/hal_clk_mx7ulp.c
- core/drivers/crypto/caam/utils/utils_dmaobj.c
- core/drivers/crypto/crypto_api/acipher/dsa.c
- core/drivers/crypto/crypto_api/acipher/ecc.c
Hello,
Here are some patches for the CAAM driver. Most of these patches fix minor issues in the CAAM.
However, the patch fixing the issue I found last week in xtest is the following : `drivers: caam: fix missing output additional length`
Thanks,
Clement
> CAAM driver minor fixes

- core/arch/arm/tee/cache.c
> core: update reference link to PrimeCell Cache Controller

- core/arch/arm/mm/core_mmu.c
With short table mappings, that is without LPAE, the user va range is
defined at the lowest addresses. Depending on the seed supplied this
could conflict with chosen base address for core mappings. Add a check
early in assign_mem_va() to avoid such conflicts.
Without this patch there's a risk of occasional panics like:
E/TC:0 0 Panic 'issue in linear address space' at core/arch/arm/mm/core_mmu.c:2147 <check_pa_matches_va>
E/TC:0 0 TEE load address @ 0xa34000
E/TC:0 0  0x00a3a901
> core: fix ASLR problem with short table mappings

- core/arch/arm/include/ffa.h
- core/arch/arm/include/kernel/secure_partition.h
- core/arch/arm/include/kernel/thread_spmc.h
- core/arch/arm/kernel/secure_partition.c
- core/arch/arm/kernel/spmc_sp_handler.c
- core/arch/arm/kernel/thread_spmc.c
This is a continuation of [core: Add FFA_PARTITION_INFO](https://github.com/OP-TEE/optee_os/pull/4556
)
The PR was automatically closed.  None of the patches has been changed however:
We created some test for the FF-A commands and SPs. 
I have a manifest file that can be used:
`repo init -u  https://review.trustedfirmware.org/OP-TEE/manifest -m psa-sp-fvp.xml -b refs/changes/99/10999/1`
Manifest file that can be used to tests:
repo init -u https://review.trustedfirmware.org/OP-TEE/manifest -m psa-sp-fvp.xml -b refs/changes/99/10999/1
Changes made in the manifest:
Build: Change the build to be able to automatically build and add SPs to the image
optee_os: This PR
Trusted-service: Add the trusted services repo, this is where the test SPs live.
optee_test: The host component of the SPMC test …
> core: Add FFA_PARTITION_INFO continuation

- .gitignore
- core/pta/tests/fs_htree.c
- core/tee/tadb.c
- ta/pkcs11/src/object.c
- ta/pkcs11/src/processing_symm.c
We have found several issues ranging from a function having no default return value to a double-free.
These issues were found with SVACE static analysis tool.
> Assorted fixes

- core/crypto/sub.mk
- core/lib/libtomcrypt/sub.mk
> Build fixes

- core/arch/arm/kernel/tee_time.c
- core/arch/arm/mm/mobj_dyn_shm.c
- core/kernel/console.c
- core/kernel/lockdep.c
- core/kernel/wait_queue.c
- core/lib/libtomcrypt/sub.mk
- core/pta/gprof.c
- core/tee/entry_std.c
- core/tee/socket.c
- core/tee/tadb.c
- core/tee/tee_fs_rpc.c
- core/tee/tee_svc_cryp.c
- lib/libmbedtls/sub.mk
- lib/libutee/tee_api_arith_mpi.c
- mk/compile.mk
- mk/config.mk
- ta/avb/entry.c
> [RFC] Use -Wdeclaration-after-statement in CI

- core/drivers/stm32_bsec.c
> plat-stm32mp1: BSEC drivers fixes and updates

- core/drivers/crypto/se050/adaptors/include/se050_utils.h
- core/drivers/crypto/se050/adaptors/utils/scp_config.c
- core/drivers/crypto/se050/adaptors/utils/utils.c
- core/drivers/crypto/se050/core/apdu.c
- core/drivers/crypto/se050/core/ctr.c
- core/drivers/crypto/se050/core/ecc.c
- core/drivers/crypto/se050/core/rsa.c
- core/drivers/crypto/se050/core/scp03.c
- core/drivers/crypto/se050/core/sub.mk
- core/drivers/crypto/se050/crypto.mk
- core/include/crypto/crypto.h
- core/include/crypto/crypto_se.h
- core/pta/apdu.c
- core/pta/scp03.c
- core/pta/sub.mk
- lib/libutee/include/pta_apdu.h
- lib/libutee/include/pta_scp03.h
https://github.com/foundriesio/plug-and-trust/releases/tag/v0.0.4
the apdu pta was tested with this uboot version on imx8mm
https://github.com/ldts/u-boot/commits/se050-apdu-ta
> se050: plug and trust update 0.0.4

- ta/pkcs11/src/object.c
> ta: pkcs11: remove unnecessary code

- core/arch/arm/dts/sama5d2.dtsi
- core/arch/arm/plat-sam/conf.mk
- core/arch/arm/plat-sam/platform_config.h
- core/drivers/atmel_trng.c
- core/drivers/sub.mk
> plat-sam: add sama5d2 TRNG driver

- core/arch/arm/mm/core_mmu_lpae.c
Two small fixes in the LPAE code.
> LPAE small fixes

- lib/libutils/ext/trace.c
The first patch is a fix that is useless if the second patch is applied, so perhaps I should drop it?
> libutils: trace: support more than 100 threads and cores

- core/drivers/atmel_shdwc.c
- core/drivers/atmel_shdwc_a32.S
- core/drivers/clk/sam/at91_clk.h
- core/drivers/clk/sam/sama5d2_clk.c
- core/drivers/sub.mk
- core/include/drivers/atmel_shdwc.h
- core/include/drivers/sam/at91_ddr.h
This PR adds driver for atmel SAM shutdown controller.
> drivers: sam: add shutdown controller driver

- .github/workflows/stales.yml
- Update 'stale' from v3.0.7 to v4.0.1.
- Give 'write' permissions to actions (pull requests and issues).
- Add and set (to true)
remove-issue-stale-when-updated
remove-pr-stale-when-updated
which will automatically remove the 'Stale' label when someone adds a
new comment to a ticket marked as stale.
> GitHub actions: General updates

- scripts/sign_encrypt.py
Allow encryption key type to be overridden from command-line. Defaults
to SHDR_ENC_KEY_DEV_SPECIFIC.
Signed-off-by: Donald Chan <hoiho@amazon.com>
> scripts/sign_encrypt.py: add flags for the encryption key type

- scripts/sign_encrypt.py
A few constant values would have been better if replaced with constant
definitions
Signed-off-by: Donald Chan <hoiho@amazon.com>
> scripts/sign_encrypt.py: readability improvements

- core/arch/arm/kernel/stmm_sp.c
- core/arch/arm/kernel/thread.c
- core/arch/arm/kernel/thread_optee_smc.c
- core/arch/arm/kernel/thread_spmc.c
- core/arch/arm/mm/mobj_dyn_shm.c
- core/arch/arm/mm/mobj_ffa.c
- core/include/mm/mobj.h
- core/kernel/msg_param.c
- core/kernel/pseudo_ta.c
- core/kernel/ree_fs_ta.c
- core/kernel/user_ta.c
- core/mm/mobj.c
- core/pta/benchmark.c
- core/pta/gprof.c
- core/tee/tadb.c
- core/tee/tee_rpmb_fs.c
- core/tee/tee_supp_plugin_rpc.c
- core/tee/tee_svc.c
> Mobj get va

- core/arch/arm/mm/mobj_dyn_shm.c
- core/arch/arm/mm/mobj_ffa.c
> Fix race in mobj_inc_map

- core/drivers/crypto/se050/core/ecc.c
Allow clients to inject their own keypairs to derive the secret - the
previous implementation only allowed for secure element NVM based
keypairs to be used.
By default, the secure element does not store all the possible EC
curves in its internal memory; however attempting to inject a keypair
when the curve is not in the secure element would cause the injection
to fail.
This commit addresses that situation by generating those curves in the
SE whenever they are not available.
Tested with:
TEE_ALG_ECDH_P192, 
TEE_ALG_ECDH_P224, 
TEE_ALG_ECDH_P256
TEE_ALG_ECDH_P384 
TEE_ALG_ECDH_P521 
**fixes xtest 4009**
> crypto: drivers: se050: ecc shared secret

- scripts/sign_encrypt.py
Adds a new option 'verify' to sign_encrypt.py to verify whether a
Trusted Application is signed correctly.
Required arguments: --uuid, --in, --key
Signed-off-by: Donald Chan <hoiho@amazon.com>
> scripts/sign_encrypt.py: Support verification of a signed TA

- core/drivers/crypto/se050/core/ecc.c
Pad small messages with zeroes during sign/verify.
Fixes xtest pkcs11_1019
> crypto: drivers: se050: ecc: fix sign/verify of small messages

- core/tee/tee_ree_fs.c
Updates ree_fs_open() to close the dirfile on error. This should take
care of the rare case were the internal file handle in the dirfile has
been closed due to an error.
Fixes an error like:
E/TC:1 1 Core data-abort at address 0xc0 (translation fault)
E/TC:1 1  esr 0x96000006  ttbr0 0x600000e19a020   ttbr1 0x00000000   cidr 0x0
E/TC:1 1  cpu #1          cpsr 0x00000004
E/TC:1 1  x0  00000000000000c0 x1  0000000000000078
E/TC:1 1  x2  000000000e1a0c88 x3  000000000e1a0c28
E/TC:1 1  x4  0000000000000078 x5  000000000e128220
E/TC:1 1  x6  000000000000001f x7  0000000000000000
E/TC:1 1  x8  0000000000000000 x9  0000000000000000
E/TC:1 1  x10 0000000000000000 x11 0000000000000000
E/TC:1 1  x12 0000000000000000 x13 0000000040014f80
E/TC:1 1  x14 0000000000000000 x15 0000000000000000
E/TC:1 1 …
> core: ree_fs_open(): close dirfile on error

- core/arch/arm/plat-stm32mp1/drivers/stm32mp1_pmic.c
- core/arch/arm/plat-stm32mp1/main.c
- core/arch/arm/plat-stm32mp1/scmi_server.c
- core/arch/arm/plat-stm32mp1/stm32_util.h
- core/drivers/clk/clk-stm32mp15.c
- core/drivers/stm32_gpio.c
- core/drivers/stm32_i2c.c
- core/drivers/stm32_rng.c
- core/drivers/stm32_uart.c
- core/include/drivers/stm32_i2c.h
- core/include/drivers/stm32_uart.h
> plat-stm32mp1: move platform drivers to clk framework

- core/arch/arm/dts/sama5d2.dtsi
- core/arch/arm/plat-sam/conf.mk
- core/arch/arm/plat-sam/main.c
- core/arch/arm/plat-sam/sam_sfr.h
- core/drivers/atmel_saic.c
- core/drivers/sub.mk
- core/include/drivers/atmel_saic.h
Add a driver for sama5d2 interrupt handler and initialize it in sama5d2 platform.
> drivers: add atmel_saic driver

- core/arch/arm/kernel/thread_optee_smc.c
- core/arch/arm/kernel/thread_spmc.c
- core/arch/arm/plat-stm/main.c
- core/include/tee/entry_std.h
- core/kernel/notif.c
- core/mm/mobj.c
- core/mm/vm.c
- core/tee/entry_std.c
- lib/libutils/ext/include/compiler.h
- lib/libutils/isoc/include/assert.h
- mk/compile.mk
Don't include optee_smc.h outside of core/arch/arm.
> Optee_smc_h

- core/drivers/crypto/se050/session.c
Failure to initialize the SE05x device is a critical operation as it will
effectively disable ciphers configured at build time.
This also matches the behaviour implemented by the other crypto drivers.
> drivers: crypto: se050: panic on initialization error

- core/include/kernel/boot.h
Adds a comment describing get_aslr_seed().
> core: add description for get_aslr_seed()

- MAINTAINERS
Replace my personal email address with my professional one. My address
@forissier.org is still valid but less preferred for Linaro-related
development.
> MAINTAINERS: update my email address

- MAINTAINERS
Victor is not with Linaro anymore, so remove him from MAINTAINERS.
> MAINTAINERS: remove Victor (Linaro)

- MAINTAINERS
tee-dev@lists.linaro.org is deprecated in favor of
op-tee@lists.trustedfirmware.org. Update MAINTAINERS accordingly.
> MAINTAINERS: update address of OP-TEE mailing list

- MAINTAINERS
Sandeep's email bounces, therefore remove him from MAINTAINERS. Since
there is now reviewer left in the "Broadcom ns3" subsystem, change its
status from Maintained to Orphan.
CC: Broadcom <bcm-optee-feedback-list.pdl@broadcom.com>
> MAINTAINERS: remove Sandeep (Broadcom ns3)

- CHANGELOG.md
- mk/config.mk
Update CHANGELOG for 3.17.0 and collect Tested-by tags.
> Update CHANGELOG for 3.17.0

- .azure-pipelines.yml
Add config for building the S-EL1 SPMC with support for S-EL0 SPs.
> ci: azure: add build for CFG_SECURE_PARTITION=y

- lib/libutils/isoc/bget_malloc.c
With memory tagging realloc() should only untag the old buffer if the
allocation of a new buffer is successful.
The implementation of realloc() prior to this patch is based on bgetr().
This is not so convenient with MTE enabled since the old buffer must be
untagged before calling bgetr(). If realloc() fails the memory tags must
be restored, but this was not done.
Restoring the tags is made somewhat more complicated by the fact that
the size reported by bget_buf_size() may actually be larger than the
size of the tagged buffer. Memalign() is sometimes forced to allocate
buffers larger than requested in order to honor the requested alignment.
So instead of using bgetr(), realloc() is implemented using bget(),
memcpy(), memset() and brel() as needed. This is the same thing that
bgetr() did, …
> libutils: fix MTE error in realloc()

- scripts/symbolize.py
When a TA panics, the TEE core shows the panic code as follows:
E/TC:? 0 TA panicked with code 0xffff000f
The value is whatever was passed to TEE_Panic() by the TA or the library
that caused the panic; typically, the TEE Intenal Core API functions
implemented in libutee. It quite often happens that this value is a
TEE_Result code. Therefore it is convenient to translate the hexadecimal
value to a symbolic name (TEE_ERROR_*). With this commit, if a match is
found, the name is shown in parentheses like so:
E/TC:? 0 TA panicked with code 0xffff000f (TEE_ERROR_SECURITY)
If the code doesn't correspond to a known TEE_Result value however
nothing is appended to the output.
Suggested-by: Peter Griffin <peter.griffin@linaro.org>
> symbolize.py: translate TA panic codes

- core/drivers/scmi-msg/clock.c
- core/drivers/scmi-msg/common.h
- core/drivers/scmi-msg/entry.c
- core/drivers/scmi-msg/smt.c
- core/drivers/scmi-msg/voltage_domain.c
- core/include/drivers/scmi-msg.h
- mk/config.mk
Fixes and changes in scmi-msg drivers, found during review of https://github.com/OP-TEE/optee_os/pull/5277.
> scmi-msg drivers: various fixes and enhancement

- core/drivers/scmi-msg/base.c
SCMI fixes from a issue reported in the LKML.
> scmi-msg: fixes in scmi base protocol

- core/arch/arm/plat-sam/conf.mk
- core/drivers/atmel_tcb.c
- core/drivers/sub.mk
Add Atmel TCB driver and enable it for plat-sam.
> drivers: add atmel_tcb driver

- core/drivers/pm/sam/pm_suspend.S
Clarify that this file was imported from Linux and relicensed to avoid
any licensing issue. This will require @noglitch acked and also could
be nice to get it from @claudiubeznea.
Thanks !
> drivers: pm: sam: clarify that the pm_suspend.S file was relicensed

- ldelf/ta_elf_rel.c
When processing a dynamic relocation for a weak undefined symbol, it is
not an error if the symbol is not found (such a symbol should resolve
to zero). The current code doesn't make a special case of this; it sets
the value to zero *after* the symbol lookup. That's OK when the binary
uses the legacy dynamic symbol table (DT_HASH format), because undefined
symbols are present in it. However, things will break when we switch to
the newer DT_GNU_HASH format which doesn't include them.
Update the code to prepare the DT_GNU_HASH support.
> ldelf: improve handling of weak undefined symbols

- core/include/mm/vm.h
- core/mm/vm.c
> Misc page tables

- core/pta/scmi.c
> core: pta: scmi: Misc fixes

- core/arch/arm/mm/pgt_cache.c
- core/include/mm/pgt_cache.h
- core/mm/core_mmu.c
- core/mm/vm.c
> core: handle large holes in S-EL0 map 

- core/arch/arm/kernel/thread_optee_smc.c
This change fixes an issue found in tag 3.17.0.
> Fixes commit [1] that changed implementation of the standard invocation
> SMC command to introduce invocation with RPC shared memory reference.
> A wrong logic was implemented to free RPC buffer on standard invocation
> completion. This change fixes that by freeing the shared memory when
> pre-allocation is disable by config switch or runtime service, not when
> it is enable.
>
>  Fixes: feb290a51087 ("core: add OPTEE_SMC_CALL_WITH_RPC_ARG")
> core: arm: kernel: fix rpc shm free when prealloc is disable

- core/arch/arm/plat-totalcompute/conf.mk
- core/arch/arm/plat-totalcompute/platform_config.h
Added TC2 platform support
Signed-off-by: Rupinderjit Singh <rupinderjit.singh@arm.com>
> plat-totalcompute: Introduce TC2

- .github/workflows/ci.yml
The Azure CI recently stopped working with frequent "no space left on
device" errors when fetching the Docker image used by the QEMUv8_check
and QEMUv8_build_Rust jobs [1]. Take this opportunity to migrate to
GitHub Actions which has similar or better capabilities (better
integration with GitHub UI, no need for an Azure account or project,
built-in caching capability for build artifacts, more concurrent jobs
and longer timeouts [2]).
No functional change except for cosmetic things (job names) and the
handling of the build cache in the multi-platform build job. Previously,
files could be uploaded to the cache server before the end of the
script. As a result, if a build would time out it would usually be
enough to just restart it, then the new run would obtain files from the
previous run …
> ci: migrate from Azure pipelines to GitHub actions

- .github/workflows/ci.yml
- MAINTAINERS
- core/arch/arm/plat-corstone1000/conf.mk
- core/arch/arm/plat-corstone1000/main.c
- core/arch/arm/plat-corstone1000/platform_config.h
- core/arch/arm/plat-corstone1000/sub.mk
These changes are to add corstone1000 platform to optee
core.
arch/arm/plat-vexpress is taken as a reference to make
these changes.
Signed-off-by: Vishnu Banavath <vishnu.banavath@arm.com>
> plat-corstone1000: add corstone1000 platform

- lib/libmbedtls/core/rsa.c
We are doing performance tuning on the PKSC11 TA and the RSA key generation speed was one area that needed improvements. The main bottleneck is the source of random bits that in any real system will be a slow hardware TRNG.
Let's do like most crypto libraries do and put a DRBG between the key generator and the TRNG. Our work focuses only on the performance with mbedtls as the core crypto library since it had the overall best performance for asymmetric crypto.
For mbedtls there was a choice between CTR and HMAC DRBG. I have no preference on one or the other, the choice of CTR was simply because its header file already was included in the rsa.c file. Perhaps a hint that someone had intended to do this work earlier.
Performance diff on RSA 2048 key generation for our system with Cortex A53 @ …
> core: mbedtls: Use a DRBG to speed up RSA key generation

- .github/workflows/ci.yml
- core/arch/arm/plat-imx/conf.mk
- core/arch/arm/plat-imx/imx-common.c
- core/arch/arm/plat-imx/imx-regs.h
- core/arch/arm/plat-imx/imx.h
- core/arch/arm/plat-imx/registers/imx93.h
> Add imx93 support

- core/arch/arm/plat-stm32mp1/main.c
- core/drivers/imx/dcp/dcp_huk.c
> gcc12 fixes

- core/drivers/crypto/caam/acipher/caam_ecc.c
- core/drivers/crypto/crypto_api/acipher/ecc.c
> nist p521 - fix key size

- core/arch/arm/plat-imx/registers/imx8m.h
- core/drivers/imx_i2c.c
> Imx8mn i2c driver

- core/arch/arm/plat-versal/conf.mk
- core/arch/arm/plat-versal/link.mk
reference: https://github.com/OP-TEE/optee_os/pull/5426
> Versal - platform updates

- core/arch/arm/kernel/thread_optee_smc.c
The error messages printed when the non-secure world fails to allocate shared memory may be misleading misleading:
E/LD:  init_elf:453 sys_open_ta_bin(cb3e5ba0-adf1-11e0-998b-0002a5d5c51b)
E/TC:? 0 ldelf_init_with_ldelf:131 ldelf failed with res: 0xffff000c
This looks like an out-of-memory condition (0xffff000c = TEE_ERROR_OUT_OF_MEMORY) in the TEE core ("E/TC"), in other words insufficient core heap space. Add the following message to help pinpoint the issue:
[Edit]~~E/TC:? 0 get_rpc_alloc_res:645 RPC allocation failed in non-secure world: ret=0xffff000c ret_origin=0x2~~
E/TC:? 0 get_rpc_alloc_res:645 RPC allocation failed. Non-secure world result: ret=0xffff000c ret_origin=0x2
This situation can be reproduced by killing tee-supplicant and invoking a TA. When the CA is interrupted …
> core: rpc: log error when allocation fails in non-secure world

- core/drivers/crypto/se050/glue/i2c_stm32.c
- core/drivers/crypto/se050/sub.mk
- core/drivers/stm32_i2c.c
> stm32 i2c: fix master mode reads, and add support for the NXP SE050 crypto device.

- core/arch/arm/plat-versal/conf.mk
- core/arch/arm/plat-versal/platform_config.h
- core/drivers/sub.mk
- core/drivers/versal_mbox.c
- core/include/drivers/versal_mbox.h
Mailbox driver to communicate with the PLM firmware executing on the
Microblaze processor.
reference: https://github.com/OP-TEE/optee_os/pull/5426
> drivers: versal: mailbox communication

- .github/workflows/ci.yml
Update the Plug-and-Trust to the latest release 04.02.00
> ci: se05x crypto driver: update plug-and-trust

- core/drivers/sub.mk
- core/drivers/versal_pm.c
- core/include/drivers/versal_pm.h
Calls the TF-A exported SiP services.
reference https://github.com/OP-TEE/optee_os/pull/5426
> drivers: versal: PM service

- MAINTAINERS
Add Versal ACAP drivers maintainer
> MAINTAINERS: Versal ACAP drivers

- core/drivers/xiphera_trng.c
If for some reason getting new random values take a bit longer toggle
interrupt masks on/off while waiting.
This allows pending interrupts to be served faster in REE side as getting
new random might not be that important. At the same time it gives more
time for random number generation to complete and not just performing
spinning and waiting.
It was originally recommended by TRNG vendor not to cache previous partial
results in memory. TRNG itself is rather fast so there should
be always fresh bytes available for consumption. Thus to simplify the code
remove the FIFO construct.
> drivers: xiphera_trng: Allow interrupts while waiting for random

- lib/libutils/isoc/bget.c
In the case of wipe = true and previous buffer is free,    memset
the current buffer, rather then current buffer with previous free
buffer.
Signed-off-by: Zengxx <zengxiaoxu@huawei.com>
For more details, please see:(https://github.com/OP-TEE/optee_os/issues/5542)
> libutils: brel: bugfix memset scope larger than expected

- core/arch/arm/mm/pgt_cache.c
- core/mm/vm.c
Fixes https://github.com/OP-TEE/optee_os/issues/5614
> core: mm: fix error flushing unused pgt's

- core/drivers/crypto/se050/adaptors/apis/sss.c
- core/drivers/crypto/se050/adaptors/utils/scp_config.c
- core/drivers/crypto/se050/crypto.mk
The SCP03 keys used in the secure channel have different levels of security that can change at runtime.
Output the one being used to the console.
> crypto: se050: SCP03 updates

- core/crypto/signed_hdr.c
Until now shdr_verify_signature() accepted any hash GP algorithm known to OP-TEE. A few of those (MD5 and SHA-1) are known to be weak. So add an extra check to only allow algorithms strong enough.
> core: shdr: check that hash algorithm is strong enough

- lib/libutils/ext/include/stdlib_ext.h
- lib/libutils/ext/include/string_ext.h
- lib/libutils/ext/include/types_ext.h
- lib/libutils/isoc/bget_malloc.c
- lib/libutils/isoc/include/assert.h
- lib/libutils/isoc/include/inttypes.h
- lib/libutils/isoc/include/limits.h
- lib/libutils/isoc/include/malloc.h
- lib/libutils/isoc/include/memory.h
- lib/libutils/isoc/include/signal.h
- lib/libutils/isoc/include/stdint.h
- lib/libutils/isoc/include/stdio.h
- lib/libutils/isoc/include/stdlib.h
- lib/libutils/isoc/include/string.h
- lib/libutils/isoc/include/time.h
- lib/libutils/isoc/include/unistd.h
- lib/libutils/isoc/include/wchar.h
- mk/compile.mk
> libutils: implement aligned_alloc() and bump to C11 (gnu11)

- MAINTAINERS
- core/drivers/crypto/versal/ecc.c
- core/drivers/crypto/versal/sub.mk
- core/include/crypto/crypto_impl.h
- core/lib/libtomcrypt/ecc.c
- lib/libmbedtls/core/ecc.c
> AMD/Xilinx Versal ACAP: ECC

- MAINTAINERS
- core/drivers/crypto/versal/rsa.c
- core/drivers/crypto/versal/sub.mk
This driver fallbacks to a default software implementation (LTC) if the requested operation is not supported by the hardware.
> AMD/Xilinx Versal ACAP: RSA

- core/crypto/crypto.c
- core/crypto/sm4-xts.c
- core/crypto/sm4.c
- core/crypto/sm4.h
- core/crypto/sub.mk
- core/include/crypto/crypto_impl.h
- core/tee/tee_cryp_utl.c
- core/tee/tee_svc_cryp.c
- lib/libutee/include/tee_api_defines_extensions.h
- lib/libutee/include/utee_defines.h
- lib/libutee/tee_api_operations.c
In this patch, The sm4-xts algorithm is supported in the GP process.
Signed-off-by: Pingan Xie <xiepingan3@huawei.com>
Reviewed-by: Xiaoxu Zeng <zengxiaoxu@huawei.com>
> optee-os: The sm4-xts algorithm is supported in the GP process.

- core/arch/arm/plat-stm/main.c
- core/arch/arm/plat-vexpress/main.c
- core/drivers/imx_lpuart.c
- core/include/drivers/serial.h
- core/kernel/console.c
> struct serial_ops: make functions optional

- core/arch/arm/plat-d06/conf.mk
- core/arch/arm/plat-d06/main.c
- core/arch/arm/plat-d06/platform_config.h
- core/drivers/lpc_uart.c
- core/drivers/sub.mk
- core/include/drivers/lpc_uart.h
Support for lpc_uart.
Signed-off-by: Xiaoxu Zeng <zengxiaoxu@huawei.com>
> drivers: implement lpc_uart driver

- core/arch/arm/plat-versal/conf.mk
- core/drivers/versal_pm.c
> FIX build failure: versal_pm

- .github/workflows/ci.yml
- core/drivers/crypto/se050/adaptors/include/se050.h
- core/drivers/crypto/se050/adaptors/utils/scp_config.c
- core/drivers/crypto/se050/core/ecc.c
- core/drivers/crypto/se050/core/rsa.c
- core/drivers/crypto/se050/crypto.mk
> SE050-F fixes. Enable SE050 fallback on software operations to comply with xtests.

- lib/libutils/isoc/bget_malloc.c
Fixes problems with MDBG when combined with memory tagging. MDBG uses an extra header which wasn't taken into account when tagging the allocated memory. This leads to tag check fault. So fix it by adding the size of the extra header when tagging the allocated memory.
Fixes: 08a5c4f9ae42 ("libutils: add MTE support in malloc() and friends")
> libutils: malloc: fix MDBG combined with MEMTAG

- core/arch/arm/plat-stm32mp1/platform_config.h
- core/arch/arm/plat-stm32mp1/scmi_server.c
> plat-stm32mp1: fixes for 3.20.0 related to SCMI

- core/drivers/crypto/se050/adaptors/apis/sss.c
Certain devices (depending on the applet) will use the common policies to for the object's read/write permissions.
Make sure both are supported.
> crypto: se050: update policies

- core/include/drivers/clk_dt.h
- core/include/kernel/dt_driver.h
> clk: fixes in header files inline description comments 

- .github/workflows/ci.yml
- MAINTAINERS
- core/arch/arm/plat-versal/conf.mk
- core/arch/arm/plat-versal/main.c
- core/arch/arm/plat-versal/platform_config.h
- core/drivers/sub.mk
- core/drivers/versal_huk.c
> Versal Platform Banner, RPMB key control, HUK driver and FPGA programming.

- CHANGELOG.md
- mk/config.mk
Update CHANGELOG for 3.20.0 and collect Tested-by tags.
> Update CHANGELOG for 3.20.0

- core/arch/arm/dts/at91-sama5d27_wlsom1.dtsi
- core/arch/arm/dts/at91-sama5d27_wlsom1_ek.dts
- core/arch/arm/plat-sam/conf.mk
- core/arch/arm/plat-sam/platform_config.h
Short series which adds support for sama5d27_wlsom1_ek board.
> plat-sam: add support for sama5d27_wlsom1_ek

- core/arch/arm/arm.mk
- core/arch/arm/include/hafnium.h
- core/arch/arm/include/kernel/thread_arch.h
- core/arch/arm/kernel/boot.c
- core/arch/arm/kernel/entry_a64.S
- core/arch/arm/kernel/thread_a32.S
- core/arch/arm/kernel/thread_a64.S
- core/arch/arm/kernel/thread_spmc.c
- core/arch/arm/mm/mobj_ffa.c
- core/arch/arm/plat-vexpress/conf.mk
- core/arch/arm/plat-vexpress/main.c
- core/drivers/hfic.c
- core/drivers/sub.mk
- core/include/drivers/hfic.h
> FF-A patches for QEMU with SPMC at EL3, S-EL2 and S-EL1

- .github/workflows/ci.yml
- core/drivers/crypto/se050/crypto.mk
> Plug and trust update

- core/kernel/ree_fs_ta.c
> Enc ta fix

- CHANGELOG.md
- mk/config.mk
Update CHANGELOG for 3.21.0 and collect Tested-by tags.
> Update CHANGELOG for 3.21.0

- .github/workflows/ci.yml
- core/include/kernel/tee_ta_manager.h
- core/kernel/tee_ta_manager.c
> pta: stats: fix compilation incompatible pointer warning 

- MAINTAINERS
Updates etienne-lms e-mail address.
> MAINTAINERS: update etienne's e-mail address

- ta/pkcs11/src/handle.c
- ta/pkcs11/src/handle.h
- ta/pkcs11/src/object.c
- ta/pkcs11/src/pkcs11_token.c
- ta/pkcs11/src/pkcs11_token.h
> ta: pkcs11: invalidate handles on destroyed token object

- .github/workflows/ci.yml
- core/arch/arm/plat-nuvoton/conf.mk
- core/arch/arm/plat-nuvoton/main.c
- core/arch/arm/plat-nuvoton/platform_config.h
- core/arch/arm/plat-nuvoton/sub.mk
Initial version
Co-developed-by: Hila Miranda-Kuzi <hila.miranda.kuzi1@gmail.com>
Signed-off-by: Margarita Glushkin <rutigl@gmail.com>
> feat(plat): added support to Nuvoton npcm845x chip

- core/drivers/imx_ele.c
Hello,
Two patches to fix ELE RNG and HUK API calls. This is related to a recent firmware change.
Thanks!
> Fix RNG and HUK ELE API

- core/arch/arm/plat-stm32mp1/conf.mk
- core/drivers/stm32_gpio.c
- core/include/drivers/stm32_gpio.h
> stm32_gpio: bump to GPIO framework

- core/drivers/gic.c
> Gic bugfix

- core/arch/arm/include/arm64.h
- core/arch/arm/include/kernel/tlb_helpers.h
- core/arch/arm/kernel/cache_helpers_a64.S
- core/arch/arm/kernel/tlb_helpers_a32.S
- core/arch/arm/kernel/tlb_helpers_a64.S
- core/arch/arm/mm/core_mmu.c
- core/arch/arm/mm/tee_pager.c
- core/arch/riscv/mm/tlb_helpers_rv.S
- core/include/mm/core_mmu.h
- core/mm/vm.c
This PR simply applies the discussion in https://github.com/OP-TEE/optee_os/issues/6099
> [RFC] Rename "mva" to "va"

- core/drivers/stm32_bsec.c
- core/mm/core_mmu.c
- ta/pkcs11/src/processing.h
> Gcc13 fixes

- core/arch/riscv/include/kernel/tlb_helpers.h
- core/arch/riscv/mm/tlb_helpers_rv.S
Add TLB invalidate function which is corresponding to virtual address and ASID.
Also the two wrappers are added for memory management implementation.
CC @maroueneboubakri for review.
> core: riscv: Complete virtual address related TLB operations

- core/arch/arm/plat-stm32mp1/scmi_server.c
Implements stubs for SCMI regulators that are to be exposed by STM32MP13 SCMI server but are not implemented yet in OP-TEE core. The drivers for these regulators (IOD SDMMC1/2 and VREFBUF) will be implemented once there is a regulator framwork in OP-TEE. In the meantime, stubbing those allows to use the platform.
> plat-stm32mp1: stub stm32mp13 regulators

- core/kernel/ldelf_loader.c
- core/kernel/user_ta.c
When `CFG_PAN` is enabled, the kernel can not directly touch the user memory.
These two commits fix the invalid accesses on user stack by applying user-access functions to duplicate the user data into the bounce buffers.
> Fix PAN in ldelf and user_ta

- .github/workflows/ci.yml
Adds a check with Hafnium, that is, testing with Hafnium as SPMC at S-EL2 and OP-TEE as an SP at S-EL1. Building with SPMC_AT_EL=2.
> ci: qemuv8: add check Hafnium

- core/kernel/user_access.c
Just as the heap uses memory tags (CFG_MEMTAG=y) use memory tags for the temporary bounce buffers. This should catch problems with out of bounds accesses, using already freed, reset bounce buffers.
> core: assign memory tags to bounce buffers

- core/arch/riscv/include/kernel/thread_private_arch.h
- core/arch/riscv/include/kernel/user_access_arch.h
- core/arch/riscv/kernel/arch_scall.c
- core/arch/riscv/kernel/thread_arch.c
- core/arch/riscv/kernel/thread_rv.S
- mk/config.mk
The series add support `CFG_PAN` for RISC-V architecture.
Some fixing on thread RPC and bit-width of CSR status are also submitted.
> RISC-V: Support CFG_PAN and some fixing

- ta/pkcs11/src/pkcs11_attributes.c
When RSA public key is created with C_CreateObject() CKA_MODULUS_BITS is not allowed to be specified.
The tooling like pkcs11-tool expects that the value is there.
In specification it is not specified clearly that it needs to be calculated but it is assumed to be in the RSA public key object.
Calculate the value and add it to the object during RSA public key import.
---
TODO:
- Add tests
Without the fix:
```
root@qemuarm64-secureboot:~# export PKCS11_MODULE=/usr/lib/libckteec.so.0
root@qemuarm64-secureboot:~# export PKCS11_SLOT=0
root@qemuarm64-secureboot:~# export PKCS11_TOKEN=device
root@qemuarm64-secureboot:~# export PKCS11_SO_PIN=1234567890
root@qemuarm64-secureboot:~# export PKCS11_USER_PIN=1234
root@qemuarm64-secureboot:~# export PKCS11_OBJECT_ID=112233
root@qemuarm64-secureboot:~# …
```
> ta: pkcs11: on RSA public key import calculate CKA_MODULUS_BITS

- core/arch/arm/kernel/secure_partition.c
- core/include/kernel/embedded_ts.h
- core/include/kernel/ts_store.h
- core/include/kernel/user_access.h
- core/include/tee/tadb.h
- core/kernel/embedded_ts.c
- core/kernel/ldelf_loader.c
- core/kernel/ldelf_syscalls.c
- core/kernel/ree_fs_ta.c
- core/kernel/scall.c
- core/kernel/secstor_ta.c
- core/kernel/user_ta.c
- core/tee/tadb.c
- core/tee/tee_svc_cryp.c
> Pan updates

- core/include/kernel/user_access.h
- core/kernel/user_access.c
- core/pta/system.c
- core/tee/tee_svc.c
- core/tee/tee_svc_storage.c
> Pan update2

- core/arch/arm/arm.mk
- core/arch/arm/kernel/boot.c
- core/arch/arm/kernel/entry_a64.S
- core/arch/arm/kernel/link_dummies_paged.c
- core/arch/arm/kernel/secure_partition.c
- core/include/kernel/boot.h
- core/include/mm/core_mmu.h
- core/mm/core_mmu.c
- lib/libutils/isoc/include/assert.h
- mk/config.mk
> Manifest dt

- core/mm/core_mmu.c
In SPMC SEL2, we can save device info in the SP manifest, and obtain device memory info from the SP manifest dtb. 
https://github.com/OP-TEE/optee_os/issues/6238
@jenswi-linaro
> core: Obtain device memory info from dtb

- core/pta/stats.c
Add new command (STATS_CMD_SECTIME_STATS) in the stats PTA. The command returns the tee and ree time for debug purposes. https://github.com/OP-TEE/optee_os/issues/6304
Tested-by: Weizhao Jiang <weizhaoj@amazon.com>
> core: implement a method to get secure time

- MAINTAINERS
Edit MAINTAINERS to add myself as maintainer for RISC-V support.
> MAINTAINERS: add RISC-V maintainer entry

- .github/workflows/ci.yml
Add platform sam-sama5d27_som1_ek and sam-sama5d2_xplained to CI build.
> Add sama5 ci build

- core/arch/arm/include/kernel/thread_arch.h
- core/arch/arm/kernel/asm-defines.c
- core/arch/arm/kernel/thread_spmc.c
- core/arch/arm/kernel/thread_spmc_a64.S
> FFA_MSG_SEND_DIRECT_REQ_64

- core/drivers/regulator/regulator.c
- core/include/drivers/regulator.h
Adds regulator API function regulator_supported_voltages() to get the list of the voltage levels supported by the regulator.
Voltage level array is either an array of increasing ordered levels, in microvolt, or is a triplet [min, max, step] for linear step incremental levels.
This P-R is extracted from RFC https://github.com/OP-TEE/optee_os/pull/6301.
> drivers: regulator: list supported levels

- .github/workflows/ci.yml
Apply the same technique as commit 788069fa88ed ("ci: rust: fix "no space left in device" error") to avoid a similar issue with the Hafnium job.
> ci: hafnium: fix "no space left on device" error

- core/arch/arm/include/optee_ffa.h
- core/arch/arm/kernel/thread_spmc.c
> Small ffa fixes

- core/arch/arm/kernel/spmc_sp_handler.c
Currently it is assumed that a NS endpoint's ID is always 0. This is not true if multiple VMs are present in the NWd, so the check will fail when reclaiming shared memory from an SP. Fix this by removing the owner ID check if the reclaim call comes from NWd, in this case the necessary checks are done by the hypervisor.
> core: sp: fix FFA_MEM_RECLAIM checks

- core/arch/riscv/kernel/thread_arch.c
In ARM, the bits in DAIF register are used to mask the interrupts. While in RISC-V, the bits in CSR XIE are used to enable(unmask) corresponding interrupt sources.
To not modify the function of thread_get_exceptions(), we invert the bits after reading the value of CSR XIE, as mask.
To not modify the function of thread_set_exceptions(), we invert the bits in given "exceptions" before writing "exceptions" into CSR XIE. Therefore, the intended masked exception bits will be cleared when we write the final value into CSR XIE to mask those interrupts.
> core: riscv: Fix logic of thread_{get/set}_exceptions()

- core/arch/arm/kernel/boot.c
- core/arch/arm/kernel/entry_a32.S
- core/arch/arm/kernel/entry_a64.S
- core/arch/arm/kernel/link_dummies_init.c
- core/arch/arm/kernel/link_dummies_paged.c
- core/arch/riscv/kernel/boot.c
- core/include/kernel/boot.h
> [RFC] Save boot params in C function

- core/arch/arm/plat-nuvoton/main.c
Reading HUK from UUID stored in two scratchpad registers
> plat-nuvoton: update HUK reading

- .github/workflows/ci.yml
- core/arch/arm/plat-imx/conf.mk
Add the support for the i.MX8DX platform.
> core: imx: add support fox i.MX8DX

- core/drivers/crypto/caam/crypto.mk
Use the job ring #3 on i.mx8dxl to avoid resource conflict with other software stacks.
> drivers: crypto: caam: use job ring 3 on i.mx8dxlevk

- core/include/mm/core_mmu.h
- core/mm/core_mmu.c
> core: static mapping of non-secure DDR and of secure memory with read-only rights

- core/kernel/dt_driver.c
Prevent `dt_driver_device_from_node_idx_prop()` to request driver probe deferral when needing to skip phandle arguments cells related to providers not yet registered. When skipping these phandle argument cells we don't really need the skipped provider is registered, we can read the `#xxx-cells` property in the provider DT node straight.
For example, consider a driver which DT node defines:
```
clocks = <&foo_clock 1 2 3>, <&bar_clock 2>;
clock-names = "foo", "bar";
```
If driver calls `clk_get_by_name(fdt, node, "bar")`, it does not need to wait `&foo_clock` related driver to be already probed, it does not even need the driver to be ever probed.
Reported-by: Gatien Chevallier <gatien.chevallier@foss.st.com>
Link: https://github.com/OP-TEE/optee_os/pull/6491#discussion_r1404181813
Fixes: …
> core: dt_driver: do not defer probe on skip phandler arguments

- core/arch/arm/plat-sam/matrix.c
- core/arch/arm/plat-sam/matrix.h
> plat-sam: matrix: fix warnings found during checkpatch

- core/tee/tee_rpmb_fs.c
The write_counter field of the rpmb_fat_entry struct is set from the RPMB device but never used. Rename it to 'unused' and cleanup the associated code.
Tested on QEMUv8 with:
$ make CFG_RPMB_FS=y CFG_RPMB_WRITE_KEY=y CFG_RPMB_TESKEY=y check
> core: rpmb: cleanup useless write_counter in struct rpmb_fat_entry

- core/arch/riscv/include/riscv.h
- core/arch/riscv/kernel/thread_arch.c
- core/drivers/plic.c
Small fixing from previous PR review and rebase from latest master branch.
> RISC-V: Small fixing

- core/arch/arm/plat-k3/drivers/sa2ul_rng.c
Check if rng is enabled in hw_get_random_bytes(), if not the initialization sequence is run.
After a suspend to ram, the rng is in reset state, and it has to be re-initialized.
> plat-k3: sa2ul_rng: check if rng is enabled before to do a read

- core/drivers/stm32_rng.c
This P-R adds somes fixes to the stm32_rng.c driver
> stm32_rng fixes

- core/drivers/crypto/caam/acipher/caam_dsa.c
- core/drivers/crypto/caam/acipher/caam_ecc.c
- core/drivers/crypto/caam/crypto.mk
- core/drivers/crypto/caam/include/caam_desc_defines.h
- core/drivers/crypto/caam/include/caam_desc_helper.h
Fix for TLS1.3 handshake failure.
> Fix for TLS1.3 handshake failure 

- core/arch/arm/plat-k3/drivers/sa2ul_rng.c
While spinlock are slightly more lightweight, they currently require that interrupts are disabled during the critical section. If this section is long enough it can have a negative affect on realtime sensitive tasks that require deterministic preemption.
As our RNG gathering can loop while waiting for new random numbers to become available we cannot know how long this section will take, so we should use a mutex. Do that here.
> plat-k3: sa2ul_rng: Use mutex instead of spinlock for critical section

- core/drivers/scmi-msg/smt.c
- core/drivers/stm32_i2c.c
- core/include/drivers/i2c.h
- core/pta/scmi.c
Minor fixes around I2C and SCMI.
> core: misc fixes

- core/arch/arm/kernel/secure_partition.c
Read the SP's FF-A version from the ffa-version property of the SP manifest. This property is mandatory according to the FF-A specification.
SPs are still able to do runtime version negotiation via the FFA_VERSION interface.
This PR is not a critical fix, so it is intended to be merged after the 4.1.0 release.
> core: ffa: Read FF-A version from the SP manifest

- core/drivers/atmel_piobu.c
- core/drivers/atmel_rstc.c
- core/drivers/atmel_rtc.c
- core/drivers/atmel_trng.c
> drivers: atmel: update piobu, trng, rstc and rtc drivers for Microchip sama7g54

- core/arch/arm/plat-sam/sam_sfr.c
- core/drivers/atmel_rstc.c
- core/drivers/atmel_rtc.c
- core/drivers/atmel_shdwc.c
- core/drivers/atmel_tcb.c
- core/drivers/atmel_wdt.c
- core/drivers/nvmem/atmel_sfc.c
> drivers: sam: use header file "platform_config.h" instead of "sama5d2.h" 

- core/drivers/crypto/hisilicon/hisi_qm.c
1. add qm_disable_clock_gate for HISI_QM_HW_V3
2. set doorbell timeout to QM_DB_TIMEOUT_SET ns
> driver: crypto: hisilicon: update qm init configs

- core/drivers/atmel_rstc.c
- core/drivers/atmel_shdwc.c
- core/drivers/atmel_tcb.c
- core/drivers/pinctrl/atmel_pio.c
- core/include/drivers/atmel_rstc.h
> drivers: atmel: update rstc timer pio and watchdog drivers for Microchip sama7g54

- core/drivers/regulator/regulator_gpio.c
Implement .supported_voltages() operation in regulator_gpio.c driver to report voltage levels a level array that is required by scp-firmware voltage domain module when a regulator-gpio is exposed through an SCMI voltage domain. This change requires filed voltage_levels_uv[] array of struct regulator_gpio to be sorted in increasing level value.
> drivers: regulator: list voltages controlled by a GPIO

- core/arch/arm/crypto/ghash-ce-core_a64.S
- core/crypto/aes-gcm.c
- core/lib/libtomcrypt/gcm.c
> AES-GCM counter fix

- core/arch/arm/plat-vexpress/main.c
- core/drivers/pl011.c
- core/include/drivers/serial.h
> Serial ops

- core/arch/arm/kernel/virtualization.c
Prior to this patch was virt_add_cookie_to_current_guest() only masking interrupts while adding a shared memory cookie to the list of cookies. Proper locking is needed to serialize access to the cookie list, replace the interrupt masking with a cpu_spin_lock_xsave().
Fixes: a65dd3a6b64d ("core: spmc: support virtualization with SPMC at S-EL1")
> virt: arm: fix lock in virt_add_cookie_to_current_guest()

- core/include/kernel/huk_subkey.h
- fixed a typo in `huk_subkey.h` comment where `TEE_SUCCES` should be `TEE_SUCCESS`
> docs(huk_subkey.h): fixed a typo

- core/include/initcall.h
- core/include/mm/core_memprot.h
- core/kernel/notif.c
- core/kernel/panic.c
- core/kernel/tee_time.c
- core/mm/core_mmu.c
> Misc nexus

- lib/libutils/ext/include/speculation_barrier.h
Implement load_no_speculate() with implementation consists of RISC-V fence instructions which are used to preserve the memory order.
- Data barrier: fence rw, rw
- Instruction barrier: fence.i; fence r, r
> libutils: Implement speculation barrier for RISC-V

- MAINTAINERS
Add myself as maintainer for NXP i.MX Platforms and Crypto Driver Interface.
Remove Clement Faure as maintainer.
> MAINTAINERS: update NXP i.MX platforms and Crypto Driver Interface

- core/drivers/clk/clk-stm32mp13.c
> Another series of fixes for STM32MP13 clock driver

- .github/workflows/ci.yml
- ldelf/ta_elf_rel.c
- lib/libunw/sub.mk
- mk/config.mk
- mk/lib.mk
Implementing https://github.com/OP-TEE/optee_os/issues/6704.
> Add RISC-V build to CI

- core/arch/riscv/include/sbi.h
- core/arch/riscv/kernel/boot.c
- core/arch/riscv/kernel/sbi.c
- core/arch/riscv/kernel/sbi_console.c
- The first 5 patches are cleanps to SBI calls
- The last one introduces debug console SBI call, which is intended to replace the legacy SBI 1.0 `sbi_console_putchar()`.
> SBI related cleanups and introduce Debug Console

- .github/workflows/ci.yml
Add a "make check" test with pager enabled on QEMUv8.
> ci: qemuv8: add test case with CFG_WITH_PAGER=y

- .github/workflows/ci.yml
> CI: use new image for QEMUv8 jobs plus rename the WD variable

- .github/workflows/ci.yml
- core/drivers/crypto/hisilicon/hpre_main.c
- core/drivers/crypto/hisilicon/include/hpre_main.h
- core/drivers/crypto/hisilicon/sub.mk
The HiSilicon HPRE is a High Performance RSA Engine. 
This module implement the hardware initialization of the HPRE.
> drivers: crypto: hisilicon: implement the hardware initialization of the HiSilicon HPRE

- core/drivers/crypto/stm32/stm32_cryp.c
This pull request adds the support of power management for CRYP peripheral.
We also remove the requirement on the reset binding.
> Add support of power management for stm32 CRYP peripheral

- core/drivers/firewall/stm32_rifsc.c
- core/include/drivers/stm32_rif.h
- core/include/dt-bindings/firewall/stm32mp25-rif.h
- core/include/dt-bindings/firewall/stm32mp25-rifsc.h
This P-R fixes a prototype and moves the RIFPROT macro definition
> drivers: firewall: small RIF fixes

- core/drivers/pm/sam/pm_suspend.S
> drivers: sam: update PLLA, MCK and LPM for sama7g5 low-power support

- .github/workflows/ci.yml
Test Xen FF-A mediator with SPMC_AT_EL=1. This test replaces the previous test of the Xen OP-TEE mediator.
> ci: xen: test FF-A mediator with SPMC_AT_EL=1

- core/drivers/pm/sam/at91_pm.c
- core/drivers/pm/sam/at91_pm.h
- core/drivers/pm/sam/pm-defines.c
- core/drivers/pm/sam/pm_suspend.S
- core/include/drivers/sam/sama7-ddr.h
> drivers: sam: add DDR self-refresh for sama7g5 low-power support

- core/tee/tee_ree_fs.c
The counter ree_fs_dirh_refcount is used to determine when ree_fs_dirh should be free, not as a guarantee that ree_fs_dirh is still valid. This wasn't the assumption in ree_fs_readdir_rpc(), ree_fs_closedir_rpc(), and ree_fs_opendir_rpc(). So fix that by using get_dirh() in ree_fs_readdir_rpc as needed.
Fixes: ace6039fd434 ("core: REE_FS: refcount dirfile handle")
> core: REE_FS: fix dirfile handle refcount

- core/drivers/crypto/hisilicon/crypto.mk
- core/drivers/crypto/hisilicon/hpre_ecc.c
- core/drivers/crypto/hisilicon/hpre_ecc.h
- core/drivers/crypto/hisilicon/sub.mk
add ECC gen_keypair and shared secret
> driver: crypto: hisilicon: add ECC gen_keypair and ECDH

- core/arch/arm/arm.mk
- core/arch/arm/include/kernel/thread_private_arch.h
- core/arch/arm/include/mm/core_mmu_arch.h
- core/arch/arm/mm/core_mmu_v7.c
- core/include/mm/mobj.h
- core/mm/mobj.c
> Misc cleanup

- core/drivers/i2c/atmel_i2c.c
- core/drivers/stm32_i2c.c
- core/include/kernel/dt_driver.h
- core/kernel/dt_driver.c
> core: dt_driver: dt_driver: fix nodes reference passed in dt_pargs

- .github/workflows/ci.yml
- core/arch/arm/plat-imx/conf.mk
- core/arch/arm/plat-imx/imx-common.c
- core/arch/arm/plat-imx/imx-regs.h
- core/arch/arm/plat-imx/imx.h
- core/arch/arm/plat-imx/registers/imx95.h
This pull request adds support for i.MX95evk platform
> Add imx95 support

- .github/workflows/ci.yml
- core/arch/arm/plat-imx/conf.mk
- core/arch/arm/plat-imx/imx-common.c
- core/arch/arm/plat-imx/imx-regs.h
- core/arch/arm/plat-imx/imx.h
- core/drivers/imx/mu/sub.mk
- core/drivers/imx_ele.c
- core/include/drivers/imx_mu.h
This pull request adds support for i.MX91 EVK platform
> Add i.MX91 support

- core/drivers/crypto/hisilicon/hpre_ecc.c
- core/drivers/crypto/hisilicon/hpre_ecc.h
> driver: crypto: hisilicon: add ECC sign and verify

- core/arch/arm/kernel/virtualization.c
- core/arch/arm/mm/core_mmu_lpae.c
- core/arch/arm/mm/core_mmu_v7.c
- core/arch/riscv/mm/core_mmu_arch.c
- core/include/kernel/virtualization.h
- core/include/mm/core_mmu.h
- core/include/mm/tee_mmu_types.h
- core/mm/core_mmu.c
- lib/libutils/ext/array.c
- lib/libutils/ext/include/string_ext.h
- lib/libutils/ext/sub.mk
> Mem map cleanup

- core/arch/arm/kernel/boot.c
- core/include/mm/core_mmu.h
- core/mm/core_mmu.c
> Core mmu for each map

- core/arch/arm/kernel/link.mk
- core/arch/riscv/kernel/link.mk
- mk/compile.mk
- mk/macros.mk
The DT-related fixes should hopefully address all the points mentioned in #6551 except the dtc warnings on the STM32MP1 DT.
> Misc fixes

- core/arch/arm/kernel/boot.c
- core/arch/arm/kernel/entry_a32.S
- core/arch/arm/kernel/entry_a64.S
- core/arch/arm/kernel/link_dummies_paged.c
- core/arch/arm/kernel/virtualization.c
- core/include/initcall.h
- core/include/kernel/boot.h
- core/kernel/initcall.c
- core/tee/tee_cryp_utl.c
This can helps https://github.com/OP-TEE/optee_os/pull/6945 to use the thread specific pauth keys during boot_init_primary_late()
> Pauth thread keys used during boot_init_primary_late()

- .checkpatch.conf
- core/arch/arm/kernel/boot.c
- core/arch/arm/kernel/secure_partition.c
- core/arch/arm/kernel/virtualization.c
- core/arch/riscv/kernel/boot.c
- core/include/mm/core_mmu.h
- core/include/mm/phys_mem.h
- core/kernel/ree_fs_ta.c
- core/mm/core_mmu.c
- core/mm/fobj.c
- core/mm/pgt_cache.c
- core/mm/phys_mem.c
- core/mm/sub.mk
- core/pta/stats.c
> Phys mem allocation functions

- lib/libmbedtls/include/mbedtls_config_uta.h
- lib/libutee/include/tee_api_types.h
- mk/compile.mk
- mk/subdir.mk
- ta/mk/ta_dev_kit.mk
This pull request replaces https://github.com/OP-TEE/optee_os/pull/7054 now that we have decided to keep the fTPM TA in a separate git. The commits needed in optee_os from the previous PR are moved into this PR.
> Support compiling optee_ftpm

- core/drivers/crypto/caam/acipher/caam_ecc.c
- core/drivers/crypto/caam/acipher/caam_rsa.c
> Fix comments in CAAM driver

- core/drivers/crypto/caam/caam_key.c
An array was used as Key blob modifier, changed it cache aligned dynamic memory.
> drivers: caam: cache align Key blob modifier

- scripts/sign_encrypt.py
Fix typo in stitch usage message.
> sign_encrypt.py: fix typo in stitch usage message

- .github/workflows/ci.yml
Add PLATFORM=rockchip-rk3588 build.
> ci: add Rockchip RK3588 build

- CHANGELOG.md
- mk/config.mk
Update CHANGELOG for 4.5.0 and collect Tested-by tags.
> Update CHANGELOG for 4.5.0

- lib/libutils/isoc/bget_malloc.c
- lib/libutils/isoc/include/malloc.h
- lib/libutils/isoc/include/malloc_flags.h
- ta/ta.mk
> Malloc flags and cleanup

- core/arch/arm/kernel/boot.c
Move the expanding of fdt transfer entry from boot_init_primary_early to boot_init_primary_late.
> core: expand the fdt transfer entry right before it is being used

- core/arch/arm/dts/stm32mp251.dtsi
- core/drivers/firewall/stm32_risaf.c
This P-R aims to upgrade RISAF as a firewall controller so that we're able to make some checks on regions' firewall configs and dynamically reconfigure regions
> (STM32) Upgrade RISAF as a firewall controller

- core/mm/core_mmu.c
> RK3399 ns mem

- core/drivers/gic.c
According to the ARM documentation for GICV2/3/4, there is no need to write to the end of interrupt register for some special IDs. Apply this recommendation to avoid writing to io memory in this time sensitive sequence.
> core: do not acknowledge end of interrupt for special GIC interrupt IDs

- .github/workflows/ci.yml
- core/arch/riscv/include/kernel/misc_arch.h
- core/arch/riscv/include/kernel/thread_arch.h
- core/arch/riscv/include/riscv.h
- core/arch/riscv/include/sbi.h
- core/arch/riscv/kernel/asm-defines.c
- core/arch/riscv/kernel/boot.c
- core/arch/riscv/kernel/entry.S
- core/arch/riscv/kernel/sbi.c
- core/arch/riscv/kernel/thread_arch.c
- core/arch/riscv/kernel/thread_rv.S
- core/arch/riscv/plat-sifive/conf.mk
- core/arch/riscv/plat-sifive/main.c
- core/arch/riscv/plat-sifive/platform_config.h
- core/arch/riscv/plat-sifive/sub.mk
- core/arch/riscv/plat-virt/platform_config.h
- core/drivers/sifive_uart.c
- core/drivers/sub.mk
- core/include/drivers/sifive_uart.h
- core/include/kernel/boot.h
This PR adds basic support for SiFive platforms and includes several RISC-V related improvements.
> [RISC-V] Support SiFive platform

- core/drivers/crypto/stm32/stm32_cryp.c
- core/drivers/crypto/stm32/stm32_saes.c
> stm32: fix CTR mode implementation in CRYP and SAES drivers

- core/arch/arm/kernel/link.mk
- lib/libmbedtls/include/mbedtls_config_kernel.h
- lib/libmbedtls/include/mbedtls_config_uta.h
- lib/libutils/compiler-rt/LICENSE.TXT
- lib/libutils/compiler-rt/README.txt
- lib/libutils/compiler-rt/lib/builtins/ashlti3.c
- lib/libutils/compiler-rt/lib/builtins/int_div_impl.inc
- lib/libutils/compiler-rt/lib/builtins/int_endianness.h
- lib/libutils/compiler-rt/lib/builtins/int_lib.h
- lib/libutils/compiler-rt/lib/builtins/int_types.h
- lib/libutils/compiler-rt/lib/builtins/int_util.h
- lib/libutils/compiler-rt/lib/builtins/sub.mk
- lib/libutils/compiler-rt/lib/builtins/udivmodti4.c
- lib/libutils/compiler-rt/lib/builtins/udivti3.c
- lib/libutils/compiler-rt/lib/sub.mk
- lib/libutils/compiler-rt/sub.mk
- lib/libutils/sub.mk
- mk/config.mk
This is trying to address https://github.com/OP-TEE/optee_os/issues/7374
> Crt builtins for long long division

- core/arch/arm/arm.mk
- core/arch/arm/include/kernel/secure_partition.h
- core/arch/arm/include/kernel/thread_spmc.h
- core/arch/arm/kernel/secure_partition.c
- core/arch/arm/kernel/thread_spmc.c
- core/arch/arm/tests/ffa_lsp.c
- core/arch/arm/tests/sub.mk
> Add framework for Logical SPs

- core/arch/arm/kernel/secure_partition.c
According to the official manifest binding documentation [1], all integer properties must be defined as 32-bit wide DTB properties. However, the OP-TEE SPMC previously implemented the boot-order property as a 16-bit value. This patch corrects that inconsistency by adding support for the correct 32 bit representation while keeping backwards compatibility.
Recent changes in TF-A’s build tooling have broken support for manifest files using the "/bits/" width specifier. This update restores compatibility by eliminating the need to use them.
[1] FF-A Manifest Binding
Link: https://trustedfirmware-a.readthedocs.io/en/v2.12.0/components/ffa-manifest-binding.html
> spmc: fix FF-A manifest boot-order handling

- core/arch/arm/include/mm/core_mmu_arch.h
- core/arch/arm/mm/core_mmu.c
- core/arch/riscv/include/mm/core_mmu_arch.h
- core/arch/riscv/mm/core_mmu_arch.c
- core/include/mm/core_mmu.h
- core/mm/core_mmu.c
This patch series is in preparation of adding ASLR support for RISC-V.
> Refactor ASLR for RISC-V architecture support

- core/arch/riscv/include/kernel/riscv_elf.h
- core/arch/riscv/kernel/asm-defines.c
- core/arch/riscv/kernel/boot.c
- core/arch/riscv/kernel/entry.S
- core/arch/riscv/kernel/kern.ld.S
- core/arch/riscv/mm/core_mmu_arch.c
- core/arch/riscv/plat-sifive/conf.mk
- core/arch/riscv/plat-virt/conf.mk
Support `CFG_CORE_ASLR` and `CFG_CORE_ASLR_SEED` features on RISC-V.
> Support RISC-V OP-TEE Core ASLR

- core/kernel/tee_ta_manager.c
The panicked TAs with TA_FLAG_SINGLE_INSTANCE,
TA_FLAG_INSTANCE_KEEP_ALIVE, and TA_FLAG_INSTANCE_KEEP_CRASHED flags
should be kept in the TA context list to maintain their paincked status
and prevent respawning.
> core: maintain the panicked TAs with instanceKeepCrashed property
