OP-TEE/optee_os

core/arch/arm32/mm/tee_pager.c
core/arch/arm32/plat-stm/conf.mk
core/arch/arm32/plat-stm/platform_config.h
core/arch/arm32/plat-vexpress/conf.mk
core/arch/arm32/plat-vexpress/platform_config.h
core/arch/arm32/sta/core_self_tests.c
core/core.mk
core/lib/libtomcrypt/include/tomcrypt_custom.h
core/lib/libtomcrypt/src/tee_ltc_provider.c
documentation/build_system.md

It is cleaner to include <generated/conf.h> rather defining CPP flags.
A small number of CFG_ variables are still handled differently because
they are used in user mode code (currently, conf.h is generated only for
the TEE core).
This commit also fixes a compile error when
CFG_TEE_CORE_EMBED_INTERNAL_TESTS=0.

core: get value of CFG_ variables from <generated/conf.h>

---

core/arch/arm32/plat-stm/conf.mk
core/arch/arm32/plat-stm/platform_flags.mk
core/arch/arm32/plat-vexpress/conf.mk
core/arch/arm32/plat-vexpress/platform_flags.mk
documentation/build_system.md
ta/mk/ta_dev_kit.mk
ta/ta.mk

Platform-specific flags that do not apply only to the TEE core are removed
from core/arch/$(ARCH)plat-$(PLATFORM)/conf.mk. They are moved to a new file:
mk/arch/$(ARCH)/plat-$(PLATFORM)/platform_flags.mk.
This file is used by ta/mk/ta_dev_kit.mk so that the Trusted Applications
are built with the same flags used when building the user-mode TEE code.

Move platform-specific flags to their own files, use them in TA dev kit

---

core/lib/libtomcrypt/src/tee_ltc_provider.c
core/tee/tee_svc_cryp.c

Global Platform Internal API 1.0 is not accurate when describing
RSA key pair generation. It only indicates
No parameter is required
This is why RSA key pair generation was always using 65537
as the public exponent.
Version 1.1 of the API is much more precise:
No parameter is required.
The TEE_ATTR_RSA_PUBLIC_EXPONENT attribute may be
specified; if omitted, the default value is 65537.
This patch implements this requirement.
Change-Id: I9e4beb43d38d67b3d0cb9cbec505d8905239d8b0
Reviewed-on: https://gerrit.st.com/19866
Reviewed-by: Laurent GERARD <laurent.gerard@st.com>
Reviewed-by: Jean-Michel DELORME <jean-michel.delorme@st.com>

Fix #6686: Support passing Public Exponent when generating RSA key pair

---

core/include/tee/tee_cryp_hkdf.h
core/lib/libtomcrypt/src/tee_ltc_provider.c
core/tee/sub.mk
core/tee/tee_cryp_hkdf.c
core/tee/tee_svc_cryp.c
documentation/extensions/crypto_hkdf.md
lib/libutee/include/utee_defines.h
lib/libutee/tee_api_operations.c

HKDF (http://tools.ietf.org/html/rfc5869) is a key derivation algorithm.
As per the RFC:
A key derivation function (KDF) is a basic and essential component of
cryptographic systems.  Its goal is to take some source of initial
keying material and derive from it one or more cryptographically
strong secret keys.
[...]
HKDF follows the "extract-then-expand" paradigm, where the KDF
logically consists of two modules.
[...]
The goal of the "extract" stage is to "concentrate" the possibly
dispersed entropy of the input keying material into a short, but
cryptographically strong, pseudorandom key.
[...]
The second stage "expands" the pseudorandom key to the desired
length; the number and lengths of the output keys depend on the
specific cryptographic algorithms for which the keys are needed.
Since …

Add HMAC-based extract-and-expand key derivation function (HKDF)

---

core/include/tee/tee_cryp_pbkdf2.h
core/tee/sub.mk
core/tee/tee_cryp_pbkdf2.c
core/tee/tee_svc_cryp.c
documentation/extensions/crypto_pbkdf2.md
lib/libutee/include/tee_api_defines_extensions.h
lib/libutee/include/utee_defines.h
lib/libutee/tee_api_operations.c

This commit implements a crypto extension to support the key derivation
function defined in section 5.2 of RFC 2898
(https://www.ietf.org/rfc/rfc2898.txt), which is a re-publish of PKCS #5 v2.0.
The underlying pseudorandom function is HMAC-SHA1, which is the default PRF
specified in the RFC. It would be trivial to support the other HMAC functions
already implemented in OP-TEE.
See documentation/extensions/crypto_pbkdf2.md for details.
Tested on PLATFORM=vexpress-qemu_virt with the test vectors from RFC 6070
(https://www.ietf.org/rfc/rfc6070.txt).
Signed-off-by: Xiaoqiang Du <xiaoqiang.du@linaro.org>

Add PKCS #5 v2.0 key derivation function 2 (PBKDF2)

---

core/arch/arm32/plat-sunxi/link.mk
core/arch/arm32/plat-vexpress/link.mk

Fixes https://github.com/OP-TEE/optee_os/issues/181.
plat-sunxi/link.mk uses CPP to generate its core linker script.
Commit a3911433960a ("core: get value of CFG_ variables directly from
generated/conf.h") has modified the core CPP flags to include conf.h
automatically, so one must make sure that this file exists when the linker
script is generated. This is done by adding a dependency on $(conf-file).
The vexpress platforms also lack the dependency, but the bug won't show
because of other dependencies which cause conf.h to be generated anyways.
PLATFORM=stm is fine because it does not use CPP.

sunxi: fix parallel build errors

---

mk/compile.mk

Fixes issue https://github.com/OP-TEE/optee_os/issues/179 (GNU make 4.0
rebuilds everything each time it is run).
GNU make 4.0 includes a fix for bug http://savannah.gnu.org/bugs/?16051
which breaks the C compilation rule in mk/compile.mk. Previous versions
of make would not add the FORCE target to $?, whereas version 4.0 does.
Therefore, one must explicitly exclude FORCE from $? to properly detect
if dependencies have changed.

mk/compile.mk: GNU make 4.0 compatibility

---

core/arch/arm32/include/arm32.h
core/arch/arm32/mm/core_mmu.c

- Add write_ats1cpw() and read_par() for page description debug
- Clear TEX bit beofre enable MMU
Tested-by: SY Chiu <sy.chiu@linaro.org> (QEMU)

Disable TEX Remap before enable MMU

---

core/arch/arm32/kernel/trace_ext.c
lib/libutee/trace_ext.c
lib/libutils/ext/include/trace.h
lib/libutils/ext/trace.c
ta/arch/arm32/user_ta_header.c

Definition of the global "trace_level" variable has been
moved from the libutil to a TA file (user_ta_header.c).
This allows to initialize it with the correct value/level
CFG_TEE_TA_LOG_LEVEL when the TA code is compiled.
Same trace level is now applied at all TA code and associated
libraries: libutee/libutils/libmpa.
Change-Id: Id6bda7f0611f78fe7ad3ee6b61193f4b80aba94d
Signed-off-by: Jean-Michel Delorme <jean-michel.delorme@st.com>
Reviewed-on: https://gerrit.st.com/22472
Reviewed-by: Emmanuel MICHEL <emmanuel.michel@st.com>

Fix user TA trace issue

---

scripts/setup_fvp_optee.sh
scripts/setup_qemu_optee.sh

Use stable commit for optee_test that supports the GlobalPlatform test
package: TEE_Initial_Configuration-Test_Suite_v1_1_0_4-2014_11_07.7z

Update setup_fvp_optee.sh/setup_qemu_optee.sh for GP test suite 1.1.0.4

---

core/lib/libtomcrypt/src/misc/mem_neq.c
core/lib/libtomcrypt/src/misc/sub.mk
core/lib/libtomcrypt/src/pk/pkcs1/pkcs_1_oaep_decode.c
core/lib/libtomcrypt/src/pk/pkcs1/pkcs_1_pss_decode.c
core/lib/libtomcrypt/src/pk/pkcs1/pkcs_1_v1_5_decode.c

This is a cherry-pick of the libtomcrypt pull-request
https://github.com/libtom/libtomcrypt/pull/57
As pointed by Herve Sibert, verification has been kept non-constant time
in this patch.
Excerpt from original libtomcrypt pull-request:
as proposed in RFC 3447 only one error return code is used when there are
errors while decoding the pkcs#1 format.
also, all steps are executed and only the "output" is skipped if something
went wrong.
Sorry this could break backwards compatibility, since there's no more
BUFFER_OVERFLOW messaging.
Former error-handling code could also be affected because now there's only
OK as return code in cases where "res" is also set to '1'.

RSA decode in constant time

---

core/tee/tee_svc_cryp.c

Fixes https://github.com/OP-TEE/optee_os/issues/161.
Services that take a TEE_Attribute array for input must check that the
memory is readable before using it. This is accomplished by
check_attr_read_access(), which is either called directly by the system
service or by tee_svc_cryp_check_attr(). Buffers pointed to by 'reference'
attributes are also validated.
Then, it is no longer necessary to check accessibility in other
functions such as tee_svc_cryp_obj_store_attr_raw().

crypto API: make sure TEE_Attribute parameters are readable

---

lib/libutee/tee_api_operations.c

In TEE_CipherUpdate, buffers must be processed when
the size of the input buffer is exactly the right minimum size.
As an example, in AES128, 16 bytes output must be given
every 16 bytes input.
Tested-by: Jeremy PLANEIX <jeremy.planeix@st.com>

Fix #6737: AES buffer not processed when size=16

---

core/lib/libtomcrypt/include/tomcrypt_custom.h
core/lib/libtomcrypt/src/misc/sub.mk
core/lib/libtomcrypt/src/pk/pkcs1/pkcs_1_oaep_decode.c
core/lib/libtomcrypt/src/pk/pkcs1/pkcs_1_pss_decode.c

Libtomcrypt: use buf_compare_ct instead of mem_neq

---

core/arch/arm32/mm/tee_pager.c
core/arch/arm32/tee/arch_svc.c
core/tee/tee_svc.c
mk/config.mk

In order to disable TA traces, whatever the compilation options of the
TAs, CFG_TEE_CORE_TA_TRACE can be defined to n

CFG_TEE_CORE_TA_TRACE to disable TA traces

---

Makefile
core/core.mk
mk/checkconf.mk
mk/cleanvars.mk

At build time, conf.in file is generated at output root directory.
At build entry, if CFG_OPTEE_CONFIG is defined, it specifies the
path of the target TEE build configuration to use.

core: load/generate TEE fmw build configuration file

---

core/arch/arm32/kernel/tee_ta_manager.c
core/include/kernel/tee_ta_manager.h
core/kernel/tee_dispatch.c
core/tee/tee_svc.c

On the following operations
invoke command
close
cancel
the one that is at the origin of the operations is checked. It could
be a TA or the core. In case of a TA, this is checked that it is the
same as the one that opened the session.

Check of the identity of the TA invoking a TA operation

---

core/arch/arm32/kernel/tee_ta_manager.c
core/include/tee/abi.h
core/include/tee/tee_svc.h
core/include/tee/tee_svc_cryp.h
core/tee/abi.c
core/tee/sub.mk
core/tee/tee_svc.c
core/tee/tee_svc_cryp.c
lib/libutee/include/tee_api_defines.h

Defines 32-bit ABI for various types passed by reference. Either by an
explicit conversion to/from TEE_Param and TEE_Attribute or by changing
size_t to uint32_t. Affected interfaces are SVC interface and parameters
passed to user TA inside tee_user_ta_enter().

Define 32-bit ABI

---

core/include/tee/tee_cryp_provider.h
core/include/tee/tee_cryp_utl.h
core/kernel/tee_dispatch.c
core/lib/libtomcrypt/src/tee_ltc_provider.c
core/tee/tee_cryp_utl.c

- Added add_entropy interface in crypto_ops.prng, and expose
new interface tee_prng_add_entropy() for platform vendor to
inject entropy.
- On FVP, inject entropy using current timestamp every time
when a core is bring up.
Tested-by: SY Chiu <sy.chiu@linaro.org> (FVP)

Added new interface in PRNG Hal to inject entropy

---

lib/libutee/abort.c
lib/libutee/assert.c
lib/libutee/include/tee_api.h
lib/libutee/tee_api.c

According to the Global Plaform Internal Core API v1.1, the prototype
of the function TEE_Panic must be
void TEE_Panic(TEE_Result panicCode);

Remove __noreturn from TEE_Panic prototype

---

ta/arch/arm32/fix_ta_binary
ta/arch/arm32/link.mk
ta/mk/ta_dev_kit.mk

Making use of the $(sm) variable that was missing in a couple of places
when building Trusted Applications. Also the CROSS_COMPILER flag for
building TA's has been updated since it didn't propagate correctly.
Tested-by: Joakim Bech <joakim.bech@linaro.org> (QEMU)

TA-dev-kit: Adds usage of the $(sm) variable

---

core/arch/arm32/include/mm/core_mmu.h
core/arch/arm32/include/mm/tee_mm_def.h
core/arch/arm32/kernel/tee_ta_manager.c
core/arch/arm32/mm/core_mmu_lpae.c
core/arch/arm32/mm/core_mmu_v7.c
core/arch/arm32/mm/tee_mmu.c

core_mmu_get_user_va_range() selects user va range. No change in user TA
va address when configured with V7 MMU tables.
When configured with LPAE only use TTBR0. The top L0 table is CPU
specific with all entries common except one which is used when mapping
user TAs. User TA va range is dependent on the first unused L0 entry.
This is needed in Aarch64 since we can't use TTBR0 and TTBR1 in the same way as before.

arm32: dynamic user va range

---

core/arch/arm32/include/kernel/thread.h
core/arch/arm32/include/mm/core_mmu.h
core/arch/arm32/kernel/thread.c
core/arch/arm32/kernel/thread_a32.S
core/arch/arm32/kernel/thread_private.h
core/arch/arm32/mm/core_mmu_lpae.c
core/arch/arm32/mm/tee_pager.c
core/arch/arm32/plat-vexpress/conf.mk
core/arch/arm32/plat-vexpress/link.mk
core/arch/arm32/plat-vexpress/platform_flags.mk
core/arch/arm32/tee/arch_svc.c
core/arch/arm32/tee/entry.c

* ARM32 specific C code is broken out and surrounded by #ifdef ARM32
* Some small architectural changes in thread and abort handling to
prepare for Aarch64

arm32: separate ARM32 specific

---

core/core.mk
mk/checkconf.mk

Make generation of conf.mk more consistent with what we do for conf.h,
that is:
- conf.mk shall not be touched if its content does not change,
- write "CHK" when checking the file, then "UPD" only if it needs
updating.

mk/checkconf.mk: update generation of conf.mk

---

.travis.yml
README.md
core/arch/arm/kernel/generic_core_bootcfg.c
core/arch/arm/plat-hikey/conf.mk
core/arch/arm/plat-hikey/kern.ld.S
core/arch/arm/plat-hikey/link.mk
core/arch/arm/plat-hikey/main.c
core/arch/arm/plat-hikey/platform_config.h
core/arch/arm/plat-hikey/platform_flags.mk
core/arch/arm/plat-hikey/sub.mk

This commit adds support for the HiKey board [1] in 32-bit mode.
Tested with and without CFG_WITH_PAGER=y. Note that everything
is loaded in DRAM which is non-secure by default.
[1] https://www.96boards.org/products/hikey/

Add support for the HiKey board (make PLATFORM=hikey)

---

.travis.yml
Makefile
core/arch/arm/kernel/link.mk
core/arch/arm/plat-stm/link.mk
core/arch/arm/plat-sunxi/link.mk
mk/checkconf.mk
mk/compile.mk
mk/lib.mk
ta/mk/ta_dev_kit.mk
ta/ta.mk

build system: support for building with V=-1 to be really quiet
travis: adds builds for Juno and FVP ARM64
travis: build using V=-1
I've changed the arm32 compiler to use the same release as the arm64 compiler. This was needed due to a build error for Juno that came from a bug in the old arm32 toolchain.

Travis arm64

---

core/arch/arm/plat-stm/conf.mk

Fixes the following error messages when $(platform-dir)/System.map does
not exist:
grep: core/arch/arm/plat-stm/System.map: No such file or directory
grep: core/arch/arm/plat-stm/System.map: No such file or directory
The function that looks for a symbol in System.map simply returns 0x0
when the file is not readable.

plat-stm: fix grep error message during build

---

lib/libutee/include/user_ta_header.h
ta/arch/arm/user_ta_header.c

add gpd.ta.version and gpd.ta.description
Note: For testing use optee_test with dev/gp11_ta_prop branch

GP Internal Core API v1.1 : TA configuration properties

---

lib/libutee/tee_api.c

Split PR#262
Note: use optee_test dev/gp11_invoke-command fix branch for testing
Tested-by: Cedric Chaumont <cedric.chaumont@linaro.org> (STM boards)
Tested-by: Cedric Chaumont <cedric.chaumont@linaro.org> (ARM Juno board)

GP Internal Core API v1.1 : TEE_InvokeTACommand fix

---

core/arch/arm/tee/entry.c
core/include/kernel/tee_common_otp.h
core/include/kernel/tee_common_unpg.h
core/include/kernel/tee_dispatch.h

OP-TEE no longer supports loading the TA directly in open session.
* Removes ta field in struct tee_dispatch_open_session_in.
* Removes get_open_session_ta()
* Removes unneeded inclusions of kernel/kta_types.h

core arm: remove unused open session option

---

core/arch/arm/plat-hikey/conf.mk
core/arch/arm/plat-hikey/platform_config.h
core/arch/arm/plat-hikey/platform_flags.mk

make PLATFORM=hikey CFG_ARM64_core=y \
CROSS_COMPILE_core=aarch64-linux-gnu-
Note: xtest 1010 fails (writing to supposedly invalid memory at 0x40000000
does not panic the TA). The same test also fails on FVP.

plat-hikey: enable ARM64

---

.travis.yml
README.md
core/arch/arm/kernel/generic_entry_a32.S
core/arch/arm/kernel/generic_entry_a64.S
core/arch/arm/plat-hikey/main.c
core/arch/arm/plat-mediatek/conf.mk
core/arch/arm/plat-mediatek/kern.ld.S
core/arch/arm/plat-mediatek/link.mk
core/arch/arm/plat-mediatek/main.c
core/arch/arm/plat-mediatek/mt8173_core_pos_a32.S
core/arch/arm/plat-mediatek/mt8173_core_pos_a64.S
core/arch/arm/plat-mediatek/platform_config.h
core/arch/arm/plat-mediatek/platform_flags.mk
core/arch/arm/plat-mediatek/sub.mk
core/arch/arm/plat-stm/main.c
core/arch/arm/plat-sunxi/console.c
core/arch/arm/plat-vexpress/main.c
core/drivers/serial8250_uart.c
core/drivers/sub.mk
core/include/console.h
core/include/drivers/serial8250_uart.h
scripts/setup_mtk_optee.sh

Add support for Mediatek mt8173 platform with 32bit
and 64bit OP-TEE OS. Due to Mediatek ATF firmware
limitation, this commit only tested with 64bit OP-TEE OS.
Tested-by: James Kung <james.kung@linaro.org> (MT8173 platform)
Signed-off-by: James Kung <james.kung@linaro.org>

Mediatek mt8173 platform support

---

core/arch/arm/kernel/generic_boot.c
core/arch/arm/plat-stm/main.c
core/arch/arm/plat-stm/tz_sinit.S

Yet another step towrds generic boot on plat-stm
plat-stm/main.c is now minimized by including
kernel/generic_boot.c

plat-stm: main.c now use generic_boot.c

---

core/arch/arm/kernel/tee_ta_manager.c
core/include/kernel/tee_rpc_types.h
core/include/kernel/tee_ta_manager_unpg.h

Tested on HiKey with 32-bit and 64-bit TEE Core.
Note: this commit depends on:
[optee_linuxdriver]
"tz: Fix handling of RPC parameters to supplicant"
[optee_client]
"Drop TEE_RPC_FREE_TA_WTH_FD, let it be TEE_RPC_FREE_TA"

Clean/simplify supplicant RPC parameters

---

core/arch/arm/arm.mk
mk/compile.mk
ta/arch/arm/arm.mk

Adds support to check source files with sparse when C=1 on the command
line. Only files that are recompiled are checked.
Note that sparse isn't very useful at this stage since the source code
need changes to be more sparse friendly.

Add sparse support [C=1]

---

core/arch/arm/kernel/tee_ta_manager.c

Some versions of GCC produce a "may be used uninitialized" error when
DEBUG=0 CFG_TEE_CORE_LOG_LEVEL=3.

Fix compile error

---

ta/arch/arm/link.mk

Fix possible TA build error with make -j: "Directory nonexistent"

---

ta/arch/arm/link.mk

With this commit, make -s is also silent when building TAs.

build: use $(cmd-echo-silent) when linking TAs

---

Makefile
ta/mk/ta_dev_kit.mk

With make 3.8x, in case of 'make all -s -w', MAKEFLAGS equals 'ws'
This patch correctly catches the flag 's'

Build: fix silent mode with make 3.8x

---

mk/cleanvars.mk

conf-file and conf-mk-file are valid for core and lib
compilation. These variables are set only once, when
starting the building.
Without this patch, the variables are cleaned when
compiling the libs. This affects the rules
$(objs): $(conf-file)
which forces the conf-file generation.
In case of parallel build, if libs are compiled before the
core, then conf-file is not created, which results in a
compilation error.

build: remove conf-file from cleanvars.mk

---

core/arch/arm/kernel/link.mk

Fixes occasional FIQ problem when pager is enabled.
Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (Juno, qemu)

arm: fixes FIQ problem with pager enabled

---

core/arch/arm/mm/core_mmu_v7.c

Clear tlb_info.table before use, because there maybe junk
data in this area. If not, system may crash when setting
ttbr0 as following:
core_mmu_set_user_map->write_ttbr0(map->ttbr0);
On my platform, the first entry of ttbr0 table is not set and it's
value is a random value. Switching ttbr0 crashes the system.
Signed-off-by: Peng Fan \<van.freenix@gmail.com\>

arm32: core_mmu_v7 clear tbl_info.table before use

---

core/arch/arm/mm/core_mmu.c
core/kernel/tee_misc.c

On ARMv7 platform, it is easy that "base + size" wraps down to 0.
For example, base is 0xfc100000, size is 0x3f00000, then base + size is 0.
We should use the "end" address to do the comparation, but not "end + 1".
This patch also can be used for ARMv8.
Signed-off-by: Peng Fan <van.freenix@gmail.com>

core: mm: fix adding integer overflow issue

---

.travis.yml
core/lib/libtomcrypt/include/tomcrypt_custom.h
core/lib/libtomcrypt/src/pk/ecc/ltc_ecc_mulmod_timing.c
core/lib/libtomcrypt/src/pk/ecc/sub.mk
core/lib/libtomcrypt/src/pk/sub.mk
core/lib/libtomcrypt/src/tee_ltc_provider.c
core/lib/libtomcrypt/sub.mk
documentation/crypto.md

GP Internal Core API v1.1 : LTC ECC build enable
Note: ECC-256 commented (legacy)

GP Internal Core API v1.1 : LTC ECC build enable

---

lib/libutee/tee_api_objects.c

…eason
Note Issue TEE_MEMORY_ACCESS_ANY_OWNER flag (next PR)

GP11 : TEE_RenamePersistentObject panic reason

---

core/tee/tee_svc_cryp.c

Make sure attribute is of reference type before checking its ref.length.
Fixes failure of xtest 4007 (TEE_ATTR_DH_X_BITS attribute) on HiKey and
FVP with 64-bit TEE core. Tested on HiKey and FVP (32 and 64-bit).

Fix buffer length test in tee_svc_cryp_obj_populate_type()

---

core/include/tee/tee_svc.h
core/tee/tee_svc.c
core/tee/tee_svc_cryp.c
core/tee/tee_svc_storage.c

arm64: fix buffer overflows when copying kernel addresses to user space

---

core/arch/arm/kernel/kern.ld.S

Fixes an issue on 64-bit HiKey when running the self-tests of
https://github.com/OP-TEE/optee_os/pull/371. The tests would pass
when CFG_TEE_CORE_LOG_LEVEL=2 but fail with static TA not found
when log level is 3.

Align __start_ta_head_section on 8-byte boundary

---

Makefile
core/arch/arm/plat-hikey/conf.mk
core/arch/arm/plat-mediatek/conf.mk
core/arch/arm/plat-stm/conf.mk
core/arch/arm/plat-sunxi/conf.mk
core/arch/arm/plat-vexpress/conf.mk
mk/config.mk

Also, for STM platforms, set CROSS_COMPILE=arm-linux-gnueabihf-
by default (which is a more standard prefix for the 32-bit
compiler).

Build for PLATFORM=vexpress-qemu_virt by default

---

lib/libutils/ext/include/types_ext.h
lib/libutils/isoc/include/unistd.h

Remove the duplicate definition of ssize_t to instead use a single definition.
Building OpenSSL as part of a TA resulted in both being included causing a build break.
Signed-off-by: Paul Swan paswan@microsoft.com
Reviewed-by: Youssef Esmat Youssef.Esmat@microsoft.com

Remove the duplicate definition of ssize_t

---

core/tee/tee_svc_cryp.c

Table 6-6 "Key-Pair Parts for Operation Modes" of Internal Core API v1.1
shows that public key is used in case of encrypt / verify, but that a
key pair can be given anyhow, only the public key part being used.

Fix Key-Pair Parts for Operation Modes

---

core/lib/libtomcrypt/src/tee_ltc_provider.c

In DES3, a key of 112 bits is made of 2 56 bits keys.
DES3 can be run using only 2 56 bit keys, with the 3rd
key being equal to the first.
Fix #408

Fix des3_cbc_mac in case of 112bits key

---

core/arch/arm/mm/core_mmu_lpae.c
core/arch/arm/mm/core_mmu_v7.c

1. Clear mmu table before fill entries
2. discard sizeof(uint64_t), but use XLAT_ENTRY_SIZE
3. Add an ERR msg if deivce virtual address conflicts with user ta address for armv7 non-lpae. Later need to find a way to fix this.

arm: mm clear mmu table before init

---

core/lib/libtomcrypt/src/hashes/sha1_armv8a_ce.c
core/lib/libtomcrypt/src/hashes/sha1_armv8a_ce_a32.S

This is some small refactoring to benefit from the HASH_PROCESS_NBLOCKS macro introduced in https://github.com/OP-TEE/optee_os/pull/418. As such please ignore the first two commits, they are from PR418.

arm: Update SHA-1 32-bit CE implementation to process multiple blocks

---

core/lib/libtomcrypt/src/hashes/sha2/sha256_armv8a_ce.c
core/lib/libtomcrypt/src/hashes/sha2/sha256_armv8a_ce_a32.S
core/lib/libtomcrypt/src/hashes/sha2/sub.mk

~~The first two commits are from https://github.com/OP-TEE/optee_os/pull/418 so please focus on the last one.~~ Edit: PR rebased on latest master.

arm: Update SHA-256 32-bit CE implementation to process multiple blocks

---

core/lib/libtomcrypt/src/hashes/sha1_armv8a_ce_a32.S

Commit 23900b599a98 ("arm: update SHA-1 32-bit CE implementation to
process multiple blocks") has introduced a regression on 32-bit
platforms when CFG_CRYPTO_SHA1_ARM32_CE=y. Test case: xtest 4006.

arm: Fix SHA-1 with cryptographic extensions

---

core/arch/arm/kernel/tee_ta_manager.c
core/arch/arm/tee/entry.c
core/include/kernel/tee_dispatch.h
core/include/kernel/tee_ta_manager.h
core/kernel/tee_dispatch.c
core/tee/tee_svc.c

TEE session handle is now used by all tee_dispatch_xx
function. uint32_t type ID parameter has be removed for
the tee_dispatch_close_session() function.
Signed-off-by: Jean-Michel Delorme <jean-michel.delorme@st.com>

Align Session handle for generic ta interface entry

---

lib/libutee/tee_api_operations.c

Tested-by: Pascal BRAND <pascal.brand@st.com>
Reviewed-by: Jean-Michel DELORME <jean-michel.delorme@st.com>

Fix #6738: remove useless src alignment check in TEE_UpdateXXX

---

core/lib/libtomcrypt/src/misc/mem_neq.c
lib/libutils/ext/buf_compare_ct.c

This fix comes from https://github.com/libtom/libtomcrypt/issues/74
mem_neq is a constant time comparison function, but it leaks information
on the secret data that is being compared in the value that is returned.

Fix leaking information from mem_neq

---

core/arch/arm/mm/tee_mmu.c

Correct the TA virtual address mapping calculation to properly support TA's more than 1Mb in size.
Signed-off-by: Paul Swan <paswan@microsoft.com>

Correct the TA virtual address mapping calculation

---

core/lib/libtomcrypt/src/encauth/ccm/ccm_add_aad.c
core/lib/libtomcrypt/src/encauth/ccm/ccm_add_nonce.c
core/lib/libtomcrypt/src/encauth/ccm/ccm_done.c
core/lib/libtomcrypt/src/encauth/ccm/ccm_init.c
core/lib/libtomcrypt/src/encauth/ccm/ccm_memory.c
core/lib/libtomcrypt/src/encauth/ccm/ccm_process.c
core/lib/libtomcrypt/src/encauth/ccm/ccm_test.c
core/lib/libtomcrypt/src/encauth/ccm/sub.mk

https://github.com/libtom/libtomcrypt/issues/73 highlighted NIST specifications
are not met in previous implementation. Here is the description of this issue:
According to the NIST specification of CCM, the authentication tag is
part of the ciphertext. In order to decrypt, this full ciphertext must
be decrypted, resulting in a "plaintext" tag. The tag must then be
recomputed upon the plaintext and compared with the decrypted value.
However, upon decryption in the libtom implementation, the ciphertext
is decrypted, and a tag is computed upon the header and (decrypted)
plaintext. This is then re-encrypted, so that the caller of the function
must compare the resulting (encryped) tag with the received (encrypted) tag.
The NIST specification specifies that "only the error message INVALID is …

libtomcrypt: sync ccm code

---

.travis.yml

.travis.yml is updated to run functional tests in QEMU after the
multi-platform builds. This involves:
- Cloning Git repositories using the Android 'repo' script (the
manifest is at https://github.com/OP-TEE/manifest)
- Building a bootable image containing Linux, OP-TEE and xtest, then
booting the image in QEMU and running the test suite ("make check")
Travis will report success only if all tests pass.
Now it takes 20 ~ 22 minutes to run .travis.yml on the Travis servers,
about 12 ~ 14 minutes more than before. ccache is enabled to speed up
the compilation as much as possible.
Some required tools are downloaded and compiled during the
before_install step: bc, Tcl and Expect. Indeed, they are not available
in the Travis container-based infrastructure, which we have to use to
enable ccache. …

Travis: run xtest in QEMU

---

core/arch/arm/kernel/trace_ext.c
lib/libutee/tee_user_mem.c
lib/libutee/trace_ext.c
lib/libutils/ext/include/trace.h
lib/libutils/ext/trace.c

Avoids random mixing of secure world traces with ones from the normal
world (assuming the normal world also flushes its debug traces
synchronously).

Flush traces synchronously

---

core/arch/arm/include/kernel/thread.h
core/arch/arm/kernel/tee_ta_manager.c
core/arch/arm/kernel/thread.c

Protect against deadlocks caused by single-instance TAs calling another
single-instance TAs directly or indirectly. When a TA is invoked but
already is busy with another operation the calling thread is suspended
using condvar_wait() until the TA is available again. This is
effectively a lock which can cause a deadlock if several such locks are
used at the same time but in different order.
This patch avoids this problem by only allowing one thread at a time to
set a single-instance TA context busy. If the thread with a
single-instance TA busy in the call stack tries to set an already busy
TA context busy it will return TEE_ERROR_BUSY instead as there is a
recursive loop in how the different TAs has invoked each other.
Tested-by: …

core: avoid deadlocks caused by single-instance TA

---

core/arch/arm/plat-stm/platform_config.h
core/arch/arm/plat-stm/system_config.mk

On plat-stm, available RAM for TA was 6MB. This is too small to run
xtest 1005 and 1006, which are opening multiple session of os_test
TA, which is huge.
This patch increases the available memory to TAs, to 14MB.

plat-stm: increase secure memory

---

core/tee/tee_svc_storage.c

Tested-by: Cedric Chaumont <cedric.chaumont@linaro.org> (STM boards)

Fix memory leak (start enum)

---

core/tee/tee_svc_storage.c

Fix start enum function potential memory leak
Add exit statement in enum functions when needed.
Rename tee_svc_storage_set_enum to storage_set_enum.

Fix potential memory leak

---

core/arch/arm/include/kernel/generic_boot.h
core/arch/arm/kernel/generic_boot.c
core/arch/arm/kernel/generic_entry_a32.S
core/arch/arm/kernel/kern.ld.S

When a paged OP-TEE binary is copied into secure memory with unpaged
code and data in the correct location, but with init code and hashes of
paged pages starting at the start of the .bss section. If .bss is large
enough init code and hashes will fit entirely in the .bss section and as
long as .bss is unused the data there is safe.
This assumption will not be true any longer if .bss shrinks dramatically
due to reduced size of mpa scratch memory.
With this patch the hashes will be copied to a temporary safe location
right after the init code. This location is the same as the start of the
.text_pageable section so the hashes must be copied to the final
location before the pager is initialized.

arm/pager: move init temp storage of hashes

---

.travis.yml
README.md
core/arch/arm/plat-imx/conf.mk
core/arch/arm/plat-imx/kern.ld.S
core/arch/arm/plat-imx/link.mk
core/arch/arm/plat-imx/main.c
core/arch/arm/plat-imx/platform_config.h
core/arch/arm/plat-imx/platform_flags.mk
core/arch/arm/plat-imx/sub.mk
core/drivers/imx_uart.c
core/drivers/sub.mk
core/include/drivers/imx_uart.h

The i.MX 6UltraLite[1] is a high performance, ultra-efficient processor
family featuring an advanced implementation of a single ARM® Cortex®-A7
core.
This patch add i.MX 6Ulralite EVK board support:
1. Add a uart driver for i.MX platforms
2. Introduce plat-imx for i.MX platforms
3. Introduce i.MX6 UltraLite platform
4. This patch has been tested using the following step,
4.1. build step:
PLATFORM_FLAVOR=mx6ulevk make ARCH=arm PLATFORM=imx
${CROSS_COMPILE}-objcopy -O binary out/arm-plat-imx/core/tee.elf optee.bin
copy optee.bin to the first partition of SD card which is used for boot.
4.2. Boot setting in uboot:
run loadfdt;
run loadimage;
fatload mmc 1:1 0x9c100000 optee.bin;
run mmcargs;
bootz ${loadaddr} - ${fdt_addr};
Note:
CAAM is not implemented now, this will be added later.
[1] …

arm: imx: add i.MX 6UltraLite and EVK board support

---

core/arch/arm/include/mm/tee_pager.h
core/arch/arm/kernel/link.mk
core/arch/arm/mm/tee_pager.c
core/lib/libtomcrypt/src/tee_ltc_provider.c

Libtomcrypt is using, because of mpa, some scratch memory
used in intermediate computation. These data are useless
once the acipher computation is completed. That means
that these data pages can be unmapped.
On QEMU, compiled with CFG_WITH_PAGER=y, "time xtest 4006" returns:
- Before the patch
real	3m 46.24s
user	0m 0.19s
sys	3m 45.51s
- After the patch
real	1m 29.00s
user	0m 0.17s
sys	1m 28.51s

pager: remove pages used by scratch memory

---

core/arch/arm/kernel/tee_ta_manager.c

Always return TEE_ERROR_SECURITY if tee_ta_load_check_shdr() fails
in any tests.

core: fix error code for corrupt TA

---

core/include/signed_hdr.h
ta/ta.mk

Exports `core/include/signed_hdr.h` and `lib/libutils/ext/include/types_ext.h` to `host_include` to be able to use `struct shdr` when testing TAs corrupted at different places.
Needed by https://github.com/OP-TEE/optee_test/pull/46

ta-dev-kit: export signed_hdr.h and types_ext.h

---

core/arch/arm/plat-hikey/conf.mk
core/arch/arm/plat-imx/conf.mk
core/arch/arm/plat-ls/conf.mk
core/arch/arm/plat-ls/platform_flags.mk
core/arch/arm/plat-mediatek/conf.mk
core/arch/arm/plat-stm/conf.mk
core/arch/arm/plat-sunxi/conf.mk
core/arch/arm/plat-ti/conf.mk
core/arch/arm/plat-vexpress/conf.mk
core/core.mk
mk/checkconf.mk

- Do not set CFG_ values that do not change the default
- Always use '?=' as opposed to ':=' for consistent behavior with
'X=Y make' and 'make X=Y'
- Always include mk/conf.mk last so that the platform definitions
always take precedence over the global configuration

plat-*/conf.mk cleanup

---

README.md

Since we have (re-)moved the repo instructions from OP-TEE/manifest.git
to OP-TEE/optee_os.git we had some inconsistency in our instructions.
This commit is a major update, where we have:
- Updated the Table of Contents.
- Have the old way of building in section 4 and the new way of build
(using repo) in section 5.
- Added clarifications and simplified a few sections.
- Added a known issues to Juno to address the current problem with
bl30.bin and bl33.bin.
- Updated, links to various pages, download locations and binaries.
- Fixed a few grammatical error.
- Added a "default" section telling how to probe the driver, run
tee-supplicant and run xtest.

README.md: Major update

---

README.md

The A80 boards exist in both locked (publicly available) an unlocked
versions (to Allwinner partners). Our main documentation has been
updated clarifying that this is the case.

docs: Allwinner clarifications about availability

---

core/arch/arm/include/kernel/time_source.h
core/arch/arm/kernel/tee_time.c
core/arch/arm/kernel/tee_time_arm_cntpct.c
core/arch/arm/kernel/tee_time_ree.c
core/include/kernel/tee_time.h
core/tee/tee_svc.c

- Set gpd.tee.systemTime.protectionLevel to 1000 when the time source
is the physical count register (CNTPCT), that is, when
CFG_SECURE_TIME_SOURCE_CNTPCT=y. The protection level value is moved
into the time_source struct for better modularity.
- When the time source is REE (CFG_SECURE_TIME_SOURCE_REE=y), make sure
that successive calls return increasing values as required by the GP
TEE Core Internal API v1.1.

core: TEE_GetSystemTime() updates

---

core/arch/arm/kernel/elf_load.c
core/arch/arm/kernel/tee_ta_manager.c
core/arch/arm/kernel/tee_time.c
core/arch/arm/kernel/thread.c
core/arch/arm/tee/arch_tee_fs.c
core/arch/arm/tee/entry_std.c
core/include/kernel/tee_common_unpg.h
core/tee/tee_svc_cryp.c
lib/libutee/include/utee_defines.h
lib/libutils/ext/include/util.h

It is assumed that the compiler keyword __alignof__ is available, so
CFG_TC_NO_ALIGNOF is of no use. We also remove unused definitions:
TEE_ALIGNMENT_*B_IS_OK().

core: remove unused code related to the TEE_ALIGNMENT_IS_OK() macro

---

core/arch/arm/plat-hikey/conf.mk
core/arch/arm/plat-mediatek/conf.mk
core/arch/arm/plat-vexpress/conf.mk
core/lib/libtomcrypt/sub.mk

When cryptographic extensions are used, and whatever the platform,
we have to ensure that VFP preservation is enabled too. Therefore it
makes sense to centralize the tests in core/lib/libtomcrypt/sub.mk
instead of having them in the platform-specific configuration files.
Incidentally, this adds a few missing statements to HiKey and Mediatek.

Avoid duplication of $(call force,CFG_WITH_VFP,y)

---

lib/libutils/sub.mk
mk/config.mk

Commit c3e0bd7 ("Delete libutil_with_isoc") wrongly assumed that the code
in lib/libutils/isoc is mandatory for any OP-TEE build. This is not true
for some non-upstream platforms which can find the functions in external
libraries.
Therefore, this commits makes the thing configurable again through
CFG_LIBUTILS_WITH_ISOC (default: y).
Reported-by: Pascal Brand <pascal.brand@linaro.org>

Make compilation of lib/libutils/isoc configurable again

---

core/tee/tee_svc_storage.c

Fix obj address in syscall_storage_obj_create()

---

core/arch/arm/include/kernel/tee_l2cc_mutex.h
core/arch/arm/kernel/tee_l2cc_mutex.c
core/arch/arm/mm/tee_mmu.c

Allocation of PL310 mutex in shared memory cannot use
malloc() as it is performed in fastcall, meaning without
any active thread.
This patch statically allocates, in the boot sequence, a mutex
that can be used as the l2cc_mutex, in shared memory.

Fix PL310 mutex allocation

---

core/core.mk
lib/libutils/isoc/bget_malloc.c
lib/libutils/isoc/include/malloc.h
mk/config.mk
ta/mk/ta_dev_kit.mk
ta/ta.mk

This patch enables built-in memory leak detection in
bget allocator. This is very helpful to find memory
leakage issue in teecore. To enable it, build optee_os
with 'CFG_TEE_CORE_ENABLE_MDBG=y'.
Then, add the following statement at some point of your
code that might frequently been triggered:
mdbg_check(1);
It will dump allocated memory blocks and the holders of
them. If you find a memory block appears multiple times
after the system runs a period of time, it is very likely
the source of memory leakage.
Here is an exmaple output:
ERR TEE-CORE:mdbg_check:720: Orphaned buffer: 0 bytes core/tee/tee_svc_storage.c:260
ERR TEE-CORE:mdbg_check:720: Orphaned buffer: 104 bytes core/tee/tee_svc_storage.c:444
ERR TEE-CORE:mdbg_check:720: Orphaned buffer: 18 bytes core/tee/tee_pobj.c:119
ERR …

debug: enable bget memory leak detection

---

core/tee/tee_svc.c

Fixes the following xtest failure on HiKey:
root@HiKey:/ xtest 8031
[...]
* XTEST_TEE_8031 a7-a3-6b
ERR [761] TEES:load_ta:317:   TA not found
ERR TEE-CORE:_assert_log:38: Assertion
'((vaddr_t)kaddr - tee_svc_uref_base) < UINT32_MAX' failed at
core/include/tee/tee_svc.h:83

core: syscall_open_ta_session: do not copy session if TA is not found

---

.travis.yml
Makefile
core/arch/arm/plat-vexpress/conf.mk
core/arch/arm/plat-vexpress/platform_flags.mk
lib/libutee/arch/arm/sub.mk
ta/arch/arm/arm.mk
ta/arch/arm/link.mk
ta/arch/arm/ta.ld.S
ta/mk/ta_dev_kit.mk
ta/ta.mk

This PR introduces one way of compiling 64-bit TAs. It's done by exporting two TA-dev-kits when compiling for arm64.
Another option would have been to only make one TA-dev-kit, but instead include multiple libs one set for 32-bit and another for 64-bit.
What do you think is the approach in this PR OK, or would you rather have something else?

RFC Ta64 3

---

core/arch/arm/kernel/tee_ta_manager.c
core/include/kernel/tee_misc.h
core/kernel/tee_misc.c
lib/libutils/ext/include/printk.h
lib/libutils/ext/snprintk.c
lib/libutils/ext/sub.mk
lib/libutils/ext/trace.c

The debug traces in tee_ta_manager.c do not show the last 8 bytes of
the TA UUIDs, which makes the output confusing sometimes.
This commit adds support for a new kprintf format for UUIDs: %pU, and
uses it in tee_ta_manager.c. For example:
TEE_UUID uuid;
DMSG("UUID: %pU", (void *)&uuid);
Note that %pU is supported only in kernel mode. The user-mode version of
libutils does not have it in order not to break standard compliance.

libutils (kernel): kprintf: add %pU for UUIDs, update tee_ta_manager.c

---

core/arch/arm/mm/tee_mmu.c

$ make \
CFG_ARM64_core=y \
CROSS_COMPILE_ta_arm64=aarch64-linux-gnu- \
CROSS_COMPILE=arm-linux-gnueabihf- \
CROSS_COMPILE_core=aarch64-linux-gnu- \
CROSS_COMPILE_ta_arm32=arm-linux-gnueabihf- \
DEBUG=0 \
PLATFORM=hikey \
CFG_TEE_CORE_LOG_LEVEL=2 \
CFG_TEE_TA_LOG_LEVEL=3
core/arch/arm/mm/tee_mmu.c: In function 'tee_mmu_map':
core/arch/arm/mm/tee_mmu.c:266:10: error: 'pa' may be used uninitialized in this function [-Werror=maybe-uninitialized]
paddr_t pa;
^
gcc version 4.9.2 20140811 (prerelease) (crosstool-NG linaro-1.13.1-4.9-2014.08 - Linaro GCC 4.9-2014.08) is ok but
gcc version 4.9.3 20150413 (prerelease) (Linaro GCC 4.9-2015.05) generates this error.

Fix compile error with newer gcc

---

core/arch/arm/plat-imx/conf.mk
core/arch/arm/plat-imx/platform_flags.mk
core/arch/arm/plat-ls/conf.mk
core/arch/arm/plat-ls/platform_flags.mk
core/arch/arm/plat-stm/conf.mk
core/arch/arm/plat-stm/platform_flags.mk
core/arch/arm/plat-sunxi/conf.mk
core/arch/arm/plat-sunxi/platform_flags.mk
core/arch/arm/plat-ti/conf.mk
core/arch/arm/plat-ti/platform_flags.mk
documentation/build_system.md
documentation/crypto.md

I didn't add ```CROSS_COMPILE_ta_arm32``` flag to ```.travis.yml``` since it should default correctly.
Update a couple of related docs as well.
Thanks!

Generate new TA dev kit for ARM32 platforms

---

.travis.yml

The QEMU build project now needs AARCH32_CROSS_COMPILE to be set.

Fix Travis build error (QEMU check)

---

documentation/arm_trusted_firmware.md

Both README.md and trace_levels.h say the level ranges from 1 to 4.

documentation/arm_trusted_firmware.md: Fixed maximum debug level

---

ta/ta.mk

When libutee is compiled, the configuration variable
CFG_TEE_PANIC_DEBUG is not exported to the C code as a pre-processor
macro (contrary to TEE core build, it does not happen automatically).
As a result, all the calls to TEE_Panic() that occur in the
GlobalPlatform API wrappers do not call EMSG() when the TA is about
to panic.
This commit fixes this issue by properly defining the C macro when the
configuration variable is enabled.
Conflicts:
ta/ta.mk

libutee: use CFG_TEE_PANIC_DEBUG setting

---

core/arch/arm/arm.mk
core/lib/libtomcrypt/include/tomcrypt_custom.h
core/lib/libtomcrypt/src/tee_ltc_provider.c

Some platforms, other than arm, may not support multiple
threads, or may have other support than the LTC_OPTEE_THREAD
thread scheme.
This patch defines LTC_OPTEE_THREAD for arm only platform,
and defines the no mutex mechanism in libtomcrypt

ltc: mutex support, in case of no mutex

---

.travis.yml
lib/libutee/tee_user_mem.c

$ make -j9 PLATFORM=hikey CFG_ARM64_core=y \
CROSS_COMPILE_core=aarch64-linux-gnu- \
CROSS_COMPILE_ta_arm64=aarch64-linux-gnu- \
CFG_TEE_TA_LOG_LEVEL=4
[...]
lib/libutee/tee_user_mem.c: In function ‘heap_inc’:
lib/libutee/tee_user_mem.c:195:2: error: format ‘%d’ expects argument of type ‘int’, but argument 6 has type ‘size_t’ [-Werror=format=]
INMSG("%d", size);
^

Fix 64-bit build errors when CFG_TEE_TA_LOG_LEVEL == TRACE_FLOW (4)

---

core/arch/arm/tee/arch_svc_a32.S

Since the assembly function tee_svc_do_call() uses registers r5 and r6,
it must push them on entry and restore them on exit.

arm32: tee_svc_do_call() must preserve r5 and r6

---

core/arch/arm/tee/arch_svc.c
core/include/tee/tee_svc.h
core/tee/tee_svc.c

When CFG_TEE_CORE_LOG_LEVEL >= 4, a debug trace is printed whenever a
system call is entered. Currently it just prints the syscall number,
which is not very convenient. This commit adds the name of the syscall
function to the trace.

core: trace_syscall(): print the syscall name in addition to its number

---

mk/checkconf.mk

The generated conf.mk configuration file no more replaces
CFG_xxx=n with commented configuration settings "# CFG_xxx is
not set" and preserve the CFG_xxx=n setting.
This allows one to fully reuse the generated conf.mk as an
input configuration to regenerate the firmware with the
same configuration directive.

core config: generate cnf.mk preserves CFG_xxx=n

---

documentation/optee_design.md

Big lock is not used in the source any more, remove it from
documentation too.

doc: remove references to big lock

---

CHANGELOG.md

Release notes

---

core/arch/arm/kernel/link.mk
core/tee/sub.mk
core/tee/tee_svc.c
mk/config.mk

Replaces CFG_TEE_IMPL_VERSION with TEE_IMPL_VERSION to avoid updating
<out-dir>/core/include/generated/conf.h each time description of the current
git commit is changed.
This avoids full recompiles that can't even be cached just because some
files has changed in an updated commit.

Replace CFG_TEE_IMPL_VERSION with TEE_IMPL_VERSION

---

.travis.yml
core/arch/arm/tee/tee_rpmb.c
core/include/tee/tee_rpmb.h
core/include/tee/tee_rpmb_fs.h
core/tee/sub.mk
core/tee/tee_fs_private.h
core/tee/tee_rpmb_fs.c
core/tee/tee_rpmb_fs_common.c

This is an update to the RPMB filesystem implementation so that the
persistent object API may use RPMB rather than the REE filesystem.
This feature is enabled with CFG_RPMB_FS=y.
Note that this implementation requires support from the non-secure side
to actually access the RPMB partition, as there is no eMMC driver here.
Also, the code is currently not compatible with CFG_ENC_FS (file
encryption), which must be set to 'n'. Encryption will be added later.
** Note: Initial patches from:
https://github.com/Microsoft/optee_os/tree/rpmb2
Youssef/Paul, please let me know if you're OK with having your
Signed-off-by: below. Also it would be good if you could provide a
Tested-by: for your platform, or discuss any issue you might have with
the changes I have introduced. I will delete this notice …

core: RPMB (Replay Protected Memory Block) filesystem support

---

.travis.yml

Sourceforge has been quite unreliable recently, and we have had a
number of build failures due to Tcl or Expect failing to download.
This patch adds the files to the Travis cache so that they will not
need to be downloaded again unless the cache is purged.

Travis: cache files downloaded from Sourceforge

---

core/arch/arm/kernel/abort.c
core/arch/arm/kernel/generic_boot.c
core/arch/arm/kernel/tee_ta_manager.c
core/arch/arm/kernel/thread.c
core/arch/arm/kernel/user_ta.c
core/arch/arm/kernel/wait_queue.c
core/arch/arm/plat-vexpress/main.c
core/kernel/panic.c
core/lib/libtomcrypt/src/tee_ltc_provider.c
core/tee/tee_svc.c
core/tee/tee_svc_cryp.c
lib/libutee/assert.c
lib/libutils/ext/include/compiler.h

When a variable, parameter or function may or may not be referenced
depending on some conditional compilation setting, mark it with
__maybe_unused instead of __unused.

core: introduce __maybe_unused

---

core/arch/arm/arm.mk
core/arch/arm/include/arm32.h
core/arch/arm/include/kernel/thread.h
core/arch/arm/include/kernel/user_ta.h
core/arch/arm/include/kernel/vfp.h
core/arch/arm/kernel/abort.c
core/arch/arm/kernel/elf_load.c
core/arch/arm/kernel/generic_boot.c
core/arch/arm/kernel/thread.c
core/arch/arm/kernel/thread_a32.S
core/arch/arm/kernel/thread_private.h
core/arch/arm/kernel/user_ta.c
core/arch/arm/kernel/vfp.c
core/arch/arm/plat-imx/conf.mk
core/arch/arm/plat-ls/conf.mk
core/arch/arm/plat-stm/conf.mk
core/arch/arm/plat-sunxi/conf.mk
core/arch/arm/plat-ti/conf.mk
core/arch/arm/tee/arch_svc.c
core/core.mk
lib/libutils/isoc/arch/arm/arm32_aeabi_softfloat.c
mk/config.mk

Adds support for hard-float in TAs. Hard-float is enabled by default for
all platforms which are capable, currently all. Soft-float is still
available if needed.

arm: add TA hard-float support

---

core/arch/arm/include/kernel/thread.h
core/arch/arm/kernel/thread.c
core/arch/arm/kernel/thread_a32.S
core/arch/arm/kernel/thread_a64.S
core/arch/arm/kernel/thread_private.h
core/arch/arm/plat-hikey/main.c
core/arch/arm/plat-imx/main.c
core/arch/arm/plat-ls/main.c
core/arch/arm/plat-mediatek/main.c
core/arch/arm/plat-stm/main.c
core/arch/arm/plat-sunxi/main.c
core/arch/arm/plat-ti/main.c
core/arch/arm/plat-vexpress/main.c

Removes the possibility to register svc and abort handlers as the same
handler is always used. The svc and abort handlers are also so closely
tied to thread system that it would be difficult and error prone to use
alternative handlers.

core: remove registration of svc and abort handlers

---

core/arch/arm/arm.mk
core/core.mk
documentation/build_system.md
mk/config.mk
ta/mk/ta_dev_kit.mk
ta/ta.mk

Currently, to build a 64-bit TEE core (as well as mixed 32- and 64-bit
TA libraries, which are automatically enabled in this case), one has to
set too many compiler variables:
$ make PLATFORM=hikey CFG_ARM64_core=y \
CROSS_COMPILE_core=aarch64-linux-gnu- \
CROSS_COMPILE_ta_arm64=aarch64-linux-gnu-
This commit introduces two variables, CROSS_COMPILE32 and
CROSS_COMPILE64. They take appropriate default values, so that the
above line may be simplified as:
$ make PLATFORM=hikey CFG_ARM64_core=y
The change remains compatible with previous builds, i.e., CROSS_COMPILE
can still be used to define the 32-bit compiler because CROSS_COMPILE32
defaults to $(CROSS_COMPILE). Similarly, CROSS_COMPILE_core and
CROSS_COMPILE_ta_arm{32,64} are still used so they may be overriden
directly.
Signed-off-by: …

Introduce CROSS_COMPILE32 and CROSS_COMPILE64

---

core/arch/arm/mm/core_mmu_v7.c

see Bug #643 
Change-Id: Ibc7aa5063265a78112bff761fdb55490cfc0d7f3
Signed-off-by: Patrick Delaunay <patrick.delaunay73@gmail.com>

core/armv7: solve map issue for unaligned pa

---

.travis.yml
core/arch/arm/tee/tee_rpmb.c
core/include/tee/tee_fs_key_manager.h
core/include/tee/tee_rpmb.h
core/include/tee/tee_rpmb_fs.h
core/tee/sub.mk
core/tee/tee_fs_key_manager.c
core/tee/tee_rpmb_fs.c
mk/config.mk

Minor updates to RPMB code + adding CBC/ESSIV encryption when `CFG_ENC_FS=y`.
Replaces https://github.com/OP-TEE/optee_os/pull/626.

RPMB encryption

---

.travis.yml

Many build commands needlessly set some variables to their default
values: simplify that. Also, reformat commands to make lines shorter,
and introduce variable make="make -j3 -s".

.travis.yml: simplify build commands

---

lib/libutils/ext/trace.c

Fixes issue https://github.com/OP-TEE/optee_os/issues/660
Tested-by: Joakim Bech <joakim.bech@linaro.org> (QEMU)

Fixes buffer overflow in trace_printf

---

core/lib/libtomcrypt/include/tomcrypt.h
core/lib/libtomcrypt/include/tomcrypt_custom.h
core/lib/libtomcrypt/include/tomcrypt_macros.h
core/lib/libtomcrypt/include/tomcrypt_pk.h
core/lib/libtomcrypt/src/pk/asn1/der/bit/der_decode_raw_bit_string.c
core/lib/libtomcrypt/src/pk/asn1/der/bit/der_encode_raw_bit_string.c
core/lib/libtomcrypt/src/pk/asn1/der/bit/sub.mk
core/lib/libtomcrypt/src/pk/asn1/der/boolean/der_decode_boolean.c
core/lib/libtomcrypt/src/pk/asn1/der/choice/der_decode_choice.c
core/lib/libtomcrypt/src/pk/asn1/der/integer/der_encode_integer.c
core/lib/libtomcrypt/src/pk/asn1/der/sequence/der_decode_sequence_ex.c
core/lib/libtomcrypt/src/pk/asn1/der/sequence/der_decode_sequence_flexi.c
core/lib/libtomcrypt/src/pk/asn1/der/sequence/der_decode_sequence_multi.c
core/lib/libtomcrypt/src/pk/asn1/der/sequence/der_decode_subject_public_key_info.c
core/lib/libtomcrypt/src/pk/asn1/der/sequence/der_encode_sequence_ex.c
core/lib/libtomcrypt/src/pk/asn1/der/sequence/der_encode_sequence_multi.c
core/lib/libtomcrypt/src/pk/asn1/der/sequence/der_encode_subject_public_key_info.c
core/lib/libtomcrypt/src/pk/asn1/der/sequence/der_length_sequence.c
core/lib/libtomcrypt/src/pk/asn1/der/sequence/der_sequence_free.c
core/lib/libtomcrypt/src/pk/asn1/der/sequence/sub.mk
core/lib/libtomcrypt/src/pk/asn1/der/set/der_encode_set.c
core/lib/libtomcrypt/src/pk/asn1/der/set/der_encode_setof.c
core/lib/libtomcrypt/src/pk/asn1/der/sub.mk
core/lib/libtomcrypt/src/pk/asn1/der/teletex_string/der_decode_teletex_string.c
core/lib/libtomcrypt/src/pk/asn1/der/teletex_string/der_length_teletex_string.c
core/lib/libtomcrypt/src/pk/asn1/der/teletex_string/sub.mk
core/lib/libtomcrypt/src/pk/asn1/der/utf8/der_encode_utf8_string.c

- Synchronization with LibTomCrypt from
origin/develop branch
(commit 4a3b53dbee4bca1f151d9a64e9584a4c8152f0b1)
- Only "src/pk/asn1/der" directory has been synchronized
- Additional changes over synchronization:
Several default case added in switch case condition
when missing.
Signed-off-by: Philippe PAGE <philippe.page@st.com>

libtomcrypt: ASN1/DER fixes

---

mk/gcc.mk

GCC requires the --sysroot command line parameter
to find libgcc.a
Signed-off-by: Zoltan Kuscsik <zoltan.kuscsik@linaro.org>

Add CLFAGS to libgcc lookup command

---

core/arch/arm/arm.mk
mk/compile.mk
mk/config.mk
mk/gcc.mk

This is a fix on top of https://github.com/OP-TEE/optee_os/pull/664.

Introduce CFLAGS32 and CFLAGS64

---

core/arch/arm/kernel/generic_entry_a32.S

The pager and GDB boot configurations assign different meanings to the
r0 register when entering the _start function. Therefore, they must not
be enabled at the same time.

arm32: CFG_WITH_PAGER and CFG_TEE_GDB_BOOT are incompatible

---

mk/compile.mk

With this commit it is possible to remove a CPP/C/AS flag for the
submodule being built. For instance suppose one adds the following
to core/core.mk:
cflags-remove-core += -pedantic
...then the '-pedantic' flag will be stripped off from the command
line when building any C file of the TEE core.
Previously, one could remove flags only on a global basis or for a
single file.

mk/compile.mk: add 'remove' flags variable for submodule

---

core/arch/arm/kernel/tee_time.c
core/arch/arm/kernel/wait_queue.c
core/arch/arm/tee/arch_tee_fs.c
core/arch/arm/tee/tee_rpmb.c

As the translation tables used to create user TA mapping are assigned
per thread there's no need to clear current session before RPC and
restore it when the RPC has returned.

core: don't clear current session before RPC

---

ta/arch/arm/link.mk

Cleaning TA $(link-script-dep) is especially important when
switching from 32bits mode to 64bits mode compilation of the TAs

TA: clean $(link-script-dep)

---

core/arch/arm/kernel/abort.c
core/arch/arm/mm/core_mmu_lpae.c

Currently, when a data or instruction abort occurs in a TA, the crash
dump does not clearly show the fault type. One has to decode the
Exception Syndrome Register to understand if it's a translation or
alignment fault for instance. This commit decodes these two likely
values for convenience.

arm64: add fault type to crash dump

---

core/arch/arm/include/kernel/abort.h
core/arch/arm/kernel/abort.c

Fixes previous f2930adaf8a10f2a6154ae21ec991ce7133fde82 "Add fault type
to crash dump" to only interpret fault_descr for data and prefetch abort
to avoid asserting if fault_descr is 0 for LPAE.
Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (QEMU with LPAE)

fix: Add fault type to crash dump

---

ta/arch/arm/user_ta_header.c

According to GP Internal API, TA_STACK_SIZE corresponds to the stack
size used by the TA code itself and does not include stack space
possibly used by the Trusted Core Framework.
Hence, stack_size which is the size of the stack to use,
must be enlarged.
Without this patch, on FVP, xtest 1012, based on ta/sims, fails because
TA_STACK_SIZE is defined as 1024, which is too low.
Note that the number 1152 has been found experimentally, using a
TA that does nothing, on FVP.

arm: fix stack size

---

.travis.yml

travis.xml clones the Git repositories with depth 1, thereby reducing
the duration of the "repo sync" step from 4-6 minutes down to about 1
min.

Travis: QEMU check: use travis.xml manifest to speed up repo download

---

.travis.yml
Makefile
core/arch/arm/include/kernel/user_ta.h
core/arch/arm/kernel/abort.c
core/arch/arm/kernel/sub.mk
core/arch/arm/sta/sub.mk
core/arch/arm/tee/sub.mk
core/arch/arm/tee/svc_dummy.c
core/tee/sub.mk
mk/config.mk

Hide all user TA related code under CFG_WITH_USER_TA. When compiled
with:
export CFG_WITH_USER_TA=n
export CFG_SE_API_SELF_TEST=n
export CFG_TEE_FS_KEY_MANAGER_TEST=n
export CFG_CRYPTO=n
export CFG_ENC_FS=n
The size of OP-TEE is reduced to one third of its original size.
Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (QEMU xtest 1001)

Minimal OP-TEE without user TAs

---

core/arch/arm/include/sm/sm.h
core/arch/arm/kernel/thread_a32.S
core/arch/arm/sm/sm_a32.S

Currently there's a security problem with the FIQ registers for armv7
targets, both with leaking information and that normal world can change
stack pointer for FIQ mode. This patch fixes this problem.
Saves and restores FIQ core registers (spsr, sp, lr) when switching
secre/non-secure state.
Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (modified QEMU)

arm: sm: [bugfix] save/restore fiq core registers

---

mk/config.mk

There is really no guarantee that the values of CFG_OPTEE_REVISION_MAJOR and
CFG_OPTEE_REVISION_MINOR can be extracted from Git (think about building from a
tarball or "git clone --depth=1"), so let's just hardcode them into the
configuration.

mk/config.mk: hardcode CFG_OPTEE_REVISION_{MAJOR,MINOR}

---

core/arch/arm/plat-hikey/platform_config.h

This is needed to run the latest "generic driver" configuration, i.e.:
https://github.com/OP-TEE/optee_os/pull/702
https://github.com/OP-TEE/optee_client/pull/47
https://github.com/OP-TEE/optee_test/pull/75
https://github.com/linaro-swg/linux/tree/optee
When the shared memory pool is 1 MiB, xtest 7633 fails with a TA panic
due to memory allocation error. This commit increases the size of the
shared memory pool so that the test will pass.
Note that UEFI (EDK2) reserves the top 32 MiB of the physical address
space (0x3E000000-0x3FFFFFFF) for OP-TEE, so we still have 14 MiB unused
(0x3E000000-0x3EDFFFFF).

hikey: increase shared memory size from 1 to 2 MiB

---

core/arch/arm/tee/arch_tee_fs.c

When thread_rpc_alloc_payload() fails, the cookie is not valid, so
thread_rpc_free() must not be called. This fixes a crash in xtest
7633 when shared memory is not large enough.

fs: do not call thread_rpc_free() when allocation fails

---

core/arch/arm/include/kernel/thread.h
core/arch/arm/include/sm/optee_smc.h
core/arch/arm/kernel/thread.c
core/arch/arm/kernel/user_ta.c
core/arch/arm/mm/tee_pager.c
core/arch/arm/tee/arch_tee_fs.c
core/arch/arm/tee/tee_rpmb.c
core/include/optee_msg.h

Buffers allocated with OPTEE_MSG_RPC_CMD_SHM_ALLOC must be freed
with OPTEE_MSG_RPC_CMD_SHM_FREE to help normal world driver to
route the message correctly.
This PR depends on using https://github.com/linaro-swg/linux/tree/optee or a branch with corresponding tee driver patches
Merging this PR needs to be synchronized with PRs in optee_client, optee_test, build and manifest.

optee_msg: add OPTEE_MSG_RPC_CMD_SHM_FREE

---

core/arch/arm/include/arm64.h
core/arch/arm/mm/core_mmu_lpae.c

Prior to this patch TCR_EL1 was incorrectly initialized with bit 32 set
to 0. On Cortex-A57 this bit is RES1 so this bit should always be set to
1, this patch fixes that.
This is related to errata 822227
"Using unsupported 16K translation granules might cause Cortex-A57 to
incorrectly trigger a domain fault"
Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (Juno)

juno: bug fix initialize TCR_EL1

---

README.md

Since we no longer use a dynamically loadable module as the TEE driver
we have removed that from the README.md file.

docs: Remove modprobe instruction

---

.travis.yml
core/arch/arm/include/mm/core_mmu.h

Fixes build error when CFG_TEE_CORE_DEBUG=y and CFG_WITH_PAGER=y are set
by adding ing CORE_MMU_PGDIR_SIZE and CORE_MMU_PGDIR_MASK.

core: fix build error with CFG_TEE_CORE_DEBUG=y

---

core/arch/arm/plat-stm/asc.S
core/arch/arm/plat-stm/main.c
core/arch/arm/plat-stm/tz_a9init.S

On plat-stm, traces IP is initialized by Non Secure world.
Hence no traces can be output while in the booting process.

plat-stm: fix traces

---

core/arch/arm/kernel/elf_load.c
core/arch/arm/kernel/elf_load.h
core/arch/arm/kernel/user_ta.c
core/arch/arm/mm/tee_mmu.c
core/include/mm/tee_mmu.h
ta/arch/arm/ta.ld.S

Maps user TA with strict permissions. Blocks with mixed permissions are
mapped with the union of the permissions. In order to take full
advantage of the strict permissions TAs should be mapped using small
pages, that is, using the config option CFG_SMALL_PAGE_USER_TA = y.
I've found and corrected the problem (cache attributes for stack and code in user mode) in the original pull request. This pull request replaces  https://github.com/OP-TEE/optee_os/pull/689

core: map TA with strict permissions

---

lib/libutee/tee_api_objects.c

Fix https://github.com/OP-TEE/optee_os/issues/757

TEE_GetNextPersistentObject: objectInfo is optional

---

core/arch/arm/plat-sunxi/platform.c
core/arch/arm/plat-sunxi/smp_boot.S
core/arch/arm/plat-vexpress/main.c
core/drivers/gic.c
core/include/kernel/interrupt.h
core/kernel/interrupt.c
core/kernel/sub.mk

Adds interrupt frameworks and adjusts gic driver to fit in.
Update plat-vexpress and sunxi platforms to initialize gic with slightly
modified interface.

core: add interrupt framework

---

lib/libutils/isoc/newlib/sub.mk

When doing builds with –O3, the GCC compiler in some cases generates
re-entrant code for memset() function which can result in calling itself
infinitely causing overflow of stack & data corruption. One way to
prevent this from happening is to enable the -fno-builtin compiler flag.
Tested-by: Joakim Bech <joakim.bech@linaro.org> (QEMU)
Suggested-by: Alexei Fedorov <alexei.fedorov@arm.com>

newlib: Add -fno-builtin to all functions/files

---

core/arch/arm/kernel/thread_a64.S

Prior to this patch reception of a FIQ while in secure user mode (secure
EL0) would be treated as if an IRQ was received instead. This resulted
in an exit to normal world and when FIQ was unmasked it would be
re-triggered but this time received as an FIQ received while in normal
world.
This patch fixes this and handles FIQ directly when received while in
secure user mode.

core: fix fiq delivery in Aarch64

---

core/tee/tee_svc_storage.c

When creating a Persistent Object (TEE_CreatePersistentObject)
using an object handle, the information and attributes related
to the handle are saved.
The information are restored when opening the object
(TEE_OpenPersistentObject)
Fixes #785

Persistent objects: save handle information

---

core/arch/arm/include/arm32_macros.S
core/arch/arm/kernel/ssvce_a32.S

When invalidating i-cache and branch predictor use inner shareable
(icialluis and bpiallis) versions of the operations to make it visible
to other cores.
Fixes occasional problem with pager with multiple active threads.
Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (HiKey)
Fixes https://github.com/OP-TEE/optee_os/issues/794

core: arm: invalidate i-cache inner shareable

---

core/arch/arm/kernel/thread_a32.S

Before this patch FIQ and asynchronous abort wasn't masked on
all exit paths. This patch fixes that.

core: arm32: fix masking exceptions on exit

---

core/include/tee/tee_obj.h
core/include/tee/tee_svc_cryp.h
core/tee/tee_obj.c
core/tee/tee_svc_cryp.c
core/tee/tee_svc_storage.c

Prior to the patch the attribute management of tee objects occasionally
assumed that the attribute data didn't contain any addresses. This
assumption is incorrect for asymmetric key objects. This patch fixes
that by introducing an operation struct for each basic attribute type.

core: fix tee object attribute management

---

core/tee/tee_svc_cryp.c

Fixes short buffer check at end of tee_obj_attr_to_binary().

tee_obj_attr_to_binary: fix short buffer check

---

scripts/render_font.py

Don't print "Writing <file>" by default. Add --verbose option for this.

scripts/render_font.py: suppress console output

---

core/arch/arm/plat-hikey/conf.mk

Set CFG_NUM_THREADS to 8 by default for HiKey since the board has
8 cores.

hikey: enable 8 threads by default

---

.travis.yml

By default we have more or less done Travis builds with
CFG_TEE_CORE_LOG_LEVEL=4 DEBUG=1
CFG_TEE_CORE_LOG_LEVEL=0
Implicitly the CFG_TEE_TA_LOG_LEVEL has been set to 3 and due to this we
have in some cases missed things like the issue described in:
https://github.com/OP-TEE/optee_os/issues/848
We should also let Travis build "no debug, no debug-print" builds to
capture such errors and therefore we've added/changed all
CFG_TEE_CORE_LOG_LEVEL=0
to instead say
CFG_TEE_CORE_LOG_LEVEL=0 CFG_TEE_TA_LOG_LEVEL=0 DEBUG=0

travis: Add non-print,debug builds for all targets

---

.travis.yml

It happened a few times that the Linaro release server cannot be
reached over HTTPS. The error is as follows:
wget https://releases.linaro.org/components/toolchain/binaries/5.3-2016.02/aarch64-linux-gnu/gcc-linaro-5.3-2016.02-x86_64_aarch64-linux-gnu.tar.xz
--2016-06-14 08:52:10--  https://releases.linaro.org/components/toolchain/binaries/5.3-2016.02/aarch64-linux-gnu/gcc-linaro-5.3-2016.02-x86_64_aarch64-linux-gnu.tar.xz
Resolving releases.linaro.org (releases.linaro.org)... 54.188.124.233
Connecting to releases.linaro.org (releases.linaro.org)|54.188.124.233|:443... connected.
OpenSSL: error:0407006A:rsa routines:RSA_padding_check_PKCS1_type_1:block type is not 01
OpenSSL: error:04067072:rsa routines:RSA_EAY_PUBLIC_DECRYPT:padding check failed
OpenSSL: error:1408D07B:SSL …

Travis: download Linaro toolchain over HTTP rather than HTTPS

---

core/arch/arm/mm/tee_mm.c
core/arch/arm/mm/tee_mmu.c
core/arch/arm/sta/stats.c
core/include/mm/tee_mm.h

Tested-by: Joakim Bech <joakim.bech@linaro.org>
Suggested-by: Sandeep Tripathy <sandeep.tripathy@broadcom.com>

Removing legacy pub_ddr init code

---

README.md

Changing hikey build to use mtools instead of sudo/mount eliminates
the need for root access during the build.  Document this dependency.
Signed-off-by: David Brown <david.brown@linaro.org>

docs: Add mtools to dependencies

---

core/include/kernel/tee_ta_manager.h
core/kernel/tee_ta_manager.c
core/tee/tee_svc.c

Fixes race to allocate secure buffer for TA to TA communication.

core: fix race to allocate secure buffer

---

core/tee/tee_svc_storage.c

As per the GP specification for functions TEE_OpenPersistentObject(),
TEE_CreatePersistentObject() and TEE_StartPersitetntObjectEnumerator(),
return TEE_ERROR_ITEM_NOT_FOUND when the storage ID is invalid instead
of TEE_ERROR_STORAGE_NOT_AVAILABLE.
Note:
The code modified in this commit cannot currently be reached because
libutee rejects invalid storage IDs with TEE_ERROR_ITEM_NOT_FOUND
already. But a patch is on the way [1] that will remove this user-mode
test, so fix the bug before it can happen.
[1] https://github.com/OP-TEE/optee_os/pull/938

storage: return TEE_ERROR_ITEM_NOT_FOUND when storage ID is unknown

---

core/arch/arm/kernel/generic_entry_a64.S

The PC relative load (`adr`) requires the destination label to be
within 1MB of the instruction itself.  If for example, the HEAP_SIZE
is increased too much, this can push the `_end` pass this limit.
Replace the single `adr` instruction with a pair (`adrp`, `add`) to
allow the symbol to load from any address.
Note that the increasing the heap size too much causes other failures.
Fixes #942.
Signed-off-by: David Brown <david.brown@linaro.org>

Allow `_end` to be more than 1MB away from code

---

core/include/tee/tee_fs_key_manager.h
core/tee/tee_fs_key_manager.c
core/tee/tee_rpmb_fs.c
documentation/secure_storage.md
documentation/secure_storage_rpmb.md

The File Encryption Key is now encrypted with a Trusted application
Storage Key (TSK) rather than directly with the Secure Storage Key.
The TSK is derived from the SSK and the TA UUID. This improves
isolation between TAs, and makes it impossible to read the data of a
TA from another TA after manually moving files in the REE filesystem
for instance.

storage: encrypt the FEK with a TA-specific key

---

core/tee/tee_rpmb_fs.c

The File Encryption Key is generated randomly but not encrypted by the
key manager before being written to the RPMB FAT. In other words, we
consider that the RNG outputs an already encrypted key.
For consistency, call tee_fs_generate_fek() instead.

storage: rpmb: call tee_fs_generate_fek() to generate FEK

---

.travis.yml

OP-TEE contains code imported from Open Source libraries or
designed to comply with GlobalPlatform specifications. Such code will
trigger checkpatch.pl errors whenever the Linux kernel coding rules are
violated. Such message are useless and actually make the CI loop look
like the builds are failing when they are actually correct.
To fix this, add a list of directories that should be ignored by
'git format-patch' when producing the diff fed into checkpatch.pl.

Travis: exclude some paths when running the coding style tool

---

core/arch/arm/kernel/thread_a64.S

Before this patch debug and asynchronous abort wasn't masked
when doing a normal return from call. This patch fixes that.
Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (QEMUv8)

core: arm64: fix masking exceptions on normal exit

---

mk/aosp_optee.mk

fix build error:
In file included from core/arch/arm/kernel/thread.c:29:0:
core/arch/arm/plat-aquila/./platform_config.h:51:2: error: #error "Unknown platform flavor"
#error "Unknown platform flavor"
Signed-off-by: Zhizhou Zhang <zhizhou.zh@gmail.com>

build: add PLATFORM_FLAVOR for BUILD_OPTEE_OS

---

core/lib/libfdt/fdt_rw.c

Fixes undefined sanitizer problem in fdt_setprop().
Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (QEMUv7)

libfdt: undef sanitizer fix fdt_setprop()

---

.travis.yml
MAINTAINERS.md
README.md
core/arch/arm/plat-rcar/conf.mk
core/arch/arm/plat-rcar/kern.ld.S
core/arch/arm/plat-rcar/link.mk
core/arch/arm/plat-rcar/main.c
core/arch/arm/plat-rcar/platform_config.h
core/arch/arm/plat-rcar/sub.mk
core/drivers/scif.c
core/drivers/sub.mk
core/include/drivers/scif.h

I have added new platform - plat-rcar.
There are only minimal peripherals support at this time. Only debug UART is working. Anyways, it was tested on renesas salvator-x board. All tests from xtest suite have passed successfully.

Add support for Renesas RCAR H3

---

core/lib/libtomcrypt/src/pk/rsa/rsa_verify_hash.c

Fixes CVE-2016-6129
cherry-picked from:
https://github.com/libtom/libtomcrypt/commit/5eb9743410ce4657e9d54fef26a2ee31a1b5dd09
Tested by https://github.com/OP-TEE/optee_test/pull/120

rsa_verify_hash: fix possible bleichenbacher signature attack

---

.travis.yml

Commit 0bbd70a5c13c ("travis: exclude some paths when running the
coding style tool") is broken in several ways:
- It will not properly exclude the specified paths from the diff output
because the exclamation mark (!) is not correctly protected when
setting $_CP_EXCL. Let's use ":(exclude)" instead of ":!".
- Even with the above fixed, Travis runs an older version of Git that
does not support pathspec magic ":!" or ":(exclude)". Address that by
compiling Git 2.9.3 from source. This adds about 60-75 seconds to the
build time with a cold cache, 8 seconds when the cache is warm.
- In addition, git format-patch need a commit range (HEAD^..HEAD).
Otherwise it will pick the next oldest patch in case the diff is empty
(due to all changes being excluded).
Signed-off-by: Jerome Forissier …

travis: fix coding style path exclusion

---

.travis.yml

`git format-patch --stdout -1` do not work as expected. In addition to
checking only one commit (as opposed to all the commits in a PR), it
may pick the wrong commit. For instance, when the PR contains several
commits, it shows the tip of the target branch instead of the tip of
the PR branch. So we have to modify the way the commits are selected.
There are two reasons why a Travis build is triggered: either a pull
request, or a branch is pushed to a monitored repository. One can tell
the two cases appart thanks to the $TRAVIS_PULL_REQUEST environment
variable.
- In the first case (pull request), HEAD is always a merge commit
between the development branch and the target branch. Use `git
rev-list` to expand the list of commits in HEAD^1..HEAD^2 (those that
are in the dev branch but not in …

travis: run coding style tool on each commit in a pull request

---

core/arch/arm/kernel/thread.c

thread_std_smc_entry() should set the frame pointer (x29) to zero to
indicate the end of the frame record chain, as required by the Aarch64
AAPCS. Without this, there is no guarantee that unwind_stack() will
terminate.

core: arm64: thread_std_smc_entry(): set FP to 0 before calling C code

---

core/arch/arm/include/arm32.h
core/arch/arm/include/arm64.h
core/arch/arm/include/kernel/unwind.h
core/arch/arm/kernel/unwind_arm32.c
core/arch/arm/kernel/unwind_arm64.c
lib/libutils/ext/include/compiler.h
lib/libutils/ext/include/trace.h
lib/libutils/isoc/include/sys/cdefs.h

Adds [EIDF]PRINT_STACK() for debugging purposes.
Depends on CFG_CORE_UNWIND=y.

trace.h: add macros to unwind and print the call stack (kernel only)

---

core/arch/arm/mm/tee_mm.c
core/arch/arm/sta/stats.c
core/include/mm/tee_mm.h
lib/libutils/isoc/bget_malloc.c
lib/libutils/isoc/include/malloc.h

Adds the following statistics to the heap allocator and export then via
the static TA `core/arch/arm/sta/stats.c` (all of them can be reset):
- num_alloc_fail: number of calls to malloc()/calloc()/realloc() that
returned NULL
- biggest_alloc_fail: the size in bytes of the largest allocation
request that resulted in a failure
- biggest_alloc_fail_used: the number of bytes that were allocated at
that time
Depends on CFG_WITH_STATS=y.

[RFC] core: add heap allocation failure statistics

---

core/arch/arm/plat-hikey/platform_config.h

The current heap size is not enough to run `xtest` when both the
default secure storage (CFG_REE_FS) and the newly added SQLite FS
(CFG_SQL_FS) are enabled. Let's increase it a bit.

hikey: increase heap size from 24 KiB to 32 KiB

---

core/arch/arm/kernel/generic_boot.c

Adds a "no-map" property to the optee@xxx node. Before this patch the node
looked like:
optee@78000000 {
reg = <0x78000000 0x800000>;
};
With this patch it becomes:
optee@78000000 {
reg = <0x78000000 0x800000>;
no-map;
};
This makes it clear to the Linux kernel that it must leave it to the
OP-TEE driver to map the reserved memory.
Fixes https://github.com/OP-TEE/optee_os/issues/1034

core: arm: add no-map property to res mem

---

.travis.yml

Address a common situation when a pull request is reviewed. Suppose a
PR contains one commit, which causes checkpatch warnings. The author
pushes a new commit to fix the warnings. Travis will still complain
because it checks every commit in the PR, and the author has no way to
make sure the fix is actually correct.
To alleviate this problem, add a call to checkpatch that will process
the whole diff added by the PR branch to the target branch (i.e., git
diff HEAD^1...HEAD^2). In the above example, the Travis status will
still be fail until all commits actually comply with the rules, but the
PR author can check that his/her contribution is OK as a whole.

travis: also check whole diff when pull request has several commits

---

core/tee/tee_ree_fs.c
core/tee/tee_sql_fs.c

Bugfix for reading beyond end of a persistent object when the file
position is larger the the size of the data stream. Applies to both REE
FS and SQL FS.

core: bugfix reading beyond end of file

---

core/include/tee/tee_svc_storage.h
core/tee/tee_svc_storage.c
lib/libutee/include/utee_syscalls.h

Fixes problem with sign extension (or lack thereof) for the syscall
storage_obj_seek. Updates the general rules of arguments for syscalls to
use signed 32-bit parameters when a signed parameter is needed.
Suggested-by: Jerome Forissier <jerome.forissier@linaro.org>
Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (QEMU and FVP)

syscall storage_obj_seek: fix sign extension

---

.travis.yml
MAINTAINERS.md
README.md
core/arch/arm/arm.mk
core/arch/arm/include/kernel/generic_boot.h
core/arch/arm/include/sm/optee_smc.h
core/arch/arm/kernel/generic_boot.c
core/arch/arm/kernel/generic_entry_a32.S
core/arch/arm/plat-imx/a9_plat_init.S
core/arch/arm/plat-imx/conf.mk
core/arch/arm/plat-imx/main.c
core/arch/arm/plat-imx/platform_config.h
core/arch/arm/plat-imx/sub.mk
mk/config.mk

Add changes to work with VxWorks as Rich OS:
1. added VxWorks specific SMC requests definition. OP-TEE is to be used as both a TEE and a Monitor for VxWorks, so additional SMC requests must be handled by OP-TEE.
2. added a new the hand-off protocol between loader and OP-TEE, that is, no hand-off at all. OP-TEE will not require loader to pass any arguments, instead, things such as paged data, NS entry and DT address are from configuration parameters. This hand-off is to be used by VxWorks.
3. Added the i.MX6 Sabre Lite board support.

init support for VxWorks-7 on Freescale i.MX6

---

scripts/gen_hashed_bin.py
scripts/render_font.py
scripts/tee_bin_parser.py

During my vacation, I'm reinstalling one of my computers and plan to use something else than Ubuntu based stuff (Arch Linux) and I encountered a couple of problems when trying to compile and test OP-TEE. This patch set and the the one in https://github.com/OP-TEE/build/pull/73 makes everything run fine on Arch Linux.
The "parser" script is a bit crude, but we can easily expand it later on (like non hardcoded paths etc).

Arch linux

---

core/arch/arm/plat-hikey/conf.mk

Use the proper CPU architecture when building 32-bit binaries for HiKey.
Note: this triggers a compiler warning:
CC      out/arm-plat-hikey/core/tee/tee_svc_cryp.o
{standard input}: Assembler messages:
{standard input}:632: Warning: IT blocks containing 32-bit Thumb instructions are deprecated in ARMv8
(compiler is gcc-linaro-arm-linux-gnueabihf-4.9-2014.09_linux).
This seems to be harmless and is registered as a compiler bug [1].
[1] https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67591

hikey: 32-bit: use -mcpu=cortex-a53 instead of cortex-a15

---

core/arch/arm/include/kernel/user_ta.h
core/arch/arm/include/mm/pgt_cache.h
core/arch/arm/include/mm/tee_pager.h
core/arch/arm/kernel/kern.ld.S
core/arch/arm/kernel/user_ta.c
core/arch/arm/mm/core_mmu.c
core/arch/arm/mm/core_mmu_lpae.c
core/arch/arm/mm/core_mmu_v7.c
core/arch/arm/mm/pgt_cache.c
core/arch/arm/mm/tee_mmu.c
core/arch/arm/mm/tee_pager.c
core/core.mk
core/include/mm/tee_mmu_types.h
core/kernel/tee_ta_manager.c
mk/config.mk

Adds support for paged user TAs

Paged user TAs

---

README.md

- Add qemu_v8_stable.xml, hikey_debian_stable.xml.
- Remove "experimental" part for HiKey running Debian, since we are now
pointing to the official RPB Linux kernel branch.

doc: Update repo xml matrix

---

core/arch/arm/plat-mediatek/platform_config.h

Running MTK8173 panics in tee_entry_std just after mapping the
arguments. The reason for this is because only 1MB out of 2MB has been
mapped and therefore leaving a gap between MEM_AREA_NSEC_SHM and
MEM_AREA_TA_RAM. I.e.,
DEBUG:   [0x0] TEE-CORE:init_mem_map:398: type va 4
0xbc000000..0xbc0fffff pa 0xbdf00000..0xbdffffff size 0x100000
DEBUG:   [0x0] TEE-CORE:init_mem_map:398: type va 3
0xbc200000..0xbdffffff pa 0xbe200000..0xbfffffff size 0x1e00000

mtk: map entire MEM_AREA_NSEC_SHM area

---

core/arch/arm/mm/tee_mmu.c

This change fixes the TA buffer parameter mapping that gets clobbered
when a parameter of lower index relates to nonsecure memory while
a parameter of higher index relates to a secure memory area.

core: fix TA memory reference parameters mapping

---

.travis.yml

The checkpatch.pl script uses a file called const_structs.checkpatch to
check for correct usage of some kernel structures. We don't want those
checks, which are linux-specific, but we still need the file to be
present otherwise the tool will log a warning message [1].
[1] https://travis-ci.org/OP-TEE/optee_os/builds/167271505#L1720

travis: prevent warning from code checking tool

---

mk/compile.mk
mk/subdir.mk

Because a library may be built several times (for example, libutils.a
is built differently for kernel and user mode), the variables that hold
the library-specific flags have to be cleared when done.
These variables are: cflags-lib$(libname) and cppflags-lib$(libname).
They may be set manually set in the makefiles (sub.mk), and they also
contain the value of $(cflags-lib-y) or $(cppflags-lib-y) respectively.
Fixes: 3d34e125a253 ("Add support for $(cflags-lib-y)")

Fix per-library flags (cflags-lib-y / cppflags-lib-y) with multiple builds

---

core/arch/arm/plat-imx/a9_plat_init.S
core/arch/arm/plat-stm/tz_a9init.S

Secure Configuration Register shall be initialized for all cpu cores.

plat-stm/plat-imx: fix SCR initialization

---

.travis.yml

Workaround a checkpatch bug [1] by creating a non-empty file
const_structs.checkpatch. By adding the name of a struct that cannot
appear in valid code, we avoid the false warning (which occurs only
no name is given) and this can't produce any unwanted side-effect.
[1] https://www.spinics.net/lists/kernel/threads.html#2364905

travis: workaround false positive in code checking tool

---

documentation/rpi3.md

I've revised and updated my NFS instructions that I started writing during the summer. This should all be up-to-date and since David will talk about this at ARM TechCon next week, I think it's about time for a pull request now.
The u-boot.env modifications are a bit awkward. I have started another [patch](https://github.com/jbech-linaro/build/commit/c5c1c8e18020e4f869a01770238e24c2b3bb2db6) that will make that easier to deal with it in the future. But for now I think this works.

doc: Add NFS boot and TFTP instructions for RPi3

---

ta/mk/ta_dev_kit.mk

This provides an easy way to append some flags to the TA build, for
instance: `make CFLAGS_ta_arm64=-O0' to disable optimizations in 64-bit
TAs.

ta_dev_kit.mk: get optional flags from $(CFLAGS_$(sm))/$(CPPFLAGS_$(sm))

---

core/tee/tee_svc.c

Fixes the debug output of Trusted Applications. For example:
- Previous output:
ERROR:   TEE-CORE: DEBUG:   USER-TA:TA_CreateEntryPoint:41: Blah
- New output:
DEBUG:   USER-TA:TA_CreateEntryPoint:41: Blah

syscall_log: do not prepend TEE core prefix

---

core/arch/arm/mm/tee_mmu.c
core/include/mm/tee_mmu.h

This change limits ta_private_vmem_end to TA segments defined when
TA is loaded.
Currently 'ta_private_vmem_end' only used to prevent a TA from exposing
its code/data/stack memory to another TA it invokes. A shared memory
buffer passed as TA invocation parameter is obviously not inside the TA
private memory an can be exposed to another TA.

core: TA private memory does not include the memref parameters

---

mk/checkconf.mk

Fixes issues with the check-conf-h and check-conf-mk functions, which
would error out or generate incorrect output on strings containing spaces
and/or double quotes.
The single quote character is used in the shell commands that builds
the list of values, instead of the double quote, so that there is no
conflict with double quotes appearing in the variables themselves. As a
consequence, single quotes cannot appear anywhere in the output string.
So remove the comments that contained quotes, and which were not that
useful anyway.
Test case:
$ grep CFG_TEST core/arch/arm/plat-vexpress/conf.mk
CFG_TEST1 ?= "test string"
CFG_TEST2 ?= test string
CFG_TEST3 ?= "test"
CFG_TEST4 ?= test
$ make -s
$ grep CFG_TEST out/arm-plat-vexpress/conf.mk
CFG_TEST1="test string"
CFG_TEST2=test string …

mk/checkconf.mk: allow spaces and double quotes in CFG_ config variables

---

README.md

Add info about using VirtFS folder sharing feature in QEMU/QEMUv8
Relates to: https://github.com/OP-TEE/build/pull/79
Signed-off-by: Igor Opaniuk igor.opaniuk@linaro.org

doc: update README.md, add info about VirtFS

---

core/arch/arm/include/mm/core_mmu.h

Comment mentions MEM_AREA_NS_SHM which does not exists. Instead
there are MEM_AREA_NSEC_SHM.
Also there was different order of memory areas in comment and
in enum definition.

core_mmu.h: align comments with code

---

core/arch/arm/include/kernel/static_ta.h
core/arch/arm/kernel/static_ta.c
core/arch/arm/mm/tee_mmu.c
core/arch/arm/sta/se_api_self_tests.c
core/arch/arm/sta/sta_self_tests.c
core/arch/arm/sta/stats.c
core/arch/arm/sta/tee_fs_key_manager_tests.c
core/arch/arm/tee/entry_std.c
core/include/kernel/tee_dispatch.h
core/include/kernel/tee_ta_manager.h
core/kernel/tee_dispatch.c
core/tee/tee_svc.c
lib/libutee/include/tee_api.h
lib/libutee/include/tee_ta_api.h
lib/libutee/include/user_ta_header.h
lib/libutee/tee_api.c

Perform cleanup for magic "4" constant that represents amount of tee
params

core/libutee: perform cleanup for magic "4"

---

core/include/tee/tee_fs.h
core/tee/tee_ree_fs.c
core/tee/tee_rpmb_fs.c
core/tee/tee_sql_fs.c
core/tee/tee_svc_storage.c

As the FOP create always is called with the overwrite flag it can be
simplified. This makes the implementation of create much easier.

core: FS: simplify FOP create

---

core/arch/arm/mm/core_mmu.c

fix debug trace when static mapping tables are setup.
this should fix https://github.com/OP-TEE/optee_os/issues/1178

core: fix mapping init deubg trace

---

core/arch/arm/kernel/user_ta.c
core/arch/arm/mm/tee_mmu.c
core/arch/arm/tee/svc_cache.c
lib/libutee/include/tee_api_defines_extensions.h
lib/libutee/include/tee_internal_api_extensions.h

New TEE Internal API extension: on TEE_CheckMemoryAccesRights(). 
[description here](https://docs.google.com/document/d/1QaCt3GgWwsQBTZ5xSHkYoavipgNC27cCkjiOrnOFE9s).
Fix on TA cache API.

MemoryAccessRight and Cache maintenance for SDP (SWG-186)

---

core/arch/arm/kernel/thread.c

stack_tmp_offset is required by secondary boot cores before
pager is initialized.
Fixes: e56a56428def ("core: sm: use stack_tmp for sm_from_nsec")

core: fix stack setup at secondary core entry

---

Makefile

To avoid issues [1] with some projects that call us from a top-level
Makefile that has an 'export' directive or a '.EXPORT_ALL_VARIABLES:'
target, we prevent $(MAKEFILE_LIST) from being exported, thereby
greatly reducing the size of the environment.
[1] Typically, the build succeeds the first time (because there is no
.cmd/.d files yet), then the second invocation of make fails with:
make[3]: execvp: /bin/bash: Argument list too long

Makefile: unexport MAKEFILE_LIST to reduce the size of the environment

---

core/arch/arm/include/arm32_macros.S
core/arch/arm/include/arm32_macros_cortex_a9.S
core/arch/arm/plat-imx/a9_plat_init.S
core/arch/arm/plat-stm/tz_a9init.S

Add more cp15 macros.
These are useful when do suspend/resume operations in OP-TEE.

core: arm: add more cp15 macros

---

core/include/tee/tee_fs_key_manager.h
core/tee/tee_ree_fs.c

In struct tee_fs_file_info, the member length's origin type is size_t,
when NS user is 64 bits, and secure kernel is 32 bits, the type size_t
will have different width, which will cause xtest 20022 case fail.
This commit change the member length's type from size_t to uint64_t,
which can keep a fixed width.
Relates to:
#1185 
Signed-off-by: Guanchao Liang <liang.guanchao@linaro.org>

secure storage: change struct tee_fs_file_info member type

---

core/arch/arm/include/kernel/spinlock.h
core/arch/arm/include/kernel/thread.h
core/arch/arm/kernel/mutex.c
core/arch/arm/kernel/proc_a32.S
core/arch/arm/kernel/spin_lock_a32.S
core/arch/arm/kernel/spin_lock_a64.S
core/arch/arm/kernel/spin_lock_debug.c
core/arch/arm/kernel/sub.mk
core/arch/arm/kernel/tee_l2cc_mutex.c
core/arch/arm/kernel/thread.c
core/arch/arm/kernel/thread_private.h
core/arch/arm/kernel/wait_queue.c
core/arch/arm/mm/core_mmu.c
core/arch/arm/mm/tee_pager.c
core/include/keep.h

This PR replaces to https://github.com/OP-TEE/optee_os/pull/1206. All review comments have hopefully been addressed ; commits have been re-organized and rebased on top of master.

Adding assertions to spinlocks & mutexes (2)

---

core/arch/arm/kernel/user_ta.c

There are two stages for ta memory access permissions:
1. TA is in loading process, PL1(kernel) has got the RW permission only.
2. TA is loaded, PL0(user ta) has got the required permissions.

mm: use more strict user ta memory access control

---

core/arch/arm/kernel/user_ta.c
core/arch/arm/tee/entry_std.c
core/include/optee_msg.h
core/include/tee/uuid.h
core/tee/sub.mk
core/tee/uuid.c
lib/libutils/ext/snprintk.c

Fixes https://github.com/OP-TEE/optee_os/issues/857 and https://github.com/OP-TEE/optee_os/issues/858
Depends on https://github.com/OP-TEE/optee_client/pull/71 and https://github.com/OP-TEE/optee_test/pull/150

Uuid fixes

---

documentation/rpi3.md

I've finally been able to run JTAG successfully on my RPi3. To make it easy to replicate I've documented all steps in the `rpi3.md` file.

RPi3 documentation, adding JTAG instructions and a general cleanup

---

core/arch/arm/mm/core_mmu.c
core/arch/arm/mm/core_mmu_lpae.c

Fixes problem in defined memory regions where physical address isn't
pgdir aligned.
Fixes: 0f8333b888f1 ("plat-vexpress/qemu: correct DRAM layout")
Fixes LPAE breakage introduced in https://github.com/OP-TEE/optee_os/pull/1236

core: lpae: deal with unaligned regions

---

core/tee/tee_sql_fs.c

If the data size is not increased as a result of the write operation,
meta.length must not be changed.
Fixes: https://github.com/OP-TEE/optee_os/issues/1268

core: sql_fs_write(): update meta.length only if length has changed

---

Makefile
core/arch/arm/kernel/link.mk
core/sub.mk
lib/libutee/tui/sub.mk
mk/cleandirs.mk
ta/mk/ta_dev_kit.mk
ta/ta.mk

"make clean" would leave behind some files and many directories. Fix
this by correctly tracking the files and directories created under $(O)
during the build process:
- Fix incorrect file names in $(cleanfiles) and add a few missing
ones.
- Introduce $(cleandirs) which is updated whenever a sub-directory is
entered (and in a couple of special cases such as the generation of
conf.h and conf.mk)
The clean target removes the files, then all the directories in depth-
first order. $(O) is also removed, if found to be empty.
Note that a more straightforward approach was discussed in [1]: use
"rm -rf $(O)/some_dir" and get rid of the whole file and directory
tracking via $(cleanfiles) and $(cleandirs). Altough it was agreed it
would be safe, doing so would necessarily break the backward …

Make sure "make clean" removes everything "make" has created under $(O)

---

ta/ta.mk

When a target starts with './', $@ does not. Therefore we must not use
$@ to access a variable if its name is created from $(out-dir) which
might start with './'. Fixes the following issue:
$ make O=./build
<snip>
GEN     build/export-ta_arm32/mk/conf.mk
/bin/bash: -c: line 0: syntax error near unexpected token `)'
/bin/bash: -c: line 0: `() >> build/export-ta_arm32/mk/conf.mk'
ta/ta.mk:120: recipe for target 'build/export-ta_arm32/mk/conf.mk' failed
make: *** [build/export-ta_arm32/mk/conf.mk] Error 1

Fix build error when $(O) starts with ./

---

lib/libutee/tee_api_operations.c

Makes the ROUNDUP() call in the "feeding from src" case consistent with
the "feeding from buffer" case a few lines earlier. Without this fix,
AES CTR encryption or decryption could fail because update would feed
blocks too soon, leaving less than two blocks in the internal buffer
thus causing utee_cipher_final() (called from TEE_CipherDoFinal()) to
fail and panic the TA.
Fixes: https://github.com/OP-TEE/optee_os/issues/1203

libutee: fix off-by-one error in tee_buffer_update()

---

core/tee/tee_rpmb_fs.c

Don't call thread_rpc_free_payload() unless thread_rpc_alloc_payload()
was successful, which is when the physical address is non-zero.
Fixes: https://github.com/OP-TEE/optee_os/issues/1319

RPMB: fix tee_rpmb_free()

---

lib/libutee/tee_api_operations.c

Ad-hoc fix for regressions introduced by [1].
Tested on HiKey using latest optee_test including GlobalPlatform tests
(32/64-bit TEE core, 32/64-bit libutee, with/without ARMv8 CE
acceleration).
Fixes: b1ecda78bab4 ("libutee: fix off-by-one error in tee_buffer_update()") [1]
Fixes: https://github.com/OP-TEE/optee_os/issues/1305

libutee: AES CTS fix

---

lib/libutee/tee_api.c
lib/libutee/tee_api_objects.c
lib/libutee/tee_api_operations.c

On many occasions, libutee calls TEE_Panic(0) to kill a TA. When an
error status from a lower layer is available, it is much more helpful
to pass it instead of zero, because the code is shown in the debug
traces.

libutee: preserve error code when calling TEE_Panic()

---

lib/libutee/include/tee_api.h
lib/libutee/include/utee_syscalls.h
lib/libutee/tee_api.c
lib/libutee/tee_api_arith.c
lib/libutee/tee_api_objects.c
lib/libutee/tee_api_operations.c
lib/libutee/tee_api_property.c

As per the GlobalPlatform Internal Core API Specification v1.1,
section 3.4 Parameter Annotations: "[...] the [in], [inbuf],
[instring], [instringopt], and [ctx] annotations can make use of the
const C keyword [...] the C header file of a compliant Implementation
SHOULD use the const keyword when these annotations appear."

libutee: API: add 'const' qualifiers

---

core/tee/tee_svc_storage.c

According to the GP spec, TEE_ResetPersistentObjectEnumerator() "resets
an object enumerator handle to its initial state after allocation".
Therefore, syscall_storage_reset_enum() should set e->fops = NULL.
This fixes a regression introduced when the FOP interface was reworked.
I'm not simply reverting the return code from TEE_ERROR_GENERIC back to
TEE_ERROR_ITEM_NOT_FOUND, because the new code makes sense and it is
more sane to properly reset the state of the enumerator.
Consequently, tee_svc_close_enum() is updated to accept e->fops == NULL
which is valid when the enum has just been allocated or reset but not
started. We should not return an error status in this case.
Tested on HiKey using xtest with GP tests (all 3 filesystems: REE, SQL,
RPMB).
Fixes: b86c18ecc7d3 ("core: RPMB FS: …

core: RPMB FS: nullify fops when resetting an enumerator

---

core/arch/arm/kernel/link.mk

If tee-init_load_addr is higher than 0xffffffff. building failed with:
```bash
Traceback (most recent call last):
File "./scripts/gen_hashed_bin.py", line 148, in <module>
main()
File "./scripts/gen_hashed_bin.py", line 132, in main
write_header(outf, 0, args, 0)
File "./scripts/gen_hashed_bin.py", line 44, in write_header
args.init_mem_usage, paged_size))
struct.error: 'I' format requires 0 <= number <= 4294967295
make: *** [out/arm-plat-vexpress/core/tee.bin] Error 1
make: Leaving directory `/home/zh/work/github/optee_os'
```
Signed-off-by: Zhizhou Zhang <zhizhouzhang@asrmicro.com>

fix build issue

---

Makefile
mk/cleandirs.mk
ta/mk/ta_dev_kit.mk

"make clean" may report errors when trying to clean with different
configuration values than the ones used during the build. For instance:
$ make -s CFG_RPMB_FS=y
$ make clean
CLEAN   out/arm-plat-vexpress
rmdir: failed to remove 'out/arm-plat-vexpress/core/tee': Directory not empty
rmdir: failed to remove 'out/arm-plat-vexpress/core': Directory not empty
rmdir: failed to remove 'out/arm-plat-vexpress': Directory not empty
Makefile:88: recipe for target 'clean' failed
make: *** [clean] Error 1
The clean command should not fail, since the build tree was properly
cleaned for the requested configuration. Fix this by using
'rmdir --ignore-fail-on-non-empty'.

make clean: don't fail on non-empty directory

---

core/arch/arm/arm.mk
core/arch/arm/kernel/generic_entry_a64.S
core/arch/arm/mm/core_mmu.c
core/arch/arm/mm/core_mmu_lpae.c

There is still a problem I didn't fix here. In `find_session`, `id` is `uint32_t`, but it's compared to a point. I'm not sure how to fix it. I just cut the high part of `s`. as shown below:
```
diff --git a/core/kernel/tee_ta_manager.c b/core/kernel/tee_ta_manager.c
index c0c4545..1faad7b 100644
--- a/core/kernel/tee_ta_manager.c
+++ b/core/kernel/tee_ta_manager.c
@@ -176,7 +176,7 @@ static struct tee_ta_session *find_session(uint32_t id,
struct tee_ta_session *s;
TAILQ_FOREACH(s, open_sessions, link) {
-               if ((vaddr_t)s == id)
+               if ((unsigned)(vaddr_t)s == id)
return s;
}
return NULL;
```

fixes for extending va to 64-bit

---

core/arch/arm/include/kernel/pseudo_ta.h
core/arch/arm/kernel/pseudo_ta.c
core/arch/arm/pta/gprof.c
core/arch/arm/pta/interrupt_tests.c
core/arch/arm/pta/pta_self_tests.c
core/arch/arm/pta/se_api_self_tests.c
core/arch/arm/pta/stats.c
core/arch/arm/pta/tee_fs_key_manager_tests.c

As part of the Secure Data Path, pseudo TAs may need to access SDP memory buffers using the memory reference provided as invocation parameters by their client.
As most pseudo TAs are likely to be not much interested with the SDP feature, these change aims at allowing pseudo TA to declare to OP-TEE core whether or not they do handle SDP memory references (and the several related constraints). Only such TAs will be able to be invoked with SDP memref parameters.
This PR does not talk about SDP. It proposes pseduo TA features that will be required for the SDP support intergration (https://github.com/OP-TEE/optee_os/pull/1322).

Allow Pseudo TAs to define their TA property flags

---

core/arch/arm/arm.mk
core/arch/arm/include/kernel/time_source.h
core/arch/arm/kernel/tee_time_arm_cntpct.c
core/arch/arm/kernel/thread.c
core/arch/arm/tee/entry_std.c
core/include/tee/tee_cryp_utl.h
core/lib/libtomcrypt/src/tee_ltc_provider.c
core/tee/tee_cryp_utl.c

At the moment if no HWRNG support as on Hikey, a deterministic RC4 PRNG is used.  That's not nice for the reasons listed in the first patch.
These two patches add an internal api that indicates it is a good time to harvest jitter from a platform time source.  By default it does nothing with an empty weak implementation.
An implementation for Hikey is also added using the ARMv8 TSC.
The api to harvest entropy is added to the PRNG init, where it gets 16 bits in the hikey implementation, and at the start of RPC calls, where it harvests 2 bits of jitter.

platform jitter entropy

---

core/arch/arm/kernel/thread.c
core/include/tee/tee_cryp_utl.h
core/lib/libtomcrypt/src/tee_ltc_provider.c
core/tee/tee_cryp_utl.c

The commit referenced below extends entropy gathering to two locations
where it is unfortunately not OK to invoke Normal World through RPC:
1. tee_ltc_prng_init(), because at this point the RPC subsystem has not
yet been initialized,
2. rpc_cmd_nolock(), because doing so would cause recursion and would
be inefficient (doubling the number of RPC calls).
The problem is: if CFG_SECURE_TIME_SOURCE_REE=y and if the platform
does not override plat_prng_add_jitter_entropy(), the function will end
up calling the RPC service where it's not permitted and the TEE will
crash.
This commit introduces plat_prng_add_jitter_entropy_norpc() and
provides a default implementation which does nothing if the time source
is the REE, thus fixing the issue while still allowing platform code to
implement a specific …

core: prng: Don't try to read REE time when it's not possible

---

lib/libutee/tee_user_mem.c

When CFG_TEE_CORE_USER_MEM_DEBUG=1 (which is the default, enables
additional checks in tee_user_mem.c and also enables traces) and
CFG_TEE_TA_LOG_LEVEL=3 (debug), libutee logs messages for each and
every allocation and deallocation, as follows:
DEBUG:   USER-TA: tee_user_mem_alloc:343: Allocate: link:[0x1211a0], buf:[0x1211b0:12]
DEBUG:   USER-TA: tee_user_mem_free:442: Free: link:[0x1211a0], buf:[0x1211b0:12]
...
That's annoying and pretty much useless so let's just remove them.
Higher severity messages, which are printed if an inconsistency is
detected, are preserved.

libutee: Remove debug traces in tee_user_mem_alloc()/tee_user_mem_free()

---

core/arch/arm/kernel/tee_time_arm_cntpct.c

Changes the DMSG() logging to FMSG() to avoid flooding the logs when
debug logs are enabled.

core: plat_prng_add_jitter_entropy() logging

---

core/tee/fs_htree.c

Fixes problem with memory leakage in tee_fs_htree_sync_to_storage()
when the hash tree doesn't need to be synced to storage.

core: FS: fix htree memory leakage

---

core/arch/arm/include/kernel/mutex.h
core/arch/arm/include/kernel/wait_queue.h
core/arch/arm/kernel/mutex.c
core/arch/arm/kernel/thread.c
core/arch/arm/kernel/wait_queue.c
core/include/tee/tee_cryp_utl.h

Obsoletes https://github.com/OP-TEE/optee_os/pull/1385

core: prng: Don't lock a mutex from rpc_cmd_nolock()

---

core/arch/arm/tee/entry_fast.c

core: arm: ignore ~OPTEE_SMC_NSEC_CAP_UNIPROCESSOR

---

core/arch/arm/kernel/user_ta.c
lib/libutee/include/user_ta_header.h

Rename TA_FLAG_UNSAFE_NW_PARAMS into TA_FLAG_SECURE_DATA_PATH.
This change does NOT able secure data path support in OP-TEE. It is
rather a pre-requisite for later changes in OP-TEE regarding SDP
support.
This change expects https://github.com/OP-TEE/optee_test/pull/181 is previous merged.
This PR is extracted from https://github.com/OP-TEE/optee_os/pull/1322 and supersedes change proposal from https://github.com/OP-TEE/optee_os/pull/1322/commits/00317254274a5b6b24403c57496b9492e90de903 . It has already been reviewed in this scope.

core: introduce TA_FLAG_SECURE_DATA_PATH

---

core/arch/arm/plat-ls/plat_init.S
core/arch/arm/plat-stm/tz_a9init.S
core/arch/arm/plat-zynq7k/plat_init.S

Before this change, a reserved bit was set in the PCR instead of
enabling the clock gating support, as configured in other supported
Cortex-A9 platforms.
Issue found thanks to reviews for https://github.com/OP-TEE/optee_os/pull/1394 (hence the proposed reported-by tag)

plat-zynq7k: fix cpu PCR/NASCR init (and few other assembly source files)

---

core/tee/tee_svc_storage.c

Removes the mutex that's supposed to protect directory operations in
secure storage. The mutex is redundant as each FS implementation has
its own internal mutex for all operations.

core: FS: remove ta_dir_mutex

---

core/include/io.h

Removes the now unused IO() macro.

core: remove IO() macro

---

core/tee/tee_svc_storage.c

An object enumerator that has just been allocated or reset has its fops
field set to NULL. So, syscall_storage_reset_enum() must take care of
this.
Fixes: https://github.com/OP-TEE/optee_os/issues/1417

core: syscall_storage_reset_enum() must check e->fops before using it

---

core/arch/arm/kernel/elf_common.h
core/arch/arm/kernel/elf_load.c

If a 64-bit TA contains relocations of type R_AARCH64_ABS64, OP-TEE
refuses to load it and logs the following error:
ERROR:   TEE-CORE: Unknown relocation type 257
This relocation type does not seem to happen in our test applications,
but someone has experienced the issue after linking a TA against a
third-party static library [1]. I could reporoduce the issue by adding
the following assembly code to a TA:
```
.pushsection .rodata
.global _reloc__text_start
_reloc__text_start:
.quad __text_start
.popsection
```
(this adds a 64-bit value into the .rodata section of the TA, exported
as a global symbol called _reloc__text_start, its value is set to the
__text_start address).
This commit adds the necessary code to support R_AARCH64_ABS64.
[1] https://github.com/OP-TEE/optee_os/issues/1399 …

core: arm64: support relocation type R_AARCH64_ABS64 (257)

---

core/arch/arm/kernel/trace_ext.c

Use spinlock to make the trace output atomic.
On SMP cores, different cores may puts out log
to uart. If there is no lock, the log will be a mess.
Signed-off-by: Peng Fan `<peng.fan@nxp.com>`

core: arm: trace: make the trace output atomic

---

.travis.yml
core/arch/arm/plat-imx/conf.mk
core/arch/arm/plat-imx/main.c
core/arch/arm/plat-imx/platform_config.h
core/arch/arm/plat-imx/sub.mk

This patch adds support for the Dual Lite version of the i.MX6 Sabre SD reference board.
In addition to add support for yet another board, it adds support for the Solo/DualLite family of NXP i.MX6 SoCs.
Signed-off-by: Mathieu Briand <mbriand@witekio.com>

core: arm: add support for i.MX6 Dual Lite SabreSD

---

core/arch/arm/plat-imx/a9_plat_init.S

According to Cortex A9 TRM, bit[10:8] of PCR is max_clk_latency:
Samples the value present on the MAXCLKLATENCY pins on exit from reset.
This value reflects an implementation-specific parameter.
ARM strongly recommends that the software does not modify it.
So change the value to 0 is not wise, correct it.
Signed-off-by: `Peng Fan <peng.fan@nxp.com>`

core: arm: imx: correct PCR settings

---

core/drivers/cdns_uart.c
core/drivers/hi16xx_uart.c
core/drivers/imx_uart.c
core/drivers/ns16550.c
core/drivers/pl011.c
core/drivers/pl050.c
core/drivers/scif.c
core/drivers/serial8250_uart.c
core/drivers/sprd_uart.c
core/drivers/sunxi_uart.c

Console operations structures must be kept in the unpaged sections
when pager is enable.
This PR fixes the OP-TEE when pager is enable.

core: fix console drivers against pager

---

core/arch/arm/mm/core_mmu.c

This change fixes a typo in the core mapping setup when pager is enabled.
Looking back in OP-TEE history show this typo has been there since quite
a while.
Various build test showed the previous buggy implementation gave valid
settings. Yet, it looks far better once fixed.

core: fix typo in pager mapping setup

---

core/arch/arm/pta/pta_invoke_tests.c
core/arch/arm/pta/sub.mk

Fixes: 040bc0f04138 ("core: add test case for hash-tree")

core: fix compile error with CFG_WITH_USER_TA=n

---

core/arch/arm/mm/core_mmu.c
core/drivers/scif.c
core/include/drivers/scif.h

There are two patches that together fix https://github.com/OP-TEE/optee_os/issues/1460
One of them is RCAR-specific. Another one is more general, as it applicable to all platforms.

Fix OPTEE startup on RCAR H3 platform.

---

core/arch/arm/kernel/thread.c

'stack_abt' is too small when pager is enabled and needs to be increased.
'stack_abt' is used for aborts (prefetch/data/undef) and native/foreign
interruptions exceptions.
Tests on ARMv7 targets show that between 1000 and 1500 bytes of these
stacks are consumed at runtime. Tests considered configurations with
trace/debug/LPAE/VFP enabled and disabled. Tests were based on running
OP-TEE with the xtest non-regression suite.
Tested qemu_virt and b2260.

core: increase size of the exception stack in AArch32 mode

---

CHANGELOG.md
mk/config.mk

This replaces #1426 since I cannot push to Jerome's branch.
Tested-by: Peng Fan <peng.fan@nxp.com> (imx6ulevk)
Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (Juno)
Tested-by: Etienne Carriere <etienne.carriere@linaro.org> (b2260, GP)
Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (D02)
Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (QEMU v7)
Tested-by: Joakim Bech <joakim.bech@linaro.org> (MTK8173)
Tested-by: Joakim Bech <joakim.bech@linaro.org> (QEMU v8)
Tested-by: Sumit Garg <sumit.garg@nxp.com> (ls1021atwr - Single core)
Tested-by: Sören Brinkmann <soren.brinkmann@xilinx.com> (zynqmp)
Tested-by: Volodymyr Babchuk <vlad.babchuk@gmail.com> (RCAR …

Update CHANGELOG.md for 2.4.0 replaces #1426

---

core/arch/arm/include/kernel/spinlock.h
core/arch/arm/kernel/wait_queue.c
core/arch/arm/mm/tee_mm.c
core/arch/arm/mm/tee_pager.c
core/include/mm/tee_mm.h
lib/libutils/isoc/bget_malloc.c

There are two patches in this PR:
- First one just eases up spinlock usage.
- Second one fixes race condition in tee_mm.c
I have spotted this race condition during shmem mobj implementation. 
At first I wanted to add `tee_mm_lock()` and `tee_mm_unlock()` pair of functions. But I don't think this is best approach, because we already have (and there will be more) such pairs in different modules. 
So I decided to implement generic functions.

Refactor spinlock && exception masking usage, add locking to tee_mm.c

---

core/arch/arm/include/mm/core_mmu.h
core/arch/arm/mm/core_mmu.c

Improve the legibility of the memory manager debug traces by
converting the memory types to strings before printing them in
dump_mmap_table() and add_phys_mem().

core: mm: print memory type name instead of numerical value

---

core/arch/arm/include/arm32.h
core/arch/arm/include/arm64.h
core/arch/arm/include/kernel/thread.h
core/arch/arm/kernel/thread_a32.S
core/arch/arm/kernel/thread_a64.S
core/drivers/gic.c
documentation/interrupt_handling.md

These two patches enabled the ARM GICv3 support.

Support ARM GICv3 mode

---

.travis.yml
core/arch/arm/plat-ti/platform_config.h

Fix "#elif with no expression" error when building with `ti-am57xx` flavor

am57xx: fix build

---

core/arch/arm/plat-imx/a9_plat_init.S

plat-imx: use the mov_imm macro instead of movw/movt

---

core/tee/tee_svc_cryp.c

syscall_asymm_verify() (and therefore TEE_AsymmetricVerifyDigest())
incorrectly assumes that the hash algorithm is SHA1 when the main
algorithm is ECDSA, and will panic the TA if the hash size is not set
accordingly. This behavior does not comply with the TEE Internal Core
API v1.1, which states:
"Where a hash algorithm is specified in the algorithm, digestLen SHALL
be equal to the digest length of this hash algorithm".
For TEE_ALG_ECDSA_P192, TEE_ALG_ECDSA_P224, TEE_ALG_ECDSA_P256,
TEE_ALG_ECDSA_P384 and TEE_ALG_ECDSA_P521, no hash algorithm is
specified, and so we must not restrict the hash size to any specific
value.

crypto: don't check hash size when the main algorithm is ECDSA

---

core/arch/arm/mm/core_mmu.c

2 fixes related to core static mapping:
- a typo in the computation of its end virtual address
- until https://github.com/OP-TEE/optee_os/pull/1459 is merged (not ready to be), non-LPAE static mapping cannot reuse level2 mmu tables when mapping memory.

fix core static mapping

---

core/arch/arm/include/kernel/unwind.h

Fix build issue with CFG_TEE_CORE_DEBUG=y and CFG_TEE_CORE_LOG_LEVEL=0.

core: fix build with DEBUG=y and LOG_LEVEL=0

---

core/arch/arm/include/mm/core_mmu.h

teecore_memtype_name() does not handle MEM_AREA_SHM_VASPACE. Add it.

core: mm: add missing entry in teecore_memtype_name()

---

core/arch/arm/include/kernel/user_ta.h
core/arch/arm/kernel/elf_load.c
core/arch/arm/kernel/elf_load.h
core/arch/arm/kernel/ree_fs_ta.c
core/arch/arm/kernel/sub.mk
core/arch/arm/kernel/user_ta.c
core/sub.mk
mk/config.mk

Some use cases may require custom load and verification methods for
user-mode Trusted Applications. Introduce struct user_ta_store_ops with
open(), get_size(), read() and close() functions to abstract these
tasks from the ELF loader code. Do the communication with
tee-supplicant as well as the hashing and signature verification of the
TA binary in core/arch/arm/kernel/ree_fs_ta.c, which may be disabled
and replaced by a different implementation if need be.
CC: Zeng Tao <prime.zeng@hisilicon.com>
Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (HiKey, QEMU)

core: add interface to load and decrypt/authenticate user TAs

---

scripts/checkpatch_inc.sh
typedefs.checkpatch

When running checkpatch on the OP-TEE code, for instance during the
Travis checks, it happens that we get false warnings and errors caused
by the use of GlobalPlatform typedefs. In the following example, the
patch introduces pointers to functions returning TEE_Result, but
checkpatch won't accept it as a valid type:
$ ./scripts/checkpatch.sh d776721 | tail -1
total: 1 errors, 5 warnings, 555 lines checked
To address such issues, declare our custom types in a local file
(typedefs.checkpatch) and use the new --typedefsfile option provided by
checkpatch.pl.

Take some GP types into account when running patch check tool

---

core/arch/arm/mm/core_mmu.c
lib/libutils/ext/include/util.h

Fixes problem with upper 32-bit of a 64-bit address being zeroed out when rounding the address.

Rounding fix

---

core/arch/arm/mm/core_mmu_lpae.c

When enumerating static_memory_map to setup the translation table, the
"dynamic" entries are skipped incorrectly. As a result, if the first
entry is MEM_AREA_RES_VASPACE, the function does nothing (because
core_mmu_is_dynamic_vaspace(mm) is true and base_va is NULL) and the
translation tables are left uninitialized.
Fixes: c6c69797168c ("mm: add new VA region for dynamic shared buffers")
Fixes: https://github.com/OP-TEE/optee_os/issues/1511

core: arm: mm: LPAE: init_xlation_table(): skip dynamic entries properly

---

core/arch/arm/include/mm/core_memprot.h
core/arch/arm/mm/core_mmu.c

core: remove unused CORE_MEM_EXTRAM

---

scripts/checkpatch_inc.sh

If one relies on a checkpatch script that does not support argument `--typedefsfile`, the script will fail whereas it could simply run without this extra feature.

checkpatch: support kernel not supporting --typedefsfile argument

---

core/arch/arm/kernel/thread.c
core/arch/arm/tee/entry_std.c
core/include/optee_msg.h

The current Linux kernel (v4.12-rc1) has introduced a few changes in
optee_msg.h. The most important one is replacing the macro
OPTEE_MSG_GET_PARAMS() with a c99 style struct optee_msg_param params[]
member in struct optee_msg_arg.
The changes in core/arch/arm/kernel/thread.c and
core/arch/arm/tee/entry_std.c deals with that change.

core: update optee_msg.h from Linux v4.12-rc1

---

core/arch/arm/mm/core_mmu_v7.c

Fixes: c6c69797168c  ("mm: add new VA region for dynamic shared buffers")
Fixes: https://github.com/OP-TEE/optee_os/issues/1536

core: fix non-LPAE mapping

---

core/arch/arm/mm/mobj.c
core/include/keep.h

Workaround the KEEP_*() macro problem that sometimes causes the Aarch64
linker to assert. Since the pager is not enabled for Aarch64 yet we can
stub these macros in the definition.

core: workaround KEEP_*() macro problem

---

core/arch/arm/include/mm/core_mmu.h
core/arch/arm/mm/core_mmu.c

Those 3 commits could be squashed into a single one.
These changes are quite useful for integration of https://github.com/OP-TEE/optee_os/pull/1459 and https://github.com/OP-TEE/optee_os/pull/1533 regarding physical TEE_RAM identification (1st commit).
The 2 later commits are cleanup related.

Remove some useless mandated mapping verifications

---

core/arch/arm/arm.mk
core/arch/arm/include/kernel/generic_boot.h
core/arch/arm/include/mm/core_mmu.h
core/arch/arm/kernel/generic_boot.c
core/arch/arm/kernel/generic_entry_a32.S
core/arch/arm/kernel/generic_entry_a64.S
core/arch/arm/kernel/kern.ld.S
core/arch/arm/mm/core_mmu.c
core/arch/arm/mm/core_mmu_lpae.c
core/arch/arm/mm/core_mmu_v7.c
core/arch/arm/mm/mobj.c
core/arch/arm/plat-sunxi/kern.ld.S

Make executable memory non writable in the OP-TEE core static mapping
(P-R title changed: drop the RFC state)
-1 core reuses the mmu xlat table when possible (allows core to map inside xlat already mapped)
- Needed for non-LPAE mapping only.
-2 new core rx/ro/rw memory, align of core (private ?) memory on attributes boundaries, apply to map
- `CFG_CORE_RWDATA_NOEXEC=y/n`    Separate executable and writable memories. Defaults to 'y'.
- `CFG_CORE_RODATA_NOEXEC=y/n`     Separate executable and from rodata. Defaults to 'n'.
~-3 pager specific case: try to make rx pages non writable through the pager aliasing.~  => postponed
~-4 Last: enable write-implies-execute-never in mmu (when applicable, updated plat configs)~  => postponed
Happy review...

Make executable memory non writable in the core

---

core/arch/arm/arm.mk
core/arch/arm/include/kernel/thread.h
core/arch/arm/include/kernel/unwind.h
core/arch/arm/include/kernel/user_ta.h
core/arch/arm/kernel/abort.c
core/arch/arm/kernel/elf_common.h
core/arch/arm/kernel/elf_load.c
core/arch/arm/kernel/elf_load.h
core/arch/arm/kernel/sub.mk
core/arch/arm/kernel/thread.c
core/arch/arm/kernel/thread_a64.S
core/arch/arm/kernel/unwind_arm32.c
core/arch/arm/kernel/unwind_arm64.c
core/arch/arm/kernel/user_ta.c
lib/libutee/arch/arm/user_ta_entry.c
lib/libutils/ext/arch/arm/aeabi_unwind.c
lib/libutils/ext/arch/arm/sub.mk
lib/libutils/ext/include/trace.h
mk/config.mk
scripts/symbolize.py

Add TA call stack to the abort message. Here is an example:
```
root@HiKey:/ xtest 9148
Test ID: 9148
Run test suite with level=0
TEE test application started with device [(null)]
######################################################
#
#
######################################################
* gp_9148 50-51-15
ERROR:   TEE-CORE: 
ERROR:   TEE-CORE: User TA data-abort at address 0xffffdecd (alignment fault)
ERROR:   TEE-CORE:  esr 0x92000021  ttbr0 0x100003f0810c0   ttbr1 0x00000000   cidr 0x0
ERROR:   TEE-CORE:  cpu #6          cpsr 0x60000130
ERROR:   TEE-CORE:  x0  00000000ffffdead x1  0000000000000000
ERROR:   TEE-CORE:  x2  0000000000000000 x3  0000000040201000
ERROR:   TEE-CORE:  x4  00000000ffffdead x5  0000000040000f74
ERROR:   TEE-CORE:  x6  0000000000000000 x7  0000000040000ec8 …
```

TA unwinding on abort (print call stack)

---

core/arch/arm/plat-imx/conf.mk
core/arch/arm/plat-imx/imx6-regs.h
core/arch/arm/plat-imx/imx6.c
core/arch/arm/plat-imx/imx6ul-regs.h
core/arch/arm/plat-imx/imx_pl310.c
core/arch/arm/plat-imx/platform_config.h
core/arch/arm/plat-imx/sub.mk

Add a CFG_MX6xxx variable for every i.MX6 SoC variants and get register
addresses and values based on these variables instead of relying on
board names.
Signed-off-by: Mathieu Briand <mbriand@witekio.com>
This patch cleans the i.MX6 support and makes the process of adding a new i.MX6 based board easier, as discussed in #1434 .
@MrVan , does it match the modifications you had in mind ? Do you see any other point that may be enhanced ?
Code and defines are grouped by ultralight vs non-ultralight SoC. Non ultralight is simply named "imx6" as naming it "imx6-sdldq" for Solo/DualLite/Dual/Quad seems quite complicated to read. Any opinion ?
Modifications only consist of code refactoring so it should not break anything. It was tested on mx6qsabrelite, mx6qsabresd and mx6dlsabresd boards. It was …

core: arm: Rework i.MX6 source files

---

core/arch/arm/pta/core_self_tests.c
lib/libutils/ext/include/compiler.h
lib/libutils/ext/include/util.h

Compiler builtin support for checking overflow of addition, subtraction
and multiplication is used if available. If unavailable a fallback
implementation using macros is used instead.

util: add macros for arithmetics with overflow checking

---

core/arch/arm/mm/tee_pager.c

This change lowers the attack surface of executable memory in the pager by allowing write access to aliased virtual pages related to read-only content (including executable content) only when pager needs to update page content.

[RFC] core: make pager aliased paged not always writable

---

core/arch/arm/include/arm32.h
core/arch/arm/include/arm64.h
core/arch/arm/pta/benchmark.c
core/arch/arm/pta/sub.mk
core/arch/arm/tee/entry_std.c
core/include/bench.h
core/include/optee_msg.h
lib/libutee/include/pta_benchmark.h

Related PRs:
Benchmark app:
https://github.com/linaro-swg/optee_benchmark/pull/1
Changes in OP-TEE
https://github.com/linaro-swg/linux/pull/38
https://github.com/OP-TEE/build/pull/124
https://github.com/OP-TEE/optee_os/pull/1365
https://github.com/OP-TEE/optee_client/pull/79

OP-TEE Benchmark

---

core/arch/arm/include/mm/core_memprot.h
core/arch/arm/mm/core_mmu.c
core/arch/arm/plat-imx/imx_pl310.c
core/arch/arm/plat-imx/main.c
core/arch/arm/plat-imx/psci.c

Add get_base and get_io_base function helper function. These two functions are only to wrap phys_to_virt and phy_to_virt_io and add cpu_mmu_enabled checking.

add get_base and get_io_base helper function

---

core/kernel/tee_ta_manager.c

Ignore the TA_FLAG_MULTI_SESSION and TA_FLAG_INSTANCE_KEEP_ALIVE when
the TA_FLAG_SINGLE_INSTANCE is not set.

core: ta flags fixup

---

core/tee/tee_cryp_utl.c
lib/libutee/tee_api_operations.c

CTR mode of AES algorithm turns block cipher into stream cipher.
It means that input data can has any size independent from block
size. It must be processed and result ciphertext must be
generated after each TEE_CipherUpdate function call. That is why
it is incorrect to apply for AES CTR the input buffering on
TEE_CipherUpdate call when size is not multiple of block size.
Signed-off-by: Bogdan Liulko <bogdan.liulko@globallogic.com>

Remove buffering for AES CTR

---

core/drivers/sub.mk
core/drivers/tzc380.c
core/include/drivers/tzc380.h

Add tzc380 driver support.
The usage:
Use tzc_init(vaddr_t base) to get the tzc380 configuration.
Use tzc_configure_region to configure the memory region,
such as "tzc_configure_region(5, 0x4e000000,
TZC_ATTR_REGION_SIZE(TZC_REGION_SIZE_32M) | TZC_ATTR_REGION_EN_MASK |
TZC_ATTR_SP_S_RW);"
An example for 6ULEVK:
```
tzc_init(addr);
tzc_configure_region(0, 0x00000000, TZC_ATTR_REGION_SIZE(TZC_REGION_SIZE_4G) | TZC_ATTR_REGION_EN_MASK | TZC_ATTR_SP_ALL);
tzc_configure_region(1, 0x80000000, TZC_ATTR_REGION_SIZE(TZC_REGION_SIZE_2G) | TZC_ATTR_REGION_EN_MASK | TZC_ATTR_SP_NS_RW);
tzc_configure_region(2, 0x9e000000, TZC_ATTR_REGION_SIZE(TZC_REGION_SIZE_32M) | TZC_ATTR_REGION_EN_MASK | TZC_ATTR_SP_S_RW);
tzc_configure_region(3, 0x9e000000, TZC_ATTR_REGION_SIZE(TZC_REGION_SIZE_2M) | …
```

drivers: tzc380: add tzc380 driver

---

core/arch/arm/arm.mk
core/arch/arm/kernel/generic_entry_a32.S
core/arch/arm/kernel/generic_entry_a64.S
core/arch/arm/plat-sunxi/entry.S
core/arch/arm/plat-sunxi/smp_boot.S

We occasionally get reports from people stumbling upon data abort
exceptions caused by alignment faults in TAs. The recommended fix is to
change the code so that the unaligned access won't occur. But it is
sometimes difficult to achieve.
Therefore we provide a compile-time option to disable alignment checks.
For AArch64 it applies to both SEL1 and SEL0.

core: arm: make alignment check configurable

---

mk/config.mk

Assume the default build environment is meant for development, so set
CFG_TEE_CORE_DEBUG=y by default.

core: enable debug mode by default

---

lib/libutils/ext/trace.c
mk/config.mk

Since commit f4aa5b11f9a3 ("Update trace format to be less verbose in
INFO and ERROR levels"), INFO and ERROR messages don't show source file
and line information by default, while message with lower severity
(DEBUG and FLOW) do contain such information. While it is OK for INFO,
it turns out to be inconvenient for ERRORs during development, because
one typically wants to be able to quickly locate the source of errors.
This patch fixes the problem by introducing a mask rather than a level
to control the long output format. This allows individual selection of
which level should use a long vs. short format.
The compile-time setting CFG_MSG_LONG_PREFIX_THRESHOLD is replaced by
CFG_MSG_LONG_PREFIX_MASK with default value 8 (= ERROR | DEBUG | FLOW).
Signed-off-by: Jerome Forissier …

trace.c: show file/line info for flow, debug and error messages

---

core/arch/arm/include/kernel/thread.h
core/arch/arm/include/mm/mobj.h
core/arch/arm/kernel/ree_fs_ta.c
core/arch/arm/kernel/thread.c
core/arch/arm/kernel/thread_private.h
core/arch/arm/mm/mobj.c
core/arch/arm/pta/gprof.c
core/arch/arm/tee/entry_std.c
core/arch/arm/tee/pta_socket.c
core/include/kernel/msg_param.h
core/include/tee/tee_fs_rpc.h
core/kernel/msg_param.c
core/kernel/sub.mk
core/tee/tee_fs_rpc.c
core/tee/tee_fs_rpc_cache.c
core/tee/tee_rpmb_fs.c

This patch series includes three patches:
* added `msg_parm.c` to ease up REE-TEE parameters handling
* added new `mobj` type `mobj_shm`. This `mobj` describes buffer in preshared memory region (` CORE_MEM_NSEC_SHM`).
*  All shared buffers are wrapped into `mobjs` (both command buffers, and buffers allocated in `thread.c`). All users of shared buffers (e.g. user TA loader) now work with `mobj`s. This allows to pass another `mobj` types, like registered `mobj` which will be introduced in #1232

Use `mobj`s to pass shared buffers

---

core/arch/arm/plat-ti/platform_config.h

The first 4KB of SRAM is used by the initial secure software and
OP-TEE should not be loaded to this address. Adjust the TEE_LOAD_ADDR
to reflect this.

plat-ti: Reserve first page of SRAM for secure boot software

---

core/arch/arm/mm/mobj.c

Not right variable was used to calculate offset.

mobj: mobj_reg_shm: fix bug in offset calculation

---

core/include/kernel/msg_param.h

msg_param_get_buf_size() and  msg_param_attr_is_tmem() only read
from their parameter, so that parameter can be declared as `const`

msg_param.h: add `const` qualifier for read-only functions

---

core/arch/arm/kernel/link.mk

Fix generation of init_entries.txt: spaces were missing and made the
tool fail to generate the 'init' dependency resource list.

core: fix 'keep_init' handling in link.mk

---

core/lib/libtomcrypt/include/tomcrypt_custom.h
core/lib/libtomcrypt/include/tomcrypt_math.h
core/lib/libtomcrypt/src/mpa_desc.c
core/lib/libtomcrypt/src/pk/rsa/rsa_exptmod.c
core/lib/libtomcrypt/sub.mk
lib/libmpa/include/mpalib.h
lib/libmpa/mpa_expmod.c
lib/libmpa/mpa_random.c

Fixes for the security issues that we discussed a while ago. Note that patches has already been reviewed once before this PR, so that is the reason why you already find that in the patches.
```bash
root@Vexpress:/ xtest -l 15
...
+-----------------------------------------------------
47112 subtests of which 0 failed
78 test cases of which 0 failed
0 test case was skipped
TEE test application done!
root@Vexpress:/ 
```

Rsa for 2.5.0

---

core/arch/arm/kernel/thread_a64.S

For GICV3 situation, IRQ is used as native interrupt. This patch
also suppressed assert in thread_user_save_vfp().
Signed-off-by: Zhizhou Zhang <zhizhouzhang@asrmicro.com>

core: fix incorrect IRQ mask for CFG_ARM_GICV3

---

core/arch/arm/tee/entry_std.c
core/include/kernel/msg_param.h
core/include/optee_msg.h
core/kernel/msg_param.c

This patch introduces new attribute OPTEE_MSG_ATTR_NONCONTIG to allow
Normal World pass arbitrary list of physical pages as a shared buffer.
To read this list of page address two new functions are added:
- msg_param_extract_pages() is a helper function that read pages list
into provided array
- msg_param_mobj_from_noncontig_param() constructs mobj from provided
struct optee_msg_param parameter. This mobj then can be used in
various parts of OP-TEE

ABI change: add OPTEE_MSG_ATTR_NONCONTIG handling

---

core/arch/arm/include/mm/core_mmu.h
core/arch/arm/kernel/generic_boot.c
core/arch/arm/mm/core_mmu.c
core/arch/arm/plat-vexpress/main.c

This should take care of the problem with unexpected non-sec addresses from normal world in for instance https://github.com/OP-TEE/optee_os/pull/1232 by updating the non-sec DDR config from DT instead of using hard coded value on QEMU.
@lorc please confirm

Assign non-sec DDR configuration from DT

---

core/arch/arm/include/arm32.h
core/arch/arm/include/arm32_macros.S
core/arch/arm/include/arm64.h
core/arch/arm/include/kernel/tz_ssvce.h
core/arch/arm/include/mm/core_mmu.h
core/arch/arm/kernel/ssvce_a32.S
core/arch/arm/kernel/ssvce_a64.S
core/arch/arm/mm/core_mmu.c
core/arch/arm/mm/core_mmu_lpae.c
core/arch/arm/mm/core_mmu_v7.c
core/arch/arm/mm/tee_mmu.c
core/arch/arm/mm/tee_pager.c

These changes reviews the TLB invalidation support and somewhat optimizes the TLB maintenance in the pager to prevent executing to many synchronization barriers when possible.
~~This change also removes the statck unwind from cache maintenance primitives, including data/instr. cache and TLBs.~~ **edited:** good question, why removing the stack unwind? no answer. discard.

Review TLB invalidation sequence

---

core/arch/arm/mm/core_mmu.c

Relaxes verify_special_mem_areas() with regards to MEM_AREA_RAM_NSEC and
MEM_AREA_NSEC_SHM. Those two regions are from now on allowed to overlap
as any overlap there is harmless and more trouble than it's worth to
avoid.
Fixes problem with panic() when booting on FVP.
Fixes: 70cdca357de9 ("plat-vexpress: use register_nsec_ddr()")

core: relax verify_special_mem_areas()

---

core/arch/arm/mm/core_mmu.c
core/arch/arm/mm/mobj.c

The first and and fourth lines in the boot sequence below are debug
messages that should not be printed when the log level is INFO:
INFO:    TEE-CORE: No NSEC DDR memory area defined
INFO:    TEE-CORE:
INFO:    TEE-CORE: OP-TEE version: 2.5.0-rc1 #1 Wed Jun 28 15:11:06 UTC 2017 aarch64
INFO:    TEE-CORE: Shared memory address range: 3dc00000, 3f000000
INFO:    TEE-CORE: Initialized

core: demote a couple of messages from IMSG() to DMSG()

---

core/arch/arm/kernel/link.mk
documentation/optee_design.md
scripts/gen_hashed_bin.py

In order to adapt to the optee pager supporting, it needs to split the
original tee.bin into three images, that is tee-header-v2.bin,
tee-pager-v2.bin and tee-pageable-v2.bin.
Change-Id: I8bff3d3aa7b03a39cda21b28e1b1a1e624675ee6
Signed-off-by: Summer Qin <summer.qin@arm.com>

Split the optee image into three images to support optee pager in arm-tf

---

core/arch/arm/mm/tee_pager.c

Adds missing synchronization, dsb_ishst(), required to make sure that
translation table update is visible after the final update of the
attributes of a page.
Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (Hikey)

core: pager: fix tee_pager_set_uta_area_attr()

---

core/arch/arm/kernel/unwind_arm32.c

Previously was print_kernel_stack() supplying zeroes instead of real
values for start and size of exidx tables needed for unwind.  With this
patch are correct values for exidx and exidx_sz supplied.

core: fix print_kernel_stack()

---

CHANGELOG.md

Update CHANGELOG.md for 2.5.0

---

core/arch/arm/include/kernel/thread.h
core/arch/arm/kernel/abort.c
core/arch/arm/kernel/thread.c

Fixes get_fault_type() to accurately report abort in abort handler also
in AArch64.
Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (QEMU v8)

core: abort: fix get_fault_type()

---

core/arch/arm/mm/core_mmu.c

The mem_map_inited is useless,so remove it.
The MEM_AREA_SHM_VASPACE vapsace should have the size of
SHM_VASPACE_SIZE, fix it here.

core: remove mem_map_inited and fix the SHM_VASPACE_SIZE

---

core/arch/arm/plat-hikey/hikey_peripherals.h
core/arch/arm/plat-hikey/main.c
core/arch/arm/plat-hikey/spi_test.c

Use core_mmu_get_va whenever possible

---

core/arch/arm/plat-imx/sub.mk

Reported in #1685 
i.MX6SOLO is almost same with i.MX6DualLite, with difference that
6S has one cpu core, but DualLite has two cpu cores.
i.MX6Solo also needs a9_plat_init.S and imx6.c for basic initialization.

core: arm: imx: fix imx6solo boot

---

core/arch/arm/include/kernel/thread.h
core/arch/arm/kernel/mutex.c
core/arch/arm/kernel/thread.c

Adds thread_is_in_normal_mode() which returns true if the current thread
is in normal mode. Adds an assert(thread_is_in_normal_mode()) in
__mutex_lock().

core: assert only normal thread takes a mutex

---

core/arch/arm/kernel/thread_a32.S

Prior to this patch when a native interrupt was received in IRQ mode
r12 wasn't saved on the stack. There's two problems with that:
1. r12 isn't a callee preserved register, but must be preserved
in an exception handler
2. Without r12 an odd number of registers was saved breaking the
8 byte alignment of the stack pointer
This patch fixes this by also saving r12 on the stack when handling a
native interrupt in IRQ mode.

core: arm32: fix native_intr_handler()

---

mk/gcc.mk

In some cases, ld is linked to gold version,
and it will cause compiling error for 32bit like following:
prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/bin/arm-linux-androideabi-ld: fatal error: --sort-section=alignment: must take one of the following arguments: none, name
with the bfd version ld, there will be no such error reported.
Signed-off-by: Yongqin Liu <yongqin.liu@linaro.org>

mk/gcc.mk: define LD to bfd version by default

---

core/arch/arm/plat-d02/conf.mk
core/arch/arm/plat-d02/platform_config.h

~Please ignore the first commit, it is a fix to the 32-bit pager configuration for D02 that's already up for review in https://github.com/OP-TEE/optee_os/pull/1596.~ *Edit: PR 1596 has been merged.*

plat-d02: enable 64-bit paging

---

core/arch/arm/kernel/generic_boot.c

From Power_ePAPR_APPROVED_v1.1.pdf chapter 3.4 Memory node,
there is no address-cells and size-cells property for in
memory node. Memory node only support three properties "device_type",
"reg" and "initial-mapped-area".
When prase the memory node, need to use the address/size-cells of
root node.
Without this patch, I have to add address-cells and size-cells to memory node of device tree. Also this patch should fix #1710

core: arm: boot: fix get_memory

---

core/arch/arm/pta/benchmark.c

Issue reproduces with enabled CFG_TEE_BENCHMARK and in case when
registration of benchmark timestamp buffer failes or isn't performed
(in case if any CA is invoked directly, without using benchmark CA)

benchmark: fix core data-abort issue

---

.travis.yml
MAINTAINERS.md
README.md

Update .travis.yml, MAINTAINERS.md and  README.md for RK322X #1666

Update description files for RK322X

---

core/arch/arm/mm/core_mmu.c

Enable MEM_AREA_TEE_COHERENT with attribute setting to
SECURE/PRWX/NONCACHE.
when register a piece memory with MEM_AREA_TEE_COHERENT, the memory will be marked as secure/prwx/noncache. Here I enable both W and X. I know that there is patch that enable WXN and UWXN to make system more secure, but I need a piece memory both have data and code to implement i.mx low power features.

core: arm: mmu: enable MEM_AREA_TEE_COHERENT

---

.travis.yml

Travis are currently migrating Linux distributions from Ubuntu Precise
(12.04) to Trusty (14.04). It seems that $HOME/bin already exists in
the new images, which causes an error as we do mkdir $HOME/bin.
Add a -p so that the directory creation doesn't fail when bin
exists. This allows the script to run on both Precise and Trusty.

Travis: add -p to mkdir $HOME/bin

---

core/arch/arm/mm/tee_pager.c

This optimization is so small that it's almost impossible to measure it but just timing xtest.
But I still think these changes has a value as it actually affects performance of the other cores also.

Pager optim

---

core/arch/arm/include/kernel/thread.h
core/arch/arm/kernel/abort.c
core/arch/arm/kernel/asm-defines.c
core/arch/arm/kernel/thread.c
core/arch/arm/kernel/thread_a32.S
core/arch/arm/kernel/thread_private.h

Switch to handle aborts in system mode in order to be able to give a
stack trace in case an abort occurs in the abort handler.
In a manner similar to the AArch64 implementation are abort and undef
mode stack pointers pointing to the struct thread_core_local of
corresponding cpu.
Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (Hikey)

core: arm32: handle aborts in system mode

---

core/arch/arm/include/sm/psci.h
core/arch/arm/plat-rockchip/common.h
core/arch/arm/plat-rockchip/cru.h
core/arch/arm/plat-rockchip/psci_rk322x.c
core/arch/arm/sm/psci.c

RK322X adds PSCI version, features and system suspend implementations.
PSCI version and features must be implemented, because Linux Kernel will check whether optee supports PSCI system suspend or not by getting status from PSCI version and features.
Signed-off-by: Joseph Chen <chenjh@rock-chips.com>

Rk322x adds PSCI version, features and system suspend

---

lib/libutee/trace_ext.c
lib/libutils/isoc/include/stdio.h

```
Calling printf() from a TA to print a single character results in a
linker error:
39  TEE_Result TA_CreateEntryPoint(void)
40  {
41          printf(".");
42          /* ... */
43  }
hello_world_ta.o: In function `TA_CreateEntryPoint':
hello_world_ta.c:41: undefined reference to `putchar'
In this case, the compiler has optimized the printf() call into a call
to putchar(), assuming that we have a C library and that it complies to
the relevant standards (so that printf() and putchar() may be used
interchangeably).
One way to fix the issue is to prevent such optimizations by using
-fno-builtin or -ffreestanding, at the cost of slightly larger code
size and possibly reduced performance.
Another option is to simply provide the missing putchar() function. It
is the purpose of this commit. …
```

libutee: provide an implementation of putchar()

---

core/arch/arm/mm/core_mmu.c
lib/libutils/ext/include/util.h

Addresses are unsigned value. Subtracting address values results
in a unsigned value. Since qsort comparison function expects a signed
integer return value, the unsigned address subtraction value gets
signed and can produce a wrong result. This change overcomes the issue
by producing a +1 or -1 signed value based on the unsigned address
values comparison.

core: fix memory address comparison

---

core/arch/arm/sm/psci-helper.S
lib/libutils/isoc/arch/arm/arm32_aeabi_divmod_a32.S
lib/libutils/isoc/arch/arm/arm32_aeabi_ldivmod_a32.S

Clean from locally defined arm.S macros.

core: clean arm32_aeabi_ldivmod_a32.S

---

.travis.yml
MAINTAINERS.md
README.md
core/arch/arm/cpu/cortex-a5.mk
core/arch/arm/kernel/tz_ssvce_pl310_a32.S
core/arch/arm/plat-sam/conf.mk
core/arch/arm/plat-sam/kern.ld.S
core/arch/arm/plat-sam/link.mk
core/arch/arm/plat-sam/main.c
core/arch/arm/plat-sam/matrix.c
core/arch/arm/plat-sam/matrix.h
core/arch/arm/plat-sam/platform_config.h
core/arch/arm/plat-sam/sama5d2.h
core/arch/arm/plat-sam/sub.mk
core/arch/arm/plat-sam/tz_matrix.h
core/drivers/atmel_uart.c
core/drivers/sub.mk
core/include/drivers/atmel_uart.h

Adding support for Atmel/Microchip [SAMA5D2-XULT board](http://www.atmel.com/tools/atsama5d2-xult.aspx)
The processor supports: 
ARM TrustZone, configuring memory and/or peripherals as secure, secure RTC, Secure boot, On-the-fly encryption/decryption of the DDR bus, Tamper protection etc. [Datasheet](http://www.atmel.com/Images/Atmel-11267-32-bit-Cortex-A5-Microcontroller-SAMA5D2_Datasheet.pdf).
Instructions to build optee_os along with bootlog, test results can be found [here](https://github.com/nodeax/optee_os/wiki).

Add Atmel SAMA5 platform support

---

scripts/symbolize.py

```
Use nm and objdump to find the symbol and ELF section that match the
address reported in the the abort line. This can help debug writes to
read-only data or unaligned accesses to global data, for example.
If the address can be resolved to a symbol plus some offset and/or a
section plus some offset, the abort line is printed again just before
the call stack with the symbolic information added. Not that the
translation cannot be done immediately when the abort line is seen
because at this point we don't know the architecture, and we don't have
the load address of the TA.
Here is an example (the line added by this patch is marked with >>):
User TA data-abort at address 0x1314d0 (write permission fault)
fsr 0x0000080f  ttbr0 0x0e07a06a  ttbr1 0x0e07406a  cidr 0x1
cpu #0          cpsr …
```

scripts/symbolize.py: try to resolve abort address to symbol/section[+offset]

---

core/arch/arm/kernel/thread_a32.S
core/arch/arm/tee/arch_svc.c

In Arm aarch32 mode, FIQ is not masked by hardware in IRQ, ABT, SVC and
UND mode.
For GICv2, IRQ is for foreign interrupt and already masked by hardware
in the exception modes listed above.
For GICv3, FIQ is for foreign interrupt. So, we need to mask FIQ
explicitly in these exception modes.
Signed-off-by: David Wang <david.wang@arm.com>

Fix arm32 FIQ mask in IRQ/ABT/SVC/UND handlers for GICv3

---

core/arch/arm/arm.mk

When the CFG_ARM64_core and CFG_ARM32_core are both missing defined by
the platform, it will raise unexpected compile errors. In this patch,
report an compile error when neither the CFG_ARM64_core nor
CFG_ARM32_core is defined.

mk: report an error when the CFG_ARM64{32}_core both missing

---

lib/libutee/trace_ext.c

puts() was recently modified [1] to always add a trailing newline (\n).
This change has broken printf() which uses puts() internally.
Fix the issue by calling trace_ext_puts() instead.
Fixes: 6246cc9d957c ("libutee: puts(): add trailing newline")

libutee: printf() fix: remove newline added by mistake

---

core/arch/arm/mm/core_mmu_lpae.c
core/arch/arm/mm/core_mmu_v7.c

Fixes race in both v7 and lpae versions of
core_mmu_user_mapping_is_active() by temporarily disabling interrupts.
Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (QEMU v8)

core: bugfix core_mmu_user_mapping_is_active()

---

scripts/symbolize.py

The -d option of symbolize.py normally expects one or more directories,
where the script will look for ELF files (TEE or TA, depending on the
input dump). For convenience, let's also accept paths to the actual ELF
files. Previously, the script would just ignore file arguments and
silently fail to resolve stack traces.
Reported-by: Lijianhui <airbak.li@hisilicon.com>

scripts/symbolize.py: accept -d <ELF_file> in addition to -d <dir>

---

core/arch/arm/kernel/unwind_arm32.c

Commit 6693786dda1a ("core: make panic call stack consistent with abort
call stack") has mistakenly introduced an extra 'x' in the TEE core
stack dumps. Remove it.
Fixes: 6693786dda1a ("core: make panic call stack consistent with abort call stack")

core: arm32: remove extra 'x' in core stack dump

---

core/arch/arm/include/arm.h
core/arch/arm/include/arm32.h
core/arch/arm/include/arm64.h

Can be used for enabling user access to both Physical/Virtual counter
registers. Example of usage:
```c
uint32_t cntkctl;
cntkctl = read_cntkctl();
cntkctl |= CNTKCTL_PL0VCTEN;
write_cntkctl(cntkctl);
```

arm timers: add read/write functions for counter PL1 control register

---

core/arch/arm/include/mm/core_mmu.h
core/arch/arm/kernel/generic_boot.c
core/arch/arm/kernel/kern.ld.S
core/arch/arm/mm/core_mmu.c
core/arch/arm/mm/tee_pager.c
core/arch/arm/plat-imx/imx6.c
core/arch/arm/plat-imx/psci.c
core/arch/arm/plat-vexpress/conf.mk
core/arch/arm/tee/init.c

The currently OP-TEE implementation depends on the identity mapping, and
the CFG_TEE_RAM_START and CFG_TEE_LOAD_ADDR are used as both physic and
virtual address which is not extensible.
This patch introduce the virtual address of these two marcos and as a
base of non-identity mapping.

core: introduce TEE_RAM_VA_START and TEE_TEXT_VA_START

---

.shippable.yml

Add a configuration file for the Shippable continuous integration tool
[1]. This file performs the same steps as the current Travis file
(.travis.yml), but it is faster and simpler. Another advantage is, the
timeout is 1 hour compared to 50 minutes for Travis. All in all, this
could be a good fix for the issues we have with Travis being too slow
to properly check our pull requests.
This was tested on a private fork of optee_os, and it worked well for
verifying pushes to private branches as well as pull requests. A full
build takes about 20-25 minutes, that is including the builds for all
targets plus the xtest run in QEMU (with a fully populated cache).
One reason for Shippable being faster is that a custom Docker container
image is used, namely: jforissier/optee_os_ci on Docker Hub [2]. …

ci: add .shippable.yml

---

core/arch/arm/plat-imx/imx6.c
core/arch/arm/plat-imx/psci.c

Fix build errors in plat-imc/imx6.c and plat-imx/psci.c
Fixes: 6a815afa16230 ("core: introduce TEE_RAM_VA_START and TEE_TEXT_VA_START")

core: imx: fix build errors

---

core/arch/arm/include/kernel/misc.h
core/arch/arm/kernel/misc_a32.S
core/arch/arm/kernel/misc_a64.S
core/arch/arm/plat-ls/ls_core_pos_a32.S
core/arch/arm/plat-ls/ls_core_pos_a64.S
core/arch/arm/plat-mediatek/mt8173_core_pos_a32.S
core/arch/arm/plat-mediatek/mt8173_core_pos_a64.S
core/arch/arm/plat-rockchip/core_pos_a32.S
core/arch/arm/plat-vexpress/juno_core_pos_a32.S
core/arch/arm/plat-vexpress/juno_core_pos_a64.S

Adds
size_t get_core_pos_mpidr(uint32_t mpidr);
which translates from mpdir to core position, like get_core_pos() does
for the calling core.
get_core_pos_mpidr() a weak function to
allow platforms to override the implementation.
get_core_pos() now uses get_core_pos_mpidr() internally to calculate the
core position without using any stack.
With get_core_pos_mpidr() all the platform specific implementations of
get_core_pos() has been replaced with get_core_pos_mpidr() and
get_core_pos() is not weak any longer to avoid unexpected runtime errors
in out of tree rebased platforms.
Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (QEMU v8)

core: introduce get_core_pos_mpidr()

---

documentation/interrupt_handling.md

This P-R initially aimed at adding a section on TEE thread scheduling in the documentation. This topic raised few question in the past months.
Best place seemed the interrupt_handling docs, hence this P-R proposes some review of the interruption/exception documentation.
If these changed are to be merged, I would propose to squash them into a single commit.

Review documentation on exceptions, add some scheduling considerations.

---

.shippable.yml

```
When building a pull request, we want to run checkpatch on each commit
included in the pull request. Unfortunately, it is not what the current
code does, because $SHIPPABLE_COMMIT_RANGE contains a three-dot
notation such as: <commit>...<commit>. This syntax is interpreted
differently depending on the git command that parses it.
Quoting git help diff:
git diff [--options] <commit> <commit> [--] [<path>...]
This is to view the changes between two arbitrary <commit>.
git diff [--options] <commit>..<commit> [--] [<path>...]
This is synonymous to the previous form.
git diff [--options] <commit>...<commit> [--] [<path>...]
This form is to view the changes on the branch containing and up
to the second <commit>, starting at a common ancestor of both
<commit>.
Quoting git help revisions …
```

ci: .shippable.yml: fix commit range

---

core/arch/arm/mm/core_mmu.c

Adds missing dsb_ishst() at the end of core_mmu_map_pages() needed to
guarantee that changes to translation tables are visible.
Reported-by: Stuart Yoder <stuart.yoder@arm.com>

core: fix core_mmu_map_pages()

---

.shippable.yml

The _make function is supposed to return an error status in case make
fails. For this to happen, we need to use && between commands, not ;.
Fixes: 5da449eaf73b ("ci: add .shippable.yml")

ci: .shippable.yml: fix _make function

---

core/arch/arm/kernel/generic_boot.c

config_nsmem() used VA of SHM region. This is wrong and it confused
linux kernel. We need to pass physical address.

dts: pass PA of reserved region

---

scripts/gen_ld_sects.py

Before Python 2.7 omitting the positional argument specifier was not
allowed. Some may still be using earlier Python version where this
will cause build to fail. Fix this here.
Fixes: 5976a0a5b9bf ("core: avoid incremental linking with -gc")
Reported-by: Nishanth Menon <nm@ti.com>

Explicitly number positional argument specifiers

---

core/arch/arm/plat-ti/conf.mk

On AM43xx family devices the non-secure side may IDLE hardware IP
that are not in use. This will prevent the correct operation of these
IP on the secure side. Until a solution to share management of IPs is
developed, disable the secure driver for this platform.

TEMP: plat-ti: Disable TRNG use on AM43xx

---

README.md

Currently we point to an individual SoCs product page, each OP-TEE
flavor works across an entire SoC family, so point the flavor info
to the family landing page instead.

README.md: Update TI URLs to product landing pages

---

core/arch/arm/plat-vexpress/platform_config.h

With the current setup, qemu puts initrd in the midst of reserved
SHM region. This confuses linux kernel, because it forbids self
to access that reserved region.
As there are no easy way tell qemu where to put initrd, it is easier
to move SHM in the optee-os.

qemu_v8: move SHM region

---

core/arch/arm/tee/arch_svc_a32.S
core/arch/arm/tee/arch_svc_a64.S

Updates comments describing how syscall_sys_return() and syscall_panic()
manages to return from the TA in order to resume execution in OP-TEE OS.

core: thread: clarify syscalls return and panic

---

core/arch/arm/plat-ti/a9_plat_init.S
core/arch/arm/plat-ti/api_monitor_index_a9.h
core/arch/arm/plat-ti/conf.mk
core/arch/arm/plat-ti/sm_platform_handler_a9.c
core/arch/arm/plat-ti/sub.mk

Hello all,
This is the AM43xx suspend/resume patch based on the common code in: https://github.com/OP-TEE/optee_os/pull/1729
Thanks,
Andrew

AM43xx Suspend/Resume

---

core/arch/arm/kernel/user_ta.c

Use TEE_MMU_UMAP_STACK_IDX to replace the number 0.

core: user_ta: use TEE_MMU_UMAP_STACK_IDX

---

core/arch/arm/mm/tee_mmu.c

If calloc fails, need to free the asid bit in g_asid.
This is just code inspection, not tested.

core: tee_mmu: avoid resource leak

---

.github/issue_template.md
.github/pull_request_template.md

With these two files added to OP-TEE the users will get this shown when (before creating/submitting) creating issues and pull requests. Hopefully some people will pay attention to that and in the long run that would eventually save us a minute or two.
I think that we could start by adding this to `optee_os` and then later add it to the other git's that we are maintaining. 
For more information regarding GitHub templates, please see [this](https://help.github.com/articles/creating-an-issue-template-for-your-repository/) and [this](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/) link.

Add GitHub template files for issues and PRs

---

core/arch/arm/include/mm/core_mmu.h
core/arch/arm/mm/core_mmu.c
core/arch/arm/mm/core_mmu_lpae.c
core/arch/arm/mm/core_mmu_v7.c

Main issue fixed here is that 32bit mmu maps dynamic shm as secure due to an issue in the `core_mmu_divide_block()` function.
This change also proposes some simplifications in `core_mmu_divide_block()` since it is currently not used to unmap already mapped memory.

Fixes for core_mmu_divide_block() on 32bit mmu

---

.shippable.yml

There is a bug in the step that prepares a source tree to build and run
OP-TEE with QEMU, at the end of the CI script. The idea is, clone the
current project forest using the repo tool, then remove optee_os and
replace it with a symbolic link to the one that has been checked out in
the CI infrastructure. So that, we are effectively testing the desired
pull request or branch.
The problem is, the symlink is not removed at the end of the script, so
it ends up being cached and restored with the next build. The repo sync
command follows the symlink and overwrites the "good" optee_os with the
current master branch and at this point we're doomed.
Fix that by making sure there is no optee_os symlink leftover from the
cache.

ci: shippable: make sure QEMU test runs on the proper commit

---

core/arch/arm/include/sm/optee_smc.h
core/arch/arm/kernel/thread.c
core/arch/arm/mm/core_mmu.c
core/arch/arm/tee/entry_fast.c
core/arch/arm/tee/entry_std.c
core/include/kernel/msg_param.h
core/kernel/msg_param.c
mk/config.mk

Hello.
There are last patches for dynamic SHM. 
I'm not sure, if I did right thing, when created two patches with ABI changes, because 4e5d00d ("ABI change: add shared memory support") enables new capability and 30260ae ("ABI change: enable TMEM parameters with non-contiguous shm") extends it.
Probably I should squash those two patches into one, or create one additional patch for `entry_fast.c`, that enables `OPTEE_SMC_SEC_CAP_DYNAMIC_SHM`. What do you think?

Enable dynamic SHM support

---

scripts/symbolize.py

The symbolize script may not process correctly several dumps in a row.
For instance, if you pipe a TA abort followed by a TEE core abort, the
later is not decoded properly because the script still uses the TA
binary to interpret the core stack. Fix this by resetting the state of
the decoder each time an abort line is encountered.

scripts/symbolize.py: reset state when a (new) abort message is found

---

mk/config.mk

Update the comment in the main configuration file to state that
CFG_UNWIND should be disabled in production builds.
Suggested-by: Etienne Carriere <etienne.carriere@linaro.org>

Add comment about CFG_UNWIND

---

core/arch/arm/plat-rcar/conf.mk
core/arch/arm/plat-rcar/main.c
core/arch/arm/plat-rcar/platform_config.h

There are two patches that configure nonsec DDR ranges for RCAR salvator-h3 and salvator-m3 boards.

Add non-secure DDR ranges to rcar-based boards

---

core/arch/arm/pta/pta_invoke_tests.c

Physical memory typed CORE_MEM_NSEC_SHM belong to the default
contiguous shm memory. Since dynamic SHM, now non secure memory
reference can be outside the default NSEC_SHM, hence check
non secure reference using CORE_MEM_NON_SEC type instead of
CORE_MEM_NSEC_SHM.

core:sdp: fix SDP test pseudo-TA against dynamic shm

---

core/arch/arm/plat-stm/main.c
core/arch/arm/plat-stm/platform_config.h

CFG_DDR_SECURE_BASE/_SIZE can be used to define the extact DDR range
reserved to secure side. This can be larger than the TEETZ reserved
memory. If CFG_DDR_SECURE_BASE/_SIZE is defined, plat-stm registers
the non-secure external memory to support dynamic shm registering.

plat-stm: support registered shm buffers

---

.shippable.yml
.travis.yml
MAINTAINERS.md
README.md
core/arch/arm/plat-marvell/armada7k8k/hal_sec_perf.c
core/arch/arm/plat-marvell/conf.mk
core/arch/arm/plat-marvell/main.c
core/arch/arm/plat-marvell/platform_config.h
core/arch/arm/plat-marvell/sub.mk
lib/libutils/ext/include/util.h

Added Marvell platform with initial support for ARMADA A7K & A8K.
Only tested 64-bit mode with default configurations:
1. build command
make PLATFORM=marvell-armada7080 CFG_ARM64_core=y
2. Passed xtest
Signed-off-by: Kevin Peng <kevinp@marvell.com>

Add Marvell ARMADA A7K A8K platform support

---

core/arch/arm/include/mm/mobj.h
core/arch/arm/mm/mobj.c
core/arch/arm/mm/tee_mmu.c
core/arch/arm/tee/entry_std.c

Currently the offset into MOBJs is calculated in a not very obvious way.
See for instance the fixes needed in https://github.com/OP-TEE/optee_os/pull/1877 to compensate for that.
This PR aims to simplify the way we keep track of the offset by always taking all the sources into account.

RFC: Remove double offset

---

core/arch/arm/include/mm/mobj.h
core/arch/arm/kernel/pseudo_ta.c
core/arch/arm/mm/mobj.c

Please ignore the commits "core: mobj: add mobj_get_phys_offs()" and "core: mobj: remove double physical offset" which are part of https://github.com/OP-TEE/optee_os/pull/1883

Map buffers in parameters for Pseudo TAs

---

core/arch/arm/mm/core_mmu.c
core/arch/arm/mm/tee_mmu.c
core/arch/arm/pta/pta_invoke_tests.c

This change takes care that the offset in page of the target address
to be converted is not added twice when computing the address
physical page based on the memory object reference.

core:mmu: fix userland va/pa conversion

---

core/arch/arm/kernel/thread.c

Mobj, containing memory for RPC arguments was not deleted
when client disabled argument cache. That would lead
to resource leak.

thread.c: free rpc arg mobj during cache disabling

---

Makefile
mk/cleandirs.mk

"make clean" might fail with the following error:
make[2]: execvp: /bin/bash: Argument list too long
This error was observed on a platform that has lots of additional
source files compared to upstream (drivers, etc.), and that sets a long
output path on the command line (make ... O=/some/long/path).
Fix the error by splitting the file list into more manageable chunks.
Note that removing one file at a time is not reasonable, because
spawning too may shells takes quite a long time (up to 7-10 seconds to
"make clean").
Reported-by: Lijianhui <airbak.li@hisilicon.com>

make clean: split file list into manageable chunks

---

core/tee/tee_svc_storage.c

Changes `syscall_storage_obj_create` to give physical object ownership
to the tee object layer only once storage is successfully inited
for that object. Otherwise, if `tee_svc_storage_init_file` fails,
the storage does not own the physical object and close method
will not release the object.
This change fixes https://github.com/OP-TEE/optee_test/issues/232.

core: fix allocated object on object creation failure in svc storage

---

core/arch/arm/include/sm/psci.h
core/arch/arm/plat-rockchip/psci_rk322x.c
core/arch/arm/sm/psci.c

In the commit 732fc43(core: arm: psci: pass nsec ctx to psci), we have
done the job, but we forgot to follow it in the later commit 1d40eb8
(core: arm: sm: add PSCI system suspend), fix it in this patch.

core: arm: psci: pass nsec ctx to system_suspend

---

core/arch/arm/kernel/generic_entry_a32.S
core/arch/arm/kernel/generic_entry_a64.S
core/arch/arm/kernel/kern.ld.S
core/arch/arm/kernel/thread_a32.S
core/arch/arm/kernel/thread_a64.S
core/arch/arm/sm/pm_a32.S
core/arch/arm/sm/sm_a32.S
lib/libutils/ext/include/asm.S

To get a more fine grained selection of which area (init, paged,
unpaged) an assembly function is assigned do the equivalent of
-ffunction-sections but in assembly.
Some functions has to be in specific places in the binary for a
successful boot, link script is updated accordingly.
Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (QEMU v7/v8)

Keep assembly functions in separate sections

---

core/tee/tee_rpmb_fs.c

According to the GPD TEE Internal Core API specs, when creating
an existing persistent object without the overwrite flag, the OS
should return a TEE_ERROR_ACCESS_CONFLICT status.
This change fixes the RPMB FS layer. An effect of this correction
is that before this change, OS panicked TAs that requested such
forbidden object creation, as a TEE_ERROR_BAD_PARAMETERS return
value is considered by the API as an unexpected status.

core: fix access conflict status in rpmb fs that panics TA

---

core/arch/arm/pta/interrupt_tests.c
core/include/tee/tee_cryp_provider.h
core/lib/libtomcrypt/src/tee_ltc_provider.c
core/tee/fs_htree.c
core/tee/tee_cryp_utl.c
core/tee/tee_fs_key_manager.c
core/tee/tee_rpmb_fs.c
core/tee/tee_svc_cryp.c

Adds crypto_rng_add_entropy() and crypto_rng_read() replacing
struct prng_ops in crypto_ops.
It turns out that https://github.com/OP-TEE/optee_os/pull/1912 wasn't enough for https://github.com/OP-TEE/optee_os/pull/1856 to be compiled with 
```
CFG_CORE_SANITIZE_KADDRESS=y
CFG_WITH_PAGER=y
```
With this PR the init size becomes more reasonable.

Replace struct prng_ops with function interface

---

core/tee/tee_pobj.c
core/tee/tee_rpmb_fs.c
lib/libutee/arch/arm/utee_misc.c

calloc() takes number of entries as first argument, and size of entry
as a second.

tee: fix improper calloc usage

---

mk/aosp_optee.mk

so that other android projects could use OPTEE_BIN
as the dependency instead of the old BUILD_OPTEE_OS target.
Ths is workaround for the problem with following with aosp master:
external/optee_test/Android.mk: error: xtest: LOCAL_ADDITIONAL_DEPENDENCIES must only contain paths (not module names)
Reviewed-by: Victor Chong <victor.chong@linaro.org>
Tested by: Victor Chong <victor.chong@linaro.org> (hikey aosp)
Tested-by: Yongqin Liu <yongqin.liu@linaro.org> (hikey aosp master)
Signed-off-by: Yongqin Liu <yongqin.liu@linaro.org>

mk/aosp_optee.mk: define OPTEE_BIN for path of tee.bin

---

mk/checkconf.mk

In mv-if-changed(file1, file2), there is no need to check if file2
exists before trying to compare both files. Indeed, if file2 does not
exist, cmp -s will return non-zero and the second branch of the
conditional will be taken anyway.

build: simplify mv-if-changed

---

core/lib/libtomcrypt/src/encauth/ccm/ccm_process.c

Upstream commit 08dee2735956 ("fixes #323 ccm_process fails to process
input buffer longer than 256").
Link: https://github.com/libtom/libtomcrypt/pull/326

ltc: fix ccm_process() bug when input buffer is longer than 256 bytes

---

core/kernel/tee_ta_manager.c

Commit 2b07dcb97c5e ("core: avoid deadlocks caused by single-instance
TA") introduces a lock that allows only one single instance TA to be
executing at any time. While it does address the risk of deadlock that
can arise when several single instance TAs call each other, it also
puts a serious performance limitation on multi-core platforms, which
could otherwise execute several unrelated single instance TAs
simultaneously.
This commit makes the single instance lock optional. By setting
CFG_CONCURRENT_SINGLE_INSTANCE_TA=y, the lock is disabled and TAs are
allowed to run concurrently. In the future, we may implement a deadlock
detection algorithm; in the meantime, this simple solution should be
enough to cover the current use cases.
Signed-off-by: Jerome Forissier …

Add CFG_CONCURRENT_SINGLE_INSTANCE_TA

---

core/arch/arm/kernel/generic_boot.c
core/arch/arm/kernel/kern.ld.S
core/arch/arm/kernel/ree_fs_ta.c
core/arch/arm/kernel/user_ta.c
core/arch/arm/mm/tee_pager.c
core/arch/arm/pta/interrupt_tests.c
core/arch/arm/tee/init.c
core/crypto/crypto.c
core/crypto/sub.mk
core/include/crypto/aes-ccm.h
core/include/crypto/aes-gcm.h
core/include/crypto/crypto.h
core/include/tee/tee_cryp_provider.h
core/lib/libtomcrypt/src/tee_ltc_provider.c
core/sub.mk
core/tee/fs_htree.c
core/tee/tee_cryp_concat_kdf.c
core/tee/tee_cryp_hkdf.c
core/tee/tee_cryp_pbkdf2.c
core/tee/tee_cryp_utl.c
core/tee/tee_fs_key_manager.c
core/tee/tee_ree_fs.c
core/tee/tee_rpmb_fs.c
core/tee/tee_svc_cryp.c
documentation/crypto.md
documentation/porting_guidelines.md

This takes care of replacing the `crypto_ops` struct as requested in https://github.com/OP-TEE/optee_os/pull/1908
But this doesn't solve the problem of supplying AES-GCM from an OP-TEE internal implementation and AES-CCM from LTC. How can that be done? `core/tee/tee_svc_cryp.c` expects `crypto_authenc_*()` functions so those need to be provided somewhere, but not in LTC as `crypto_authenc_*()` implementation will use OP-TEE internal AES-GCM implementation further on.
One way forward could be:
1. Specify `crypto_aes_gcm_*()` and `crypto_aes_ccm_*()` in `core/include/crypto/aes-{g,c}cm.h`
2. Move the `crypto_authenc_*()` implementation to `core/crypto/crypto.c`, implemented by using the new functions above.
I suppose the best would be to solve the `crypto_authenc_*()` problem in this pull …

Replace crypto ops

---

.shippable.yml

For better test coverage, run xtest in QEMU with RPMB FS enabled.

ci: .shippable.yml: enable RPMB FS during "make check"

---

core/arch/arm/mm/mobj.c
lib/libutils/isoc/bget_malloc.c

cpu_spin_lock_xsave() returns exceptions state in uin32_t, not
in unsigned int.

optee: use correct type to hold exceptions state

---

.shippable.yml

We get random build failures with Shippable CI. First kind is [1]:
/bin/bash: out/arm-plat-imx/conf.mk.tmp: No such file or directory
core/core.mk:69: recipe for target 'out/arm-plat-imx/conf.mk' failed
make: *** [out/arm-plat-imx/conf.mk] Error 1
make: *** Waiting for unfinished jobs....
Second kind is [2]:
mkdir: cannot create directory 'out/arm-plat-ti/core': No such file or directory
mk/subdir.mk:151: recipe for target 'out/arm-plat-ti/core/ta_pub_key.c' failed
make: *** [out/arm-plat-ti/core/ta_pub_key.c] Error 1
make: *** Waiting for unfinished jobs....
Sometimes both bash and mkdir fail with 'No such file or directory' [3]
I cannot see any mistake in our Makefile or anything that could explain
these errors. I have opened a support request with Shippable [4].
In the mean time, let's …

ci: .shippable.yml: disable parallel build

---

core/arch/arm/kernel/wait_queue.c

avoid:
core/arch/arm/kernel/wait_queue.c: In function 'wq_wake_next':
core/arch/arm/kernel/wait_queue.c:155:7: error: 'wake_read' may be used uninitialized in this function [-Werror=maybe-uninitialized]
if (wqe->wait_read != wake_read)
When building with gcc 5.3.1

core: avoid warning in wq_wake_next()

---

core/arch/arm/tee/pta_socket.c

Adds flag TA_FLAG_CONCURRENT to PTA socket used by the socket
implementation. This avoids one TA blocking another unrelated TA both
doing socket operations.

core: pta_socket: add TA_FLAG_CONCURRENT

---

scripts/mem_usage.py

Fix the following error:
make mem_usage CROSS_COMPILE="ccache arm-linux-gnueabihf-"
...
GEN     out/arm-plat-vexpress/core/tee.mem_usage
Traceback (most recent call last):
File "./scripts/mem_usage.py", line 162, in <module>
main()
File "./scripts/mem_usage.py", line 94, in main
universal_newlines=True)
File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
restore_signals, start_new_session)
File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'ccache arm-linux-gnueabihf-readelf'
core/arch/arm/kernel/link.mk:255: recipe for target 'out/arm-plat-vexpress/core/tee.mem_usage' failed
make: *** [out/arm-plat-vexpress/core/tee.mem_usage] Error 1
Signed-off-by: Jerome …

mem_usage.py: fix error with ccache

---

core/lib/libtomcrypt/src/pk/dsa/dsa_import.c

Upstream commit 1e260eeaae43 ("fir coverity finding: dsa_import double
free").
Fixes: https://github.com/OP-TEE/optee_os/issues/1962

core: ltc: fix double free in dsa_import()

---

core/tee/tee_fs_rpc.c

Avoid the potential memory leak after early return.

---

core/arch/arm/kernel/ree_fs_ta.c

ta_open() relies on the local variable shdr to be NULL unless it's a valid
pointer. alloc_and_copy_shdr() can in one code path update shdr and then
free it before returning.
The fix is in alloc_and_copy_shdr() to only set the returned shdr once
the pointer is to be returned.
Fixes: https://github.com/OP-TEE/optee_os/issues/1968

core: fix potential double free in ta_open()

---

core/lib/libfdt/fdt.c

Upstream commit d0b3ab0a0f46 ("libfdt: Fix undefined behaviour in
fdt_offset_ptr()").
Using pointer arithmetic to generate a pointer outside a known object is,
technically, undefined behaviour in C.  Unfortunately, we were using that
in fdt_offset_ptr() to detect overflows.
To fix this we need to do our bounds / overflow checking on the offsets
before constructing pointers from them.
Fixes: https://github.com/OP-TEE/optee_os/issues/1967

libfdt: fix undefined behaviour in fdt_offset_ptr()

---

core/drivers/imx_wdog.c

The registers's base address are 16bytes aligned, so read32/write32
should be replaced with read16/write16.

core: drivers: imx_wdog: fix register access

---

README.md
documentation/images/green.svg
documentation/images/orange.svg
documentation/images/red.svg

Since there are some platforms where we haven't heard from the maintainers for a while. I think it would be good to indicate what the current status is on our platforms. This could also be used for releases also. I.e., instead of writing a [Tested On](https://github.com/OP-TEE/optee_os/blob/master/CHANGELOG.md#tested-on) section in CHANGELOG.md we could just refer to the readme.md with a link pointing to a tagged (release tagged) version.
The review tool in GitHub doesn't seem to render the icons in the preview. So if you want to see the rendered version correctly, then head to my branch instead.
https://github.com/jbech-linaro/optee_os/blob/maintenance_icons/README.md

[RFC] Icons for telling the status of our platforms

---

core/crypto/crypto.c

Although _CFG_CRYPTO_WITH_CIPHER=n does not seem to be a valid
configuration (both the REE and RPMB FS use AES and at least one has to
be enabled currently), fix build errors triggered by:
make _CFG_CRYPTO_WITH_CIPHER=n \
out/arm-plat-vexpress/core/crypto/crypto.o

core/crypto/crypto.c: fix compile errors when _CFG_CRYPTO_WITH_CIPHER=n

---

core/arch/arm/kernel/ree_fs_ta.c
core/arch/arm/kernel/secstor_ta.c
core/arch/arm/kernel/sub.mk
core/arch/arm/pta/secstor_ta_mgmt.c
core/arch/arm/pta/sub.mk
core/crypto/signed_hdr.c
core/crypto/sub.mk
core/include/kernel/refcount.h
core/include/signed_hdr.h
core/include/tee/tadb.h
core/include/tee/tee_svc_storage.h
core/kernel/refcount.c
core/kernel/sub.mk
core/sub.mk
core/tee/fs_htree.c
core/tee/sub.mk
core/tee/tadb.c
core/tee/tee_svc_storage.c
lib/libutee/include/pta_secstor_ta_mgmt.h
lib/libutils/ext/include/atomic.h
lib/libutils/ext/include/compiler.h
mk/config.mk
scripts/sign.py
ta/arch/arm/link.mk

This pull request introduces bootstrap TAs which can completely replace the current TAs depending on how we'd like to progress.
I see some ways forward:
1. Add this as yet another method of loading TAs
2. Replace the current way of loading TAs from supplicant with this
3. Wait until we have some security domain in place before starting to retire/deprecate 1
Doing 2 (or 3) doesn't mean that we have to remove the old code, we could just make it optional. But we'd change our current test setup to only install TAs via bootstrap TAs (or via a security domain).
Bootstrap TA are basically only the solution to the chicken and egg problem for security domains. Next step would be to introduce a security domain.

[RFC] Bootstrap ta

---

.shippable.yml

Caching was inadvertently broken by commit 4af6a141f612 ("ci:
shippable: run only platform builds"). I wrongly assumed that Shippable
saves the ccache directory by default (~/.ccache), but is not the case.
Only $SHIPPABLE_BUILD_DIR is saved, i.e., the checked out project
(/root/src/github.com/OP-TEE/optee_os).
Fix that by giving the ccache directory in cache_dir_list.

ci: shippable: configure caching properly for ccache

---

.travis.yml

Build with GCC 4.9 in order to detect compile errors specific to that
version of the compiler, such as:
core/tee/tadb.c:593:15: error: missing braces around initializer [-Werror=missing-braces]
const struct tadb_entry null_entry = { 0 };
^
core/tee/tadb.c:593:15: error: (near initialization for ‘null_entry.prop’) [-Werror=missing-braces]

ci: .travis.yml: use GCC 4.9

---

core/arch/arm/kernel/trace_ext.c
lib/libutils/ext/trace.c
scripts/symbolize.py
ta/arch/arm/user_ta_header.c

So this is a continuation of what we have discussed [here](https://github.com/jbech-linaro/optee_os/commit/0d3305af8741e88f08cbc36d955781d273ea6ff8). I've kept commit message etc the same, I'm going to update then we have agreed on the output and when I'm about to squash it. I've also fixed the symbolize.py script, but I couldn't see that there was any need to update the documentation about it(?).

Trace improvments

---

.shippable.yml
MAINTAINERS.md
README.md
core/arch/arm/plat-poplar/conf.mk
core/arch/arm/plat-poplar/hi3798cv200.h
core/arch/arm/plat-poplar/main.c
core/arch/arm/plat-poplar/platform_config.h
core/arch/arm/plat-poplar/sub.mk

poplar: Add initial support

---

core/tee/tee_svc.c
lib/libutee/tee_api_property.c

In 'ta_props' in ta/arch/arm/user_ta_header.c properties tagged as
USER_TA_PROP_TYPE_BOOL are assigned a pointer to a bool, but is in the
rest of the code handled as if it was a pointer to a uint32_t. This
works as long as a bool is four bytes, with certain compilers the size
of a `bool` is 1 instead leading to errors.
TA properties can be supplied via the define
TA_CURRENT_TA_EXT_PROPERTIES. The pattern used in
ta/arch/arm/user_ta_header.c is likely copied when assigning properties
via TA_CURRENT_TA_EXT_PROPERTIES.
This patch is fixing the assumption that the size of a `bool` is the
same as the size of a `uint32_t` by changing all handling of
USER_TA_PROP_TYPE_BOOL to base it on the type `bool` instead of
`uint32_t`.

Fix USER_TA_PROP_TYPE_BOOL handling

---

core/kernel/tee_ta_manager.c

when a single instance TA is not muti-session, it 's allowed to open a
new session only if the TA context reference is not zero, no matter
whether it is keepalive or not.

core: fix the reopen session condition for single instance TA

---

mk/config.mk

The configuration variable CFG_TEE_DRV_DEBUGFS was used by an older
version of the older OP-TEE linux driver, before commit 724298b6e425
("Linux driver refactoring") [1]. It is now obsolete, so remove it.
The text explaining how to set log levels is also reworded slightly.
Link: [1] https://github.com/OP-TEE/optee_linuxdriver/commit/724298b6e425

mk/config.mk: remove obsolete text and clarify usage of log levels

---

core/arch/arm/arm.mk
core/arch/arm/sm/sm_a32.S

* If built with internal secure monitor, invalidates branch predictor
on non-secure entry.
* If built for usage with ARM-TF, invalidates branch predictor on
entry.
Fixes CVE-2017-5715

core: arm32: invalidate branch predictor

---

core/arch/arm/mm/core_mmu_lpae.c

Fixes: 4cc2823eb25c ("core: user mode translation table")
Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (Hikey)

core: lpae: zero initialize all l1 tables

---

core/arch/arm/kernel/ree_fs_ta.c
core/arch/arm/pta/secstor_ta_mgmt.c
core/crypto/aes-gcm.c
core/crypto/crypto.c
core/include/crypto/aes-ccm.h
core/include/crypto/aes-gcm.h
core/include/crypto/crypto.h
core/lib/libtomcrypt/src/tee_ltc_provider.c
core/tee/fs_htree.c
core/tee/tadb.c
core/tee/tee_cryp_concat_kdf.c
core/tee/tee_cryp_hkdf.c
core/tee/tee_cryp_pbkdf2.c
core/tee/tee_cryp_utl.c
core/tee/tee_fs_key_manager.c
core/tee/tee_rpmb_fs.c
core/tee/tee_svc_cryp.c

The crypto api in crypt.h doesn't match the crypt api supplied by mbedtls very well with regards to how the crypto context is managed.
This pull request tries to address that by letting moving management of the crypto context into the api provided by crypt.h.

Crypto alloc

---

core/arch/arm/kernel/tz_ssvce_pl310_a32.S

According to PL310 TRM:
Atomic operations:
The following are atomic operations:
Clean Line by PA or by Set/Way
Invalidate Line by PA
Clean and Invalidate Line by PA or by Set/Way
Cache Sync.
These operations stall the slave ports until they are complete.
When these registers are read, bit [0], the C flag, indicates that
a background operation is in progress. When written, bit 0 must be
zero.
So write 1 to sync register is not correct.

arm: pl310: fix cache sync

---

core/arch/arm/kernel/thread_a64.S

Fixes compile errors
out/arm-plat-hikey/core/arch/arm/kernel/thread_a64.o: In function `el0_sync_abort':
/home/bla/optee_os/core/arch/arm/kernel/thread_a64.S:778:(.text.el0_sync_abort+0xf4): relocation truncated to fit: R_AARCH64_TSTBR14 against `.text.thread_vect_table'
out/arm-plat-hikey/core/arch/arm/kernel/thread_a64.o: In function `elx_fiq':
/home/bla/optee_os/core/arch/arm/kernel/thread_a64.S:949:(.text.elx_fiq+0x9c): relocation truncated to fit: R_AARCH64_TSTBR14 against `.text.thread_vect_table'
make: *** [out/arm-plat-hikey/core/tee.elf] Error 1
experienced with some gcc 4.9 compiler
Fixes: https://github.com/OP-TEE/optee_os/issues/2067

core: thread_a64.S: fix gcc 4.9 compile error

---

core/arch/arm/kernel/thread_a32.S

Fixes exception return from FIQ and SVC handlers to not return via
abort mode as we under some circumstances may return to abort mode.
Fixes 5726c56d45ba ("core: thread: fix exception return")

core: thread: fix exception return

---

core/arch/arm/include/kernel/misc.h
core/arch/arm/kernel/generic_entry_a32.S
core/arch/arm/kernel/generic_entry_a64.S
core/arch/arm/kernel/misc_a32.S
core/arch/arm/kernel/misc_a64.S
core/arch/arm/mm/core_mmu_lpae.c
core/arch/arm/plat-sunxi/entry.S
core/arch/arm/plat-sunxi/smp_boot.S
core/arch/arm/plat-ti/a9_plat_init.S
core/arch/arm/sm/pm_a32.S

strange that we did saw issues before...
maybe i missed something.
The proposed fixes were found from a review of the use of `get_core_pos()` in optee_os.

core: add missing interrupt masking in get/set user map for LPAE

---

core/arch/arm/arm.mk
core/arch/arm/kernel/thread_a32.S

This pull request is done on top of https://github.com/OP-TEE/optee_os/pull/2048 to avoid unnecessary conflicts when finally merging everything. The commit to review here is `
core: arm32: thread: invalidate branch predictor`.

Cve 2017 5715 2

---

core/arch/arm/sm/sm_a32.S

Fixes assembly error:
AS out/arm/core/arch/arm/sm/sm_a32.o
core/arch/arm/sm/sm_a32.S: Assembler messages:
core/arch/arm/sm/sm_a32.S:354: Error: invalid constant (c08) after fixup
core/arch/arm/sm/sm_a32.S:356: Error: invalid constant (c09) after fixup
core/arch/arm/sm/sm_a32.S:358: Error: invalid constant (c0e) after fixup
core/arch/arm/sm/sm_a32.S:363: Error: invalid constant (c0f) after fixup
mk/compile.mk:146: recipe for target 'out/arm/core/arch/arm/sm/sm_a32.o' failed
Fixes: 2ac6322d1ab1 ("core: arm32: sm: runtime selection of spectre workaround")

core: arm32: sm_a32.S: fix assembly errors

---

core/arch/arm/include/mm/core_mmu.h

Suggested-by: Etienne Carriere <etienne.carriere@linaro.org>

Define register_sdp_mem() only when CFG_SECURE_DATA_PATH is defined

---

core/arch/arm/pta/sdp_pta.c
core/arch/arm/pta/sub.mk
lib/libutee/include/sdp_pta.h

Hello,
Secure firmware ta needs physical address for creating pagetable; add a pta for retrieve physical address for it. There is restriction checking in pta which make sure only secure firmware could access this pta.

pta: add pta for retrieve sdp physcial address

---

core/drivers/tzc380.c
core/include/drivers/tzc380.h

1. Do not touch reserved bits for region 0.
2. Export more API for flexible configuration.

Tzc update

---

core/arch/arm/include/arm32.h
core/arch/arm/include/arm32_macros.S
core/arch/arm/plat-imx/conf.mk
core/arch/arm/sm/sm_a32.S

There is an property "arm,cpu-registers-not-fw-configured" in Linux side,
that could workaround the issue that firmare initialize CNTVOFF.
But if use that property, virtualization support will be break in linux.
Also without CNTVOFF or that property no defined, kernel could not
boot up on i.MX7D with two cores.
So we init CNTVOFF in OP-TEE to make kernel work well.
I did not find a better place to do this, so add it in sm_init and configure SCR.NS.

arm: init CNTVOFF

---

core/arch/arm/pta/secstor_ta_mgmt.c

If signature check failed, we need to close tadb session first.
This fixes #2095

secstor: fix memory leak in install_ta()

---

core/arch/arm/include/kernel/pseudo_ta.h
core/arch/arm/include/kernel/user_ta.h
core/arch/arm/kernel/pseudo_ta.c
core/arch/arm/kernel/user_ta.c
core/include/kernel/tee_ta_manager.h
core/kernel/tee_ta_manager.c

Commit 99f969dd6c99 ("core: fine grained tee_ta_mutex locking") fixes a
deadlock that can occur if a TA is loaded while not enough page tables
are available in pgt_cache to map the context. But it also splits up a
big critical section and there's obviously a few hidden dependencies
towards tee_ta_mutex causing stability issues with the pager. Running
'while xtest 1013; do true; done' in AArch64 with at least three
threads running in parallel will ultimately fail.
Therefore, revert the fine grained locking commit until the race
conditions are sorted out.
Reported-by: Jens Wiklander <jens.wiklander@linaro.org>

Revert "core: fine grained tee_ta_mutex locking"

---

core/tee/tee_svc.c

GlobalPlatform TEE Internal Core API v1.1.2 section 4.9.4 states that
parameters of type *_MEMREF_* can have memref.buffer == NULL, provided
that memref.size is zero.
The corresponding test in tee_svc_copy_param() is backwards, so reverse
it.
Reported-by: Kevin Peng <kevinp@marvell.com>
Link: https://github.com/OP-TEE/optee_os/issues/2105
Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (QEMU)

core: fix handling of NULL memory references by Internal Client API

---

core/arch/arm/include/arm32.h
core/arch/arm/kernel/generic_entry_a32.S
core/arch/arm/kernel/thread_a32.S
core/arch/arm/sm/sm_a32.S

Enables ACTLR_CA8_ENABLE_INVALIDATE_BTB (ACTLR[6]) in generic boot if
compiled with CFG_CORE_WORKAROUND_SPECTRE_BP or
CFG_CORE_WORKAROUND_SPECTRE_BP_SEC and the cpu is discovered to be
Cortex-A8.
Fixes CVE-2017-5715

arm32: enable ACTLR_CA8_ENABLE_INVALIDATE_BTB

---

Makefile

By default if nothing is specified OP-TEE is built keeping the output under
the directory "out" in the source tree. With this patch the cscope database
will not include those files.

cscope: skip in tree out directory

---

lib/libutils/isoc/bget.c
lib/libutils/isoc/bget.h
lib/libutils/isoc/bget_malloc.c

Hi! 
This PR is needed mostly for virtualization support. It moves all bget state into struct, so we can use multiple bget allocators simultaneously.

bget: support multiple allocators

---

core/include/tee/fs_htree.h
core/tee/fs_htree.c
core/tee/tee_ree_fs.c

ree_fs_truncate() sync

---

lib/libutils/ext/include/compiler.h

__packed, __noreturn, __unused and __used are already defined in bionic
so avoid redefining them here.

compiler.h: Avoid bionic macro redefinition

---

core/arch/arm/mm/mobj.c

On user TA crash or panic the core may dump the TA state
among which the physical address of the memory area mapped
in the TA space which are referenced by the mobj layer.
Therefore the get_pa method for such mobj shall have a
KEEP_PAGER constraint.
This change adds such constraint for static shm and registered
shm memory objects.

core: add pager constraint on mobj get_pa method

---

core/arch/arm/include/sm/optee_smc.h

In order to support multiple guests, OP-TEE should be able to track
guest lifecycle. Idea is that hypervisor informs OP-TEE when it
wants to create a new virtual machine. OP-TEE allocates resources
for it or returns an error, if there are not enough resources available.
When virtual machine is being destroyed - OP-TEE frees any resources
that was allocted previously.

smc: extend protocol to support virtualization

---

Makefile
core/core.mk

It is the only value used for now. No other value works, not even
`aarch64`.

Force ARCH to arm

---

core/kernel/tee_ta_manager.c

TEE_ERROR_SHORT_BUFFER is unlikely to be an unexpected error
code returned by a trusted application or a core service. Therefore
this change prevents debug "Error: " in short buffer case at completion
the the invoke_command request.

core: lower debug verbosity on short buffer errors

---

core/crypto/crypto.c
core/lib/libtomcrypt/src/tee_ltc_provider.c

Update the crypto_*_free_ctx() functions so that they do nothing when
passed a NULL ctx. Allows for easier error handling.

core: crypto.c: crypto_*_free_ctx() stubs should allow NULL context

---

mk/checkconf.mk

Some build environment (i.e yocto) may use build directory path that
include a '+' character. This change allows such '+' character(s) to be
replaced with a '_' character in the conf.h macro.

make config: allow '+' character in file paths

---

mk/checkconf.mk

There is no need to compute a guard string when generating the CMake
configuration file. Obviously the line was mistakenly copied from
check-conf-h, so remove it.

Remove unused guard string in check-conf-cmake

---

core/arch/arm/include/mm/core_mmu.h
core/arch/arm/mm/core_mmu.c
core/arch/arm/mm/core_mmu_lpae.c
core/arch/arm/mm/core_mmu_private.h
core/arch/arm/mm/core_mmu_v7.c

This is the first part #2088 with squashed and rebased patches.
Basically, it initializes MMU in single place both for v7 and lpae, by using primitives from core_mmu_v7.c and core_mmu_lpae.c

Rework MMU initialization.

---

mk/config.mk
ta/mk/ta_dev_kit.mk
ta/ta.mk

In order to use the memory leak detection code, a user-mode TA needs
two things:
- A version of libutils.a that was built with malloc debug code. This
is taken care of by ta/ta.mk which sets ENABLE_MDBG=1 when
CFG_TEE_TA_MALLOC_DEBUG is 'y'.
- The proper declarations for malloc(), mdbg_malloc(), mdbg_check()
etc. in the header files when the TA is built. This patch adds the
missing definition of ENABLE_MDBG when CFG_TEE_TA_MALLOC_DEBUG is 'y'.
In addition, the usage of CFG_TEE_TA_MALLOC_DEBUG and
CFG_TEE_CORE_MALLOC_DEBUG is better documented in mk/conf.mk.

ta_dev_kit.mk: define ENABLE_MDBG when CFG_TEE_TA_MALLOC_DEBUG is set

---

core/arch/arm/mm/core_mmu.c

Since recent changes in the MMU the 32bit descriptor mode now allows
the map different memory using different entries in the same level2
MMU table. In the old days, the non-LPAE layer failed to share such
level2 table. This change removes the now useless constraint.

core 32bit mmu: remove constraint on reuse of xlat tables

---

core/arch/arm/kernel/kern.ld.S

Stop using the PROVIDE() keyword in the linker script. The current usage
causes problems like:
out/arm-plat-vexpress/core/kern.ld:168: undefined symbol
`__asan_map_end' referenced in expression
make: *** [out/arm-plat-vexpress/core/tee.elf] Error 1
when compiled with certain flags and compilers.

core: arm: kern.ld.S: stop using PROVIDE()

---

core/arch/arm/mm/core_mmu_v7.c

The value of CONTEXTIDR is initially undefined, initialize it with a
sane value.

core: armv7: core_init_mmu_regs() init contextidr

---

scripts/checkpatch_inc.sh

checkpatch.pl produces false errors when given files with inline
assembly [1]. It is best to skip those files entirely.
Link: [1] https://travis-ci.org/OP-TEE/optee_os/builds/347435939#L2115

checkpatch_inc.sh: exclude files with inline assembly

---

core/arch/arm/include/kernel/generic_boot.h
core/arch/arm/kernel/generic_boot.c
core/arch/arm/kernel/generic_entry_a32.S
core/arch/arm/plat-imx/pm/psci.c
core/arch/arm/plat-rockchip/psci_rk322x.c
core/arch/arm/plat-vexpress/main.c

The PSCI specification requires the 'context_id' parameter to be passed in r0 when the core jumps to normal world. Some OS's require this parameter.
Tested on IMX6Quad and IMX7Dual.
Signed-off-by: Jordan Rhee <jordanrh@microsoft.com>

Fix psci_cpu_on() to use context parameter

---

core/arch/arm/crypto/aes-gcm-ce.c

aes-gcm-ce.c is a internal GCM and it should be not relative with tomcrypt anymore.
So remove tomcrypt.h from it.
Signed-off-by: Edison Ai <edison.ai@arm.com>

core/crypto/aes-gcm-ce.c:Remove unused included header file

---

core/arch/arm/include/kernel/generic_boot.h
core/arch/arm/kernel/generic_boot.c
core/arch/arm/plat-imx/pm/psci.c
core/arch/arm/plat-rockchip/psci_rk322x.c
core/arch/arm/plat-vexpress/main.c

Without a memory barrier there is no guarantee that the write to `ns_entry_contexts` will be observed by other cores.

core: insert memory barrier after write to ns entry context

---

.travis.yml

Due to recent changes in manifest.git and build.git for buildroot
support,  it is not possible to build with GCC4.9 anymore. One has
to use the toolchain installed by "make toolchains".
Since we want to keep GCC4.9 for now [1], let's revert to an older,
stable version of the source tree, except for the optee_* projects
which we keep at the tip of their master branch.
[1] Commit 148ea708383e ("ci: .travis.yml: use GCC 4.9")

ci: .travis.yml: clone stable version (3.0.0)

---

core/arch/arm/plat-imx/a7_plat_init.S

Implement get_core_pos for A7.
According the DIT0017f_Cortex-A7_Integration_Manual_r0p5,
If the system contains only a single multiprocessor device,
tie all the CLUSTERID[3:0] to HIGH.
To i.MX family which use A7 core, there is no one contains
more that 4 cores. on i.MX7ULP, there is only one core.
So implement get_core_pos to avoid get wrong cpu id.

core: imx: a7_plat_init: implement get_core_pos

---

.travis.yml

Now that build files support GCC 4.9 [1] and "make check" supports the
buildroot environment [2], revert commit 793884e19284
("ci: .travis.yml: clone stable version (3.0.0)") and set
COMPILE_LEGACY=y to instruct the build system to download and use the
legacy compiler (gcc-linaro-4.9-2015.02-3-x86_64_arm-linux-gnueabihf).
Link: [1] https://github.com/OP-TEE/build/pull/239
Link: [2] https://github.com/OP-TEE/build/pull/240

ci: .travis.yml: track latest manifest again

---

MAINTAINERS
README.md

Mediatek MT8173 EVB is not used on a regular basis for OP-TEE by anyone
we know, so mark is as Orphan. I'm not getting rid of the platform code
because is is small and quite trivial, so there is not much to be
gained by removing it.

MAINTAINERS: mark Mediatek MT8173 EVB as Orphan

---

core/tee/tee_svc_cryp.c

Fixes problem with possibly leaking uninitialized stack content via
tlen.
Fixes: https://github.com/OP-TEE/optee_os/issues/2214

core: syscall_authenc_enc_final() initialize tlen

---

Notice.md
README.md
documentation/extensions/crypto_concat_kdf.md
documentation/extensions/crypto_hkdf.md
documentation/extensions/crypto_pbkdf2.md
documentation/extensions/extensions.md
documentation/globalplatform_api.md

While reading back current documentation I found deprecated info. Here is an update proposal.
* OP-TEE currently target ARM Cortex-A with TZ, not all ARM TZ HW.
* Reference the GPD TEE Internal Core API v1.1 instead of the older
GPD TEE Internal API v1.0. Note: sole reference to the "Internal
core API v1.1" missed an uppercase 'C'.
* Remove reference to the deprecated optee_linuxdriver git repository.
These updates lead to few other changes, especially adding references
to other available documentation where accurate.

doc: update documentation against out dated information

---

core/arch/arm/include/kernel/pseudo_ta.h
core/arch/arm/include/kernel/user_ta.h
core/arch/arm/kernel/elf_load.c
core/arch/arm/kernel/pseudo_ta.c
core/arch/arm/kernel/user_ta.c
core/arch/arm/pta/gprof.c
core/arch/arm/pta/se_api_self_tests.c
core/kernel/tee_ta_manager.c
core/tee/tee_svc.c
lib/libutee/arch/arm/gprof/gmon.h
lib/libutee/include/user_ta_header.h
mk/config.mk
ta/arch/arm/user_ta_header.c

Current optee mandates these but does not support their misconfiguration.
This change insures the required flags are in place.

ta: TA_FLAG_EXEC_DDR and TA_FLAG_USER_MODE are implicit in optee

---

core/lib/libtomcrypt/src/ciphers/aes_modes_armv8a_ce_a32.S

Commit 628a9a10ca36 ("ltc: ctr: improve performance") reveals a bug in
the Aarch32 accelerated crypto code (AES CTR mode), which causes xtest
9159 to fail with some invalid buffer content: encrypting 96 bytes of
data in one pass does not yield the same result than encrypting 3 * 32
bytes. The problem is fixed by adding a missing counter increment in
ce_aes_ctr_encrypt().
Fixes: 9ff4f2ccc026 ("arm32: AES using ARMv8-A cryptographic extensions")
Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (HiKey960)

core: crypto: arm32: add counter increment in ce_aes_ctr_encrypt()

---

core/arch/arm/include/kernel/thread.h
core/arch/arm/include/smccc.h
core/arch/arm/kernel/thread.c
core/arch/arm/kernel/thread_a32.S
core/arch/arm/kernel/thread_a64.S
core/arch/arm/kernel/thread_private.h
core/arch/arm/mm/tee_mmu.c

SMCCC_ARCH_WORKAROUND_1

---

core/arch/arm/plat-ti/a9_plat_init.S

The resume path may need to re-setup the GIC and enable non-secure
VFP access. These are cleared in some suspend paths and so should
be restored.

plat-ti: Restore NSACR and GIC context on resume

---

scripts/checkpatch_inc.sh

```
If a commit changes only paths that are filtered out by $_CP_EXCL, thus
making the diff empty, 'git format-patch -1 <sha1>' will show the parent
commit instead. As a result, checkpatch.sh will check the wrong commit.
Several things are needed to fix the issue:
1. When calling 'git format-patch', specify the commit ID as a range
(<sha1>^..<sha1>) rather than as a single revision with a maximum count
(-1 <sha1>). This avoids showing the wrong commit.
2. Show the commit message then the diff in two steps, because the
above syntax will not print anything if the diff happens to be empty.
3. Tell checkpatch.pl to ignore the "not a unified diff" error which
is triggered if the commit log is not followed by a diff.
Link: https://travis-ci.org/OP-TEE/optee_os/builds/367058383#L2199-L2204 …
```

checkpatch_inc.sh: fix case of empty commit due to path filtering

---

lib/libutee/tee_api_operations.c

With this change, a single call to TEE_AEEncryptFinal() checks both
the output data buffer size and the tag buffer size and return
TEE_ERROR_SHORT_BUFFER with both expected size if at least one
of the provided buffer is too short.
Before this change caller may need to call twice TEE_AEEncryptFinal()
in the right order to get the output buffers sizes, first for the
output data size then for the tag data size.

libutee: out and tag buffer can be too short in TEE_AEEncryptFinal

---

core/arch/arm/include/arm64_macros.S
core/arch/arm/kernel/generic_entry_a64.S

Fixes the following linker errors which happens when adding a big
global array of data (~200 KB):
.../generic_entry_a64.o: In function `_start`:
.../generic_entry_a64.S:95:(.text._start+0x30): relocation truncated to fit: R_AARCH64_ADR_PREL_LO21 against symbol `__bss_start` defined in .bss.__malloc_spinlock section in all_objs.o
.../generic_entry_a64.S:96:(.text._start+0x34): relocation truncated to fit: R_AARCH64_ADR_PREL_LO21 against symbol `__bss_end` defined in .bss.__malloc_spinlock section in all_objs.o
.../generic_entry_a64.o: In function `clear_bss`:
.../generic_entry_a64.S:108:(.text._start+0x84): relocation truncated to fit: R_AARCH64_ADR_PREL_LO21 against symbol `__text_start` defined in .bss.__malloc_spinlock section in all_objs.o …

core: arm64: use 33-bit pc-relative addressing to allow bigger data sections

---

core/arch/arm/mm/core_mmu_lpae.c

SOC has configurable core settings (e.g., Juno) does not
take core-0 as primary core. Copying mapping table of core-0
to other cores causes boot failure on such configured SOC.
Fix this problem by taking mapping table of actual primary
core as copy source.
Signed-off-by: Ken Liu <ken.liu@arm.com>

mmu: fix boot failure on specified SOC

---

core/arch/arm/plat-ls/conf.mk
core/arch/arm/plat-ls/platform_config.h

Remove `CFG_DDR_TEETZ_RESERVED_START/_SIZE:` internal to platform.
Remove `CFG_PUB_RAM_SIZE`, use `TEE_SHMEM_SIZE` instead.
Remove useless definition of `DDR_PHYS_START`, `DDR_SIZE`, `DRAM0_BASE/_SIZE`,
`CFG_DDR_START/_SIZE`.
@@b49020 and @pangupta,
This P-R removes `CFG_` definitions from plat-lsplatform_config.h file.
Could you have a look and report comments or ack the changes.
regards

plat-ls: move some CFG_'s from platform_config.h to conf.mk

---

core/arch/arm/plat-ti/conf.mk
core/arch/arm/plat-ti/platform_config.h

@glneo,
This P-R is small changes. It removes `CFG_` definitions from **plat-ti/platform_config.h** file.
Could you please ack the changes or report issues or comments you would like to share?
regards

plat-ti: move some CFG_'s from platform_config.h to conf.mk

---

core/arch/arm/plat-zynq7k/conf.mk
core/arch/arm/plat-zynq7k/platform_config.h

@yanyan-wrs,
Please, could you have a look a this P-R. It removes `CFG_` definitions from plat-zynq7k/platform_config.h file.
Could you please report any issue or comment you may address, or ack the changes if you are happy with it.
regards

plat-zynq7k: move some CFG_'s from platform_config.h to conf.mk

---

core/arch/arm/plat-vexpress/conf.mk

https://github.com/OP-TEE/manifest/pull/111 is needed for building on hosts with glibc >= 2.27. That PR causes a crash without this patch.
This has been tested on qemu with glibc 2.27 and 2.26 with and without https://github.com/OP-TEE/manifest/pull/111.
Fixes: https://github.com/OP-TEE/optee_os/issues/2291
Signed-off-by: illustris <rharikrishnan95@gmail.com>

Fix crash when bumping qemu to 2.12.0

---

core/arch/arm/pta/core_self_tests.c

Add a test that fails with GCC 4.9.4 (Linaro GCC 4.9-2017.01) [1]
Link: http://releases.linaro.org/components/toolchain/binaries/4.9-2017.01/arm-linux-gnueabihf/gcc-linaro-4.9.4-2017.01-x86_64_arm-linux-gnueabihf.tar.xz

core_self_tests:.c: add ADD_OVERFLOW() test

---

core/tee/tee_svc_storage.c

Fixes out of memory handling error in tee_svc_storage_read_head(). Prior
to this all errors from fops->read() was reported as
TEE_ERROR_CORRUPT_OBJECT leading to removal of the object even when the
real problem was temporary memory shortage. This patch reports
TEE_ERROR_OUT_OF_MEMORY from fops->read() correctly while translating
all other errors to TEE_ERROR_CORRUPT_OBJECT.
Fixes https://github.com/OP-TEE/optee_os/issues/2310

core: fix OOM handling in tee_svc_storage_read_head()

---

core/arch/arm/kernel/generic_boot.c
core/arch/arm/plat-ls/conf.mk
core/arch/arm/plat-ls/main.c

This is an alternate proposal to #2296 that uses generic code and a configuration option to initialize CNTFRQ on secondary cores.

Use common helper routines to initialize cntfrq on secondary cores

---

core/arch/arm/include/arm32.h
core/arch/arm/kernel/generic_entry_a32.S
core/arch/arm/plat-imx/conf.mk
core/arch/arm/plat-imx/imx_pl310.c
core/arch/arm/plat-imx/imx_pl310.h
core/arch/arm/plat-imx/imx_sip.h
core/arch/arm/plat-imx/sm_platform_handler.c
core/arch/arm/plat-imx/sub.mk

When Windows runs in normal world, it expects the PL310 to be initially
disabled. Windows then invokes SMCs to turn on the L2 cache.
@MrVan, this builds on #2036, but implements the Windows protocol for enabling the PL310.

plat-imx: implement PL310 SMC protocol

---

lib/libutils/ext/include/compiler.h

After commit 9a8117de1263 ("util: update fallback ADD_OVERFLOW() macro")
and commit ecdedc94e720 ("util: update fallback SUB_OVERFLOW() macro"),
the following macros are not used anymore. Remove them.
__INTOF_HALF_MAX_SIGNED(type)
__INTOF_MAX_SIGNED(type)
__INTOF_MIN_SIGNED(type)
__INTOF_MIN(type)
__INTOF_MAX(type)

util: remove unused macros

---

core/arch/arm/plat-ls/conf.mk
core/arch/arm/plat-ls/platform_config.h

Move default secure and non-secure Optee memory locations from
**platform_config.h** to conf.mk using header **generic_ram_layout.h**.

plat-ls: move to generic RAM layout

---

core/tee/fs_htree.c

Prior to this patch was the size of the meta data supplied as the size
of the pointer to meta data. With this patch the size is corrected to be
the size of meta  data itself.
Fixes: https://github.com/OP-TEE/optee_os/issues/2330
Fixes: 94a72998bc1d ("core: fs_htree: include meta in root hash")

core: htree: fix meta inclusion in root hash

---

core/arch/arm/kernel/user_ta.c

gcc7 failed to build with -Werror=format-truncation.
snprintf() with format "[%d]" can output 12 bytes maximum because
the range of the argument are from 1 to 10 bytes. Thus we need to
enlarge the desc buffer to 13 bytes to avoid this error.
Signed-off-by: Ying-Chun Liu (PaulLiu) <paulliu@debian.org>
> 
> CC out/arm-plat-sunxi/core/arch/arm/kernel/user_ta.o
> core/arch/arm/kernel/user_ta.c: In function ‘user_ta_dump_state’:
> core/arch/arm/kernel/user_ta.c:388:31: error: ‘%d’ directive output may be truncated writing between 1 and 10 bytes into a region of size 7 [-Werror=format-truncation=]
>    snprintf(desc, desc_size, "[%d]", idx);
>                                ^~
> core/arch/arm/kernel/user_ta.c:388:29: note: directive argument in the range [0, 2147483647]
>    snprintf(desc, …

core: fixed gcc 7 format-truncation errors

---

core/arch/arm/kernel/user_ta.c

tee_ta_init_user_ta_session() leaked allocated ELFs if
there was an error during initializastion.
-----
This fixes another portion of #2327

user_ta: free all ELFs in case of error

---

core/tee/tee_ree_fs.c

It is possible that one core will call ree_fs_close_primitive()
while another is calling ree_fs_read_primitive(). This patch
prevents this by putting ree_fs_close_primitive under mutex.

tee_ree_fs: avoid race condition between fh usage/closing

---

core/arch/arm/plat-vexpress/conf.mk

Increase CFG_TEE_CORE_NB_CORE to 4 for qemu_armv8a. This is to allow
more extensive tests of multithreading.

plat-vexpress: qemu v8: increase default core count

---

.travis.yml

COMPILE_LEGACY is not needed anymore since the legacy toolchain has been
deprecated in build.git [1].
Fixes the following compile error during the Travis CI build:
CC      /home/travis/optee_repo/build/../out/bios-qemu/bios/entry.o
gcc: warning: ‘-mcpu=’ is deprecated; use ‘-mtune=’ or ‘-march=’ instead
bios/entry.S:1:0: error: bad value (cortex-a15) for -mtune= switch
/*
^
Link: [1] https://github.com/OP-TEE/build/pull/263

ci: .travis.yml: download GCC 4.9 toolchain

---

core/arch/arm/plat-marvell/conf.mk
core/arch/arm/plat-marvell/platform_config.h

Move default secure and non-secure Optee memory locations from
platform_config.h to conf.mk using the generic_ram_layout.
Acked-by: Joakim Bech <joakim.bech@linaro.org>
Acked-by: Kevin Peng <kevinp@marvell.com>

plat-marvell: support generic Ram layout

---

core/arch/arm/pta/sub.mk
core/arch/arm/pta/system.c
lib/libutee/include/pta_system.h
mk/config.mk
ta/ta.mk

AOSP Keymaster implementations need to securely mix the provided entropy into
their pool, which also must contain internally-generated entropy from a
hardware random number generator.
Add PTA, which can add caller-provided entropy to the default RNG pool.

pta: add Pseudo TA for auxiliary crypto services

---

core/arch/arm/kernel/elf_load.c

I have encounterd the relocation type R_ARM_REL32 in a shared library,
so implement it.

core: arm: support relocation type R_ARM_REL32

---

ta/arch/arm/link_shlib.mk

The symbolic link and its target are in the same directory, so we need
to make sure that there is no relative path before the target filename.
The proper Make variable to use is therefore not $< but $(<F).
Fixes: 01b8b5ce011d ("TA dev kit: when building a shared library, create symlink with UUID")

TA dev kit: shared library: strip directory part

---

core/lib/libtomcrypt/src/ciphers/aes_armv8a_ce.c
core/lib/libtomcrypt/src/ciphers/aes_modes_armv8a_ce_a32.S
core/lib/libtomcrypt/src/ciphers/aes_modes_armv8a_ce_a64.S
core/lib/libtomcrypt/src/modes/ctr/ctr_encrypt.c

There is a problem with how the counter is incremented in our Aarch32
implementation of ce_aes_ctr_encrypt(). When 3 or more 16-byte blocks of
data are processed, the counter is incremented one time too many and
invalid data is produced as a result [1].
More generally, the way the counter is handled is quite convoluted. It is
incremented:
- In the generic LibTomCrypt code in ctr_encrypt_sub(),
- In the Crypto Extension glue layer in aes_ctr_encrypt_nblocks(),
- In the CE accelerated assembly code in ce_aes_ctr_encrypt().
We can easily get rid of the second one. We can also avoid always calling
the non-accelerated function on the first block of data.
This commit simplifies the C code to reflect the following rules:
- The core encryption functions (accelerated or not) should use the
counter …

core: crypto: cleanup and fix CE accelerated AES CTR

---

.shippable.yml

Try to speed up the Shippable CI by re-introducing parallel builds, which
were removed by commit c330283b4a00 ("ci: .shippable.yml: disable parallel
build") due to random build errors. Although the root cause was never
identified, there are reasons to believe that the issue may not be
reproducible anymore:
- The container environment has likely seen updates
- Commit 836334a163f9 ("ci shippable: set build directory identically for
all platforms") has modified the output paths, so a race condition on
directory creation seems quite unlikely to happen.

ci: shippable: enable parallel build

---

mk/aosp_optee.mk

Current use case is that xtest `os_test` TA depends on xtest `os_test_lib` TA (specifically libos_test.so) if `CFG_TA_DYNLINK=y`.
@liuyq please ack!

aosp_optee.mk: allow dependency builds for TAs

---

lib/libutee/arch/arm/user_ta_entry.c

Keepalive condition check should involve single instance flag too, since
the keepalive flag is meaningless if the TA is not single instance.
The same fix was done earlier in the core by commit f9a64f12b542 ("core:
fix the keepalive condition in close session").
Fixes: b7ea03ff2963 ("libutee: fix TA_CreateEntryPoint() and TA_DestroyEntryPoint()")
Signed-off-by: Andrew Gabbasov <andrew_gabbasov@mentor.com>

libutee: Fix the keepalive condition on last session close

---

core/lib/libtomcrypt/src/ciphers/aes_armv8a_ce.c
core/lib/libtomcrypt/src/ciphers/aes_modes_armv8a_ce_a64.S

Update the Aarch64 Crypto Extension accelerated CBC encryption/decryption
routines to the latest upstream implementation in the Linux kernel
(v4.17-rc7).
Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (HiKey960)
CC: Ard Biesheuvel <ard.biesheuvel@linaro.org>
Fixes: https://github.com/OP-TEE/optee_os/issues/2355

core: crypto: arm64 ce: update AES CBC routines

---

.shippable.yml
MAINTAINERS
README.md
core/arch/arm/plat-k3/conf.mk
core/arch/arm/plat-k3/main.c
core/arch/arm/plat-k3/platform_config.h
core/arch/arm/plat-k3/sub.mk

Add platform 'k3' for the TI K3 family. These are ARMv8 devices
and are quite different from our line of existing ARMv7 OMAP style
SoCs, hence the new platform.
Thanks,
Andrew

Add new platform for the TI K3 class of SoCs

---

core/arch/arm/kernel/generic_boot.c

Since the two addresses are already of type struct core_mmu_phys_mem, do not
divide by sizeof(struct core_mmu_phys_mem). This broke dynamic shared memory on
Juno r0, since nelem would be zero for two slots.
Tested on Juno r0.
Fixes: 2f82082fada3 ("core: add ddr overall register")
Signed-off-by: Rouven Czerwinski <rouven@czerwinskis.de>

core: don't divide by sizeof(*mem) for ddr nsec memory

---

.shippable.yml
MAINTAINERS
README.md
core/arch/arm/plat-stm32mp1/boot_api.h
core/arch/arm/plat-stm32mp1/conf.mk
core/arch/arm/plat-stm32mp1/link.mk
core/arch/arm/plat-stm32mp1/main.c
core/arch/arm/plat-stm32mp1/platform_config.h
core/arch/arm/plat-stm32mp1/reset.S
core/arch/arm/plat-stm32mp1/scripts/stm32image.py
core/arch/arm/plat-stm32mp1/sub.mk
core/drivers/stm32_uart.c
core/drivers/sub.mk
core/include/drivers/stm32_uart.h

Introduce platform stm32mp1 with board stm32mp1-stm32mp157c-ev1 based on stm32mp1 SoC family integrating Arm Cortex-A7 technology. In its default configuration, stm32mp1 OP-TEE core operates in a 256kB secure RAM with pager support enabled.
Platform flavor identifiers for the stm32mp1 do contain a hyphen, as the default stm32mp1-stm32mp157c-ev1. For optee_os to support hyphens inside platform flavor, the P-R includes a change in the core make script.

introduce platform stm32mp1

---

scripts/symbolize.py

With the introduction of dynamically linked TAs, symbolize.py may
encounter undefined (external) symbols when it parses the output of the nm
command looking for a symbol's address. The current code is not prepared
for that and will raise an exception. Fix the issue by ignoring lines that
have an unexpected format.

scripts/symbolize.py: ignore undefined symbols

---

.shippable.yml
.travis.yml
mk/compile.mk

Having -Werror turned on by default can be annoying, because not everyone
uses the same compiler, and different compiler versions have different
warnings.
Therefore, provide CFG_WERROR to turn it on instead. Enable CFG_WERROR in
the CI scripts because we still don't want warnings with the officially
supported compilers.

Do not set -Werror by default

---

core/include/drivers/tzc380.h

fix parameter type in function prototype

drivers: tzc380: fix tzc_configure_region api

---

scripts/symbolize.py

When a TA dump is processed, there is a list of ELF files just before the
call stack. However, when analyzing a TEE core dump, there is no such
list. Make sure this situation is properly handled to avoid displaying a
spurious message. This means fixing incorrect indentation in a
conditional.

scripts/symbolize.py: remove spurious output '(out/arm/core/tee.elf)'

---

core/arch/arm/tee/entry_std.c

Prior to this patch assign_mobj_to_param_mem() stored the offset
supplied with a non-contiguous buffer in mem->offs. Since that offset
already is stored inside the resulting MOBJ that offset is added twice.
This patch fixes this by initializing mem->offs to 0 instead.

core: fix offset in assign_mobj_to_param_mem()

---

core/drivers/imx_wdog.c

use WDT_WCR defined in watchdog specific imx_wdog.h
instead of  WCR_OFF defined in the platform imx-regs.h
Signed-off-by: Silvano di Ninno <silvano.dininno@nxp.com>
Acked-by: Jerome Forissier <jerome.forissier@linaro.org>

drivers: imx_wdog driver cleanup

---

core/arch/arm/arm.mk
core/arch/arm/include/arm32.h
core/arch/arm/include/arm32_macros.S
core/arch/arm/include/sm/sm.h
core/arch/arm/plat-imx/pm/cpuidle-imx7d.c
core/arch/arm/plat-imx/pm/imx7_suspend.c
core/arch/arm/plat-ti/main.c
core/arch/arm/sm/sm.c
core/arch/arm/sm/sm_a32.S

Introduce CFG_SM_NO_CYCLE_COUNTING to intitialize PMCR.DP to 1 and
save/restore PMCR on world switch. Similar to what is done in ARM TF
commit 3e61b2b54336 ("Init and save / restore of PMCR_EL0 / PMCR") [1].
The purpose of this is to (hopefully) make attacks such as CLKSCREW [2]
harder to mount, altough it is likely that timing information could be
obtained via other means.
Link: [1] https://github.com/ARM-software/arm-trusted-firmware/commit/3e61b2b54336
Link: [2] https://www.usenix.org/system/files/conference/usenixsecurity17/sec17-tang.pdf

core: arm: sm: initialize PMCR.DP to 1 and save/restore PMCR

---

core/drivers/hi16xx_rng.c

hw_get_random_byte() may be called from a context where mutexes are not
allowed. Use a spinlock instead.
Fixes: https://github.com/OP-TEE/optee_os/issues/2437

drivers: hi16xx_rng: replace mutex with spinlock

---

lib/libutee/include/tee_api_types.h
lib/libutils/ext/include/util.h

Uses inttypes.h over stdint.h on some .h files to be nice to U-boot.
Needed when compiling parts of the xtest regression suite embedded into U-boot since U-boot doesn't like stdint.h.

Use inttypes.h over stdint.h on some .h files

---

core/arch/arm/tee/arch_svc.c
core/arch/arm/tee/arch_svc_private.h

syscall_t is currently typedef'ed as TEE_Result (*)(void). It is used to
represent a pointer to any system call, in the syscall table for instance.
As such, the exact type behind syscall_t cannot reflect all the syscalls
since they have different prototypes. The current declaration with a
TEE_Result return type was probably chosen because it was a common
characteristic of all syscalls to return a TEE_Result.
However, this type causes compilation warnings with GCC 8.1:
core/arch/arm/tee/arch_svc.c:43:36: warning: cast between incompatible function types from ‘void (*)(long unsigned int)’ to ‘TEE_Result (*)(void)’ {aka ‘unsigned int (*)(void)’} [-Wcast-function-type]
#define SYSCALL_ENTRY(_fn) { .fn = (syscall_t)_fn }
^
core/arch/arm/tee/arch_svc.c:50:2: note: in expansion of macro …

core: define syscall_t as void (*)(void)

---

mk/config.mk

NOWERROR=1 has been made obsolete by commit beb065df6ee5 ("Do not set
-Werror by default"). Remove it.

mk/config.mk: remove obsolete comment

---

core/arch/arm/include/kernel/unwind.h

When CFG_TEE_CORE_LOG_LEVEL=0 to make, met build failure:
"
core/arch/arm/kernel/abort.c: In function '__print_stack_unwind_arm32':
core/arch/arm/kernel/abort.c:113:2: error: too many arguments to function 'print_stack_arm32'
print_stack_arm32(TRACE_ERROR, &state, exidx, exidx_sz, kernel_stack,
^~~~~~~~~~~~~~~~~
"

core: unwind: correct function args for print_stack_arm32/64

---

core/drivers/imx_wdog.c

The prefix `0` is removed in Linux Kernel upstream code,
so let's drop it to let wdog work.

imx: wdog: correct wdog_path

---

lib/libutils/ext/trace.c
mk/config.mk

If (D|E|I|F)MSG is called with foreign interrupts masked
we can report core ID. "?" will be printed instead, if
foreign interrupts aren't masked.
With this patch log looks like this:
D/TC:2 0 core_mmu_set_user_map:940 0xe181b88 0xeee8003
D/TC:? 0 __wq_rpc:40 wake  thread 1 0xe16f028 -3
D/TC:1   thread_handle_std_smc:612 a7: 2
D/TC:3 0 core_mmu_set_user_map:940 0x0 0x0
Where first digit shows core id and second - thread id.

[RFC]trace: print core id if in atomic context

---

.travis.yml

The QEMU test environment has recently been upgraded to use U-Boot
("qemu.mk: replace bios with u-boot" [1] and "default.xml: replace
bios_qemu_tz_arm with u-boot" [2]), which requires GCC 6 or newer.
Fixes the following CI build error:
*** Your GCC is older than 6.0 and is not supported
make[1]: *** [checkgcc6] Error 1
make: *** [u-boot] Error 2
Link: [1] https://github.com/OP-TEE/build/commit/248f5733bf29
Link: [2] https://github.com/OP-TEE/manifest/commit/2067ab3f9bbe

ci: travis: do not build with legacy compiler (GCC 4.9) anymore

---

core/arch/arm/pta/core_self_tests.c

This is invalid use of realloc, because it can cause memory leak.

core_self_tests.c: fix p1=realloc(p1) issue

---

core/arch/arm/kernel/generic_entry_a32.S
core/arch/arm/kernel/thread_a32.S
core/arch/arm/plat-ti/a9_plat_init.S

When compiling with -mcpu=cortex-a9, GCC 8.1 fails on the smc instruction:
$ make -s PLATFORM=stm CROSS_COMPILE32=~/work/toolchains/gcc-linaro-8.1.0-20180705-09_18_46-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-
core/arch/arm/kernel/thread_a32.S: Assembler messages:
core/arch/arm/kernel/thread_a32.S:44: Error: selected processor does not support `smc #0' in ARM mode
[snip]
mk/compile.mk:146: recipe for target 'out/arm-plat-stm/core/arch/arm/kernel/thread_a32.o' failed
make: *** [out/arm-plat-stm/core/arch/arm/kernel/thread_a32.o] Error 1
Use the '.arch_extension sec' directive to allow the assembler to emit
the instruction.

arm32: add assembly directive: .arch_extension sec

---

ta/mk/build-user-ta.mk

When processing the source files for an in-tree user TA (ta/*/user_ta.mk),
make sure not to insert a double slash in the object file path.
Fixes the following error:
$ make -s
$ make clean
CLEAN   out/arm-plat-vexpress
rmdir: failed to remove 'out/arm-plat-vexpress/ta/avb': No such file or directory
Makefile:98: recipe for target 'clean' failed
make: *** [clean] Error 1
The error results from the fact that we have two kinds of object files in
the in-tree TAs:
- The object files built from ta/*/user_ta.mk. For AVB, we have
out/arm-plat-vexpress/ta/avb//entry.o (notice the repeated slash).
- The object files that correspond to "specified source files", i.e.,
constructed from $(spec-out-dir) and $(spec-srcs). For AVB we have
out/arm-plat-vexpress/ta/avb/user_ta_header.o.
When "make clean" …

In-tree TAs: prevent double slash in object paths

---

core/arch/arm/kernel/ree_fs_ta.c

properly free hash_ctx by calling crypto_hash_free_ctx
instead of the generic free function
Signed-off-by: Silvano di Ninno <silvano.dininno@nxp.com>

core: arm: ree_fs: fix free hash_ctx

---

core/arch/arm/kernel/abort.c

`abort_handler()` can be called both within and without thread
context. In the latter case it stops on
`assert(thread_get_exceptions() & THREAD_EXCP_FOREIGN_INTR)`
in `thread_kernel_save_vfp()` and no information about abort is displayed.
This assert fires during some initialization stages and during
fast SMCs, because they are handled with foreign interrupts disabled.
To fix this, we should call `thread_kernel_{save,restore}_vfp()` only
when foreign interrupts are enabled.

abort.c: manipulate with VFP state only if thread is active

---

core/tee/tee_cryp_utl.c

Crypto_init is called twice in tee_cryp_init.
Signed-off-by: Silvano di Ninno <silvano.dininno@nxp.com>

core: tee: crypt_utl: remove one crypto_init

---

mk/compile.mk
ta/mk/build-user-ta.mk

Fixes the following errors which may reportedly be triggered by plain
"make" too [1]:
$ make -s clean && make -s out/arm-plat-vexpress/ta/avb/entry.o
cc1: warning: out/arm-plat-vexpress/export-ta_arm32/include: No such file or directory [-Wmissing-include-dirs]
ta/avb/entry.c:5:30: fatal error: tee_internal_api.h: No such file or directory
compilation terminated.
mk/compile.mk:146: recipe for target 'out/arm-plat-vexpress/ta/avb/entry.o' failed
make: *** [out/arm-plat-vexpress/ta/avb/entry.o] Error 1
$ make -s clean && make -s out/arm-plat-vexpress/ta/avb/user_ta_header.o
cc1: warning: out/arm-plat-vexpress/export-ta_arm32/include: No such file or directory [-Wmissing-include-dirs]
out/arm-plat-vexpress/export-ta_arm32/src/user_ta_header.c:5:22: fatal error: compiler.h: No such file or …

Add dependency on ta-dev-kit when building in-tree TA

---

ta/mk/build-user-ta.mk
ta/ta.mk

Commit cf903a62bc12 ("Add dependency on ta-dev-kit when building in-tree
TA") introduces a dependency of the in-tree TA object files on the phony
target 'ta_dev_kit'. The purpose was to make sure the dev kit files are
available when make starts building the TA. Unfortunately, this introduces
useless recompilation (the lines marked with >):
$ make -s && make
CHK     out/arm-plat-vexpress/conf.cmake
CHK     out/arm-plat-vexpress/export-ta_arm32/mk/conf.mk
>  CC      out/arm-plat-vexpress/ta/avb/entry.o
>  CC      out/arm-plat-vexpress/ta/avb/user_ta_header.o
>  CPP     out/arm-plat-vexpress/ta/avb/ta.lds
>  LD      out/arm-plat-vexpress/ta/avb/023f8f1a-292a-432b-8fc4-de8471358067.elf
>  OBJDUMP …

Do not make in-tree TAs depend on a phony target

---

.shippable.yml
MAINTAINERS
README.md
core/arch/arm/plat-sunxi/conf.mk
core/arch/arm/plat-sunxi/main.c
core/arch/arm/plat-sunxi/platform_config.h
core/arch/arm/plat-sunxi/sub.mk

This pull request attempts to add support for pine64 board based on
Allwinner's A64 SoC.
PS: This depends on one of the patches from PR: Upstream i.MX SoC support #2216 
Signed-off-by: Amit Singh Tomar <amittomer25@gmail.com>

plat-sunxi: Add Allwinner A64 support

---

core/arch/arm/include/sm/sm.h
core/arch/arm/kernel/asm-defines.c
core/arch/arm/sm/sm.c
core/arch/arm/sm/sm_a32.S

When compiled with "CFG_SM_NO_CYCLE_COUNTING=y" sm_save_unbanked_regs()
doesn't return with r0 pointing to ctx->nsec.r8 even if that's assumed
in sm_fiq_entry(). Fixes this by calculating the pointer based on sp
instead or relying on a certain value in r0.
Fixes: 8267e19bbcce ("core: arm: sm: initialize PMCR.DP to 1 and save/restore PMCR")

core: arm: sm: fix FIQ from normal world

---

ta/arch/arm/link.mk

Prevents ta.lds from being needlessly re-generated, such as in the
following test case:
$ make -s out/arm-plat-vexpress/ta/avb/ta.lds
$ make -s out/arm-plat-vexpress/core/kernel/console.o
$ make out/arm-plat-vexpress/ta/avb/ta.lds
CPP     out/arm-plat-vexpress/ta/avb/ta.lds
The last line should not hapen because ta.lds exists already, and building
the unrelated console.o should not trigger a re-build.
The cause of the re-build is the dependency on $(MAKEFILE_LIST) which
contains *all* the files that record previous build command and
dependencies such as out/arm-plat-vexpress/core/kernel/.console.o.{d,cmd}.
Filter out those files, thus keeping only the static Makefiles (*.mk).
This is still more …

ta: link.mk: filter out dependency and command files from $(MAKEFILE_LIST)

---

core/arch/arm/tee/entry_std.c
core/include/io.h

Code that deals with command buffers follows rule "read once, validate, use". Problem is that compiler does not know about this rule, so it can optimize out temporary variables and read data twice from the shared buffer.
We need to explicitly tell it to not do this.

Fix possible repeated reads  from shared memory

---

core/arch/arm/tee/entry_std.c

If the OP-TEE driver from the rich OS specifies a message with a number
of params < `TEE_NUM_PARAMS`, `copy_in_params()` will copy in undefined
values from `pt[i]` (where i >= the number of params). This is because the
`pt` array is an uninitialized local value, and per the C99 standard
6.7.8:
> If an object that has automatic storage duration is not initialized
> explicitly, its value is indeterminate.
This change fixes this issue by clearing out the unused parts of pt.
Signed-off-by: Christopher Tam <godtamit@google.com>

Fix copying dirty values in copy_in_params()

---

README.md
core/lib/libtomcrypt/src/sub.mk
lib/libmpa/sub.mk
mk/compile.mk

Removes the -Wdeclaration-after-statement compiler flag to allow mixed
declaration and code
Acked-by: Jerome Forissier <jerome.forissier@linaro.org>

Allow mixed declaration and code

---

core/kernel/dt.c

By convention the compatible array for driver probing ends with
a NULL compatible string ID reference.
This change ensures such NULL reference is properly handled as
the end of the compatible array references.

core: correct dt_find_compatible_driver() if no driver found

---

core/arch/arm/kernel/generic_boot.c

Add a nice info trace about the size of the pager physical page pool.

core: trace out size of the pager physical page pool

---

core/arch/arm/kernel/abort.c

This reverts commit cfa34ec63699e26e3eb674212fe6401fab32e98c.
The patch being revered causes problems with pager enabled together
crypto extensions. abort_handler() is always called with all exceptions
masked (THREAD_EXCP_ALL) so the condition to save VFP state will never
be true.
Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (Hikey AArch64 pager)

Revert "abort.c: manipulate with VFP state only if thread is active"

---

scripts/symbolize.py

Get CROSS_COMPILE prefix directive if defined in the environment.
If CROSS_COMPILE is not defined, default to aarch64-linux-gnu- or
arm-linux-gnueabihf- as done prior this change according to the
architecture read from the ELF file.

symbolize: use CROSS_COMPILE directive if available

---

.travis.yml

Since build.git has been upgraded to GCC 8.2 [1], we are running out of
disk space when running the Travis CI script. This is because the GCC 8.2
binaries are much larger than 6.2:
218M gcc-arm-8.2-2018.08-x86_64-aarch64-linux-gnu.tar.xz
213M gcc-arm-8.2-2018.08-x86_64-arm-linux-gnueabihf.tar.xz
94M gcc-linaro-6.2.1-2016.11-x86_64_aarch64-linux-gnu.tar.xz
88M gcc-linaro-6.2.1-2016.11-x86_64_arm-linux-gnueabihf.tar.xz
This commit makes some room by deleting the packages once they have been
extracted.
Link: [1] https://github.com/OP-TEE/build/commit/53119b77e9f2

ci: travis: delete toolchain binaries after download

---

core/arch/arm/mm/core_mmu.c
core/kernel/tee_misc.c

* **core: correct overflows in range overlap functions**
Buffers that end at end of the available address range which may happen on 32bit machine fail have an end address that of computed as 0. This change uses the computation already used in `_core_is_buffer_inside()` to ensure functions `_core_is_buffer_outside()` and `_core_is_buffer_intersect()` return a reliable result.
* **core: correct memory layout trace**
Buffers that end at end of the available address range which may happen on 32bit machine fail have an end address that of computed as 0. This change uses a 64bit address computation to prevent the displayed end address being 0.

3.3.0 end address

---

core/arch/arm/include/mm/mobj.h
core/arch/arm/kernel/pseudo_ta.c
core/arch/arm/mm/mobj.c
core/arch/arm/tee/entry_std.c

This pull request relates to the life cycle of registered shared memory objects and fixes the problem of normal world trying to unregister shared memory objects which are in use.

Life cycle of registered shared memory objects (take 2)

---

core/arch/arm/kernel/user_ta.c

This change prevent the core from allocating memory, mapping and
other resources to map exception index tables that are all empty.

core: prevent allocation when exception index tables are empty

---

lib/libutee/base64.c

Bitwise OR of unsinged int and a signed char is machine dependent and
could lead to invalid base64 encoding.
This commit makes it use unsigned char instead.
Signed-off-by: Krzysztof Jackiewicz <k.jackiewicz@samsung.com>

libutee: Fix base64 encoding function

---

core/arch/arm/arm.mk
core/arch/arm/plat-vexpress/conf.mk

Workaround errata 808870:
Unconditional VLDM instructions might cause an alignment fault even
though the address is aligned
Products Affected: Cortex-A57 MPCore.
Present in: r0p0
The workaround is to avoid generating the problematic instructions in
AArch32 TA.
Not tested on Juno yet, all the problematic instructions seems to be gone from the TAs though.

core: juno: workaround cortex-a57 errata 808870

---

core/arch/arm/kernel/otp_stubs.c
core/arch/arm/plat-ls/main.c
core/arch/arm/plat-ti/main.c
core/include/kernel/tee_common_otp.h
core/tee/tee_rpmb_fs.c
documentation/secure_storage.md

Getting the hardware key can fail on some platforms. Modify the function
signature to return an appropriate error code.
@dmcilvaney

core: modify tee_otp_get_hw_unique_key to return TEE_Result

---

core/arch/arm/plat-hikey/platform_config.h

SoC reference manual [1] page 2-23 says that the DRAM address range is
0x00000000 - 0xDFFFFFFF for a total of 3.5GB, so the limit would seem
to be 0xE0000000, not 0x100000000, or 0xFFE00000 based on [2] and [3].
[1] https://github.com/96boards/documentation/raw/master/consumer/hikey/hikey960/hardware-docs/HiKey960_SoC_Reference_Manual.pdf
[2] https://github.com/OP-TEE/optee_os/issues/2597#issuecomment-428587050
[3] https://github.com/OP-TEE/optee_os/issues/2597#issuecomment-428865951
Fixes: https://github.com/OP-TEE/optee_os/issues/2597

hikey960: change DRAM1_SIZE_NSEC for 4GB board

---

scripts/checkpatch.sh

try to locate checkpatch.pl in typical location(s) if environment variable is not set
the dispatcher script now tries to populate the CHECKPATCH environment variable if it is not available or empty with a path to `checkpatch.pl` if one is found under `/usr/src/linux-headers*`, a commonly used path.
Signed-off-by: Markus S. Wamser <markus.wamser@mixed-mode.de>

auto-locate checkpatch.pl

---

core/arch/arm/plat-vexpress/conf.mk

Since upstream QEMU commit 14ec3cbd7c1e ("device_tree: Increase
FDT_MAX_SIZE to 1 MiB"), which is included in release v2.12.1 and later,
OP-TEE initialization fails with the following error (-3 is
-FDT_ERR_NOSPACE):
E/TC:0 0 init_fdt:808 Invalid Device Tree at 0x40000000: error -3
Increase CFG_DTB_MAX_SIZE accordingly. Tested with the current tip of the
QEMU master branch, in 32- and 64-bit modes (note that our 64-bit QEMU
setup needs a TF-A patch -- PLAT_QEMU_DT_MAX_SIZE needs to be set to 1 MiB
too).

qemu: increase CFG_DTB_MAX_SIZE to 1 MiB

---

core/drivers/imx_uart.c

Avoid indefinite hangs by not writing to the UART if it's disabled. If the UART is disabled, the write and flush routines will hang indefinitely which can be difficult to debug
@neilsh-msft
@MrVan

drivers: imx_uart: do not write to disabled UART

---

core/arch/arm/kernel/thread.c

Fixes compile error:
CC      ../out-os-qemu/core/arch/arm/mm/tee_mm.o
core/arch/arm/kernel/thread.c:984:16: error: ‘select_vector’ defined but not used [-Werror=unused-function]
static vaddr_t select_vector(vaddr_t a)
^~~~~~~~~~~~~
cc1: all warnings being treated as errors
when compiled with CFG_CORE_WORKAROUND_SPECTRE_BP_SEC=n

core: fix compile error with CFG_CORE_WORKAROUND_SPECTRE_BP_SEC=n

---

core/arch/arm/include/kernel/mutex.h
core/arch/arm/include/kernel/thread.h
core/arch/arm/kernel/mutex.c
core/arch/arm/kernel/thread.c
core/arch/arm/kernel/thread_private.h

With the recently merged lockdep patches thread_add_mutex() and
thread_rem_mutex() are obsolete. Remove them to save memory and
overhead.

core: remove thread_{add,rem}_mutex()

---

core/arch/arm/include/arm64.h
core/arch/arm/plat-synquacer/conf.mk
core/drivers/gic.c

This pull request also includes patch to set default number of threads to 8 which has already been reviewed as part of https://github.com/OP-TEE/optee_os/pull/2564.

GICv3 interrupt handling fix

---

core/lib/zlib/inflate.c

GCC 8.x warns when building core/lib/zlib/inflate.c:
$ make PLATFORM=hikey-hikey960 out/arm-plat-hikey/core/lib/zlib/inflate.o
[...]
core/lib/zlib/inflate.c: In function ‘inflate’:
core/lib/zlib/inflate.c:842:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
state->mode = DICT;
~~~~~~~~~~~~^~~~~~
core/lib/zlib/inflate.c:843:9: note: here
case DICT:
^~~~
[...]
Fix that by adding some /* Fall through */ comments.

zlib: fix compiler warning

---

lib/libmbedtls/sub.mk
lib/libmpa/sub.mk
lib/libutee/sub.mk
lib/libutils/sub.mk
mk/lib.mk

Code cleanup, no functional change. This commit avoids the duplication of
the -pg flag in the library makefiles.

lib.mk: centralize profiling flag (-pg)

---

core/arch/arm/include/mm/mobj.h
core/arch/arm/kernel/thread.c
core/arch/arm/tee/entry_std.c

Removes MOBJ_INVALID_COOKIE which resulted in an unexpected ABI change
against the normal world driver. Instead 0 is continued to be used as an
invalid/absent cookie value.
Reported-by: Sumit Garg <sumit.garg@linaro.org>
Fixes: cd278f78382b ("core: simplify shm cookie handling")

core: remove MOBJ_INVALID_COOKIE

---

core/arch/arm/kernel/generic_boot.c
core/sub.mk
documentation/file_structure.md
documentation/optee_design.md
mk/compile.mk
mk/config.mk
scripts/bin_to_c.py

This series introduces a way to use a secure device tree for the description of the platform.
* Add a helper in  mk/compile.mk for generating a DTB file from a DTS file.
* Introduce `CFG_EMBEDDED_DTS`: defines a DTS file from **core/arch/arm/dts/** that is embedded in a read-only section of the core and used as secure FDT reference for platform configuration.
This change is the redesign of the initial P-R https://github.com/OP-TEE/optee_os/pull/2653.

FDT compilation & CFG_EMBEDDED_DTS

---

ta/ta.mk

Exports CFG_TEE_TA_LOG_LEVEL to TA dev-kit. It can still be overridden
when compiling the TA, but it makes sense to default to the value used
when compiling the dev-kit.

TA: export CFG_TEE_TA_LOG_LEVEL to dev-kit

---

core/arch/arm/kernel/generic_boot.c
documentation/optee_design.md
mk/config.mk

This pull request adds the ability for OPTEE to provide a DTB overlay to a subsequent boot stage.
We can either
1. Append to an existing DTB overlay located at CFG_DT_ADDR or passed in arg2
2. Generate a new DTB overlay at CFG_DT_ADDR
Providing a DT overlay means it is possible for OPTEE to provide internal dynamic data without requiring the DTB to already be in-memory.
Here is an example of merging an OPTEE provided device tree overlay into a main DTB image.
CFG_DT_ADDR = 0x82000000
CFG_DT_OVERLAY = y
u-boot:
=> load mmc 0:1 0x83000000 imx7s-warp.dtb
38564 bytes read in 10 ms (3.7 MiB/s)
=> fdt addr 0x83000000
=> fdt resize 0x1000
=> fdt print /firmware
libfdt fdt_path_offset() returned FDT_ERR_NOTFOUND
=> fdt print /psci
libfdt fdt_path_offset() returned FDT_ERR_NOTFOUND
=> fdt print …

Master+optee overlay

---

core/arch/arm/plat-stm32mp1/conf.mk

Minor cleaning and allow CFG_TEE_CORE_NB_CORE to be set to 1.

stm32mp1: release constraint on core count

---

lib/libutils/ext/include/mempool.h
lib/libutils/ext/mempool.c

This commit will be needed when updating the import/mbedtls-2.6.1 branch for the MPI integration in libutee.

mempool: add mempool_calloc()

---

core/arch/arm/dts/stm32mp157-pinctrl.dtsi
core/arch/arm/dts/stm32mp157c-ed1.dts
core/arch/arm/dts/stm32mp157c-ev1.dts
core/arch/arm/dts/stm32mp157c.dtsi
core/arch/arm/plat-stm32mp1/conf.mk
core/arch/arm/plat-stm32mp1/main.c
core/include/dt-bindings/clock/stm32mp1-clks.h
core/include/dt-bindings/gpio/gpio.h
core/include/dt-bindings/interrupt-controller/arm-gic.h
core/include/dt-bindings/interrupt-controller/irq.h
core/include/dt-bindings/pinctrl/stm32-pinfunc.h
core/include/dt-bindings/reset/stm32mp1-resets.h
documentation/dt-bindings/README.txt
scripts/checkpatch_inc.sh

This change introduces the device tree source files describing boards
EV1, ED1 and DK2 and the related bindings.
Bindings for stm32mp1 complies with the bindings used common
open source packages as Linux kernel, U-boot or Arm Trusted
Firmware A. The bindings provided by this change are synced
with bindings from Linux kernel 4.19.
Rely on DT source file (CFG_EMBED_DTB_SOURCE_FILE) to distinguish
between the platform flavors.
Support CFG_SECURE_DT for some legacy configuration: if defined,
specifies target in-tree platform DTS file without the .dts
file name extension.
Default configuration locates the secure DDR area (TZDRAM) from
the base address of the last 32MBytes of the DDR over 30Mbyte.
The last 2MBytes of the DDR are the OP-TEE static shared memory.
Many contributors not listed …

stm32mp1: device tree platform description

---

core/arch/arm/include/kernel/generic_boot.h
core/arch/arm/kernel/generic_boot.c
core/drivers/imx_wdog.c
core/kernel/console.c

Makes chosen console selection more flexible being probed
from either secure-chosen node or chosen node, from
either secure embedded DTB or non-secure external DTB.
Secure-chosen node has precedence over chosen node. Chosen console
from the secure DTB as precedence over chosen console defined by
the non-secure device tree.

core: console: secure/non secure chosen console

---

core/arch/arm/plat-stm32mp1/link.mk
core/arch/arm/plat-stm32mp1/scripts/stm32image.py

Introduce the binary image type information to the STM32 header
used for OP-TEE boot images.

stm32mp1: update boot image header script tool

---

core/sub.mk

Correct the name of the script used to embed a DTB in the core
when added to the core dependency list.

core: fix dependency in embedded DTB build

---

core/arch/arm/kernel/thread_a64.S

__thread_enter_user_mode() cannot be paged out, because the pager cannot
be invoked to restore any faulting code page after SP has been switched to
use SP_EL1. At this point, a synchronous exception would take the CPU to
the 0x200 offset in the exception vector, which corresponds to
[workaround_]el1_sync_sp1 and is an error-catching infinite loop. This
explains the behavior described in [1].
Add the requisite KEEP_PAGER so that the function is kept in the unpaged
area.
Fixes: [1] https://github.com/OP-TEE/optee_os/issues/2684

core: arm64: pager: make sure __thread_enter_user_mode is unpaged

---

core/arch/arm/kernel/thread.c
core/arch/arm/kernel/thread_private.h

Prior to this patch the non-secure VFP state was only saved when it
seemed necessary based on control registers.
To make sure that non-secure VFP state isn't corrupted always save the
entire register file before modifying it. This is now the same behavior
on both ARMv8-A and ARMv7-A platforms.

core: always save non-secure vfp state

---

core/include/io.h

Introduce new iomem util functions to set, clear or set and clear
bit masks in peripheral interfaces.
io_setbits32(addr, mask) sets the bits enabled in mask at address.
io_clrbits32(addr, mask) clears the bits enabled in mask.
io_clrsetbits32(addr, clear_mask, set_mask) clears the bits enabled in
clear_mask and sets the bits enabled in set_mask.
These functions are more friendly in instruction blocks to sets and
clears bitmasks in peripheral registers. They provide a more readable
implementation than playing with io_mask32() for the equivalent
sequence, for example, extracted from a DDR controller driver:
```C
/* IOs powering down (PUBL registers) */
io_setbits32(ddrphy_base + DDRPHYC_ACIOCR, DDRPHYC_ACIOCR_ACPDD);
io_setbits_32(ddrphy_base + DDRPHYC_ACIOCR, DDRPHYC_ACIOCR_ACPDR); …
```

core: io_{set|clr|clrset}bits32() helpers

---

core/arch/arm/include/kernel/delay.h
core/arch/arm/kernel/delay.c
core/drivers/stm32_uart.c

This P-R proposes timeout functions and an example of their use on the stm32_uart `putc()` and `flush()` function used for the platform console.

Timeout functions based on Arm CNTP

---

core/arch/arm/pta/benchmark.c

@igoropaniuk, please crosscheck this.
Will exploring uncleared freed reference when fixing for https://github.com/OP-TEE/optee_os/pull/2572 I found this occurence that  I think should be fixed. But maybe, as I don't master the op-tee benchmarch feature, this change is useless.

core: benchmarch: dereference freed memory

---

Makefile

The build directory contains some generated source files, such as
include/generated/conf.h, core/include/generated/arm32_sysreg.{h,S} and
core/include/generated/asm-defines.h. Let cscope parse them and only
exclude the files that are copied into the export-ta_* directories (TA
dev kit).

cscope: do not exclude generated file

---

core/arch/arm/kernel/thread_a32.S
core/arch/arm/kernel/thread_a64.S

The two symbols thread_excp_vect and thread_excp_vect_end are used to
mark the part of the privileged code that still to be mapped in order to
transition between user mode and privileged mode when compiled with
CFG_CORE_UNMAP_CORE_AT_EL0=y.
Prior to this patch it was assumed that thread_excp_vect_end would mark
the end of the thread_excp_vect() assembly function including literals
emitted by the assembler. This assumption was wrong and an extra .pool
directive is added before the thread_excp_vect_end to guarantee that all
literals will be included in the section starting with thread_excp_vect
and ending with thread_excp_vect_end.
Reported-by: Jerome Forissier <jerome.forissier@linaro.org>

core: fix thread_excp_vect_end and literal pool

---

core/arch/arm/plat-stm32mp1/conf.mk
core/arch/arm/plat-stm32mp1/main.c
core/arch/arm/plat-stm32mp1/platform_config.h
core/drivers/stm32_uart.c
core/include/console.h
core/include/drivers/stm32_uart.h
core/include/kernel/dt.h
core/kernel/console.c
core/kernel/dt.c

This P-R brings allows stm32mp1 to get the OP-TEE console configuration from the devicetree.
This P-R also provides some configuration means for the early console.
This P-R proposes 2 generic changes in the core:
* Factorize a sequence from `configure_console_from_dt()` to allow an external console driver to get the console DT info through function `get_console_node_from_dt()`.
* Introduce `_fdt_fill_device_info()` to factorize extraction of some generic device DT properties as the status, the registers address, a clock ID.

stm32mp1: uart consoles

---

scripts/gen_hashed_bin.py

By default Python tries to open files in text mode. This is
okay for python2, because it uses 8-bit encoding.
But python3 tries to decode file as utf-8 encoded and fails,
because it is a binary file.

gen_hashed_bin.py: open file in binary mode

---

lib/libutils/ext/include/atomic.h
lib/libutils/ext/mempool.c

Mempool fix

---

lib/libmbedtls/mbedtls/library/bignum.c

Fixes memory leak in mpi_miller_rabin() that occurs when the function has
failed to obtain a usable random 'A' 300 turns in a row.
Reviewed-by: Joakim Bech <joakim.bech@linaro.org>

mbedtls: fix memory leak in mpi_miller_rabin()

---

lib/libutils/ext/trace.c
scripts/symbolize.py

We don't need 2 digits print for '?' in case of non-atomic context.
So make it single digit print only.
It causes symbolize.py script parsing failure for call stack addresses
in case number of cores is greater that 9.

trace: fix core id print if in non-atomic context

---

core/arch/arm/plat-vexpress/main.c

Disables uart interrupts if compiled for TF-A and GICv3 since TF-A
doesn't know which interrupts OP-TEE will handle.

plat-vexpress: disable uart IT with TF-A and GICv3

---

core/arch/arm/kernel/thread_a32.S

Fixes a race where FIQ isn't masked in the abort handler which results
lost register content and invalid processing of the abort when resumed.
Fixes: 18901324e00a ("Support ARM GICv3 mode")

core: arm32: fix gicv3 fiq race

---

CHANGELOG.md

Preparing for OP-TEE release 3.4.0. As usual this PR will be used to collect `Tested-by:` tags.

Update CHANGELOG.md for 3.4.0

---

mk/aosp_optee.mk

AOPS's Toybox's version of cp doesn't support -u option
Signed-off-by: Yongqin Liu <yongqin.liu@linaro.org>

mk/aosp_optee.mk: remove cp -u option

---

documentation/external_libraries.rst

Document how larger external libraries are imported into the OP-TEE
repository and how they are maintained. Although this process has been
applied in parts for mbed TLS, it is still somewhat theoretical and may
need to be amended in the future.

Add documentation/external_libraries.rst

---

core/arch/arm/plat-stm32mp1/scripts/stm32image.py
scripts/bin_to_c.py

Fixes the following warnings:
$ pycodestyle --version
2.5.0
$ pycodestyle scripts/*.py
scripts/bin_to_c.py:15:9: E117 over-indented
scripts/bin_to_c.py:34:9: E117 over-indented
scripts/bin_to_c.py:37:17: E117 over-indented
scripts/bin_to_c.py:49:17: E117 over-indented
scripts/bin_to_c.py:50:25: E117 over-indented
scripts/bin_to_c.py:54:25: E117 over-indented
scripts/bin_to_c.py:56:25: E117 over-indented
scripts/bin_to_c.py:62:9: E117 over-indented
$ cd core/arch/arm/plat-stm32mp1/scripts; \
pycodestyle stm32image.py
stm32image.py:21:9: E117 over-indented
stm32image.py:27:9: E117 over-indented
stm32image.py:29:17: E117 over-indented
stm32image.py:39:9: E117 over-indented
stm32image.py:77:9: E117 over-indented
stm32image.py:84:17: E117 over-indented
stm32image.py:96:9: E117 over-indented …

scripts: re-indent Python scripts

---

core/arch/arm/kernel/user_ta.c

get_elf_segments() doesn't initialize the returned segs array properly,
some fields are left uninitialized. Fix this by doing a compound
assignment when initializing new elements in the array.

core: fix get_elf_segments() segs initialization

---

core/lib/libtomcrypt/src/tee_ltc_provider.c

When there is some data already pending in the cbc->block and the input
data size is not large enough to do cbc_encrypt(), the pending data is
going to be overwritten. For example, a serial input with size like 3,3...
uncovers this bug.
Signed-off-by: Oliver Chiang <rockerfeynman@gmail.com>

ltc: fix the CBC_MAC error

---

core/arch/arm/pta/stats.c

Adds a memleak function to the status PTA which calls mdbg_check(1)
to dump all allocations.

core: pta_stats: add memleak function

---

core/arch/arm/plat-rcar/conf.mk
core/arch/arm/plat-rcar/platform_config.h

plat-rcar have quite standard memory layout, so there is no sense to maintain
separate configuration if it possible to use generic one.

plat-rcar: Use generic memory layout

---

lib/libutils/isoc/bget.c

bget: check for size overflow
#2780 
Check size overflow to avoid size <= 0 which may be caused by
calculation "size += sizeof(struct bhead)".(url)

bget: check for size overflow  

---

core/lib/libtomcrypt/src/mpa_desc.c
core/lib/libtomcrypt/src/mpi_desc.c
lib/libutee/tee_api_arith_mpa.c
lib/libutee/tee_api_arith_mpi.c
lib/libutils/ext/include/mempool.h
lib/libutils/ext/mempool.c

Prior to this patch was _TEE_MathAPI_Init() in
lib/libutee/tee_api_arith_mpi.c supplying a data buffer which was only 4
byte aligned while mempool_alloc_pool() requires the alignment of long.
This will work in 32-bit mode, but could lead to alignment problem in
64-bit mode.
Incorrect alignment can result in errors like:
E/TA:  assertion '!((vaddr_t)data & (POOL_ALIGN - 1))' failed at lib/libutils/ext/mempool.c:134 in mempool_alloc_pool()
This fix introduces MEMPOOL_ALIGN which specifies required alignment of
data supplied to mempool_alloc_pool().

Fix alignment of data for mempool_alloc_pool()

---

core/arch/arm/plat-stm32mp1/drivers/stm32mp1_pwr.c
core/arch/arm/plat-stm32mp1/drivers/stm32mp1_pwr.h
core/arch/arm/plat-stm32mp1/drivers/sub.mk
core/arch/arm/plat-stm32mp1/main.c
core/arch/arm/plat-stm32mp1/platform_config.h

PWR is a memory mapped SoC interface for power control. This change maps and defines the interface for the stm32mp1 platform.

stm32mp1: PWR support

---

core/arch/arm/pta/core_self_tests.c
lib/libutils/isoc/bget_malloc.c
lib/libutils/isoc/include/malloc.h

Removes the unused memalign() function. Usage of this function will
cause severe fragmentation of the heap.
Another problem is with the implementation which is added on top of bget
while still depending heavily on internals of bget. The implementation was
somewhat buggy since it can sometimes can cause:
E/TC:0 0 assertion 'bn->prevfree == 0' failed at lib/libutils/isoc/bget_malloc.c
:423 <create_free_block>
E/TC:0 0 Panic at core/kernel/assert.c:28 <_assert_break>

Remove memalign()

---

.shippable.yml

There is currently no CI build with CFG_VIRTUALIZATION=y. Add one.

ci: .shippable.yml: add build for QEMUv8 with virtualization

---

lib/libutils/isoc/bget_malloc.c

gen_malloc_reset_stats() and gen_malloc_get_stats()
are only available when BufStats is defined.

bget: fix nex_ pool building with disabled stats

---

core/arch/arm/plat-stm32mp1/drivers/stm32mp1_clk.c
core/arch/arm/plat-stm32mp1/drivers/stm32mp1_rcc.c
core/arch/arm/plat-stm32mp1/drivers/stm32mp1_rcc.h
core/arch/arm/plat-stm32mp1/drivers/sub.mk
core/arch/arm/plat-stm32mp1/main.c
core/arch/arm/plat-stm32mp1/stm32_util.h

Driver API uses the clock IDs published in the DT bindings (as per later Linux kernel v4.20) to identify the clocks.
Note configuration of clock parenthood and related divisors as well as configuration of the PLLs are under to responsibility of an earlier boot stage. Such configuration directives found by OP-TEE core in the DT are ignored. DT is used to set the SoC clocks interface secure state and the frequencies of the platform source clocks.
Driver API allows to gate (enable/disable) a clock, get a clock enable state and its frequency.

stm32mp1: introduce platform clock driver

---

ta/arch/arm/link.mk

TA binaries contain a lot of zero padding (almost 64 KiB) between sections
.ta_head and .text. This value can be reduced to 4 KiB by reducing the
linker's max-page-size parameter. Since the OP-TEE ELF loader always
aligns on small page boundaries, it does not make sense to request a
larger alignment.
This patch adds "-z max-page-size=4096" to the linker flags so that the
alignment constraints are relaxed from 64 KiB (the default for our 32 and
64 targets as it seems) to what OP-TEE is actually expecting (4 KiB).
The TA file size is reduced by 60 KiB. It changes nothing to the layout
of the TA in memory.

ta: link.mk: set linker max-page-size to 4K

---

core/arch/arm/plat-stm32mp1/drivers/stm32mp1_clk.c
core/arch/arm/plat-stm32mp1/drivers/stm32mp1_rcc.h
core/arch/arm/plat-stm32mp1/main.c
core/arch/arm/plat-stm32mp1/stm32_util.h
core/drivers/stm32_etzpc.c
core/drivers/stm32_gpio.c
core/include/io.h

Change API for `io_clrbits32()`, `io_setbits32()` and `io_clrsetbits32()` to have a `vaddr_t` type address argument, rather than `uintptr_t` as previously.

core: change io_{clr|set|clrset}bits32() address argument type

---

core/arch/arm/plat-stm32mp1/drivers/stm32mp1_rcc.c
core/arch/arm/plat-stm32mp1/drivers/stm32mp1_rcc.h
core/arch/arm/plat-stm32mp1/stm32_util.h

Reset API functions:
- stm32_reset_assert(id) asserts reset signal on target resource.
- stm32_reset_deassert(id) releases reset signal on target resource.
Driver API relies on resource IDs defined in the platform DT bindings
header file dt-bindings/reset/stm32mp1_reset.h.

stm32mp1: reset driver for platform peripheral interfaces

---

core/arch/arm/plat-stm32mp1/main.c

Fixes commit 1095cc2ec739 ("stm32mp1: platform enables STM32 ETZPC driver")
that did not define ETZPC interface registers mapping.

stm32mp1: fix missing ETZPC mapping

---

core/arch/arm/mm/core_mmu_lpae.c
core/arch/arm/plat-rcar/main.c

There are two patches: 
One flushes TLB, to fix issue with page fault while writing to stack. This wasn't needed on QEMU, but is required on real HW.
Another moves platform data to `.nex` sections. Similar changes are required to other platforms, but I have no means to test them.

Enable virtualization support on Renesas RCAR platform

---

lib/libutee/tee_api_objects.c

The TEE spec says about  TEE_OpenPersistentObject:
> If this function fails for any reason, the value pointed to by object is set to TEE_HANDLE_NULL.
The diff looks a bit confusing. All I did was to move the `if (!object)` block to the top and set `*object` to `TEE_HANDLE_NULL` directly afterwards.

libutee: fix TEE_OpenPersistentObject error behavior

---

core/arch/arm/include/arm64.h
core/drivers/gic.c

OP-TEE dispatcher registers with TF-A to handle EL1S interrupts
by design. OP-TEE should own the G1S interrupts.
-gic_it_add() should result in configuring a given interrupt to
G1S instead of G0 for GICv3.
-G1S interrupts to be enabled at distributor interface.
-system interface register ICC_IGRPEN1_EL1 to be used to enable
G1S interrupts.
Signed-off-by: Sandeep Tripathy <sandeep.tripathy@broadcom.com>

drivers: GICv3: Configure native secure interrupt

---

.travis.yml

The Travis build keeps timing out apparently due to a reduced download
speed compared with some time ago. It is not rare for the build to fail
in the initial "repo sync" phase with the error message:
No output has been received in the last 10m0s, this potentially
indicates a stalled build or something wrong with the build itself.
Allowing more verbosity from "repo sync" could possibly avoid this
particular error, but then the second issue is that total build time
reaches 50 minutes very frequently which is the limit for Open Source
projects.
Since we have IBART to run xtest on HiKey, we can loose the test on
QEMU. Therefore, this commit keeps only the code rule checks in the
Travis script (checkpatch.pl and pycodestyle).

ci: travis: keep only code rule checks

---

core/arch/arm/kernel/pseudo_ta.c
core/include/kernel/tee_ta_manager.h
lib/libutee/include/pta_invoke_tests.h

Replace inline comment ??? with an appropriate description of
the user_ctx field which points the the caller user TA context
in case a pseudo TA is invoked from the user TA client.

core: add inline description of TEE session field user_ctx

---

core/arch/arm/arm.mk

TA source files are compiled with the -fpie GCC flag in order to
generate a Position Independant Executable. This is not suitable to
produce a shared library as introduced by commit f8896d1301fc ("TA dev
kit: add support for creating shared libraries"). -fpic should be used
instead. Here is what the GCC man page has to say on these flags:
-fpic
Generate position-independent code (PIC) suitable for use in a
shared library [...]
-fpie
-fPIE
These options are similar to -fpic and -fPIC, but generated
position independent code can be only linked into executables.
So, it is quite clear that -fpie is wrong for a shared library. It is
not very clear however if -fpic can be used when generating code for an
executable. I think it can, and there is a bug report against the GCC
documentation that …

Compile user TAs with -fpic rather than -fpie

---

core/arch/arm/kernel/generic_boot.c
core/arch/arm/kernel/tee_time_arm_cntpct.c
core/arch/arm/kernel/thread.c
core/arch/arm/kernel/unwind_arm32.c
core/arch/arm/kernel/user_ta.c
core/arch/arm/mm/core_mmu_lpae.c
core/arch/arm/tee/entry_std.c
core/drivers/tzc380.c
core/drivers/tzc400.c
core/kernel/tee_ta_manager.c
core/lib/libtomcrypt/src/tee_ltc_provider.c
core/tee/tee_obj.c
core/tee/tee_rpmb_fs.c
core/tee/tee_svc_storage.c

Change trace message indicating absence of external DTB
from error level to debug level. Implementation and comment
clearly state the configuration is fully legitimate.

core/generic-boot: level up missing external DTB trace

---

core/arch/arm/kernel/elf_load.c
core/arch/arm/kernel/user_ta.c
mk/config.mk
mk/lib.mk
ta/arch/arm/link.mk
ta/mk/build-user-ta.mk
ta/ta.mk

This RFC introduces a config flag to build user-mode libraries (libutee, libutils etc.) as shared objects.
I wrote this patch set when I was implementing the dynamic link support in the ELF loader, because it was quite convenient to test the feature. But, without the ability to share code and RO data between TAs, it was quite useless in practice.
Now that @jenswi-linaro has proposed #2801 "Shared read-only pages between TAs", things are different and thus I'm pushing this as an RFC. With both features combined we can probably save significant amounts of memory and load many more TAs simultaneously. 
FYI, here is the output of `xtest 1019` (calling `TEE_Panic()` in a library) filtered through `symbolize.py`, with all libraries built as shared objects. Pretty cool, no? ;-)
```
E/TC:? 0 TA …
```

RFC: libutils libutee etc. as shared libraries

---

lib/libutee/include/user_ta_header.h

Commit 387b0ee39b1b ("core: deprecate TA property flags EXEC_DDR and
USER_MODE") removes the requirement for user TAs to set the flags
TA_FLAG_EXEC_DDR (bit 0) and TA_FLAG_USER_MODE (bit 1), the rationale
being that they are meaningless in the current implementation.
The macros are re-defined to be zero to reflect the fact that they have
no use. But, instead of ignoring the previous values, the TEE core now
requires that bits 0 and 1 must *not* be set. This is a problem because
it needlessly breaks backward compatibility. A TA built against OP-TEE
3.0.0 will not work with 3.1.0 or later:
E/TC:? 0 tee_ta_init_user_ta_session:1040 Invalid TA flag(s) 0x3
This commit changes the acceptable flags mask (TA_FLAGS_MASK) to
include the previous EXEC_DDR and USER_MODE bits, thus restoring
backward …

core: ignore deprecated TA flags EXEC_DDR and USER_MODE

---

lib/libutee/include/user_ta_header.h

Update inline comment and value for the deprecated TA flag `TA_FLAG_REMAP_SUPPORT`.

libutee: fix deprecated TA_FLAG_REMAP_SUPPORT inline comment

---

core/arch/arm/plat-zynqmp/platform_config.h

Add flavor 'ultra96' to platform 'zynqmp'.
Redirect TEE console output to UART1.
Fix UART1 base address which is wrong.
Successfully tested on Ultra96 board.

Add support for ultra96 ZynqMP board

---

scripts/symbolize.py

User TA crash dumps were slightly modified to better align region
numbers. scripts/symbolize.py needs to be updated accordingly.
Fixes: dba5a1eab8af1 ("core: better align output of TA dump with many or big regions")

scripts/symbolize.py: accept several spaces after "region"

---

typedefs.checkpatch

```
Adds a couple of mbed TLS types to typedefs.checkpatch to avoid the
following warning:
WARNING: Missing a blank line after declarations
#100: FILE: lib/libutee/tee_api_arith_mpi.c:105:
+		const struct bigint_hdr *hdr = (struct bigint_hdr *)bigInt;
+		const mbedtls_mpi_uint *p = (const mbedtls_mpi_uint *)(hdr + 1);
```

Add mbed TLS types to typedefs.checkpatch

---

lib/libutee/tee_api_arith_mpi.c

Until now tee_api_arith_mpi.c assumed that for instance TEE_BigIntConvertFromOctetString() wouldn't do a
mbedtls_mpi_free(mpi);
mbedtls_mpi_init(mpi);
sequence on the supplies mpi argument. Doing so replaces the special allocation type MBEDTLS_MPI_ALLOC_TYPE_STATIC with MBEDTLS_MPI_ALLOC_TYPE_MALLOC. This
results in the value of the mpi argument isn't propagated further to the dest
argument of TEE_BigIntConvertFromOctetString().
With this patch we're instead explicitly copying the value of
mbedtls_mpi to a TEE_BigInt when the value should be returned.

libutee: lessen dependency on mbedtls internals

---

lib/libutee/base64.c

There is a possible buffer overflow in base64_dec(). Since the output
buffer size is *blen, the last byte of the buffer is buf[*blen - 1] and
therefore the buffer must not be written to when the current index m is
such that (m >= *blen), not (m > *blen).

libutee: fix off-by-one errors in base64_dec()

---

mk/compile.mk

This change removes -pedantic from the build directive from all
warning build level. The rational is that OP-TEE OS package no
longer supports being built in pedantic mode allowing now use
of implementation sequence that are rejected in pedantic mode.

build: remove pedantic from build directives

---

core/drivers/stm32_gpio.c
core/drivers/stm32_i2c.c
core/include/drivers/stm32_i2c.h

When device tree content defines pins related to an I2C interface, the I2C driver saves the pins configuration instances and set the registered pins in the expected power mode at runtime.

stm32_i2c: handle pinctrl (+ fix inline comment in stm32 pinctrl)

---

core/arch/arm/plat-stm32mp1/conf.mk
core/arch/arm/plat-stm32mp1/drivers/stm32mp1_clk.c
core/arch/arm/plat-stm32mp1/platform_config.h
core/arch/arm/plat-stm32mp1/shared_resources.c
core/arch/arm/plat-stm32mp1/stm32_util.h
core/arch/arm/plat-stm32mp1/sub.mk

This series introduces shared resources for stm32mp1. Some platform resources can be assigned to the secure or the non-secure world according to platform configuration. As platform is configured at boot time thanks to device tree technology, assignation of resource is done during the core inits. Note some resource cannot be assigned to secure world.
Each driver is responsible for registering itself as secure or non-secure during its initialization. Note that core may register non-secure resource in secure world, for example when shared a UART console with the non-secure world and its related pin muxing (GPIO driver controls stm32mp1 pin control)
1st commit "stm32mp1: shres: registering shared resources" introduces the drivers used to saves the resources assignation. Shared peripherals …

stm32mp1: introduce shared resource support

---

core/drivers/bcm_hwrng.c
core/drivers/bcm_sotp.c
core/drivers/sub.mk
core/include/drivers/bcm_hwrng.h
core/include/drivers/bcm_sotp.h

Add low level sequences for sotp and hwrng ip.
TODO: use dt to populate the base address , enable disable for these devices.

plat-bcm: add sotp and hwrng low lever drivers

---

core/arch/arm/plat-imx/drivers/sub.mk
core/arch/arm/plat-imx/drivers/tzc380.c
core/arch/arm/plat-imx/imx.h
core/arch/arm/plat-imx/imx6.c
core/arch/arm/plat-imx/sub.mk
core/drivers/tzc380.c
core/include/drivers/tzc380.h

Hello,
this PR adds a new function called `tzc380_auto_configure` which searches for the matching configuration for a given start address and size. This configuration is then applied with the given permissions to the controller.
This vastly simplifies configurations for devices with a generic RAM layout, since the necessary information is already available from the header file.
Support for i.MX6QD devices is added as a user of the new function.

TZC380 autoconfiguration (search correct region size) and support for i.MX6Q/D

---

core/arch/arm/include/sm/optee_smc.h
core/arch/arm/tee/entry_fast.c

This call can be used to query OP-TEE about different configuration
options.
It is introduced after discussion at [1] about possibility to read
number of supported threads. It is needed for XEN OP-TEE mediator to
mitigate possible DoS from virtual guest. If XEN knows number of
OP-TEE threads, it can limit number of standard calls from the guest
on own side.
I tried to implement OPTEE_SMC_GET_CONFIG in flexible way, so more
options can be added later.
[1] https://lists.xenproject.org/archives/html/xen-devel/2019-01/msg01460.html
---
This isn't strictly required change. I can limit number of threads from XEN side using arbitrary number. Hence, [rfc] tag.
But anyways, it is a nice feature to have.

[rfc] core: Introduce OPTEE_SMC_GET_CONFIG SMC

---

core/arch/arm/plat-imx/a7_plat_init.S
core/arch/arm/plat-imx/a9_plat_init.S

This patchset is to improve performance and add errata fix. 
The patch `core: arm: imx: a9: allow nonsecure modify SMP bit `  is not that elegant, but to make the downstream i.MX Linux busfreq work, need this patch.

perf and errata fix on i.MX

---

core/arch/arm/kernel/user_ta.c

If any error is encountered when the TEE core attempts to load a TA from
TA storage, the next storage is tried and so on until the TA is
successfully loaded or there is no more storage to try. In this case, a
generic error code (TEE_ERROR_ITEM_NOT_FOUND) is returned to the caller
of load_elf() and ultimately to the client. This is not super useful,
especially when debug traces are disabled, because the user has no way
to differentiate a true "not found" situation (which might be a
configuration or deployement issue) from an issue with the TA file
itself or an out-of-memory condition etc.
This commit changes the return code of load_elf() to better reflect the
errors. Here are some examples (assuming we have two TA stores: 1 and 2,
1 is tried first):
Partial results                 Final …

core: user_ta: load_elf(): return meaningful error code

---

lib/libutee/arch/arm/gprof/gprof_a32.S
lib/libutee/arch/arm/gprof/gprof_a64.S
lib/libutee/arch/arm/user_ta_entry.c
ta/arch/arm/ta.ld.S

Define original mcount APIs: _mcount (for aarch64) and __gnu_mcount_nc
(for arm) inserted by compiler instead of providing them via
__utee_mcount API.
As linker treats __utee_mcount as normal symbol which may be discarded
(in case its defined in static library) or undetected (in case its
defined in shared library) leading unresolvable symbol linker error.
Fixes: 64718c9 ("Allow building libutils etc. as shared libraries")

gprof: define original mcount APIs inserted by compiler

---

typedefs.checkpatch

When using BSD queues from <sys/queues.h>, a queue entry is declared
with a macro:
TAILQ_ENTRY(type) var;
This makes checkpatch.pl unhappy because the type is unknown:
WARNING: Missing a blank line after declarations
#52: FILE: core/arch/arm/include/mm/tee_pager.h:32:
+	struct pgt *pgt;
+	TAILQ_ENTRY(tee_pager_area) link;
This patch adds a regular expression to typedefs.chackpatch that
matches the macro part, thus fixing the warning.

Add TAILQ_ENTRY() to typedefs.checkpatch

---

core/arch/arm/include/kernel/mutex.h
core/arch/arm/include/kernel/wait_queue.h
core/arch/arm/kernel/link_dummies.c
core/arch/arm/kernel/mutex.c
core/arch/arm/kernel/wait_queue.c

mutex::owner_id was used for debugging purposes only. But since commit
8aff6c039ee5 "core: remove thread_{add,rem}_mutex()", it is never set to
a valid thread ID anymore. Let's just remove the field.

core: arm: mutex: remove owner_id

---

mk/config.mk

The gprof sample buffer is currently allocated at link time by the TA
linker script: ta/arch/arm/ta.ld.S. The size of the buffer is a
function of the total TA code size (.text segment). While this works
fine for statically linked TAs, it is problematic when shared libraries
are used, because in this case the total .text size is not known at
link time. As a result, the pre-allocated buffer may be too small,
resulting in the following error when the TA is initialized:
E/TA:  __utee_gprof_init:159 gprof: could not allocate profiling buffer
One way to fix this problem is to allocate the buffer at run time, once
all the shared libraries have been loaded. Since the TA loader is about
to be reworked and moved to user space, let's wait for this to occur
before implementing a long term solution. …

Error out if CFG_TA_GPROF_SUPPORT and CFG_ULIBS_SHARED are both enabled

---

core/arch/arm/plat-stm32mp1/shared_resources.c
core/arch/arm/plat-stm32mp1/stm32_util.h

Replace type uintptr_t with type vaddr_t when applicable for consistency
with other resources.

stm32mp1: clean shared resource to use vaddr_t

---

core/arch/arm/include/tee/entry_std.h
core/arch/arm/kernel/user_ta.c
core/arch/arm/mm/tee_mmu.c
core/arch/arm/mm/tee_pager.c
core/arch/arm/tee/entry_std.c
core/kernel/tee_ta_manager.c
core/tee/tee_svc.c

This change include change commit from https://github.com/OP-TEE/optee_os/pull/2838 prepended with a preparatory change to not crash on release context reference in TEE session instances:
* "core: handle user TA context released from session": to be reviewed.
* "core: keep alive TA context can be created after TA has panicked": https://github.com/OP-TEE/optee_os/pull/2838 incluing review tags.

Release resources in case of panicked instance #2

---

core/arch/arm/plat-stm32mp1/conf.mk
core/arch/arm/plat-stm32mp1/main.c

Fixes for RNG support in the stm32mp1: fix missing mapping and default enable driver in the platform.

stm32mp1: fixes for RNG support

---

core/kernel/tee_ta_manager.c

Change tee_ta_close_session() function to support panicked TA contexts.
Prior this change, the function did not expect referenced context
had previously panicked. Since recent changes for reloadable keep alive
TAs, referenced below, Panic on open session does completely release
context which session closure is expected to proceed to.
Fixes: fd10f62b8210 ("core: keep alive TA context can be created after TA has panicked")

core: fix session closure when open panicked

---

core/tee/tee_svc_storage.c

Fixes: https://github.com/OP-TEE/optee_os/issues/3004

core:tee: remove redundant tee_obj_attr_to_binary() calls

---

core/arch/arm/plat-stm32mp1/shared_resources.c
core/arch/arm/plat-stm32mp1/stm32_util.h

Change `stm32mp_periph_is_non_secure()` to cover unregistered and non-secure registered resources. This allows to remove `stm32mp_periph_is_unregistered()` that also relates to non-secure
resources.
This change also lowers verbosity of shared resource registration trace from info to debug log level.

stm32mp1: remove stm32mp_periph_is_unregistered()

---

core/arch/arm/plat-stm32mp1/shared_resources.c
core/arch/arm/plat-stm32mp1/stm32_util.h

Helper functions for stm32mp1 platform to access a SoC interface
register that can be accessed from several drivers and services.
They all use a common spinlock to ensure atomic update of the
register content.
Helpers: io_mask32_stm32shregs(), io_setbits32_stm32shregs(),
io_clrbits32_stm32shregs() and io_clrsetbits32_stm32shregs().

stm32mp1: common SoC registers protections

---

core/arch/arm/kernel/mutex.c

Prior to this patch mutex_destroy() was incorrectly testing the lock state.
With this patch the test is corrected to avoid panic() on unlocked mutexes.
Tested-by: Jens Wiklander <jens.wiklander@linaro.org>

core: bugfix mutex_destroy()

---

core/arch/arm/kernel/kern.ld.S

tee.elf currently has an INTERP segment that contains
"/usr/lib/ld.so.1". This is totally meaningless, so remove it by
discarding the .interp section in the linker script.

core: arm: kern.ld.S: discard .interp section

---

core/tee/tee_rpmb_fs.c

The overflow check used when computing the number of the last block in
the RPMB parition is incorrect. It causes an overflow when
rpmb_size_mult is 128, that is, when the partition size is 16 MiB.
Indeed, max_blk_idx is a uint16_t and we are trying to store 65536
(= 128 * (128 * 1024) / 256).
Fix this by using a 32-bit temporary variable to hold the result of the
multiplication (the number of blocks), then subtract 1 to get the last
block number using SUB_OVERFLOW().
Fixes: ea81076f7896 ("core: RPMB FS: check for potential overflows")
Fixes: https://github.com/OP-TEE/optee_os/issues/3012

core: RPMB FS: fix panic when RPMB partition size is 16 MiB

---

core/arch/arm/include/mm/core_memprot.h
core/arch/arm/mm/core_mmu.c
core/arch/arm/plat-stm32mp1/drivers/stm32mp1_pwr.c
core/arch/arm/plat-stm32mp1/drivers/stm32mp1_rcc.c
core/arch/arm/plat-stm32mp1/main.c
core/drivers/stm32_bsec.c
core/drivers/stm32_etzpc.c
core/drivers/stm32_i2c.c
core/drivers/stm32_rng.c

When MMU is ON, `io_pa_or_va()` returns a secure mapped virtual address if found, or falls back to a non-secure mapped address if found, or returns `NULL`.
This P-R introduces `io_pa_or_va_secure()` to get an address for a secure only interface
and  `io_pa_or_va_nsec()` to get an address for a non-secure only interface.
This P-R updates the drivers accordingly. However, most drivers calling  `io_pa_or_va()` are UART console drivers for which interface maybe secure or not, according to the platform. Therefore, all these drivers are not modified. There are stm32 drivers where `io_pa_or_va()` is repalced appropriate the new function.

core: new io_pa_or_va_secure() and io_pa_or_va_nsec()

---

core/arch/arm/include/kernel/abort.h
core/arch/arm/include/kernel/thread.h
core/arch/arm/kernel/abort.c
core/arch/arm/kernel/user_ta.c
core/arch/arm/mm/tee_pager.c
core/arch/arm/tee/arch_svc.c

Instead of printing TA stack dump in abort mode, save the required
information and print it from user_ta_enter() in thread context. This
allows dumping the stack also for paged TAs.

core: print TA stack dump from thread context

---

core/arch/arm/plat-stm32mp1/main.c

Correct missing return in function stm32_get_gpio_bank_base(). Prior
this change, platform may fail to boot and with debug trace:
E/TC:0 0 assertion 'bank <= GPIO_BANK_K' failed at core/arch/arm/plat-stm32mp1/main.c:311 <stm32_get_gpio_bank_base>
Fixes: 68c4a16b37c7 ("stm32mp1: use phys_to_virt_io_secure() where expected")

stm32mp1: fix stm32_get_gpio_bank_base()

---

lib/libutee/arch/arm/user_ta_entry.c
lib/libutee/tee_api_private.h
ta/arch/arm/user_ta_header.c

As __ta_entry() acts as function entry point, it makes sense to
logically return from this api only via utee_return(). So remove
redundant __noreturn from __utee_entry().

Remove redundant __noreturn from __utee_entry()

---

mk/config.mk

The current release is 3.5.0, change the revision to match.
Fixes https://github.com/OP-TEE/optee_os/issues/3028

config.mk: fix CFG_OPTEE_REVISION_MINOR

---

lib/libmbedtls/mbedtls/library/bignum.c
lib/libutee/tee_api_arith_mpi.c

The W variable is 3072 on AArch64 with MBEDTLS_MPI_WINDOW_SIZE set to 6
for maximum performance. Instead of allocating such a large variable on
the stack use mempool_alloc().

libmbedtls: mbedtls_mpi_exp_mod(): reduce stack usage

---

core/drivers/stm32_i2c.c
core/include/drivers/stm32_i2c.h

Introduce stm32_i2c_read_write_membyte() to operate a single byte
data transfer in memory mode. This function will be used by the
power management sequence in order to relax pager resident memory
footprint when I2C need to execute in an unpaged context.

stm32_i2c: optimized I2C 1 byte memory transfer

---

core/arch/arm/kernel/kern.ld.S

The linker script for the TEE core exports two symbols using the
PROVIDE() keyword. This keyword is not needed; it makes no difference
because when CFG_VIRTUALIZATION=y the symbols are *not* defined
elsewhere, and they *are* used by a C file, so that a normal symbol will
do the same. Therefore, remove the keyword.
[1]: https://sourceware.org/binutils/docs/ld/PROVIDE.html#PROVIDE
"The PROVIDE keyword may be used to define a symbol [...] only if it is
referenced but not defined."

virt: kern.ld.S: remove PROVIDE() keyword

---

core/arch/arm/plat-imx/conf.mk

The Digi CCIMX6UL SBC Pro does not fit any of the existing flavours, add a new flavour for it.
The board ships with 256MB of RAM and the default console of the SoM is Uart5.

Add plat-imx flavour: digi ccimx6ulsbcpro

---

mk/cleandirs.mk

Fixes the macro do-rm-f from outputting spurious empty lines if supplied
a large list of files.
Reviewed-by: Jerome Forissier <jerome@forissier.org>

mk/cleandirs.mk: avoid print spurious empty lines

---

core/drivers/stm32_i2c.c
core/include/drivers/stm32_i2c.h

This change saves DTB status value found in the I2C node and introduces `i2c_is_secure()` to state the bus state.

stm32_i2c: save DTB status

---

lib/libmbedtls/mbedtls/library/bignum.c

With W allocated in the mempool instead of the stack it more important
to utilize the mempool in a stack like way.
With this patch allocation and initialization of W is moved to a point
where all following mempool allocations are free before the function
returns.
This reduces maximum memory consumption of mempool in regression case
8101 for an AArch64 TA in from 17280 to 7640 bytes. Figures for an
AArch32 TA are 12040 to 5288 bytes.

libmbedtls: mbedtls_mpi_exp_mod(): optimize mempool usage

---

core/arch/arm/plat-imx/imx6.c
core/arch/arm/plat-imx/imx6ul.c
core/arch/arm/plat-imx/imx7.c
core/arch/arm/plat-imx/imx_caam.c
core/arch/arm/plat-imx/imx_caam.h
core/arch/arm/plat-imx/sub.mk

This series 
1. Adds a simple set of routines to set the CAAM job-rings to normal world
2. Calls that routine for i.MX6 and i.MX7 processors.
This is not a full fledged CAAM driver, which both NXP and Microsoft have written but, not thus far upstreamed code for. This is simply about setting the default permissions of the CAAM.
The expectation is that a full CAAM driver will assign some job-rings to secure and some job-rings to normal world and will communicate job-ring ownership via DTB settings.
Setting job-ring ownership when transitioning from secure to non-secure world is best done in OPTEE rather than u-boot and so if this code is applied in OP-TEE the next step is to stop setting job-ring permissions in u-boot.

Master+imx caam fix

---

core/arch/arm/dts/stm32mp157-pinctrl.dtsi
core/arch/arm/dts/stm32mp157a-dk1.dts
core/arch/arm/dts/stm32mp157c-dk2.dts
core/arch/arm/dts/stm32mp157c-ev1.dts
core/arch/arm/dts/stm32mp157c.dtsi
core/drivers/stpmic1.c
core/drivers/sub.mk
core/include/drivers/stpmic1.h
core/include/dt-bindings/mfd/st,stpmic1.h

This P-R introduced a driver STPMIC1 chip.
STPMIC1 is a power management chip for the stm32mp1 platform. It is accessed through an I2C bus. STPMIC1 provides regulators and other features as interrupt sources and watchdogs.
The P-R presents the driver through 2 change commits: basic driver and added API functions for low power sequences that will execute in an unpaged execution context.
This P-R start with a initial change commit to upgrade stm32mp1 DTS files to those found from Linux kernel 5.2-rc1 that defines the STPMIC1 DT nodes and bindings, needed by the driver.

stm32mp1: introduce STPMIC1, a external regulator control chip

---

core/arch/arm/kernel/generic_boot.c
core/arch/arm/plat-stm32mp1/main.c
core/include/console.h
core/kernel/console.c

This change makes generic boot to discover non-secure memory and
console configuration from the external DTB only, no more from the
embedded DTB as prior this change. When generic boot attempts to access
embedded DTB, the embedded DTB gets located in init read-only data
section become unnecessary too big. With this change, embedded DTB now
lies in the standard pageable read-only data section, relaxing memory
footprint constraint.

core: move embedded DTB out of init sections

---

core/arch/arm/tee/arch_svc.c

This change fixes a core panic occurrence when a TA panics while core
is built with `CFG_TEE_CORE_DEBUG=y` and `CFG_UNWIND=n`.
When a TA panics while `CFG_UNWIND=n,` the thread specific data holding
`abort_type` was not loaded prior this change. The abort sequence that
print information to the console dumps now does not attemp to dump
un-relevant CPU register content.
Prior this change, ARM32 code could panic since reading an invalid SPSR
value when printing CPU state to the console, with an error trace like:
```
E/TC:? 0 TA panicked with code 0xbeef
E/TC:? 0 assertion 'thread_get_exceptions() & THREAD_EXCP_FOREIGN_INTR' failed at core/arch/arm/include/kernel/misc.h:22 <get_core_pos>
E/TC:0 0 Panic at core/kernel/assert.c:28 <_assert_break>
```
Prior this change ARM64 code printed …

core: fix core panic when CFG_UNWIND=n

---

core/arch/arm/kernel/generic_boot.c

Move info trace "Embedded DTB found" so that it is output only once
even when get_embedded_dt() is called several times.

core: ensure embedded DTB found trace is output once

---

core/arch/arm/mm/mobj.c

`mobj_with_fobj_get_pa()` gets called when a TA crashed and core prints some information about the TA. This change ensures the function belongs to an unpaged section.

core: fix missing unpaged constraint on mobj_with_fobj_get_pa()

---

core/include/kernel/dt.h

Correct _fdt_get_status() function description since it returns a
positive or null value on success and -1 on error.

core: correct _fdt_get_status() description

---

core/arch/arm/include/sm/sm.h
core/arch/arm/plat-imx/sm_platform_handler.c
core/arch/arm/plat-ti/sm_platform_handler_a15.c
core/arch/arm/plat-ti/sm_platform_handler_a9.c
core/arch/arm/sm/sm.c
core/arch/arm/sm/sm_a32.S
core/arch/arm/sm/sm_private.h

Explicit return values for `sm_platform_handler()` and `smc_std_handler()` to state whether the SMC was handled or shall be relayed to another layer.

Explicit return values for `sm_platform_handler()` and `smc_std_handler()`

---

ta/arch/arm/link_shlib.mk

If a TA shared library is created, and needs to call OP-TEE functions,
it needs to link against the TEE libraries (libutee, libutils etc.) in
a similar way to TAs.
This patch adds the proper flags.

TA dev kit: always link shared libraries against OP-TEE libraries

---

core/arch/arm/kernel/abort.c

Restores user TA stack base and size __print_stack_unwind_arm64() to be able
to dump the user TA stack.
Fixes: c0bc8d0e7d72 ("core: print TA stack dump from thread context")

core: fix AArch64 user TA stack dump
