OP-TEE/optee_os

core/arch/arm/pta/system.c, core/include/kernel/huk_subkey.h, lib/libutee/include/pta_system.h
Enable derivation of device and Trusted Application unique keys that can
be used by different Trusted Applications directly. An example of use
case could be when you need to encrypt some data in a Trusted App and
then give it back to normal world.
By default device unique properties (HUK and TA UUID) will be used when
deriving a key. However, the one calling the pTA derive key function
also have the ability to provide some extra data that will be mixed in
together with existing device unique properties. That gives the ability
to derive keys that are not only device and Trusted Application unique,
but also tied to some additional data, it could for example be a
password or something similar.
I have test cases in xtest ready for this also, I'll send that PR right after this one has been …
=> pta: add support for deriving device and TA unique keys

core/arch/arm/plat-imx/imx6.c, core/arch/arm/plat-imx/imx_caam.c
Commit 4cb61ae7d98e ("core: imx: Add simple CAAM permissions set routine")
has the following cast, which has a typo resulting in a forward declaration
of "struct caam_ctrl" which is not in fact a structure defined anywhere.
struct imx_caam_ctrl *caam = (struct caam_ctrl *)CAAM_BASE;
It looks like it shouldn't compile but, it does.
Fixes: 4cb61ae7d98e ("core: imx: Add simple CAAM permissions set routine")
Signed-off-by: Bryan O'Donoghue <bryan.odonoghue@linaro.org>
Reported-by: Jerome Forissier <jerome@forissier.org>
=> core: imx: Fix compilation warning leading to build breakage

lib/libutee/arch/arm/user_ta_entry.c, ta/arch/arm/user_ta_header.c, ta/ta.mk
Since commit eeb866c431db ("Add TA entry point function: __ta_entry()"),
__ta_entry() is the first function in the user space call stack, not
__utee_entry(). Therefore, the asm(".cantunwind") declaration should be
moved from __utee_entry() to __ta_entry().
When utee_return() was moved from __utee_entry() to __ta_entry() by
commit fde3a7f212f8 ("Remove redundant __noreturn from __utee_entry()"),
it caused a regression in xtest 1010.3. The stack unwinding would enter
an infinite loop as follows:
E/TC:? 0 User TA prefetch-abort at address 0x0 (translation fault)
E/TC:? 0  fsr 0x00000005  ttbr0 0x3f07906a  ttbr1 0x3f06c06a  cidr 0x2
E/TC:? 0  cpu #7          cpsr 0x80000110
E/TC:? 0  r0 0x00000001      r4 0x00161448    r8 0x00161438   r12 0x00152f80
E/TC:? 0  r1 0x00000002      r5 0x00152f40 …
=> arm32: prevent unwinding of __ta_entry()

core/arch/arm/tee/entry_fast.c
Outside of the initial boot or error cases OP-TEE is quiet, this
is a notable exception that dirties up the boot log and has caused
confusion during kernel boot by users. It is only needed for
debug purposes.
Reduce this message to only debug verbosity.
`Signed-off-by: Andrew F. Davis <afd@ti.com>`
=> tee: entry_fast: reduce verbosity of dynamic shared memory message

core/tee/tee_svc_storage.c
According to the GlobalPlatform specification it should be possible to
call TEE_StartPersistentObjectEnumerator(..) on an enumerator that
already has been started. When doing that we trigged an assert and ended
up with a panic. This patch fixes that issue by ensuring that we are
closing the currently open directory before re-opening or opening
another directory in those cases where
TEE_StartPersistentObjectEnumerator(..) are called again and again with
no reset done in-between.
Fixes: https://github.com/OP-TEE/optee_os/issues/3093
Reported-by: Daniel McIlvaney <damcilva@microsoft.com>
(I'll see if I can add a couple of test to xtest for this also).
=> svc: fix behavior of TEE_StartPersistentObjectEnumerator

.shippable.yml, MAINTAINERS, core/arch/arm/plat-k3/platform_config.h
The only difference from AM65x that OP-TEE cares about currently is the
GICC offset and size. Update the same.
=> plat-k3: Add J721E device support

core/arch/arm/include/sm/optee_smc.h, core/arch/arm/tee/entry_fast.c
We need some way to tell normal world if OP-TEE does support
virtualization. Prior to this patch NW had to probe for virtualization by
calling OPTEE_SMC_VM_DESTROYED which is not reliable.
New capability flag OPTEE_SMC_SEC_CAP_VIRTUALIZATION solves this issue.
=> core: introduce OPTEE_SMC_SEC_CAP_VIRTUALIZATION

core/arch/arm/mm/tee_pager.c
Fixes a potential NULL dereference in
tee_pager_pgt_save_and_release_entries() in case a struct user_ta_ctx
doesn't have an areas pointer allocated yet.
=> core: pager: fix NULL deref in tee_pager_pgt_save_and_release_entries()

core/arch/arm/include/arm.h, core/arch/arm/include/arm32.h, core/arch/arm/include/arm64.h, core/arch/arm/include/kernel/cache_helpers.h, core/arch/arm/include/kernel/tlb_helpers.h, core/arch/arm/kernel/cache_helpers_a32.S, core/arch/arm/kernel/cache_helpers_a64.S, core/arch/arm/kernel/thread_a32.S, core/arch/arm/kernel/thread_a64.S, core/arch/arm/mm/tee_pager.c
Increase speed by more optimized cache maintenance. Also some TLB invalidations are optimized.
=> Cache optimizations 

core/lib/libtomcrypt/src/misc/burn_stack.c, core/lib/libtomcrypt/src/misc/zeromem.c
LTC_CLEAN_STACK uses burn_stack() API that uses a recursive call which
leads to approx. double the size of stack cleaned than expected on ARM64.
So this causes stack overflow corrupting canaries in case we perform a
SHA512 hash operation which utilizes maximum stack as compared to other
libtomcrypt APIs. So get rid of this recursive call via using variable
length array to clean stack.
Also, convert zeromem() API as a wrapper to call memzero_explicit().
Fixes: ad565116a0d7 ("core: crypto: libtomcrypt: enable LTC_CLEAN_STACK")
Suggested-by: Daniel Thompson <daniel.thompson@linaro.org>
=> core: crypto: libtomcrypt: fix LTC_CLEAN_STACK bug

core/arch/arm/arm.mk, ldelf/ftrace.c, lib/libutee/arch/arm/utee_mcount_a32.S, lib/libutee/include/user_ta_header.h, lib/libutils/isoc/arch/arm/setjmp_a32.S, lib/libutils/isoc/arch/arm/sub.mk, lib/libutils/isoc/include/setjmp.h, ta/arch/arm/user_ta_header.c
This patch-set adds ftrace support for 32 bit apps as well as function execution time. So after this patch-set function graph would look something like:
```
| __ta_entry() {
|  __utee_entry() {
1.168 us |   ta_header_get_session();
1.392 us |   __utee_to_param();
|   TA_InvokeCommandEntryPoint() {
|    ta_entry_params_access_rights() {
31.392 us |     TEE_CheckMemoryAccessRights();
28.176 us |     TEE_CheckMemoryAccessRights();
173.984 us |    }
202.448 us |   }
1.152 us |   __utee_from_param();
|   ta_header_save_params() {
.656 us |    memset();
5.488 us |   }
275.824 us |  }
281.424 us | }
```
Looking forward to your valuable feedback/comments.
Regards,
Sumit
=> ftrace: Add 32 bit apps and function execution time support

core/lib/libtomcrypt/src/math/rand_bn.c, core/lib/libtomcrypt/src/pk/ecc/ecc_sign_hash.c
This is originates from the LibTomCrypt upstream mitigation patch:
f0a51bbdbd ("ecc_sign_hash blinding CVE-2018-12437") [1]
but with modifications to fit into the current LibTomCrypt version used
by OP-TEE (use the old function name rand_bn_range(..) instead of the
new name rand_bn_upto(..)).
[1] https://github.com/libtom/libtomcrypt/commit/f0a51bbdbd50e03a43914c9ee912c451b6ad82e5
Fixes: OP-TEE-2019-0018
Tested-by: Joakim Bech <joakim.bech@linaro.org> (QEMU-v7)
Reported-by: Santos Merino del Pozo <santos.research@gmail.com>
Suggested-by: Santos Merino del Pozo <santos.research@gmail.com>
=> ecc_sign_hash blinding CVE-2018-12437

scripts/gen_ldelf_hex.py
Simple port for gen_ldelf_hex to python3.
=> scripts: port gen_ldelf_hex to python3

core/arch/arm/dts/stm32mp157a-dk1.dts, core/arch/arm/dts/stm32mp157c-ed1.dts, core/arch/arm/plat-stm32mp1/drivers/stm32mp1_clk.c, core/arch/arm/plat-stm32mp1/main.c, core/arch/arm/plat-stm32mp1/shared_resources.c, core/arch/arm/plat-stm32mp1/stm32_util.h
This series aims at allowing one to use upstream OP-TEE next 3.6.0 together with upstream Linux kernel (release 5.2) which support stm32mp1 ST boards but not yet with a secure hardened RCC SoC interface.
Once upstream Linux kernel will support fully secured stm32mp1, the ST board DTS files will be updated to enable back RCC secure hardening.
With this series, RCC secure hardening mandates secure bootloader also disabled RCC secure hardening which also complies with stm32mp1 support in upstream TF-A package.
=> stm32mp1: disable RCC security in ST boards

core/include/console.h, core/kernel/console.c
Commit 770b2afacf33 ("core: more flexible console init from DT") has
split configure_console_from_dt() in two parts, the first one being
moved to a new function: get_console_node_from_dt(). Unfortunately,
this function may return pointers to a freed buffer.
Fix the problem by allocating each output string on the heap and letting
the caller clean on return.
Fixes: 770b2afacf33 ("core: more flexible console init from DT")
=> core: console: fix use after free when CFG_DT=y

core/arch/arm/kernel/generic_entry_a64.S
Add CFG_DT_ADDR for a64 to override the DT address passing
through arg2.
Signed-off-by: Ying-Chun Liu (PaulLiu) <paulliu@debian.org>
=> core: kernel_generic_entry_a64.S: support CFG_DT_ADDR

ldelf/ftrace.c
Fixes warning in ftrace_init():
ldelf/ftrace.c: In function ‘ftrace_init’:
ldelf/ftrace.c:47:9: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
fbuf = (struct ftrace_buf *)finfo->buf_start.ptr64;
^
Fixes: c96d7091b566 ("ftrace: Enable support for 32 bit apps")
=> ldelf: fix warning in ftrace_init()

core/arch/arm/mm/core_mmu.c
Newest versions of GCC (v9.1.0 at least) are unhappy about subtraction
from array pointer:
core/arch/arm/mm/core_mmu.c: In function 'core_init_mmu_map':
core/arch/arm/mm/core_mmu.c:523:30: warning: array subscript -1 is outside array bounds of 'const struct core_mmu_phys_mem[]' [-Warray-bounds]
523 |  for (mem = start; mem < end - 1; mem++) {
|                          ~~~~^~~
In file included from core/include/initcall.h:9,
from core/arch/arm/include/kernel/generic_boot.h:8,
from core/arch/arm/mm/core_mmu.c:11:
core/include/scattered_array.h:100:29: note: while referencing '__scattered_array_end'
100 |   static const element_type __scattered_array_end[0] __unused \
|                             ^~~~~~~~~~~~~~~~~~~~~
This is valid warning, as such pointer arithmetic produces undefined …
=> core_mmu: fix "outside of array bounds" warning

core/arch/arm/mm/core_mmu.c
Suppose in init stage all physical memory registered is in 0~4G,
the IPS bits (bit34~32) is set 0. Later a physical address 0x100000000
is dynamically mapping with core_mmu_add_mapping, since 0x100000000
is higher than 4G, the IPS bits of TCR_EL1 register should be updated
to 0x1. Otherwise the below panic occurs:
E/TC:00 check_pa_matches_va:1805 va 0x82a00000 maps 0x100000000, expect 0x0
As currently TCR_EL1 register is only set in init stage, this patch
also updates the register in core_mmu_add_mapping.
Signed-off-by: Fangsuo Wu <fangsuowu@asrmicro.com>
=> core: mmu: Update TCR_EL1 register when new physical address added

ldelf/main.c, ldelf/ta_elf.c, ldelf/ta_elf.h
Prior to this patch ldelf relied on e_entry in the ELF header to point
anywhere but at the lowest possible executable address to tell that it's
not a legacy TA. This isn't enough since all TAs can use this entry
address depending on compiler and linker. The only reliable indicator
that the TA is not a legacy TA is that the depr_entry field of the TA
header is UINT64_MAX. Unfortunately this means assuming that the ELF is
not a legacy TA at load time and that the process needs to be restarted
in case it turns out that it was a legacy TA.
With this patch we have reliable detection of non-legacy TAs, but with
increased load time for legacy TAs since the main ELF needs to be loaded
and verified twice due to the TA store interface.
=> ldelf: accurate non-legacy TA check

scripts/ta_bin_to_c.py
`zlib.compress()` behaves differently in python2 and python3.
It returns a string in python2, and it returns bytes object in python3.
Hence, the script fails during `ord()` conversion in python3.
This commit fixes by checking python version to perform proper
conversion before writing to a file.
Signed-off-by: Pipat Methavanitpong <pipat.methavanitpong@linaro.org>
=> ta_bin_to_c.py: fix hex string conversion in python3

ta/arch/arm/link.mk, ta/mk/build-user-ta.mk, ta/ta.mk
When a library is changed (libutee.a, libutils.a, etc.) the in-tree TAs
are re-built from scratch. We can easily avoid recompilation and only
re-link instead.
For example, without this patch:
$ make -s -j10
$ touch out/arm-plat-vexpress/export-ta_arm32/lib/libutee.a
$ make out/arm-plat-vexpress/ta/avb/023f8f1a-292a-432b-8fc4-de8471358067.elf
CC      out/arm-plat-vexpress/ta/avb/entry.o
CC      out/arm-plat-vexpress/ta/avb/user_ta_header.o
AS      out/arm-plat-vexpress/ta/avb/ta_entry_a32.o
LD      out/arm-plat-vexpress/ta/avb/023f8f1a-292a-432b-8fc4-de8471358067.elf
With this patch applied:
$ make -s -j10
$ touch out/arm-plat-vexpress/export-ta_arm32/lib/libutee.a
$ make …
=> In-tree TAs: avoid recompiling when a library changes

scripts/sign.py, ta/arch/arm/link.mk, ta/arch/arm/link_shlib.mk
Signed-off-by: Markus S. Wamser <markus.wamser@mixed-mode.de>
This modifies `scripts/sign.py` to support offline signing.
The behaviour should not change for users that provide the private key in `keys/default_ta.pem`.
In case no privat key is found, the digest is written to a file and a notice is printed. If a matching file containing a signature is found, the signature is verified against the current digest of the TA and the public key and applied only if verification succeds.
Naming of files and encoding of contents follows https://github.com/Microsoft/ms-tpm-20-ref/tree/master/Samples/ARM32-FirmwareTPM/ta_prod_signing_scripts. While not explicitly tested, the workflows should be compatible.
To produce an ofline signature with OpenSSL (1.1.0):
```
DIGFILE=some-U-U-I-D.dig # as printed …
```
=> support offline signing of TAs

lib/libutils/isoc/arch/arm/arm32_aeabi_divmod.c
Some of the aeabi functions provided are undocumented and are not called from anywhere. This patch removes them entirely.
This resolves #3143.
=> Remove unneccessary __aeabi functions

scripts/sign.py
The script now exits with a retun value of 1 instead of 0 if the key is not usable for signing.
A typo in regenerating the digest during stiching was fixed.
Command dispatching was simplified.
Signed-off-by: Markus S. Wamser <markus.wamser@mixed-mode.de>
=> Fixup to 'Support offline signing of TAs.'

mk/lib.mk
```
With 1cdd95a2a46d ("Support offline signing of TAs.") the sign.py script
now expects the token "sign" first in the arguments in order to do its
original purpose. So effectively to sign a TA or a library the script
now has to be called as "./scripts/sign.py sign ..." or there's to be
errors like:
SIGN    ../out-os-qemu/ta_arm32-lib/libutee/527f1a47-b92c-4a74-95bd-72f19f4a6f74.ta
usage:
sign.py command [ arguments ]
command:
sign        Generate signed loadable TA image file.
Takes arguments --uuid, --in, --out and --key.
digest      Generate loadable TA binary image digest for offline
signing. Takes arguments  --uuid, --in and --dig.
stitch      Generate loadable signed TA binary image file from
TA raw image and its signature. Takes arguments
--uuid, --in, --out, and --sig.
sign.py …
```
=> Fix signing in-tree TAs and libraries

core/arch/arm/arm.mk, core/arch/arm/kernel/thread_a32.S, core/arch/arm/kernel/thread_a64.S, core/arch/arm/sm/sm_a32.S
Adds CFG_CORE_WORKAROUND_NSITR_CACHE_PRIME which if 'y' enables
protection against a tool like Cachegrab
(https://github.com/nccgroup/cachegrab), which uses non-secure
interrupts to prime and later analyze the L1D, L1I and BTB caches to
gain information from secure world execution.
=> core: add CFG_CORE_WORKAROUND_NSITR_CACHE_PRIME

core/arch/arm/include/sm/sm.h, core/arch/arm/kernel/thread.c, core/arch/arm/kernel/user_ta.c, core/arch/arm/sm/sm_a32.S, core/include/kernel/tee_ta_manager.h, core/kernel/tee_ta_manager.c, ldelf/ftrace.c, ldelf/ftrace.h, ldelf/include/ldelf.h, ldelf/main.c, lib/libutee/arch/arm/arm32_user_sysreg.txt, lib/libutee/arch/arm/ftrace/ftrace.c, lib/libutee/include/arm64_user_sysreg.h, lib/libutee/include/arm_user_sysreg.h, lib/libutee/include/user_ta_header.h, scripts/arm32_sysreg.py, ta/ta.mk
This patch-set adds function execution time support and is in continuation of PR: https://github.com/OP-TEE/optee_os/pull/3080 with comments incorporated. So after this patch-set function graph would look something like:
```
| __ta_entry() {
|  __utee_entry() {
1.168 us |   ta_header_get_session();
1.392 us |   __utee_to_param();
|   TA_InvokeCommandEntryPoint() {
|    ta_entry_params_access_rights() {
31.392 us |     TEE_CheckMemoryAccessRights();
28.176 us |     TEE_CheckMemoryAccessRights();
173.984 us |    }
202.448 us |   }
1.152 us |   __utee_from_param();
|   ta_header_save_params() {
.656 us |    memset();
5.488 us |   }
275.824 us |  }
281.424 us | }
```
Looking forward to your valuable feedback/comments.
Regards,
Sumit
=> ftrace:  Add function execution time support

scripts/arm32_sysreg.py
pycodestyle v2.4.0 complains:
$ pycodestyle scripts/arm32_sysreg.py
scripts/arm32_sysreg.py:72:80: E501 line too long (80 > 79 characters)
scripts/arm32_sysreg.py:99:80: E501 line too long (80 > 79 characters)
Break those two lines before the 79 character limit.
Fixes: 4486d5866e238 ("libutee: add headers for user-space to access sysregs")
=> arm32_sysreg.py: shorten lines to <= 79 characters

core/arch/arm/kernel/user_ta.c
Fix incorrect usage of ROUNDUP macro during ftrace data dump to normal
world. It leads to random crashes dependent on ftrace buffer size.
Fixes: 153479acb74e ("core: dump ftrace data with ldelf")
=> core: ftrace: fix incorrect usage of ROUNDUP

core/arch/arm/include/kernel/unwind.h
Fix a build failure when CFG_TEE_CORE_LOG_LEVEL=0,
core/arch/arm/kernel/abort.c: In function ‘__print_stack_unwind’:
core/arch/arm/kernel/abort.c:85:2: error: too few arguments to function
‘print_stack_arm64’
print_stack_arm64(TRACE_ERROR, &state, thread_stack_start(),
^~~~~~~~~~~~~~~~~
=> core: unwind: fix function args for print_stack_arm64

core/arch/arm/pta/secstor_ta_mgmt.c, core/include/signed_hdr.h, scripts/sign.py
build: restore TA --version argument to signing script
Restores argument --version to script sign.py to allow user to
set the trusted application version identifier in the signed
header of the TA binary image. This argument was wrongly removed
while review fixed referred to below.
Fixes: 1cdd95a2a46d ("Support offline signing of TAs.")
...followed by a minor fixup in `sign.py`
=> restore TA version arguement in sign.py

scripts/checkpatch_inc.sh
Uses the --strict option with checkpatch to catch more of the common style
issues. Ignoring the PREFER_KERNEL_TYPES since we are normally not using
those types. CAMELCASE is also ignored for now since it triggers many false
positives due to the TEE_Result type.
=> checkpatch: use --strict option

scripts/checkpatch_inc.sh
Adds --ignore CONCATENATED_STRING to checkpatch to allow constructs
like:
DMESG("value1 %"PRIX32" value2 %"PRIX32, v1, v2);
Without this we're force to use:
DMESG("value1 %" PRIX32 " value2 %" PRIX32, v1, v2);
Which is a bit harder to read, especially for more complicated cases.
=> checkpatch: allow string concatenation without space

ldelf/ldelf.mk, lib/libutee/arch/arm/utee_syscalls_a32.S, lib/libutee/arch/arm/utee_syscalls_a64.S
Enable function trace for utee_* syscall assembly APIs for better view
of user-space to kernel switching.
Suggested-by: Jerome Forissier <jerome.forissier@linaro.org>
=> ftrace: enable trace for utee_* assembly APIs

core/kernel/tee_ta_manager.c
This patch fixes a possible NULL dereference in a debug print in
tee_ta_close_session() which is done before checking the supplied
parameter for NULL.
Fixes: 99164a05ff51 ("core: do not use virtual addresses as session identifier")
=> core: fix possible NULL dereference in tee_ta_close_session()

scripts/get_maintainer.py
When given the -m/-merge-check option, get_maintainer.py parses the
Acked-by and Reviewed-by tags that may be found in a patchset or
Github PR. In presence of several patches the tags should apply to
each patch individually, not to the whole patchset as is currently
done. As a result, the script may fail to report some unapproved
changes.
Fix this issue by splitting patchsets into individual patches before
processing.
=> get_maintainer.py: process patches individually

core/crypto.mk, core/lib/libtomcrypt/sub.mk, lib/libmbedtls/core/sub.mk
Compiler optimization flags -O0 or -Os are selected globally by the
config variable CFG_CC_OPTIMIZE_FOR_SIZE, but crypto code
(lib/libmbedtls and core/lib/libtomcrypt) is always built with -Os
when CFG_CRYPTO_SIZE_OPTIMIZATION=y. This is a bit inconvenient
when debugging crypto code because two flags have to be set, and it
is not obvious why CFG_CC_OPTIMIZE_FOR_SIZE would not influence crypto.
Since performance does not matter much when debugging, and -Os/-O0
does not make a huge difference anyway, it is wiser to keep the purpose
of the two CFG_ variables separated: CFG_CC_OPTIMIZE_FOR_SIZE should
control the -O flag for all sources, while CFG_CRYPTO_SIZE_OPTIMIZATION
should deal with other size-related settings in the crypto code
(namely: set -DLTC_SMALL_CODE for LibTomCrypt). …
=> Do not let CFG_CRYPTO_SIZE_OPTIMIZATION set -Os

core/arch/arm/kernel/link.mk
Allow using SOURCE_DATE_EPOCH when defining DATE_STR in order to support
reproducible builds.
See https://reproducible-builds.org/specs/source-date-epoch/
=> core: link.mk: support reproducible builds via SOURCE_DATE_EPOCH

core/arch/arm/kernel/thread_optee_smc_a32.S
Compilation with newer gcc versions fails:
core/arch/arm/kernel/thread_optee_smc_a32.S: Assembler messages:
core/arch/arm/kernel/thread_optee_smc_a32.S:29: Error: selected processor does not support `smc #0' in ARM mode
add the required .arch_extension sec to the recently added assembly
file.
=> core: add missing arch_extension to thread assembly

core/arch/arm/kernel/link.mk, ldelf/link.mk, ta/arch/arm/link.mk
This patch cleans up the command line where we use the C preprocessor
to better reflect the documented usage in the GCC man page, thus
preparing for Clang support.
1. When invoking the C preprocessor, there is no need for -Wp to pass
arguments, so remove it.
2. -MD is not supposed to take a file name when passed to cpp. The
dependency output file name is overridden with -MF.
3. Lastly, it is better to use -o to specify the output file instead
of redirecting standard output, because if an error occurs during
preprocessing we don't want the output file to be created.
=> build: do not use -Wp with the preprocessor and use -o instead of a redirection

.shippable.yml, core/arch/arm/plat-imx/conf.mk
Add Toradex Apalis iMX6D and iMX6Q platform flavors.
=> core: imx: add mx6dapalis/mx6qapalis platform flavor

scripts/get_maintainer.py
OSError is spelled incorrectly, causing the following error:
$ ./scripts/get_maintainer.py core/arch/arm/plat-imx/
Traceback (most recent call last):
File "./scripts/get_maintainer.py", line 102, in split_patchset
f = open(patchset, "r")
IsADirectoryError: [Errno 21] Is a directory: 'core/arch/arm/plat-imx/'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "./scripts/get_maintainer.py", line 292, in <module>
main()
File "./scripts/get_maintainer.py", line 242, in main
patches = split_patchset(arg)
File "./scripts/get_maintainer.py", line 103, in split_patchset
except OsError:
NameError: name 'OsError' is not defined
=> get_maintainer.py: fix spelling mistake

lib/libutils/ext/include/compiler.h
This breaks GCC Address Sanitizer, because it refuses to track
variables, that are stored in user sections. Even if those
sections are actually .bss and .data.
---
This should fix #3235
=> core: don't use __bss and __data attributes

core/arch/arm/kernel/thread.c, core/include/kernel/tee_ta_manager.h, core/kernel/tee_ta_manager.c
Current TA function execution time feature only reports user mode
execution time and exclude any non-user mode execution time. But in
case of syscalls which are essentially function invocations from TA
into the kernel, we shouldn't exclude syscall execution time in order
to account for actual function execution time.
So changes in this patch allows to incorporate syscall execution time
in the function graph output.
Fixes: f5df167c2ffb ("ftrace: Add function execution time support")
=> ftrace: exclude only foreign interrupt time

lib/libutils/isoc/bget_malloc.c
When CFG_CORE_SANITIZE_KADDRESS=y, most OP-TEE files are built with
address sanitizer flags except bget_malloc.c. As a result, the memcpy()
function in memcpy.c is instrumented, whereas the malloc context
structure (malloc_ctx) in bget_malloc.c is not. This causes the
following panic:
$ xtest --stats --alloc
E/TC:0 0 Panic at core/kernel/asan.c:189 <check_access>
E/TC:0 0  0x0e125c3d print_kernel_stack at optee_os/core/arch/arm/kernel/unwind_arm32.c:450
E/TC:0 0  0x0e13fcfb __do_panic at optee_os/core/kernel/panic.c:32 (discriminator 1)
E/TC:0 0  0x0e13e099 check_access at optee_os/core/kernel/asan.c:187 (discriminator 2)
E/TC:0 0  0x0e13e10f check_load at optee_os/core/kernel/asan.c:199
E/TC:0 0  0x0e13e187 __asan_load4_noabort at optee_os/core/kernel/asan.c:231 …
=> libutils: replace memcpy() with plain struct assignment

lib/libutils/ext/include/util.h
Adds the macro ROUNDUP_OVERFLOW() which rounds up like ROUNDUP() but also
checks the result for overflow and returns true on overflow.
=> util.h: add the macro ROUNDUP_OVERFLOW()

ldelf/ldelf.ld.S
__reloc_begin is currently defined as "__reloc_begin = ." just before
the various .rel.* output sections. The problem is, there is no
guarantee that the symbol will actually point to the first relocation
entry due to the alignment constraints on relocation sections. For
instance for Aarch64 relocations, alignment is 8 bytes, but
__reloc_begin has no alignment constraint, so it might end before the
first relocation (this issue was observed with the Clang linker,
ld.lld).
The patch forces the alignment of __reloc_begin on 8 bytes so that
there can be no unwanted padding.
=> ta: ldelf.ld.S: align __reloc_begin on 8 bytes

core/arch/arm/kernel/pm_stubs.c, core/arch/arm/kernel/sub.mk, core/arch/arm/plat-imx/pm/psci.c, core/arch/arm/plat-imx/pm/sub.mk, core/arch/arm/plat-sunxi/psci.c, core/arch/arm/plat-sunxi/sub.mk, core/drivers/sub.mk, core/include/drivers/imx_wdog.h
The GCC option -Wno-suggest-attribute=noreturn is not supported by
Clang. Instead of playing with compiler options, let's fix the code
according to the following rules:
- If a function is know to never return, it should have the __noreturn
attribute in the header file.
- If only some implementation of a function never returns, __noreturn
shall be applied to that particular implementation in the .c file.
=> Get rid of option -Wno-suggest-attribute=noreturn

core/include/kernel/dt.h
When CFG_DT != y, the stub function _fdt_fill_device_info() just
panics. Therefore it deserves the __noreturn attribute. Adding it makes
a Clang warning go away.
=> core: dt: add __noreturn to _fdt_fill_device_info() stub

mk/subdir.mk
Problem:
$ make -s out/arm-plat-vexpress/core/mm/fobj.o
$ rm out/arm-plat-vexpress/ldelf/ldelf.elf
$ rm out/arm-plat-vexpress/core/mm/fobj.o
$ make out/arm-plat-vexpress/core/mm/fobj.o
LD      out/arm-plat-vexpress/ldelf/ldelf.elf
GEN     out/arm-plat-vexpress/core/ldelf_hex.c
CC      out/arm-plat-vexpress/core/mm/fobj.o
Why would fobj.o depend on ldelf.elf and ldelf_hex.c? Answer is: it
shouldn't. This behavior is caused by FORCE-GENSRC$(sm) depending on
all the produce-<something> targets. In fact, such a dependency is
rarely needed. It makes sense for include files for instance; but
certainly not for C source files which are pulled in the build by other
means.
This patch introduces …
=> build: prevent produce-* from being forced built before current submodule

lib/libdl/dlfcn.c, lib/libutee/arch/arm/gprof/gprof_pta.c, lib/libutee/tee_socket_pta.c, lib/libutee/tee_system_pta.c
TEE_OpenTASession(), TEE_InvokeTACommand() calls using 0ms timeout
are replaced with TEE_INFINITE_TIMEOUT to avoid risk of being cancelled.
Signed-off-by: Cedric Auger <cauger@provenrun.com>
=> libutee,libdl: remove 0ms timeouts in TA invocations

core/arch/arm/plat-hikey/conf.mk
=> hikey: increase core heap size to 192 kB

lib/libutils/ext/include/compiler.h
Replaces attribute label identifier noreturn with __noreturn__ to
prevent conflicts when importing code which defines label noreturn
itself as a macro. This change applies suggestion from the GCC
documentation [1], applicable even prio GCC 4.x.x, cited below.
> You may optionally specify attribute names with ‘__’ preceding
> and following the name. This allows you to use them in header
> files without being concerned about a possible macro of the same
> name. For example, you may use the attribute name __noreturn__
> instead of noreturn.
[1] https://gcc.gnu.org/onlinedocs/gcc-8.3.0/gcc/Attribute-Syntax.html#Attribute-Syntax
=> libutils: relax noreturn label

core/core.mk
The cfg-depends-all function from mk/checkconf.mk has to be enclosed
in a $(eval ...) statement. Fix core/core.mk accordingly.
=> core: fix configuration check for CFG_PAGED_USER_TA

scripts/symbolize.py
When scripts/symbolize.py is used interactively and the input data is
copied and pasted into the terminal, both the input and output text are
displayed on the same screen. There is nothing preventing both text
streams from mixing up because it depends on buffering and how Python
reads and flushes its buffers.
Things usually go well with Python 2, but I have observed that Python 3
is more problematic. So the issue needs to be properly addressed. This
patch temporarily disables local echo so that only the processed text is
shown.
=> symbolize.py: disable terminal local echo

mk/config.mk
Now that the TA loader is in user space [1], the main reason why we had
introduced CFG_REE_FS_TA_BUFFERED [2] does not exist anymore. Therefore
we can set it to 'n' by default, thus saving some time and memory.
[1] commit d1911a85142d ("core: load TAs using ldelf")
[2] commit 7db24ad625b9 ("core: REE FS TAs: add option to verify
signature before processing")
=> core: REE FS TAs: disable CFG_REE_FS_TA_BUFFERED by default

core/arch/arm/plat-hikey/conf.mk
This reverts commit 28c75dbebc49 ("hikey: increase core heap size to
192 kB") which increased the core heap size in order to pass the AOSP
VTS. Unfortunately, this bigger value does not work well when the pager
is enabled: it causes lots of page faults and a massive slowdown (for
instance, 'xtest 1013' on HiKey620 completes in ~ 1.7 s with the
default heap size of 64 kB but takes ~ 53 s with 192 kB).
Therefore, revert to the previous configuration. A bigger value can
always be set on the command line or by other means when building for
AOSP.
=> Revert "hikey: increase core heap size to 192 kB"

scripts/symbolize.py
Commit 6b4fc6752b3c ("symbolize.py: disable terminal local echo") uses
termios functions on stdin unconditionally. Unfortunately, this will
cause an exception when stdin is not a terminal, for instance:
$ echo Hello | ./script/symbolize.py
Traceback (most recent call last):
File "./scripts/symbolize.py", line 497, in <module>
main()
File "./scripts/symbolize.py", line 484, in main
old = termios.tcgetattr(fd)
termios.error: (25, 'Inappropriate ioctl for device')
Add a try/except block and test 'old' and 'new' to deal with this
situation.
=> symbolize.py: fix exception when stdin is not a terminal

core/arch/arm/plat-rcar/conf.mk
R-car Gen3 SoCs have consistent core numbering across all
variations: CA57 cluster have core numbers 0-3 and CA53 have
numbers 4-7.
Also M3 flavor have 6 cores: two CA57s and four CA53s. Taking
into account consistent numbering, M3 will have the following
core ids: 0, 1, 3, 5, 6, 7. So, it is natural to set
CFG_TEE_CORE_NB_CORE = 8 for M3 flavor.
=> plat/rcar: set 8 cpu cores for all flavors

Makefile, core/kernel/show_conf.c, core/kernel/sub.mk, core/sub.mk, mk/config.mk, scripts/bin_to_c.py
This RFC PR introduces `CFG_SHOW_CONF_ON_BOOT` which I think would have come handy to know more about an IBART failure (see [here](https://github.com/OP-TEE/optee_os/pull/3268#issuecomment-532598986)).
FYI, here is what it looks like when booting QEMU OP-TEE with `CFG_SHOW_CONF_ON_BOOT=y`.
```
I/TC:
I/TC: Non-secure external DT found
I/TC: Switching console to device: /pl011@9040000
I/TC: OP-TEE version: 3.6.0-163-ga33f0c8924-dev (gcc version 6.2.1 20161016 (Linaro GCC 6.2-2016.11)) #2 Wed 18 Sep 2019 04:00:30 PM UTC arm
I/TC: Contents of conf.mk (decode with 'ascii85 -d | xz -d'):
<~rAT%)=o\O*k16n/!WXAE('"=7F>)aNi!pD(<a>\JP_<`1%r^hlZdit2!d[9Aa#s*r4r)8kZPS@2Eq3(:S]prR4BtVp2B1V\@]R
<"F9oC1/tCgM,2KTlf&:^$o5*^;d4.DYlrhS;IbLES'#u[":p'=qq\p5b+6jVdOlSX0'SDf++.nD#8i&gi%&NZ/#Bo%n6cGB"Z-9 …
```
=> [RFC] Dump configuration on boot

ldelf/main.c
The ldelf heap is not big enough to load some 64-bit TAs with several
shared libraries such as xtest 1006 when CFG_ULIBS_SHARED=y:
* regression_1006 Test Basic OS features
E/LD:  copy_section_headers:766 malloc
E/TC:? 0 init_with_ldelf:229 ldelf failed with res: 0xffff000c
E/TC:? 0 tee_ta_open_session:727 Failed. Return error 0xffff000c
regression_1006 FAILED
=> ldelf: increase heap size from 8 to 12 KiB

core/lib/libtomcrypt/src/pk/asn1/der/utf8/der_decode_utf8_string.c
Fix a vulnerability in der_decode_utf8_string as specified here:
https://github.com/libtom/libtomcrypt/issues/507
Patch manually picked from:
https://github.com/libtom/libtomcrypt/commit/25c26a3b7a9ad8192ccc923e15cf62bf0108ef94
[Joakim Bech: Extended commmit message]
Signed-off-by: Luigi Coniglio <werew@ret2libc.com>
Acked-by: Joakim Bech <joakim.bech@linaro.org>
Tested-by: Joakim Bech <joakim.bech@linaro.org> (QEMU v7)
=> Fixes #507 in LTC - vulnerability in der_decode_utf8_string

core/tee/tee_svc_cryp.c
Fixes for potential security issues found by Riscure's fuzzer tool.
I've tested this in QEMU v7, no regressions seen.
```bash
24105 subtests of which 0 failed
96 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```
=> Riscure fuzzer vuln

core/arch/arm/kernel/early_ta.c
I found what appears to be a flaw with early_ta_get_tag() while working
on some code measurement features.
I believe this has been working correctly due to the order of execution
(tag is calculated before any reads) and crypto_hash_final taking the 
minimum of digest length and buffer length, but this will be more
reliable.
Signed-off-by: Daniel McIlvaney <damcilva@microsoft.com>
=> Fix tag hash calculation for early TAs

core/lib/libtomcrypt/src/pk/asn1/der/utf8/der_decode_utf8_string.c
@werew FYI and btw, we tend to use "Signed-off-by" tags in patches in our tree, so I wonder, is it OK if I add the following to the commit message?
```
Signed-off-by: Luigi Coniglio <werew@ret2libc.com>>
```
Fix a vulnerability in der_decode_utf8_string as specified here:
https://github.com/libtom/libtomcrypt/issues/507
Patch created by @werew and manually picked from:
https://github.com/libtom/libtomcrypt/commit/25c26a3b7a9ad8192ccc923e15cf62bf0108ef94
=> Fixes #507 in LibTomCrypt

core/lib/libtomcrypt/src/ciphers/aes/aes.c
There is no check that the 'skey' structure has been properly
initialized. For example, the skey->rijndael.Nr is assumed to contain a
positive number corresponding to the number of AES rounds to perform. In
_rijndael_ecb_encrypt the skey->rijndael.Nr is subtracted by two, which
can result in an integer underflow if the structure hasn't been
initialized correctly.
By clamping the value for skey->rijndael.Nr into the valid rounds for
AES we can return an error instead of ending up reading outside the
boundaries (of skey->rijndael.eK).
Patch manually picked from [1].
Link: [1] https://github.com/libtom/libtomcrypt/commit/7b4a5c1dcf2803e9c6cbcbc2458db9317e6fb8ca
Tested-by: Joakim Bech <joakim.bech@linaro.org> (QEMU v7)
Reported-by: Martijn …
=> ltc: check range in _rijndael_ecb_ functions

CHANGELOG.md, mk/config.mk, scripts/update_changelog.py
@OP-TEE/maintainers please start testing your devices/platforms and add `Tested-by: ...` in the comments. Release candidate tag will be sent out shortly.
I've also written a python script that makes it quick and easy to create/update the `CHANGELOG.md`. The changelog updates in this commit has been generated by that script. Another change is that it also lists the other gits that makes up the core of the OP-TEE project.
// Joakim
=> Update CHANGELOG for 3.7.0

core/arch/arm/include/arm.h, core/arch/arm/kernel/misc_a32.S, core/arch/arm/kernel/misc_a64.S, mk/config.mk
If the MT bit is set the affinities are shifted in the MPIDR register
so the get_core_pos_mpidr functions needs to be modified accordingly.
This is necessary to make OP-TEE to be able to run on multi-threaded
systems. The number of threads/core can be modified by the
CFG_THREAD_CORE_SHIFT makefile parameter. The default value is the
existing single threaded mode.
Change-Id: Ibfacad34ac2bc67b1d0b7929f731da6406a97b5a
Signed-off-by: Imre Kis <imre.kis@arm.com>
=> core: Add support for multi-threaded MPIDR values

core/arch/arm/include/sm/optee_smc.h
Update the value of OPTEE_SEC_CAP_VIRTUALIZATION as it currently conflicts
with OPTEE_SEC_CAP_DYNAMIC_SHM
Signed-off-by: Michalis Pappas <mpp@opensynergy.com>
=> core: Fix value of OPTEE_SMC_SEC_CAP_VIRTUALIZATION

core/arch/arm/plat-imx/conf.mk
Currently, using an upstream kernel with i.MX6/7 devices and OP-TEE
results in OP-TEE stalling during the loading of trusted applications.
OP-TEE tries to use the CAAM for verification, unfortunately the
upstream kernel will turn off the clocks for the CAAM, resulting in the
bus transaction stalling on the bus and the processors requiring a hard
reset. Disable the NXP CAAM driver until the clocks issues are resolved.
This is the same problem I already reported in the initial CAAM pull requests.
One could argue that this is about platform configuration, but my expectation
is that upstream OP-TEE works with an upstream kernel without required
additional configuration.
=> core: imx: disable CAAM for all i.MX6/7 flavors

core/arch/arm/plat-imx/registers/imx6.h
The i.MX6UL/L variants contains additional UARTs which are not present
on the Cortex A9 variants. Add them to register file so they can be used
for new board definitions.
cc @clementfaure
=> plat-imx: add UART6 & 7 for i.MX6UL/L

core/arch/arm/arm.mk
When CFG_FTRACE_SUPPORT=y, thumb mode should not be used in TA code,
because the ftrace code assumes arm instructions. Therefore we have to
pass the -marm flag to the compiler and assembler. This is correctrly
done for the C compiler but not for the assembler -- fix that.
The same fix applies for assembler files in the TEE core when
CFG_SYSCALL_FTRACE=y.
Fixes a crash in the setjmp()/longjmp() test of xtest 1006 when GCC 6.2
is used to build the user space libutils.a (more precisely:
lib/libutils/isoc/arch/arm/setjmp_a32.S):
E/TC:? 0 User TA prefetch-abort at address 0x0 (translation fault)
E/TC:? 0  fsr 0x00000005  ttbr0 0x0e19206a  ttbr1 0x0e18806a  cidr 0x2
E/TC:? 0  cpu #1          cpsr 0x60000110
E/TC:? 0  r0 0x00000000      r4 0x00115780    r8 0x00000000   r12 0x00115658
E/TC:? 0 …
=> ftrace: arm32: make sure assembler code is compiled in arm mode

core/arch/arm/kernel/thread_a32.S
thread_excp_vect_workaround isn't reentrant because it use the tpidr
as a temporary register to save value of r0. That means if a fiq
happend when optee is processing a syscall, the syscall argument r0
will be changed to unexpected value.
Move `write_tpidrprw r0` out of `vector_prologue_spectre` and add
`cpsid aif` before it to fix this issue.
Signed-off-by: Mark-PK Tsai <mark-pk.tsai@mediatek.com>
#3371
=> core: arm32: disable interrupt in thread_excp_vect_workaround

core/pta/tests/invoke.c
For testing purposes Add invoke_tests.pta to enumerated TAs. This gives
optee_enumerate_devices() in the OP-TEE kernel driver something to
iterate over in case there's no other TAs to enumerate.
=> core: add invoke_tests.pta to enumerated TAs

core/kernel/tee_ta_manager.c, lib/libutee/arch/arm/gprof/gprof.c, mk/config.mk, ta/arch/arm/ta.ld.S
The gprof sample buffer is in user space memory but is also accessed by
the TEE core. Currently, space is reserved by the TA linker script. The
address and size of the buffer is passed to the TEE core via a call to
the gprof PTA. After this call, the TEE core accesses the buffer
periodically, such as when the TA is interrupted by a timer interrupt.
Commit ef305e5 ("libutee: allocate temp secmem for invoke")
modified the way that private TA memory is mapped in TA to TA
invocations, so that memory is mapped only for the duration of the
call. After this point, the memory is unmapped so the gprof sample
buffer becomes inaccessible, resulting in a crash:
E/TC:0 0 Core data-abort at address 0x121356 (translation fault)
E/TC:0 0  fsr 0x00000007  ttbr0 0x0e19206a  ttbr1 0x0e18806a  cidr 0x2 …
=>  gprof: fix TEE core crash by allocating sample buffer dynamically

core/arch/arm/include/mm/mobj.h, core/arch/arm/kernel/thread_optee_smc.c, core/arch/arm/kernel/user_ta.c, core/arch/arm/mm/mobj.c, core/arch/arm/mm/mobj_dyn_shm.c, core/arch/arm/mm/tee_mmu.c, core/arch/arm/tee/entry_std.c, core/include/mm/tee_mmu_types.h, core/kernel/msg_param.c, core/pta/system.c, core/tee/tee_svc.c
The mobj interface is changed to use reference counting of mobjs, the
direct mobj_free() call is replaced by mobj_put(). As expected a
mobj_get() is also added to handle multiple references to the same mobj.
This also changes already present reference counting in struct
mobj_reg_shm to use the reference counting mechanism now available in
struct mobj.
The VM_FLAG_EXCLUSIVE_MOBJ flag is removed since the referenced mobj is
put instead when a struct vm_region is removed.
=> core: reference count struct mobj

core/arch/arm/mm/core_mmu.c
This patch updates check_mem_map() to recognize MEM_AREA_IDENTITY_MAP_RX
as part of secure only memory.
This fix is only needed with CFG_CORE_ASLR= and prevents an error like:
E/TC:0 0 check_mem_map:1166 Uhandled memtype 8
E/TC:0 0 Panic at core/arch/arm/mm/core_mmu.c:1167 <check_mem_map>
Fixes: 1385854b72c9 ("core: Add core memory type MEM_AREA_IDENTITY_MAP_RX")
=> core: fix check_mem_map() vs MEM_AREA_IDENTITY_MAP_RX

core/arch/arm/plat-bcm/platform_config.h, core/drivers/bcm_sotp.c
- Hardware does not support ECC bits for SOTP section_0 to
section_3, i.e ROWS_0 to ROWS_20.
- Remove magic number and use platform provided
SOTP_NO_ECC_ROWS macro.
Signed-off-by: Bharat Kumar Reddy Gooty <bharat.gooty@broadcom.com>
Signed-off-by: Raveendra Padasalagi <raveendra.padasalagi@broadcom.com>
=> Fix Broadcom SOTP driver

core/pta/bcm/hwrng.c, core/pta/bcm/sub.mk
Add PTA for hardware random number generator.
PTA Reads the random number from the RNG FIFO and passes to
user application.
Signed-off-by: Bharat Kumar Reddy Gooty <bharat.gooty@broadcom.com>
=> Add HW RNG PTA

core/arch/arm/plat-imx/drivers/tzc380.c
Add support for the TZC380 found on the MX6UL.
On the MX6UL/ULL only one instance of the TZC380 can be found, add a check for this in the driver and use only one if either of the SoCs is detected.
Add the tzasc autoconfiguration for the i.MX6UL.
Tested on a Nitrogen6x and a Digi CCIMX6UL SBC Pro.
=> TZC380 support for MX6UL/ULL

core/arch/arm/include/kernel/user_ta.h
Since commit d1911a85142d ("core: load TAs using ldelf"), the load_addr
field in struct user_ta_ctx is not used anymore. Remove it.
=> core: remove unused user_ta_ctx::load_addr

core/arch/arm/kernel/otp_stubs.c, core/arch/arm/kernel/ree_fs_ta.c, core/include/kernel/huk_subkey.h, core/include/kernel/tee_common_otp.h, core/include/signed_hdr.h, core/include/tee/tee_ta_enc_manager.h, core/tee/sub.mk, core/tee/tee_ta_enc_manager.c, mk/lib.mk, scripts/sign_encrypt.py, ta/arch/arm/link.mk, ta/arch/arm/link_shlib.mk, ta/ta.mk
Add framework to support loading of encrypted TAs from REE-FS using symmetric authenticated encryption scheme supported by OP-TEE.
This framework only support buffered REE-FS TAs as encrypted TA needs to be read at once and decrypted into temporary secure memory buffer.
The default encryption key is derived from hardware unique key which can be overridden via platform specific encryption key.
Also it adds support in TA dev kit to encrypt as well as sign TA in case corresponding TA build time configuration option `CFG_ENCRYPT_TA=y` is enabled.
Looking forward to your feedback/comments.
-Sumit
=> [RFC] Add framework to support REE-FS encrypted TAs

core/arch/arm/kernel/unwind_arm32.c, core/arch/arm/kernel/unwind_arm64.c, core/arch/arm/kernel/user_ta.c, scripts/symbolize.py
When decoding an ftrace file with syscall tracing enabled [1], the
kernel functions are not resolved and show question marks instead.
[1] $ make CFG_FTRACE_SUPPORT=y CFG_SYSCALL_FTRACE=y CFG_ULIBS_MCOUNT=y \
CFLAGS_ta_arm32=-pg
[run test and copy content of /tmp/ftrace*]
$ optee_os/scripts/symbolize.py -d optee_os/out/arm/core \
-d out-br/build/optee_test-1.0/ta/*/out
[paste ftrace log here]
Fixes: 105e09c24479 ("symbolize.py: add support for TEE core ASLR")
=> symbolize.py: fix decoding of ftrace dumps containing syscalls

core/crypto/signed_hdr.c, scripts/sign_encrypt.py
PKCS#1 v1.5 has some security issues, https://cryptosense.com/blog/why-pkcs1v1-5-encryption-should-be-put-out-of-our-misery/
In this PR I propose to switch to sign TAs using TEE_ALG_RSASSA_PKCS1_PSS_MGF1_SHA256. However, it's not completely without issues. In the scripts/sign_encrypt.py script we'll add dependency to Cryptodome. Before this the was dependency to Cryptodome only if TAs where to be encrypted.
Perhaps we should have a way of passing the algorithm to the script instead of using a hard coded algorithm.
=> [rfc] Sign TAs using pss

core/arch/arm/plat-imx/conf.mk
The CFG_DRAM_BASE on imx8qm and imx8qxp is 0x80000000
=> core: imx: fix CFG_DRAM_BASE for imx8qm/qxp

core/arch/arm/kernel/kern.ld.S, scripts/gen_tee_bin.py
Prior to this patch generation of tee.bin (CFG_WITH_PAGER=n) fails with:
GEN     out/core/tee.bin
Cannot find symbol __init_end
core/arch/arm/kernel/link.mk:183: recipe for target 'out/core/tee.bin' failed
Introduce a special __get_tee_init_end to fix this and also avoid
confusion with __init_end used in the code for the pager case.
Fixes: 5dd1570ac5b0 ("core: add embedded data region")
=> core: fix generation of tee.bin

.shippable.yml
Modifies two targets to also generate the deprecated v1 images.
=> shippable: generate deprecated v1 images

core/arch/arm/plat-ti/a9_plat_init.S
When resuming the only value we need to work with a new version of is the
non-secure context as it will have changed since boot. This value is
stored on OP-TEE entry in r5, previously we saved this value by moving
r5 to r3 then r3 to r4 basically just dodging getting overwritten by
functions we call. This can be simplified now as nothing clobbers r5,
so we can use it directly as the source for the non-secure context
pointer feed into init_sec_mon().
=> plat-ti: Restore non-secure entry address from saved copy in r5

core/arch/arm/kernel/link.mk
The OP-TEE v1 header is the only version supported by U-Boot[0] and several other projects, including non-modifiable device code. Community and device support for v2 should be in better shape before marking the format as deprecated (if it ever has to be deprecated).
Removing the images from the 'all' build causes automatic testing to miss issues with the v1 format like [here](https://github.com/OP-TEE/optee_os/issues/3459).
Restore v1 as a supported format.
Andrew
[0] https://gitlab.denx.de/u-boot/u-boot/blob/master/include/tee/optee.h
=> Un-deprecate v1 OP-TEE header

core/arch/arm/plat-ti/sm_platform_handler_a15.c, core/arch/arm/plat-ti/sm_platform_handler_a9.c
Previously on our TI evil vendor Linux tree we would use a sentinel value
in r12 to signal if a call was meant for OP-TEE or the legacy ROM. A path
to using SMCCC compatible calls from Linux is being implemented.
Switch the OP-TEE side over.
=> plat-ti: Switch to using SMCCC compatible calls

core/crypto.mk, core/crypto/crypto.c, core/crypto/sm4-cbc.c, core/crypto/sm4-ctr.c, core/crypto/sm4-ecb.c, core/crypto/sm4.c, core/crypto/sm4.h, core/crypto/sub.mk, core/include/crypto/crypto_impl.h, core/tee/tee_cryp_utl.c, core/tee/tee_svc_cryp.c, lib/libutee/include/tee_api_defines.h, lib/libutee/include/utee_defines.h, lib/libutee/tee_api_operations.c
Adds support for the SM4 cipher [1] using the API defined in the
GlobalPlatform TEE Internal Core API v1.2.
ECB, CBC and CTR modes are implemented. Other modes are valid but are
not included in the GP specification, so they are not considered here.
[1] https://tools.ietf.org/html/draft-ribose-cfrg-sm4-10
=> core: crypto: add support for SM4

mk/compile.mk
Adds a macro to test the availability of a compiler option. For example:
$(call cc-option,-opt1,-opt2)
...will evaluate to '-opt1' if the C compiler supports option -opt1, or
'-opt2' otherwise. The second argument (-opt2) is optional.
=> mk/compile.mk: add cc-option macro

.shippable.yml, core/crypto/sm3-hmac.c
Remove unused mbedtls/md.h header file to fix error:
core/crypto/sm3-hmac.c:12:10: fatal error: mbedtls/md.h: No such file or directory
when building with CFG_CORE_MBEDTLS_MPI=n. To prevent future similar
regression, also add a test case to Shippable.
Fixes: https://github.com/OP-TEE/optee_os/issues/3487
Fixes: 47645577c806 ("core: crypto: add support for SM3")
=> core: crypto: sm3: remove unused header

.shippable.yml
The ccache unify mode does not increase cache hits in the Shippable
build, contrary to what is claimed in commit a2a52e198719 ("ci:
shippable: enable ccache's 'unify' option"). Disable this mode,
because it is slower than the default mode [1] and might cause
corrupted builds [2].
Unify mode was enabled in the above commit, but that commit also set
CFG_DEBUG_INFO=n. It was in fact this configuration flag that allowed
better caching, by preventing -g3 from being added to the C flags.
With -g3, the preprocessor output contains all the macro definitions
(such as the configuration variables from config.h). Without it (or
with -g), those defines are not visible after the preprocessing stage
and therefore adding defines that do not change the actual code has no
impact and cached objects can be …
=> ci: shippable: remove CCACHE_UNIFY=true

core/lib/libtomcrypt/mpa_desc.c, core/lib/libtomcrypt/mpi_desc.c
Adds the addmod() and subkod() functions which will be useful for
Elliptic Curve Cryptography (they are used by ltc_ecc_is_point()).
=> core: ltc: add implementations for .addmod and .submod

core/arch/arm/kernel/thread_a64.S
Even though ERET always causes a jump to another address, aarch64 CPUs
speculatively execute following instructions as if the ERET
instruction was not a jump instruction.
The speculative execution does not cross privilege-levels (to the jump
target as one would expect), but it continues on the kernel privilege
level as if the ERET instruction did not change the control flow -
thus execution anything that is accidentally linked after the ERET
instruction. Later, the results of this speculative execution are
always architecturally discarded, however they can leak data using
microarchitectural side channels. This speculative execution is very
reliable (seems to be unconditional) and it manages to complete even
relatively performance-heavy operations (e.g. multiple dependent
fetches from …
=> Fixing a public but almost undocumented speculative execution vulnerability that is specific to aarch64

core/arch/arm/kernel/ree_fs_ta.c, ta/arch/arm/link.mk, ta/avb/user_ta.mk, ta/mk/ta_dev_kit.mk
Add check for TA version while loading TA from REE-FS and compare against secure storage based TA version database to prevent against any TA version downgrades.
We should normally keep TA version database in RPMB filesystem for more robustness. That's the reason for default selection being RPMB based secure storage if present otherwise fallback to REE-FS based secure storage.
Looking forward to your comments.
-Sumit
=> Enable rollback protection for REE-FS TAs

.github/workflows/stale_issue.yml, .github/workflows/stale_pr.yml
It's not uncommon that people ask questions or send pull requests that
becomes stale for various reasons. Some examples can be:
- Original Poster (OP) doesn't close the ticket.
- OP doesn't get back when maintainers asked for more information.
- OP gets busy with other things and have to put the work a side.
Having lots of open issues and pull request makes it almost impossible
to figure out where help and input is needed, since things simply
becomes overwhelming. By using GitHub actions [1] we enable a tool that
can:
- Automatically close issues that no one cares about.
- Help us bring attention back to issues that are of importance.
- Push patch creators to not drop their proposed patches.
- Remind maintainers and other OP-TEE users that reviews are needed.
This patch set propose …
=> GitHub: use GitHub actions to close stale issues and PRs

core/arch/arm/include/mm/core_mmu.h
Makes SMALL_PAGE_MASK, CORE_MMU_PGDIR_MASK, CORE_MMU_USER_CODE_MASK and
CORE_MMU_USER_PARAM_MASK of type paddr_t to allow correct masking of
significant bits.
Example:
extern paddr_t addr;
paddr_t page_addr = addr & ~SMALL_PAGE_MASK
If paddr_t is a 64-bit type SMALL_PAGE_MASK must also be 64-bit wide or
the ~ operation will not set all the higher bits.
=> core: make SMALL_PAGE_MASK and friends of type paddr_t

core/arch/arm/arm.mk, core/arch/arm/mm/core_mmu.c, core/arch/arm/mm/core_mmu_lpae.c, core/arch/arm/mm/core_mmu_private.h, core/arch/arm/plat-rcar/conf.mk, core/arch/arm/plat-vexpress/conf.mk
Introduces CFG_CORE_ARM64_PA_BITS which replaces the max_pa global
variable which was used to configure TCR_EL1.IPS.
Prior to 520860f ("core: generic_entry: add enable_mmu()") TCR_EL1.IPS
was calculated and even updated later in the boot flow to automatically
cover the needed physical address space. But now it's calculated before
MMU is enabled and once MMU it's kept in read only memory.
With CFG_CORE_ARM64_PA_BITS TCR_EL1.IPS can be determined early and
later it is enough to check that physical addresses to be mapped are
covered by CFG_CORE_ARM64_PA_BITS.
Fixes: 520860f658be ("core: generic_entry: add enable_mmu()")
=> core: arm64: introduce CFG_CORE_ARM64_PA_BITS

core/arch/arm/kernel/generic_entry_a64.S
After moving some initial sections around in memory we clean out the new
data and invalidate the cache so it can be seen by other cores when they
enable caches. The instruction used was invalidate; on most systems this
will behave the same as clean/invalidate, but on some with L3 caches this
can cause the just written data to be invalidated. Use the
clean+invalidate to prevent this on such systems.
=> core: generic_entry_a64.S: use CIVAC over IVAC to clean cache data

core/arch/arm/kernel/generic_entry_a32.S, core/arch/arm/kernel/generic_entry_a64.S
Stores the correct register at cached_mem_end at boot. This avoids usage
of stale dcache content.
Fixes: 5dd1570ac5b0 ("core: add embedded data region")
=> core: generic_entry_a{32,64}.S: use correct cached_mem_end

core/crypto.mk, core/crypto/crypto.c, core/include/crypto/crypto.h, core/lib/libtomcrypt/acipher_helpers.h, core/lib/libtomcrypt/ecc.c, core/lib/libtomcrypt/sm2-kep.c, core/lib/libtomcrypt/sm2-pke.c, core/lib/libtomcrypt/sm2_kdf.c, core/lib/libtomcrypt/sub.mk, core/tee/tee_svc_cryp.c, lib/libutee/include/tee_api_defines.h, lib/libutee/include/utee_defines.h, lib/libutee/tee_api_operations.c
This is the last bit of my Chinese crypto series: the key exchange protocol (key derivation).
The first 3 commits are small fixes and improvement required by the two main ones: "core: ltc: add support for SM2 KEP" and "core: crypto: add support for SM2 KEP".
Note that the commits prefixed with "core: ltc:" will need to eventually go into the LTC import branch. I'll take care of that later for simplicity (well, I think it is simpler to review everything here).
=> SM2 KEP (Key Exchange Protocol)

core/arch/arm/plat-rcar/conf.mk, core/arch/arm/plat-rcar/link.mk, scripts/gen_tee_bin.py
Rcar Gen3 uses quite old ARM-TF which does not support OP-TEE image with headers. This wasn't problem until now. We just used objdump to generate raw binary (or srec) file to flash it to a board.
But with recent changes, it is not working anymore, as OP-TEE expects some additional data right after its image. This set of patches uses gen_tee_bin script to generate image in the correct way.
Also I'm disabling core ASLR for reasons described in the patch.
=> Fix Rcar Gen3 platform boot

core/lib/libtomcrypt/sm2-pke.c
crypto_acipher_sm2_pke_decrypt() fails to check a return status from
LibTomCrypt. Add the missing check.
Fixes: f9a78287dd12 ("core: ltc: add support for SM2 PKE")
=> core: ltc: sm2: add missing status check

core/arch/arm/include/mm/core_mmu.h, core/arch/arm/kernel/generic_boot.c, core/arch/arm/mm/core_mmu.c
In core_mmu_set_discovered_nsec_ddr(), core_mmap_is_end_of_table
always returns false and the loop body cannot be executed, which
is unexpected.
In carve_out_phys_mem(), when pa has the same address
with m[n].addr, the m[n].size should also be adjusted.
also submitted a patch to fix compiling errors when only use dynamic shared memory
(i.e: CFG_CORE_DYN_SHM=y && CFG_CORE_RESERVED_SHM=n), with
CFG_SHMEM_START and CFG_SHMEM_SIZE not defined.
Totally, I submitted 3 patches to fix the bugs. Pls help to review. thanks.
=> fix bugs in dynamic shared ddr support

core/arch/arm/kernel/generic_boot.c
In case an external device tree overlay is configured within OP-TEE,
fdt_{size,address}_cells will return the defaults from the device tree
specification. These will be wrong for 32-bit ARM platforms, instead
calculate them from the paddr_t size instead.
Fixes https://github.com/OP-TEE/optee_os/issues/3470
Alternative to https://github.com/OP-TEE/optee_os/pull/3481
=> core: calculate size/address cells with overlay

.shippable.yml
Since commit e6e68745589b ("core: REE FS TAs: disable
CFG_REE_FS_TA_BUFFERED by default"), there is no need for an entry with
CFG_REE_FS_TA_BUFFERED=n in .shippable.yml. Instead, we should test
with =y.
=> .shippable.yml: build with CFG_REE_FS_TA_BUFFERED=y

scripts/symbolize.py
The documentation for the Python 3 subprocess module [1] has the
following note related to the Popen() constructor:
Changed in version 3.7: Added the text parameter, as a more
understandable alias of universal_newlines.
In order to avoid a runtime error with versions of Python prior to 3.7,
replace the 'text' parameter with 'universal_newlines'.
Link: [1] https://docs.python.org/3/library/subprocess.html
=> symbolize.py: Python < 3.7 compatibility

core/lib/libfdt/README.license, core/lib/libfdt/fdt.c, core/lib/libfdt/fdt_addresses.c, core/lib/libfdt/fdt_empty_tree.c, core/lib/libfdt/fdt_overlay.c, core/lib/libfdt/fdt_ro.c, core/lib/libfdt/fdt_rw.c, core/lib/libfdt/fdt_strerror.c, core/lib/libfdt/fdt_sw.c, core/lib/libfdt/fdt_wip.c, core/lib/libfdt/include/fdt.h, core/lib/libfdt/include/libfdt.h, core/lib/libfdt/include/libfdt_env.h, core/lib/libfdt/libfdt_internal.h
Imports upstream libfdt version v1.5.1 [1]. Things worthy of note:
- SPDX license identifiers were added upstream in commit 94f87cd5b7c5
("libfdt: Add dual GPL/BSD SPDX tags to files missing license text").
They conflict with the identifiers we have added locally in commit
1bb929836182 ("Add SPDX license identifiers"). We added "BSD-2-Clause"
while upstream added "GPL-2.0-or-later OR BSD-2-Clause".
This commit keeps the upstream tags.
- At this stage we carry no local modification except for two minor
things enabling C99 compliance:
1. Zero sized arrays at the end of structs fdt_node_header and
fdt_property are changed from "[0]" to "[]",
2. An extra semicolon is removed after the static function
overlay_fixup_one_phandle().
These changes were in the initial import already, commit …
=> libfdt: move to version v1.5.1

lib/libmbedtls/core/dh.c
GP wrapper of mbedtls DH operation generate key function wrongly
calculates the number of bytes from bits, leading to incorrect public
key generated and returned.
Change-Id: I3ea4e5a551b3af3b740b0f75cff1457bce68b866
Signed-off-by: Cao, Vincent T <vincent.t.cao@intel.com>
=> libmbedtls: Fix Diffie-Helman operation wrong public key size

core/arch/arm/mm/core_mmu.c, core/arch/arm/tee/entry_fast.c
Two trivial things I stumbled upon when building without dynamic shared memory support.
=> Fix warnings

ta/pkcs11/Android.mk, ta/pkcs11/Makefile, ta/pkcs11/include/pkcs11_ta.h, ta/pkcs11/src/entry.c, ta/pkcs11/src/sub.mk, ta/pkcs11/src/user_ta_header_defines.h, ta/pkcs11/sub.mk, ta/pkcs11/user_ta.mk
Introduce in-tree SKS TA: basic source/header/make files.
Define API and implement a first command that gets the TA implementation version info.
This P-R introduces the first commits from #2732.
=> Introduce SKS TA

.shippable.yml, MAINTAINERS, core/arch/arm/plat-amlogic/conf.mk, core/arch/arm/plat-amlogic/link.mk, core/arch/arm/plat-amlogic/main.c, core/arch/arm/plat-amlogic/platform_config.h, core/arch/arm/plat-amlogic/scripts/aml_bin2img.py, core/arch/arm/plat-amlogic/sub.mk, core/drivers/amlogic_uart.c, core/drivers/sub.mk, core/include/drivers/amlogic_uart.h
This is the initial support for the Amlogic platforms.
Tested 64-bin mode on A113D (AXG) board using upstream BL31.
* xtest results (-l 15):
| 44074 subtests of which 0 failed
| 96 test cases of which 0 failed
| 0 test cases were skipped
| TEE test application done!
* Compiled with:
| make PLATFORM=amlogic
Signed-off-by: Carlo Caione <ccaione@baylibre.com>
=> plat-amlogic: Add initial support for Amlogic platforms

core/arch/arm/plat-imx/crypto_conf.mk, core/drivers/crypto/caam/hash/caam_hash.c, core/drivers/crypto/caam/include/caam_common.h, core/drivers/crypto/caam/include/caam_desc_helper.h, core/drivers/crypto/caam/include/caam_trace.h, core/drivers/crypto/caam/include/caam_utils_mem.h, core/drivers/crypto/caam/include/caam_utils_sgt.h, core/drivers/crypto/caam/utils/utils_mem.c, core/drivers/crypto/caam/utils/utils_sgt.c
Hi everyone,
This PR introduces the scatter gather for CAAM driver. CAAM uses DMA to load/store data in memory. In case of a user buffer, if the buffer is crossing multiple Small Page, a CAAM Scatter Gather Table needs to be created to rebuild the physical memory chunks used by the User virtual buffer.
This PR also add the use of SGT for the Hash driver.
Thanks!
=> [i.MX CAAM] SGT + Hash Fix

core/arch/arm/plat-hikey/conf.mk
Since commit 4518cdc1ff64 ("core: arm64: introduce CFG_CORE_ARM64_PA_BITS")
platforms are required to define CFG_CORE_ARM64_PA_BITS if their physical
address space extends beyond 4G. This was missing for HiKey960 4G & 6G versions,
which indeed have addresses beyond 4G.
Signed-off-by: Henrik Uhrenfeldt <henrik.uhrenfeldt@huawei.com>
=> hikey960: fix support for 4G & 6G boards

core/arch/arm/kernel/thread.c
When entering user mode, the bits of SPSR should be derived from CPSR.
Fixes: a702f5e71e79 "core: split thread_enter_user_mode"
Signed-off-by: Ali Zhang <alizhang@google.com>
=> core: arm32: derive spsr from cpsr

.travis.yml
As per the Travis docs at
https://docs.travis-ci.com/user/customizing-the-build#git-clone-depth to
avoid performing git clones with limited depth, the depth should be set
to "false", not to a large magic number.
Signed-off-by: David Brown <david.brown@linaro.org>
=> ci: travis: Use proper construct for full clone

core/arch/arm/plat-imx/conf.mk
Board imx6*sabreauto default UART is UART4 and not UART1.
=> core: imx: add default UART for sabreauto boards

core/drivers/tzc380.c, core/include/drivers/tzc380.h
Hello,
Here is a small fix for `tzc_auto_configure()` function.
We met an error on a i.MX platform where this function creates a region of 8G when the AXI bus width is 32bits. This causes the newly created region to be ineffective.
According to the TZASC RM,
> Size of region <n>. See Table 3-16.
> Note
> The AXI address width, that is AXI_ADDRESS_MSB+1, controls the upper limit value of this field.
The ARM supports confirms this case is outside of the restrictions and the tzasc behavior would be unpredictable.
Thanks!
=> drivers: tzc: set maximum region size for tzc_auto_configure()

core/tee/tee_rpmb_fs.c
Improves RPMB performance as dump_fat has various callers (write_fat_entry(), rpmb_fs_setup()).
When called, dump_fat traverses the whole list of FAT entries and prints out using FMSG().
dump_fat() should be used for debugging/tracing, but not for productive builds.
=> Empty body for dump_fat() unless log level set to TRACE_FLOW

core/arch/arm/kernel/generic_entry_a32.S, core/arch/arm/kernel/generic_entry_a64.S, core/arch/arm/tee/init.c
cached_mem_end was calculated before relocation. Add code to update cached_mem_end with ASLR load offset.
tee_svc_uref_base was using hardcoded TEE_TEXT_VA_START define value. This value no longer valid after TEE core relocation. Switch to use VCORE_START_VA which is linker variable that should get update after relocation code executed.
=> Fix ASLR bug: update cached_mem_end after relocation and switch tee_svc_uref_base to use VCORE_START_VA

core/tee/tee_rpmb_fs.c, mk/config.mk
Allows to configure the number of FAT fs entries to be read from RPMB
storage in one chunk. Increasing this number makes functions that
traverse the FAT fs read in more entries within a single RPMB read
operation. While this potentially improves RPMB I/O, it comes at the
cost of additional memory required to be allocated on the heap.
Determining an optimal size is platform- and use-case-dependent.
Signed-off-by: Manuel Huber <manuel.huber@microsoft.com>
=> core: RPMB FS: Make N_ENTRIES a config variable

core/drivers/crypto/caam/caam_desc.c
Updated caam_desc_pop() for reading the output CAAM job ring
entry for 64-bit platforms
Signed-off-by: Priyanka Singh <priyanka.singh@nxp.com>
=> drivers: CAAM: Update caam_desc_pop() function for 64bit platforms

core/include/kernel/panic.h
When CFG_TEE_CORE_DEBUG != y, panic("Some text") prints no file/line/
function information (which is expected in non-debug mode) but it also
ignores its parameter. As a result, the console simply shows "Panic"
which is not very helpful.
There is no reason not to print the panic message, so add it.
Note that it is still possible to build a fully silent OP-TEE by
setting the log level to zero.
=> core: panic(): don't lose the message in non-debug mode

ta/pkcs11/src/user_ta_header_defines.h
GPD TEE specification mandates that trusted applications provide
a  version information through TA property "gpd.ta.version". This
change implement this propoerty for the PKCS11 TA. The version number
is defined by PKCS11_TA_VERSION_MAJOR/PKCS11_TA_VERSION_MINOR in TA
API header file.
This change also adds a short description in "gpd.ta.description".
=> ta: pkcs11: add TA version property mandated by GPD

mk/config.mk, ta/arch/arm/ta.ld.S
This reverts commit 59e8ef0dcb3773964fd133d0a9360989cb86108f.
The default value for CFG_FTRACE_BUF_SIZE needs to be in the TA link
script ta.ld.S, because this file is *not* pre-processed before being
added to the TA dev kit. Replacement of CFG_* values only happens when
the TA is built, at which point mk/config.mk is irrelevant. It makes
sense of course, since it allows to change TA settings and re-build
only the TA.
Fixes the following TA link error:
$ make CFLAGS_ta_arm32=-pg
[...]
bin/arm-linux-gnueabihf-ld.bfd:out/ta.lds:57: undefined symbol `CFG_FTRACE_BUF_SIZE' referenced in expression
=> Revert "ftrace: define CFG_FTRACE_BUF_SIZE in mk/config.mk"

scripts/get_maintainer.py
Adds an option to scripts/get_maintainer.py showing the email addresses
to be used for release announcements. All addresses in Maintainer (M:)
or Reviewer (R:) entries are shown.
=> get_maintainer.py: add --release-to

mk/clang.mk
Clang version 9.0.0 has a llvm-objdump tool that provides equivalent
output to the binutils version. Let's use it and remove the hack in
mk/clang.mk.
With this, it is possible to build OP-TEE with Clang and without a GCC
toolchain.
=> clang: use llvm-objdump

scripts/symbolize.py
```
The symbolize script uses the "file" command to identify the
architecture of ELF binaries. If the file is a symbolic link (which can
happen with shared libraries typically), the command may fail to return
the expected output and print "symbolic link to <some path>" instead.
This behavior of the "file" command depends on the environment variable
POSIXLY_CORRECT. In order to not depend on this, this commit adds the
-L option (follow symlinks).
```
=> symbolize.py: add -L option to the "file" command

core/arch/arm/plat-imx/conf.mk, core/arch/arm/plat-imx/drivers/imx_snvs.c, core/arch/arm/plat-imx/drivers/sub.mk, core/drivers/imx_snvs.c, core/include/drivers/imx_snvs.h, core/include/tee/tee_fs.h, core/tee/tee_rpmb_fs.c
Often the RPMB should only be written if the platform is in the correct
state where the Hardware Unique Key (HUK) for the platform works
correctly. As an example on imx platforms with HUK derivation from the
OTPMK, the OTPMK is only accessible from the secure or trusted state.
Add a function and weak implementation for platforms to indicate that
the device is in the correct state to allow RPMB key writes.
This PR implements the weak functions to block RPMB, reworks the i.MX SNVS support and adds a function for i.MX6/7 which can block the RPMB write operation if the platform is not in the secure state.
=> Add platform rpmb ready check

core/arch/arm/mm/core_mmu.c, core/arch/arm/mm/core_mmu_private.h
Correct test on memory physical end address that was not consistent
in use of `core_mmu_check_end_pa()`.
This change fixes `core_mmu_set_discovered_nsec_ddr()` where
`core_mmu_check_end_pa()` was called with a byte length argument
decreased by one whereas it should provide the effective byte size
of the memory area.
This change fixes `core_mmu_check_end_pa()` so that it computes
the end address as start address plus byte size minus one to
obtain the inclusive end address `core_mmu_check_max_pa()` expects
as input argument.
Fixes: 4518cdc1ff64 ("core: arm64: introduce CFG_CORE_ARM64_PA_BITS")
=> core: mmu: fix secure memory end address

core/arch/arm/kernel/ree_fs_ta.c
This change fix bootstrap header size check. Before it use sizeof(bs_hdr) but bs_hdr is a struct pointer. Correct it to sizeof(*bs_hdr)
=> core: ree_fs_ta: fix bootstrap header size check

ldelf/ta_elf.c, ldelf/ta_elf.h, lib/libdl/dlfcn.c, lib/libutee/arch/arm/user_ta_entry.c, lib/libutee/include/user_ta_header.h, ta/arch/arm/link.mk
```
Adds support for running initialization and finalization functions in
TA ELF files. Such functions are used, for instance, by C++ compilers
to construct and destruct global objects. They can also be used in C
thanks to __attribute__((constructor)) and __attribute__((destructor)).
A global structure is added to libutee. ldelf is responsible for
filling it with the addresses of the functions pointer arrays present
in the ELF files whenever such a file is loaded. Since the number of
arrays is unknown at compile time (it depends on how many ELF files are
loaded, and whether they have constructors or destructors), memory is
allocated on the TA heap.
Two helper functions are introduced: __utee_call_elf_init_fn() and
__utee_call_elf_fini_fn(). They are used when the TA instance is
created …
```
=> ldelf, ta: add support for DT_INIT_ARRAY and DT_FINI_ARRAY

core/drivers/crypto/caam/caam_rng.c
Not doing so calls the default implementation which generates
misleading rng trace information.
``
> D/TC:0 0 caam_rng_init:536 Initialization
> D/TC:0 0 caam_rng_instantiation:428 RNG Instantation
> D/TC:0 0 caam_rng_instantiation:492 RNG Kick (inc=0) ret 0x00000000
> D/TC:0 0 prepare_inst_desc:367 RNG SH Status 0x00000000 - Key Status 0
> D/TC:0 0 prepare_inst_desc:373 Instantiation start at SH0 (2)
> D/TC:0 0 caam_rng_instantiation:504 RNG Job returned 0x00000000
> D/TC:0 0 caam_rng_instantiation:482 RNG All SH are instantiated (0x00000003)
> D/TC:0 0 caam_rng_instantiation:527 RNG Instantiation return 0x00000000
> D/TC:0 0 check_ta_store:638 TA store: "early TA"
> D/TC:0 0 check_ta_store:638 TA store: "Secure Storage TA"
> D/TC:0 …
=> drivers: caam: RNG: provide plat_rng_init symbol

core/arch/arm/tee/arch_svc.c
If a TA fails to load due to an assertion failure in ldelf, the user
stack might be inaccessible. save_panic_stack() detects this situation
but fails to set abort information in the thread specific data (tsd).
As a result, the stack unwinding code can erroneously execute kernel
unwinding code and trigger an assertion:
E/TC:? 0 assertion 'thread_get_exceptions() & THREAD_EXCP_FOREIGN_INTR' failed at core/arch/arm/include/kernel/misc.h:22 <get_core_pos>
The fix consists in moving the tsd initialization above the user stack
accessibility check.
=> core: save_panic_stack(): make sure tsd is initialized

ta/pkcs11/include/pkcs11_ta.h, ta/pkcs11/src/entry.c, ta/pkcs11/src/persistent_token.c, ta/pkcs11/src/pkcs11_helpers.c, ta/pkcs11/src/pkcs11_helpers.h, ta/pkcs11/src/pkcs11_token.c, ta/pkcs11/src/pkcs11_token.h, ta/pkcs11/src/sub.mk
Initialize token(s) state from a persistent database. If no
persistent database is found in the secure storage, initialize
it to a default state and save the database in secure storage.
PKCS11 TA may implement several tokens each related to its own
database.
A token persistent database is stored in several part in TEE secure
storage. The main database stores token label, flags and PINs status.
Another database stores the UUIDs of the TEE persistent objects
used to store the token PKCS11 objects allowing the token to find
back PKCS11 persistent objects. This object database is out of the
scope of this change.
At runtime, a token instance is reference by a struct ck_token instance
in RAM which stores the state of the token and references to the
resources the token as loaded as PIN cipher …
=> ta: pkcs11: persistent database for the pkcs11 tokens

ta/arch/arm/ta.ld.S
Contrary to .ARM.exidx, we have no .ARM.extab entry in the TA linker
script. As a result, the multiple .ARM.extab* sections [1] gathered
from the object files will remain in the TA. While this is perfectly
valid and does not cause any functional issue, it uselessly pollutes
the readelf/symbolize.py/etc. dumps.
This commit merges all the .ARM.extab* into a unique .ARM.extab.
[1] Due to -ffunction-sections, each function that generates exception
table information will create its own section.
=> ta: ta.ld.S: merge .ARM.extab* sections

ta/pkcs11/src/persistent_token.c
Change init_pin_keys() and init_persistent_db() to rely on the
strict byte size of the object ID reference rather than using hard
coded value 32.
Fixes: c84ccd0a805e ("ta: pkcs11: persistent database for the pkcs11 tokens")
=> ta: pkcs11: better test object ids generation

ta/pkcs11/src/entry.c, ta/pkcs11/src/pkcs11_token.c, ta/pkcs11/src/pkcs11_token.h, ta/pkcs11/src/serializer.c, ta/pkcs11/src/serializer.h, ta/pkcs11/src/sub.mk
Implement TA commands for PKCS#11 API functions `C_GetSlotList()` and `C_GetSlotInfo()`.
=> ta: pkcs11: get list of slots and related info implemented in TA

ta/pkcs11/src/entry.c, ta/pkcs11/src/pkcs11_token.c, ta/pkcs11/src/pkcs11_token.h
* ta: pkcs11: add pad_str() helper in token info wrapper
Add pad_str() to pad a string ('\0' terminated) with blank characters (' '), removing the '\0' termination as per PKCS#11 specification. This will factorize other padding needed in other function/command wrappers.
* ta: pkcs11: implement command to get token information
Implement TA command PKCS11_CMD_TOKEN_INFO for client to get information on a token embedded in the PKCS11 TA.
=> ta: pkcs11: get token information

ldelf/ta_elf.c, ldelf/ta_elf_rel.c
"ldelf: use confine_array_index() to cap speculation" brings protection against Spectre V1 speculations.
When parsing the ELF there's indexes and offsets used to load data which in turn is used to load other data and so on, a growing ground for Spectre V1. I think `confine_array_index()` should only be used when needed or sometimes needed. It is however not so easy to tell since it's with the second data load there's danger. This ELF parsing is a bit of a special case so perhaps we should try to annotate the code in a way to assist someone reviewing the code to see if another call to `confine_array_index()` might be needed or not.
=> Ldelf nospec

lib/libutils/isoc/include/setjmp.h
The longjmp() function does not return, therefore it should have the
__noreturn attribute. Avoids compiler warnings.
=> libutils: add __noreturn to longjmp() prototype

core/drivers/crypto/caam/acipher/caam_rsa.c, core/drivers/crypto/crypto_api/acipher/rsassa.c
Hello,
A small patch set to fix RSA CAAM issue #3657
Thanks!
Clement
=> Fix CAAM RSA inconsistent fails

ta/pkcs11/src/entry.c
Prefer sizeof() to use rc reference rather than explicit 32bit.
=> ta: pkcs11: minor fix of 32bit return code reference for sizeof

ta/pkcs11/include/pkcs11_ta.h, ta/pkcs11/src/persistent_token.c
Define users  with CKU User Type in Cryptoki API:
PKCS11_CKU_SO and PKCS11_CKU_USER. They will be used as identifiers
for login and related PKCS#11 API functions.
=> ta: pkcs11: identify user as per define user types

mk/lib.mk
The command used to link shared libraries when CFG_ULIBS_SHARED=y is
slightly incorrect for two reasons:
1. The -L/-l arguments are passed before the object files, when they
should normally be added after;
2. The shared libraries needed during the link are passed as files in
addition to being supplied with -L/-l. This is redundant, and is a
consequence of having the shared libraries in the prerequisites and
using $^. Order-only prerequisites should be used instead.
=> mk/lib.mk: cleanup shared library link command

core/drivers/stm32_etzpc.c
Changes initcall level for STM32 ETZPC driver so that in initializes
early, at service_init level. The driver does not depends on other
SoC drivers and can be initialize early. This change allows other
driver_init level initialization sequence to use ETZPC resources.
=> drivers/stm32_etzpc: initialize etzpc driver early

core/drivers/gic.c
Current SPI raised by gic_it_set_pending is limited
to secure interrupt. Remove this limitation to let
it be handled by REE.
=> driver/gic: remove SPI security checking

core/arch/arm/tee/entry_std.c, lib/libutee/include/tee_api_defines_extensions.h
Add private login method for REE kernel clients to invoke TAs. It allows
a TA to distinguish among normal world clients whether its a REE kernel
client or a REE user-space client.
=> core: add TEE_LOGIN_REE_KERNEL login method

core/arch/arm/plat-stm32mp1/drivers/stm32mp1_rcc.c, core/arch/arm/plat-stm32mp1/stm32_util.h
Stm32mp1 reset function APIs now get a timeout argument and return
an error if reset domain has not effectively reset when timeout has
expired. A null timeout means the driver loads target reset state
and return without waiting request domain reset state is reached.
=> plat-stm32mp1: change reset functions to get a timeout argument

core/tee/tee_rpmb_fs.c
In tee_rpmb_write_and_verify_key() a call was recently added to check if
the RPMB key was ready to be retrieved. But the function wasn't called
in the new if statement, instead was just the address of the function
tested to be non-NULL. So with this patch add the missing () to make it
a function call.
Fixes: b1042535dc3e ("rpmb: function to block rpmb write per platform")
=> rpmb: fix call to plat_rpmb_key_is_ready()

ta/pkcs11/include/pkcs11_ta.h, ta/pkcs11/src/entry.c, ta/pkcs11/src/handle.c, ta/pkcs11/src/handle.h, ta/pkcs11/src/pkcs11_helpers.c, ta/pkcs11/src/pkcs11_helpers.h, ta/pkcs11/src/pkcs11_token.c, ta/pkcs11/src/pkcs11_token.h, ta/pkcs11/src/sub.mk
This P-R implements support for PKCS11 session commands: open session, close session, close all sessions, get session info. It is spread into a 5 commit series:
* ta: pkcs11: define TA commands related to session management
* ta: pkcs11: add mechanism info and session command to helpers
* ta: pkcs11: handle database for various client references
* ta: pkcs11: register a client instance for each opened TEE session
* ta: pkcs11: session commands support
(If too many commits in the series, tell me, I can split into smaller P-Rs)
This P-R is related to https://github.com/OP-TEE/optee_client/pull/194 and https://github.com/OP-TEE/optee_test/pull/404.
Note that commit "ta: pkcs11: define TA commands related to session management" hurts checkpatch for macro `BIT()` being intentionally not used …
=> ta: pkcs11: session support related commands

.shippable.yml, core/arch/arm/plat-imx/drivers/imx_snvs.c
RPMB ready check keeps on giving. I'll keep this in mind to be more careful when making changes next time. Also add a shippable configuration to catch these kinds of errors. Thanks @ldts for the report.
=> i.MX: fix RPMB ready check function name

core/tee/tee_svc.c
Check that the callee_params are writeable too in tee_svc_copy_param()
as they will be updated in tee_svc_update_out_param() in case one of the
parameters is an "out" parameter. To keep it simple always require
callee_params to be writeable.
Reported-by: Bastien Simondi <bsimondi@netflix.com>
=> core: check writeable in tee_svc_copy_param()

core/drivers/stm32_rng.c
FDT data defines through the status/secure-status property whether
RNG device is assigned to the secure world or to the non-secure
world. This change makes the device driver to register the
peripheral assignation at boot time.
=> drivers/stm32_rng: register device as secure or non-secure

core/arch/arm/crypto/ghash-ce-core_a32.S, core/arch/arm/crypto/ghash-ce-core_a64.S, core/arch/arm/kernel/thread_a32.S, core/arch/arm/kernel/thread_a64.S, core/arch/arm/sm/sm_a32.S, lib/libutils/isoc/arch/arm/arm32_aeabi_divmod_a32.S, lib/libutils/isoc/arch/arm/arm32_aeabi_ldivmod_a32.S
Assembler functions are normally defined using the FUNC/LOCAL_FUNC
macros from <asm.S>. The macros takes care of several things, including
putting the function in a specific section for later garbage collection
by the linker (--gc-sections).
A few files do not follow this convention, let's fix them. Two
functions in ghash-ce-core_a64.S (pmull_gcm_load_round_keys() and
pmull_gcm_aes_sub()) totally lack a .section directive, which I think
is a mistake. Fix them at the same time.
No functional change is expected.
=> Remove '.section .text.<name>' and use function macros instead

core/arch/arm/plat-stm32mp1/drivers/stm32mp1_clk.c
Oscillators, PLLs and AXI/MPU/MCU clocks are not gated from
functions stm32_clock_enable() and stm32_clock_disable(). This change
allows these functions and stm32_clock_is_enabled() to blindly handle
clock gating for such always-on clocks. Gating these clocks is out of
the scope of this change even if preferred for power consumption
optimization considerations.
=> plat-stm32mp1: clock: handle always-on clocks

core/arch/arm/plat-stm32mp1/drivers/stm32mp1_clk.c
Assign a null frequency value to root clocks when FDT defines them
as disabled.
=> plat-stm32mp1: allow fdt to disable root clocks

core/arch/arm/plat-stm32mp1/drivers/stm32mp1_clk.c
Oscillators, PLLs and some system clocks can be related straight to
a parent clock identifier. Prior this change were only oscillators
and few clocks supported by this look up scheme. This changes makes all
parent IDs covered supported. This enables for flexible use of clock
tree exploration when computing a clock frequency value.
Introduces helper function clock_id2parent_id() for clock ID
to parent ID conversion and defines helper right above parent clock
resources for consistency.
=> plat-stm32mp1: clock: allow tree lookup for several system clocks

core/crypto/signed_hdr.c, core/drivers/crypto/crypto_api/acipher/rsa.c, core/include/tee/tee_cryp_utl.h, core/lib/libtomcrypt/dsa.c, core/lib/libtomcrypt/rsa.c, core/tee/tee_cryp_concat_kdf.c, core/tee/tee_cryp_hkdf.c, core/tee/tee_cryp_pbkdf2.c, core/tee/tee_cryp_utl.c, core/tee/tee_svc_cryp.c, lib/libmbedtls/core/rsa.c, lib/libutee/include/utee_defines.h, lib/libutee/tee_api_operations.c
Set digestLength as specified in the TEE Internal Core API, section 6.2.3. Previously, this value was always 0. Fixes #3471. 
Not sure this is the best approach to reuse `tee_hash_get_digest_size`, but those are at this moment core functions that I could not access from libutee. Perhaps moving `tee_hash_get_digest_size` etc. to a new file like core/tee/tee_cryp_utl_size.c and including that file in the build of utee would make  sense.  But I experienced build problems that way, in particular when building 32bit and 64bit together. Maybe I am just not familiar enough with the build system to make it work properly. Either way, having those functions in utee doesn't seem particularly wrong on the other hand, since they don't depend really on core functionality. I think the approach taken …
=> libutee: Set digestLength value in TEE_OperationInfo structure

core/arch/arm/include/sm/optee_smc.h, core/arch/arm/mm/tee_mmu.c, core/arch/arm/tee/entry_fast.c, core/arch/arm/tee/entry_std.c
Refering to GPTS test suite v2.0.0.1-2016-11-09 id de-14-33
Refer to the TEEC_RegisterSharedMemory function for error conditions
which can be triggered during temporary registration of a memory region.
When a CA passes a memref with size 0, a valid pointer must be passed to
the TA.  An example use is passing a read pointer for a shared buffer.
This is tested by GPTS, case de-14-33 for example.
To allow passing a memref with size 0, memref validity is based on pointer
non NULL, not on size non-zero.  For the size 0 case, the minimum
size memory allocation is done to allow a correct virtual address to be
passed.
Signed-off-by: Michael Whitfield <michael.whitfield@nxp.com>
Signed-off-by: Cedric Neveux <cedric.neveux@nxp.com>
=> core: arch: arm: Allow memrefs with size 0

core/drivers/scmi-msg/base.c, core/drivers/scmi-msg/base.h, core/drivers/scmi-msg/clock.c, core/drivers/scmi-msg/clock.h, core/drivers/scmi-msg/common.h, core/drivers/scmi-msg/entry.c, core/drivers/scmi-msg/reset_domain.c, core/drivers/scmi-msg/reset_domain.h, core/drivers/scmi-msg/smt.c, core/drivers/scmi-msg/sub.mk, core/drivers/sub.mk, core/include/drivers/scmi-msg.h, core/include/drivers/scmi.h, mk/config.mk
These changes propose a set of drivers to help a platform to embed an SCMI server in OP-TEE.
This P-R proposes support for SCMI base, clock and reset domain protocols. More protocols can easily be added.
SCMI message drivers offers API functions to read an SCMI message received by Core. The drivers call one or more platform handlers to get the message handled. For example a clock STATE_SET message ends in platform clock driver interface to enable/disable the clock. The drivers only carry the messages to the right platform handler.
SCMI message drivers use the SMT header format to manage the shared memory area used for SCMI message exchanges. SCMI message notification channel can be:
* an interrupt: if so, SCMI message drivers execute in interrupt context up to handlers completion. …
=> SCMI message drivers

core/kernel/lockdep.c, mk/config.mk
The lockdep algorithm uses quite a bit of heap memory to record the
call stacks. This commit adds a configuration flag so that this may be
turned off. When CFG_LOCKDEP_RECORD_STACK=n the deadlock detection
still works but the diagnostics message will show no call stack
obviously.
=> core: lockdep: introduce CFG_LOCKDEP_RECORD_STACK

core/tee/tee_svc.c
Ensure that TA param mobj is set to NULL, in case User Parameter of
type IN/OUT memref is NULL with a size=0 is handled.
Signed-off-by: Cedric Neveux <cedric.neveux@nxp.com>
=> [fix] core: TEE capability for null sized memrefs support

ta/pkcs11/src/pkcs11_token.c
Fix PKCS11 TA command PKCS11_CMD_MECHANISM_IDS to handle case
where client provides a NULL buffer reference when querying the
list of supported mechanism IDs. In such case TA should return OK,
not PKCS11_CKR_BUFFER_TOO_SMALL.
This change is needed since commit [1] that makes an OP-TEE TA able
to receive memref parameters with a NULL buffer reference.
Link: [1] 20b567068a37 ("libutee: flag NULL pointer using invalid shm id")
=> ta: pkcs11: fix MECHANISM_IDS to return OK when no output buffer

ta/pkcs11/src/token_capabilities.c
Drop key derivation as a capability of mechanisms AES_ECB as not part
of the PKCS#11 specification.
Reported-by: Ricardo Salveti <ricardo@foundries.io>
=> ta: sks: drop derive from AES_ECB

Makefile
Some linux distributions do not provide bash at the /bin/bash location,
use the /usr/bin/env wrapper which is guaranteed to exist instead.
=> Makefile: use plain bash for SHELL

core/pta/tests/invoke.c, lib/libutee/include/pta_invoke_tests.h
Add command PTA_INVOKE_TESTS_CMD_MEMREF_NULL to test invocation
of a PTA with a memref parameter with a NULL buffer reference.
The PTA should successfully be invoked with a valid memref
parameter yet referring to a NULL buffer pointer.
=> pta: invoke_test.pta: add test on null memref parameter

core/drivers/crypto/caam/caam_desc.c, core/drivers/crypto/caam/caam_jr.c, core/drivers/crypto/caam/include/caam_desc_helper.h, core/drivers/crypto/caam/include/caam_jr.h
Hello,
This PR is a follow-up of this previous PR : https://github.com/OP-TEE/optee_os/pull/3713
I took the suggestion from @jenswi-linaro where we should supply the function with a pointer to ```struct outring_entry``` instead of a ```void *```.
Thanks
=> drivers: caam: use pointers to out/inring_entry for CAAM

.github/issue_template.md, .github/pull_request_template.md
Auto-generated URLs from readthedoc.io has changed since we started
using it. This fixes broken links in our GitHub template files.
=> github: update links in issue/pr templates

core/arch/arm/mm/core_mmu.c
On platforms where the DT is parsed from the device tree, devices can
pass in the complete available memory. This is in accordance with the
device tree specification which mandates that the total physical memory
should be passed in the memory nodes.
Remove the TZDRAM from the passed in memory on platforms with CFG_DT,
here reserved-memory nodes are used to indicate that part of the RAM is
not accessible to Linux. Fixes the following warning on some i.MX
platforms:
I/TC: Non-secure external DT found
E/TC:0 0 check_phys_mem_is_outside:330 Non-sec mem (0x10000000:0x40000000) overlaps map (type 2 0x4e000000:0x5d000)
E/TC:0 0 Panic at core/arch/arm/mm/core_mmu.c:334 <check_phys_mem_is_outside>
E/TC:0 0 TEE load address @ 0x4e000000
E/TC:0 0  0x4e006fd1
Fixes …
=> core: mmu: remove TEE/TA RAM from passed in total RAM

ta/pkcs11/include/pkcs11_ta.h, ta/pkcs11/src/entry.c, ta/pkcs11/src/persistent_token.c, ta/pkcs11/src/pkcs11_helpers.c, ta/pkcs11/src/pkcs11_helpers.h, ta/pkcs11/src/pkcs11_token.c, ta/pkcs11/src/pkcs11_token.h
=> Pkcs11 login

MAINTAINERS, core/arch/arm/plat-uniphier/conf.mk, core/arch/arm/plat-uniphier/kern.ld.S, core/arch/arm/plat-uniphier/link.mk, core/arch/arm/plat-uniphier/main.c, core/arch/arm/plat-uniphier/platform_config.h, core/arch/arm/plat-uniphier/sub.mk
This introduces support for Socionext UniPhier SoCs in 64-bit mode,
that include LD11 and LD20. Tested with Akebi96 board[1].
[1] https://www.96boards.org/product/akebi96/
Signed-off-by: Tetsuya Yoshizaki <yoshizaki.tetsuya@socionext.com>
Signed-off-by: Kunihiko Hayashi <hayashi.kunihiko@socionext.com>
=> Add initial UniPhier platform support

core/lib/libtomcrypt/dsa.c, core/tee/tee_svc_cryp.c
When generating a DSA key, syscall_obj_generate_key() currently ignores
the supplied parameters: TEE_ATTR_DSA_PRIME, TEE_ATTR_DSA_SUBPRIME and
TEE_ATTR_DSA_BASE. Instead a new set of parameters is generated each
time based on the specified key size. This does not comply with the
GlobalPlatform TEE Internal Core API specification which lists these
atrributes as mandatory input to the generation function (see v1.2.1
table 5-12 TEE_GenerateKey parameters).
Fix this issue by providing the supplied parameter to LibTomCrypt's
dsa_generate_key() instead of calling dsa_make_key().
Fixes: https://github.com/OP-TEE/optee_os/issues/3746
=> core: crypto: use supplied DSA parameters when creating key

core/crypto/crypto.c, core/include/crypto/crypto.h, core/lib/libtomcrypt/dh.c, core/tee/tee_svc_cryp.c, lib/libmbedtls/core/dh.c
TEE_GenerateKey() takes a key_size argument and various attributes. For
Diffie-Hellman, if the size of the prime number (TEE_ATTR_DH_PRIME) is
not key_size, we should return TEE_ERROR_BAD_PARAMETERS as per the GP
TEE Internal Core API specification v1.2.1: "If an incorrect or
inconsistent attribute is detected. The checks that are performed
depend on the implementation.".
=> core: crypto: DH: make sure key_size is consistent with attributes

core/crypto/crypto.c, core/include/crypto/crypto.h, core/lib/libtomcrypt/ecc.c, core/tee/tee_svc_cryp.c, lib/libmbedtls/core/ecc.c
TEE_GenerateKey() takes a key_size argument and various attributes. If
the size derived from the attributes is not key_size, we should return
TEE_ERROR_BAD_PARAMETERS as per the GP TEE Internal Core API
specification v1.2.1: "If an incorrect or inconsistent attribute is
detected. The checks that are performed depend on the implementation.".
=> core: crypto: ECC: make sure key_size is consistent with attributes

mk/clang.mk
Adds missing definition for libgcc$(sm) (the compiler runtime library)
to mk/clang.mk.
=> mk/clang.mk: define libgcc$(sm)

mk/clang.mk
AOSP's prebuilt versions of Clang [1] don't contain the clang-cpp
symlink to clang, so use the equivalent command of 'clang -E' instead.
LINK: [1] https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/refs/heads/master
LINK: [2] https://github.com/llvm/llvm-project/tree/llvmorg-9.0.1
LINK: [3] https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/refs/heads/master/clang-r370808/bin/clang
Suggested by: Jerome Forissier <jerome@forissier.org>
Tested-by: Victor Chong <victor.chong@linaro.org> (builds only with
clang-v9.0.1 [2] and AOSP clang v10.0.1 [3])
=> mk: clang.mk: use 'clang -E' instead of clang-cpp

core/tee/tee_rpmb_fs.c, mk/config.mk
This patch adds optional FAT FS entry caching functionality to the
RPMB FS. This functionality can be enabled and configured in
config.mk. The caching functionality can improve RPMB I/O at the
cost of additional heap memory. The cache size is most likely
platform-specific and should be chosen according to available secure
world memory and expected FAT FS entries in RPMB. The cache holds
the first X FAT FS entry in RAM. Whenever the FAT FS is traversed,
we read from the cache instead of invoking RPMB I/O. The cache is
updated when cached FAT FS entries are written.
Signed-off-by: Manuel Huber <mahuber@microsoft.com>
=> core: RPMB FS: Caching for FAT FS entries

core/arch/arm/kernel/ree_fs_ta.c
Initialize structs with '= { };' rather than '= {0};' because (1) it is
the recommended style and (2) it fixes the following warning with Clang
9:
CC      out/arm/core/arch/arm/kernel/ree_fs_ta.o
core/arch/arm/kernel/ree_fs_ta.c:325:40: warning: suggest braces around initialization of subobject [-Wmissing-braces]
struct shdr_bootstrap_ta hdr_entry = {0};
^
{}
=> core: ree_fs_ta.c: initialize structs with '= { };'

scripts/gen_ldelf_hex.py
Latest Clang [1] generates the following ldelf.elf:
```
Program Headers:
Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
LOAD           0x001000 0x00000000 0x00000000 0x04834 0x04834 R E 0x1000
LOAD           0x005838 0x00004838 0x00004838 0x01620 0x01620 R   0x1000
LOAD           0x007000 0x00006000 0x00006000 0x0006c 0x0006c RW  0x1000
LOAD           0x00706c 0x0000606c 0x0000606c 0x00068 0x00078 RW  0x1000
DYNAMIC        0x007000 0x00006000 0x00006000 0x00060 0x00060 RW  0x4
GNU_RELRO      0x007000 0x00006000 0x00006000 0x0006c 0x01000 R   0x1
GNU_STACK      0x000000 0x00000000 0x00000000 0x00000 0x00000 RW  0
EXIDX          0x006800 0x00005800 0x00005800 0x002b8 0x002b8 R   0x4
```
Nothing wrong with that from a strict ELF compliance point of view, but
it …
=> scripts/gen_ldelf_hex.py: relax rules for PT_LOAD segments

core/arch/arm/plat-stm32mp1/main.c
Fix GPZIOZ registers memory mapping that shall be mapped secure
for secure world to safely access the secure hardening configuration
registers of the bank.
Fixes: 68c4a16b37c7 ("stm32mp1: use phys_to_virt_io_secure() where expected")
=> plat-stm32mp1: map GPIOZ bank registers as secure

core/arch/arm/plat-stm32mp1/main.c, core/arch/arm/plat-stm32mp1/stm32_util.h, core/drivers/stm32_bsec.c, core/include/drivers/stm32_bsec.h
A series of fixes in stm32_bsec driver.
This P-R is a preparation for BSEC SiP service in platform stm32mp1 that were introduced in stalled P-R https://github.com/OP-TEE/optee_os/pull/3063. I'll create a new P-R for this on top of these fixes.
=> stm32_bsec: fixes

core/arch/arm/plat-stm32mp1/main.c, core/arch/arm/plat-stm32mp1/shared_resources.c
Remove static ETZPC configuration and rely on shared_resources
driver to dynamically configure secure aware resources.
=> plat-stm32mp1: remove static ETZPC configuration

core/lib/libtomcrypt/acipher_helpers.h
Calling TEE_AsymmetricVerifyDigest() with lnvalid RSA signature
length cause TA to panic. Introduced by commit:
a3f5668a0cae797a8eee1c0f3287983c5eb749eb
By GP TEE Internal Core specs, TEE_AsymmetricVerifyDigest()
shouldn't cause panic when call with invalid signature length.
=> core: libtomcrypt: fix return code in convert_ltc_verify_status()

core/arch/arm/kernel/link.mk, mk/clang.mk
Core ASLR relies on the executable being ready to run from its
preferred load address, because some symbols are used before the MMU is
enabled and relocations are applied. Clang (ld.lld) on Aarch64 needs a
special flag for this: --apply-dynamic-relocs. Without the flag the
R_AARCH64_RELATIVE places are initially filled with zeros.
=> core: clang: add --apply-dynamic-relocs linker flag

mk/clang.mk
Since LLVM commit [1] ("[ELF] Keep orphan section names (.rodata.foo
.text.foo) unchanged if !hasSectionsCommand"), ld.lld behaves like GNU
ld regarding output section names. So, we can remove our temporary hack.
This also fixes a build issue when a newer Clang (v11 master) is used
together with an older GNU ld (8.3 for instance) due to the latter not
supporting some GNU_PROPERTY_* values generated by the Clang compiler:
LD      out/arm/core/tee.elf
bin/aarch64-linux-gnu-ld: warning: out/arm/core/ta_pub_key.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
...
Link: [1] https://github.com/llvm/llvm-project/commit/9e33c096476a
=> core: clang: pager: use the normal linker (ld.lld)

core/arch/arm/plat-stm32mp1/rng_seed.c, core/arch/arm/plat-stm32mp1/sub.mk
Initialize the core PRNG with samples from the SoC RNG during early
initialization. PRNG is used to generate random samples used early
before all services and obviously device and peripheral drivers
are initialized. Therefore the platform sequence to initialize the
PRNG locally handles RNG clock and reset without relying on clock
and reset device drivers as these are not yet initialized.
=> stm32mp1: seed PRNG with STM32 RNG

lib/libutils/ext/include/confine_array_index.h
Fix implementation of confine_array_index() for 32bit Arm and Thumb2
modes as previous implementation does not explicit the return value
and show issues with GCC 8.3 compiler.
Fixes: https://github.com/OP-TEE/optee_os/issues/3799
Fixes: 2b6dd0df52b4 ("confine_array_index.h: add A32 and T32 versions of confine_array_index()")
Tested-by: Etienne Carriere <etienne.carriere@linaro.org> (qemu,qemu_v8)
=> lib: fix confine_array_index() for 32bit modes

core/tee/tee_rpmb_fs.c
Remove unnecessary check to fix compile warning reported
by clang as following:
core/tee/tee_rpmb_fs.c:2051:11: warning: address of array 'fh->filename'
will always evaluate to 'true' [-Wpointer-bool-conversion]
if (fh->filename && (!strcmp(fh->filename,
fe->filename)) &&
~~~~^~~~~~~~ ~~
core/tee/tee_rpmb_fs.c:2134:10: warning: address of array 'fh->filename'
will always evaluate to 'true' [-Wpointer-bool-conversion]
if (fh->filename && !fh->rpmb_fat_address)
~~~~^~~~~~~~ ~~
=> rpmb: remove unnecessary check

core/drivers/stm32_rng.c
When enabling STM32 RNG from reset state, it may take few milliseconds
for the RNG to be ready. Use a longer timeout to warm up RNG when it
is enabled.
Fixes panic at platform boot with trace:
E/TC:0 0 Panic at core/arch/arm/plat-stm32mp1/rng_seed.c:48 <plat_rng_init>
Fixes: 4e0397eed2e5 ("stm32mp1: seed PRNG with STM32 RNG")
=> plat-stm32mp1: fix timeout when seeding PRNG

scripts/checkpatch_inc.sh
Prevent reports like:
ba3899ce plat-stm32mp1: PSCI_SYSTEM_RESET support
CHECK: usleep_range is preferred over udelay; see Documentation/timers/timers-howto.rst
#30: FILE: core/arch/arm/plat-stm32mp1/pm/psci.c:215:
+	udelay(100);
Suggested-by: Jerome Forissier <jerome@forissier.org>
=> checkpatch: ignore USLEEP_RANGE

lib/libmbedtls/mbedtls/library/bignum.c
If mbedtls_mpi_shrink() is passed a value for nblimbs that is smaller
than the minimum number of limbs required to store the big number, the
current implementation will unexpectedly truncate the number to the
requested size. It should use the minimal size instead in order not to
corrupt the bigum value.
This issue was introduced in [1] probably as a result of a bad copy
and paste from mbedtls_mpi_grow().
Fixes: [1] commit 98bd5fe350be ("libmbedtls: add mbedtls_mpi_init_mempool()")
Reported-by: Zhenke Ma <zhenke.ma@armchina.com>
=> libmbedtls: mbedtls_mpi_shrink(): fix possible unwanted truncation

core/arch/arm/include/sm/sm.h, core/arch/arm/include/sm/std_smc.h, core/arch/arm/sm/sm.c
SMCCC v1.1 specification: support defined function IDs with weak
handlers platform can override, as other PSCI function handler.
* `unsigned long arm_arch_version(void);`
returns SMCCC_V_1_1
* `unsigned long arm_arch_feature(unsigned long a1);`
default supports version only
* `unsigned long arm_arch_soc_id(void);`
`unsigned long arm_arch_workaround_1(void);`
`unsigned long arm_arch_workaround_2(void);`
default return ARM_SMCCC_RET_NOT_SUPPORTED
This support is needed by Linux kernel (maybe U-Boot one day) drivers that rely on `arm_smccc_1_1()` supports. Linux kernel probes SMCCC v1.1 support to establish SMC/HVC conduit. Caller driver don't need to select smc/hvc.
=> core: sm: support SMCCC v1.1 specification

core/arch/arm/plat-stm32mp1/drivers/stm32mp1_clk.c
Fix implementation that divides clock with a value that in fact is
a bit shift value.
Fix implementation for getting MPU clock: when PMUDIV is zero,
MPU clock is disabled.
=> plat-stm32mp1: clock: fix MPUDIV support

core/arch/arm/plat-stm32mp1/drivers/stm32mp1_clk.c
With this change some system clocks are enabled by Core at
boot time and have a reference counter synchronized with
the clock hardware state. RTCAPB must be enabled for secondary
cores to boot, if any.
This change also ensures these secure clocks are derived from
secure clocks.
=> plat-stm32mp1: clock: enable some secure clocks at initialization

core/arch/arm/plat-imx/crypto_conf.mk, core/drivers/crypto/caam/blob/caam_blob.c, core/drivers/crypto/caam/blob/sub.mk, core/drivers/crypto/caam/caam_ctrl.c, core/drivers/crypto/caam/hal/common/hal_ctrl.c, core/drivers/crypto/caam/include/caam_blob.h, core/drivers/crypto/caam/include/caam_hal_ctrl.h, core/drivers/crypto/caam/include/caam_trace.h, core/drivers/crypto/caam/sub.mk, core/include/initcall.h
This is a port of PR #3160 to the NXP CAAM driver. The i.MX platform configuration is also modified to enable the MKVB generation for all possible platforms.
This PR:
1. introduces a early_driver initcall which runs before the service initcalls
2. moves the CAAM initialization there
3. implements a MKVB module which retrieves the MKVB
4. implements the platform implementation to retrieve a HUK using the MKVB
5. moves the jobring handoff into the driver_late initcall
This way there is always a jobring available during OP-TEE initialization which is used to retrieve the MKVB. Instead of disabling the complete CAAM driver, the default configuration now disables the crypto driver and runtime jobring access to prevent the SoC hang if clocks are disabled.
cc @clementfaure
=> Hardware Unique Key (HUK) generation using the CAAM Master Key Verification Blob (MKVB) for i.MX platforms.

scripts/gen_ldelf_hex.py
f-strings were introduced in Python 3.6 [1] and will therefore
cause an error with prior versions:
| File "scripts/gen_ldelf_hex.py", line 68
| print(f'RO load segment found after RW one(s) (m={n})')
| ^
| SyntaxError: invalid syntax
For better compatibility use .format() instead.
Link: [1] https://docs.python.org/3/whatsnew/3.6.html#pep-498-formatted-string-literals
Fixes: c706c2449b50 ("scripts/gen_ldelf_hex.py: relax rules for PT_LOAD segments")
=> scripts/gen_ldelf_hex.py: do not use f-strings

lib/libutee/tee_api_operations.c
Explicitly initialize operation param buffer_offs in TEE_AEInit() instead
of relying on TEE_AllocateOperation() as it may cause issues while using
operation handle allocated once and used in subsequent authenticated
encryption operations.
It is quite similar to how TEE_CipherInit() and init_hash_operation()
initializes buffer_offs.
=> libutee: crypto: AE: Explicitly initialize buffer_offs

core/arch/arm/include/kernel/generic_boot.h, core/arch/arm/kernel/generic_boot.c, core/arch/arm/kernel/link_dummies_paged.c, core/kernel/console.c
This P-R supersedes  https://github.com/OP-TEE/optee_os/pull/3827.
Initial purpose is to allow console generic initialization to use the embedded DTB instead of the external DTB.
However this simple change makes the embedded DTB to move from a pageable section to an _init_ section (pageable sections pre-loaded/mapped at Core early boot time) since embedded DTB would be accessed from `init_primary_helper()`. This can be a issue from some platforms.
This P-R proposes to relax a part of the Core initialization sequence from the pager _init_ section constraints. See 1st commit of this series. **(still a draft, deserves some cleaning)**
The 2nd commit implements https://github.com/OP-TEE/optee_os/pull/3827 proposal.
Few numbers to illustrate, based on **plat-stm32mp1** (enables pager) builds …
=> core: try to get embedded dt when external dt not found (2nd try)

.shippable.yml
Add build test for platform flavor stm32mp1-157C_DK2 to build stm32mp1
with an embedded DTB.
=> shippable: build stm32mp1-157C_DK2

core/arch/arm/kernel/generic_boot.c
In 32-bit builds with CFG_CORE_LARGE_PHYS_ADDR=y, PRIxPA is "llx"
which is not the recommended format to print an unsigned long int.
Use "lx" instead to avoid warnings with some compilers.
=> core: generic_boot: use "%#lx" to print unsigned long, not "0x%"PRIxPA

core/arch/arm/plat-stm32mp1/pm/psci.c
As per Arm SMCCC v1.1 specification [1], PSCI PSCI_FEATURES function ID
should report Arm Architecture Call SMCCC_VERSION as supported when
the secure firmware supports both PSCI PSCI_FEATURE function ID and
Arm SMCCC_VERSION function ID.
Link: [1] https://developer.arm.com/docs/den0028/latest
=> plat-stm32mp1: psci: support Arm SMCCC_VERSION function ID

core/arch/arm/dts/stm32mp151.dtsi, core/arch/arm/dts/stm32mp157a-dk1.dts, core/arch/arm/dts/stm32mp157c-dk2.dts, core/arch/arm/dts/stm32mp157c-ed1.dts, core/arch/arm/plat-stm32mp1/conf.mk, core/arch/arm/plat-stm32mp1/nsec-service/bsec_svc.c, core/arch/arm/plat-stm32mp1/nsec-service/bsec_svc.h, core/arch/arm/plat-stm32mp1/nsec-service/stm32mp1_smc.h, core/arch/arm/plat-stm32mp1/nsec-service/stm32mp1_svc_setup.c, core/arch/arm/plat-stm32mp1/nsec-service/sub.mk, core/drivers/stm32_bsec.c
This P-R supersedes https://github.com/OP-TEE/optee_os/pull/3063/files.
This P-R implements management of SiP SMCs allowing non-secure world to access platform secure fuses that platform secure device tree defines as accessible from non-secure world.
=> stm32mp1: SiP SMCs for BSEC access (take 2)

core/arch/arm/plat-hisilicon/psci.c
As per Arm SMCCC v1.1 specification [1], PSCI PSCI_FEATURES function ID
should report Arm Architecture Call SMCCC_VERSION as supported when
the secure firmware supports both PSCI PSCI_FEATURES function ID and
Arm SMCCC_VERSION function ID.
Link: [1] https://developer.arm.com/docs/den0028/latest
=> plat-hisilicon: psci: support Arm SMCCC_VERSION function ID

core/tee/tee_rpmb_fs.c
Building with CFG_RPMB_FS=y and CFG_TEE_CORE_LOG_LEVEL=4 yields a
compile-time error due to a typo.
Replacing TEE_RESULT with TEE_Result fixes the issue.
Signed-off-by: Gianguido Sorà <me@gsora.xyz>
=> rpmb: fix building when TRACE_LEVEL >= TRACE_FLOW

core/arch/arm/kernel/generic_boot.c, core/arch/arm/plat-stm32mp1/drivers/stm32mp1_clk.c, core/arch/arm/plat-stm32mp1/shared_resources.c, core/core.mk, core/drivers/imx_wdog.c, core/drivers/stm32_bsec.c, core/drivers/stm32_etzpc.c, core/drivers/stm32_gpio.c, core/drivers/stm32_rng.c, core/kernel/console.c, core/kernel/tpm.c
libfdt is built only when CFG_DT=y. As a result, the libfdt header
files are only available when CFG_DT=y and any source file that makes
optional use of the library has to guard the #include <libfdt.h> with
a #ifdef CFG_DT ... #endif block. This contrasts with other features
which don't require such guards.
This patch builds libfdt unconditionally and removes the include
guards. No change is expected in the binaries.
=> [RFC] core: always build libfdt

core/arch/arm/plat-stm32mp1/drivers/stm32mp1_clk.c, core/arch/arm/plat-stm32mp1/drivers/stm32mp1_rcc.h, core/arch/arm/plat-stm32mp1/drivers/stm32mp1_syscfg.c, core/arch/arm/plat-stm32mp1/drivers/sub.mk, core/arch/arm/plat-stm32mp1/main.c, core/arch/arm/plat-stm32mp1/platform_config.h, core/arch/arm/plat-stm32mp1/stm32_util.h
Implement platform functions stm32mp_syscfg_enable_io_compensation()
and stm32mp_syscfg_disable_io_compensation() to enable/disable
STM23MP1 IO compensation. Enable IO compensation when platform boots.
This change defines SYSCFG clock that is needed and moves definition
of the RCC compatible string DT_RCC_CLK_COMPAT to RCC header file so
that it can be shared with stm32mp1_syscfg.c.
=> plat-stm32mp1: enable IO compensation at boot time

mk/subdir.mk
As a general rule, paths to directories should not end with a slash
[1]. In some cases, $(sub-dir-out) does not meet this requirement. For
example when building the 'crypt' TA in the optee_test project:
```
GEN     /tmp/optee/optee_test/out/ta/crypt//ca_crt.c
CC      /tmp/optee/optee_test/out/ta/crypt//ca_crt.o
GEN     /tmp/optee/optee_test/out/ta/crypt//mid_crt.c
CC      /tmp/optee/optee_test/out/ta/crypt//mid_crt.o
GEN     /tmp/optee/optee_test/out/ta/crypt//mid_key.c
CC      /tmp/optee/optee_test/out/ta/crypt//mid_key.o
```
In this example, $(sub-dir-out) is /tmp/optee/optee_test/out/ta/crypt/.
This patch removes the trailing slash.
[1] commit 4334e8d79fa3 ("Makefile variables $(*-dir) should not have a
trailing slash")
=> mk/subdir.mk: avoid trailing slash in $(sub-dir-out)

core/pta/device.c, lib/libutee/include/pta_device.h, lib/libutee/include/user_ta_header.h
Some TAs require tee-supplicant to be run. For example fTPM requires
storage services provided by tee-supplicant. When scanning and
probe() devices on tee bus we can initialize early drivers which
do not require tee-supplicant and after mount fs and tee-supplicant
run do probe() drivers witch require tee-supplicant.
Signed-off-by: Maxim Uvarov <maxim.uvarov@linaro.org>
=> core: device pta: add flag to watch for running tee-supplicant

core/arch/arm/plat-stm32mp1/nsec-service/stm32mp1_svc_setup.c
Load STM32_SIP_SVC_OK in output argument a0 on return from
SCMI message notification from SiP SMC function IDs. It simplifies
non-secure world to consider any non-zero values,
including standard unknown function error code (-1), as
reporting a failure.
=> plat-stm32mp1: ack SCMI SiP SMC entry with 0 return code

core/arch/arm/include/kernel/thread.h, core/arch/arm/kernel/generic_entry_a32.S, core/arch/arm/kernel/wait_queue.c, core/drivers/crypto/crypto_api/acipher/local.h, core/include/crypto/crypto.h, core/include/kernel/handle.h, ta/pkcs11/include/pkcs11_ta.h, ta/pkcs11/src/handle.h
a input -> an input
Optinally -> Optionally
the the -> if the, the, by the, to the (guessed from context)
(typos inherited from upstream are kept)
Signed-off-by: Markus S. Wamser <github-dev@mail2013.wamser.eu>
=> batch typo fixes in documentation/comments

core/arch/arm/mm/tee_mmu.c, core/include/kernel/tee_misc.h, core/kernel/tee_misc.c
The core_is_buffer_*() helpers are sometimes used with physical
addresses (type paddr_t). This can cause problem on platforms where
sizeof(paddr_t) > sizeof(vaddr_t), that is on ARM32 systems with
CFG_CORE_LARGE_PHYS_ADDR=y. The FVP platform compiled for AArch32 is one
such system which as a consequence fails with:
E/TC:0 0 check_phys_mem_is_outside:335 Non-sec mem (0x880000000:0x180000000) ove
rlaps map (type 12 0xff000000:0x1000000)
E/TC:0 0 Panic at core/arch/arm/mm/core_mmu.c:336 <check_phys_mem_is_outside>
This patch fixes this problem by taking input addresses as paddr_t and
sizes as paddr_ssize_t instead. The wrapper macros which did some
automatic casting removed. The requires updates at some of the places
where these functions are called.
Signed-off-by: Jens Wiklander …
=> core: make core_is_buffer_*() paddr_t compatible

core/arch/arm/plat-imx/pm/psci.c
As per Arm SMCCC v1.1 specification [1], PSCI PSCI_FEATURES function ID
should report Arm Architecture Call SMCCC_VERSION as supported when
the secure firmware supports both PSCI PSCI_FEATURES function ID and
Arm SMCCC_VERSION function ID.
Link: [1] https://developer.arm.com/docs/den0028/latest
=> plat-imx: psci: support Arm SMCCC_VERSION function ID

lib/libutils/ext/include/confine_array_index.h
Older compilers such as GCC 6.2 do not support the csdb mnemonic [1].
For better compatibility, replace it by its equivalent: `hint #20`.
```
CC      out/arm/ldelf/ta_elf_rel.o
{standard input}: Assembler messages:
{standard input}:274: Error: unknown mnemonic `csdb' -- `csdb'
{standard input}:371: Error: unknown mnemonic `csdb' -- `csdb'
{standard input}:667: Error: unknown mnemonic `csdb' -- `csdb'
{standard input}:776: Error: unknown mnemonic `csdb' -- `csdb'
{standard input}:1010: Error: unknown mnemonic `csdb' -- `csdb'
{standard input}:1084: Error: unknown mnemonic `csdb' -- `csdb'
{standard input}:1413: Error: unknown mnemonic `csdb' -- `csdb'
{standard input}:1495: Error: unknown mnemonic `csdb' -- `csdb'
{standard input}:1671: Error: unknown mnemonic `csdb' -- `csdb'
make[1]: *** …
```
=> libutils: confine_array_index: arm64: replace csdb by hint #20

core/arch/arm/kernel/link.mk
The following errors were observed when building with GCC 6.2.1:
- 64 bits:
GEN     out/arm/core/tee.bin
Unexpected relocation type 0x101
- 32 bits:
GEN     out/arm/core/tee.bin
Unexpected relocation type 0x2
Relocation type 0x101 is R_AARCH64_ABS64 and 0x2 is R_ARM_ABS32. The
errors are output by scripts/gen_tee_bin.py which expects only relative
relocations (the ones that are necessary for ASLR).
This patch adds the -Bsymbolic linker option to avoid these
relocations. More information can be found in Linux commit [1].
Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=08cc55b2afd97a654f71b3bebf8bb0ec89fdc498
=> core: aslr: suppress R_AARCH64_ABS64 and R_ARM_ABS32 relocations

core/arch/arm/mm/tee_mmu.c
vm_unmap() use r->va and r->size after it already freed cause the
end VA address calulation to be wrong and the while loop keep going
till it unmap rest of the regions. This bug usually cause TA to
crash with translation fault since vm_unmap() removed text and data
regions.
=> core: tee_mmu: fix use after free bug in vm_unmap()

CHANGELOG.md
Update CHANGELOG for 3.9.0 and collect Tested-by tags.
=> Update CHANGELOG for 3.9.0

.travis.yml
Since commit e7e3142343c2 ("checkpatch: add codespell support"),
checkpatch.pl expects to find the codespell dictionary at
/usr/share/codespell/dictionary.txt. This patch adds the missing
package.
=> ci: travis: install codespell package

scripts/pem_to_pub_c.py
Upgrade scripts/pem_to_pub.py to use module Cryptodome instead of
module Crypto for consistency with the other helper Python scripts
of OP-TEE OS package.
=> scripts/pem_to_pub.py: use Cryptodome module instead of Crypto

core/arch/arm/arm.mk, core/core.mk, mk/cc-option.mk, mk/clang.mk, mk/compile.mk, mk/gcc.mk, ta/mk/ta_dev_kit.mk, ta/ta.mk
This is a follow-up to https://github.com/OP-TEE/optee_os/pull/3874 which I unfortunately had to revert until I could investigate a few issues.
Well there it is, I have now fixed the cc-option macro and (hopefully) dealt with circular dependencies so that it can finally be used as intended.
I spent quite some time figuring out the root cause of the `bash: --: invalid option` [error](https://github.com/OP-TEE/optee_os/pull/3874#issuecomment-633617767), the reason is we were using `?=` instead of `:=` when defining the platform flags but the latter form is needed for immediate evaluation of `$(call cc-option...)`, i.e., with the current value of `$(CC$(sm))`.
Perhaps a global replace of `?=` with `:=` would be in order for everything but the `CFG_` flags (which have a [good …
=> Fix cc-option and disable outline-atomics when applicable

core/arch/arm/plat-imx/conf.mk, core/arch/arm/plat-imx/main.c
Following up on @clementfaure suggestion (#3869), remove
CFG_BOOT_SYNC_CPU.
It was disabled by default, and no i.MX platform was enabling it anyway.
=> plat-imx: remove CFG_BOOT_SYNC_CPU

ta/mk/build-user-ta.mk
Unbreaks building of vexpress-qemu_armv8a and k3-am65x, e.g.
Fixes: 682f256 ("TA dev kit: expose CFG_TA_VERSION build option")
Signed-off-by: Jan Kiszka <jan.kiszka@siemens.com>
=> ta: Add missing default user-ta-version settings

lib/libutee/base64.c, lib/libutee/tee_api_property.c
Fixes https://github.com/OP-TEE/optee_os/issues/3876 **~~+ relax property type used with `TEE_GetPropertyAsBinaryBlock()`~~**.
**(edited)**
=> Fixes for TEE_GetPropertyAsBinaryBlock() support

core/arch/arm/arm.mk
With ARM CPUs, unaligned accesses are forbidden in a number of cases
such as when the MMU is disabled, or when device memory is concerned,
or with atomic instructions. However in the general case [1] and for
all modern ARMv7-A and ARMv8-A processors, they do not really matter.
Compilers such as GCC and Clang will generate unaligned accesses by
default; a specific flag (-mstrict-align or --mno-unaligned-access) has
to be supplied to prevent such code from being output.
[1] Roughly speaking: LDR/STR instructions operating on normal cached
memory.
The SCTLR.A bit ("Alignment check enable") defines whether the CPU
should allow these unaligned accesses (when set to 0) or should trap
(when set to 1). Having SCTLR.A enabled by default can be annoying for
a couple of reasons that we have met in …
=> Disable CFG_SCTLR_ALIGNMENT_CHECK (SCTLR.A) by default

lib/libutils/ext/include/atomic.h
Prior to this patch was atomic_load_u32() using wrong types, unsigned int
instead of the expected uint32_t. Fix this by changing the types.
=> libutils: atomic.h: fix atomic_load_u32() types

mk/cc-option.mk, ta/arch/arm/link_shlib.mk
Link shared libraries with the LLVM linker option `-z separate-loadable-segments` (when supported) so that the `PT_LOAD` segments are laid out as expected by `ldelf`.
=> Clang 10 support

core/arch/arm/kernel/thread.c
When building for HiKey with Clang 10.0.0 and DEBUG=1 we get the
following panic:
D/TC:0 0 check_pa_matches_va:2120 va 0x3b000000 maps 0x3f200000, expect 0x0
E/TC:0 0 Panic at core/arch/arm/mm/core_mmu.c:2121 <check_pa_matches_va>
The root cause is an overflow of the temporary stack. DEBUG=1 sets
CFG_CC_OPTIMIZE_FOR_SIZE=n which in turn sets the optimization flags to
-O0 instead of -Os. In this configuration, Clang apparently needs much
more stack space (not something observed with GCC).
This commit increases the temporary stacks from approximately 2K per
core to approximately 4K per core.
Acked-by: Etienne Carriere <etienne.carriere@linaro.org>
=> core: arm64: clang: increase temporary stack size

core/arch/arm/include/kernel/thread.h, core/arch/arm/kernel/boot.c, core/arch/arm/kernel/entry_a32.S, core/arch/arm/kernel/entry_a64.S, core/arch/arm/kernel/thread.c, core/arch/arm/kernel/unwind_arm32.c, core/arch/arm/kernel/unwind_arm64.c
The struct thread_core_local for each CPU is global, hence initialized
to zero when .bss is cleared. So before threads are initialized we have
a seemingly valid curr_thread value (0) when we should really have -1.
thread_get_id_may_fail() can return 0 although there is no current
thread.
Fix this by setting curr_thread to -1 earlier in the boot.
Note: this moves code out of thread_init_threads(), which is called by
virt_guest_created() when virtualization is enabled. I think it is the
right thing to do because I see no reason why the thread_core_local
structures should be cleared when a guest is added (the data belong to
.nex_bss).
=> core: initialize curr_thread to -1 + fix print_kernel_stack

core/arch/arm/include/kernel/thread.h, core/arch/arm/kernel/boot.c, core/arch/arm/kernel/thread.c, core/arch/arm/kernel/thread_optee_smc.c, core/kernel/initcall.c
There are a few places where the value of thread_core_local::flags
does not reflect the stack being used, i.e., the temporary stack is
used but THREAD_CLF_TMP is not set or the opposite. In such cases,
get_stack_limits() would return invalid values. The consequence is a
debugging issue: no stack dump on core panic or abort.
This was found with the help of compiler instrumentation
(-finstrument-functions).
=> core: add missing THREAD_CLF_TMP flag updates

core/crypto/sm3.c
Several crypto tests fail when OP-TEE is built with Clang in non-debug
mode, more precisely with -Os. xtest numbers 4001, 4002, 4006 and 4014
are impacted.
The root cause is the right and left shift operation in the ROTL(x, n)
macro. When n > 32, they are undefined because the values to shift are
uint32_t.
Fix the bug by introducing a new macro: ROTL2(x, n) which subtracts 32
from n when n >= 32. ROTL2() can therefore be used with 0 <= n <= 63.
=> core: crypto: fix invalid SM3 output with Clang -Os

ldelf/unwind_arm64.c
unwind_arm64() currently does not check the value of the frame pointer
after it has done its job unwinding one frame. A NULL value indicates
the end of the call stack, and therefore the function should return
false to stop the caller from unwinding further (a do .. while loop is
used in print_stack_arm64()). Instead invalid values for FP and PC are
returned which causes an erroneous display and the unwind stops one
step too late, when the FP is found to be outside the stack.
Fixes the invalid last line in call stacks such as xtest 1019:
```
E/TC:? 0 TA panicked with code 0x0
E/LD:  Status of TA 5b9e0e40-2636-11e1-ad9e-0002a5d5c51b
E/LD:   arch: aarch64
[...]
E/LD:  Call stack:
E/LD:   0x0000000080062a50
E/LD:   0x00000000801df848
E/LD:   0x00000000800631a8
E/LD:   0xfffffffffffffffc
``` …
=> ldelf: arm64: do not unwind past end of stack

scripts/symbolize.py
When processing the memory map of a TA, it can happen that the ELF file
for a region is not found. One typical reason is a missing -d argument
on the command line (can easily happen when a TA uses shared libraries
for instance).
In the above case, the script crashes with no clear indication about
the cause. This commit fixes the crash by ignoring ELFs that are not
found. This is consistent with the general behavior of symbolize.py,
which is to always print out all the information it is fed and simply
augment it with debug information when possible.
=> symbolize.py: ignore error if ELF file is not found

core/arch/arm/kernel/thread_a32.S, core/arch/arm/tee/arch_svc.c, ldelf/start_a32.S, ldelf/start_a64.S, ldelf/sys.c, ldelf/sys.h, ldelf/ta_elf.c, lib/libutee/abort.c, lib/libutee/arch/arm/utee_syscalls_a32.S, lib/libutee/arch/arm/utee_syscalls_a64.S, lib/libutee/arch/arm/utee_syscalls_asm.S, lib/libutee/assert.c, lib/libutee/base64.c, lib/libutee/base64.h, lib/libutee/include/utee_syscalls.h, lib/libutee/tee_api.c, lib/libutee/tee_api_arith_mpi.c, lib/libutee/tee_api_objects.c, lib/libutee/tee_api_operations.c, lib/libutee/tee_api_panic.c, lib/libutee/tee_api_property.c, lib/libutee/trace_ext.c, lib/libutils/ext/ftrace/ftrace.c, ta/arch/arm/user_ta_header.c
A couple of patches to `libutee` so that all internal symbols [1] begin with a leading underscore to avoid conflicts with application code.
[1] Internal symbols = those that are not part of the API exported by `libutee`
=> libutee: add leading underscores

core/arch/arm/plat-imx/conf.mk
The Webasto ccbv2 is a mx6ul based custom board with 256MB of RAM and
the communication done on UART7.
=> imx: add support for ccbv2

.checkpatch.conf
The Linux kernel has recently increased maximum line length to 100, but
still recommends to stay under 80. So make sure the checkpatch still warn
when exceeding 80.
=> checkpatch: limit maximum line length to 80

mk/lib.mk
The same Clang 10 fix in commit 4d35ab6a0cef ("TA dev kit: clang: link
shared libraries with -z separate-loadable-segments") is needed for
locally built libraries user space libraries when CFG_ULIBS_SHARED=y.
=> lib.mk: clang: link shared libraries with -z separate-loadable-segments

core/tee/tee_fs_rpc.c
The type of params[1] is changed to OUT to match the expected params in
tee-supplicant's tee_fs_rpc_readdir, so calls to tee_fs_rpc_readdir
won't fail with TEE_ERROR_BAD_PARAMETERS.
Signed-off-by: Roland Nagy <rnagy@xmimx.tk>
=> Bugfix in tee_fs_rpc_readdir

core/drivers/stm32_etzpc.c
Fix typo in function label: init_devive_from_hw_config() is renamed
init_device_from_hw_config().
Fix also a typo in source file inline comment.
=> stm32_etzpc: rename internal function init_device_from_hw_config()

core/arch/arm/plat-imx/drivers/imx_csu.c
io_write32() would replace the settings bits while writing the lock
bits, replace the setting of the lock bits with io_setbits32() to ensure
that the access bits won't be overwritten. The lock bit mask also
contained access value bits, remove those.
=> plat-imx: fix CSU SA settings for i.MX6UL

core/arch/arm/arm.mk, core/arch/arm/kernel/link.mk, core/sub.mk, mk/config.mk, mk/lib.mk, ta/arch/arm/link.mk, ta/arch/arm/link_shlib.mk, ta/ta.mk
Build systems that manage multiple different python interpreters need
explicit control over which version of the interpreter to use.
This patch enables one to override the default interpreter with the path
to a specific one.
Signed-off-by: Dick Olsson <hi@senzilla.io>
Reviewed-by: Jerome Forissier <jerome@forissier.org>
---
Revision 1:
* Updated the variable name to CFG_PYTHON3
* Clarified the comment in mk/config.mk
Revision 2:
* Fixed the formatting of the commit message
Revision 3:
* Renamed the variable from CFG_PYTHON3 to PYTHON3
* Exporting PYTHON3 to the TA dev kit
Revision 4:
* Added _nl_ to the TA dev kit exports
Revision 5:
* Expand the PYTHON3 variable export in the TA dev kit
* Removed spurious empty line
Revision 6:
* …
=> mk: core: ta: Configurable Python interpreter

core/tee/tee_ree_fs.c
When CFG_REE_FS and CFG_RPMB_FS are both 'y', the data stored by OP-TEE
in the REE filesystem (typically, under /data/tee) are protected by
hashes stored in the RPMB. Any modifications to the REE files via
external means are therefore detected and TEE_ERROR_SECURITY is
returned. However, no error or debug message is printed to the secure
console which makes troubleshooting more difficult than needed. This
commit adds an error message.
=> core: log error when secure storage corruption is detected

ta/ta.mk
This patch fixes the following error triggered by a heavily parallel build:
echo sm := ta_arm64 > .../export-ta_arm64/mk/conf.mk.tmp
/bin/bash: .../export-ta_arm64/mk/conf.mk.tmp: No such file or directory
Fixes: https://github.com/OP-TEE/optee_os/issues/3999
=> build: fix race when generating conf.mk

core/tee/tee_rpmb_fs.c
When CFG_TEE_CORE_LOG_LEVEL=4 and CFG_RPMB_FS=y, the TEE core crashes
with a dead stack canary message:
E/TC:0 0 Dead canary at end of 'stack_abt[3]'
E/TC:0 0 Panic at core/arch/arm/kernel/thread.c:192 <thread_check_canaries>
E/TC:0 0 TEE load address @ 0x1bd0f000
E/TC:0 0  0x1bd17b3d print_kernel_stack at optee_os/core/arch/arm/kernel/unwind_arm32.c:452
E/TC:0 0  0x1bd23a07 __do_panic at optee_os/core/kernel/panic.c:32 (discriminator 1)
E/TC:0 0  0x1bd120cb thread_check_canaries at optee_os/core/arch/arm/kernel/thread.c:188 (discriminator 2)
E/TC:0 0  0x1bd12c1f thread_state_suspend at optee_os/core/arch/arm/kernel/thread.c:754
E/TC:0 0  0x1bd14610 thread_rpc at optee_os/core/arch/arm/kernel/thread_optee_smc_a32.S:227
The issue happens to be with the debug function …
=> rmpb: fix infinite recursion in dump_fat() when CFG_TEE_CORE_LOG_LEVEL=4

lib/libutee/tee_api_operations.c
User can call TEE_AsymmetricSignDigest with a NULL signature and a valid
zero signatureLen in order to discover the size of the required
signature buffer (function should then return TEE_ERROR_SHORT_BUFFER and
update signatureLen with the required amount).
=> libutee: TEE_AsymmetricSignDigest support 0 signature len

ta/ta.mk
The value of CFG_TEE_TA_LOG_LEVEL used at optee_os build time is
exported to the TA dev kit ($O/export_ta_arm{32,64}/mk/conf.mk). The
purpose is to provide a default value to the TA build environment,
which can easily be changed from the command line ("make
CFG_TEE_TA_LOG_LEVEL=3" for example).
However the following TA Makefile won't behave as expected:
```
BINARY := <somme uuid>
CFG_TEE_TA_LOG_LEVEL := 3  # Ignored!
include $(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk
```
This commit changes := to ?= so that ta_dev_kit.mk won't override any
value that may have been set previously in the TA Makefile or the
environment.
=> ta: export CFG_TEE_TA_LOG_LEVEL with ?= not :=

ldelf/ta_elf_rel.c
Symbols defined in a linker script are assigned type STT_NOTYPE, but
the __resolve_sym() function in ldelf only supports STT_OBJECT and
STT_FUNCTION. As a result, it is impossible to resolve STT_NOTYPE
symbols at runtime. This causes an error in shared libraries when
ftrace is enabled:
```
$ make CFG_FTRACE_SUPPORT=y CFLAGS_ta_arm32=-pg run
$ xtest 1019
D/LD:  ldelf:134 Loading TA 5b9e0e40-2636-11e1-ad9e-0002a5d5c51b
E/LD:  __resolve_sym:61 Symbol type not supported
E/TC:? 0 init_with_ldelf:232 ldelf failed with res: 0xffff000a
* regression_1019 Test dynamically linked TA
regression_1000.c:1502: [...] TEEC_ERROR_NOT_SUPPORTED
```
This commit adds STT_NOTYPE to the supported types, handled the same way
as STT_OBJECT and STT_FUNCTION.
Fixes: 97c5ac19427b ("ldelf: check ranges in …
=> ldelf: __resolve_sym(): support STT_NOTYPE

.shippable.yml
Shippable has a maximum build time of 1 hour for Open Source projects.
It is usually sufficient since typical build time is currently around
35 minutes, thanks to caching (ccache). But it can happen that the code
is changed too much by a pull request in which case the cache is
ineffective and build time would exceed 1 hour. When a build times out,
the cache is NOT updated and there is no other choice than to manually
feed the cache with a partial build (by removing some steps in
.shippable.yml) so that the next build can be quicker, wait for the
build to succeed, then restore all the build steps. This is quite
impractical.
This commit replaces the Shippable built-in caching mechanism with our
own cache on a cloud server (currently a Digital Ocean [1] VM).
Automatic upload is triggered …
=> ci: shippable: use our own cache server

core/arch/arm/arm.mk, core/arch/arm/cpu/cortex-a15.mk, core/arch/arm/cpu/cortex-a5.mk, core/arch/arm/cpu/cortex-a7.mk, core/arch/arm/cpu/cortex-a9.mk, core/arch/arm/cpu/cortex-armv8-0.mk
These patches were required to get the latest tests compiled on ARM32, Cortex-A7 (i.MX6UL). Otherwise the tests will complain while linking the cxx object file with the c object file, due to the hard-float soft-float difference.
=> CXX Flags Hard Float Support

core/arch/arm/kernel/boot.c
Fix spelling mistake in the info message displayed on the console when
secondary CPUs are initialized.
=> core: init_secondary_helper(): fix spelling mistake

core/arch/arm/plat-vexpress/conf.mk
With be3bc461c686 ("ta: experimental C++ support") we have some C++
tests in the regression tests which depends on libraries in the
toolchain with hard float enabled. To be able to compile the regression
tests hard float cannot be disabled. Disabling hard float was our
original workaround for this erratum. Another way to avoid the erratum
is to disable strict alignment checks. So unless
CFG_SCTLR_ALIGNMENT_CHECK isn't explicitly set to 'y' force it to 'n'
instead.
Fixes: be3bc461c686 ("ta: experimental C++ support")
=> core: juno: update 808870 Unconditional VLDM workaround

core/arch/arm/kernel/rpc_io_i2c.c, core/arch/arm/kernel/sub.mk, core/include/kernel/rpc_io_i2c.h, core/include/optee_rpc_cmd.h
Gives OP-TEE access to the i2c buses initialized and controlled by the
REE kernel. This is done by memory mapping a buffer from the thread's
cache where the input or output data is transferred.
Using this mechanism, OP-TEE clients do not have to worry about REE
RUNTIME_PM features switching off clocks from the controllers or
collisions with other bus masters.
This driver assumes that the I2C chip is on a REE statically assigned
bus which value is known to OP-TEE (it will not query/probe the REE).
The slave address can be either seven or ten bits. When using a ten
bit address, the corresponding flag needs to be set in the command and
the REE adapter must support the requested addressing mode.
=> core: arm: rpc i2c trampoline driver

core/arch/arm/arm.mk
$(platform-cflags-optimization) and $(platform-cflags-debug-info) are
added to the TA C flags via ta_arm{32,64}-platform-cflags. Do the same
for C++ flags thanks to ta_arm{32,64}-platform-cxxflags.
Tested-by: Jerome Forissier <jerome@forissier.org> (QEMU)
Tested-by: Jerome Forissier <jerome@forissier.org> (QEMUv8)
=> Add optimization and debug flags to exported TA C++ flags

mk/subdir.mk
Adds proper handling of cxxflags-y, cxxflags-\<file name>-y,
cxxflags-remove-y, cxxflags-remove-\<file name>-y, cxxflags-lib-y in the
same way as for C flags.
Fixes: be3bc461c686 ("ta: experimental C++ support")
=> mk/subdir.mk: handle C++ flags related variables

core/arch/arm/kernel/boot.c
When OP-TEE is built with CFG_VIRTUALIZATION=y, it does not call
`thread_clr_boot_thread()` during boot because the threads are
allocated in "tee" memory area, which is not available when there is
no virtual guests.
So, in this case local core state is left in erroneous state, which
causes assertion violation in thread_alloc_and_run(), when guests
calls OP-TEE for the first time from boot core.
Fixes: b166fabf3e8c ("core: initialize thread_core_local::curr_thread to -1")
=> boot.c: clear current tread id during initialization

lib/libutils/ext/arch/arm/sub.mk
Fix a TA build issue found when CFG_UNWIND=n. This issue produces a
build error trace like the below:
.../toolchains/aarch32/bin/arm-linux-gnueabihf-ld.bfd: .../toolchains/aarch32/bin/../lib/gcc/arm-linux-gnueabihf/8.3.0/libgcc_eh.a(unwind-arm.o): in function `__aeabi_unwind_cpp_pr0':
/tmp/dgboter/bbs/rhev-vm8--rhe6x86_64/buildbot/rhe6x86_64--arm-linux-gnueabihf/build/src/gcc/libgcc/config/arm/unwind-arm.c:494: multiple definition of `__aeabi_unwind_cpp_pr0'; .../optee_os/out/arm/export-ta_arm32/lib/libutils.a(aeabi_unwind.o): .../optee_os/lib/libutils/ext/arch/arm/aeabi_unwind.c:9: first defined here
.../optee_os/out/arm/export-ta_arm32/mk/link.mk:109: recipe for target 'out/5b9e0e40-2636-11e1-ad9e-0002a5d5c51b.elf' failed
I don't understand why toolchain support for …
=> libutils: embed AEABI personality routines upon CFG_UNWIND

core/arch/arm/include/kernel/thread.h, core/arch/arm/kernel/rpc_io_i2c.c, core/arch/arm/kernel/thread.c, core/arch/arm/kernel/thread_private.h, core/tee/socket.c, core/tee/tadb.c, core/tee/tee_fs_rpc.c
Adds a user parameter to thread_rpc_shm_cache_alloc() to make sure that
different callers of thread_rpc_shm_cache_alloc() doesn't interfere with
each other. The FS allocation could perhaps be intertwined with I2C
allocations if crypto operations are done over I2C.
Fixes: 9bee8f2a5af7 ("core: add generic rpc shared memory buffer caching")
=> core: add user parameter thread_rpc_shm_cache_alloc()

core/arch/arm/mm/core_mmu.c
Fixes get_va_width() when CFG_LPAE_ADDR_SPACE_SIZE != (1ull << 32).
=> core: mmu: arm64: fix get_va_width()

core/kernel/tpm.c
TF-A Measured Boot driver expects a tpm_event_log node on the
DTB with the compatible field set to "arm,tpm_event_log", so
fix the match table entry for the TPM support to match the one
used by TF-A.
Signed-off-by: Javier Almansa Sobrino <javier.almansasobrino@arm.com>
=> core: Fix the entry on the match table for TPM support.

ldelf/sub.mk, ldelf/ta_elf_rel.c, ldelf/tlsdesc_rel_a64.S, lib/libutee/include/elf_common.h
When compiling the __thread test in optee_test (xtest 1029), GCC 8.3
emits R_AARCH64_TLS_TPREL relocations while GCC 6 and 7 generate
R_AARCH64_TLSDESC instead. The latter are quite easy to implement once
the former are done so add the required code to ldelf. This also
enables the C++ tests (xtest 1031) to pass with the older compilers.
Tested-by: Jerome Forissier <jerome@forissier.org> (QEMUv8, GCC 6.2/7.2)
=> ldelf: arm64: support R_AARCH64_TLSDESC relocations

core/arch/arm/tee/arch_svc.c
Tracing the log syscall is of very little value since it will generate
some output to the console anyways. Worse, it pollutes the TA output in
case of a panic or an abort. For example:
```
o regression_4005.1 AE case 0 algo 0x40000710 line 2819
F/TC:?? 0 trace_syscall:132 syscall #27 (syscall_cryp_obj_alloc)
F/TC:?? 0 trace_syscall:132 syscall #15 (syscall_cryp_state_alloc)
F/TC:?? 0 trace_syscall:132 syscall #27 (syscall_cryp_obj_alloc)
F/TC:?? 0 trace_syscall:132 syscall #24 (syscall_cryp_obj_get_info)
F/TC:?? 0 trace_syscall:132 syscall #30 (syscall_cryp_obj_populate)
F/TC:?? 0 trace_syscall:132 syscall #24 (syscall_cryp_obj_get_info)
F/TC:?? 0 trace_syscall:132 syscall #24 (syscall_cryp_obj_get_info)
F/TC:?? 0 trace_syscall:132 syscall #29 (syscall_cryp_obj_reset)
F/TC:?? 0 …
```
=> core: do not trace syscall_log()

.shippable.yml, core/arch/arm/plat-vexpress/conf.mk
Enables CFG_ARM64_core by default for PLATFORM=vexpress-qemu_v8a. This
platform is mostly used in full 64-bit mode, especially since until now
the build.git Makefiles do not support anything else [1].
Link: [1] https://github.com/OP-TEE/build/blob/3.10.0/qemu_v8.mk#L9
=> vexpress-qemu_v8a: set CFG_ARM64_core to 'y' by default

.shippable.yml, MAINTAINERS, core/arch/arm/kernel/boot.c, core/arch/arm/plat-ls/main.c, core/arch/arm/plat-rzn1/a7_plat_init.S, core/arch/arm/plat-rzn1/conf.mk, core/arch/arm/plat-rzn1/link.mk, core/arch/arm/plat-rzn1/main.c, core/arch/arm/plat-rzn1/platform_config.h, core/arch/arm/plat-rzn1/psci.c, core/arch/arm/plat-rzn1/rzn1_regauth.h, core/arch/arm/plat-rzn1/rzn1_tz.h, core/arch/arm/plat-rzn1/sm_platform_handler.c, core/arch/arm/plat-rzn1/sub.mk, core/drivers/ns16550.c, core/include/drivers/ns16550.h
Add support for RZ/N1 platform from Renasas:
- Cortex-A7 based dual core processor.
This platform supports TrustZone based IO register access control, so add corresponding OEM service based implementation.
For more information about this platform, refer [here](https://www.renesas.com/us/en/products/microcontrollers-microprocessors/rz/rzn/rzn1d.html).
=> Add support for Renesas RZ/N1 platform

core/arch/arm/mm/tee_mmu.c
The check, if a memory parameter is located in a region, fails
because of a typo in the comparison. The region size must be
added to the start address, not subtracted.
Fixes: 2667e1359e51 ("core: fix offset calculation in param_mem_to_user_va()")
Signed-off-by: Wolfgang Ocker <weo@reccoware.de>
=> core: mm: fix region lookup in param_mem_to_user_va()

core/arch/arm/mm/tee_mmu.c, core/include/mm/tee_mmu.h, core/pta/system.c
Add a parameter to the mapping function to specify the alignment needed for the requested mapping. This is useful for mapping a device like a nor flash, which needs the base address to be aligned at the flash device's sector size.
=> core: Add a parameter to vm_map_pad() to specify alignment requirement

core/arch/arm/kernel/thread.c, lib/libutils/ext/include/compiler.h
With compiler optimizer enable (-O2) compiler generate invalid code
for thread_get_id_may_fail(). The curr_thread read got re-order
after exceptions unmask.
code generated for thread_get_id_may_fail() when compile OPTEE with `-O2`
```
000000000e105728 <thread_get_id_may_fail>:
thread_get_id_may_fail():
/home/optee/qemu-optee/optee_os/core/arch/arm/kernel/thread.c:783
e105728:       a9be7bfd        stp     x29, x30, [sp, #-32]!
e10572c:       910003fd        mov     x29, sp
e105730:       f9000bf3        str     x19, [sp, #16]
read_daif():
/home/optee/qemu-optee/optee_os/core/arch/arm/include/arm64.h:313
e105734:       d53b4233        mrs     x19, daif
e105738:       d53b4220        mrs     x0, daif
thread_set_exceptions(): …
```
=> core: thread: add compiler barrier to thread_(un)mask_exceptions()

lib/libutee/trace_ext.c
When Optee OS is compiled with TRACE_LEVEL=0, Optee test fails to
compile properly:
arm-none-linux-gnueabihf-ld.bfd: libutils.a(fputs.o): in function 'fputs':
fputs.c:15: undefined reference to 'trace_ext_puts'
link.mk:109: recipe for target '5b9e0e40-2636-11e1-ad9e-0002a5d5c51b.elf' failed
=> libutils: Fix fputs() when TRACE_LEVEL=0

core/crypto/crypto.c, core/drivers/crypto/caam/acipher/caam_rsa.c, core/drivers/crypto/crypto_api/acipher/rsa.c, core/drivers/crypto/crypto_api/include/drvcrypt_acipher.h, core/include/crypto/crypto.h, core/lib/libtomcrypt/rsa.c, lib/libmbedtls/core/rsa.c
There was no function to proper free a rsa kepair from inside a PTA
or the core itself. Now there is crypto_acipher_free_rsa_keypair().
Signed-off-by: E. von Däniken elias.vondaeniken@bluewin.ch
=> crypto: add function to free rsa keypair

core/tee/tee_obj.c, core/tee/tee_svc_cryp.c, lib/libutee/tee_api_objects.c, lib/libutee/tee_api_operations.c
Tested with 721619e ("core: Parse all memory DT nodes")  reverted in order to boot on qemu.
=> Gp 1.1 small fixes

core/arch/arm/kernel/link.mk
The build date included in the version string depends on the current
locale (language), which is not very good. Force LANG=C so that english
abbreviations are used for the day and month.
=> core: use C locale when generating the build date

Makefile
The Makefile function $(wildcard ...) may return matching files in any
order. Therefore the "make" command is not guaranteed to always produce
the same sequence of commands when building the in-tree TAs. This could
be inconvenient when troubleshooting build errors in different
environments for instance.
In order to produce predictable builds, sort the in-tree TA makefiles in
lexical order.
=> Makefile: sort in-tree TAs in lexical order

core/tee/tee_rpmb_fs.c
Fix an assert in fat_entry_dir_update that always fires when updating
fat entries other than the first element in the cache.
Signed-off-by: Neil Shipp <neilsh@microsoft.com>
=> core: Bad assert in fat_entry_dir_update.

core/arch/arm/mm/core_mmu_lpae.c
Depending on the ASLR seed, the MMU code may run out of translation
tables and panic. For instance with seed = 0x71dfb000 in init_mem_map()
the following crash is reproducible:
D/TC:0   core_mmu_entry_to_finer_grained:761 xlat tables used 7 / 7
...
D/TC:0   tee_entry_exchange_capabilities:102 Dynamic shared memory is enabled
E/TC:0 0 Panic 'Failed to spread pgdir on small tables' at core/arch/arm/mm/core_mmu.c:1739 <core_mmu_map_pages>
E/TC:0 0 TEE load address @ 0x7fefb000
E/TC:0 0  0x000000007ff06688 print_kernel_stack at optee_os/core/arch/arm/kernel/unwind_arm64.c:79
E/TC:0 0  0x000000007ff13d24 __do_panic at optee_os/core/kernel/panic.c:24
E/TC:0 0  0x000000007ff083d8 core_mmu_map_pages at optee_os/core/arch/arm/mm/core_mmu.c:1719
E/TC:0 0  0x000000007ff0cf8c …
=> core: lpae: allocate one more translation table for ASLR

core/tee/tee_rpmb_fs.c
Ensure that fat_entry_dir_update can only update entries less than
the current cache size and not just the maximum size limit of the cache
which may not be fully allocated yet.
Signed-off-by: Neil Shipp <neilsh@microsoft.com>
=> core: Fix RPMB fat entry cache buffer overflow.

core/arch/arm/plat-stm32mp1/drivers/stm32mp1_rcc.c, core/arch/arm/plat-stm32mp1/drivers/stm32mp1_rcc.h, core/arch/arm/plat-stm32mp1/scmi_server.c, core/arch/arm/plat-stm32mp1/shared_resources.c, core/arch/arm/plat-stm32mp1/stm32_util.h, core/include/dt-bindings/reset/stm32mp1-resets.h
Adding the MCU hold boot management through a SCMI dedicated
reset domain. MCU hold boot controls the MCU reboot sequence together
with MCU reset controller already exposed to SCMI agent 0.
Signed-off-by: Lionel Debieve <lionel.debieve@st.com>
=> plat-stm32mp1: use SCMI reset to manage MCU hold boot

core/drivers/scmi-msg/common.h, core/drivers/scmi-msg/entry.c, core/drivers/scmi-msg/sub.mk, core/drivers/scmi-msg/voltage_domain.c, core/drivers/scmi-msg/voltage_domain.h, core/include/drivers/scmi-msg.h, core/include/drivers/scmi.h
SCMI Voltage Domain protocol in defined in the SCMI specification [1]
since its version 3. This protocol allows a SCMI server to expose
voltage regulator control services. The current specific (v3) defines
services to discover the exposed regulators, to enable/disable them
and to set/get the regulator voltage level.
The protocol driver is embedded upon configuration switch
CFG_SCMI_MSG_VOLTAGE_DOMAIN.
=> drivers: scmi-msg: add SCMI Voltage Domain protocol

core/arch/arm/include/mm/pgt_cache.h
xtest on QEMU shows allocation errors when CFG_ULIBS_SHARED=y:
```
...
o regression_1010.10 Invalid memory access 5 with 1024 bytes memref
regression_1000.c:500: [...] 0xffff000c = TEEC_ERROR_OUT_OF_MEMORY [...]
regression_1000.c:505: [...] 0xffff000c = TEEC_ERROR_OUT_OF_MEMORY [...]
regression_1010.10 FAILED
...
E/TC:? 0 alloc_pgt:147 5 page tables not available
E/TC:? 0 alloc_pgt:147 5 page tables not available
```
This configuration needs at least 5 page tables. Use 8 to avoid wasting
space.
=> core: non-lpae: increase PGT_CACHE_SIZE when CFG_NUM_THREADS=2

core/arch/arm/mm/core_mmu_v7.c
Commit 1579bdf39b3e ("core: lpae: allocate one more translation table
for ASLR") has fixed an issue with LPAE (QEMUv8), but a similar one
occurs with non-LPAE. More specifically, running xtest 1013 on QEMU
with CFG_ULIBS_SHARED=y:
```
E/TC:0 0 Panic 'Failed to spread pgdir on small tables' at core/arch/arm/mm/core_mmu.c:1737 <core_mmu_map_pages>
E/TC:0 0 TEE load address @ 0x5a9b5000
E/TC:0 0  0x5a9bcba1 print_kernel_stack at optee_os/core/arch/arm/kernel/unwind_arm32.c:109
E/TC:0 0  0x5a9c8293 __do_panic at optee_os/core/kernel/panic.c:31
E/TC:0 0  0x5a9bf357 core_mmu_map_pages at optee_os/core/arch/arm/mm/core_mmu.c:1737
E/TC:0 0  0x5a9c2a2f mobj_reg_shm_inc_map at optee_os/core/arch/arm/mm/mobj_dyn_shm.c:200
E/TC:0 0  0x5a9e9067 mobj_inc_map at …
```
=> core: non-lpae: allocate one more translation table for ASLR

lib/libutils/ext/arch/arm/mcount_a32.S
The __gnu_mcount_nc() function lacks proper annotation as registers are
pushed onto the stack. The unwind table information for this symbol is
therefore incorrect and stack unwinding may fail in spectacular ways.
For example, xtest 1007 enters an infinite loop as ldelf tries to unwind
the call stack when the TA panics:
```
(buildhost)$ make CFG_FTRACE_SUPPORT=y CFLAGS_ta_arm32=-pg run
(qemu)$ xtest 1007
...
E/TC:? 0 TA panicked with code 0xbeef
E/LD:  Status of TA 5b9e0e40-2636-11e1-ad9e-0002a5d5c51b
E/LD:   arch: arm
E/LD:  region  0: va 0x00102000 pa 0x0e300000 size 0x002000 flags rw-s (ldelf)
E/LD:  region  1: va 0x00104000 pa 0x0e302000 size 0x00c000 flags r-xs (ldelf)
E/LD:  region  2: va 0x00110000 pa 0x0e30e000 size 0x001000 flags rw-s (ldelf)
E/LD:  region  3: va 0x00111000 pa …
```
=> libutils: arm: add .cantunwind to __gnu_mcount_nc()

core/include/tee/tee_obj.h, core/tee/tee_obj.c, core/tee/tee_svc_cryp.c, core/tee/tee_svc_storage.c
Some function incorrectly use uint32_t for object identifiers:
tee_obj_get(), tee_svc_cryp_get_state() and tee_svc_storage_get_enum().
Those object IDs are actually virtual addresses so they need to be of
type vaddr_t.
Link: https://github.com/OP-TEE/optee_os/issues/4035#issuecomment-680037072
=> core: use vaddr_t instead of uint32_t for object IDs

core/arch/arm/kernel/secure_partition.c
The current Firmware Framework(FF-A) specification defines the major
version of 0x1 and minor version of 0x0. Return these values when
requested through the FFA_VERSION call instead of returning the
FFA_VERSION function id
Signed-off-by: Sughosh Ganu <sughosh.ganu@linaro.org>
=> core: ffa: Fix the ff-a version returned to Secure Partition

core/tee/tee_rpmb_fs.c
The max block index check in tee_rpmb_req_pack() is incorrect and would
fail when trying to access the last block of the partition.
=> core: rpmb: fix off-by-one in block index check

core/arch/arm/plat-zynqmp/conf.mk
Disable core ASLR for two reasons:
1. There is no source for ALSR seed, as ATF does not provide a
DTB to OP-TEE. Hardware RNG is also not currently supported.
2. OP-TEE does not boot with enabled CFG_CORE_ASLR.
Further investigation is needed to see why enabled ASLR causes
OP-TEE to not boot properly.
=> plat: zynqmp: force disable core ALSR

MAINTAINERS
Update MAINTAINERS with myself as reviewer for Xilinx Zynq
UltraScale+ MPSOC (plat-zynqmp).
=> MAINTAINERS: maintain plat-zynqmp

scripts/pem_to_pub_c.py, scripts/sign_encrypt.py
Current actual Python library for cryptography is being distributed in
two flavors: pycroptodome and pycroptodomex. They are basically the same
library, but with different import names:
- pycryptodome provides 'Crypto' module and indented to directly replace old
pycrypto library
- pycryptodomex provides 'Cryptodome' module and is intended for old
distributions, where pycrypto is still present
Most of the modern Linux distributions provide both of the libraries, so there
is no difference which one is to use. But some of them (like Yocto/Poky) provide
only one.
This patches makes scripts agnostic to a crypto library flavor being used by
trying to import Cryptodome first and then Crypto if first import fails.
=> scripts: support both pycryptodome and pycryptodomex

CHANGELOG.md
Update CHANGELOG for 3.11.0 and collect Tested-by tags.
=> Update CHANGELOG for 3.11.0

lib/libutils/ext/arch/arm/auxval.c, lib/libutils/ext/arch/arm/sub.mk, ta/arch/arm/link.mk, ta/mk/ta_dev_kit.mk
I stumbled on error
```
aarch64-linux-gnu-ld.bfd: /usr/lib/gcc/aarch64-linux-gnu/10.2.0/libgcc.a(lse-init.o): in function `init_have_lse_atomics':                                     
lse-init.c:(.text.startup+0xc): undefined reference to `__getauxval'  
```
when I tried to build optee_test (along with other OP-TEE components) with GCC 10.2.0.
While we already have `-mno-outline-atomics` option enabled for OP-TEE, it appears that `libgcc_eh` is built with `-moutline-atomics`, so linker fails when it tries to link C++ code in `os_test` TA. 
I see no other way than to provide empty `__getauxval()` function in `libutils`.
=> Fix 'undefined symbol __getauxval' while building xtest TAs

core/arch/arm/include/mm/core_mmu.h, core/arch/arm/kernel/boot.c, core/arch/arm/mm/core_mmu.c, core/arch/arm/mm/core_mmu_lpae.c
What do you think, does it make sense to deprecate `register_dynamic_shm()`?
We should not merge this until after the current release is done.
=> [rfc] core: deprecate register_dynamic_shm()

.travis.yml
The Travis CI script obtains checkpatch.pl from a mirror of the master
branch of the Linux repository. Unfortunately, kernel v5.9 has a buggy
checkpatch.pl [1]:
Global symbol "$gitroot" requires explicit package name [...]
The fix [2] is available in linux-next already but due to the Linux
release schedule it won't make it to the master branch until the end of
the v5.10-rc1 merge window, which is expected two weeks after the v5.9
release.
Downloading checkpatch.pl from linux-next seems to be a better idea in
general. Of course it might break more often due to the unstable nature
of linux-next, but on the other hand fixes appear much more quickly
than in master. A faster update time is even more beneficial in case
new features are added (such as the --kconfig-prefix option I submitted
some …
=> ci: travis: download checkpatch.pl from linux-next

mk/cc-option.mk
The purpose of the ld-option macro is to detect if the linker supports
a given command line option or not. It does so by invoking the linker
with the option and checking the exit status of the process. Some
options however may not cause an error but only generate a warning
message, and the linker exits with a success status. For example,
'-z unrecognized-option' does cause an error with Clang but triggers a
warning with GCC. As a result, $(call ld-option,-z unrecognized-option)
has a different behavior depending on the compiler.
Address this issue by loooking for the word 'warning' in the linker
output in addition to checking the exit status.
Fixes the following warning when building xtest shared libraries with
GCC:
path/to/bin/arm-linux-gnueabihf-ld.bfd: warning: -z …
=> build: ld-option: handle any linker warning as an error

.checkpatch.conf
A few days before v5.9-rc1, the checkpatch.pl script was modified in
the Linux kernel tree [1]. This caused spurious warnings in the OP-TEE
CI such as [2]:
WARNING: IS_ENABLED(CFG_VIRTUALIZATION) is normally used as IS_ENABLED(CONFIG_CFG_VIRTUALIZATION)
Fortunately, checkpatch now has an option to control the prefix used for
configuration variables [3]. Add this option to .checkpatch.conf.
Link: [1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=50161266973bcc662e969e63d68fc7bff71de21b
Link: [2] https://travis-ci.org/github/OP-TEE/optee_os/builds/717905104
Link: [3] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=3e89ad8506f39c4739a6c9ca1e1552f506f000c9
=> checkpatch: add --kconfig-prefix=CFG_

core/arch/arm/plat-imx/registers/imx6-crm.h, core/arch/arm/plat-imx/registers/imx6.h, core/arch/arm/plat-imx/registers/imx8m-crm.h, core/arch/arm/plat-imx/registers/imx8m.h, core/drivers/imx_i2c.c
Support native I2C access on imx6ull (this SoC has an additional
register to configure the daisy chain in the iomuxc).
Tested on imx6ull-evk 14x14 with the bus at 400Kbps.
A patch has been sent upstream to address the current configuration in U-Boot.
https://lists.denx.de/pipermail/u-boot/2020-October/430482.html
=> I2c imx6ull 

core/arch/arm/include/kernel/ldelf_loader.h, core/arch/arm/include/kernel/thread.h, core/arch/arm/include/kernel/user_ta.h, core/arch/arm/kernel/ldelf_loader.c, core/arch/arm/kernel/stmm_sp.c, core/arch/arm/kernel/sub.mk, core/arch/arm/kernel/thread.c, core/arch/arm/kernel/user_ta.c, core/arch/arm/tee/arch_svc.c, core/include/kernel/user_mode_ctx_struct.h, core/kernel/tee_ta_manager.c, core/pta/system.c
This is a step towards enabling Secure Partitions (SPs) in OP-TEE.
Ldelf should be used for both TAs and SPs, so ldelf related code is moved from user TA specific files to generic files.
~~The work is based on #4126 which is not merged yet, I've included those patches in this PR.~~ It has been merged.
=> Separate ldelf from user TAs

core/include/crypto/crypto.h, core/lib/libtomcrypt/rsa.c
Cherry-pick the libtomcrypt part of commit a1d5c81f8834 ("crypto: add
function to free rsa keypair") from optee_os master.
=> libtomcrypt: add function to free rsa keypair

core/include/crypto/crypto.h, lib/libmbedtls/core/rsa.c
Cherry-pick the libmbedtls part of commit a1d5c81f8834 ("crypto: add
function to free rsa keypair") from optee_os master.
=> libmbedtls: add function to free rsa keypair

core/include/kernel/tee_ta_manager.h, core/kernel/tee_ta_manager.c
Fix secure partition invocation in tee_ta_manager.c. The TA context
instance is found in the secure partition context (as here *_stmm_ctx()),
instead of the trusted service context as for regular TAs and PTAs.
This change moves to_ta_session() from header file to source file
so that is_stmm_ctx() is visible and can be asserted.
=> core: fix secure partition TA context

core/crypto/crypto.c, core/drivers/crypto/crypto_api/acipher/ecc.c, core/drivers/crypto/crypto_api/acipher/sub.mk, core/drivers/crypto/crypto_api/include/drvcrypt.h, core/drivers/crypto/crypto_api/include/drvcrypt_acipher.h, core/include/crypto/crypto.h, core/include/crypto/crypto_impl.h, core/lib/libtomcrypt/acipher_helpers.h, core/lib/libtomcrypt/ecc.c, core/lib/libtomcrypt/sm2-dsa.c, core/lib/libtomcrypt/sm2-pke.c, core/tee/tee_svc_cryp.c, lib/libmbedtls/core/ecc.c
In order to enable one ECC HW driver and one ECC SW library at build and runtime, introduces `struct crypto_ecc_public_ops` and `struct crypto_ecc_keypair_ops` respectively to the `struct ecc_public_key` and `struct ecc_keypair`.
At key (public/keypair) allocation, the HW driver is first called and if key type/size not supported, the SW library is then called.
When key is allocated with success, the key->ops is set with the cryptographic functions pointer to call when using keys to:
- Generate keypair
- Sign with keypair
- Shared secret with keypair
- Verify with public key
- Free public key
Modify the tomcrypt and mbedtls libraries to set the ECC keys operations reference function of the key type. 
This is the first phase to introduce the crypto driver API to connect a HW ECC driver in a …
=> Asym crypto/ecc keys ops

core/arch/arm/kernel/abort.c
Commit 02d307b7db90 ("core: use libunw") has involuntarily removed the
"TEE load address @ ..." message when a TEE core abort occurs. This
information is essential to be able to resolve function addresses when
ASLR is enabled, and scripts/symbolize.py needs this line. Add it back.
Fixes: 02d307b7db90 ("core: use libunw")
=> core: print "TEE load address" message on abort

core/lib/libtomcrypt/sm2-pke.c
Fix calloc() failure case in core crypto API function for SM2 PKE
decryption. Prior this change the function failed but return 0/OK.
This change sets the return value to TEE_ERROR_OUT_OF_MEMORY before
reaching the function exit sequence.
Fixes: f9a7828 (core: ltc: add support for SM2 PKE)
=> core: ltc: fix return value in crypto API SM2 PKA decrypt

core/arch/arm/plat-stm32mp1/scmi_server.c, core/arch/arm/plat-stm32mp1/stm32_util.h
This P-R is the companion of https://github.com/OP-TEE/optee_os/pull/4134 that introduced SCMI voltage domains.
This P-R allows STM32MP15 boards to expose some PMIC regulators to the non-secure world thorugh SCMI.
It also includes minor fixup commits to clean platform implementation in the SCMI service.
=> stm32mp1: PMIC regulators exposed thru SCMI and minor fixes

mk/cc-option.mk
Commit 5510db0b9458 ("build: ld-option: handle any linker warning as an
error") fixed an issue when used with the GNU linker, but while doing
so it broke the Clang use case. The problem is, the exit status tested
by `|| echo "Not supported"' is the one from grep, not the one from the
link command.
The fix provided here is tested with GCC (ld) and Clang (ld.lld).
=> build: fix ld-option again

ta/pkcs11/src/pkcs11_attributes.c
Fix return value when one-short processing is requested over an operation
that has already gone through a operation update processing. Prior this
change the PKCS11 TA return PKCS11_CKR_KEY_FUNCTION_NOT_PERMITTED which
is not accurate when key permits the operation but not the specification.
For clarity, this change splits one-shot and update steps case in
check_mechanism_against_processing().
Reported-by: Ruchika Gupta <ruchika.gupta@linaro.org>
=> ta: pkcs11: fix return code on one-shot process of an updated operation

core/arch/arm/include/kernel/stmm_sp.h, core/arch/arm/kernel/stmm_sp.c, core/arch/arm/kernel/thread_a32.S, core/arch/arm/kernel/thread_private.h
StMM is used with UEFI features. These few commits propose a 32bit port.
StMM build process is somewhat complex and currently built image have a bad entry code (1st instructions). An embedded hack computes a fixed value before StMM is entered when it boots up. This issue should be addressed in edk2 build, not is optee.
This RFC assumes the StMM SP is compiled for Thumb2 instruction set.
=> [RFC] 32bit support for StMM secure partition

core/sub.mk, mk/config.mk
Build process requires that private key is present when signing TAs.
In order to support external HSM based re-signing of the TAs, add support
to import different TA signing public key into TEE OS binary by
introducing TA_PUBLIC_KEY.
By default TA_PUBLIC_KEY gets the value of TA_SIGN_KEY.
=> core: Add support to import external TA signing public key

core/include/keep.h
The DECLARE_KEEP_PAGER() and DECLARE_KEEP_INIT() macros create symbols
in a special section called __keep_meta_vars_pager. The behavior
differs slightly in C and assembler:
- In C, the section is of type SHT_PROGBITS and has (SHF_ALLOC |
SHF_WRITE) flags,
- In assembler, the section is also SHT_PROGBITS but has no flags.
Enter the Clang linker, ld.lld. When used with --gc-sections, all
sections without the SHF_ALLOC flag (and a few other conditions) are
marked "live" in a first pass before dependencies on other sections
are considered. A side effect is that the reference to the symbol given
in DECLARE_KEEP_*() is ignored and the macro does not pull the desired
section in the link. That section is garbage collected instead.
Whether or not it is a bug in the linker is slightly above my …
=> core: keep.h: set SHF_ALLOC flag in all __keep_meta_vars_pager sections

core/arch/arm/kernel/link.mk
The path to kernel script is hard-coded. Despite it is in a arch specific folder, it should use defined variables.
This is helpful in case of porting OP-TEE OS to a new architecture such we make maximum reuse of existing sources.
=> core: kernel: link.mk: make path to kernel linker script generic

lib/libutee/errno.c
lib/libutee/errno.c is not built or used in any way so remove it.
=> Remove unused file lib/libutee/errno.c

core/drivers/pl022_spi.c, core/include/spi.h
We identified that the caller of the pl022 driver needs to flush the pl022's internal fifo to make sure next transaction starts clean.
This PR makes existing pl022_flushfifo function available to caller via spi_ops.
The validation is performed on bcm platform.
Signed-off-by: Vahid Dukandar <vahidd@microsoft.com>
=> spi: pl022_spi.c: fifo flush internal API made available to caller.

.shippable.yml, MAINTAINERS, core/arch/arm/kernel/link.mk, core/arch/arm/plat-rcar/link.mk, core/arch/arm/plat-rzg/conf.mk, core/arch/arm/plat-rzg/link.mk, core/arch/arm/plat-rzg/main.c, core/arch/arm/plat-rzg/platform_config.h, core/arch/arm/plat-rzg/sub.mk
This patch adds support for Renesas RZ/G2{HMNE} SoC's.
* Compiled with:
| make PLATFORM=rzg # Defaults to RZ/G2M SoC
Based on the work done from Huynh Thanh Hung for RZ/G2 internally and
similar work done for Renesas RCar-Gen3 SoC's in mainline OP-TEE OS.
Signed-off-by: Lad Prabhakar <prabhakar.mahadev-lad.rj@bp.renesas.com>
Reviewed-by: Biju Das <biju.das.jz@bp.renesas.com>
=> Initial support for Renesas RZ/G2{HMNE} SoC's

core/drivers/imx_i2c.c
Fix the build error triggered when enabling
-Werror=expansion-to-defined
=> drivers: imx_i2c: remove non-portable use of define

core/drivers/crypto/se050/crypto.mk
Some versions of the force function used in the makefile might produce
incorrect results when spaces are included in the parameter field.
In general is a better practice to strip spaces when invoking this
sort of functions.
To prevent issues (ie: in case of backport) make sure that the SE050
driver is not affected by that variability.
Issue: #4259
=> drivers: crypto: se050: strip spaces from crypto.mk

mk/checkconf.mk
The 'force' macro can cause unexpected errors in some cases where
the name of the configuration variable is preceded by a space:
'$(call force, CFG_FOO,foo)' instead of '$(call force,CFG_FOO,foo)'.
For example:
$ make PLATFORM=imx-mx8mmevk CFG_STACK_{TMP,THREAD}_EXTRA=8192 \
CFG_CRYPTO_DRV_ACIPHER=y CFG_NXP_SE05X=y CFG_NXP_CAAM=y
core/drivers/crypto/se050/crypto.mk:49: *** CFG_CRYPTO_DRV_ACIPHER is set to '' (from undefined) but its value must be 'y' [Mandated by CFG_NXP_SE05X_ACIPHER_DRV].  Stop.
Fixing the callers is certainly a good thing to do (if only for
consistency) but the current behavior is difficult to troubleshoot.
Therefore, make the 'force' macro more robust by stripping any space
around the variable name.
Reported-by: Jorge Ramirez-Ortiz <jorge@foundries.io>
Signed-off-by: …
=> build: make 'force' macro more robust

core/arch/arm/mm/tee_pager.c
Fix tee_pager_gpt_save_and_release_entries() to use to_user_mode_ctx()
to get current context user memory areas instead of to_user_ta_ctx()
since the former supports both SP and TA contexts.
Prior this change was pager asserting with an error trace like below:
E/TC:0 0 assertion 'is_user_ta_ctx(ctx)' failed at core/arch/arm/include/kernel/user_ta.h:56 <to_user_ta_ctx>
E/TC:0 0 Panic at core/kernel/assert.c:28 <_assert_break>
=> core: fix user mode context reference in pager

core/drivers/crypto/se050/core/huk.c
Guarantee the uniqueness of the die_id even when the requested length
is smaller than the se050 unique identifier.
Currently, tee_otp_get_die_id requests 12 bytes while the se050 unique
identifier is 18 bytes which is an issue as the uniqueness of the
device can be lost due to the truncation of the identifier.
=> drivers: crypto: se050: die_id generation

core/drivers/tzc380.c
Currently the region size is always decremented when finding a region. Instead reset to the biggest size to restart with another start address. Also fixes an unnecessary multiply/divide with the same `region_size`.
=> TZC380: Fix autoconfiguration for bigger DRAM sizes.

core/arch/arm/plat-rockchip/platform.c
The weak variant of platform_secure_ddr_region() only emits a message that the
target region won't get protected due to missing platform-code.
Depending on the log-level this can result in the function parameters not
getting used at all, so mark them as __maybe_unused.
Signed-off-by: Heiko Stuebner <heiko.stuebner@theobroma-systems.com>
=> plat-rockchip: mark parameters as __maybe_unused in platform_secure_ddr_region

lib/libutee/tee_api_arith_mpi.c
The TEE_BigIntInit() supplied length is the number of words allocated
for the bigint, including headers. Prior to this patch it seems it was
assumed that length was number of bits given the call to
TEE_BigIntSizeInU32(). With this patch correct this by removing the
TEE_BigIntSizeInU32() call.
Fixes: 062e3d01c039 ("ta: switch to to mbedtls for bignum")
=> libutee: fix TEE_BigIntInit() memset()

core/arch/arm/include/arm.h, core/arch/arm/include/kernel/delay.h, core/arch/arm/kernel/tee_time_arm_cntpct.c, core/kernel/tee_ta_manager.c, lib/libutee/include/arm_user_sysreg.h, lib/libutils/ext/ftrace/ftrace.c
Arm ARM quite clearly mentions that such reads must be preceded by an
ISB to forbid re-ordering.
Reported-by: Olivier Deprez <Olivier.Deprez@arm.com>
=> core: add isb() before reading CNTPCT/CNTVCT

mk/compile.mk
When building with bitbake with gitpkgv class git revision details have
'+' as delimeter.
Version details appears in path and this causes following warnings during
the OP-TEE OS build:
```
In file included from core/arch/arm/kernel/entry_a64.S:11:
/build/.../optee-os/devel+gitrAUTOINC+e97c83bd6f-r0/build.zcu102/core/include/generated/asm-defines.h:1:123: warning: extra tokens at end of #ifndef directive
1 | #ifndef _build_..._optee_os_devel+gitrAUTOINC+e97c83bd6f_r0_build_zcu102_core_include_generated_asm_defines_h
|                                  ^
/build/.../optee-os/devel+gitrAUTOINC+e97c83bd6f-r0/build.zcu102/core/include/generated/asm-defines.h:2:9: warning: missing whitespace after the macro name
2 | #define _build_..._optee_os_devel+gitrAUTOINC+e97c83bd6f_r0_build_zcu102_core_incl …
```
=> mk/compile.mk: Fix handling of '+' in path for generated include guards

core/drivers/crypto/se050/adaptors/apis/apdu.c, core/drivers/crypto/se050/adaptors/include/se050_apdu_apis.h, core/drivers/crypto/se050/adaptors/include/se050_utils.h, core/drivers/crypto/se050/adaptors/utils/utils.c, core/drivers/crypto/se050/core/ecc.c, core/drivers/crypto/se050/core/sub.mk, core/drivers/crypto/se050/crypto.mk
The following commits enable OP-TEE to use ecc on the SE050 I2C device.
=> drivers: crypto: se050: add support for elliptic curve cryptography

core/arch/arm/plat-vexpress/platform_config.h
Configures GIC and enable reception of interrupts from the secure uart.
=> qemu_v8: configure secure interrupts

core/arch/arm/plat-imx/link.mk, core/arch/arm/plat-rzn1/link.mk
Since commit 5ae0290f7f3b ("core: kernel: link.mk: Move rules to generate
tee-raw.bin and tee.srec from rcar platform"), the recipe to produce
tee-raw.bin is in the common makefile core/arch/arm/kernel/link.mk.
Therefore the recipes in core/arch/arm/plat-imx/link.mk and
core/arch/arm/plat-rzn1/link.mk are redundant and need to be removed.
Fixes the following build warning:
$ make -s PLATFORM=imx-mx6ullevk
core/arch/arm/plat-imx/link.mk:7: warning: overriding recipe for target 'out/arm-plat-imx/core/tee-raw.bin'
core/arch/arm/kernel/link.mk:230: warning: ignoring old recipe for target 'out/arm-plat-imx/core/tee-raw.bin'
=> plat-imx, plat-rzn1: remove redundant recipes to generate tee-raw.bin

core/arch/arm/plat-imx/drivers/imx_snvs.c
The i.MX6SDL/SLL SoCs do not expose the security configuration in the
HPSR registers, however the SSM state machine information is still
exposed. Remove the check for the security configuration, since the bits
all read zero on these SoCs, even if they are securely booted.
I hope I got all the SoCs now, I looked at the reference manual and removed SDL ~and SLL~ since for those, bits 12-14 are marked as reserved.
CC @clementfaure
=> core: imx: remove security check for i.MX6SDL

.shippable.yml
Since commit 87372da451d4 ("Enable ASLR by default"), most platforms
have ASLR turned on and do not need to explicitly set CFG_CORE_ASLR=y
at build time. Remove the redundant settings in .shippable.yml.
=> shippable: remove useless CFG_CORE_ASLR=y for QEMU

core/tee/tee_rpmb_fs.c
When decrypt_block fails (although unlikely) it shouldn't be silently ignored.
In such case the data in the buffer pointed to by *out is unmodified or bogus
while the return code is TEE_SUCCESS.
Signed-off-by: Robin van der Gracht <robin@protonic.nl>
=> core: tee_rpmb_fs: Return error when block decryption fails

ta/pkcs11/src/persistent_token.c
See issue #4303.
I added a patch that renames a sizeof() call's argument for consistency.
=> PKCS#11 Fix persistent db panic when empty

mk/config.mk, ta/pkcs11/include/pkcs11_ta.h, ta/pkcs11/src/persistent_token.c, ta/pkcs11/src/pkcs11_token.c, ta/pkcs11/src/pkcs11_token.h
In C_InitToken() if PIN is NULL_PTR then it will activate TEE Identity
based authentication support for token.
Once activated:
- When ever PIN is required client's TEE Identity will be used for authentication
- PIN failure counters are disabled
- If new PIN is given as input it is in form of PIN ACL string
- It can be disabled with C_InitToken with non-zero PIN
Internally protected authentication path will be used for mode determination.
Implements:
https://github.com/OP-TEE/optee_os/issues/3946
Testing this without having other PKCS11 features like RSA, EC, objects lists and so needs a bit imagination how it would eventually work but I add comments what happens in the test sequence.
Actual functionality has also been verified with "full blown" features in real hardware with NXP CPU. …
=> pkcs11: Add TEE Identity based authentication support

ta/pkcs11/src/object.c, ta/pkcs11/src/object.h, ta/pkcs11/src/pkcs11_token.c
When re-initializing a token the previously created objects need
to be removed.
Signed-off-by: Robin van der Gracht <robin@protonic.nl>
=> ta: pkcs11: Remove persistent objects on token re-initialization

core/kernel/tee_ta_manager.c
Commit 00b3b9a25e76 ("core: add generic struct ts_session") has
introduced a regression in the ftrace code by introducing a call to
ts_get_current_session() in ftrace_update_times() in replacement of
tee_ta_get_current_session(). At this point it can happen that no
current session exists, in which case the function should simply return.
Unfortunately ts_get_current_session() will call panic() is such a
situation. The proper function is ts_get_current_session_may_fail().
Fixes: 00b3b9a25e76 ("core: add generic struct ts_session")
Fixes: https://github.com/OP-TEE/optee_os/issues/4313
=> ftrace: fix regression causing panic in ftrace_update_times()

lib/libutee/arch/arm/user_ta_entry.c
The code that is supposed to invoke the finalization functions in the
DT_FINI_ARRAY of a TA is broken. It mixes DT_INIT_ARRAY with
DT_FINI_ARRAYSZ. As a result, the finalization functions are never
called and the TA may even crash on exit.
Fix the issue by replacing the erroneous DT_INIT_ARRAY with
DT_FINI_ARRAY.
Fixes: dd655cb9906c ("ldelf, ta: add support for DT_INIT_ARRAY and DT_FINI_ARRAY")
Reported-by: JY Ho <JY.Ho@mediatek.com>
=> ta: fix processing of DT_FINI_ARRAY

core/tee/tee_svc_storage.c
Prior to this patch was syscall_storage_next_enum() opening a file
handle with tee_svc_storage_read_head() but never freeing the handle.
Fix this by closing the file handle as part of cleaning up before
returning.
Fixes: 928efd065222 ("core: syscall_storage_next_enum() use live pobj")
=> core: fix file handle leakage in syscall_storage_next_enum()

core/tee/tee_rpmb_fs.c
update_write_helper() is clearing uninitialized parts of blk_buf.
There's an error in the logic calculating how much should be cleared
resulting in a negative size being supplied to memset(). Fix this by
always clearing blk_buf before usage.
Fixes: cd799689cd3d ("core: rpmb: fix initialization of new rpmb data")
=> core: fix bad memset() in update_write_helper()

core/drivers/imx_wdog.c
Instead of searching the node by hard-coded paths, search the node by
the compatible, which should be more robust against upstream device tree
changes. Upstream recently changed the naming of "aips-bus" to "bus",
breaking the OP-TEE i.MX Watchdog driver in the process, since the path
can no longer be found within the tree.
Opening as draft since I do not have testing hardware on hand at the moment, I would nevertheless appreciate some review.
cc @clementfaure @MrVan @cneveux @sdininno
=> driver: imx_wdog: search node by compatible

ta/arch/arm/link.mk
Global data defined in user_ta_header.c need to be made visible to
shared libraries because they may be referenced by them. For example,
trace_level is ultimately referenced by the trace macros (IMSG() and
similar). Therefore, when IMSG() is called in a shared library, the
dynamic loader (ldelf) needs to locate the trace_level symbol in the
TA. But since a TA is a "main executable" and not a shared library,
the linker by default will not add all global symbols to the dynamic
symbol table (.dynsym section). Instead those symbols are put in the
static symbol table (.symtab) which is typically not used at run time
and discarded when executables are stripped. In any case, ldelf only
uses the dynamic symbol table.
Add trace_ext_prefix and trace_level to the list of exported symbols to
fix the …
=> ta: link.mk: export trace_ext_prefix and trace_level

core/arch/arm/plat-imx/drivers/imx_snvs.c
Recent commit cfff3778 ("core: imx: remove security check for i.MX6SDL")
fixed an issue where i.MX6SDL SoC does not expose the security
configuration in the HPSR registers correctly.
This issue also affects i.MX6DQ. Let's add a check for this SoC
family in the same place.
Signed-off-by: Michael Scott <mike@foundries.io>
=> core: imx: remove security check for i.MX6DQ

ta/pkcs11/src/attributes.c, ta/pkcs11/src/object.c, ta/pkcs11/src/persistent_token.c, ta/pkcs11/src/pkcs11_token.h
Persistent object attributes are now loaded during the first find
operation. This means that you're forced to do a find operation to make
the objects attributes available.
Right now entry_find_objects_init is broken in such that it tries to
access the obj->attributes for objects in the session->token->object_list
before setting the obj->attributes (by calling token_obj_matches_ref).
This results in a Panic.
This patch fixes both issues.
Signed-off-by: Robin van der Gracht <robin@protonic.nl>
=> ta: pkcs11: Load persistent object attributes during db initialization

CHANGELOG.md, mk/config.mk
Update CHANGELOG for 3.12.0 and collect Tested-by tags for the next release.
=> Update CHANGELOG for 3.12.0

core/include/kernel/rpc_io_i2c.h, core/include/optee_rpc_cmd.h
Make the I2C defines consistent with the rest of the defines in
optee_rpc_cmd.h.
=> core: optee_rpc_cmd.h: shorten some I2C defines

core/arch/arm/include/kernel/boot.h, core/arch/arm/kernel/asm-defines.c, core/arch/arm/kernel/boot.c, core/arch/arm/kernel/entry_a32.S, core/arch/arm/kernel/entry_a64.S, core/arch/arm/kernel/link_dummies_init.c, core/arch/arm/kernel/link_dummies_paged.c
Splits boot_init_primary() into boot_init_primary_early() and
boot_init_primary_late(). The thread#0 stack pointer is assigned as
stack pointer before boot_init_primary_late() is called. This allows
functions registered to be called by call_finalcalls() to depend on the
full thread stack being available.
=> core: split boot_init_primary()

lib/libutils/ext/sub.mk, lib/libutils/isoc/sub.mk
The path to platform specifc code is hard-coded. This commit
changes it to use defined variable. This is helpful in case
of porting OP-TEE OS to a new architecture such we make
maximum reuse of existing sources.
=> lib: libutils: ext/isoc: sub.mk: make sources path platform generic

ta/pkcs11/src/pkcs11_token.c
When traversing object list to remove objects, use LIST_FOREACH_SAFE
to avoid segmentation fault.
=> ta/pkcs11: Use LIST_FOREACH_SAFE when removing objects from list

core/include/optee_rpc_cmd.h, core/include/tee/tee_supp_plugin_rpc.h, core/pta/system.c, core/tee/sub.mk, core/tee/tee_supp_plugin_rpc.c, lib/libutee/include/pta_system.h, lib/libutee/include/tee_internal_api_extensions.h, lib/libutee/tee_system_pta.c
Any external TEE services can be designed as a tee-supplicant plugin.
The plugins will be loaded by the supplicant during startup process
using libdl.
It makes it easy to:
- add new features in the supplicant that aren't needed in upstream,
e.g. Rich OS specific services;
- sync upstream version with own fork;
These patches add a new RPC - 'OPTEE_RPC_CMD_PLUGIN' as an unified
interface between OP-TEE and any plugins and a new PTA as an unified
interface between any user's TAs and any plugins.
Kernel code can use RPC directly to call for execution of some command in plugins.
TAs can use the plugin-pta.
Every plugin has own name based on UUID.
OP-TEE has access to plugins by it.
See definition of protocol for the command 'OPTEE_RPC_CMD_PLUGIN'
in 'core/include/optee_rpc_cmd.h' file. …
=>  core: add new PRC and PTA for loadable plugins framework

core/arch/arm/kernel/thread_a32.S
Prior to this patch with CFG_WITH_PAGER=y, CFG_WITH_LPAE=y and
CFG_CORE_UNMAP_CORE_AT_EL0=n icache_inv_user_range() crashes with a
prefetch abort due to TTBR0 being configured with an invalid value.
This happens due to an error in the ifdef logic using an uninitialized
register.
Fix this by using the correct register.
Fixes: c4a57390edef ("core: pager: use icache_inv_user_range()")
=> core: fix icache_inv_user_range()

.shippable.yml, MAINTAINERS, core/arch/arm/dts/fsl-lx2160a-qds.dts, core/arch/arm/dts/fsl-lx2160a-rdb.dts, core/arch/arm/dts/fsl-lx2160a.dtsi, core/arch/arm/plat-ls/conf.mk, core/arch/arm/plat-ls/main.c, core/arch/arm/plat-ls/platform_config.h
This pull request is taking care of following things:
1. Remove UART console initialization for PL011 specific platforms, because that is also done in ATF.
2. Enable dynamic shared memory for LX2160A-RDB & LX2160A-QDS
3. Add the dts files for LX2160A-QDS and LX2160A-RDB and enable EMBED DTB option for these platforms by default.
4. Remove GIC initialization for platforms with ATF as bootloader, because GIC is initialized by ATF in that case.
5. Add support for new platforms LX2160A-QDS.
6. Getting GIC base address from Embedded DTB for LX2160A-QDS and LX2160A-RDB
=> Multiple changes for Layerscape platforms (LX2160A-RDB and LX2160A-QDS)

core/arch/arm/include/mm/core_mmu.h, core/arch/arm/mm/core_mmu.c
Removes the deprecated and unused function core_tlb_maintenance().
=> core: remove deprecated core_tlb_maintenance()

core/drivers/crypto/se050/adaptors/apis/sss.c, core/drivers/crypto/se050/adaptors/include/se050_utils.h, core/drivers/crypto/se050/adaptors/utils/scp_config.c, core/drivers/crypto/se050/session.c, core/include/kernel/huk_subkey.h
Remove the need to store the SCP03 keys by deriving them from the HUK
and the SE050 unique hardware identifier.
Works under the assumption that the HUK is unknown and never exposed
outside the TEE.
CFG_CORE_SE05X_SCP03_PROVISION
Needs to be configured to exec the feature.
CFG_CORE_SE05X_DISPLAY_SCP03_KEYS:
Outputs the current and the new SCP03 keys to the console during
provisioning.
Note that to provision new SCP03 keys, SCP03 must already be in
operation (ie, have an encrypted communication channel between the
processor and the SE050).
U-boot support has just been posted to the list
https://lists.denx.de/pipermail/u-boot/2021-February/440455.html
=> drivers: crypto: se050: Global Platform SCP03 key provisioning

core/arch/arm/include/mm/core_mmu.h, core/arch/arm/mm/core_mmu.c
Clarifies tlbi_mva_range() with a full description of the interface at
the declaration of the function. The supplied VA range must be aligned
on the supplied granularity.
The implementation is updated to take full advantage of this restriction
together with an additional assert.
=> core: clarify tlbi_mva_range()

ta/pkcs11/include/pkcs11_ta.h, ta/pkcs11/src/attributes.c, ta/pkcs11/src/attributes.h, ta/pkcs11/src/entry.c, ta/pkcs11/src/object.c, ta/pkcs11/src/object.h, ta/pkcs11/src/pkcs11_attributes.c, ta/pkcs11/src/pkcs11_attributes.h, ta/pkcs11/src/pkcs11_helpers.c
Implement commands
- PKCS11_CMD_SET_ATTRIBUTE_VALUE
- PKCS11_CMD_COPY_OBJECT
optee_client :
https://github.com/OP-TEE/optee_client/pull/251
For testing I have currently used google pkcs11test and softhsm unit tests.
I will also be submitting tests to optee_test repo.
=> ta: pkcs11: Add support for modifying and copying objects

ta/pkcs11/src/pkcs11_token.c
Correct token reference pass to verify client credentials.
Fixes: 1a27b197 ("ta: pkcs11: Add TEE Identity based authentication support")
=> ta: pkcs11: fix TEE identity authentication token reference

core/arch/arm/kernel/virtualization.c
It is possible that get_ta_ram_size() would return size which is not
aligned to a small page size. This will cause panic in core_init_mmu_prtn()
function.
To fix this we need to round down calculated value to a page size.
=> virt: round down TA RAM memory size to page size

core/arch/arm/include/mm/mobj.h
Provide a function definition when CFG_CORE_DYN_SHM is not configured.
=> core: mobj: fixup undefined mobj_mapped_shm_alloc

ta/pkcs11/include/pkcs11_ta.h, ta/pkcs11/src/entry.c, ta/pkcs11/src/pkcs11_helpers.c, ta/pkcs11/src/pkcs11_token.c, ta/pkcs11/src/pkcs11_token.h
Add code for handling C_SeedRandom() and C_GenerateRandom() functionality.
Relates to:
https://github.com/OP-TEE/optee_os/issues/4283
Goes with:
https://github.com/OP-TEE/optee_client/pull/256
https://github.com/OP-TEE/optee_test/pull/487
=> ta: pkcs11: Add implementation for random number generation

core/arch/arm/kernel/sub.mk, mk/compile.mk
The header file <generated/asm-defines.h> is created at build time. It
contains macro definitions for various offsets in C structures and is
especially useful for use from assembler code. It is generated from
asm-defines.c, which includes a number of header files, of which two
are also generated at build time: <generated/arm32_sysreg.h> and
<generated/arm32_gicv3_sysreg.h>.
These dependencies are expressed nowhere in the makefiles and therefore
build errors can result. For example:
$ make out/arm-plat-vexpress/core/include/generated/.asm-defines.s
UPD     out/arm-plat-vexpress/conf.mk
UPD     out/arm-plat-vexpress/include/generated/conf.h
CC …
=> build: core: add missing dependencies when generating assembly constants

ta/pkcs11/src/object.c
When creating a object file handle was left open. This was observed in
tee-supplicant as open file handles.
This fixes the situation so that file handles are not left open.
To demonstrate the problem:
Without the fix:
```sh
$ lsof | grep tee-supplicant
279	/usr/sbin/tee-supplicant	/dev/null
279	/usr/sbin/tee-supplicant	socket:[7445]
279	/usr/sbin/tee-supplicant	socket:[7445]
279	/usr/sbin/tee-supplicant	/dev/teepriv0
$ pkcs11-tool --module /usr/lib/libckteec.so.0 --slot-index 1 --init-token --label pkcs11test --so-pin 5678567856
$ pkcs11-tool --module /usr/lib/libckteec.so.0 --slot-index 1 --init-pin --login --so-pin 5678567856 --new-pin 1234123412
$ lsof | grep tee-supplicant
279	/usr/sbin/tee-supplicant	/dev/null
279	/usr/sbin/tee-supplicant	socket:[7445]
279	/usr/sbin/tee-supplicant …
```
=> ta: pkcs11: Close file handle after object has been created

MAINTAINERS, core/arch/arm/plat-ls/conf.mk, core/drivers/ls_i2c.c, core/drivers/sub.mk, core/include/drivers/ls_i2c.h
This patch add 2 things:
1. Add I2C driver for NXP Platform.
2. Add I2C test code for reading time from RTC connected on I2C5
in LX2160A-RDB
I2C Driver compilation is enabled by default for LX2160A-RDB
& LX2160A-QDS.
If you need to test this driver you can use the I2C test code,
which reads the time from RTC.
For that you need to set CFG_NXP_I2C_TEST=y during compilation.
When CFG_NXP_I2C_TEST=y, For LX2160A-RDB, RTC is connected to I2C5,
We will pass CFG_NXP_I2C_CONTROLLER = 4.
=> plat-ls: add i2c driver for NXP LS Platforms

ta/pkcs11/src/pkcs11_attributes.c
Even thou normal operations should mark private key a private with
CKA_PRIVATE attribute it is possible that someone could do
unexpected choise.
Specification does not state that private key class itself means that it
is private, specification only states that CKA_PRIVATE is in control of
the privacy of the object.
This commit moves object class CKO_PRIVATE_KEY processing to normal
handling of CKA_PRIVATE.
CKA_PRIVATE is specified in:
PKCS #11 Cryptographic Token Interface Base Specification Version 2.40
Plus Errata 01
4.4 Storage Objects
Possibility of having private key object with CKA_PRIVATE as false:
PKCS #11 Cryptographic Token Interface Base Specification Version 2.40
Plus Errata 01
4.9 Private key objects
=> ta: pkcs11: private key can also be public

core/arch/arm/mm/mobj_dyn_shm.c
dynamic shared memory is not being released leading to an out of
memory condition.
Issue triggered by exporting the cryptographic random generator to the
REE (Linux) and then loop reading the value via the device interface
(cat /dev/random). This test case generates a couple of 4K allocations
every ~200ms on imx8mm with one of them always leaking.
=> core: mobj: fix memory leak

.azure-pipelines.yml
The Shippable Continuous Integration service is scheduled for retirement
on May 3rd, 2021 [1]. Therefore, a replacement has to be found.
This commit introduces .azure-pipelines.yml which serves the same
purpose as .shippable.yml but runs on the Microsoft Azure Pipelines
infrastructure [2].
Link: [1] https://blog.shippable.com/the-next-step-in-the-evolution-of-shippable-jfrog-pipelines
Link: [2] https://azure.microsoft.com/en-us/services/devops/pipelines/
=> ci: add .azure-pipelines.yml

ta/pkcs11/include/pkcs11_ta.h, ta/pkcs11/src/entry.c, ta/pkcs11/src/pkcs11_attributes.c, ta/pkcs11/src/pkcs11_helpers.c, ta/pkcs11/src/processing.c, ta/pkcs11/src/processing.h, ta/pkcs11/src/processing_symm.c
Other PR's related to this :
optee_client - https://github.com/OP-TEE/optee_client/pull/257
optee_test - https://github.com/OP-TEE/optee_test/pull/490
DERIVE_TEMPLATE has not been used in the implementation right now. The specification (even v3.0) doesn't mention clearly about it. The plan is to work on C_Wrap/UnWrap API's next and then revisit the DERIVE_TEMPLATE usage.
=> pkcs11: Add implementation for C_DeriveKey()

MAINTAINERS, core/arch/arm/plat-hikey/spi_test.c, core/arch/arm/plat-ls/conf.mk, core/drivers/bcm_gpio.c, core/drivers/ls_gpio.c, core/drivers/pl022_spi.c, core/drivers/pl061_gpio.c, core/drivers/sub.mk, core/include/drivers/ls_gpio.h, core/include/gpio.h, core/pta/bcm/gpio.c
This pull request does 2 things:
1. Add 'struct gpio_chip *chip' in 'struct gpio_ops' and updated bcm_gpio and pl061_gpio as per modified gpio.h definition.
Based on https://github.com/OP-TEE/optee_os/issues/4007 discussion.
2. Add GPIO driver for NXP LS Platforms
=> Update struct gpio_ops and Add GPIO driver for NXP LS Platforms

ta/pkcs11/src/object.c, ta/pkcs11/src/persistent_token.c, ta/pkcs11/src/pkcs11_token.h
For token objects, for any modification in attributes,
the attributes also need to be updated in the objects
persistent storage. These modifications are done when
C_SetAttributeValue() is used.
=> ta: pkcs11: Update attributes in persistent storage for C_SetAttributeValue()

core/arch/arm/include/ffa.h, core/arch/arm/include/kernel/abort.h, core/arch/arm/include/kernel/secure_partition.h, core/arch/arm/include/kernel/spmc_sp_handler.h, core/arch/arm/include/kernel/thread.h, core/arch/arm/include/kernel/thread_spmc.h, core/arch/arm/kernel/abort.c, core/arch/arm/kernel/ldelf_loader.c, core/arch/arm/kernel/secure_partition.c, core/arch/arm/kernel/spmc_sp_handler.c, core/arch/arm/kernel/stmm_sp.c, core/arch/arm/kernel/sub.mk, core/arch/arm/kernel/thread.c, core/arch/arm/kernel/thread_private.h, core/arch/arm/kernel/thread_spmc.c, core/arch/arm/kernel/thread_spmc_a64.S, core/arch/arm/kernel/user_ta.c, core/include/kernel/user_mode_ctx.h, core/kernel/ldelf_syscalls.c, core/kernel/user_access.c, ldelf/main.c
Secure Partitions (SP) are S-EL0 execution service defined in the Arm FF-A specification. This PR adds the following features for SPs:
-Load Secure Partitions at boot.
-Run every Secure Partition after it has been loaded
-Accept FFA_MSG_SEND_DIRECT_REQ_32 and FFA_MSG_SEND_DIRECT_RESP_32 messages from and to SPs.
I will update the documentation as soon as possible to give some extra details about the implementation.
This PR is a continuation of https://github.com/OP-TEE/optee_os/pull/4322. The PR got a bit big.
=> Add Secure partitions (continuation)

ta/pkcs11/src/object.c, ta/pkcs11/src/object.h, ta/pkcs11/src/persistent_token.c, ta/pkcs11/src/pkcs11_token.c, ta/pkcs11/src/pkcs11_token.h
PKCS11 has concept of shared objects between different PKCS11 sessions
which need to work.
As in OP-TEE context there can be multiple callers which should not share
the objects use OP-TEE client session association to separate those from
each other.
Specified in:
PKCS #11 Cryptographic Token Interface Usage Guide Version 2.40
2.6 Sessions
=> ta: pkcs11: relocate shared session object db to client session

MAINTAINERS, core/arch/arm/plat-ls/conf.mk, core/drivers/ls_dspi.c, core/drivers/sub.mk, core/include/drivers/ls_dspi.h
This patch adds DSPI driver for Layerscape Platforms.
DSPI compilation is enabled by default for LX2160A-QDS and LX2160A-RDB.
Signed-off-by: Carl Lamb <calamb@microsoft.com>
Signed-off-by: Manish Tomar <manish.tomar@nxp.com>
=> plat-ls: Add DSPI driver for NXP LS Platforms

lib/libutee/tee_api_objects.c
Checks that all the function parameters which are annotated in the
specification [1] are compliant with regards to memory access and memory
location. In case the check fails the TA panics to help debugging. The
more precise and expensive checks can be disabled with
CFG_TA_STRICT_ANNOTATION_CHECKS=n.
TEE_Realloc(), TEE_MemMove(), TEE_MemCompare(), TEE_MemFill() are
skipped for performance reasons. The TA will instead die with a fatal
exception if buffers supplied to these functions do not follow the
annotation rules.
[1]: GlobalPlatform TEE Internal Core API Specification v1.1
Signed-off-by: Stefan Schmidt <snst@meek.de>
=> GP 1.1: Check parameters annotated in the specification

ta/pkcs11/src/processing.c
check_parent_attrs_against_processing() checks if the right attributes
are set in the key to be used for a cryptgraphic purpose. It returns
error - CKR_KEY_FUNCTION_NOT_PERMITTED if this is not the case.
For C_DeriveKey(), C_UnwrapKey(), CKR_KEY_FUNCTION_NOT_PERMITTED is not
specified in the error code list. So, for such errors return
CKR_KEY_TYPE_INCONSISTENT instead.
=> ta: pkcs11: Fix error code returned by entry_processing_key()

core/drivers/gic.c
Gd->max_it shold refer to the largest support interrupt Id. Fix
the off by one error so that the interrupt with the largest id
can be correctly handled.
Signed-off-by: Fangsuo Wu <fangsuowu@asrmicro.com>
=> drivers: gic: Fix the off by one error

.azure-pipelines.yml, .shippable.yml, MAINTAINERS, core/arch/arm/plat-imx/registers/imx6.h, core/drivers/imx_rngb.c, core/drivers/sub.mk
The purpose of the RNGB is to generate cryptographically strong random data.
The RNGB generates random numbers for secret keys, per message secrets, random challenges, and other similar quantities 
used in the cryptographic algorithms.
This would be one of the options: ie, use it as the cryptographic RNG
Another option would be use it as done by Linux: just to seed and give entropy to the PRNG: this would make the crypto_rng_* interface more resistant to hardware issues since a problem in the hwrng wouldnt be critical (just an issue during seed or feeding some new _hwrng entropy pool_ if we decide to go this way)
However I am not sure which one is the preferred choice so I'll start with this one.
=> iMX Random Number Generator driver

lib/libutee/tee_api_arith_mpi.c
Fix a memory-leak in bigint_binary_mod function.
The modulus n was not released.
Signed-off-by: Matthieu BERTIN <matthieu.bertin@viaccess-orca.com>
=> Fix a memory-leak in bigint_binary_mod function.

core/arch/arm/include/kernel/abort.h, core/arch/arm/include/mm/tee_pager.h, core/arch/arm/kernel/abort.c, core/arch/arm/kernel/thread.c, core/arch/arm/mm/tee_pager.c, core/include/mm/fobj.h, core/mm/fobj.c, mk/config.mk
This PR reduces the heap usage when paging is enabled by storing the IVs and Tags of the paged user TA pages in a special paged area instead of allocating these from the heap.
=> Paged IV and Tags state for RW paged mappings used for user TAs

core/arch/arm/include/mm/core_mmu.h, core/arch/arm/mm/core_mmu.c, core/arch/arm/mm/mobj.c, core/include/mm/vm.h, core/mm/vm.c
Change check_pa_matches_va() to not panic on memory references
on fully pageable (unlocked) memory.
This change makes tee_mmu_user_va2pa_attr() (and vm_va2pa()) to
return a null physical address with TEE_SUCCESS on unlocked
pageable memory since these may change of physical page.
An alternative is to inspect the pager to check is there is a
matching physical page but in this case one should lock pager
or at least the page, while va and pa are loaded and
check_pa_matches_va() returns. I think it's not worth the gain.
TODO: rename straight tee_mmu_user_va2pa_attr() to vm_va_info(pa, attr)
and update the inline comments stating vm_va2pa() is deprecated.
=> core: mm: fix check_pa_matches_va() panic on unlocked paged memory

core/arch/arm/mm/tee_pager.c
Initialize the vabase in each struct pgt used to page OP-TEE core.
Fixes: 5ca851ec83ba ("core: pager: add struct tblidx")
=> core: pager: initialize vabase in core pager tables

lib/libmbedtls/sub.mk
When building MBed TLS source files for use in the TEE core, some files
are currently compiled which are not used in the final link. This wastes
some resources (build time and disk space), although not much; but it
also makes it less clear what is actually used by the core.
Introduce a reduced source file list in lib/libmbedtls/sub.mk when the
library is built for the core.
=> core: libmbedtls: build only necessary files

core/tee/tee_svc_cryp.c
Fixes the check of the RSA Public Exponent in check_pub_rsa_key(). Prior
to this patch was the wrong byte used to check if the bignum was odd.
With this patch is the correct byte selected in the big-endian bignum.
Fixes: 338b123ee66c ("core: syscall_obj_generate_key() check public rsa exponent")
Suggested-by: Cedric Neveux <cedric.neveux@nxp.com>
=> core: fix rsa public exponent check

core/arch/arm/plat-imx/drivers/imx_csu.c
The sentinel detection in the initialization loop for the CSU_CSL<n>
registers is wrong in that is doesn't allow to set the first register,
CSU_CSL0 (when csu_index == 0). Fix the conditional so that it stops
on the sentinel value (-1) but still allows 0 as a valid index.
CSU_CSL0 is used for the PWM peripherals on i.MX6 platforms.
Reported-by: Robert Delien <r.delien@payter.nl>
=> drivers: csu: allow setting CSU_CSL0

core/drivers/bcm_sotp.c
bcm_sotp should be available early in optee boot.
which is achived by making it as service.
Signed-off-by: Vahid Dukandar <vahidd@microsoft.com>
=> driver: bcm_sotp: changed driver_init to service_init

core/mm/vm.c
Commit d6ad67f674e5 ("core: mm: change vm_pa2va() to return a virtual
address") moved the call to mobj_get_pa() up in a 'for' loop and added
a 'continue' statement. Moving it was wrong because at this point 'size'
is not yet updated which causes an infinite loop when the PA is not
found.
Move the call back to its original location but keep the 'continue'
which looks correct.
Fixes: d6ad67f674e5 ("core: mm: change vm_pa2va() to return a virtual address")
=> core: mm: fix infinite loop in vm_pa2va()

core/arch/arm/mm/core_mmu.c
During discovery of the non-secure memory, the memory attributes like
address and size are stored as part of the core_mmu_phys_mem
structure. Memory for this structure is allocated on the nexus heap
area. Subsequently, when memory for this structure is reallocated,
this is done using the plain realloc call. Use the nex_realloc api for
the reallocation.
Signed-off-by: Sughosh Ganu <sughosh.ganu@linaro.org>
=> core: mm: Use nexus memory allocation api's in carve_out_phys_mem

core/include/kernel/tee_ta_manager.h, core/kernel/tee_ta_manager.c, core/kernel/user_ta.c
This is to fix issue [4471](https://github.com/OP-TEE/optee_os/issues/4471)
When a ctx of a single instance user TA is first created,
lock_single_instance() is called in tee_ta_try_set_busy().
However, unlock_single_instance() is not called in
tee_ta_clear_busy() since ctx->initializing is still false.
It results that tee_ta_single_instance_thread is not reset
when CFG_CONCURRENT_SINGLE_INSTANCE_TA is not enabled.
So remove the wrong conditional expression and remove
"initializing" from tee_ta_ctx since it's no longer used.
Signed-off-by: RueiAnHu <Rayan.Hu@mediatek.com>
=> core: fix wrong conditional expression in tee_ta_clear_busy()

core/arch/arm/kernel/unwind_arm64.c
- if CFG_TEE_CORE_LOG_LEVEL in build/common.mk set to zero,
optee_os doesn't compile
- error is:
```
core/arch/arm/kernel/unwind_arm64.c:77:6: Error: redefinition of »print_kernel_stack«
77 | void print_kernel_stack(void)
|      ^~~~~~~~~~~~~~~~~~
in file, included from core/arch/arm/kernel/unwind_arm64.c:35:
core/include/kernel/unwind.h:15:20: Warning: previous definition of »print_kernel_stack« was here
15 | static inline void print_kernel_stack(void)
|                    ^~~~~~~~~~~~~~~~~~
```
- to avoid this error we assure the function is not redefined
=> optee_os: fixes compilation problem with trace level 0

core/sub.mk, mk/config.mk
Define CFG_EARLY_TA_COMPRESS configuration switch to
allow platform to disable early TAs compression at build time.
Disabling the compression drastically reduces the amount of the
core heap required in the embedded part.
Enable the configuration by default for backward compatibility.
Suggested-by: Arnaud Pouliquen <arnaud.pouliquen@st.com>
=> mk: core: ta: make early TA compress optional

core/arch/arm/include/mm/core_mmu.h, core/arch/arm/kernel/entry_a32.S, core/arch/arm/kernel/entry_a64.S, core/arch/arm/mm/core_mmu_lpae.c, core/arch/arm/mm/core_mmu_v7.c
For virtualization support, we have multiple mmu partitions, one per
virtual machine. These partitions are initially mapped to the default
partition in core_init_mmu_map(). With CFG_ASLR=y, the partition table
needs to be reinitialized as default_partition has now been relocated to
a different VA.
=> core_mmu: Initialize mmu partition table after relocation

core/arch/arm/include/kernel/secure_partition.h, core/arch/arm/include/kernel/thread_spmc.h, core/arch/arm/kernel/spmc_sp_handler.c, core/arch/arm/kernel/thread_spmc.c
rxtx buffers are used for SPs and the SPMC to exchange information.
Implements the following FF-A messages for SPs.
FFA_RXTX_MAP_64 and FFA_RXTX_MAP_32 to have a SP map a rxtx buffer
FFA_RXTX_UNMAP: to unmap the rxtx buffer
FFA_RX_RELEASE: to release have the SP release the rx buffer
=> core: ADD FF-A rxtx buffer for SPs

core/arch/arm/kernel/link.mk, core/arch/arm/plat-rcar/link.mk
.srec files are used to flash OPTEE on Rcar Gen3 using serial mode. Serial mode
downloader in Rcar does not recognize S2 records in .srec files that objcopy
generates by default. It allows only S3 records. Also, it requires correct load
address present in .srec files.
So, we need to provide additional flags to objcopy during tee.srec file
generation. This change introduces makefile variable SRECFLAGS that can be used
exactly for this task. Also it provides the correct flags for rcar platform.
Note: at the begging tee.srec file was generated directly from tee.elf and had
correct load addresses. As the load address is wider than 24 bits, objcopy
automatically used S3 records. But, later tee-raw.bin were introduced and I
changed source for tee.srec, so now it is generated from tee-raw.bin. …
=> core/link.mk, plat-rcar: introduce SRECFLAGS variable

core/arch/arm/include/kernel/stmm_sp.h, core/arch/arm/kernel/stmm_sp.c
Fix a memory layout issue when `CFG_WITH_STMM_SP=y` and `CFG_WITH_PAGER=y`.
Before this change were all StMM operation function handlers their related resources being linked into the pager unpaged sections despite they could be pageable.
The reasons are both `__rodata_unpaged` attribute used for `stmm_sp_ops` instance and also the fact it is referenced in helper function `is_stmm_ctx()` which is referenced in unpaged helper function `is_user_mode_ctx()`.
This change removes `__rodata_unpaged` attribute from `stmm_sp_ops` and removes `stmm_sp_ops` reference pager constraint by using an indirect reference in `is_stmm_ctx()`.
=> core: stmm: Remove pager constraint on stmm_sp_ops

core/drivers/crypto/se050/core/cipher.c
A boolean encrypt flag was being passed to the cipher init function that
instead expects a TEE_OperationMode enum. Given that the enum TEE_MODE_ENCRYPT
has as a value of 0, encrypt and decrypt operations were effectively swapped.
This error has no practical effect on current se050 mainline code because the
only AES mode currently supported for se050 is CTR, which ignores the passed
value and always performs an encrypt. But it needs to be fixed before
adding support for ECB or CBC, for example.
Signed-off-by: Dave Herron <dave.herron@gallagher.com>
=> drivers: se050: Fix incorrect handling of se050 cipher operation mode

ta/pkcs11/src/sanitize_object.c
In sanitize_indirect_attributes(), class and key check is performed
to check to check that athe indirect attribute is provided
only for particular type of key objects. This check causes issue
in case an indirect template further has pointer to another
indirect template. It is not essential for an indirect template to
have class and key attributes.
When creating objects for classes which don't support the indirect
template, this would result in scenario where error is not returned.
However, the indirect attribute won't get added to the created object.
This is inline with how the other attributes are dealt with currently.
eg. if when creating a secret key, a public key attribute is passed,
it is currently ignored rather than returning error. A probable
fix is to check all the attributes in …
=> ta: pkcs11: Remove class and key check for indirect attributes

core/drivers/crypto/caam/hal/common/hal_cfg_dt.c, core/drivers/gic.c, core/drivers/sp805_wdt.c, core/include/kernel/dt.h, core/include/kernel/interrupt.h, core/kernel/dt.c, core/kernel/interrupt.c
This patch series:
- Split dt-bindings management to welcome other interrupt drivers.
- Update gic driver to take account the type of interrupt specified in device tree (SPI | PPI)
- Add interrupt resource in dt_node_info.
- Add an interface to allocate and add an interrupt handler.
=> core: interrupt: update dt and client interface

core/tee/tee_pobj.c
When tee_pobj_get() is called with TEE_POBJ_USAGE_CREATE and without
TEE_DATA_FLAG_OVERWRITE, and the persistent object is found in the list of
open objects, the function should return TEE_ERROR_ACCESS_CONFLICT
immediately. There is no need to call into the FS layer since we know
the object exists at this point.
Fixes: https://github.com/OP-TEE/optee_os/issues/4560
=> core: tee_pobj_get(): detect access conflict

core/arch/arm/include/kernel/thread_spmc.h, core/arch/arm/kernel/spmc_sp_handler.c, core/arch/arm/kernel/thread_spmc.c
Add the following functionality:
FFA_ID_GET: Allow a SP to retrieve it's own id
FFA_VERSION: Allow a SP to retrieve the FF-A version supported
FFA_FEATURES: Allow a SP to retrieve the FF-A features supported.
=> core: Add a couple of small FF-A messages support for SPs

lib/libutee/include/pta_invoke_tests.h
In PTA "invoke test", AES performance test command takes as argument key
size value as bits instead of bytes. Fix typo in comments.
=> libutee: include: fix typo in pta_invoke_tests.h

core/arch/arm/plat-rcar/main.c, core/arch/arm/plat-rcar/platform_config.h
Pair of patches that adds support for the new version of M3 SoC and removes deprecated calls.
Theoretically, rcar platform now supports memory configuration via DTB, but for some reason it can't parse memory nodes that describe non-secure RAM. So, for now I'll just add static configuration for m3_2x4gb.
=> plat: rcar: add M3 SoC with 8GB memory and use register_ddr()

core/arch/arm/plat-stm32mp1/conf.mk, core/include/drivers/scmi-msg.h, core/pta/scmi.c, core/pta/sub.mk, lib/libutee/include/pta_scmi_client.h, mk/config.mk
Adds a PTA interface to REE SCMI agents to get SCMI message communication channel for processing in OP-TEE SCMI server.
Currently implement supports for a SCMI server built with CFG_SCMI_MSG_SMT=y.
The implementation is made so that an alternate SCMI server implementation can added.
=> SCMI: introduce an SCMI PTA interface for REE SCMI agents

core/drivers/crypto/caam/cipher/caam_cipher_mac.c
Hello,
These are two fixes for the CAAM CMAC we found while inspecting the code.
xtest does not cover these cases.
Thanks!
Clement
=> Fix for data input size of CAAM CMAC do_update()

CHANGELOG.md, mk/config.mk
Update CHANGELOG for 3.13.0 and collect Tested-by tags for
the next release.
=> Update CHANGELOG for 3.13.0

core/arch/arm/include/mm/tee_pager.h, core/arch/arm/kernel/boot.c, core/arch/arm/kernel/stmm_sp.c, core/arch/arm/kernel/thread.c, core/arch/arm/mm/tee_pager.c, core/include/kernel/user_mode_ctx_struct.h, core/include/mm/fobj.h, core/include/mm/tee_mmu_types.h, core/kernel/user_ta.c, core/mm/fobj.c, core/mm/mobj.c, core/mm/vm.c
Renames struct tee_pager_area to struct vm_paged_region and moves it
next to the declaration of struct vm_region. Since areas are now called
paged regions or regions also rename functions, variables and struct
members accordingly.
=> core: rename struct tee_pager_area to vm_paged_region

.travis.yml
The default build environment for Travis CI is currently Linux Ubuntu
Xenial (16.04). This is quite an old release (21 April 2016). The latest
release supported by Travis CI is Focal (20.04), released on 23 April
2020. This commit updates to 20.04 by selecting "dist: focal" instead of
keeping the default. The reason is to obtain a more up-to-date codespell
dictionary. For example, it was found that checkpatch detects the
spelling mistake 'becase' on 20.04 but not on 16.04.
=> ci: travis: select Ubuntu 20.04

.travis.yml
checkpatch.pl expects to find the codespell dictionary in
/usr/share/codespell/dictionary.txt, but the codespell package in Ubuntu
20.04 has moved to a different path [1]. Take care of this by creating a
symlink.
Link: [1] https://packages.ubuntu.com/focal/all/codespell/filelist
Fixes: 784103ed82de ("ci: travis: select Ubuntu 20.04")
=> ci: travis: create symlink /usr/share/codespell/dictionary.txt

core/arch/arm/kernel/thread.c
Fix thread_alloc_and_run() to pass all its arguments to
__thread_alloc_and_run().
=> core: fix thread_alloc_and_run() argument passing

lib/libmbedtls/core/sm2-dsa.c, lib/libmbedtls/core/sm2-pke.c
When enable mbedtls in optee-os , xtest run twice will be fail.
Memory leakage exists in three functions.
1. grp and mpi in sm2_mbedtls_pke_encrypt
2. grp in sm2_mbedtls_dsa_sign
3. grp in sm2_mbedtls_dsa_verify
Fixes: c84eee6397bb ("core: add support for SM2 using MBed TLS")
Reviewed-by: Jerome Forissier <jerome@forissier.org>
Signed-off-by: lubing <lubing@eswin.com>
=> core: Fix memory leaks in sm2 of Mbedtls lib

core/lib/zlib/zconf.h
In zlib, _LFS64_LARGEFILE is expected to be a boolean directive, either
1 (true) or 0 (false). Depending on toolchain version and directives
build may produces warnings (as shown below with gcc 9.3) when the macro
is not defined hence this change to default it to value 0 (false).
```
core/lib/zlib/zutil.h:196:39: warning: "_LFS64_LARGEFILE" is not defined, evaluates to 0 [-Wundef]
196 |     (!defined(_LARGEFILE64_SOURCE) || _LFS64_LARGEFILE-0 == 0)
|                                       ^~~~~~~~~~~~~~~~
In file included from core/lib/zlib/adler32.c:9:
core/lib/zlib/zutil.h:196:39: warning: "_LFS64_LARGEFILE" is not defined, evaluates to 0 [-Wundef]
196 |     (!defined(_LARGEFILE64_SOURCE) || _LFS64_LARGEFILE-0 == 0)
|                                       ^~~~~~~~~~~~~~~~
CC …
```
=> core: zlib: fix build warning when _LFS64_LARGEFILE is not defined

core/mm/sub.mk
Function rwp_unpaged_iv_free() is reduced to a call to panic() when
CFG_WITH_PAGER=y and CFG_CORE_PAGE_TAG_AND_IV=y. In this case, Clang 12
suggests a noreturn attribute:
$ make -s CFG_WITH_PAGER=y COMPILER=clang
core/mm/fobj.c:322:1: warning: function 'rwp_unpaged_iv_free' could be
declared with attribute 'noreturn' [-Wmissing-noreturn]
{
^
1 warning generated.
However the attribute cannot be applied since it would be inappropriate
when CFG_CORE_PAGE_TAG_AND_IV != y. Therefore, disable the warning for
the file core/mm/fobj.c when the problematic configuration is enabled.
=> core: pager: fix compiler warning with Clang

scripts/mem_usage.py
All allocatable sections end up using memory when the TEE binary is
loaded. Therefore the 'A' (allocatable) flag in the readelf output is
all that matters when gathering memory usage data using mem_usage.py.
The hardcoded combinations that are currently hardcoded in the script
('AX', 'WA', 'A', 'AL') are fragile and need to be replaced. For
example, with COMPILER=clang many sections have the 'W' flag set.
=> mem_usage.py: consider all allocatable sections

core/arch/arm/kernel/thread_optee_smc_a32.S, core/arch/arm/kernel/thread_spmc_a32.S
With the commit referred below is __thread_std_smc_entry() changed to
take 6 arguments instead of 4. This means with the arm32 calling
convention [1] that the last two parameters are passed on the stack.
This is handled automatically by the C compiler, but has to be done by
hand when calling from assembly. __thread_std_smc_entry() is called from
assembly so fix the two places where the function is called.
Link [1]: https://developer.arm.com/documentation/ihi0042/latest/
Fixes: 4107d2f93e3e ("core: add a4 and a5 to thread_alloc_and_run()")
=> core: a32: fix parameter passing for __thread_std_smc_entry()

core/drivers/crypto/caam/utils/utils_dmaobj.c
Remove DMA object debug trace that would print a structure
variable through a NULL pointer.
=> drivers: caam: remove faulty DMAOJB_TRACE()

core/pta/scmi.c
Enable SMT channel threaded state when SCMI PTA gets a channel. Before
this fixup, Core panics when SCMI message is posted since the assertion
on channel threaded field value in scmi_smt_threaded_entry() when
in debug mode.
Fixes: b0a1c2504aaf ("core: pta: scmi: new interface to REE SCMI agent")
=> core: pta: scmi: fix missing threaded state of the channel

core/arch/arm/include/ffa.h, core/arch/arm/include/kernel/boot.h, core/arch/arm/kernel/entry_a32.S, core/arch/arm/kernel/entry_a64.S, core/arch/arm/plat-vexpress/fvp_spmc_pm.c
Replace the non-standard secondary core init mechanism on FVP platform.
Depends on TF-A v2.5, related PR: https://github.com/OP-TEE/manifest/pull/183
=> FF-A: secondary core init for FVP

core/drivers/crypto/caam/cipher/caam_cipher_mac.c
Depending on the memory buffer input configuration, the function
caam_dmaobj_sgtbuf_build() might modify the data size to be processed in
the loop.
This case happens sometimes on the imx8mp where the input buffer
physical address in above 32 bits.
This implies reporting the data size re-adjustment when data is saved in
the context buffer.
=> drivers: caam: fix CMAC data input handling

core/drivers/crypto/crypto_api/include/drvcrypt_asn1_oid.h
This macro forms the HASH OID for MD5 algorithm,
It is defined as:
id-md5 OBJECT IDENTIFIER ::= {
iso(1) member-body(2) us(840) rsadsi(113549) digestAlgorithm(2) 5
}
According to OpenSSL,
iso(1) member-body(2) us(840) rsadsi(113549) digestAlgorithm(2) 5
part is encoded as
0x2A,0x86,0x48,0x86,0xF7,0x0D,0x02,0x05
OpenSSL Link for reference: https://bit.ly/3hVZ7Is
But in this case it was being formed as
0x2A,0x86,0x48,0x86,0x48,0x02,0x05 which was wrong.
=> drivers:caam: Update DRVCRYPT_OID_MB_US_RSADSI macro with correct value

core/lib/libtomcrypt/src/headers/tomcrypt_pk.h, core/lib/libtomcrypt/src/headers/tomcrypt_private.h, core/lib/libtomcrypt/src/pk/rsa/rsa_make_key.c
This PR applies commit [49556a8e606c](https://github.com/libtom/libtomcrypt/commit/49556a8e606c) ("rsa: add rsa key generate with public exponent upto 256 bits") to the OP-TEE master branch.
I am not expecting any review or comment since this comes from upstream. I am creating a PR mainly to run CI.
=> Cherry-pick rsa_make_key_bn_e() patch from LibTomCrypt upstream

core/arch/arm/include/mm/core_mmu.h, core/arch/arm/kernel/boot.c, core/arch/arm/mm/core_mmu.c, core/drivers/crypto/caam/hal/common/hal_cfg.c, core/drivers/crypto/caam/hal/common/hal_cfg_dt.c, core/drivers/imx_i2c.c, core/drivers/imx_rngb.c, core/kernel/dt.c, core/kernel/tpm.c
In core_mmu_add_mapping() requested physical address
rounded up/down to granule size (0x100000), which leads
to establishing of virtual mappings with overlapped
physical counterparts. If two virtual mappings overlaps
due to such roundings, then following phys_to_virt() can
implicitly return result of virtual address from
unexpected mapping. This patch fix such behavior by
returning virtual address of newly established mapping.
Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>
Signed-off-by: Anton Rybakov <a.rybakov@omp.ru>
=> core_mmu: fix implicit behavior of core_mmu_add_mapping()

core/lib/libtomcrypt/rsa.c
Fix libtomcrypt crypto_acipher_gen_rsa_key() to call rsa_make_key_bn_e()
API to generate a RSA key with a public exponent upto 256 bits.
RSA standard specify that public exponent e can be between 65537 (included)
and 2^256 (excluded).
=> libtomcrypt: fix rsa key generation public exponent

core/arch/arm/plat-imx/conf.mk
Support for Compulab IoT Gateway (imx8mm) platform.
(PLATFORM=imx-mx8mm_cl_iot_gate)
Signed-off-by: Ying-Chun Liu (PaulLiu) <paulliu@debian.org>
=> plat-imx: add compulab iot-gate-imx8 board support

core/arch/arm/mm/tee_pager.c
With the introduction of the commit referred below may a paged region
span multiple translation tables, but tee_pager_set_um_region_attr()
wasn't updated to handle this. So fix this by by accurately calculate
the increment in the main loop of that function.
Fixes: 4a3f6ad054d4 ("core: pager: let struct tee_pager_area span multiple translation tables")
=> core: pager: fix increment calculation in tee_pager_set_um_region_attr()

lib/libmbedtls/core/rsa.c
This changes fixes Keymaster VTS if cryptolib use libmedtls
EncryptionOperationsTest, RsaPkcs1Success and
EncryptionOperationsTest, RsaOaepSuccess probabilistic failure.
We should change error code from libmedtls to TEE_AsymmetricDecrypt.
In the same scenario, the tomcrypt return value is eventually
Converted to TEE_ERROR_BAD_PARAMETERS,and then pass the test.
But mbedtls converted to TEE_ERROR_BAD_STATE,
This then causes panic to return the function TEE_AsymmetricDecrypt.
Signed-off-by: Liu Shiwei <liushiwei@eswin.com>
Tested-by: Liu Shiwei <liushiwei@eswin.com>
Acked-by: Etienne Carriere <etienne.carriere@linaro.org>
Acked-by: Jerome Forissier <jerome@forissier.org>
Acked-by: vchong
Acked-by: Jens Wiklander <jens.wiklander@linaro.org>
=> lib: mbedtls: return TEE_ERROR_BAD_PARAMETERS on input data error

core/drivers/crypto/caam/cipher/caam_cipher_mac.c, core/drivers/crypto/caam/include/caam_utils_dmaobj.h, core/drivers/crypto/caam/utils/utils_dmaobj.c
In case of cipher operation, the input and output CAAM SGT/Buffer
are built in same time through function caam_dmaobj_sgtbuf_inout_build()
to ensure that both SGT/Buffer do the same cipher block size.
This fix usecase when:
- cipher block to encrypt/decrypt is more than 1 Kbytes
- input data are accessible from CAAM (no reallocation)
- output data is not accessible from CAAM (reallocation of DMA buffer).
Due to this fix, AES CMAC update loop has to be fixed.
=> drivers: caam: fix DMA object when only output reallocated

core/tee/tee_ree_fs.c, mk/config.mk
New boolean configuration switch CFG_REE_FS_ALLOW_RESET that, when
enabled, will make OP-TEE OS to allow REE FS content to be reset in
the Linux filesystem even when RPMB FS is enabled and already stores a
REE FS rollback protection hash. This switch is intended to test purpose
where REE FS can be wiped because the device flash memory was programmed
with brand new build artifacts.
=> core: REE FS: introduce CFG_REE_FS_ALLOW_RESET

.azure-pipelines.yml
Adds a separate job to execute "make check" in the QEMUv8 environment.
The default configuration is tested as well as Normal World
virtualization (XEN_BOOT=y).
The Docker image used for this is jforissier/optee_os_ci:qemuv8_check
on Docker Hub [1]. The Dockerfile is available on Github [2].
Link: [1] https://hub.docker.com/repository/docker/jforissier/optee_os_ci/
Link: [2] https://github.com/jforissier/docker_optee_os_ci/blob/qemuv8_check/Dockerfile
=> ci: azure: run regression tests (make check) in QEMUv8

core/arch/arm/kernel/entry_a64.S
When CFG_NUM_THREADS and/or CFG_TEE_CORE_NB_CORE become large enough,
link errors are reported:
$ make -s CFG_TEE_CORE_NB_CORE=48 CFG_NUM_THREADS=48 \
PLATFORM=vexpress-qemu_armv8a
out/arm-plat-vexpress/core/arch/arm/kernel/entry_a64.o: in function `clear_bss':
core/arch/arm/kernel/entry_a64.S:160:(.text._start+0x98): relocation truncated to fit: R_AARCH64_ADR_PREL_LO21 against symbol `stack_tmp_stride' defined in .identity_map.stack_tmp_stride section in out/arm-plat-vexpress/core/arch/arm/kernel/thread.o
out/arm-plat-vexpress/core/arch/arm/kernel/entry_a64.o: in function `cpu_on_handler':
core/arch/arm/kernel/entry_a64.S:443:(.text.cpu_on_handler+0x50): relocation truncated to fit: R_AARCH64_ADR_PREL_LO21 against symbol `stack_tmp_stride' defined in .identity_map.stack_tmp_stride …
=> core: arm64: use adr_l to reference stack_tmp_stride

core/arch/arm/kernel/entry_a32.S, core/arch/arm/kernel/entry_a64.S
boot_init_primary_late() uses the stack of thread 0, so the flag that
indicates usage of the temporary stack must be cleared in the current
core's thread_core_local structure.
Fixes the following crash when CFG_CORE_DEBUG_CHECK_STACKS=y:
D/TC:0 0 select_vector:1126 SMCCC_ARCH_WORKAROUND_1 (0x80008000) available
D/TC:0 0 select_vector:1128 SMC Workaround for CVE-2017-5715 used
D/TC:0 0 check_stack_limits:370 Stack pointer out of range (0xb7f54fd0)
D/TC:0 0 print_stack_limits:346 tmp [0] 0xb7f57c90..0xb7f584b0
D/TC:0 0 print_stack_limits:346 tmp [1] 0xb7f58ad0..0xb7f592f0
D/TC:0 0 print_stack_limits:346 tmp [2] 0xb7f59910..0xb7f5a130
D/TC:0 0 print_stack_limits:346 tmp [3] 0xb7f5a750..0xb7f5af70
D/TC:0 0 print_stack_limits:351 abt [0] 0xb7f4e710..0xb7f4f330
D/TC:0 0 print_stack_limits:351 …
=> core: clear temporary stack flag before entering boot_init_primary_late()

lib/libutee/tee_api_operations.c
The GlobalPlatform TEE Internal Core API specification mentions the
following panic reason for TEE_MACCompareFinal(): "if input data exceeds
the maximum length for the algorithm". The current code returns
TEE_ERROR_MAC_INVALID instead. Fix this by assigning error code
TEE_ERROR_BAD_PARAMETERS which gets translated into a panic later.
Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>
=> libutee: TEE_MACCompareFinal(): panic if input size is too large

lib/libutee/tee_api_operations.c
This reverts commit dbb3274a60f0b258fe115ed1678fc569335c0c5d. It turns
out the panic reason cited in the commit ("If input data exceeds maximum
length for the algorithm") applies to the message only and has nothing
to do with macLen. The same sentence appears elsewhere in the spec where
there is no ambiguity.
=> Revert "libutee: TEE_MACCompareFinal(): panic if input size is too large"

core/arch/arm/plat-ls/platform_config.h
The GIC offset for LS1012A is different than the one for
LS1043A and LS1046A.
Fixing for LS1012A
Signed-off-by: Franck LENORMAND <franck.lenormand@nxp.com>
=> core: plat-ls: ls1012a: Fix GIC offset

scripts/checkpatch_inc.sh
Add new environment variable CHECKPATCH_OPT for configuring common optional
arguments.
In example newer codespell has moved dictionary to new location.
This allows one to use:
```
export CHECKPATCH=<path to linux kernel source>/scripts/checkpatch.pl
export CHECKPATCH_OPT=--codespellfile=/usr/lib/python3/dist-packages/codespell_lib/data/dictionary.txt
```
=> scripts: checkpatch_inc.sh: Add CHECKPATCH_OPT for optional arguments

.azure-pipelines.yml
Update the repo tool to the latest version before running 'repo sync'.
Fixes the following error [1]:
```
sudo -E bash -c "cd /root/optee_repo_qemu_v8 && repo sync -j 10"
project .repo/manifests/
Updating 7b69f4f..30fb9a8
Fast-forward
info: A new version of repo is available
warning: repo is not tracking a remote branch, so it will not receive updates
repo: Updating release signing keys to keyset ver 2.3
repo reset: error: Entry 'docs/manifest-format.md' not uptodate. Cannot merge.
fatal: Could not reset index file to revision 'v2.16.2^0'.
```
Link: [1] https://dev.azure.com/OPTEE/optee_os/_build/results?buildId=855&view=logs&j=705748f3-7146-5e86-79af-1c0266d20a8c&t=d3458a7d-1a81-5639-8e63-8927d807e53a&l=23
=> ci: azure: run 'git pull' to update repo tool before 'repo sync'

core/crypto.mk, core/crypto/cbc-mac.c
The current AES CBC MAC implementation invokes the AES CBC algorithm via
crypto_cipher_update() for each 16-byte block of the input data. This
can be inefficient especially with hardware accelerated implementations
which may have a significant overhead (I am thinking of proprietary
implementations of MBed TLS for example).
This commit introduces a new config option:
CFG_CRYPTO_CBC_MAC_BUNDLE_BLOCKS (default 64) which allows to bundle
several 16-byte blocks of input data when calling the AES CBC function.
Therefore with the default value, data are processed 1 KB at a time
(assuming the caller provides enough data of course). There is a small
memory overhead (malloc) of the same size at most.
=> crypto: optimize speed of AES CBC MAC

core/mm/vm.c
Whatever the return value of vm_map_pad, the mobj_put() is always called.
Therefore mobj_put() should not be called when mobj_get_cattr(mobj, &cattr) fails.
Signed-off-by: ZheTingLiu \<Gavin.Liu@mediatek.com>
=> core: mm: remove duplicate mobj_put() in vm_map_pad()

.azure-pipelines.yml
Since commit [1] in build.git, no need to touch a file in /boot.
Link: [1] https://github.com/OP-TEE/build/commit/fc2747c213bab7994317fe7a0d4a5fdaba92119a
=> ci: azure: remove hack previoously required for virt-make-fs

lib/libunw/unwind_arm64.c
print_stack_arm64() currently shows the full 64 bit addresses in
hexadecimal with leading zeros (0x0000000000000000). This is a bit hard
to read and is not necessary since virtual addresses are typically 32
or 36 bits (defined by CFG_LPAE_ADDR_SPACE_BITS), and in any case
nowhere near 64 bits.
Therefore, use a 32-bit format by default (0x00000000) and expand the
width as necessary. The new format is already used in ldelf to print
the region addresses so this changes brings consistency.
=> arm64: format call stack addresses on 8 characters by default

ta/pkcs11/src/processing.c
If C_EncryptInit()/C_DecryptInit() is called twice first starts the
operation and should inform caller that operation is already in progress
and keep the operation active until it is terminated with C_Encrypt()/
C_Decrypt() or by C_EncryptFinal()/C_DecryptFinal().
Specified in:
PKCS #11 Cryptographic Token Interface Base Specification Version 2.40
Plus Errata 01
5.8 Encryption functions
C_EncryptInit
and
5.9 Decryption functions
C_DecryptInit
Relates to:
- https://github.com/OP-TEE/optee_os/issues/4283
Related PRs:
- https://github.com/OP-TEE/optee_test/pull/537
=> ta: pkcs11: Fix calling twice of C_EncryptInit()/C_DecryptInit()

core/arch/arm/include/mm/core_mmu.h, core/arch/arm/kernel/virtualization.c, core/arch/arm/mm/core_mmu.c, core/mm/mobj.c
This fixes mobj splitting onto RX/RW parts. Now split can be done
incorrectly if RX and RW regions doesn`t mapped contiguosly.
Added helper core_mmu_find_mapping() allows to find mapping for
specified type and length independently of their order, so then
RX/RW regions for mobjects should be determined correctly.
Signed-off-by: Anton Rybakov <a.rybakov@omp.ru>
=> mm: fix mobj split by adding core_mmu_find_mapping() helper

mk/config.mk
Set CFG_EMBEDDED_TS when CFG_EARLY_TA or CFG_SECURE_PARTITION
is set even when no early_ta's or SPs are added to the system.
Signed-off-by: Jelle Sels <jelle.sels@arm.com>
=> Build: Fix CFG_EMBEDDED_TS dependency

ta/pkcs11/src/pkcs11_attributes.c, ta/pkcs11/src/pkcs11_token.c, ta/pkcs11/src/pkcs11_token.h, ta/pkcs11/src/processing.c
Add more operation states to take care of scenarios like failure
of an incremental (update) operation if a one-shot/final operation
has been started.
=> ta: pkcs11: Add operation state in session

ta/pkcs11/src/processing_asymm.c
Correct return code in asymmetric update sequence when digest of
the input data is updated on a multi-stage operation. Prior this
change, the implementation returned CKR_GENERAL_ERROR instead of
CKR_OK because the expected success return value was loaded for
that stage.
Fixes: fb279d8b608e ("ta: pkcs11: Add support for elliptic curve signing & verification")
=> ta: pkcs11: fix error code in asymmetric signature update sequence

core/arch/arm/kernel/asm-defines.c
Following commit 1b302ac09816 ("core: enable FF-A with SPM Core at
S-EL1"), the THREAD_CTX_SIZE macro is now defined twice on arm64
(in $(out-dir)/core/include/generated/asm-defines.h).
Kill the definition in the #ifdef ARM64 block and keep the common
one.
=> core: arm64: remove duplicate definition of THREAD_CTX_SIZE

mk/config.mk
When OP-TEE is built outside of a Git repository, the implementation
version is shown as "Unknown" at boot time. For example:
I/TC: OP-TEE version: Unknown (gcc version 10.2.1 ...
Improve this a bit by appending the major/minor revision of OP-TEE,
which is hardcoded in mk/config.mk and thus always available.
The above example becomes:
I/TC: OP-TEE version: Unknown_3.14 (gcc version 10.2.1 ...
=> core: improve version string shown at boot time when not using Git

core/arch/arm/kernel/entry_a32.S
During reset_primary, r7 is used to keep the content of r2 register
given to OP-TEE at start. However, r7 is clobbered during boot. This lead
to r2 being incorrectly restored when returning to normal world and
thus r2 value being corrupted. Use r9 instead where needed of r7 to
avoid clobbering it.
=> core: Fix r7 clobbering in reset_primary

ldelf/ldelf.mk, ta/mk/build-user-ta.mk, ta/mk/ta_dev_kit.mk
Defines arch-bits-$(sm) for ldelf and intree TAs sub components
so that they can build using CFLAGS32 (or CFLAGS64) directives
possibly passed by the build environment.
Defines arch-bits-ta_arm32 (resp. 64) in TA devkit to leverage
CFLAGS32 (reps. CFLAGS64) directive passed by the build process. This
change is needed for external package willing to pass specific
directive to TA build sequence as toolchain's sysroot path.
=> build: ldelf and TAs can rely on CFLAGS32/CFLAGS64

mk/config.mk
Change test for when both CFG_TA_GPROF_SUPPORT and CFG_ULIBS_SHARED
are enabled to be more strict on switches expected value.
Reported-by: Clément Léger <clement.leger@bootlin.com>
=> mk: fix test on gprof and shared libs configuration for TAs

core/lib/libtomcrypt/src/math/fp/ltc_ecc_fp_mulmod.c
Fix an improper locking bug due to unreleased lock ltc_ecc_fp_lock
Signed-off-by: ycaibb <ycaibb@gmail.com>
=> Fix an improper locking bug

ta/ta.mk
Fully remove configuration switch CFG_TA_DYNLINK that is deprecated
since 3.6.0, see commit d1911a85142d ("core: load TAs using ldelf").
=> ta: remove deprecated CFG_TA_DYNLINK

core/arch/arm/kernel/boot.c, lib/libutils/isoc/bget_malloc.c, lib/libutils/isoc/include/malloc.h, ta/arch/arm/user_ta_header.c
Don't add heap1 pool when smaller than 64 bytes when CFG_WITH_PAGER=y.
Bget memory allocation stack fails when pools are too small. This change
does not correct the issue but works around it as losing 64 byte of heap
here is affordable even when OP-TEE pager is enabled.
=> core: don't register heap pools when too small

core/arch/arm/plat-stm32mp1/main.c, core/arch/arm/plat-stm32mp1/shared_resources.c, core/drivers/stm32_bsec.c, core/drivers/stm32_etzpc.c
Several pieces of stm32mp1 code call get_embedded_dt(), then use the
resulting pointer without checks, or initiate a panic if it is NULL.
Thus hitting this code results in a non-working binary. For example:
"PLATFORM=stm32mp1 CFG_DT=y"
The get_embedded_dt() uses were #ifdef'd out based on CFG_DT. However,
as shown, this is problematic, as the calls assumed a valid fdt must
be returned. A non-NULL fdt can be guaranteed with CFG_EMBED_DT, so
use this as the basis for the #ifdefs.
Signed-off-by: Alexandru Gagniuc <mr.nuke.me@gmail.com>
=> plat-stm32mp1: Don't call get_embedded_dt() without CFG_EMBED_DT

mk/config.mk
Ensure CFG_SYSTEM_PTA is disabled when CFG_WITH_USER_TA is disabled since
system PTA is designed to provide user TA extended system features.
Without this change, building with CFG_SYSTEM_PTA=y and CFG_WITH_USER_TA=n
may fails with error traces like:
core/pta/system.c:227: undefined reference to 'ldelf_dlopen'
core/pta/system.c:260: undefined reference to 'ldelf_dlsym'
Also fix reference to the GPD TEE Internal Core API in CFG_SYSTEM_PTA
description.
=> core: enable system PTA upon user TA support

core/arch/arm/plat-ls/conf.mk
Emebedded DTB flag is CFG_EMBED_DTB which was wrongly
set as CFG_EMBED_DT.
=> plat-ls: conf.mk: correct Embedded DTB flag

core/include/kernel/dt.h, core/kernel/dt.c
The standard FDT reference in libfdt and friends is a const void *. Fix
few function prototypes that miss the const attribute.
=> core: dt: fix missing const attribute on fdt reference

ta/mk/ta_dev_kit.mk
Hello,
With this commit recently merged : https://github.com/OP-TEE/optee_os/pull/4829
It is now required to export `CFLAGS64` and `CFLAGS32` in Yocto optee-test recipe to compile TAs.
This is due to the introduction of : 
https://github.com/OP-TEE/optee_os/blob/3469baa6e7a7b4920596e54ec4c7624314e32042/ta/mk/ta_dev_kit.mk#L29-L30
that make the export `CFLAGS64` and `CFLAGS32` required. Exporting `CFLAGS` only in the recipe won't work.
With this patch, if `CFLAGS` is defined, set `CFLAGS64` and `CFLAGS32` to `$(CFLAGS)`
For reference, the NXP recipes for OPTEE : https://source.codeaurora.org/external/imx/meta-imx/tree/meta-bsp/recipes-security/optee-imx?h=hardknott-5.10.52-2.1.0
Patch similar to a change introduced in b09cddcab1eee090886ca94ab9a4958ec6e174e0
Thanks!
Clement
=> ta: mk: introduce CFLAGS32 and CFLAGS64

lib/libutils/isoc/bget_malloc.c, lib/libutils/isoc/include/malloc.h
When enabling malloc debug for TAs (CFG_TEE_TA_MALLOC_DEBUG=y), the
standard malloc entry points malloc(), calloc() and realloc() are
redirected by C macros to instrumented variants: mdbg_malloc(),
mdbg_calloc() and mdbg_realloc(). In addition, the 'normal' symbols are
not exported by libutils. That is a problem because a TA might still
reference them. For example the C++ code in optee_test requires libstdc++
which relies on malloc() etc.:
```
build (master)$ make -j10 CFG_TEE_TA_MALLOC_DEBUG=y CFG_TEE_TA_LOG_LEVEL=2
...
/home/jerome/work/optee_repo_qemu/build/../toolchains/aarch32/bin/arm-linux-gnueabihf-ld.bfd: /home/jerome/work/toolchains-gcc10.2/aarch32/bin/../lib/gcc/arm-none-linux-gnueabihf/10.2.1/../../../../arm-none-linux-gnueabihf/lib/libstdc++.a(eh_alloc.o): in function …
```
=> libutils: ta: provide malloc(), calloc() and realloc() when debug is on

core/arch/arm/plat-poplar/conf.mk
Since linaro-swg/linux.git branch optee [1] was rebased onto kernel
v5.12, Secure Data Path is broken in xtest [2] because the client side
is based on the ION allocator, which was removed from the kernel.
Therefore, disable SDP support by default.
Link: [1] https://github.com/linaro-swg/linux/tree/optee-v5.12-20210628
Link: [2] https://github.com/OP-TEE/optee_test/blob/3.13.0/host/xtest/regression_1000.c#L1220-L1263
Signed-off-by: Igor Opaniuk <igor.opaniuk@foundries.io>
=> poplar: disable CFG_SECURE_DATA_PATH by default

core/arch/arm/kernel/thread_optee_smc.c, core/arch/arm/mm/mobj_dyn_shm.c, mk/config.mk
Since recent changes in Linux kernel to add a shutdown callback to optee driver, I saw an issue with OP-TEE pager.
Disabling SHM cache is done from a fastcall SMC context that mandates unpaged resources. The issue is that moving SHM release resource to unpaged sections cost 6kB (without debug, on armv7-A/stm32mp1).
This change proposes to introduce CFG_PREALLOC_RPC_CACHE to allow disabling RPC shm preallocation. Enabling the switch (default) ensures required resources are resisdent to pager. Disabling the switch prevents these extra 6kB space in unpaged sections.
=> core: new config switch CFG_PREALLOC_RPC_CACHE

ta/pkcs11/include/pkcs11_ta.h, ta/pkcs11/src/attributes.h, ta/pkcs11/src/object.c, ta/pkcs11/src/pkcs11_attributes.c, ta/pkcs11/src/pkcs11_helpers.c, ta/pkcs11/src/pkcs11_helpers.h, ta/pkcs11/src/sanitize_object.c
Adds support for:
PKCS #11 Cryptographic Token Interface Base Specification Version 2.40
Plus Errata 01
4.6 Certificate objects
4.6.3 X.509 public key certificate objects
Relates to:
- https://github.com/OP-TEE/optee_os/issues/4283
Related PRs:
- https://github.com/OP-TEE/optee_client/pull/283
- https://github.com/OP-TEE/optee_test/pull/542
- https://github.com/OP-TEE/optee_client/pull/287
---
Before there is tests available here are some manual steps on how to test it out.
NSS certutil is the easiest command line tool to import certificates:
```shell
export PKCS11_MODULE=/usr/lib/libckteec.so.0
export PKCS11_SLOT=0
export PKCS11_TOKEN=token
export PKCS11_SO_PIN=1234567890
export PKCS11_USER_PIN=1234
pkcs11-tool --module …
```
=> ta: pkcs11: Add certificate object support

core/arch/arm/arm.mk, mk/config.mk
Makefile should test disabled CFG_CC_OPTIMIZE_FOR_SIZE against not
being 'y' instead of being 'n'.
=> core: arm: fix test on CFG_CC_OPTIMIZE_FOR_SIZE value

core/arch/arm/dts/stm32mp157a-dk1.dts, core/arch/arm/dts/stm32mp157c-dk2.dts, core/arch/arm/dts/stm32mp157c-ed1.dts, core/arch/arm/plat-stm32mp1/conf.mk, core/arch/arm/plat-stm32mp1/drivers/stm32mp1_clk.c, core/arch/arm/plat-stm32mp1/drivers/stm32mp1_pmic.c, core/arch/arm/plat-stm32mp1/drivers/stm32mp1_rcc.h, core/arch/arm/plat-stm32mp1/main.c, core/arch/arm/plat-stm32mp1/shared_resources.c, core/include/drivers/stm32_gpio.h
A series of changes around resources to prepare support for generic clock API.
=> plat-stm32mp1: prepare for clock framework

core/arch/arm/kernel/boot.c, core/arch/arm/kernel/link_dummies_paged.c, core/arch/arm/kernel/virtualization.c, core/arch/arm/mm/mobj_dyn_shm.c, core/arch/arm/mm/mobj_ffa.c, core/include/initcall.h, core/kernel/initcall.c
Adds call_preinitcalls() for really early initcalls. This function is
supposed to be called before call_initcalls() is called. With
virtualization enabled it is called in a blocking context when the
OP-TEE partition is created.
This PR breaks out the initcall stuff from https://github.com/OP-TEE/optee_os/pull/4844
I hope to continue the discussion here. I believe that the hooks enabled with with are needed, but the names may have become a bit messy with the extensions added over the time. Perhaps we can find some better name.
=> core: add call_preinitcalls()

CHANGELOG.md, mk/config.mk
Update CHANGELOG for 3.15.0 and collect Tested-by tags.
=> Update CHANGELOG for 3.15.0

core/drivers/gic.c, core/include/kernel/dt.h, core/include/kernel/interrupt.h, core/kernel/dt.c, core/kernel/interrupt.c
When describing a device in the device tree, it is sometimes necessary
to parse the interrupts properties and propagates them until adding
the interrupt. For instance some interrupt-cells allows to describe
priority and type of interrupt:
interrupts = <67 IRQ_TYPE_LEVEL_HIGH 2>;
With existing support, only the interrupt number is returned by
`dt_get_irq()`. This patch adds type and prio parameter which are passed to
`dt_get_irq_type_prio()` and `itr_add_type_prio()`. This allows interrupt
drivers to fill this from devicetree in `dt_get_irq()` but also use these
information in the `add()` callback. Additionally, it allows to specify these
flags manually when not using devicetree.
These parameters can then be used by the interrupt controller driver to
setup the irq line correctly. …
=> core: kernel: interrupt: add type and prio for interrupts 

core/arch/arm/plat-zynqmp/main.c
Register DDR based on the DRAM base and size definitions from
platform_config.h for supporting dynamic shared memory usage.
=> plat: zynqmp: register ddr for dyn shm support

core/tee/socket.c
Propagate out size for socket recv event when it's larger than the
supplied in size. Also enable passing a NULL buffer while querying the
size of the buffer.
=> core: pta: socket: enable TA to query recv out buffer

core/drivers/imx_mu.c, core/drivers/sub.mk, core/include/drivers/imx_mu.h
Hello,
I plan on upstreaming the CAAM support for i.MX8QM and i.MX8QXP.
I will split the code to upstream into multiple pull-requests to ease the review process.
I start today with the MU driver. Please note that the compilation flag for this driver (`CFG_IMX_SC`) is not defined anywhere for now.
Thanks!
Clement
=> drivers: imx: add MU driver

.azure-pipelines.yml
After the addition of Buildroot package host-python3-cryptography as a
dependency of optee_client_ext and optee_examples_ext [1], we now have
a build error in the Azure CI "QEMUv8 check" job:
```
>>> host-libopenssl 1.1.1l Configuring
(cd /root/optee_repo_qemu_v8/out-br/build/host-libopenssl-1.1.1l; ...
./config ...)
Operating system: x86_64-whatever-build
This system (build) is not supported. See file INSTALL for details.
```
The same command runs OK manually in the Docker image, but not in the
Azure environment. It is due to the fact that Azure sets a number of
environment variables, one of which (${SYSTEM}) conflicts with the
OpenSSL configuration script. Since we don't use this variable in our
script, just unset it.
Link: [1] https://github.com/OP-TEE/build/commit/a3b368f89a1c …
=> ci: azure: fix build error in Buildroot's OpenSSL

.azure-pipelines.yml
Add a job to the Azure CI to build the Rust examples in the
Teaclave Trustzone SDK [1]. They are part of the "buildroot" target so
restrict the build to that particular target to save time.
Link: [1] https://github.com/apache/incubator-teaclave-trustzone-sdk/
=> [RFC] ci: azure: add job to build and run the Rust tests

core/arch/arm/plat-ls/main.c, core/drivers/crypto/caam/hal/common/hal_cfg_dt.c, core/drivers/stm32_i2c.c, core/drivers/stm32_rng.c, core/drivers/stm32_uart.c, core/include/drivers/stm32_i2c.h, core/include/kernel/dt.h, core/kernel/dt.c
A series of changes that use the reg_size from the device tree to manage the call to phys_to_virt which now adds the len management.
Initial patch is to define the size as size_t to be compliant with the different functions using length as size_t and not ssize_t.
Update the driver using the _fdt_fill_device_info to retrieve the reg size and use it to get virtual address.
=> dt_node_info: add the reg size to manage core virtual address map

.azure-pipelines.yml
Same fix as commit 58676b162a91 ("ci: azure: fix build error in
Buildroot's OpenSSL") but for the Rust job.
=> ci: azure: fix build error in Buildroot's OpenSSL (Rust)

lib/libmbedtls/core/rsa.c
The value TEE_ERROR_MAC_INVALID returned by function
crypto_acipher_rsassa_verify() of mbedtls library will
cause TEE_AsymmetricVerifyDigest() to call TEE_Panic()
when it reports an invalid signature. Fix this by returning
TEE_ERROR_SIGNATURE_INVALID instead as specified by
the GPD TEE Internal Core API specifications.
Signed-off-by: lubing <lubing@eswin.com>
Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>
Acked-by: Jens Wiklander <jens.wiklander@linaro.org>
=> lib: mbebtls: correct return value in RSA-SSA signature verification

core/drivers/clk/clk_dt.c, core/include/drivers/clk_dt.h, core/include/kernel/dt.h, core/include/kernel/dt_driver.h, core/kernel/dt_driver.c, core/kernel/sub.mk
This P-R implements the first commits from RFC P-R #4949 that moves code from **core/drivers/clk/clk_dt.c** to a newly created source file **core/kernel/dt_driver.c** to use the sequences and resources for other drivers than clocks.
=> Driver probing sequence - step1 - factorize clk_dt code

core/arch/arm/dts/stm32mp157c-dk2.dts, core/arch/arm/dts/stm32mp157c-ed1.dts, core/arch/arm/dts/stm32mp157c-ev1.dts, core/arch/arm/plat-stm32mp1/conf.mk, core/crypto/crypto.c, core/drivers/crypto/crypto_api/authenc/authenc.c, core/drivers/crypto/crypto_api/authenc/sub.mk, core/drivers/crypto/crypto_api/include/drvcrypt.h, core/drivers/crypto/crypto_api/include/drvcrypt_authenc.h, core/drivers/crypto/crypto_api/sub.mk, core/drivers/crypto/stm32/authenc.c, core/drivers/crypto/stm32/cipher.c, core/drivers/crypto/stm32/common.h, core/drivers/crypto/stm32/crypto.mk, core/drivers/crypto/stm32/stm32_cryp.c, core/drivers/crypto/stm32/stm32_cryp.h, core/drivers/crypto/stm32/sub.mk, core/drivers/crypto/sub.mk, core/include/crypto/crypto_impl.h
This branch add support to the STM32 CRYP, an AES/DES hardware IP.
As this IP also support authenticated encryption (AES-CCM, AES-GCM), this branch add support for hardware accelerated Authenc in the OP-TEE crypto framework. (drivers: crypto: implement crypto driver - AUTHENC)
STM32 CRYP ip wil be used (compile and DT "enabled" if a device tree that support it is selected. (
plat-stm32mp1: enable CRYPTO HW if available)
=> Stm32 cryp driver and Authenticated Encryption driver interface

scripts/pem_to_pub_c.py, scripts/sign_encrypt.py
Move away from pycryptodome and use pyca/cryptography instead.
Also, deprecate TEE_ALG_RSASSA_PKCS1_V1_5_SHA256 in sign_encrypt.py. It
is not the default algorithm choice and should not be used anyway.
Signed-off-by: Donald Chan <hoiho@lab126.com>
=> scripts: migrate away from pycryptodome

core/arch/arm/plat-stm32mp1/drivers/stm32mp1_clk.c
A series a change in stm32mp1 clock driver to ease integration in generic clk framework, as proposed in RFC P-R https://github.com/OP-TEE/optee_os/pull/4942.
=> plat-stm32mp1: prepare clock driver for generic clk framework

core/drivers/clk/clk_dt.c, core/include/drivers/clk_dt.h, core/include/initcall.h, core/include/kernel/dt.h, core/include/kernel/dt_driver.h, core/kernel/dt_driver.c, lib/libutee/include/tee_api_defines_extensions.h
**(edited atfer #4965 merge)**
This RFC proposes a unified driver probing sequence for compatible drivers registered as dt_driver. The main goal of this unified driver probing implementation is to resolve device driver dependencies without requiring specific static initcall levels.
This changes introduce implementation in _core/kernel/dt_drivers.c_, executed at `driver_init` initcall level. The function parses DT nodes and probes registered compatible drivers. Driver probe function can register as a device driver provider. Driver probe function can query device(s) to the driver provider which may in turn request caller probe to be deferred when the target device is not yet registered in the driver provider database.
**Preparatory changes:**
~~This scheme reuses and adapts the …
=> Proposal for a driver probing sequence

core/arch/arm/kernel/boot.c, core/arch/arm/mm/core_mmu.c, core/arch/arm/mm/mobj_dyn_shm.c, core/arch/arm/mm/tee_mm.c, core/include/mm/tee_mm.h, core/mm/fobj.c, core/mm/mobj.c
In case of TA_RAM defined at the end of address range,
the high address will be defined outside the vaddr_t limits
which ends in a 0 address usage.
The size must be used rather than the high address that will
avoid this overflow issue. Update the corresponding files due
to API modification.
Signed-off-by: Lionel Debieve <lionel.debieve@foss.st.com>
=> core: mmu: fix overflow with high address in tee_mm_pool_t

core/arch/arm/plat-sam/conf.mk, core/arch/arm/plat-sam/sam_sfr.h, core/drivers/clk/sam/at91_audio_pll.c, core/drivers/clk/sam/at91_clk.h, core/drivers/clk/sam/at91_generated.c, core/drivers/clk/sam/at91_h32mx.c, core/drivers/clk/sam/at91_i2s_mux.c, core/drivers/clk/sam/at91_main.c, core/drivers/clk/sam/at91_master.c, core/drivers/clk/sam/at91_peripheral.c, core/drivers/clk/sam/at91_pll.c, core/drivers/clk/sam/at91_plldiv.c, core/drivers/clk/sam/at91_pmc.c, core/drivers/clk/sam/at91_pmc.h, core/drivers/clk/sam/at91_programmable.c, core/drivers/clk/sam/at91_sckc.c, core/drivers/clk/sam/at91_system.c, core/drivers/clk/sam/at91_usb.c, core/drivers/clk/sam/at91_utmi.c, core/drivers/clk/sam/sama5d2_clk.c, core/drivers/clk/sam/sub.mk, core/drivers/clk/sub.mk, core/include/dt-bindings/clock/at91.h, lib/libutils/ext/include/util.h
This series add complete support for SAMA5D2 clock tree.
Drivers have been partially ported from Linux and have been relicensed with dual GPL2 and BSD-3-Clause.
This will need to be acked by @Noglitch and @bbrezillon.
=> plat-sam: add sama5d2 clock tree support

core/arch/arm/kernel/boot.c, mk/config.mk
Recent security issues reported to the OP-TEE project covering iMX-devices has mostly been about current CSU configuration in the OP-TEE project. This purpose of this PR is to reduce the likelihood of configuring plat-imx incorrectly. It's simply a debug print. It might seem overkill to have something like this, but I think we've seen enough reports now that we can justify adding this.
=> Introduce boot warning print for vanilla developer builds

core/kernel/dt_driver.c
Adds a debug level trace message in dt_driver_device_from_node_idx_prop()
when unexpectedly not finding provider expected property in target node.
=> core: dt_driver: debug trace if property not found

core/kernel/huk_subkey.c, mk/config.mk
Legacy code has used the result of tee_otp_get_die_id function for SSK
generation. get_dummy_die_id function always returns default value and
this doesn't work for devices that initialized RPMB partition with old
OP-TEE version and have SoC specific tee_otp_get_die_id implementation.
Signed-off-by: Ruslan Piasetskyi <ruslan.piasetskyi@gmail.com>
=> Fix SSK generation for CFG_CORE_HUK_SUBKEY_COMPAT

core/include/kernel/dt.h
Corrects inline comment describing _fdt_get_status() helper function.
=> core: dt: fix inline description of _fdt_get_status()

ta/mk/build-user-ta.mk
Commit 19fdfcf617e3 ("build: ldelf and TAs can rely on CFLAGS32/CFLAGS64")
only partially implements what is mentioned in the commit description.
The ldelf part is OK, but in-tree TAs still don't use CFLAGS32 or
CFLAGS64. The reason is that the submodule name $(sm) is not ta_arm32 or
ta_arm64 like for TAs build with the "dev kit". Instead, $(sm) is the
name of the directory (such as "avb" for core/ta/avb, "pkcs11" for
core/ta/pkcs11, etc.). Therefore, it is not arch-bits-ta_arm32 or
arch-bits-ta_arm64 that needs to be set but arch-bits-$(sm).
Fixes: 19fdfcf617e3 ("build: ldelf and TAs can rely on CFLAGS32/CFLAGS64")
=> build: use CFLAGS32/CFLAGS64 when building in-tree TAs

core/lib/libtomcrypt/sha256_accel.c
Attempting to build optee-os with gcc11 fails with the following error
```
In function ‘sha256_compress_nblocks’,
inlined from ‘sha256_compress’ at core/lib/libtomcrypt/sha256_accel.c:81:11,
inlined from ‘sha256_done’ at core/lib/libtomcrypt/sha256_accel.c:158:5:
core/lib/libtomcrypt/sha256_accel.c:75:5: error: ‘crypto_accel_sha256_compress’ accessing 32 bytes in a region of size 20 [-Werror=stringop-overflow=]
75 |     crypto_accel_sha256_compress(state, buf, blocks);
|     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
core/lib/libtomcrypt/sha256_accel.c: In function ‘sha256_done’:
core/lib/libtomcrypt/sha256_accel.c:75:5: note: referencing argument 1 of type ‘uint32_t *’ {aka ‘unsigned int *’}
In file included from core/lib/libtomcrypt/sha256_accel.c:41: …
```
=> libtomcrypt/sha256_accel: fix stringop-overflow error

core/kernel/dt_driver.c
During discussions around P-R https://github.com/OP-TEE/optee_os/pull/4965 I missed an instruction in the implementation: where dt_driver provider reports a probe deferral error case: that is when expected provider is not yet registered.
This is fixed by commit "core: dt_driver: return TEE_ERROR_DEFER_DRIVER_INIT if no provider".
**(edited) the driver probing test part has been removed from this P-R**
~~This P-R also proposes some test support for driver probing, based on a dedicated embedded DTB. It adds a command to the invocation test PTA, to retrieve the status of the DT drivers probing tests.~~
~~Because the test currently relies only on clock resources, a commit adds config switch `CFG_DRIVERS_CLK_EARLY_PROBE` to have clock drivers probed with other registered compatible drivers so …
=> core: dt_driver: fix missing probe deferral report

core/arch/arm/dts/stm32mp157c-dk2.dts, core/arch/arm/dts/stm32mp157c-ed1.dts, core/arch/arm/dts/stm32mp157c-ev1.dts, core/drivers/crypto/stm32/stm32_cryp.c
Don't enable CRYP1 support in OP-TEE core from ST boards supporting stm32mp1 platform to comply with the upstream boards DTS files since v5.11 in Linux kernel that enables CRYP1 in non-secure world.
Adds registering of CRYP1 device as a secure peripheral when it is registered as a crypto driver.
=> plat-stm32mp1: fixes for CRYP1 support

core/kernel/dt_driver.c
If drivers is not providing a probe operator, that can result in
crash, so skip drivers not providing a probe operator.
Signed-off-by: Sahil Malhotra <sahil.malhotra@oss.nxp.com>
Fixes: 5017
=> core: dt_driver: skip drivers not providing a probe operator

core/arch/arm/include/kernel/boot.h, core/drivers/crypto/caam/hal/common/hal_cfg.c, core/drivers/crypto/caam/hal/common/hal_cfg_dt.c
On LX2160 board, Embedded DTB is enabled.
While booting with CAAM enabled, a crash comes in OP-TEE because it
tries to disable the Job Ring in Embedded DTB, which is read only.
So disable Job ring only when using External DTB.
=> core: drivers: caam: disable jobring in dts only in case of external DTB

core/drivers/clk/clk_dt.c
Prints the names of the parent node and node for which core failed to
probe a clock instance. Also prints the returned error code. These
added debug information help understanding where and FDT parsing failed.
=> drivers: clk: add verbosity on provider probe error case

core/kernel/dt_driver.c
Following recent discussions, a driver initialization failure (aside from probe deferral error case) should not panic core.
These patches changes the common driver probing sequence to not panic in such case.
=> core: dt_driver: allow driver probe/init failure without panicking

core/drivers/crypto/se050/adaptors/utils/utils.c
With the introduction of the se050 APDU driver, external clients can
create persistent objects on the secure element non-volatile memory.
The unique identifiers for these objects do not necessarily need to
fall within the range defined for objects created using the
cyptographic operation interfaces (keypair_gen).
This commit fixes the use case where a key stored in the SE05x device
(for example via a cloud service communicating to the optee-client's
libseteec) is imported into the secure world (ie the pkcs#11 database) and then used for
authentication (ie, EC sign)
=> crypto: drivers: se050: object identifier range [FIX]

core/include/kernel/dt.h
Fixes dt.h to prevent build failure when dt_driver.h is pre-compiled
while CFG_DT is disabled. Below are examples of such build error
traces:
core/include/kernel/dt_driver.h:61:29: warning: ‘enum dt_driver_type’ declared inside parameter list will not be visible outside of this definition or declaration
61 |            void *data, enum dt_driver_type type);
|                             ^~~~~~~~~~~~~~
core/include/drivers/clk_dt.h: In function ‘clk_dt_register_clk_provider’:
core/include/drivers/clk_dt.h:101:15: error: ‘DT_DRIVER_CLK’ undeclared (first use in this function); did you mean ‘CFG_DRIVERS_CLK’?
101 |         data, DT_DRIVER_CLK);
|               ^~~~~~~~~~~~~
=> core: dt: prevent build failure when CFG_DT is disabled

core/drivers/crypto/stm32/stm32_cryp.c
Changes stm32_crypt initialization function to not report an error
when the device is not defined or disabled in the embedded DT.
Prevents error trace message seen at boot time:
E/TC:0 0 call_initcalls:43 Initcall __text_start + 0x0002b958 failed
Fixes: 5c3bcc386415 ("dts: stm32mp1: disable CRYP1 device")
=> drivers: stm32_cryp: prevent error trace when disabled

ta/pkcs11/sub.mk
In some test cases, 16kB memory configured is not enough, specifically
while generating RSA keys, So increasing the default heap size to 32kB
=> ta: pkcs11: increase default heap size to 32kB

ta/pkcs11/src/sanitize_object.c
When sanitizing indirect templates, obj2 was getting allocated
twice leading to memory leak.
Fixes - https://github.com/OP-TEE/optee_os/issues/5022
=> ta: pkcs11: Fix memory leak

core/drivers/atmel_rstc.c, core/drivers/sub.mk, core/include/drivers/atmel_rstc.h
This reset controller will be used by PSCI to reset the SoC.
=> drivers: atmel-rstc: add support for reset controller

core/kernel/pm.c
Fix test error check that always return true with current
the condition. The check must be done to identify if the
SUSPENDED flag as been set.
Signed-off-by: Lionel Debieve <lionel.debieve@foss.st.com>
=> core: pm: fix incorrect flag check in pm_callback

core/drivers/imx_wdog.c
Fix a defined but not used error when building with CFG_DT by moving
dt_wdog_match_table under the same ifdef block used by the device-tree
block.
=> drivers: imx_wdog: fix defined but not used with CFG_DT=n

core/drivers/atmel_trng.c
Remove mistakenly added assert which will always trigger in debug
mode.
=> driver: atmel_trng: remove wrong assertion

core/include/kernel/dt_driver.h, core/kernel/dt_driver.c, core/tee/tee_cryp_utl.c
This series changes the driver probing sequence to probe drivers before and after core crypto and rng services are initialized.
Driver registering the the drvcrypt framework must be registered before crypto API is used. Drivers depending on the crypto service should be deferred to after crypto init.
=> dt drive rprobing: probe before/after crypto initialization

lib/libutils/isoc/qsort.c
Clang 13.0.0 produces the following warning:
lib/libutils/isoc/qsort.c:81:8: warning: performing pointer subtraction with a null pointer has undefined behavior [-Wnull-pointer-subtraction]
loop:   SWAPINIT(a, es);
^~~~~~~~~~~~~~~
lib/libutils/isoc/qsort.c:50:47: note: expanded from macro 'SWAPINIT'
#define SWAPINIT(a, es) swaptype = ((char *)a - (char *)0) % sizeof(long)
^ ~~~~~~~~~
Replace the subtraction with a simple cast to uintptr_t.
=> libutils: qsort.c: fix undefined pointer subtraction

core/arch/arm/mm/core_mmu_lpae.c
A compile time assertion is triggered by the following command:
$ make -j10 -s PLATFORM=vexpress-qemu_armv8a CFG_TEE_CORE_NB_CORE=128 \
CFG_LPAE_ADDR_SPACE_BITS=40
In file included from core/arch/arm/mm/core_mmu_lpae.c:61:
core/arch/arm/mm/core_mmu_lpae.c: In function ‘core_init_mmu_prtn_ta_core’:
lib/libutils/isoc/include/assert.h:30:24: error: duplicate case value
30 |   switch (0) { case 0: case ((x) ? 1: 0): default : break; } \
|                        ^~~~
core/arch/arm/mm/core_mmu_lpae.c:697:2: note: in expansion of macro ‘COMPILE_TIME_ASSERT’
697 |  COMPILE_TIME_ASSERT(MAX_XLAT_TABLES <
|  ^~~~~~~~~~~~~~~~~~~
lib/libutils/isoc/include/assert.h:30:16: note: previously used here
30 |   switch (0) { case 0: case ((x) ? 1: 0): default : break; } \
|                ^~~~ …
=> core: arm: lpae: fix build with large number of CPU cores

core/drivers/crypto/caam/acipher/caam_dh.c, core/drivers/crypto/caam/acipher/caam_ecc.c, core/drivers/crypto/caam/acipher/caam_math.c, core/drivers/crypto/caam/acipher/caam_rsa.c, core/drivers/crypto/caam/caam_ctrl.c, core/drivers/crypto/caam/hash/caam_hash.c, core/drivers/crypto/caam/hash/caam_hash_mac.c, core/drivers/crypto/caam/include/caam_acipher.h, core/drivers/crypto/caam/include/caam_hash.h
Hello,
A patch set to initialize CAAM hash, ecc, rsa and math drivers with the given JR base address instead of taking JR0 as base address systematically.
It prepares the CAAM support for imx8q/qxp
Thanks!
Clement
=> Initialize CAAM drivers with job ring base address

lib/libutils/ext/mempool.c
This commit removes `thread.h` from `lib/libutils/ext/mempool.c` since it is
not used, but also to eliminate the dependency between generic libraries
code and architecture-specific core functions.
=> lib: libutils: ext: mempool.c: remove unused thread.h

core/arch/arm/kernel/trace_ext.c, lib/libutils/ext/include/trace.h, lib/libutils/ext/trace.c
The function` print_core_id()` in `lib/libutils/ext/trace.c` is calling
architecture-specific routines to retrieve the core id. It is more
relevant to create a new abstract function `trace_ext_get_core_id()`
in `lib/libutee/trace_ext.c` that needs to be implemented in the
architecture-specific code. This is is similar to `print_thread_id()`
which calls `trace_ext_get_thread_id()` implemented in
`core/arch/arm/kernel/trace_ext.c`
Signed-off-by: Maroune Boubakri <marouene.boubakri@nxp.com>
=> lib: libutils: trace.c: make print_core_id() architecture-independent

core/drivers/atmel_trng.c, core/drivers/clk/clk_dt.c, core/drivers/clk/sam/sama5d2_clk.c, core/include/drivers/clk_dt.h
* drivers: clk: change `clk_dt_get_by_*()` prototype
Changes `clk_dt_get_by_idx()` and `clk_dt_get_by_name()` to return a the `TEE_Result` code and use an output argument to pass back clock reference rather than the opposite. This change makes `clk_dt_get_by_*()` function more consistent with the other OP-TEE core API functions.
Also renames`clk_dt_get_by_idx()` to `clk_dt_get_by_index()`.
Updates _sama5d2_clk.c_ and _atmel_trng.c_ accordingly.
* drivers: clk: use `while (true)`
Changes _clk_dt.c_ to use `while (true)` instead of `while (1)` for consistency in optee_os implementation.
=> drivers: clk: change API functions clk_dt_get_by_*()

core/lib/libtomcrypt/mpi_desc.c
This value is increased because xtest pkcs11_1019 when run
in loop, leads to extensive use of memory pool which
sometimes leads to memory allocation failure.
Problem is the way mempool_alloc() is implemented in combination
with how it's used from ltc_ecc_projective_add_point().
mempool_alloc() has a stack like allocation scheme. When freeing
the top element that memory is returned to the pool, but if memory
further down is free it's not returned until all elements above has
been freed. If two or more elements gets allocated and freed in a
cycle they can continue to use more and more memory with nothing
returned.
Fixes: https://github.com/OP-TEE/optee_os/issues/5022
=> core: libtomcrypt: increase MPI_MEMPOOL_SIZE to 46kB

core/arch/arm/kernel/stmm_sp.c
Currently we only allow single page sharing for the StanAloneMM non-secure
world buffer.  There are cases on EFI variables though which this isn't
enough.  For example an EFI signature list (.esl) containing more than
two keys would fail since the payload is larger than a single page.  So
let's bump the number to something more reasonable.
Note that we could add this on a config option with an upper boundary, but
four pages should be enough for embedded use cases
Signed-off-by: Ilias Apalodimas <ilias.apalodimas@linaro.org>
=> core: stmm: Increase the shared number of pages

core/drivers/crypto/se050/adaptors/include/se050_sss_apis.h, core/drivers/crypto/se050/adaptors/include/se050_utils.h, core/drivers/crypto/se050/adaptors/utils/info.c, core/drivers/crypto/se050/adaptors/utils/scp_config.c, core/drivers/crypto/se050/core/ecc.c, core/drivers/crypto/se050/core/rsa.c, core/drivers/crypto/se050/crypto.mk, core/drivers/crypto/se050/session.c
ECC sign fix:
----------------
The crypto API validates the size of the buffer that will hold the
resulting signature. This means that the SE05X driver can not use the
variable length buffer mechanism to request extra bytes to handle the
DER format.
To address this situation, this patch allocates a temporary buffer to
get the signature from the Plug-and-Trust subsystem; then, upon doing
the DER to binary conversion, copies the resulting data to the output
buffer.
OEFID runtime detection:
----------------------------------
The CFG_CORE_SE05X_OEFID definition is not required as the SE05X OEFID
can be read during early init - before the SCP03 session has been
established.
However we can continue to define it optionally: when that occurs, the OP-TEE driver 
will only initialize when such …
=> crypto: drivers: se050 updates

core/arch/arm/include/kernel/thread.h, core/arch/arm/include/kernel/thread_spmc.h, core/arch/arm/mm/mobj_ffa.c
It is more relevant to declare `thread_spmc_populate_mobj_from_rx()` and
`thread_spmc_relinquish()` in `thread_spmc.h` instead of `thread.h`
Source file `mobj_ffa.c` makes use of these two functions, hence include
`kernel/secure_partition.h` header.
=> core: arch: kernel: move spmc functions from thread.h to thread_spmc.h

core/arch/arm/kernel/thread_spmc_a64.S
Replace an adr instruction with adr_l in thread_foreign_intr_exit to
make sure that the r/w global variable threads is accessible even if the
optee binary is very large.
=> core: use adr_l for global r/w variable threads

lib/libutils/isoc/include/stdio.h, lib/libutils/isoc/sprintf.c
While building optee_test CXX test-cases natively on aarch64, OP-TEE
build relies on toolchain provided by buildroot. The buildroot toolchain
is built with flag: -fstack-protector-strong which requires
__sprintf_chk symbol provided by standard glibc. For OP-TEE we use a
customized libc which leads to below error:
CC out/init.o
CC out/os_test.o
CC out/ta_entry.o
CXX out/cxx_tests.o
CC out/user_ta_header.o
CPP out/ta.lds
LD out/5b9e0e40-2636-11e1-ad9e-0002a5d5c51b.elf
/home/sumit/optee_br/build/../toolchains/aarch64/bin/aarch64-linux-ld.bfd: /home/sumit/optee_br/toolchains/aarch64/bin/../lib/gcc/aarch64-buildroot-linux-gnu/10.3.0/../../../../aarch64-buildroot-linux-gnu/lib/../lib64/libstdc++.a(cp-demangle.o): in function d_append_num': cp-demangle.c:(.text+0x830): undefined reference to …
=> libutils: provide __sprintf_chk implementation

core/arch/arm/arm.mk, core/arch/arm/include/sm/optee_smc.h, core/arch/arm/kernel/boot.c, core/arch/arm/plat-vexpress/conf.mk, core/arch/arm/plat-vexpress/main.c, core/arch/arm/tee/entry_fast.c, core/include/drivers/gic.h, core/include/kernel/notif.h, core/include/optee_msg.h, core/include/optee_rpc_cmd.h, core/kernel/notif.c, core/kernel/sub.mk, core/kernel/wait_queue.c, core/tee/entry_std.c, mk/config.mk
This is a preview and RFC of the asynchronous notifications feature.
Note this is tested on QEMU virt (v7) together with the kernel patches in PR https://github.com/linaro-swg/linux/pull/93
I'm in particular interested in feedback on this from a SCMI point of view.
Other aspects to keep in mind is how this harmonizes with asynchronous notifications in FF-A 1.1
=> [RFC] Asynchronous notifications

lib/libutils/ext/mempool.c, lib/libutils/isoc/bget_malloc.c, lib/libutils/isoc/include/malloc.h, mk/config.mk
This relates to the issue https://github.com/OP-TEE/optee_os/issues/5022 and the recently merged PR https://github.com/OP-TEE/optee_os/pull/5065
Reply to https://github.com/OP-TEE/optee_os/issues/5022#issuecomment-996885144
> > Interesting, I wonder how much it can increase. Perhaps it's time to start looking for a alternative implementation to the mempool. I have an idea where bget could actually be reused with this.
> 
> Yes, we should look for some other mempool implementation as it hogs memory which is already free in some cases. It would be great if we can improve this implementation with bget.
This PR attempts to do this. Note that I haven't tried to tune `MPI_MEMPOOL_SIZE`.
The purpose of mempool is to be able to guarantee that temporary memory allocations will succeed during …
=> mempool based on bget

core/arch/arm/plat-imx/conf.mk
Support for Advantech RSB-3720 board (imx8mp).
(PLATFORM=imx-mx8mp_rsb3720_6g)
Signed-off-by: Ying-Chun Liu (PaulLiu) <paulliu@debian.org>
=> plat-imx: add Advantech RSB-3720 board support

core/arch/arm/plat-sam/main.c
plat-sam: set QSPI memories as non secure
When left unconfigured, the QSPI memories are in the secure world.
However, the controller is not secure and Linux expect to use these
memories with them and it will fail because the memories are not
accessible. Configure them as non secure to let linux handle the QSPI
controller.
=> plat-sam: Set QSPI memories as non secure

core/arch/arm/plat-sam/conf.mk, core/arch/arm/plat-sam/pm/psci.c, core/arch/arm/plat-sam/pm/sub.mk, core/arch/arm/plat-sam/sub.mk
This PR adds support for reset and shutdown via PSCI for plat-sam. It depends on reset controller and shutdown controller support which is currently under review.
=> plat-sam: add psci support for reset and shutdown

ta/pkcs11/src/object.c
When handle_get() failed in create_object(), ssession obj is not removed from temporary_object_list.
Only token obj is removed inside cleanup_persistent_object().
Add LIST_REMOVE for session obj.
Signed-off-by: Mengchi Cheng <mengcc@amazon.com>
=> ta: pkcs11: Clean up temporary_object_list in err condition

core/arch/arm/include/ffa.h
From: Sudeep Holla <sudeep.holla@arm.com>
Commit ef30482b4ad6 ("plat-vexpress: FF-A: update secondary core init")
updated secondary core init for the vexpress platform. In the process,
it used FFA_SECONDARY_EP_REGISTER with FID 0xC4000084 based on the ALP0
ABI of the spec and the TF-A upstream implementation at the time with a
note that the function ID needs to updated to the one finalied in the
spec and the TF-A implementation.
Assuming it is all finalised now, let us update the same with correct/
updated FID 0xC4000087.
Cc: Jens Wiklander <jens.wiklander@linaro.org>
Cc: Olivier Deprez <olivier.deprez@arm.com>
Cc: Balint Dobszay <balint.dobszay@arm.com>
Signed-off-by: Sudeep Holla <sudeep.holla@arm.com>
=> Fix FID for FFA_SECONDARY_EP_REGISTER_64

lib/libutee/tee_api_operations.c
Ideally, the ECB mode doesn't need an IV at all.
The GlobalPlatform spec says "IV required: No" for
the algorithms that use this mode (Table 6-6b).
So, in order to be inclined to the requirement of the
spec,  the implementation can panic when IV is provided
for ECB modes.
Signed-off-by: Sadiq Hussain <sadiq.muchumarri@intel.com>
=> libutee: Panic when IV is provided for ECB modes

core/arch/arm/include/kernel/spmc_sp_handler.h
Prior to this patch there's a link error when compiled with
CFG_CC_OPT_LEVEL=0 CFG_CORE_SEL1_SPMC=y CFG_SECURE_PARTITION=n:
LD      out/arm/core/all_objs.o
aarch64-linux-gnu-ld.bfd: out/arm/core/arch/arm/kernel/thread_spmc.o: in function `handle_mem_share_rxbuf':
core/arch/arm/kernel/thread_spmc.c:781: undefined reference to `spmc_sp_add_share'
Fix this by adding a dummy static inline spmc_sp_add_share().
Fixes: 6a1b230ce97c ("core: FFA_SHARE: Process Normal World share")
=> core: fix link error with CFG_CC_OPT_LEVEL=0

core/drivers/crypto/crypto_api/acipher/rsa.c
Route the unimplemented RSA sign/verify optional cases to their
software implementations.
=> drivers: crypto: rsa: handle not implemented sign/verify operations

core/include/kernel/dt_driver.h
Fixes inline description of type get_of_device_func that falsely mentions
TEE_ERROR_BUSY instead of TEE_ERROR_DEFER_DRIVER_INIT when expected
resource requests deferral of the driver probing.
Fixes: d8b14b46af9d ("core: dt_driver: get return code when querying a device")
=> core: dt_driver: fix result argument description get_of_device_func

core/arch/arm/arm.mk
The OP-TEE FF-A driver in the Linux kernel has been merged, so the
changes in the ABI towards the Linux kernel from now on have to be
backwards compatible.
=> core: the FF-A ABI is now a stable ABI

core/arch/arm/mm/core_mmu.c
Fix find_map_by_pa() to test the inclusive end address of an area
to prevent issues when end address overlaps size field byte size.
=> core: arm: mmu: fix find_map_by_pa() on areas end addresses

core/arch/arm/kernel/kern.ld.S, core/drivers/atmel_rstc.c, core/drivers/atmel_shdwc.c, core/drivers/atmel_trng.c, core/drivers/imx_lpuart.c, core/drivers/imx_uart.c, core/drivers/pl011.c, core/drivers/serial8250_uart.c, core/include/drivers/clk_dt.h, core/include/kernel/dt.h, core/kernel/dt.c, core/kernel/dt_driver.c
Replace the specific mechanism used to define and enumerate DT drivers
with scattered arrays. Doing so simplifies the TEE linker file a bit.
=> core: define DT drivers using scattered arrays

core/drivers/rstctrl/rstctrl.c, core/drivers/rstctrl/sub.mk, core/drivers/sub.mk, core/include/drivers/rstctrl.h, core/include/io.h, core/include/kernel/dt.h, core/kernel/dt_driver.c, mk/config.mk
This P-R proposes a reset controller driver interface and means to register in the DT driver provider framework ~~and some embedded tests~~:
* commit "_drivers: add reset controller framework_"
* ~~commit "_core: dt_driver: test reset-controller probing_"~~
~~This P-R reuses other changes alrerady under in others P-R:~~
~~* commit "_core: dt_driver: pass driver type to clk_get_provider_by_*()_" (from [P-R 4988](https://github.com/OP-TEE/optee_os/pull/4988)) is needed for provider to possibly differentiate providers relate to a same device node in the embedded DT.~~
~~* commits "core: dt_driver: return TEE_ERROR_DEFER_DRIVER_INIT if no provider",
"drivers: clk: add CFG_DRIVERS_CLK_EARLY_PROBE" and "core: dt_driver: drivers to test probe deferral"
(from [P-R …
=> core: reset controller driver interface

core/arch/arm/plat-imx/conf.mk, core/arch/arm/plat-imx/crypto_conf.mk, core/arch/arm/plat-ls/crypto_conf.mk, core/drivers/crypto/caam/utils/utils_mem.c
Hello,
Here is the last PR that will enable the CAAM support for mx8qmmek and mx8qxpmek platforms.
Thanks!
=> Enable CAAM driver on imx8qm/qxp

.azure-pipelines.yml, core/arch/arm/plat-imx/conf.mk, core/arch/arm/plat-imx/imx-common.c, core/arch/arm/plat-imx/imx-regs.h, core/arch/arm/plat-imx/imx.h
Hello!
A patch to add the i.MX 8DXL platform support.
Please note that the CAAM is currently disabled and will be enabled later.
Thanks,
Clement
=> core: imx: add support for i.MX8DXL

core/arch/arm/plat-stm32mp1/shared_resources.c
Changes stm32mp1 ETZPC configuration to allow non-secure read access
to DDRCTRL and DDRPHYC interface register. This change is needed by
U-Boot since release v2022.01 in order to dynamically compute the
DDR size.
Link: [1] https://source.denx.de/u-boot/u-boot/-/commit/d72e7bbe7c2841f161848d57b723495a731d0121
Signed-off-by: Patrick Delaunay <patrick.delaunay@foss.st.com>
=> plat-stm32mp1: allow non-secure to read DDR registers

core/arch/arm/kernel/spmc_sp_handler.c
Inside check_retrieve_request() the flags and tag where swapped.
Store them in the correct variable.
Signed-off-by: Jelle Sels <jelle.sels@arm.com>
=> core: Fix flags and tag check_retrieve_request()

scripts/sign_encrypt.py, scripts/sign_helper_kms.py
This adds support for signing trusted applications (TAs) using
a customer owned AWS KMS asymmetric key.
When the option to --key points to a valid Amazon Resource Name (ARN),
the signing operation will be delegated to AWS KMS. IAM credentials are
provided via environment variables.
Requires boto3 to work correctly.
Signed-off-by: Donald Chan <hoiho@amazon.com>
=> scripts/sign_encrypt.py: Support signing TAs using AWS KMS

.azure-pipelines.yml, core/drivers/crypto/se050/adaptors/sub.mk, core/drivers/crypto/se050/cflags.mk, core/drivers/crypto/se050/core/sub.mk, core/drivers/crypto/se050/crypto.mk, core/drivers/crypto/se050/sub.mk, mk/subdir.mk
Building the Plug-and-Trust library required building OP-TEE first in
order to get some architecture specific definitions. This makes the
integration with Yocto metas unnecessarily complex.
The following commit simplifies the build sequence: the user would
clone the Plug-and-Trust tree [1] into the external (ext) folder and
build OP-TEE as usual.
[1] https://github.com/foundriesio/plug-and-trust.git
=> drivers: crypto: se050: build plug-and-trust in tree

core/arch/arm/plat-ls/platform_config.h
Fix UART0_BASE address for LS1028 platform
=> core: plat-ls: ls1028a: fix uart address

core/include/kernel/dt.h
Fixes macro DEFINE_DT_DRIVER() to use SCATTERED_ARRAY_DEFINE_PG_ITEM()
that defines a paged list whereas SCATTERED_ARRAY_DEFINE_ITEM()
assumes array must be linked in the rodata_init section. Indeed
DT driver probing is done after pager is initialized.
Fixes: 61bdedea9452 ("core: define DT drivers using scattered arrays")
=> core: use a paged scattered array for DT drivers list

core/tee/tee_svc_cryp.c
The size of a DSA key is the size of the prime number (p) and not the
size of the subprime (q). Therefore the size indicator flag in the
definition of DSA cryptographic object attributes should be associated
with TEE_ATTR_DSA_PRIME, not with TEE_ATTR_DSA_SUBPRIME.
=> core: crypto: DSA key size is given by TEE_ATTR_DSA_PRIME

core/arch/arm/plat-stm32mp1/conf.mk
Changes platform stm32m1 to default enable CFG_ENABLE_EMBEDDED_TESTS
rather than CFG_TEE_CORE_EMBED_INTERNAL_TESTS to get all embedded tests
support including the test interface PTAs.
=> plat-stm32mp1: default enable CFG_ENABLE_EMBEDDED_TESTS

MAINTAINERS, core/arch/arm/plat-aspeed/conf.mk, core/arch/arm/plat-aspeed/core_pos_a32.S, core/arch/arm/plat-aspeed/platform_ast2600.c, core/arch/arm/plat-aspeed/platform_config.h, core/arch/arm/plat-aspeed/sub.mk
Aspeed AST2600 is a dual-core SoC with ARM Cortex-A7 integrated.
This PR aims to add the initial OP-TEE support for AST2600 platform.
=> arm: Add Aspeed AST2600 platform support

core/arch/arm/plat-zynqmp/conf.mk, core/arch/arm/plat-zynqmp/main.c, core/arch/arm/plat-zynqmp/platform_config.h
Xilinx Zynq MPSoC features two base addresses for DDR memories:
- First 2 GiB of DRAM (DDR Low): 0x0000_0000 .. 0x8000_0000
- And then rest of memory (DDR High): 0x0008_0000_0000 .. 0x000F_FFFF_FFFF
This change configures DDR base addresses depending on the size of DDR memory configured during build time and also helps on taking in use device tree to capture memory size from there.
Fixes physical address space bits to 40 bits allowing all peripherals to be used in OP-TEE.
This change also fixes DDR memory size for Xilinx ZCU102 board to 4 GB.
Tested that ZCU102 boots with and without device tree being used.
Also tested with custom board with larger DDR memory.
Fixes: https://github.com/OP-TEE/optee_os/issues/5144
=> Xilinx Zynq MPSoC fix memory allocation

CHANGELOG.md, mk/config.mk
Update CHANGELOG for 3.16.0 and collect Tested-by tags.
=> Update CHANGELOG for 3.16.0

core/arch/arm/include/arm32_macros.S, core/arch/arm/include/arm64_macros.S, core/arch/arm/include/kernel/boot.h, core/arch/arm/kernel/boot.c, core/arch/arm/kernel/entry_a32.S, core/arch/arm/kernel/entry_a64.S, core/arch/arm/kernel/thread_optee_smc_a32.S, core/arch/arm/kernel/thread_optee_smc_a64.S
Certain smc's are not expected to return. Prior to this patch in order
to guard against unexpected return a "b ." instruction was added after
each such smc to at least capture the cpu. With the introduction of FF-A
TF-A may in case there's a mismatch between OP-TEE and TF-A
configuration return some error code when an unrecognized smc is
encountered. The result is typically that the boot hangs after the print:
I/TC: Primary CPU switching to normal world boot
To help diagnosing such errors a call to panic is added after
each smc which isn't expected to return. The result becomes instead:
I/TC: Primary CPU switching to normal world boot
E/TC:0   Panic at core/arch/arm/kernel/boot.c:122 <__panic_at_smc_return>
E/TC:0   TEE load address @ 0xe100000
E/TC:0   Call stack:
E/TC:0    0x0e10d23c …
=> core: panic at unexpected smc return

core/arch/arm/arm.mk, core/arch/arm/include/arm.h, core/arch/arm/include/arm64.h, core/arch/arm/include/arm64_macros.S, core/arch/arm/include/kernel/thread.h, core/arch/arm/kernel/asm-defines.c, core/arch/arm/kernel/thread.c, core/arch/arm/kernel/thread_a64.S, core/include/kernel/user_mode_ctx_struct.h, core/kernel/user_ta.c, core/tee/tee_svc.c, ldelf/pauth.c, ldelf/pauth.h, ldelf/sub.mk, lib/libunw/include/unw/unwind.h, lib/libunw/unwind_arm64.c, mk/config.mk, ta/ta.mk
Pointer Authentication (part of ARMv8.3 Extensions) provides instructions for signing and authenticating pointers against secret keys. These can be used to mitigate ROP (Return oriented programming) attacks. The patches enables these instructions for TA's at EL0. When this option is chosen, TEE core will initialise secret keys per TA at the load time. 
The PAUTH support in ARMv8.3 introduces 2 keys for instruction space (APIA/B), 2 for data space (APDA/B) and 1 for general use (APG). The patchset uses only one key i.e APIAKey for TA's.
All xtests along with GP tests pass with the patch-set.
Changes have been done in thread_a64.S to save and restore the keys. Currently it is assumed we are enabling pauth when transitioning to el0 and disabling it whenever there is a sys call or exception …
=> Enable support for Pointer Authentication for TAs

mk/config.mk
Linux boot fails with XEN on CPU's with FEAT_PAUTH. So,
CFG_TA_PAUTH currently has not been tested and is incompatible
with CFG_VIRTUALIZATION.
It is also incompatible with debug options like FTRACE and GPROF.
If these incompatible options are selected together by a platform,
compilation will stop and user will be warned with an error
message.
=> cfg: Add restrictions with CFG_TA_PAUTH

.azure-pipelines.yml, core/drivers/crypto/se050/glue/i2c.c, core/drivers/crypto/se050/glue/i2c_imx.c, core/drivers/crypto/se050/glue/include/i2c_native.h, core/drivers/crypto/se050/sub.mk
The SE05X device is platform independent and therefore does not need
the iMX I2C driver but the actual driver for the particular platform
is connected into.
Implementing these changes required a fix in the Plug-and-Trust tree
(the addition of a missing dependency), therefore we will also bump
the Plug-and-Trust version used in the Azure pipeline.
=> crypto: drivers: se050: remove implicit dependency

.azure-pipelines.yml
The NXP SE05X Plug-and-Trust library generates too many warnings
causing it to flood the CI logs while building.
This commit bumps the Plug-and-Trust library version to a tag where
these warnings have been disabled.
References: https://github.com/OP-TEE/optee_os/issues/5162
=> ci: azure: plug-and-trust: disable build warnings

core/drivers/crypto/caam/include/caam_desc_defines.h, core/drivers/crypto/caam/include/caam_desc_helper.h
Instantiate RNG state handles with Prediction Resistance (PR) support.
This way SW further downstream (e.g. Rich OS, boot loader etc.) is able
to use the "PR" bit in RNG generation descriptors (forcing TRNG
re-seeding before PRNG / DRBG outputs random data).
Note: current patch does not deal with RNG state handles that have
already been initialized, but without PR support (this could happen if
U-boot would run before OP-TEE etc.). In this case, RNG state handle
would have to be deinstantiated first, and then reinstantiated with
PR support.
Signed-off-by: Franck LENORMAND <franck.lenormand@nxp.com>
Signed-off-by: Horia Geantă <horia.geanta@nxp.com>
=> drivers: caam: instantiate RNG state handle with prediction resistance

core/arch/arm/plat-sam/conf.mk, core/arch/arm/plat-sam/nsec-service/sm_platform_handler.c, core/arch/arm/plat-sam/nsec-service/smc_ids.h, core/arch/arm/plat-sam/nsec-service/sub.mk, core/arch/arm/plat-sam/sub.mk, core/drivers/pm/sam/at91_pm.c, core/include/drivers/pm/sam/atmel_pm.h
PSCI allows entering platform suspend with `SYSTEM_SUSPEND` call which is meant to enter the system in its deepest power state. sama5d2 platform supports multiple suspend power states.
Currently, Linux supports the atmel.pm_modes command line option which allows to select this suspend state. Since Linux uses PSCI `SYSTEM_SUSPEND` to enter suspend mode, we are not able to pass information (such as done for `CPU_SUSPEND`).
In order to select the mode that will be entered by `SYSTEM_SUSPEND` from normal world and thus select the desired suspend state, SMCs are added to allow selecting and getting this power mode.
This commits adds `sm_platform_handler()` support as well as handling of SiP SMCs to select/get the suspend mode from Linux.
=> plat-sam: add suspend mode support

core/arch/arm/dts/at91-sama5d27_som1_ek.dts, core/arch/arm/dts/at91-sama5d2_xplained.dts, core/arch/arm/dts/sama5d2.dtsi, core/arch/arm/include/kernel/boot.h, core/arch/arm/include/kernel/misc.h, core/arch/arm/kernel/delay.c, core/arch/arm/kernel/misc_a32.S, core/arch/arm/plat-sam/conf.mk, core/arch/arm/plat-sam/freq.c, core/arch/arm/plat-sam/sub.mk, core/arch/arm/sm/sm.c, core/drivers/atmel_wdt.c, core/drivers/sub.mk, core/drivers/wdt/sub.mk, core/drivers/wdt/watchdog.c, core/drivers/wdt/watchdog_sm.c, core/include/drivers/wdt.h, mk/config.mk
This commits adds a thin glue layer for watchdog access and adds a SMC handler which handles the `arm-smc-wdt` compatible Linux driver [1].
[1] https://lwn.net/Articles/819480/
=> watchdog: add glue and arm-smc-wdt smc handler

core/arch/arm/arm.mk, core/arch/arm/include/kernel/thread_spmc.h, core/arch/arm/kernel/thread_spmc.c, core/arch/arm/mm/mobj_ffa.c, core/arch/arm/plat-vexpress/main.c, core/include/mm/mobj.h
Please wait with this until after the release.
This adds support for FF-A with SPMC at EL3. There's a dependency to patches in TF-A since that's where the SPMC is implemented in this configuration.
This is built using https://github.com/OP-TEE/build/pull/548
The patches I've tested with are available at https://github.com/jenswi-linaro/arm-trusted-firmware/tree/poc/ffa_el3_spmc with QEMU specific patches on top
The base patches are reviewed at https://review.trustedfirmware.org/q/topic:%22ffa_el3_spmc%22+(status:open%20OR%20status:merged)
=> Ffa el3 spmc

core/drivers/stm32_gpio.c
The valid_gpio_config function did access the GPIO register
before the clock was enabled, which did lead to the assert always
failing when using stm32_gpio_set_output_level.
Signed-off-by: Loïc Bauer <loic.bauer@socomec.com>
=> dirvers: stm32_gpio: Fix register access before enabling clocks

core/arch/arm/plat-aspeed/platform_ast2600.c, core/arch/arm/plat-imx/main.c, core/arch/arm/plat-ls/main.c, core/arch/arm/plat-rockchip/main.c, core/arch/arm/plat-rzn1/main.c, core/arch/arm/plat-stm/main.c, core/arch/arm/plat-stm32mp1/main.c, core/arch/arm/plat-stm32mp1/stm32_util.h, core/arch/arm/plat-sunxi/main.c, core/arch/arm/plat-ti/main.c, core/arch/arm/plat-vexpress/main.c, core/arch/arm/plat-zynq7k/main.c, core/drivers/gic.c, core/include/drivers/gic.h
All platforms (except STM32MP1) follow the same pattern during GIC
initialization: get virtual addresses for distributor (and optionally,
for CPU interface), check that they are not NULL, call either
`gic_init()` or `gic_init_base_addr()`.
We can move most of this logic into `gic_init_base_addr()` while platform
code will supply only base physical addresses for distributor and CPU
interface. This will simplify and align platform code.
ST32MP1 had more complex logic, as it used `io_pa_or_va_secure()` to get
MMIO range addresses. However, as `main_init_gic()` called
`assert(cpu_mmu_enabled())`, there is no sense in using
`io_pa_or_va_secure()`, because we already ensured that VA will be
always used. Thus `assert()` call was moved to `gic_init_base_addr()`, and
STM32MP1 were aligned with …
=> plat: arm: refactor GIC initialization

core/arch/arm/plat-imx/drivers/imx_csu.c
The Secure Access register configures the access mode for
non-TrustZone aware DMA masters. To ensure that no DMA master can read
the secure memory for OP-TEE, we set access for all masters except the
ARM CP15 register to non-secure only and lock the settings afterwards.
Signed-off-by: Marc Kleine-Budde <mkl@pengutronix.de>
=> plat-imx: Add SA settings for i.MX7DS

core/drivers/crypto/crypto_api/acipher/rsassa.c
Add size check in the crypto driver for RSA sign and verify functions.
For both functions, the encoded message length has some size
constraints [1].
[1]: Public-Key Cryptography Standards (PKCS) #1: RSA Cryptography
https://datatracker.ietf.org/doc/html/rfc3447#section-9.1.1
Fixes: f5a70e3ef ("drivers: crypto: generic resources for crypto device driver - RSA")
Signed-off-by: Cedric Neveux <cedric.neveux@nxp.com>
=> drivers: crypto: add parameter checks for RSA signature

core/arch/arm/plat-rcar/conf.mk, core/arch/arm/plat-rcar/main.c, core/arch/arm/plat-rcar/platform_config.h, core/arch/arm/plat-rcar/sub.mk
There are two patches, first one adds GIC support for Gen3, second one adds support for Gen4.
=> plat: rcar: enable GIC support and add initial port for Renesas RCar Gen4 

core/tee/fs_dirfile.c, core/tee/tee_svc_storage.c, lib/libutee/tee_api_objects.c
A fix to allow persistent objects with an empty ID.
=> core: FS: make dirfile interface accept empty object ID

core/arch/arm/plat-imx/imx-common.c
Add the following SoC IDs to soc_is_imx6()
- SOC_MX6SL
- SOC_MX6SLL
- SOC_MX6D
Fixes: 16e73240d ("core: imx: add CSU module")
=> core: imx: add missing imx6 SoC IDs to soc_is_imx6()

core/arch/arm/include/optee_ffa.h, core/arch/arm/include/sm/optee_smc.h, core/arch/arm/kernel/thread_optee_smc.c, core/arch/arm/kernel/thread_spmc.c, core/arch/arm/tee/entry_fast.c, core/include/mm/mobj.h
This PR proposes a way to combine the RPC argument struct with the main struct when using the SMC ABI. This approach is already used with the FF-A ABI. This PR also enables efficient caching of argument structs in the kernel driver, see corresponding changes at https://github.com/jenswi-linaro/linux-1/tree/rpc_arg
=> [RFC] Combinded rpc arg

core/arch/arm/plat-imx/link.mk
In the NXP BSP, for imx6 and imx7 platforms (ARMv7), optee-os
is booted by U-Boot as a uImage file.
The generation of this uImage requires:
- optee-os load address. This address is fetched in the tee.elf file
with readelf.
- mkimage u-boot-tools. This tool takes the load address and the
tee-raw.bin as an input to generate the uImage uTee.
=> core: imx: generate uImage for imx6 and imx7 platforms

core/arch/arm/kernel/secure_partition.c, core/arch/arm/kernel/spmc_sp_handler.c, core/arch/arm/mm/sp_mem.c, core/include/mm/sp_mem.h
This is a replacement for #5215. The original author (@jellesels-arm) won't be able to continue the original PR.
I moved the contents without modification (only squash and rebase), please add any new comments on this PR.
Map the device and memory regions from the SP manifest file into the SP memory space.
Iterate over all device and manifest regions in the manifest file. Map the regions inside the SP memory space.
With this patch the Trusted Service crypto can use the hardware TRNG.
=> FF-A map manifest region

core/arch/arm/dts/stm32mp151.dtsi, core/arch/arm/dts/stm32mp157c-ed1.dts, core/arch/arm/dts/stm32mp15xx-dkx.dtsi, core/arch/arm/plat-stm32mp1/conf.mk, core/arch/arm/plat-stm32mp1/main.c, core/arch/arm/plat-stm32mp1/platform_config.h, core/drivers/stm32_iwdg.c, core/drivers/sub.mk, core/include/drivers/stm32_iwdg.h
This P-R implements stm32mp1 watchdog driver.
A later change will be posted once P-R and #5203 are merged, to implement watchdog timeout extension for this platform.
=> plat-stm32mp1: add watchdog driver

Makefile
The .ld.S files contains nothing worth indexing with cscope. The
generated *_unpaged.ld.S and *_init.ld.S are especially unfriendly as
they adds lots of false positive matches for cscope. Fix this by
excluding all the .ld.S files.
=> cscope: exclude .ld.S files

core/arch/arm/dts/dt_driver_test.dtsi, core/arch/arm/dts/embedded_dtb_test.dts, core/arch/arm/plat-vexpress/conf.mk, core/drivers/clk/clk_dt.c, core/include/kernel/dt_driver.h, core/kernel/dt_driver_test.c, core/kernel/sub.mk, core/pta/tests/invoke.c, core/pta/tests/misc.c, core/pta/tests/misc.h, lib/libutee/include/pta_invoke_tests.h, mk/config.mk
Implement _dt_driver_test.c_ with emulated resources (starting with clk's and rstctrl's) and a consumer device that gets those resources (possibly deferring its probe). A test DTSI defines the topology. After initcall completion, collect the status and let core self test (`xtest -t regression 1001`) report any failure (with a companion error traces).
Former change introduces `CFG_DRIVERS_CLK_EARLY_PROBE=y|n` to ease probe deferral (clocks not always early probe).
Note: can be useful when a clock depends on a pinctrl, probed after clock, but no occurrence in existing platforms.
Later change adds a missing description for CFG_DRIVERS_DT_RECURSIVE_PROBE.
The series default enables the test for qemu's platforms. The don't embed any DTB so use a template DTS file.
=> dt driver: test for driver probing sequence

core/arch/arm/mm/core_mmu_lpae.c, core/arch/arm/mm/core_mmu_v7.c, core/include/mm/core_mmu.h, core/mm/core_mmu.c
Removes constraint in LPAE implementation that expects core virtual
address range to fit a single block of the MMU base table used to
map the area. The implementation allows virtual addresses to spread
over several blocks of the base table. Therefor the limitation can be
removed.
As a result, selecting whether core virtual address range spreads
above or below the chosen base address depends on its location
against the virtual range mid address.
Fixes: https://github.com/OP-TEE/optee_os/issues/5201
=> core: mm: fix core virtual address range constraint in lpae

core/arch/arm/kernel/secure_partition.c, core/include/kernel/tpm.h, core/kernel/tpm.c, core/mm/core_mmu.c, mk/config.mk
**The first three commits of this PR are being reviewed in a separate PR: #5223** 
Forward TPM event log to FF-A SPs, so the initial attestation service of trusted-services can access it.
The PR consists of two parts:
- Enable OP-TEE to read the external device tree from secure memory. If OP-TEE acts like a SEL-1 SPMC Trusted Firmware-A passes a device tree in the secure memory (TOS FW config) and it forwards the details of TPM event log buffer in this device tree. Compared to the "traditional" OP-TEE boot (non-FF-A) the standard "tpm_event_log_addr" property is being used instead of "tpm_event_log_sm_addr".
- Map the TPM event log into the FF-A SP if its manifest has an "arm,tpm_event_log" compatible node indicating its need for the event log.
=> Forwarding TPM event log to FF-A SPs

core/kernel/tee_ta_manager.c
Fixes a use after free where the session pointer 's' was used after
tee_ta_close_session() while recovering from an error.
Fixes: 82061b8d7b34 ("core: store TA params in session struct")
=> core: fix use after free in tee_ta_open_session()

core/drivers/clk/clk_dt.c, core/kernel/dt_driver.c
This small series fixes parsing problems when using `assigned-clocks` properties:
- Wrong check for assigned-clock-rates property
- Handling of phandle == 0
=> Fix device-tree assigned-clocks properties parsing

scripts/get_maintainer.py
The release annoucements should be sent to the general OP-TEE mailing
list(s), in addition to the maintainers and reviewers. Add the needed
bits to extract this information.
=> get_maintainer.py: add OP-TEE mailing list(s) to --release-to

core/arch/arm/plat-imx/crypto_conf.mk, core/drivers/crypto/caam/hal/common/hal_jr.c
There is a bug in the CAAM JR interruption enablement logic. When
CFG_CAAM_NO_ITR=y, the JR interruptions are used and when
CFG_CAAM_NO_ITR=n, the JR interruptions are not used.
Even with this wrong logic, the CAAM is still able to enqueue jobs.
When no JR interruptions are received, the CAAM will manually dequeue
jobs from the jobring by checking the number of jobs done in the output
ring slots full register.
CAAM JR interruptions are not mandatory for the CAAM to work properly
but it makes the dequeuing faster than polling the output ring slot full
register.
Fixes: 3f45afc31 ("drivers: caam: disable the use of interrupts for some platforms")
=> drivers: caam: fix function definition when CFG_CAAM_NO_ITR=y

core/drivers/crypto/caam/caam_jr.c
Adding the JR interruption in the OPTEE CAAM driver, even if not used in
OPTEE, prevents the Linux CAAM driver from using the JR interruption on
platforms sharing the same line of interruption for all job rings.
To dequeue job from the job ring, the Linux CAAM driver would pull the
number of jobs done from the output ring slot full register.
The fix is to add the JR interruption only if CFG_CAAM_ITR=y. This
allows the Linux CAAM driver from dequeuing job faster than polling from
a register.
=> drivers: caam: add JR interruption only if CFG_CAAM_ITR=y

.azure-pipelines.yml, core/arch/arm/plat-rockchip/platform_config.h
Commit 60801696667d ("plat: arm: refactor GIC initialization") has
introduced a build regression for Rockchip:
$ make -s PLATFORM=rockchip-rk3399
core/arch/arm/plat-rockchip/main.c: In function ‘main_init_gic’:
core/arch/arm/plat-rockchip/main.c:29:29: error: ‘GICC_BASE’ undeclared (first use in this function); did you mean ‘GIC_BASE’?
29 |         gic_init(&gic_data, GICC_BASE, GICD_BASE);
|                             ^~~~~~~~~
|                             GIC_BASE
Fix that by defining GICC_BASE unconditionally as most platforms do.
=> plat-rockchip: rk3399: define GICC_BASE

mk/config.mk
The default log level of the TEE core is 1 (error), which means it is
normally silent. Set it to 2 (info) so that the boot sequence can be
seen (OP-TEE version banner, CPUs detected etc.).
=> core: set CFG_TEE_CORE_LOG_LEVEL to 2 (info) by default

core/arch/arm/plat-aspeed/platform_ast2600.c, core/drivers/crypto/aspeed/hace_ast2600.c, core/drivers/crypto/aspeed/hace_ast2600.h
These patch series include 2 parts:
1. Fix processing sequence wrong and typos
2. Lock HACE engine into Secure World
=> aspeed: crypto: fix digest incorrect problem

.azure-pipelines.yml
Removes build for CFG_FTRACE_SUPPORT=y, CFG_SYSCALL_FTRACE=y and
CFG_ULIBS_MCOUNT=y since they causes compile and link errors for GCC
version 11.2.0.
=> ci: azure: remove build for CFG_FTRACE_SUPPORT=y and CFG_ULIBS_MCOUNT=y

core/arch/arm/kernel/vfp_a32.S
Almost all Cortex-A processors come with a Floating-Point Unit (FPU)
and most also have a NEON unit. However, use of registers D16-D31 of
the VFP register file depends on the processor's FPU implementation.
Arm coprocessor access control register (CPACR.D32DIS) indicates if
FPU and Advanced SIMD is implemented. Check this bit to see if the
processor is supported or not.
Signed-off-by: Neal Liu <neal_liu@aspeedtech.com>
-----------------
Fix the issue of undefined instruction abort.
```
E/LD:  Call stack:
E/LD:   0x40112710
regression_1010.4 OK
o regression_1010.5 Invalid memory access 5
E/TC:0 0
E/TC:0 0 Core undef-abort at address 0x88002fd4
E/TC:0 0  fsr 0x00000000  ttbr0 0x8806786a  ttbr1 0x8806006a  cidr 0x2
E/TC:0 0  cpu #0          cpsr 0x400001df
E/TC:0 0  r0 0x880416c8      r4 …
```
=> arm: vfp_a32: check the existence of FPU NEON by CPACR

core/drivers/imx_ocotp.c
Initialize the OCOTP driver earlier with service_init() instead of
driver_init().
With CFG_CORE_HUK_SUBKEY_COMPAT=y, tee_fs_init_key_manager() and consequently
tee_otp_get_die_id() get executed earlier than the OCOTP driver
initialization. tee_fs_init_key_manager() is called by
service_init_late() routine.
On platforms featuring the OCOTP driver, the function
tee_otp_get_die_id() relies on the driver to be initialized.
=> drivers: imx_ocotp: initialize OCOTP driver earlier

core/arch/arm/mm/sp_mem.c, core/include/mm/sp_mem.h
Commit 8afe7a7c5220 ("core: rename mobj_get_cattr() to mobj_get_mem_type()")
renames the get_cattr() callback in struct mobj_ops(). However, sp_mem
wasn't updated as part of this change, so currently it doesn't compile.
Fix this and get aligned with the new naming.
=> core: sp_mem: fix get_cattr() callback name

.azure-pipelines.yml, MAINTAINERS
Nothing extra is needed yet from the OP-TEE side to run on these devices (we have been using the `am65x` flavor for these SoCs so far), but we are starting to add drivers that will have different configurations on these two devices. Add named support here.
=> Add AM64x and AM62x device support

core/arch/arm/plat-k3/drivers/sec_proxy.c, core/arch/arm/plat-k3/drivers/sec_proxy.h, core/arch/arm/plat-k3/drivers/sub.mk, core/arch/arm/plat-k3/drivers/ti_sci.c, core/arch/arm/plat-k3/drivers/ti_sci.h, core/arch/arm/plat-k3/drivers/ti_sci_protocol.h, core/arch/arm/plat-k3/main.c, core/arch/arm/plat-k3/platform_config.h, core/arch/arm/plat-k3/sub.mk
K3 HS devices have KEK embedded in them but it can't be extracted
directly due to security reasons. The system firmware provides us with a
Derived key encryption key (DKEK) which can be used for setting up the
HUK. 
For getting DKEK, we need the support of TI-SCI which in-turn
requires secure proxy driver for communicating with it. 
This patch series adds support for setting up HUK in OPTEE for 
K3 Generic SOCs.
K3 Lite devices aren't supported as of now.
Signed-off-by: Manorit Chawdhry <m-chawdhry@ti.com>
=> plat-k3: Setup HUK for K3 HS Generic SOCs

lib/libutee/include/tee_api_defines.h
The GlobalPlatform TEE Interbal Core API specification v1.3 has the
following text:
In TEE Internal Core API v1.2 and v1.2.1, TEE_ECC_CURVE_25519 and
TEE_ECC_CURVE_SM2 were incorrectly assigned the same identifier.
Indeed, both were 0x00000300. In v1.3, TEE_ECC_CURVE_SM2 is now
0x00000400. Update the code accordingly.
This is an API and ABI change, but note that this value is used only
in TEE_IsAlgorithmSupported(). Therefore, only TAs that dynamically
check for algorithm support at runtime may be impacted.
=> libutee: fix value of TEE_ECC_CURVE_SM2

mk/subdir.mk
This change enables adding the same directory several times to subdirs-y
in sub.mk without causing warnings. This means we can now use patterns
such as:
subdirs-$(CFG_FOO) += foobar
subdirs-$(CFG_BAR) += foobar
=> build: allow multiple occurrences of the same directory in subdirs-y

core/lib/libtomcrypt/acipher_helpers.h
Hey folks,
This PR fixes a compilation issue with `CFG_CRYPTO_ECC=n`.
Disabling `ECC` crypto does not disable the `LTC ECC` related declarations, so `CFG_CRYPTO_ECC=n` gives a compilation error.
=> core: libtomcrypt: Fix compilation issue with CFG_CRYPTO_ECC=n

core/drivers/crypto/caam/utils/utils_sgt.c
The cache operation of the SGT table in caam_sgt_derive() was wrong and
it did not take into account the CAAM "burst" defined by the value
CFG_CAAM_SGT_ALIGN.
The cache operation of the SGT table in caam_sgt_cache_op() is done
correctly however.
This patch adds caam_sgt_entries_cache_op() to do this operation and
avoid implementation errors.
Signed-off-by: Franck LENORMAND <franck.lenormand@nxp.com>
=> drivers: caam: fix cache operation on SGT table

core/arch/arm/plat-imx/link.mk
For some platforms like mx7ulpevk, the `UL` attribute for CFG_DRAM_BASE
is necessary to avoid the following error:
$ PLATFORM=imx-mx7ulpevk make uTee
core/mm/mobj.c: In function ‘mobj_init’:
./out/arm-plat-imx/include/generated/conf.h:222:64: warning: integer overflow in expression of type ‘int’ results in ‘-1644167168’ [-Woverflow]
222 | #define CFG_TZDRAM_START (0x60000000 - 0x01e00000 - 0x00200000 + 0x40000000)
|                                                                ^
However, this `UL` attribute prevents the shell from properly computing
the CFG_TZDRAM_START value :
$ PLATFORM=imx-mx7ulpevk make uTee
bash: (UL(0x60000000) - 0x01e00000 - 0x00200000 + 0x40000000): missing `)' (error token is "(0x60000000) - 0x01e00000 - 0x00200000 + 0x40000000)")
To address both issues, the …
=> core: imx: link: generate entry_point_address.txt for uTee image

core/include/drivers/gic.h
The mapped size for GIC distributor and cpu registers is currently
defined to the size used for GICv3. GICv2 doesn't need such large sizes,
in fact some platforms has the distributor and cpu registers next to
each other in the physical memory map. This causes an overlap that can
be confusing. Fix this by selecting a smaller size when a GICv2 is used
instead.
It should be noted GICC_DIR is at offset 0x1000 in the cpu interface so
this register will not be accessible, but this should not be a problem
since OP-TEE doesn't use that register.
=> core: decrease register size for gicv2

mk/config.mk
Adds CFG_OPTEE_REVISION_EXTRA (default: empty) which can be used to
append a custom string to the revision string shown in the boot banner.
A typical use case is build environments such as Yocto/OpenEmbedded
which check out a particular version of the optee_os repository and may
add patches on top. In this case the revision string is something like:
3.17.0-dev (gcc version ...
which doesn't give any information on what modifications are added and
therefore makes it difficult to know for sure if a deployed binary is
indeed the expected one (even more so when the build date is fixed via
SOURCE_DATE_EPOCH for reproducible builds).
CFG_OPTEE_REVISION_EXTRA allows to append a specific build identifier.
For example:
$ make CFG_OPTEE_REVISION_EXTRA=-mybuild_1234
would give: …
=> build: introduce CFG_OPTEE_REVISION_EXTRA

mk/config.mk
Fixup for a config issue brought by https://github.com/OP-TEE/optee_os/pull/5296.
=> mk: config.mk: fix dependency on CFG_SCMI_MSG_SHM_MSG

core/arch/arm/arm.mk, core/arch/arm/plat-amlogic/conf.mk, core/arch/arm/plat-d02/conf.mk, core/arch/arm/plat-hikey/conf.mk, core/arch/arm/plat-imx/conf.mk, core/arch/arm/plat-k3/conf.mk, core/arch/arm/plat-ls/conf.mk, core/arch/arm/plat-marvell/conf.mk, core/arch/arm/plat-mediatek/conf.mk, core/arch/arm/plat-poplar/conf.mk, core/arch/arm/plat-rockchip/conf.mk, core/arch/arm/plat-rpi3/conf.mk, core/arch/arm/plat-rzg/conf.mk, core/arch/arm/plat-sprd/conf.mk, core/arch/arm/plat-sunxi/conf.mk, core/arch/arm/plat-synquacer/conf.mk, core/arch/arm/plat-totalcompute/conf.mk, core/arch/arm/plat-uniphier/conf.mk, core/arch/arm/plat-versal/conf.mk, core/arch/arm/plat-vexpress/conf.mk, core/arch/arm/plat-zynqmp/conf.mk
A couple of patches to move common patterns from platform config to `core/arch/arm/arm.mk`.
=> Simplify setting of CFG_ARM64_core, CFG_ARM32_core, CFG_WITH_LPAE

core/arch/arm/plat-k3/main.c, core/arch/arm/plat-k3/platform_config.h
This patch introduces DDR setup for possible use of
CFG_CORE_DYN_SHM/dynamic shared memory on k3 platform.
Signed-off-by: Ivan Mikhaylov <ivan.mikhaylov@siemens.com>
=> plat-k3: Add DDR setup in k3 platform

core/drivers/imx_snvs.c
Hello,
Here are two fixes for silly mistakes in the SNVS driver.
These two problems have been found after testing on a 8mscale closed platform with OTP selected as a master key.
=> Fixes for the SNVS driver

core/drivers/sub.mk, core/drivers/xiphera_trng.c, core/kernel/dt_driver.c, lib/libutee/include/tee_api_defines_extensions.h
Adds support for Xiphera's XIP8001B true random number generator.
XIP8001B is a FPGA IP core that can be synthesized in FPGA devices to
provide TRNG source for device where it is missing like Xilinx Zynq-7000
and Xilinx Zynq MPSoC.
Co-developed-by: Atte Tommiska <atte.tommiska@xiphera.com>
---
Example device tree entries:
```
xiphera_trng_0: xiphera_trng@aaaa0000 {
compatible = "xiphera,xip8001b-trng";
status = "okay";
secure-status = "disabled";
reg = <0x0 0xaaaa0000 0x0 0x10000>;
clock-names = "S_AXI_ACLK";
clocks = <&zynqmp_clk 71>;
};
xiphera_trng_1: xiphera_trng@bbbb0000 {
compatible = "xiphera,xip8001b-trng";
status = "disabled";
secure-status = "okay";
reg = <0x0 0xbbbb0000  0x0 0x10000>;
clock-names = "S_AXI_ACLK"; …
```
=> drivers: xiphera_trng: Add support for XIP8001B TRNG

core/arch/arm/plat-ti/platform_config.h, core/arch/arm/plat-ti/sm_platform_handler_a15.c
This mirrors what is available as a ROM API. We implement this here as
OP-TEE's monitor replaces the ROM's monitor functions and we would like
to keep feature parity.
=> plat-ti: Add SM handler for setting AMBA IF in the WUGEN

core/arch/arm/plat-ti/conf.mk
When the hardware RNG is available we should also enable
the HWRNG PTA so we can use it from the REE.
=> plat-ti: Enable hardware RNG PTA

core/arch/arm/plat-ti/a9_plat_init.S, core/arch/arm/plat-ti/api_monitor_index_a15.h, core/arch/arm/plat-ti/api_monitor_index_a9.h, core/arch/arm/plat-ti/sm_platform_handler_a15.c, core/arch/arm/plat-ti/sm_platform_handler_a9.c, core/arch/arm/plat-ti/ti_pl310.c
Minor cleanup, extra header lines to scroll past were not adding anything.
=> plat-ti: Remove extra license text

core/arch/arm/plat-rockchip/conf.mk
Enables Arm Cryptography Extensions by default for the rk3399 SoC since
they are supported [1].
Link: [1] http://opensource.rock-chips.com/images/d/d7/Rockchip_RK3399_Datasheet_V2.1-20200323.pdf
=> plat-rockchip: rk3399: set CFG_CRYPTO_WITH_CE ?= y

core/arch/arm/kernel/entry_a32.S
With commit 528dabb28254 ("core: suppress text relocation on
stack_tmp_export") the stack pointer is calculated using a relative
address instead of based on an absolute address which is relocated with
ASLR enabled.
Prior to this on Armv7 we compensate for a relocation update for
stack_tmp_export_rel in reset_secondary() just after the stack pointer
was initialized. So now when the relocation update of stack_tmp_export_rel
is gone remove the compensating code too.
Fixes: 528dabb28254 ("core: suppress text relocation on stack_tmp_export")
=> core: armv7: fix ASLR error

core/arch/arm/plat-stm32mp1/drivers/stm32mp1_syscfg.c, core/arch/arm/plat-stm32mp1/pm/psci.c, core/arch/arm/plat-stm32mp1/stm32_util.h, core/drivers/clk/clk-stm32mp15.c
This change removes a deprecated API.
=> drivers: clk: remove stm32_clock_*() helpers

core/drivers/scmi-msg/clock.c, core/drivers/scmi-msg/voltage_domain.c
In order to make clock.c and voltage_domain.c compile on
64 bit architecture, we cannot use unsigned int in the
function prototype and size_t in the function definition.
Signed-off-by: Ludvig Pärsson <ludvig.parsson@axis.com>
=> drivers: scmi-msg: Fix parameter type

core/arch/arm/plat-stm32mp1/drivers/stm32mp1_syscfg.c, core/arch/arm/plat-stm32mp1/main.c, core/arch/arm/plat-stm32mp1/pm/psci.c, core/arch/arm/plat-stm32mp1/scmi_server.c, core/arch/arm/plat-stm32mp1/shared_resources.c, core/drivers/clk/clk-stm32mp15.c, core/include/drivers/stm32mp_dt_bindings.h
This P-R implements the use of the stm32mp_dt_bindings.h helper which was upstreamed but not used.
This header groups all the device tree bindings necessary to compile a particular platform. This way, drivers do not include some headers under compilation switches: they remain in this helper.
=> plat-stm32mp1: use stm32mp_dt_bindings.h helper

core/arch/arm/kernel/link.mk
Setting LANG=C before invoking the date command doesn't always result in
the "C" (English) locale being selected. The correct way is to set
LC_ALL. As explained in the locale(7) man page:
If the second argument to setlocale(3) is an empty string, "", for the
default locale, it is determined using the following steps:
1. If there is a non-null environment variable LC_ALL, the value of
LC_ALL is used.
2. If an environment variable with the same name as one of the
categories above exists and is non-null, its value is used for that
category.
3. If there is a non-null environment variable LANG, the value of LANG
is used.
Fixes: 3e2b963515c1 ("core: use C locale when generating the build date")
=> core: make sure build date is always in English

core/pta/attestation.c
There is assertion error in the attestation PTA when it comes to
deserialize the key. Here are the logs:
* regression_1037 Remote attestation
o regression_1037.1 Get public key
E/TC:? 0 assertion '!buf_sz' failed at core/pta/attestation.c:199 <deserialize_key>
E/TC:3 0 Panic at core/kernel/assert.c:28 <_assert_break>
E/TC:3 0 TEE load address @ 0xbe000000
E/TC:3 0 Call stack:
E/TC:3 0  0xbe0091b4
E/TC:3 0  0xbe024b5c
E/TC:3 0  0xbe02292c
E/TC:3 0  0xbe02fde4
E/TC:3 0  0xbe0300c4
E/TC:3 0  0xbe029a3c
E/TC:3 0  0xbe025e70
E/TC:3 0  0xbe0336e0
E/TC:3 0  0xbe007070
E/TC:3 0  0xbe0071ec
To reproduce the issue, you need a persistent storage and follow these
steps:
$ xtest 1037
*reboot the platform*
$ xtest 1037
When allocating the key buffer, the maximum buffer size is allocated
(1033 bytes) …
=> core: pta: attestation: fix buffer size for generated key

core/arch/arm/dts/sama5d2.dtsi
While checking for OP-TEE 3.18, found that the device-tree modifications
to enable the TCB were missing. Add missing status-okay line to enable
TCB1 for OP-TEE usage.
=> dts: sama5d2: Set TCB1 as secure

core/arch/arm/plat-stm32mp1/conf.mk, core/arch/arm/plat-stm32mp1/shared_resources.c, core/arch/arm/plat-stm32mp1/stm32_util.h, core/arch/arm/plat-stm32mp1/sub.mk, core/drivers/clk/clk-stm32-core.c, core/drivers/clk/clk-stm32mp15.c, core/drivers/stm32_shared_io.c, core/drivers/sub.mk, core/include/drivers/stm32_shared_io.h
This P-R introduce the use of the shared IO driver which use is to isolate the use of shared resources that aren't relevant for STM32MP13 platform.
Now, the use of such resources is under the CFG_STM32MP1_SHARED_RESOURCES compilation flag, which is disabled by
default but enabled for STM32MP15.
=> plat-stm32mp1: rework the use of shared resources

core/drivers/imx_snvs.c
The current implementation of snvs_get_security_cfg() for
imx8m platforms includes the read of SYS_SECURE_BOOT bit.
This fourth bit shows if the board boots from internal
ROM. This bit will reset to 1 for a board in the field
and 0 for a test chip.
The read of this bit is out of scope of the snvs_get_security_cfg()
purpose which is to return the system security configuration.
The SYS_SECURE_BOOT bit (msb) can be discarded.
Fixes: d0fa513dcef5 (drivers: imx_snvs: fix SNVS security configuration values)
Signed-off-by: Franck LENORMAND <franck.lenormand@nxp.com>
=> drivers: imx_snvs: re-work security state for imx8m platforms

core/arch/arm/plat-stm32mp1/conf.mk
Restores OP-TEE reserved shared memory (the last MBytes of DRAM located
on top of the secure DDR) in STM32MP15 default configuration. This
default configuration is needed to support latest mainline TF-A in conjunction
with mainline Linux kernel.
=> plat-stm32mp1: restore reserved shared memory

core/tee/tee_svc_cryp.c
op_attr_bignum_to_user() lacks a call to memtag_strip_tag() before it
calls vm_check_access_rights(). This results in the memory buffer not
being found and the function returning TEE_ERROR_ACCESS_DENIED.
Test case: xtest pkcs11_1019 on QEMUv8, build command:
make CFG_PKCS11_TA=y CFG_USER_TA_TARGET_pkcs11=ta_arm64 MEMTAG=y run
Fixes: ef142203a36b ("core: syscalls: strip tags from user space pointers")
=> core: crypto: mte: strip tag before calling vm_check_access_rights()

core/arch/arm/plat-zynqmp/main.c
Without the __nex_bss symbol added to gic_data and console_data
the zynqmp platform results in a deadlock when attempting
to write to the serial device on the platform.  This fix resolves
the deadlock issue.  More details can be found at this issue
link https://github.com/OP-TEE/optee_os/issues/5384
Signed-off-by: Michael Doran <michael.doran@dornerworks.com>
=> plat-zynqmp: Added __nex_bss symbol for virtualization support

core/drivers/imx_ocotp.c
Not all the imx platforms have the same bank spacing. In particular
the imx6 and imx7ulp both have bank sizes that are twice as large
as the imx8m.
This will set the correct computation.
Signed-off-by: Tim Anderson <tim.anderson@foundries.io>
=> imx_ocotp: correct ocotp fuse address computation
