OP-TEE/optee_os

core/drivers/crypto/caam/hal/common/registers/rng_regs.h
The i.MX6SX requires to start the RNG instantiation at a higher
entropy delay to provide a stable RNG generation and avoid RNG
hardware errors.
=> drivers: caam: increase the minimum entropy delay the imx6sx

.azure-pipelines.yml, core/arch/arm/plat-ls/conf.mk, core/arch/arm/plat-ls/crypto_conf.mk, core/arch/arm/plat-ls/platform_config.h
LS1012A-FRWY does not support OP-TEE anymore, removing its
support.
=> core: plat-ls: remove OP-TEE support for LS1012A-FRWY platform

core/arch/arm/plat-ls/conf.mk
core: plat-ls: correct expression CFG_NUM_THREADS ?= CFG_TEE_CORE_NB_CORE
There was no parenthesis around CFG_TEE_CORE_NB_CORE
when assigning it to CFG_NUM_THREADS, so corrected it.
=> core: plat-ls: correct expression CFG_NUM_THREADS ?= CFG_TEE_CORE_NB_CORE

core/arch/arm/plat-k3/conf.mk, core/arch/arm/plat-k3/platform_config.h
Only enable the SA2UL TRNG on platform flavors that are currently
supported. This can be relaxed for platforms as support is verified.
=> Disable SA2UL RNG driver on unsupported flavors

core/arch/arm/plat-k3/drivers/sa2ul_rng.c, core/arch/arm/plat-rcar/conf.mk, core/arch/arm/plat-rcar/hw_rng.c, core/arch/arm/plat-rcar/main.c, core/arch/arm/plat-stm/rng_support.c, core/crypto/rng_hw.c, core/drivers/atmel_trng.c, core/drivers/crypto/caam/caam_rng.c, core/drivers/crypto/se050/core/rng.c, core/drivers/dra7_rng.c, core/drivers/hi16xx_rng.c, core/drivers/imx_rngb.c, core/drivers/smccc_trng.c, core/drivers/stm32_rng.c, core/drivers/xiphera_trng.c, core/include/rng_support.h, core/pta/hwrng.c, mk/config.mk
When in the process of adding a new RNG driver, I noticed a couple oddities we have in the driver-side HW RNG API.
The normal way to implement a HW RNG driver is to override `hw_get_random_byte()`. The issue here is that all the supported RNG hardware outputs more than one byte at a time, leading to the need for buffering of bytes to be read out by this interface in the drivers. Reading out one byte at a time has a bit of a performance overhead, so instead several drivers also override `crypto_rng_read()` (which can read out multiple bytes in one call). Since all users of HW RNG read out in multiple bytes in a loop anyway, there is no need for this single byte API.
Switch all users of RNG over to only `crypto_rng_read()`. Have all drivers implement only `hw_get_random_bytes()`. When HW …
=> Unified hardware random number get bytes

core/arch/arm/dts/stm32mp15-pinctrl.dtsi, core/arch/arm/dts/stm32mp151.dtsi, core/arch/arm/dts/stm32mp153.dtsi, core/arch/arm/dts/stm32mp157.dtsi, core/arch/arm/dts/stm32mp157a-dk1.dts, core/arch/arm/dts/stm32mp157c-dk2.dts, core/arch/arm/dts/stm32mp157c-ed1.dts, core/arch/arm/dts/stm32mp157c-ev1.dts, core/arch/arm/dts/stm32mp15xx-dkx.dtsi, core/include/dt-bindings/gpio/gpio.h
Syncronize with STM32MP15 Device Tree files from Linux v5.19-rc6.
I've readded the etzpc node, disabled the rcc secure-status and removed the ressources related GPLv2 licensing model for all boards like in the previous bump of the stm32mp15 dts(i) files.
This update is required to add a new boards based on Linux 5.19-rc6
dts file.
Ping @etienne-lms as the STM32MP1 platform maintainer.
=> Update STM32MP15 Device Tree files to Linux 5.19-rc6

core/drivers/bcm_sotp.c, core/include/drivers/bcm_sotp.h, core/pta/bcm/sotp.c
- Added write support for bcm secure one time programmable fuses.
- bcm_iproc_sotp_mem_read() now takes in a bool value for sotp_add_ecc
instead of an int to denote if error checking memory is supported.
- Updated debug and error messages to return TEE_result codes.
Signed-off-by: Vahid Dukandar <vahidd@microsoft.com>
=> drivers: bcm_sotp: add sotp write support

.github/workflows/ci.yml
```
The code_style job runs checkpatch, which checks if commit references
found in commit descriptions are valid or not. In order for this to
work, the Git repo must contain the full history otherwise some IDs
might be reported as unknown. For example [1]:
WARNING: Unknown commit id '60801696667d', maybe rebased or not pulled?
#7:
- Commit 60801696667d ("plat: arm: refactor GIC initialization")
Link: [1] https://github.com/OP-TEE/optee_os/runs/7529955940?check_suite_focus=true#step:5:35
```
=> ci: code_style: clone repository with full history

core/arch/arm/plat-bcm/main.c
- Commit 60801696667d ("plat: arm: refactor GIC initialization")
refactored GIC initialization to have a virtual address lookup be
performed within gic_init_base_addr() instead of requiring a
platform's init_gic() to perform it.
- Before this change, BCM's main_init_gic() still performed the lookup
before calling gic_init_base_addr() and would hand over a virtual
address instead of a physical one. This caused the new virtual lookup
in gic_init_base_addr() to fail and panic.
- This change removes the virtual memory lookup in BCM's gic_init() and
has it hand gic_init_base_addr() a physical address instead.
=> core: plat-bcm: remove virtual address lookup from main_init_gic()

.github/workflows/ci-cancel.yml
When the CI workflow is triggered, we usually don't want previous jobs
related to the same branch or pull request to keep running; it is
just wasteful of resources. Therefore add a special workflow to deal
with the situation [1].
An exception is made for CI workflows started by updates to the master
branch so that several PR merged in a row do not cancel previous CI runs
started on master.
Link: [1] https://github.com/marketplace/actions/cancel-workflow-action#advanced-pull-requests-from-forks
=> ci: cancel obsolete workflows

core/drivers/imx_i2c.c
NXP drivers in both u-boot and linux waits 50us after enabling
the bus controller to stablize the bus.
Signed-off-by: Tim Anderson <tim.anderson@foundries.io>
=> drivers: imx_i2c: update the I2C initialization

core/tee/tee_svc.c
Add missing comma to fix the following error:
$ make -s PLATFORM=vexpress-qemu_armv8a CFG_TA_PAUTH=y CFG_MEMTAG=y
core/tee/tee_svc.c:371:9: error: expected ‘}’ before ‘{’ token
371 |         {
|         ^
core/tee/tee_svc.c:280:44: note: to match this ‘{’
280 | const struct tee_props tee_propset_tee[] = {
|                                            ^
Fixes: a0e8ffe9ba8f ("core: add support for MTE")
=> core: tee_svc.c: add missing comma

core/arch/arm/kernel/link.mk
binutils ld.bfd generates one RWX LOAD segment by merging several sections
with mixed R/W/X attributes (.text, .rodata, .data). After version 2.38 it
also warns by default when that happens [1], which breaks the build due to
--fatal-warnings. The RWX segment is not a problem for the TEE core, since
that information is not used to set memory permissions. Therefore, silence
the warning.
Link: [1] https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=ba951afb99912da01a6e8434126b8fac7aa75107
=> core: link: add --no-warn-rwx-segments

lib/libmbedtls/core/ecc.c
The ecc signature implementation must check that the output buffer
has sufficient space to store the signature. This check was missing
in the mbedtls version of ecc_sign.
Fixes: ad6cfae7c0 ("libmbedtls: support mbedtls ECC function")
Signed-off-by: Lars Persson <lars.persson@axis.com>
=> core: mbedtls: Add ecc signature size check

core/drivers/crypto/se050/crypto.mk, core/drivers/crypto/se050/glue/i2c.c
Platforms with secure I2C buses (i.e: STM32MP1) or those with only
a secure element on the bus might prefer not to delegate the I2C
traffic to the REE.
=> drivers: se050: optional I2C access via trampoline

mk/clang.mk
When building on an AArch64 host and using OP-TEE's build.git [1], the
AArch64 cross compiler prefix is "aarch64-linux-" instead of the usual
"aarch64-linux-gnu-". This happens due to [2]. Clang still expects
--target=aarch64-linux-gnu so for convenience map the prefix accordingly
in mk/clang.mk.
Link: [1] https://github.com/OP-TEE/build.git
Link: [2] https://github.com/OP-TEE/build/blob/3.18.0/toolchain.mk#L97
=> clang.mk: fix build on AArch64 host

lib/libutils/ext/include/util.h
This commit defines `get_field_u{32,64}()` and `set_field_u{32,64}()` macros for respectively getting and setting bit fields.
=> libutils: util.h: add get_field_u{32,64}() and set_field_u{32,64}()

core/arch/arm/kernel/link.mk, ldelf/link.mk, lib/libutee/arch/arm/utee_syscalls_a32.S, lib/libutils/ext/arch/arm/atomic_a32.S, lib/libutils/ext/arch/arm/mcount_a32.S, lib/libutils/isoc/arch/arm/arm32_aeabi_divmod_a32.S, lib/libutils/isoc/arch/arm/arm32_aeabi_ldivmod_a32.S, lib/libutils/isoc/arch/arm/setjmp_a32.S, ta/arch/arm/ta_entry_a32.S
Addressing https://github.com/OP-TEE/optee_os/issues/5471#issuecomment-1222621421.
=> Fix binutils 2.39 ld warning about missing .note.GNU-stack section and executable stack

core/arch/arm/plat-rcar/core_pos_a64.S
Due to mistake, cluster position wasn't shifted left if chip is not M3W. This
led to erroneous core ID calculation on chips that are not M3W. Actually, this
affected only H3, as only this chip has two clusters.
Fix this by always shifting x1 (cluster ID) to the left, before doing one
additional shift for non-M3W chips.
Fixes: 572afdce53ea ("plat: rcar: Derive core map from PRR")
Reported-by: Oleksandr Grytsov <oleksandr_grytsov@epam.com>
Tested-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com> (R-Car M3)
Tested-by: Oleksandr Grytsov <oleksandr_grytsov@epam.com> (R-Car H3)
=> plat: rcar: fix core pos calculation for H3 boards

core/arch/arm/dts/stm32mp157a-dhcor-avenger96.dts, core/arch/arm/dts/stm32mp157c-dhcom-pdk2.dts, core/arch/arm/dts/stm32mp15xx-dhcom-pdk2.dtsi, core/arch/arm/dts/stm32mp15xx-dhcom-som.dtsi, core/arch/arm/dts/stm32mp15xx-dhcor-avenger96.dtsi, core/arch/arm/dts/stm32mp15xx-dhcor-io1v8.dtsi, core/arch/arm/dts/stm32mp15xx-dhcor-som.dtsi, core/arch/arm/plat-stm32mp1/conf.mk
This pull request adds two sample baseboards based on our STM32MP1-based DHCOM and DHCOR SoMs to ease evaluation of our modular platform and customization for custom baseboards.
This is a follow up of https://github.com/OP-TEE/optee_os/pull/5459 with the additional Avenger96 board as second commit.
----------------------------------------
The dts(i) files are imported from Linux 5.19-rc6.
Changes made to the imported dts(i) files:
- Enable rcc as on other boards
- Allow iwdg2 for usage in non-secure world
Signed-off-by: Johann Neuhauser <jneuhauser@dh-electronics.com>
The dts(i) files are imported from Linux 5.19-rc6.
Changes made to the imported dts(i) files:
- Drop GPLv2 licensed resources and/or use their explicit values
- Drop cryp1 okay status as on other boards
- Drop unsupported …
=> plat-stm32mp1: add STM32MP1 based DHCOM/DHCOR SoMs on PDK2/Avenger96 baseboards

core/arch/arm/plat-stm32mp1/scmi_server.c, core/drivers/scmi-msg/voltage_domain.c, core/include/drivers/scmi-msg.h
plat_scmi_voltd_get_level is refactored to return an SCMI error code and
retrieve the voltage via an out parameter. This allows errors from the
platform SCMI server implementation to be propagated to the REE.
The implementation for stm32mp1 is updated to handle at least some
possible errors.
Signed-off-by: Anton Eliasson <anton.eliasson@axis.com>
=> drivers: scmi-msg: Propagate errors from platform voltd_get_level

core/arch/arm/plat-stm32mp1/pm/psci.c, core/include/dt-bindings/reset/stm32mp1-resets.h, core/include/dt-bindings/reset/stm32mp13-resets.h
Implements PSCI system reset support in STM32MP13 by using rstctrl API to reset the system rather than a SoC specific resource in plat-stm32mp1.
=> plat-stm32mp1: reset system using rstctrl device

lib/libutils/isoc/include/assert.h
This PR is used to fix ```static_assert``` issue in [issue 5502](https://github.com/OP-TEE/optee_os/issues/5502)
=> libutils:assert.h:add compiler check for static_assert

core/drivers/ls_sec_mon.c, core/drivers/sub.mk, core/include/drivers/ls_sec_mon.h
- This driver implements reading the entire NXP LX2160-series Security Monitor (SecMon) module.
- To enable the SecMon driver, the optee-os build requires the CFG_LS_SEC_MON flag.
=> core: drivers: nxp: Add LX series SecMon driver

core/arch/arm/kernel/thread_a64.S
When a foreign interrupt (non-secure) is trapped in OP-TEE the state of the current thread is saved similarly to when an RPC is performed.
With pointer authentication enabled two more registers which are part of the current context, APIAKEYHI-EL1 and APIAKEYLO-EL1, are added. These registers contains a key needed for pointer authentication. This key is unique per context so it must always be saved and restored when switching context.
Prior to this patch the step where this key is saved in the foreign interrupt handler was missing, so fix this by adding the missing step.
Fixes: 2b06f9dede33 ("Add basic pointer authentication support for TA's")
=> core: add missing pauth key saving in foreign interrupt handler

core/arch/arm/include/kernel/secure_partition.h, core/arch/arm/kernel/secure_partition.c
TF-A offers a mechanism to encapsulate an SP image and its manifest into an SP package and add that to the FIP. During boot BL2 will load these packages into memory and the SPMC manifest is used to pass the load addresses to the SPMC. 
https://trustedfirmware-a.readthedocs.io/en/v2.6/components/secure-partition-manager.html#secure-partition-packages
This is an alternate method to the current way of embedding the SPs into the OP-TEE binary. It makes integration of the system easier, since OP-TEE won't depend on the SPs images. At build time this means that we don't have to rebuild OP-TEE if an SP is changed, it only gets replaced in the FIP. Also, Hafnium (S-EL2 SPMC) uses the same FIP SP mechanism so adding this feature to OP-TEE reduces the fragmentation between the SPMC implementations.
=> FF-A: Enable loading Secure Partitions from the FIP

mk/config.mk, ta/ta.mk
The ffa.h file is needed by the OP-TEE test suite. Export it so it can
be used by it. The corresponding test PR can be found [here](https://github.com/OP-TEE/optee_test/pull/614) 
Signed-off-by: Jelle Sels <jelle.sels@arm.com>
=> ffa: Export ffa.h to be used by host

core/lib/libtomcrypt/src/modes/ctr/ctr_encrypt.c
Commit 8411e6ad673d ("Squashed commit upgrading to libtomcrypt-1.18.2-develop-20220913") is missing a local change in ctr_encrypt.c which should have been carried over from the previous import branch, see commit 5a913ee74d3c ("Squashed commit upgrading to libtomcrypt-1.18.2-develop-20180819"). The missing code is from commit c54b6344cc4e ("core: crypto: cleanup and fix CE accelerated AES CTR"). Most of that commit was made irrelevant after the move of accelerated code out of core/lib/libtomcrypt/src, except for the bits that touch ctr_encrypt() in core/lib/libtomcrypt/src/modes/ctr/ctr_encrypt.c.
Re-introduce the needed change. Fixes failures in xtest 4003 when CFG_CRYPTO_WITH_CE=y.
=> libtomcrypt: ctr_encrypt(): adjust for OP-TEE CE accelerated routines

.github/workflows/ci.yml
Adds a line to build and run regression tests with CFG_CRYPTO_WITH_CE=y. Many Armv8 CPUs support this extension so it is very commonly used and deserves to be tested here.
While we're at it, set CFG_TEE_CORE_LOG_LEVEL=0 at the beginning to avoid duplication.
=> ci: QEMUv8_check: also run tests with Cryptographic Extension enabled

core/crypto.mk, core/crypto/crypto.c, core/include/crypto/crypto.h, core/lib/libtomcrypt/ed25519.c, core/lib/libtomcrypt/src/pk/ec25519/sub.mk, core/lib/libtomcrypt/src/pk/ed25519/sub.mk, core/lib/libtomcrypt/src/pk/sub.mk, core/lib/libtomcrypt/sub.mk, core/tee/tee_svc_cryp.c, lib/libutee/include/tee_api_defines.h, lib/libutee/include/utee_defines.h, lib/libutee/tee_api_operations.c
This PR adds Ed25519 support as defined in GlobalPlatform TEE Internal Core API v1.3, using libtomcrypt as the backend crypto implementation.
Companion PR for optee_test: [#610](https://github.com/OP-TEE/optee_test/pull/610)
=> support Ed25519 sign/verify scheme

core/arch/arm/arm.mk, core/arch/arm/include/kernel/thread_arch.h, core/arch/arm/kernel/abort.c, core/arch/arm/kernel/asm-defines.c, core/arch/arm/kernel/boot.c, core/arch/arm/kernel/entry_a64.S, core/arch/arm/kernel/thread.c, core/arch/arm/kernel/thread_a64.S, core/arch/arm/kernel/thread_optee_smc_a64.S, core/arch/arm/kernel/thread_spmc_a64.S, core/arch/arm/kernel/unwind_arm64.c, core/include/kernel/thread.h, core/include/kernel/thread_private.h, core/kernel/thread.c, mk/config.mk
Previously pointer authentication was only supported for TAs. With this patch add a configuration option CFG_CORE_PAUTH to enable support for core. Each privileged thread has its own APIA key. There are also a separate APIA key for each physical core used when handling an abort or when using the tmp stack.
=> core: add pointer authentication support

core/lib/libtomcrypt/src/pk/ed25519/ed25519_make_key.c
For the same reasons as in commit 2d7740f6f44c ("core: libtomcrypt: Remove prng_state* NULL pointer check from x25519_make_key()"), remove the NULL pointer check in ed25519_make_key().
=> libtomcrypt: Remove prng_state* NULL pointer check from ed25519_make_key()

core/tee/tee_svc_cryp.c
The ECC curve is not an attribute of an Ed25519 key pair, let alone a mandatory one for key generation. It was mistakenly added by commit 03e07432b68f ("ta: pkcs11: Add Ed25519 support"), thus breaking xtest regression_4007_ed25519 (subcase .1 Generate Ed25519 key). Remove that attribute from the key type definition.
Fixes: 03e07432b68f ("ta: pkcs11: Add Ed25519 support")
=> core: crypto: remove TEE_ATTR_ECC_CURVE as an attribute of TEE_TYPE_ED25519_KEYPAIR

ta/pkcs11/src/processing.c, ta/pkcs11/src/processing_ec.c
Fix the issues with the key generation in 
https://github.com/OP-TEE/optee_test/pull/618
=> ta: pkcs11: Fix key generation for Ed25519

core/crypto/crypto.c, core/drivers/crypto/se050/core/storage.c, core/drivers/crypto/se050/crypto.mk, core/include/crypto/crypto.h, core/tee/tee_svc_storage.c
Keys created on the Secure Element NVM via the PKCS#11 TA are removed by scanning the data buffer holding the reference to the key during the release of the object.
The storage allocated to hold those keys (ECC/RSA) is always below the page size length which seems like a reasonable figure to use for future extensions.
This commit avoids scanning objects larger than that length.
Incidentally also fixes regression 6018: this test releases an object of size 0xA0000 which can't be scanned due to this part of the code hitting an OOM.
=> core: storage: improve SE05x deletion of NVM objects

CHANGELOG.md, core/arch/arm/plat-stm32mp1/conf.mk, mk/config.mk
=> Update CHANGELOG for 3.19.0 and collect Tested-by tags.

core/lib/libtomcrypt/ed25519.c
Fixes signature size value not properly set from caller argument in crypto_acipher_ed25519_sign() and crypto_acipher_ed25519ctx_sign().
Prior this patch could execution fail or not fail, depending on content previously loaded in siglen stack memory cell.
=> core: libtomcrypt: fix ed25519ctx signature

core/arch/arm/plat-stm32mp1/conf.mk, core/drivers/stm32mp15_huk.c, core/drivers/sub.mk
The algorithm used simplifies the device provisioning phase because
it does not require a unique per device secret to be fused: just a key
common to all devices.
The algorithm uses a 128 bit symmetric key stored as four 32 bit words
read from OTP fuses.
The HUK is calculated by AES-GCM encrypting the device UID (96 bits).
Since the UID is persistent - and so should be the key - the NONCE can
be reused and hold any value.
The OTP values must be secrets but don't need to be unique per-device.
=> plat-stm32mp15: generate HUK using an AES-GCM key from BSEC OTP

lib/libutils/ext/include/util.h
Some parenthesis are missing in the ROUNDUP_OVERFLOW expression. The macro can only return false.
=> libutils: util.h: fix the ROUNDUP_OVERFLOW macro

.github/workflows/ci.yml
Test compile optional Xiphera TRNG and HUK drivers (and its related
drivers).
---
Depends on:
- https://github.com/OP-TEE/optee_os/pull/5460
=> ci: zynqmp: Add compilation for optional drivers

core/kernel/ts_manager.c
Current session can not return NULL as panic() aborts the execution in that case.
=> core: remove invalid check

core/tee/fs_htree.c
init_head_from_data triggers a TA panic in case corrupt data is read from the secure storage, for instance by request from the PKCS#11 trusted application.
"Every Trusted Storage implementation is expected to return TEE_ERROR_CORRUPT_OBJECT if a Trusted Application attempts to open an object and the TEE determines that its contents (or those of the storage itself) have been tampered with or rolled back." See TEE Internal Core API Specification v1.1.2, section 5.7.1.
Signed-off-by: Joakim Nordell <joakim.nordell@axis.com>
=> Avoid panic in TEE core init_head_from_data

.github/workflows/ci.yml
When checkpatch reports issues, it returns an error status which make the code_style job fail as expected. However, by default when a job step fails the subsequent ones are not executed. Therefore, pycodestyle is skipped which is bad because we sometimes want to ignore some checkpatch errors and we still want to detect Python issues.
This problem is fixed by adding a condition to the "Run pycodestyle" step.
=> ci: code_style: run pycodestyle even if checkpatch has failed

core/arch/arm/plat-k3/conf.mk, core/arch/arm/plat-k3/platform_config.h
Add SA2UL and TRNG support for TI SoC AM62X through OP-TEE.
Signed-off-by: Kamlesh Gurudasani <kamlesh@ti.com>
=> plat-k3: am62x: add SA2UL and TRNG support

core/drivers/atmel_piobu.c, core/drivers/atmel_rstc.c, core/drivers/atmel_rtc.c, core/drivers/atmel_saic.c, core/drivers/atmel_shdwc.c, core/drivers/atmel_tcb.c, core/drivers/atmel_trng.c, core/drivers/atmel_wdt.c, core/drivers/clk/sam/sama5d2_clk.c, core/drivers/imx_i2c.c, core/drivers/imx_lpuart.c, core/drivers/imx_rngb.c, core/drivers/imx_uart.c, core/drivers/imx_wdog.c, core/drivers/ls_dspi.c, core/drivers/ls_gpio.c, core/drivers/ls_i2c.c, core/drivers/ls_sec_mon.c, core/drivers/pl011.c, core/drivers/pm/sam/at91_pm.c, core/drivers/serial8250_uart.c, core/drivers/xiphera_trng.c, core/include/kernel/dt.h, core/kernel/dt.c
In case where IP core device is TrustZone aware and is used by both REE
and TEE dt_map_dev() would normally cause non-secure mapping for the
device.
When selected registers in IP core are only accessible by TrustZone device
needs to be mapped with MEM_AREA_IO_SEC to cause actual AXI memory access
be made with AWPROT[1] and ARPROT[1] bits configured properly.
This adds new argument for dt_map_dev() to enable forcing mapping to be
secure or non-secure.
=> core: dt: Make it possible to alter device mapping

MAINTAINERS, core/arch/arm/plat-versal/conf.mk, core/drivers/sub.mk, core/drivers/versal_trng.c
Configure the TRNG driver to operate in Hybrid mode with derivative
function.
This driver was ported from its original FSBL implementation (1)
(1) https://github.com/Xilinx/embeddedsw
reference: https://github.com/OP-TEE/optee_os/pull/5426
=> drivers: versal: true random number generator

MAINTAINERS, core/arch/arm/plat-versal/conf.mk, core/drivers/sub.mk, core/drivers/versal_nvm.c, core/include/drivers/versal_nvm.h
Provide an interface to access the xilnvm service executing in the PLM firmware running on the Microblaze processor.
reference https://github.com/OP-TEE/optee_os/pull/5426 
=> drivers: versal: non volatile memory (eFuse and BBRAM)

core/kernel/dt.c
This change allows reg property to have value 0. The reg property can be used to describe an element that is not a physical address  but an offset and for which 0 is a valid value.
=> core: dt: allow null value in reg property

core/tee/tee_svc.c
Fixes a potential integer overflow in syscall_log(). Note that an eventual overflow would still be caught by copy_from_user(), but it's preferable to catch this earlier.
=> core: fix potential integer overflow in syscall_log()

core/arch/arm/plat-zynqmp/conf.mk, core/arch/arm/plat-zynqmp/platform_config.h
Adding support for the ZCU104 and ZCU106 boards since they possess the same core as the ZCU102. This is to avoid having the "flavour not supported error" when compiling for the ZCU104 and ZCU106
Tested succesfully on the ZCU106
=> Added ZCU104 and ZCU106 flavour support

core/kernel/ree_fs_ta.c
As soon as TA signature has been verified check that the total loaded size matches what is in the sign header. This prevents an eventual attacker from providing arbitrary values in the img_size field of the signed header.
=> core: ree_fs: check ta size early

MAINTAINERS, core/arch/arm/plat-versal/conf.mk, core/drivers/crypto/sub.mk, core/drivers/crypto/versal/authenc.c, core/drivers/crypto/versal/include/ipi.h, core/drivers/crypto/versal/ipi.c, core/drivers/crypto/versal/sub.mk
**Note/Update to the crypto: versal: authentication driver**
This driver uses the PLM xilsecure service to deliver authentication
functionality using AES-GCM.
The driver currently does not handle unaligned data and lengths; due
to this the corresponding xtest regression test will not pass
(regression 4005 in xtest).
To add more use cases, we developed this specific test
https://github.com/ldts/optee_os/blob/15d27821d6e561697cbc0603c90d93a2f7a59e11/core/drivers/crypto/versal/authenc_test.c 
(it shows support for multiple contexts and copy operations)
**AMD/Xilinx next release of the PLM software addresses the issue.**
reference
https://github.com/OP-TEE/optee_os/pull/5426
=> crypto: versal: AES 

core/arch/arm/include/ffa.h, core/arch/arm/include/kernel/secure_partition.h, core/arch/arm/kernel/secure_partition.c, core/arch/arm/kernel/spmc_sp_handler.c
Handle FFA_MEM_PERM_GET and FFA_MEM_PERM_SET interfaces for enabling SPs to query and set the access rights of their memory regions. These interfaces are only permitted in the initialization phase thus a new state variable is being introduced in sp_session. SPs indicate the end of their initialization phase through the FFA_MSG_WAIT interface.
Some tests have been added to the Trusted Services repo and can be found here: https://review.trustedfirmware.org/c/TS/trusted-services/+/17390
=> FF-A: Add support for FFA_MEM_PERM_GET/SET

core/include/drivers/stm32_gpio.h
Replace "Configuratioh" with "Configuration".
Signed-off-by: Ding Tao <miyatsu@qq.com>
=> core: include: Fix simple typo in drivers/stm32_gpio.h

core/arch/arm/include/kernel/thread_private_arch.h, core/arch/arm/kernel/stmm_sp.c, core/arch/arm/kernel/thread_a32.S
This P-R tries to fix an issue in StMM management in 32bit mode where CPU register USR_LR is not preserved in StMM execution context.
=> [RFC] StMM: 32bit mode requires cpu usr_lr to be preserved

core/arch/arm/kernel/stmm_sp.c
Changes StMM management to have zlib using default mempool to allocate buffers for StMM image decompression. This is useful as the process can require buffer of several kilobytes.
=> core: arm: stmm: use mempool to decompress stmm image

core/arch/arm/arm.mk, core/arch/arm/kernel/link_dummies_paged.c, core/arch/arm/kernel/secure_partition.c, core/arch/arm/kernel/thread_spmc.c, core/arch/arm/kernel/thread_spmc_a32.S, core/arch/arm/kernel/thread_spmc_a64.S, core/arch/arm/mm/mobj_ffa.c, core/arch/arm/mm/sp_mem.c
Configuration with pager and FF-A is currently not supported. Supporting this would require extensions to the FF-A specification to be able to load OP-TEE with paging enabled. So far we don't have any platforms with FF-A which are memory constrained enough that paging can be motivated. If this would change we'll have a good use case to test with when adding pager support for FF-A.
Currently we have a few pager annotations (DECLARE_KEEP_PAGER() and __*_unpaged) which are effectively unused. So save us from adding yet more unused annotations by removing the few we have in the FF-A specific code.
=> core: ffa: remove pager annotations

core/crypto/signed_hdr.c, core/drivers/crypto/crypto_api/acipher/rsa.c, core/include/kernel/thread.h, core/kernel/ree_fs_ta.c, core/lib/libtomcrypt/rsa.c, core/lib/libtomcrypt/src/pk/pkcs1/pkcs_1_pss_decode.c, core/lib/libtomcrypt/src/pk/rsa/rsa_verify_hash.c, core/sub.mk, core/tests/ftmn_boot_tests.c, core/tests/sub.mk, lib/libmbedtls/core/rsa.c, lib/libmbedtls/mbedtls/library/rsa.c, lib/libutils/ext/fault_mitigation.c, lib/libutils/ext/include/fault_mitigation.h, lib/libutils/ext/sub.mk, mk/config.mk
This is https://github.com/OP-TEE/optee_os/pull/5247 rebased and updated.
The use case is to make `buf_ta_open()` more resilient to fault injection attacks on the hardware, more specifically glitching attacks. The basic assumption is that glitch can cause one or more instructions in sequence to act as nops when executed. Anything can happen of course but I'm using this approximation to have something more concrete to work with.
The fault mitigations are supposed to add zero overhead unless enabled and if enabled have a  modest overhead.
In this PR I've made fault mitigations enabled by default with `CFG_CORE_FAULT_MITIGATION?=y` in `mk/config.mk`. Should it be disabled by default instead?
=> Fault mitigation

core/arch/arm/dts/stm32mp151.dtsi, core/arch/arm/dts/stm32mp157a-dk1.dts, core/arch/arm/dts/stm32mp157c-dk2.dts, core/arch/arm/dts/stm32mp157c-ed1.dts, core/arch/arm/dts/stm32mp157c-ev1.dts, core/arch/arm/dts/stm32mp15xx-dkx.dtsi, core/arch/arm/plat-stm32mp1/shared_resources.c
Changes in stm32mp15 DTSI files and ST boards DTS files without functional changes in generated images:
- Remove commented out gpio properties (stm32mp157c-ev1.dts)
- Disable nodes not consumed by optee (stm32mp157c-{dk1|dk2|ed1|ev1}.dts) 
- Sync gpio-z node name with linux dtsi files (stm32mp151.dtsi)
- Reorder node in board dts files (stm32mp157c-{dk1|dk2|ed1}.dts)
=> plat-stm32mp1: fixes in DTS files

core/tee/tee_svc_storage.c
Removes file local variable from syscall_storage_obj_open() that is not used.
=> core: tee_scv_storage: remove unused local variable

ldelf/ldelf.ld.S, ldelf/ldelf.mk, ldelf/start_rv64.S, ldelf/sub.mk, ldelf/ta_elf.c, ldelf/ta_elf_rel.c, lib/libutee/include/elf_common.h, lib/libutils/ext/include/confine_array_index.h
Added 64-bit riscv ldelf startup assembly and
parsing 64-bit elf files.
Tested-by: Liu Shiwei <liushiwei@eswincomputing.com>
=> ldelf: supports riscv ldelf startup and riscv TAs loading

core/arch/arm/kernel/boot.c, core/arch/arm/kernel/entry_a32.S, core/arch/arm/kernel/entry_a64.S, core/core.mk, core/include/kernel/boot.h, lib/libutils/isoc/stack_check.c, mk/config.mk, ta/arch/arm/user_ta_header.c, ta/ta.mk
This change add support for CFG_CORE_STACK_PROTECTOR and CFG_TA_STACK_PROTECTOR. This flag enable the compiler stack overflow protection feature -fstack-protector-strong and also generate random stack canary value on kernel boot and TA entry.
Weak function plat_get_random_stack_canary() should be override by platform to provide random stack canary value for the core kernel.
=> Add support for compiler stack protector

core/crypto.mk
Make LTC implementations of X25519 & Ed25519 algorithms available when crypto library is chosen to be mbedtls (which yet lacks support for these algorithms).
=> make X25519 & Ed25519 available for mbedtls configurations

lib/libutee/include/tee_api_compat.h, lib/libutee/include/tee_api_defines.h, lib/libutee/include/tee_internal_api.h, mk/config.mk, ta/mk/build-user-ta.mk, ta/mk/ta_dev_kit.mk
Updates the reported version to 1.3.1. Three new defines:
- TEE_CORE_API_REQUIRED_MAJOR_VERSION
- TEE_CORE_API_REQUIRED_MINOR_VERSION
- TEE_CORE_API_REQUIRED_MAINTENANCE_VERSION are added by the standard as a way for the TA to specify required version of the API. OP-TEE only supports downgrading to version 1.1.
A simplified OP-TEE specific method is also provided: Adds the configuration option CFG_TA_OPTEE_CORE_API_COMPAT_1_1 which enables TEE Internal Core API v1.1 compatibility for in-tree TAs.
The TA dev kit is also updated to recognize
CFG_TA_OPTEE_CORE_API_COMPAT_1_1 and set define
__OPTEE_CORE_API_COMPAT_1_1 to 1 if set.
These new defines does not do anything yet, but in following commits functions and types will be updated gradually until all functions and types changed in version …
=> Update reported version to GP Core Internal API v1.3.1

ta/pkcs11/src/processing.c
Minor mistake of printing key handle values after reset.
Signed-off-by: Sergiy Kibrik <Sergiy_Kibrik@epam.com>
=> ta: pkcs11: fix debug message

core/arch/arm/dts/fsl-lx2160a.dtsi, core/drivers/ls_sfp.c, core/drivers/sub.mk, core/include/drivers/ls_sfp.h
core: drivers: nxp: Add LX series SFP driver
- Implement reading and writing to the NXP LX2160-series Security Fuse
Processor (SFP).
- Add the CFG_LS_SFP flag to enable building the SFP driver.
- The SFP driver should be able to:
- Read the entire SFP.
- Read the debug level.
- Read the Intent to Secure (ITS) and Secure Boot (SB) flags.
- Read individual OEM Unique Scratch Pad Fuse (OUID) registers.
- Read individual Super Root Key Hash (SRKH) registers.
- Set the debug level.
- Set the device to permanently program the fuse block by
setting the ITS and SB flags.
- Set individual OUID registers.
- Get the status of the SFP driver itself.
- Update fsl-lx2160a device tree with sfp and gpio nodes.
Reviewed-by: Sahil Malhotra …
=> core: drivers: nxp: Add LX series SFP driver

ta/pkcs11/src/processing.c, ta/pkcs11/src/processing_asymm.c, ta/pkcs11/src/processing_digest.c, ta/pkcs11/src/processing_symm.c
> Sets session active processing mechanism type from init_symm_operation(),
> init_asymm_operation() and init_disgest_operation() rather than from
> their caller functions. No functional change.
During #5647 review I saw storage of `mecha_type` was not consistent accross functions. This P-R proposes to address that. @varder, may I ask you to have a look?
=> ta: pkcs11: save mechanism type on operation initialization

core/arch/arm/plat-totalcompute/fdts/optee_sp_manifest.dts
The default image offset is changed from 0x1000 to 0x4000 to accomodate the boot protocol information.
Signed-off-by: Davidson K <davidson.kumaresan@arm.com>
=> plat-totalcompute: change entrypoint of secure partition

lib/libutee/include/tee_api_defines.h
Clarifies that the used version in TEE Internal Core API is still v1.1. Changes the version defines back to v1.1.0.
=> libutee: clarify that the used version is still 1.1

.github/workflows/ci.yml
Now that optee_rust has been updated [1] ("qemu_v8: Pin optee_rust to the latest version"), drop the patch in ci.yml.
Link: [1] https://github.com/OP-TEE/manifest/commit/286184404963afc4b298dfd94e3463e00177cc45
=> ci: drop optee_rust patch

core/arch/arm/dts/stm32mp131.dtsi, core/arch/arm/dts/stm32mp135f-dk.dts, core/arch/arm/dts/stm32mp151.dtsi, core/arch/arm/plat-stm32mp1/main.c, core/drivers/stm32_bsec.c, core/include/drivers/stm32_bsec.h
Support the NVMEM layout that is used to describe OTP mapping in the device-tree.
This allows drivers to find an OTP location (BSEC word number and bit size) from the OTP string identifier, name of the cell in device tree. No more hardcoded OTP index :)
=> Support NVMEM layout for BSEC

MAINTAINERS, core/arch/arm/plat-versal/conf.mk, core/drivers/sub.mk, core/drivers/versal_puf.c, core/include/drivers/versal_puf.h
The Versal® device contains a physically unclonable function (PUF). The PUF creates a signature (or fingerprint) of each device that is unique to that device. The KEK can only be directly fed into the AES-GCM engine and cannot be read out of the device.
The KEK is 256 bits in length with 256 bits of entropy and is used to encrypt the users red key allowing its storage in black (encrypted) form. The black key can be stored in either eFUSEs, BBRAM, or external storage.
Enhanced from the previous generation, the Versal device PUF also outputs a user accessible unique ID that is cryptographically isolated from the PUF KEK despite using the same entropy source. While unique to each device, it is not considered a “secret” and does not have the same access protections as the KEK. …
=>  AMD/Xilinx Versal ACAP: Physical Unclonable Function

core/lib/libtomcrypt/ccm.c
aad_len and payload_len are of the type size_t which has a greater range than int which is used for the corresponding arguments when passed to ccm_init(). So to guard against wrapped or truncated values check that the variables can be in a int first before calling ccm_init().
Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>
=> core: add overflow checks in crypto_aes_ccm_init()

core/tee/tee_svc_cryp.c
Commit 0aaad418ac8b ("core: crypto: add Ed25519 support") introduced support for the ED25519 algorithm. This included parsing a TEE_ATTR_EDDSA_PREHASH parameter that unfortunately was not fully compliant with the standard.  So fix this with a more strict interpretation of TEE_ATTR_EDDSA_PREHASH as described in the specification.
Fixes: 0aaad418ac8b ("core: crypto: add Ed25519 support")
@varder FYI
=> core: crypto: fix TEE_ATTR_EDDSA_PREHASH interpretation

lib/libmbedtls/include/mbedtls_config_kernel.h
The wrong name of a configuration was used to test in mbedtls if the accelerated SHA-256 routines should be used. Fix this by using the correct name CFG_CORE_CRYPTO_SHA256_ACCEL instead.
Fixes: 2fc5dc95a949 ("core: mbedtls: use SHA-256 crypto accelerated routines")
=> core: mbedtls: fix use of SHA-256 crypto accelerated routines

core/kernel/tee_misc.c
Correct the function description of core_is_buffer_outside in comment.
Signed-off-by: Mark-PK Tsai <mark-pk.tsai@mediatek.com>
=> core: Correct the description of core_is_buffer_outside

core/arch/arm/dts/at91-sama5d27_som1.dtsi, core/arch/arm/dts/at91-sama5d27_som1_ek.dts, core/arch/arm/dts/at91-sama5d2_xplained.dts, core/arch/arm/dts/sama5d2.dtsi, core/drivers/atmel_rstc.c, core/drivers/atmel_shdwc.c, core/drivers/atmel_wdt.c
This series embeds multiple improvements for the sama5d2 support. It mainly target at improving secure status for multiple devices as well as enabling reboot on watchdog reset.
=> [plat-sam] sama5d2 improvements

lib/libutee/arch/riscv/sub.mk, lib/libutee/arch/riscv/utee_syscalls_rv.S
Add 64-bit RISC-V system call function of connection.
Signed-off-by: liushiwei <liushiwei@eswincomputing.com>
=> core: support RISC-V syscall

core/arch/arm/dts/stm32mp135f-dk.dts, core/drivers/stm32_bsec.c
Add a way for non-secure world to provision One Time Programmed resources using "st,non-secure-otp" device tree property.
=> Add BSEC otp provisionning

lib/libutils/isoc/include/assert.h
Changes assert() definition to return a (dummy) value when expression to true. This change allows to integrate external libraries which assume assert() conforms to such implementation, as found in GCC or LLVM toolchains.
=> libutils: change assert() to conform with stdlib implementation

.github/workflows/ci.yml, core/arch/arm/plat-stm32mp1/conf.mk, core/arch/arm/plat-stm32mp1/platform_config.h, core/drivers/stm32_bsec.c, core/drivers/stm32mp15_huk.c
Use of NVMEM layout in BSEC  driver instead of hardcoded OTP numbers.
=> drivers: stm32_bsec: use DT NVMEM layout API

lib/libutils/isoc/arch/riscv/setjmp_rv.S, lib/libutils/isoc/arch/riscv/sub.mk, lib/libutils/isoc/include/setjmp.h
- Add jmp buffer size and type for RISC-V in setjmp.h
- Implement `setjmp()` and `longjmp()` in setjmp_rv.S
=> riscv: Implement setjmp() and longjmp() for RISC-V

core/drivers/rstctrl/rstctrl.c, core/include/drivers/rstctrl.h, core/include/kernel/dt_driver.h, core/kernel/dt_driver.c
Add a way to differentiate missing properties from actual device tree errors when looking for a property.
=> Differentiate device tree property access error codes

core/arch/arm/tee/entry_fast.c
It took me a bit more time than it should have to troubleshoot an error on RockPi4 with `CFG_CORE_RESERVED_SHM=n`. The Linux kernel reports:
```
optee: probe of firmware:optee failed with error -22
```
(22 is `EINVAL`)
What happens with the RockPi4 build is, it doesn't register any memory range with `register_ddr()` and no DT is passed to OP-TEE by the bootloader either. Therefore, dynamic shm is disabled. So if reserved shm is disabled at compile time, there is no shared memory communication possible.
The two patches in this PR:
- Upgrade the existing `DMSG()` in `tee_entry_exchange_capabilities()` to `IMSG()`,
- Add similar `IMSG()` for virtualization and reserved shm,
- Panic the core if no shm is enabled.
=> Log capabilities on boot and check shared memory support

core/pta/scmi.c
Fixes a typo in config switch name CFG_SCMI_MSG_DRIVERS in SCMI PTA open session function.
Fixes: 7ff454421a8c ("core: pta: scmi: support SCP-firmware SCMI resources")
=> core: pta: scmi: fix typo in open session test

core/arch/arm/kernel/secure_partition.c
Commit 2e82874cc9b7922e000dd4d7718e3153e347b1d7 in Trusted Firmware-A slightly changes the SP package format in the FIP image. The new format is compatible with the previous version thus it is only necessary to allow the new version number on FIP SP load.
Signed-off-by: Imre Kis <imre.kis@arm.com>
=> core: sp: Allow v2 FIP package format

core/kernel/notif.c
Allows to use GIC_PPI interrupts for asynchronous notification.
This change replace macro COMPILE_TIME_ASSERT() with static_assert() as the former is deprecated.
=> core: notif: allow GIC_PPI usage for async notif

lib/libutee/include/pta_stm32mp_bsec.h
Fixes BSEC PTA API header file that did not mention possible error code TEE_ERROR_ACCESS_DENIED for command PTA_BSEC_CMD_READ_OTP.
Fixes: 4583de067b5d ("pta: stm32mp: add BSEC PTA")
=> pta: stm32mp: mention access denied error code in BSEC PTA API

core/arch/arm/plat-stm32mp1/conf.mk, core/arch/arm/plat-stm32mp1/main.c
This P-R enables full debug features if the board is not in secure-closed mode and CFG_TEE_CORE_DEBUG is enabled.
=> plat-stm32mp1: enable debug feature on non secure-closed chip

Makefile, mk/config.mk
This flag allows us to enable or disable building "User TAs". By disabling "User TAs" we could build "TA_DEV_KIT" without building TAs present in optee-os project under ta/*/user_ta.mk.
Signed-off-by: Julien Masson <jmasson@baylibre.com>
Signed-off-by: Balsam CHIHI <bchihi@baylibre.com>
Signed-off-by: Safae Ouajih <souajih@baylibre.com>
=> config: add CFG_BUILD_USER_TA flag

lib/libutils/ext/arch/riscv/atomic_rv.S, lib/libutils/ext/arch/riscv/sub.mk
Implement `atomic_inc32()` and `atomic_dec32()` in atomic_rv.S. The implementation is based on atomic addition instruction with acquire and release suffix to add additional memory order constraints.
=> libutils: riscv: provide atomic_rv.S

core/arch/riscv/kernel/boot.c, core/arch/riscv/kernel/entry.S, core/arch/riscv/kernel/sub.mk
Implement boot flow in boot.c and entry.S
**entry.S** provides core's single entry point for RV32/RV64 in S/M Modes. For now it performs: booting primary and secondary harts. Setting stack pointer, thread pointer (to `thread_core_local`), supervisor address translation and protection register, clearing BSS...etc and calls to appropriate functions to initialize the MMU and continue to boot flow from boot.c.
**boot.c** provides an implementation of `init_tee_runtime()`, `plat_primary_init_early()`, `boot_init_primary_early()`, `boot_init_primary_late()`, `boot_init_secondary()` and helper functions.  For now `init_sec_mon()` is kept to be replaced later by a routine to initialize SBI implementation (to for example, probe for available SBI extensions).
=> riscv: kernel: implement boot flow for RISC-V

.github/workflows/ci.yml, core/drivers/crypto/se050/adaptors/utils/utils.c
Converting the OID watermarked value to a bignum removes the first byte if this is different than zero.
The failing case observed the value 0x57.72.15.66.1a.f2.9d.00 being retrieved as 0x57.72.15.66.1a.f2.9d after having been transformed into a bignum and back to its original binary value.
This will cause cryptographic operations to fail as the secured keys and objects become not addressable.
=> crypto: drivers: se050: fix generation of oid values

core/drivers/crypto/se050/core/ecc.c
In order to support P-521 (132 byte {r,s} pairs), the buffer storing the DER signature must be large enough.
Tested with:
`$ xtest -l 2 -t pkcs11 1019
`
=> drivers: crypto: se050: increase DER signature buffer

mk/compile.mk
Add -Ulinux and -Uunix to dtb-cppflags to fix two corner cases, where DTS file might contain properties like following:
dma_coherent: coherent {
compatible = "shared-dma-pool";
linux,dma-default;
}
Without these flags, C preprocessor will modify "linux,dma-default" to "1,dma-default"
Thanks jerome.forissier for quickly identifying the root cause.
=> mk/compile.mk: add -Ulinux -Uunix to dtb-cppflags

core/arch/arm/dts/stm32mp13-pinctrl.dtsi, core/arch/arm/dts/stm32mp135f-dk.dts
Unused peripherals shouldn't be supported at board level for STM32MP13.
=> dts: stm32: clean device tree for STM32MP13

ta/avb/entry.c
Should close object created for reading, so better use seek and then close the object.
Fixes: b29b41950 ("ta: add AVB TA")
Signed-off-by: Ivan Khoronzhuk <ivan.khoronzhuk@globallogic.com>
=> ta: avb: fix object leakage at lock state write

lib/libutils/isoc/bget_malloc.c
Add missing calls to strip_tag() ins raw_malloc_buffer_overlaps_heap() and raw_malloc_buffer_is_within_alloced(). Without them pointer arithmetic cannot work. Fixes xtest 1001.1 (make check MEMTAG=y).
=> libutils: mte: add missing calls to strip_tag()

core/arch/riscv/include/kernel/arch_scall.h, core/arch/riscv/include/kernel/thread_arch.h, core/arch/riscv/include/kernel/thread_private_arch.h, core/arch/riscv/include/riscv.h, core/arch/riscv/include/riscv_macros.S, core/arch/riscv/kernel/abort.c, core/arch/riscv/kernel/arch_scall.c, core/arch/riscv/kernel/arch_scall_rv.S, core/arch/riscv/kernel/asm-defines.c, core/arch/riscv/kernel/cache_helpers_rv.S, core/arch/riscv/kernel/sub.mk, core/arch/riscv/kernel/thread_arch.c, core/arch/riscv/kernel/thread_rv.S
Summary of changes:
- Introduce helper macros to load/store a range registers from/to a base register at a given offset. It uses LDR and STR macros defined in riscv.h for respectively RV32 and RV64. Offsets are shifted by `RISCV_XLEN_BYTES`.
- Exceptions un/masking
- Trap handling, including syscalls handling.
- Thread allocation, execution, suspension, freeing with slight changes to set RISC-V registers such as CSRs.
-  An entry point of trap handler in non-vectored mode. `thread_unwind_user_mode()` and `thread_exit_user_mode()` to return from U-Mode.
-  `__thread_enter_user_mode()` to jump to U-Mode from S-Mode or M-Mode.
-  `thread_std_smc_entry` and `thread_resume()` to transfer execution to the desired routine.
- Introduce a new function `thread_return_from_nsec_call()` to return to …
=> riscv: kernel: initial implementation of thread management routines for RISC-V 

core/drivers/ls_sfp.c, core/include/drivers/ls_sfp.h
- The LX series manual specifies that fusing the SFP can take up to 100ms to complete.
- The fuse timeout in the LS SFP driver should be changed to 150ms so that the possible 100ms timeout has a buffer to interpret errors.
=> core: drivers: nxp: update LX series SFP fuse timeout

core/drivers/ls_sfp.c, core/include/drivers/ls_sfp.h
- The Intent to Secure (ITS) and Secure Boot (SB) flags are written to a given pointer in ls_sfp_get_its() and ls_sfp_get_sb() respectively.
- The written values are equivalent to the entire masked OSPR0 and OSPR1 registers.
- The two functions should instead update a pointer with a boolean integer containing the bit shifted value of the desired flag.
=> core: drivers: nxp: bit shift the ITS and SB bits when reading the SFP

core/arch/arm/plat-versal/conf.mk, core/drivers/crypto/versal/crypto.mk, core/drivers/crypto/versal/ecc.c, core/drivers/crypto/versal/rsa.c
The crypto driver API provides an extra indirection level to enable different ciphers.
Since Versal ACAP supports acipher and authenc, enable them.
=> versal: enable the crypto driver

core/arch/arm/kernel/secure_partition.c, core/include/kernel/user_mode_ctx_struct.h, core/kernel/ldelf_loader.c, ldelf/include/ldelf.h, ldelf/main.c, ldelf/ta_elf.c, ldelf/ta_elf.h, scripts/ts_bin_to_c.py
This pull request introduces support for an SPMC agnostic SP format. In order to make it easier to implement support for this format, a simple flat binary format was chosen so it won't require an ELF loader. The SPMC only has to copy the SP binary into an RWX memory area then it can jump to its entry point. The access rights of different sections of the SP can be set by either via the load relative memory region definitions of the SP manifest or by invoking the `FFA_MEM_PERM_SET` FF-A interface from the SP during the boot phase. Setting up the stack, clearing the .bss section, handling relocations, etc. are all handled by the SP startup code.
The ELF format SPs remain supported by OP-TEE. The SP loader can distinguish between the two formats by the `legacy-elf-format` field of the SP …
=> Introduce binary format SP support

core/arch/arm/plat-vexpress/conf.mk
Configure `plat-vexpress` to build the PKCS#11 TA by default and select the default TA target of `vexpress-qemu_armv8a` to be `ta_arm64`.
=> plat-vexpress: enable PKCS#11 TA by default

lib/libutee/include/utee_defines.h
The CAAM driver relies on TEE_ALG_GET_MAIN_ALG() macro to retrieve the main algorithm ID from the TEE_ALG_* value.
With the addition of TEE_ALG_SHAKE128 and TEE_ALG_SHAKE256, TEE_ALG_GET_MAIN_ALG() would return 0x01 (TEE_MAIN_ALGO_MD5) and 0x02 (TEE_MAIN_ALGO_SHA1). These returned values are wrong.
Add TEE_MAIN_ALGO_SHAKE128 and TEE_MAIN_ALGO_SHAKE256 values for respectively TEE_ALG_SHAKE128 and TEE_ALG_SHAKE256.
@jforissier I'm not sure about the `TEE_MAIN_ALGO_SHAKE` values tho ...
=> libutee: add TEE_MAIN_ALGO_SHAKE values

core/kernel/tpm.c
Fixes build warning (trace message below) when CFG_CORE_TPM_EVENT_LOG=y.
=> core: tpm: fix syntax in trace message

lib/libutee/arch/arm/arm32_user_sysreg.txt
Adds CNTVCT to user system registers. Needed when compiling with CFG_CORE_SEL2_SPMC=y and CFG_MEMTAG=y.
=> libutee: add CNTVCT to user system registers

core/arch/arm/plat-stm32mp1/main.c, core/arch/arm/plat-stm32mp1/shared_resources.c, core/drivers/clk/clk-stm32mp15.c, core/drivers/rstctrl/stm32_rstctrl.c, core/drivers/stm32_bsec.c, core/drivers/stm32_etzpc.c, core/drivers/stm32_gpio.c, core/drivers/stm32_rng.c, core/drivers/stm32_uart.c
T***w***o patches to remove tests on CFG_DT and CFG_EMBED_DTB in stm32mp1 platform and drivers.
**_(edited)_**
=> plat-stm32mp1: remove code for when DT is not supported

lib/libutils/ext/pthread_stubs.c, lib/libutils/ext/sub.mk
When building with GCC 11.3.1 [1], the linker reports undefined symbols in the C++ test TA:
```
$ make 2>&1 | grep -E "(in function|undefined reference)" | sed 's@.*/@@'
libstdc++.a(eh_alloc.o): in function `(anonymous namespace)::pool::free(void*) [clone .constprop.0]':
gthr-default.h:749: undefined reference to `pthread_mutex_lock'
gthr-default.h:779: undefined reference to `pthread_mutex_unlock'
libstdc++.a(eh_alloc.o): in function `(anonymous namespace)::pool::allocate(unsigned long) [clone .constprop.0]':
gthr-default.h:749: undefined reference to `pthread_mutex_lock'
gthr-default.h:779: undefined reference to `pthread_mutex_unlock'
libgcc_eh.a(unwind-dw2-fde-dip.o): in function `__gthread_mutex_lock':
gthr-default.h:749: undefined reference to `pthread_mutex_lock' …
```
=> libutils: add stubs for pthread functions

mk/lib.mk
To add link flags for a shared library, a makefile variable is used that is called lib-ldflags$(libuuid). That's incorrect because the UUID is not enough to uniquely identify a shared library in the build. For example when both 32-bit and 64-bit user space is generated there are two versions of the shared library with the same UUID. It is not a problem at the moment because lib-ldflags$(libuuid) is used only for one target: ta_arm64, but fix this anyways so that the variable may be used for more complex cases.
=> build: mk/lib.mk: use full path to shared library in flags variable

core/crypto/crypto.c, core/include/crypto/crypto.h, core/lib/libtomcrypt/ed25519.c, core/tee/tee_svc_cryp.c
The software implemetation of ED25519 algorithm has a memory leak in the key and keypair allocation. Upon every public key allocation, a key pair is allocated (public and private components). When freeing the public key, only the public component is freed. To reproduce the issue:
$ while xtest 4016; do :; done
Until the following error:
* regression_4016 Test TEE Internal API ED25519 sign/verify E/LD:  copy_section_headers:1124 sys_copy_from_ta_bin E/TC:? 0 ldelf_init_with_ldelf:131 ldelf failed with res: 0xffff000c /usr/src/debug/optee-test/master.imx-r0/host/xtest/regression_4000.c:6062: xtest_teec_open_session(&session, &crypt_user_ta_uuid, ((void *)0), &ret_orig) has an unexpected value: 0xffff000c = TEEC_ERROR_OUT_OF_MEMORY, expected 0x0 = TEEC_SUCCESS
regression_4016 FAILED
To fix …
=> core: crypto: fix memory leak in Ed25519 support

core/arch/arm/kernel/boot.c, core/arch/arm/kernel/entry_a32.S, core/arch/arm/kernel/entry_a64.S, core/arch/arm/kernel/link_dummies_paged.c, core/arch/arm/kernel/secure_partition.c, core/include/kernel/boot.h
At boot TF-A passes two DT addresses (HW_CONFIG and TOS_FW_CONFIG), but currently only the HW_CONFIG address is saved, the other one is dropped. This commit adds functionality to save the TOS_FW_CONFIG too, so we can retrieve it later. This is necessary for the CFG_CORE_SEL1_SPMC use case, because the SPMC manifest is passed in this DT.
=> core: ffa: add TOS_FW_CONFIG handling

core/drivers/crypto/caam/acipher/caam_rsa.c
Check if original buffer is large enough for a result of RSA PKCS_V1_5 decryption operation.
With this change PKCS11 variable length buffers are supported for all RSA operations:
- Crypto API checks it for PKCS_V1_5 and OAEP encryptions.
- OAEP decryption already supports it.
This fixes: https://github.com/OP-TEE/optee_os/issues/5841
=> core: drivers: crypto: caam: Check PKCS_V1_5 decryption buffer size

core/kernel/tee_ta_manager.c
Problem: in the case of no UTA running, the buffer of dump_ctx will be allocated with 0 size and passed to init_dump_ctx(). That causes buffer overrunning.
Solution: Check buffer size before allocate the buffer. If it's 0, return TEE_ERROR_ITEM_NOT_FOUND.
Tested-by: Weizhao Jiang <weizhaoj@amazon.com>
=> core: fix out-of-bounds access of dump_ctx

core/arch/arm/mm/core_mmu_v7.c, core/arch/arm/plat-stm32mp1/conf.mk, core/arch/arm/plat-stm32mp1/platform_config.h, core/drivers/clk/clk-stm32mp15.c
Few changes it optimize a bit resident memory size when using pager.
=> plat-stm32mp1: pager resident size optims

lib/libutee/tee_api_arith_mpi.c
With the Widevine v17/v18 OPKs using their new Provisioning 4.0 technique, this pool size needs to be increased to 14Kb from 12Kb.
The sequence that is being executed that requires this is as follows:
1. TEE_GenerateKey(key_handle, 2048, NULL, 0)
2. TEE_GetObjectBufferAttribute(key, TEE_ATTR_RSA_MODULUS, modulus_data, &modulus_len), same for TEE_ATTR_RSA_PUBLIC_EXPONENT and TEE_ATTR_RSA_PRIVATE_EXPONENT.
3. mbedtls_rsa_complete() on a pk object created from the extracted modulus, public exp and private exp.
=> libutee: increase MPI_MEMPOOL_SIZE to 14Kb

ldelf/ldelf.mk, ldelf/sub.mk, ldelf/syscalls_rv.S
Added 32-bit and 64-bit RISC-V ldelf system calls.
=> ldelf: syscall: support RISC-V ldelf sycall

core/arch/arm/plat-imx/conf.mk, core/arch/arm/plat-imx/registers/imx8ulp.h, core/arch/arm/plat-imx/registers/imx93.h, core/drivers/imx/mu/sub.mk, core/drivers/imx_ele.c, core/drivers/sub.mk, core/include/drivers/imx_mu.h
Hello,
In this PR, I add the driver for the secure enclave available on i.MX8ULP and i.MX93, aka EdgeLock Enclave, aka ELE.
To start, we only enable some basic functionalities. Cryptographic features will come later.
Thanks!
Clement
=> Add EdgeLock Enclave driver for i.MX8ULP and i.MX93

core/arch/arm/include/kernel/secure_partition.h, core/arch/arm/kernel/secure_partition.c, core/arch/arm/kernel/thread_spmc.c
The FF-A spec doesn't forbid multiple SPs to have the same UUID. This makes it possible to use the FF-A UUID as a identifier for the protocol on top of the FF-A layer.
To achieve this we have to make sure that the FFA_PARTITION_INFO_GET can return more then one endpoint id if we pass a UUID. To make sure that there is no collision between the SP binaries names, we distinguish between the FF-A UUID and the SP UUID. The SP UUID is used to identify the SP itself. While the FF-A UUID is used as part of the FF-A protocol.
Build changes can be found [#636](https://github.com/OP-TEE/build/pull/636)
This is a follow-up on [#5650](https://github.com/OP-TEE/build/pull/603)
=> core: ffa: Allow multiple SPs with same UUID

core/pta/attestation.c
To reproduce (any 64bits platform will do):
$ make PLATFORM=imx-mx8mmevk CFG_ATTESTATION_PTA=y CFG_WERROR=y
core/pta/attestation.c: In function ‘cmd_get_pubkey’: core/pta/attestation.c:358:30: warning: initialization of ‘uint32_t *’ {aka ‘unsigned int *’} from incompatible pointer type ‘size_t *’ {aka ‘long unsigned int *’} [-Wincompatible-pointer-types]
358 |         uint32_t *e_out_sz = &params[0].memref.size;
|                              ^
core/pta/attestation.c:360:30: warning: initialization of ‘uint32_t *’ {aka ‘unsigned int *’} from incompatible pointer type ‘size_t *’ {aka ‘long unsigned int *’} [-Wincompatible-pointer-types]
360 |         uint32_t *n_out_sz = &params[1].memref.size;
|                              ^
=> pta: attestation: fix compilation incompatible pointer warning

core/kernel/tee_ta_manager.c
Problem: In some concurrent cases, ta dump will try to dump a TA which has not completed TA initialization and the TA stack pointer isn't set. That causes a data abort when accessing its stack.
Solution: Check the user TA initialization is completed or not. If it is still being initialized, return TEE_ERROR_BAD_STATE. https://github.com/OP-TEE/optee_os/issues/5905
Tested-by: Weizhao Jiang <weizhaoj@amazon.com>
=> core: check TA initialization completion before dump it

core/arch/arm/plat-imx/drivers/tzc380.c
Remove duplicated call to driver_init().
The previous driver_init() call would only initialize the driver. The new driver_init() call initializes the driver and its power management callback.
Fixes: 97eb916803fe ("drivers: imx: tzc380: re-configure TZ380 upon PM resume")
=> core: imx: remove duplicate driver_init() call

core/drivers/crypto/crypto_api/acipher/ecc.c
Adds TEE_TYPE_SM2_DSA_SM3_PUBLIC_KEY to
drvcrypt_asym_alloc_ecc_public_key() and adds
TEE_TYPE_SM2_DSA_SM3_KEYPAIR to drvcrypt_asym_alloc_ecc_keypair(). Adds support for TEE_MAIN_ALGO_SM2_DSA_SM3 in ecc_sign and ecc_verify.
=> drivers:crypto:add support for SM2_DSA_SM3

core/drivers/crypto/caam/acipher/sub.mk, core/drivers/crypto/caam/hal/common/hal_ctrl.c, core/drivers/crypto/caam/include/caam_acipher.h, core/drivers/crypto/caam/include/caam_hal_ctrl.h
Hello,
Here is a quick rework for the CAAM `crypto.mk` that was IMO cumbersome to read.
@ldts Let me know that configuration is still compatible with SE050 configuration.
With that, I did some minor fixes on CAAM compilation flags.
Thanks!
=> CAAM compilation fix

core/arch/arm/plat-zynqmp/main.c, core/arch/arm/plat-zynqmp/platform_config.h
Updates GICC_OFFSET to account for the already-offset GIC_BASE. Additionally initializes the interrupt controller with a pointer to the interrupt chip.
Fixes #5949
=> plat-zynqmp: fixes interrupt controller

core/crypto.mk, core/drivers/crypto/caam/crypto.mk
Follow-up : https://github.com/OP-TEE/optee_os/pull/5937
=> drivers: caam: disable CFG_CRYPTO_SM2_* when ECC CAAM driver is enabled

ta/pkcs11/include/pkcs11_ta.h, ta/pkcs11/src/pkcs11_token.c
When token has been initialized make sure that SO is properly authenticated based on authentication mode setting to follow PKCS#11 2.40 specification for `C_InitToken()`.
This makes it impossible to change authentication mode with `C_InitToken()`.
To enable authentication mode switching add logic to `C_SetPIN()` operation but require that token has been initialized but user PIN is not yet set.
---
Example sequence without the fix in place to demonstrate the problem:
```
root@qemuarm64-secureboot:~# dmesg | grep optee
[    5.718771] optee: probing for conduit method.
[    5.724213] optee: revision 3.20 (8e74d476)
[    5.731371] optee: dynamic shared memory is enabled
[    5.789814] optee: initialized driver
root@qemuarm64-secureboot:~# pkcs11-tool --module /usr/lib/libckteec.so.0 …
```
=> ta: pkcs11: Fix token initialization's authentication

.github/workflows/ci.yml, core/drivers/i2c/atmel_i2c.c, core/drivers/i2c/i2c.c
Fixes I2C bus driver and atmle_i2c driver regarding function fdt_reg_base_address() and fdt_get_status() labels change in commit [1].
Fixes: f354a5d8f98e ("core: replace _fdt_ prefix with fdt_ for device tree API")
=> drivers: i2c: fix fdt_xxx() function label

core/drivers/crypto/caam/acipher/caam_ecc.c, core/drivers/crypto/crypto_api/acipher/ecc.c, core/drivers/crypto/crypto_api/include/drvcrypt_acipher.h, core/drivers/crypto/se050/core/ecc.c, core/drivers/crypto/versal/ecc.c
For **Elliptic Curve**, the cryptographic api can fallback to its software
operation instead of failing due to the lack of hardware support.
The relevant code can be see seen in key allocation functions for 
the [public](https://github.com/OP-TEE/optee_os/blob/c4cab13e43f8170575612892f66bdbc8c9e67285/core/crypto/crypto.c#L709) and [private](https://github.com/OP-TEE/optee_os/blob/c4cab13e43f8170575612892f66bdbc8c9e67285/core/crypto/crypto.c#L727) keys
crypto_api/acipher/ecc.c (i.e [pair]( https://github.com/OP-TEE/optee_os/blob/c4cab13e43f8170575612892f66bdbc8c9e67285/core/drivers/crypto/crypto_api/acipher/ecc.c#L348) ) however does not pass the key type to 
the relevant driver and therefore the driver can not take the correct
action at allocation time.
This commit addresses that …
=> crypto_api: ecc allocation api

core/arch/arm/plat-sam/sam_sfr.c, core/drivers/atmel_piobu.c, core/drivers/atmel_rstc.c, core/drivers/atmel_rtc.c, core/drivers/atmel_shdwc.c, core/drivers/atmel_wdt.c, core/drivers/clk/clk-stm32mp15.c, core/drivers/crypto/stm32/authenc.c, core/drivers/crypto/stm32/cipher.c, core/drivers/crypto/stm32/stm32_cryp.c, core/drivers/i2c/atmel_i2c.c, core/drivers/i2c/i2c.c, core/drivers/imx_lpuart.c, core/drivers/imx_uart.c, core/drivers/pl011.c, core/drivers/rstctrl/rstctrl.c, core/drivers/rstctrl/stm32_rstctrl.c, core/drivers/serial8250_uart.c, core/drivers/stm32_iwdg.c, core/drivers/stm32_tamp.c, core/include/drivers/clk_dt.h, core/include/drivers/i2c.h, core/include/drivers/rstctrl.h, core/include/kernel/dt.h, core/include/kernel/dt_driver.h, core/kernel/console.c, core/kernel/dt.c, core/kernel/dt_driver_test.c
Moves so-called dt_driver related declarations and definitions from dt.h to dt_drivers.h. Incidentally adds an inline description to enum dt_driver_type. This change clarifies when a source file shall include dt.h and/or dt_driver.h.
This change updates driver source files to include none, one or both of these header files where applicable.
=> core: dt_driver: move related content from dt.h to dt_driver.h

core/arch/arm/include/arm.h, core/arch/arm/include/arm64.h, core/arch/arm/kernel/secure_partition.c
Add support for discovering if the CRC32 instruction family is implemented by the PE.
Convey this information to Secure Partitions through the SP manifest DT.
=> CRC32 HW support discovery

core/arch/riscv/kernel/boot.c
This patch adds "unsigned long tos_fw_config" as second parameter for RISC-V's boot_init_primary_late() to solve compilation error.
=> core: riscv: kernel: Fix compilation error with missing parameter

core/drivers/cbmem_console.c, core/drivers/sub.mk, core/include/drivers/cbmem_console.h, core/kernel/console.c
This adds a CBMEM console driver which gets the cbmem address from a device tree with the coreboot table information.
=> drivers: add cbmem console driver

core/arch/arm/plat-imx/conf.mk, core/arch/arm/plat-ls/conf.mk, core/crypto.mk, core/drivers/crypto/caam/crypto.mk, core/drivers/crypto/caam/sub.mk, mk/config.mk
Hello,
This PR combines the re-work of the CAAM crypto configuration file for i.MX/LS and the move of CFG_WITH_SOFTWARE_PRNG definition from mk/config.mk to mk/crypto.mk.
The latter allows the HW Crypto driver to overide the default CFG_WITH_SOFTWARE_PRNG value. Let me know what you think about this change.
Thanks!
=> Re-work CAAM Crypto configuration file + move CFG_WITH_SOFTWARE_PRNG definition

core/drivers/crypto/se050/adaptors/apis/sss.c
Symmetric keys should be compared in constant time to protect against side channel attacks.
=> crypto: se050: compare symmetric keys in constant time

.github/workflows/ci.yml, core/kernel/thread.c
With CFG_FTRACE_SUPPORT=y CFG_ULIBS_MCOUNT=y CFG_SYSCALL_FTRACE=y (tested on QEMUv8), OP-TE boot hangs do to infinite recursion:
ftrace_enter()
get_fbuf()
thread_get_id_may_fail()
_mcount()
ftrace_enter()
...
Break the cycle by tagging thread_get_id_may_fail() with __noprof.
=> Fix issues with CFG_SYSCALL_FTRACE=y

core/arch/riscv/include/encoding.h, core/arch/riscv/include/riscv.h
The "CSR_XXX" definitions are not only used for pure assembly code, but also used for inline assembly in C code. But using SHIFT_U64() in inline assembly will lead to compilation error, since this macro casts value to (uint64_t) first.
For example, "read_csr(CSR_XSTATUS)" will be expanded by pre-processor as "csrr a5,(((uint64_t)(1)<<(8))|0x000)", which is not acceptable for assembly language.
Fix this by using UINT64_C macro instead, since it suffixes the value with ULL instead of C type.
=> core: riscv: Fix macro for inline assembly

core/arch/arm/include/sm/optee_smc.h, lib/libutils/ext/include/bitstring.h, mk/config.mk
Patches extracted from https://github.com/OP-TEE/optee_os/pull/5793 and all ready reviewed (R-b tag applied).
=> bit_ffs_from() + fix typo in notif inline comment

core/arch/riscv/kernel/entry.S
The RISC-V privileged specification defines that at least one hart must have a hart ID of zero. Since at least one stack_tmp_stride is required for calculating the initial SP value for each hart, the formula should be address of stack_tmp plus (hartid+1) multiplied by stack_tmp_stride.
This commit fixes the formula for initializing SP of each hart, otherwise the stack underflow happens to hart 0. Also we remove some unused local data.
=> core: riscv: kernel: Fix stack pointer initialization for each hart

core/include/kernel/thread_private.h, lib/libutee/include/elf.h
RV64 also uses kern_sp. The elf.h is also used by RV32 and RV64.
=> Add missing conditional compilation for RISC-V

core/arch/riscv/kernel/boot.c
The thread core local stacks should be initialized when the primary core performs system initialization.
Fixes: ca82589 ("core: split core/arch/arm/kernel/thread.c")
=> core: riscv: kernel: Add missing initialization for core local stacks

.clang-format
Adds a configuration file to be used with clang-format. This file was copied from the Linux kernel, but with the ForEachMacros updated for OP-TEE.
Clang-format can help with formatting the code, but we are not expecting follow it to the letter.
=> [RFC] clang-format: add configuration file

mk/compile.mk
Adds the two warning options -Wpacked-not-aligned and -Waddress-of-packed-member to the default compiler flags.
=> Add warning options relating to packed structs

lib/libutils/ext/include/compiler.h, lib/libutils/isoc/arch/arm/arm32_aeabi_divmod.c
Some toolchain build optee_os with "-fstack-protector-strong", But the generated codes add "check stack" operations after the "ret_idivmod_values", which overwrite the r1 value.
So __aeabi_uidivmod/__aeabi_idivmod will got error value,
Bug: https://github.com/OP-TEE/optee_os/issues/6007
=> Disable stack protector for __aeabi_uidivmod/__aeabi_idivmod

core/arch/arm/dts/sama5d2.dtsi, core/arch/arm/plat-sam/conf.mk, core/drivers/pinctrl/atmel_pio.c, core/drivers/pinctrl/pinctrl.c, core/drivers/pinctrl/sub.mk, core/drivers/sub.mk, core/include/drivers/pinctrl.h, core/include/kernel/dt_driver.h, core/kernel/dt_driver.c, mk/config.mk
Add pinctrl support code for device-tree parsing and to allow drivers to apply pin muxing configuration based on the `pinctrl-<x>`and `pinctrl-names`. Also add a PIO driver for the sama5d2 pin muxing controller that provides a way to apply these configurations. This support will be used for the upcoming mcp16502 I2C connected PMIC support.
=> drivers: pinctrl: add device-tree pinctrl support 

core/arch/riscv/plat-virt/conf.mk, core/arch/riscv/riscv.mk
In RISC-V, each platform may have different supported ISA extensions, ABI, and code model.
In the first commit, we define the default variables of ISA extensions, ABI, and code model in RISC-V core Makefile `riscv.mk`.
In the second commit, we show that how the virt platform overrides the ISA in its `conf.mk`.
=> RISC-V: Add Makefile variables for platform ISA, ABI, and code model

.github/workflows/ci.yml, core/arch/arm/include/ffa.h, core/arch/arm/include/kernel/secure_partition.h, core/arch/arm/include/kernel/spmc_sp_handler.h, core/arch/arm/include/kernel/thread_spmc.h, core/arch/arm/kernel/entry_a64.S, core/arch/arm/kernel/secure_partition.c, core/arch/arm/kernel/spmc_sp_handler.c, core/arch/arm/kernel/thread_spmc.c, core/arch/arm/kernel/virtualization.c, core/arch/arm/mm/mobj_ffa.c, core/include/kernel/virtualization.h, core/include/mm/core_mmu.h, core/include/mm/mobj.h, core/mm/core_mmu.c
=> FF-A and virtualization

core/arch/riscv/kernel/thread_arch.c, core/arch/riscv/plat-virt/main.c
Fixes itr_core_handler() reference in RiscV architecture that was renamed interrupt_main_handler() in commit referred below.
Fixes: 358bf47c0612 ("core: interrupt: rename itr_core_handler()")
=> core: riscv: fix interrupt_main_handler() reference

core/include/drivers/pinctrl.h
Fixes pinctrl_free_state() when CFG_DRIVERS_PINCTRL is disabled as the API function has no return value.
The issue is reported by GCC with an error trace like the below:
core/include/drivers/pinctrl.h: In function ‘pinctrl_free_state’: lib/libutee/include/tee_api_defines.h:117:43: error: ‘return’ with a value, in function returning void [-Werror=return-type]
117 | #define TEE_ERROR_NOT_SUPPORTED           0xFFFF000A
|                                           ^~~~~~~~~~
core/include/drivers/pinctrl.h:158:16: note: in expansion of macro ‘TEE_ERROR_NOT_SUPPORTED’
158 |         return TEE_ERROR_NOT_SUPPORTED;
|                ^~~~~~~~~~~~~~~~~~~~~~~
In file included from core/include/drivers/stm32_uart.h:10,
from core/arch/arm/plat-stm32mp1/main.c:14:
core/include/drivers/pinctrl.h:156:6: …
=> drivers: pinctrl: fix stubbed pinctrl_free_state()

lib/libutee/arch/riscv/utee_syscalls_rv.S
In RISC-V, "j" instruction has R_RISCV_JAL relocation that can represent an even signed 21-bit offset (+-1MiB). However, this range is not enough to be position independent code, and the linker generates linking error. Fix it by using "tail" instruction which has R_RISCV_CALL_PLT relocation that the execution can jump to +-2GB location.
Note that we won't return from _utee_panic(), that's why we use "tail" instead of "call" instruction so that we won't generate redundant return instruction.
=> libutee: riscv: Fix relocation type of function call into __utee_panic()

core/drivers/stm32_gpio.c, core/include/drivers/stm32_gpio.h
Adds an helper function (dt_stm32_gpio_bank()) to register GPIO banks in stm32_gpio driver based on DT pinctrl nodes. GPIO banks are registered in a local list from which will be later used to find a bank based on its ID number. The function is expected to be called from the driver probe sequence. The function ensures a bank is not registered twice.
This P-R is a preparatory patch for moving stm32_gpio driver to pinctrl (`CFG_DRIVERS_PINCTRL`) and gpio (`CFG_DRIVERS_GPIO`) frameworks.
=> drivers: stm32_gpio: helper function to register GPIO banks

core/arch/arm/plat-stm32mp1/shared_resources.c, core/arch/arm/plat-stm32mp1/stm32_util.h
Removes platform function stm32mp_gpio_bank_is_shared() that is not used.
=> plat-stm32mp1: remove unused stm32mp_gpio_bank_is_shared()

core/drivers/stm32_rng.c
Checks RNG data ready status bit before each read of a 32bit sample from the RNG FIFO. Indeed the data ready status bit tells that the RNG FIFO contains random bytes by burst of 32bit word, not by burst of 4 32bit words.
=> drivers: stm32_rng: fix case when RNG is not ready

core/arch/arm/plat-stm32mp1/main.c
Adds inclusion of stm32_gpio.h from main.c that is needed when CFG_STM32MP13 is enabled.
=> plat-stm32mp1: add missing inclusion of stm32_gpio.h

core/include/drivers/gpio.h
Adds a `.put` operation handler in `struct gpio_ops` for a GPIO consumer driver to be able to release the GPIO resources it has allocated when getting its GPIO using a DT drvier GPIO provider (`gpio_dt_alloc_pin()`). This is needed for example, when such a consumer driver must defer its probe sequence hence release resources as it will be probed again later and will request again its GPIO resources.
=> gpio framework: add a put operator

core/drivers/atmel_piobu.c, core/drivers/clk/clk-stm32-core.c, core/drivers/clk/clk-stm32mp15.c, core/drivers/clk/sam/at91_clk.h, core/drivers/clk/sam/at91_pmc.c, core/drivers/gpio/gpio.c, core/drivers/i2c/atmel_i2c.c, core/drivers/pinctrl/atmel_pio.c, core/drivers/rstctrl/stm32_rstctrl.c, core/include/drivers/clk_dt.h, core/include/drivers/gpio.h, core/include/drivers/i2c.h, core/include/drivers/pinctrl.h, core/include/drivers/rstctrl.h, core/include/kernel/dt_driver.h, core/kernel/dt_driver.c, core/pta/tests/dt_driver_test.c
Renames struct dt_driver_phandle_args to struct dt_pargs to shorten the label and prevent ugly line breaks in function signatures.
=> core: rename dt_driver_phandle_args to dt_pargs

core/arch/arm/kernel/abort.c, lib/libunw/unwind_arm64.c, scripts/symbolize.py
The MTE tag is not really useful when displaying a crash dump. In fact it makes it more complicated for tools like script/symbolize.py to retrieve the actual (untagged) virtual address, especially as we now support non-Arm architectures and therefore blindly stripping the MTE bits is not possible.
This commit strips the tag in call stacks displayed by print_stack_arm64(). It also removes it from the virtual address shown on abort (__print_abort_info()) since symbolize.py does try to resolve the address as symbol + offset ; but in this case the tagged address is printed as well, because it can be helpful to diagnose tag check faults.
=> arm64: memtag: strip tag from crash dumps

core/arch/riscv/include/riscv.h, core/arch/riscv/kernel/abort.c, core/arch/riscv/kernel/asm-defines.c, core/arch/riscv/kernel/entry.S, core/arch/riscv/kernel/sub.mk, core/arch/riscv/kernel/thread_rv.S, core/arch/riscv/kernel/unwind_rv.c, core/arch/riscv/riscv.mk, lib/libunw/include/unw/unwind.h, lib/libunw/sub.mk, lib/libunw/unwind_riscv.c, scripts/symbolize.py
This patch sets implement the kernel stack unwinding for RISC-V architecture.
The detail can be found in the commit message of [libunw: Implement RISC-V stack unwinding](https://github.com/OP-TEE/optee_os/commit/904034a75ccf31c59831f23cf704dd6012aa5eb6)
=> RISC-V: Implement stack unwinding

core/drivers/stm32_gpio.c
Get output data pin configuration from DT node property "output-high" and "output-low".
This P-R is a preparatory patch for moving stm32_gpio driver to pinctrl (`CFG_DRIVERS_PINCTRL`) and gpio (`CFG_DRIVERS_GPIO`) frameworks.
Checkpatch emits a warning message because a field of existing `struct stm32_gpio` is named `od` (which reflect the related GPIO configuration register GPIO_ODR described in the SoC reference manual):
```
cbdf0432a drivers: stm32_gpio: consider DT output data configuration
WARNING: 'od' may be misspelled - perhaps 'of'?
#52: FILE: core/drivers/stm32_gpio.c:306:
+			ref->active_cfg.od = odata;
^^
total: 0 errors, 1 warnings, 0 checks, 35 lines checked
=> drivers: stm32_gpio: consider DT output data configuration

core/drivers/pinctrl/pinctrl.c
Changes pinctrl_get_state_by_name() to return TEE_ERROR_ITEM_NOT_FOUND instead of TEE_ERROR_GENERIC when an pinctrl state index is not found in the DT.
Fixes: 9aec039ec0d7 ("drivers: pinctrl: add pinctrl support")
=> drivers: pinctrl: pinctrl name may not be found

core/arch/arm/plat-stm32mp1/main.c, core/arch/arm/plat-stm32mp1/stm32_util.h, core/drivers/stm32_gpio.c
Adds local helper function `stm32_gpio_get_bank()` in stm32_gpio driver to remove stm32mp1 platform functions `stm32_get_gpio_bank_clock()`, `stm32_get_gpio_bank_clk()` and `stm32_get_gpio_bank_base()`.
=> plat-stm32mp1: repelace 2 stm32mp1 platform helper function with a driver local one

core/include/kernel/interrupt.h, core/kernel/interrupt.c
3 patches extracted from https://github.com/OP-TEE/optee_os/pull/5954:
"core: interrupt: interrupt_get_main_chip() returns main controller":
@jenswi-linaro review tag applied (https://github.com/OP-TEE/optee_os/pull/5954#issuecomment-1577972865).
"core: interrupt: rename internal itr_chip to itr_main_chip"
@jenswi-linaro review tag applied (https://github.com/OP-TEE/optee_os/pull/5954#issuecomment-1570403576).
"core: interrupt: add inline descriptions":
@jenswi-linaro review tag applied (https://github.com/OP-TEE/optee_os/pull/5954#pullrequestreview-1462257113).
=> itr_chip drivers: get main chip + main chip renaming + add inline descriptions

core/arch/arm/plat-stm32mp1/main.c, core/drivers/stm32_gpio.c
Fixes STM32MP13 sequence that default configures GPIO as non-secure from `set_all_gpios_non_secure()` registered at `early_init_late` initcall level, that is at same level driver are initially probed by dt_driver framework. This result on `set_all_gpios_non_secure()` possibly needing a bank resource before it is probed. Fix that by removing initcall function `set_all_gpios_non_secure()` and default configuring GPIO pins for STM32MP13 variant on their GPIO bank registering.
Fixes: 077d486ef09d ("drivers: stm32_gpio: add helper function stm32_gpio_get_bank()")
=> plat-stm32mp1: fix default setting GPIO as non-secure

core/include/kernel/dt_driver.h, core/kernel/dt_driver.c
2 patches extracted from https://github.com/OP-TEE/optee_os/pull/5954:
"core: dt_driver: define interrupt controller drivers identifier":
@jenswi-linaro review tag applied (https://github.com/OP-TEE/optee_os/pull/5954#issuecomment-1570403576).
"core: dt_driver: add helper for old fashion interrupt bindings"
@jenswi-linaro review tag (https://github.com/OP-TEE/optee_os/pull/5954#pullrequestreview-1464333713) is NOT YET applied as I squashed in a fix (https://github.com/OP-TEE/optee_os/pull/5954#discussion_r1219294494).
=> itr_chip drivers: dt_driver resources for interrupts bindings

ta/ta.mk
`commit 5489e94f0566 ("core: ffa: add boot info structs and defines")` causes the compiler error below in host applications.
```
ffa.h:196:41: error: implicit declaration of function ‘U’ [-Werror=implicit-function-declaration]
196 | #define FFA_BOOT_INFO_NAME_LEN          U(16)
|                                         ^
ffa.h:319:19: note: in expansion of macro ‘FFA_BOOT_INFO_NAME_LEN’
319 |         char name[FFA_BOOT_INFO_NAME_LEN];
|                   ^~~~~~~~~~~~~~~~~~~~~~
ffa.h:319:14: error: variably modified ‘name’ at file scope
319 |         char name[FFA_BOOT_INFO_NAME_LEN];
|              ^~~~
```
`ffa.h` uses the `U` macro which is only part of OP-TEE's libc and not a standard macro. This causes a compiler error when compiling a host application and the libc is provided by the …
=> ffa: remove ffa.h from host export list

mk/aosp_optee.mk, ta/mk/ta_dev_kit.mk
For AOSP environment to build user static libraries, there are two issues we had met,
1. the static library is default writing to the current source folder which is not allowed by AOSP build environment.
2. the static library is not necessarily installed to vendor lib folder like a TA or a shared library.
Propose to use `$(out-link-dir$(sm))` (passed by `$O`) to place the generated user static library, and change LOCAL_MODULE_CLASS to STATIC_LIBRARIES for it in AOSP build to avoid unnecessarily installation.
=> mk: Support user static lib for aosp build

core/arch/arm/include/ffa.h, core/arch/arm/include/kernel/secure_partition.h, core/arch/arm/kernel/boot.c, core/arch/arm/kernel/secure_partition.c
Implement the FF-A v1.1 boot protocol for passing boot info to Secure Partitions.
=> FF-A v1.1 boot protocol for SPs

core/arch/riscv/riscv.mk
The -mxxx and -Wxxx are not preprocessor flags. Fix it by defining them as C flags.
=> core: riscv: Fix misuse of cppflags

core/arch/arm/include/mm/core_mmu_arch.h, core/arch/arm/mm/core_mmu_lpae.c, core/arch/arm/mm/core_mmu_v7.c, core/arch/riscv/include/mm/core_mmu_arch.h, core/include/mm/core_mmu.h, core/mm/core_mmu.c
This PR is initiated from the discussion in https://github.com/OP-TEE/optee_os/issues/5725
To decouple the architecture specific address translation rule from core mm.
The `next_level` filed is added in the `struct core_mmu_table_info` to represent the next finer grained level.
Some ARM is also modified based on this change.
=> core: mm: Refine architecture specific translation level

core/drivers/atmel_piobu.c, core/drivers/clk/clk-stm32-core.c, core/drivers/clk/clk-stm32mp15.c, core/drivers/clk/clk_dt.c, core/drivers/clk/sam/at91_clk.h, core/drivers/clk/sam/at91_pmc.c, core/drivers/gpio/gpio.c, core/drivers/i2c/atmel_i2c.c, core/drivers/pinctrl/atmel_pio.c, core/drivers/pinctrl/pinctrl.c, core/drivers/rstctrl/stm32_rstctrl.c, core/drivers/stm32_gpio.c, core/include/drivers/clk_dt.h, core/include/drivers/gpio.h, core/include/drivers/i2c.h, core/include/drivers/pinctrl.h, core/include/drivers/rstctrl.h, core/include/kernel/dt_driver.h, core/kernel/dt_driver.c, core/pta/tests/dt_driver_test.c
Changes dt_driver callback function to return a `TEE_Result` value and pass retrieved device reference by a output argument rather than the opposite.
This change updates _dt_driver.c_, _dt_driver.h_, _dt_driver_test.c_ and all drivers implementing related dt_driver callback functions.
As a consequence, this change removes all type definition related to device specific callback handler function types which are useless as all these now comply with type `dt_driver_probe_func` defined in _dt_driver.h_.
This P-R is related to discussion thread https://github.com/OP-TEE/optee_os/pull/5954#discussion_r1211837322.
=> core: dt_driver: swap TEE_result and retrieved device reference

core/drivers/atmel_saic.c, core/drivers/gic.c, core/drivers/hfic.c, core/include/kernel/interrupt.h, core/kernel/interrupt.c
5 patches etracted from https://github.com/OP-TEE/optee_os/pull/5954 + a fixup patch (for an added change not proposed in that reference P-R: sanity test on pageable attribute of interrupt handling resources) to propose new interrupt management API functions that can be used on CPU main interrupt controller as well as on secondary interrupt controllers.
=> core: interrupt: new interrupt API functions

MAINTAINERS
LS1021A and LS1012A-FRWY is not supported anymore, their support was removed in the past.
=> MAINTAINERS: Layerscape: remove unsupported platforms

scripts/symbolize.py
The script will crash if the xxx.elf file can not be found.
Here is a example
```sh
/optee/optee-qemu-v8/optee_os/scripts/symbolize.py -d /optee/optee-qemu-v8/out-br/build/optee_examples_ext-1.0/test_ta/ta/out/
```
```
D/TC:0 0 abort_handler:530 [abort] abort in User mode (TA will panic)
E/TC:? 0 
E/TC:? 0 User mode data-abort at address 0x0 (translation fault)
E/TC:? 0  esr 0x92000045  ttbr0 0x400000e1a3000   ttbr1 0x00000000   cidr 0x0
E/TC:? 0  cpu #0          cpsr 0x20000100
E/TC:? 0  x0  0000000000000000 x1  000000000000004c
E/TC:? 0  x2  0000000000000000 x3  0000000040015d90
E/TC:? 0  x4  0000000000000001 x5  0000000000000001
E/TC:? 0  x6  00000000fffffffe x7  00000000ffffffff
E/TC:? 0  x8  0000000000000001 x9  0000000040015ad8
E/TC:? 0  x10 0000000000000038 x11 0000000000000000 …
```
=> scripts/symbolize.py: Fix crash when .elf file not found

core/drivers/stm32_bsec.c
This P-R fixes incorrect timeouts initialization
=> drivers: stm32_bsec: fix timeouts initialization

core/arch/riscv/include/riscv.h, core/arch/riscv/kernel/arch_scall.c, core/arch/riscv/riscv.mk, ldelf/main.c, ldelf/ta_elf.c, ldelf/ta_elf.h, lib/libutee/arch/riscv/utee_syscalls_rv.S
This PR adds support for TA stack unwinding on RISC-V architecture.
To test it, `TEE_Panic(0)` is invoked in function `inc_value()` of hello_word example TA.
Use `script/symbolize.py` to parse the debug information:
```
$ cat dump_ta.txt | ./optee_os/scripts/symbolize.py -d ./out-br/build/optee_examples_ext-1.0/hello_world/ta/out
I/TA: Hello World!
Invoking TA to increment 42
D/TA:  inc_value:105 has been called
I/TA: Got value: 42 from NW
I/TA: Increase value to: 43
E/TC:? 0
E/TC:? 0 TA panicked with code 0x0
E/LD:  Status of TA 8aaaf200-2450-11e4-abe2-0002a5d5c51b
E/LD:   arch: riscv64
E/LD:  region  0: va 0x40000000 pa 0x8e200000 size 0x002000 flags rw-s (ldelf)
E/LD:  region  1: va 0x40002000 pa 0x8e202000 size 0x00c000 flags r-xs (ldelf)
E/LD:  region  2: va 0x4000e000 pa 0x8e20e000 …
```
=> RISC-V: Implement TA stack unwinding

mk/aosp_optee.mk
After skipping installation for static libraries by commit  667213e21e8b ("mk: Support user static lib for aosp build").  The dependency set by $(local_module_deps) needs different file paths for static libraries. Use aosp macro to build the dependency with the intermediate file instead of installed file.
The dependency change also affects user TAs and shared libraries. Since installed location could be changed for some customization requirement, I think using the intermediate-dir should make it easier if we would like to change the `$(LOCAL_MODULE_PATH)` for TAs.
=> mk/aosp_optee.mk: fix build dependency for static libraries

core/arch/arm/kernel/boot.c, core/arch/arm/kernel/entry_a32.S, core/arch/arm/kernel/entry_a64.S, core/include/kernel/boot.h, core/include/kernel/thread.h, core/kernel/thread.c
Currently hardcoded magic number is used as thread stack canary, an attacker with full control over the overflow can embed the hardcoded canary value on the right location to bypass the overflow detection.
To add extra layer of security, redefine the canary value as variable, such that the canary can be initialized during runtime.
Weak function plat_set_thread_canary() can be overridden by platform to initialize the thread canary with random numbers from TRNG hardware.
=> core: thread: Add support for canary value randomization

lib/libutils/isoc/bget_malloc.c
When checking if there's an overlap between allocated buffer and heap, raw_malloc_buffer_overlaps_heap() considers two cases: when buffer comes before the pool and the opposite. On the first case, overlap will happen if the buffer end after the loop start. Since buf_end is computed as buf_start + len, it will point to the address of the first byte after the memory region allocated to the buffer.
Fix raw_malloc_buffer_overlaps_heap() by considering overlap only when buffer end is bigger than the pool start.
Fixes: 12d739bd5028 (libutils: use raw_malloc_*() as more primitive bget wrappers)
Signed-off-by: Vitor Sato Eschholz <vsatoes@baylibre.com>
=> libutils: malloc: fix raw_malloc_buffer_overlaps_heap()

core/arch/arm/plat-k3/drivers/ti_sci.c, core/arch/arm/plat-k3/drivers/ti_sci.h, core/arch/arm/plat-k3/drivers/ti_sci_protocol.h, core/arch/arm/plat-k3/main.c
Add requests to read OTP values used during secure boot
- SWREV: Secure Board Configuration revision
- KEY Count, Key Revision : the number of keys (max = 2), active key
Messages are documented below:
https://software-dl.ti.com/tisci/esd/latest/2_tisci_msgs/security/otp_revision.html#sec-api-rd-swrev-otp
Code tested on TI am62b HS and am62b HS-FS
Below console output on a secured board (ROM verified boot) where only one key (SMPK hash) was fused.
```
NOTICE:  BL31: v2.7(release):v2.7.0-359-g1309c6c80 …
```
=> plat-k3: drivers: add TISCI calls to retrieve OTP values that configure secure boot

core/arch/arm/kernel/thread_spmc.c
Handles the previously missing FFA_MSG_SEND_VM_DESTROYED message used to signal the destruction of a non-secure guest. This is the counter part of FFA_MSG_SEND_VM_CREATED that is used to signal the creation of a non-secure guest.
Fixes: a65dd3a6b64d ("core: spmc: support virtualization with SPMC at S-EL1")
=> core: spmc: handle missing FFA_MSG_SEND_VM_DESTROYED

core/arch/arm/mm/mobj_dyn_shm.c
Fixes a race in mobj_reg_shm_dec_map() when r->mm is NULL. This is similar to the race fixed by commit 06ea466f9c19 ("core: fix race in mobj_reg_shm_inc_map()"), but with one more possibility.
The problem goes like:
A. Thread 1 calls mobj_reg_shm_dec_map() at the same time as thread 2
calls mobj_reg_shm_inc_map().
B. Thread 1 decreases mapcount to zero and tries to take the spinlock,
but thread 1 is suspended before it has acquired the spinlock.
C. Thread 2 sees that mapcount is zero and takes the spinlock and maps
the memory.
D. Thread 2 calls mobj_reg_shm_dec_map(), mapcount reaches zero again
and the shared memory is unmapped and r->mm is set to NULL.
E. Thread 1 is finally resumed and acquires the spinlock, mapcount is still
zero but r->mm is also NULL.
To fix the problem at step E …
=> core: fix race in mobj_reg_shm_dec_map()

ldelf/ftrace.c, lib/libutee/include/user_ta_header.h, lib/libutils/ext/ftrace/ftrace.c, mk/config.mk, scripts/ftrace_format.py
The current implementation of function tracing (CFG_FTRACE_SUPPORT) produces human-readable text into the output buffer that is passed to tee-supplicant and ultimately saved to the Linux filesystem. Two main issues with that:
1. The string formatting code is somewhat complex. It introduces significant overhead in the execution time of the instrumented functions.
2. The various policies about how to handle a buffer full condition (CFG_FTRACE_BUF_WHEN_FULL) are not very convenient. In particular, "shift" is typically the most desirable option because it always keeps the most recent entries, but it is very inefficient to the point of not being usable in practice.
This commit addresses the above concerns by making the ftrace buffer circular one, each entry being a 16-byte binary structure. …
=> ftrace: change implementation to use binary circular buffer

Makefile, core/arch/arm/plat-vexpress/conf.mk
The proper way to build in-tree TAs in 64-bit mode by default is to set supported-ta-targets to "ta_arm64 ta_arm32". Indeed, the default target is always defined as the first entry in supported-ta-targets, as documented in mk/config.mk.
Fixes the following build error:
$ make CFG_USER_TA_TARGETS=ta_arm32 PLATFORM=vexpress-qemu_armv8a
bash: -W: invalid option
...
default-user-ta-target is not to be used by the platform configuration files. It is meant to be set by the main Makefile. For this reason, replace the conditional assignment (?=) with $(call force, ...) in order to catch inconsistencies in a more friendly way.
Fixes: 07031b23de23 ("qemu_armv8a: set default-user-ta-target ?= ta_arm64")
=> qemu_armv8a: fix build with CFG_USER_TA_TARGETS=ta_arm32

core/tee/tee_svc_cryp.c
Fixes syscall_asymm_operate() to report inconsistent hash algorithm specified as attribute for TEE_ALG_RSAES_PKCS1_OAEP_MGF1_* operations as OP-TEE only supports the hash predefined for the request algorithm TEE_ALG_RSAES_PKCS1_OAEP_MGF1_xxx.
Fixes: https://github.com/OP-TEE/optee_os/issues/6143
=> core: tee_svc_cryp: report RSAES_PKCS1_OAEP_MGF1 bad hash ID

core/arch/arm/plat-stm32mp1/scmi_server.c
The function plat_scmi_clock_set_state sends debug messages when handling some scmi services.
At runtime this leads to a lot of traces and debug loglevel is unusable. Change all debug traces to flow level.
=> plat-stm32mp1: change loglevel in plat_scmi_clock_set_state.

core/crypto/crypto.c, core/drivers/crypto/caam/acipher/caam_dh.c, core/drivers/crypto/caam/acipher/caam_dsa.c, core/drivers/crypto/caam/acipher/caam_ecc.c, core/drivers/crypto/caam/acipher/caam_rsa.c, core/drivers/crypto/se050/core/ecc.c, core/drivers/crypto/se050/core/rsa.c, core/drivers/crypto/versal/ecc.c, core/include/crypto/crypto.h, core/lib/libtomcrypt/dh.c, core/lib/libtomcrypt/dsa.c, core/lib/libtomcrypt/ecc.c, core/lib/libtomcrypt/mpi_desc.c, core/lib/libtomcrypt/rsa.c, core/tee/tee_svc_cryp.c, lib/libmbedtls/core/bignum.c, lib/libmbedtls/core/dh.c, lib/libmbedtls/core/ecc.c, lib/libmbedtls/core/rsa.c
To prevent human mistake, crypto_bignum_free() sets the location of the bignum pointer to NULL after freeing it.
Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>
Reviewed-by: Joakim Bech <joakim.bech@linaro.org>
=> core: crypto_bignum_free(): add indirection and set pointer to NULL

CHANGELOG.md, mk/config.mk
Update CHANGELOG for 3.22.0 and collect Tested-by tags.
Maintainers etc, we will use this PR for the upcoming 3.22 release. In the docs it says that the release is July 14th. But due to vacations, holidays etc, we've decided to release one week earlier, i.e,. July 7th will be the release date for OP-TEE 3.22.0.
RC-tags will be created in about a week, but it probably doesn't hurt to start sanitize testing already now.
**EDIT 2023-06-30**
I have just submitted the 3.22.0-rc1 tag to all of our git repositories.
// Regards
Joakim
=> Update CHANGELOG for 3.22.0

core/arch/arm/kernel/boot.c, core/arch/arm/plat-sam/freq.c, core/arch/arm/plat-stm32mp1/shared_resources.c, core/arch/riscv/kernel/boot.c, core/arch/riscv/kernel/entry.S, core/drivers/clk/clk_dt.c, core/drivers/crypto/caam/hal/common/hal_cfg.c, core/include/kernel/boot.h, core/include/kernel/dt.h, core/kernel/dt.c
This PR is version 2 of https://github.com/OP-TEE/optee_os/pull/6147.
Since some existed device tree functions in ARM can also be used by other architectures,
we create `core/kernel/boot.c` to move those functions into it.
Now RISC-V can get the external device tree provided by early boot stage.
And invoke aforementioned device tree functions to utilize the DTB.
=> [v2] RISC-V: Support device tree

mk/aosp_optee.mk
The LOCAL_REQUIRED_MODULES proposed by the commit [1] creates the dependency for the specified modules and product to make sure they are installed to the product image. But it doesn't create the dependency between a TA and its libraries for build process to correctly link them. Add the dependency back and change the depended file to the result file in the intermediate directory instead of the installation directory.
Fixes: fb66b364b5d2 ("mk/aosp_optee.mk: fix build dependency for static libraries")
=> mk/aosp_optee.mk: fix build dependency between a TA and its libraries

core/arch/arm/plat-stm32mp1/main.c, core/drivers/stm32_bsec.c, core/drivers/stm32mp15_huk.c, core/include/drivers/stm32_bsec.h
Some updates in the BSEC driver used to OTPs access on STM32MP13x and STM32MP15x SoC family,
based on STMicroelectronics patches present in https://github.com/STMicroelectronics/optee_os.
The OTP descriptions are based on NVMEM cell binding.
The addition of the API "get otp by phandle()" is a preliminary steps for next series.
=> Stm32mp1 bsec

core/arch/arm/include/arm64.h
Implement the use of osh data barrier to ensure that all data access and modifications have been completed before executing subsequent instructions.
=> core: arm64: add dsb_osh

core/arch/riscv/include/mm/core_mmu_arch.h, core/arch/riscv/kernel/asm-defines.c, core/arch/riscv/mm/core_mmu_arch.c, core/arch/riscv/mm/sub.mk
Happy to see, that there is an intention to make slight changes to the current OP-TEE OS's memory management layer, to make it easier for RISC-V MMU driver integration, I re-open this PR to check progressively what we can adapt to have this big chunk merged.
=> riscv: mm: initial implementation of memory management routines for RISC-V

core/drivers/crypto/caam/cipher/caam_cipher_mac.c
In case of an update operation, the total input data size processed must be a multiple of a block size. The total block size is equal to the input data size and the saved buffer size.
If the reallocation DMA buffer is less than the input data size, buffer length plus saved buffer size need to be adjusted to align on multiple of a block size.
Depending on the memory buffer input configuration, the function caam_dmaobj_sgtbuf_build() might modify the data size to be processed in the loop.
This case happens sometimes on i.MX platforms where the input buffer physical address in above 32 bits. This implies reporting the data size re-ajustment when data is saved in the context buffer.
=> drivers: caam: fix size of cmac update data

core/arch/arm/plat-stm32mp1/conf.mk, core/arch/arm/plat-stm32mp1/drivers/stm32mp1_pmic.c, core/arch/arm/plat-stm32mp1/main.c, core/arch/arm/plat-stm32mp1/shared_resources.c, core/arch/arm/plat-stm32mp1/stm32_util.h, core/drivers/crypto/se050/glue/i2c_stm32.c, core/drivers/stm32_gpio.c, core/drivers/stm32_i2c.c, core/drivers/stm32_uart.c, core/include/drivers/stm32_gpio.h, core/include/drivers/stm32_i2c.h, core/include/drivers/stm32_uart.h
Bump stm32_gpio driver to recently merged  pinctrl device driver probing support.
For STM32MP13 variant to comply with pinctrl support (and not panic on driver probe errors), I needed to update STM32MP13 DTS and DTSI file and 2 stm32 drivers (stm32_etzpc and stm32_rstctrl). They are part of this series.
A patch fixing a pinctrl driver probe function in under review at https://github.com/OP-TEE/optee_os/pull/6081.
=> plat-stm32mp1: bumping to pinctrl framework 

ta/pkcs11/src/pkcs11_attributes.c
PKCS#11 standard specifies that verification or usage of start and end date for certificate objects is responsibility of the application.
There is no other activity than storage needed for those.
=> ta: pkcs11: remove redundant comment about start and end date

core/crypto/crypto.c, core/drivers/crypto/crypto_api/include/drvcrypt.h, core/drivers/crypto/crypto_api/include/drvcrypt_acipher.h, core/include/crypto/crypto.h, core/lib/libtomcrypt/x25519.c, core/tee/tee_svc_cryp.c, lib/libutee/include/utee_defines.h
1.Refer to the X25519 algorithm, add the X448 algorithm framework code.
2.Design the montgomery keypair structure, to merge x25519 and x448 algorithm keypair structure.
=> crypto: add X448 algorithm framework code and rename struct x25519_keypair. 

.github/workflows/ci.yml, core/include/kernel/pseudo_ta.h, core/kernel/pseudo_ta.c, core/pta/attestation.c
Several fixes for the attestation PTA. One commit excludes a region that should not be hashed, which was introduced by a commit related to PAN. The other ones fix invalid accesses to user space memory (TA memory pages and memref parameters) when `CFG_PAN=y`.
=> pta: attestation: fixes

core/arch/arm/plat-nuvoton/conf.mk, core/arch/arm/plat-nuvoton/main.c
Changes load address of OPTEE-OS from 0x36000000 to 0x02100000
Implements HUK reading from DME PCR0 located in PCI mailbox
Disables DT insecure warning
=> plat-nuvoton: configuration change

core/arch/arm/plat-stm32mp1/conf.mk, core/arch/arm/plat-stm32mp1/main.c, core/drivers/crypto/stm32/authenc.c, core/drivers/crypto/stm32/cipher.c, core/drivers/crypto/stm32/common.h, core/drivers/crypto/stm32/crypto.mk, core/drivers/crypto/stm32/stm32_cryp.c, core/drivers/crypto/stm32/stm32_saes.c, core/drivers/crypto/stm32/stm32_saes.h, core/drivers/crypto/stm32/sub.mk, core/include/kernel/huk_subkey.h, core/kernel/huk_subkey.c
This pull request adds the driver SAES for the platform STM32MP13
SAES is used to derive a key for the HUK.
To do that,  we override the function huk_subkey_derive().
One false positive will be found by the CI, the macro CLRSETBITS changes one of its parameters
=> crypto : custom HUK derviation with SAES on STM32MP13

core/arch/arm/plat-versal/main.c
If log level is set to print only EMSGs, constant strings can be unused. Add maybe_unused attribute to prevent compilation errors.
=> core: arm: plat-versal: Add maybe_unused attribute to constant strings

core/drivers/imx/mu/imx_mu.c, core/drivers/imx/mu/imx_mu_8q.c, core/drivers/imx/mu/imx_mu_8ulp.c, core/drivers/imx/mu/imx_mu_platform.h
On i.MX8ULP, there are multiple MUs with a different number of RX and TX buffer sizes. To make the driver generic for all MUs on this platform, get the RX and TX buffer size from the MU configuration register.
The configuration remains static for i.MX8Q.
=> drivers: imx_mu: read RX and TX buffer size from MU configuation register

core/drivers/crypto/caam/mp/caam_mp.c, core/drivers/crypto/caam/utils/utils_dmaobj.c, core/drivers/crypto/crypto_api/acipher/rsamgf.c, core/pta/attestation.c, core/tee/entry_std.c, core/tee/fs_dirfile.c, core/tee/tadb.c, lib/libutee/include/user_ta_header.h, lib/libutee/tee_api.c, lib/libutee/tee_api_property.c
Hello,
Our CI reported multiple Coverity issues in optee-os. The issues fixed in this pull-request are rated `High` and `Medium` impact. As a maintainer of the crypto driver API and the CAAM, I want to push 2878ec621 b3b05676a 1ba0f6dc6 d34d5c50b.
At the same time, I also fixed some issues in libutee, PTA attestation and the core. Feel free to comment regarding commits  d68119a17 dae33b69b a6c6ab0fe 726f19ea9 b98fa53d1
Thanks!
=> Multiple Coverity fixes for CAAM Driver, Crypto API and Core

.github/workflows/ci.yml
A previous patch temporarily removed the libscmi-server build.
Now that the related PR in SCP-firmware has been merged, reintroduce the build step.
Refs:
https://github.com/ARM-software/SCP-firmware/pull/812 https://github.com/OP-TEE/optee_os/pull/6190
=> ci.yml: Reintroduce build of libscmi-server

core/arch/arm/include/arm64_macros.S, core/arch/arm/kernel/asm-defines.c, core/arch/arm/kernel/thread_a64.S
With larger values of CFG_TEE_CORE_NB_CORE (for example, 18 on the marvell-cnf10ka platform) CORE_MMU_BASE_TABLE_OFFSET becomes to large to be used as an immediate value in add and sub assembly instructions. This is handled by populating a spare register using the mov_imm macro and use the spare register instead. But the mov_imm macro can handle complex defines so CORE_MMU_BASE_TABLE_OFFSET must be evaluated in asm-defines.c first.
This should fix errors like:
core/arch/arm/kernel/thread_a64.S: Assembler messages: core/arch/arm/kernel/thread_a64.S:339: Error: immediate out of range core/arch/arm/kernel/thread_a64.S:347: Error: immediate out of range core/arch/arm/kernel/thread_a64.S:355: Error: immediate out of range core/arch/arm/kernel/thread_a64.S:372: Error: immediate out of range …
=> core: support larger values for CFG_TEE_CORE_NB_CORE

.github/workflows/ci.yml, MAINTAINERS, core/arch/arm/plat-marvell/cn10k/core_pos.S, core/arch/arm/plat-marvell/conf.mk, core/arch/arm/plat-marvell/platform_config.h, core/arch/arm/plat-marvell/sub.mk
Add support for CN10K SoCs from Marvell.
Only tested 64-bit mode with default configurations:
1. Build command make PLATFORM=marvell-cn10ka
2. Passed xtest
Signed-off-by: Gowthami <gthiagarajan@marvell.com>
Reviewed-by: Anil Kumar Reddy <areddy3@marvell.com>
=> plat-marvell: Add support for CN10K SoCs

core/arch/riscv/kernel/asm-defines.c, core/arch/riscv/kernel/thread_rv.S
RISC-V kernel uses TP register to store thread_core_local structure. When the thread enters user mode, the value of TP is used by user mode. Therefore, when CPU enters trap handler, it needs to restore TP to get thread_core_local structure.
In previous implementation, the value of TP is saved under kernel SP before entering user mode, and the trap handler restores TP from that stack location. However, the value of TP has already been saved into the thread_user_mode_rec structure (https://github.com/OP-TEE/optee_os/blob/master/core/arch/riscv/kernel/thread_rv.S#L202), which is also upon kernel SP, before entering user mode. So the value of TP can be restored just from thread_user_mode_rec, instead of saving into another location which is under the kernel SP.
=> RISC-V: Refine TP restoring in trap handler

core/lib/libtomcrypt/src/pk/rsa/rsa_verify_hash.c
When running a test with CFG_FAULT_MITIGATION=y and with a corrupted message, hash verification fails and panic TEE core:
F/TC:? 0 trace_syscall:149 syscall #40 (syscall_asymm_verify) E/TC:2 0 Panic at lib/libutils/ext/fault_mitigation.c:87 <___ftmn_callee_done_check> E/TC:2 0 TEE load address @ 0x43200000
E/TC:2 0 Call stack:
E/TC:2 0  0x4320a9f0 print_kernel_stack at optee-os/core/arch/arm/kernel/unwind_arm64.c:91 E/TC:2 0  0x432203fc __do_panic at optee-os/core/kernel/panic.c:26 (discriminator 32) E/TC:2 0  0x4327d324 ___ftmn_callee_done_check at optee-os/lib/libutils/ext/fault_mitigation.c:87 E/TC:2 0  0x43263aac __ftmn_callee_done_check at optee-os/lib/libutils/ext/include/fault_mitigation.h:349 E/TC:2 0  0x43258408 sw_crypto_acipher_rsassa_verify at …
=> libutils: fault_mitigation: fix panic on hash mismatch

scripts/derive_rpmb_key.py
Adds the script derive_rpmb_key.py that can derive the RPMB key OP-TEE uses offline or in normal world during a production step.
=> scripts: add derive_rpmb_key.py

lib/libutils/ext/mempool.c
Prior to this patch mempool_free() unconditionally called put_pool(), but if the "ptr" argument is NULL it means that there hasn't been a corresponding call to get_pool(). Fix this only calling put_pool() for non-NULL pointers.
Fixes: a51d45b52503 ("libutils: mempool based raw malloc functions")
=> libutils: mempool: fix unbalanced put_pool()

core/pta/imx/manufacturing_protection.c
Allow opening the PTA without a calling session.
Enabling CFG_NXP_CAAM_MP_NO_ACCESS_CTRL permits users to use the OP-TEE
client interface to retrieve the public key as well as to generate
signatures.
See OP-TEE/optee_client#352
=> core: pta: imx: disable access control for MP PTA

core/arch/riscv/plat-spike/platform_config.h
Add definitions for base address of CLINT, otherwise build failure occurs for platform spike.
=> core: riscv: Add definitions of CLINT for platform spike

core/arch/arm/include/arm64.h
Implement write_64bit_pair that write two 64 bits data together.
=> core: arm64: write_64bit_pair()

core/arch/arm/kernel/secure_partition.c, core/arch/arm/kernel/spmc_sp_handler.c
There were multiple issues with FF-A direct message error handling in the SPMC component. This pull request introduces fixes in the following steps.
- Set initial SP state to busy which will prevent sending direct messages to uninitialized SPs.
- Clear MBZ registers of FFA_ERROR messages. This prevents sending back the reminiscence of the direct message in the error message.
- Cover all invalid cases in FF-A direct message request and response handlers. Also fix the logic behind determining the destination of the FFA_ERROR message.
I've extended the [SPMC test in trusted-services](https://review.trustedfirmware.org/c/TS/trusted-services/+/22959/1/components/service/spm_test/sp.c) by negative tests for covering all the error handler branches of FF-A direct message handlers.
=> Fixing issues around FF-A direct message handling in SPMC

core/tee/sub.mk, mk/config.mk
We add a new pbkdf2 implementation.
=> crypto: add a new pbkdf2 implementation

core/drivers/crypto/caam/caam_ctrl.c
On i.MX platforms, the CAAM DMA width is limited to 32 bits. That limitation requires OPTEE to be located in the 32 bits DDR address space.
=> drivers: caam: check OPTEE DDR location if the CAAM DMA is 32 bits width

core/drivers/crypto/stm32/stm32_saes.c
Uses SAES internal reset sequence only when external reset controller is not available. This change fixes a non-systematic SAES error seen when SAES internal reset is triggered right after external reset sequence. Whereas a fixe could be to add a delay between external reset and internal reset sequences, this change simplifies the sequence as internal reset sequence is not needed when SAES instance is reset using its external reset controller.
Fixes: 4320f5cf30c5 ("crypto: stm32: SAES cipher support")
=> crypto: stm32: fix SAES reset at probe time

core/arch/arm/plat-zynqmp/platform_config.h
The hardware description is identical in all the platforms, there is no need for specific ultra96 code to define base addresses.
=> zynqmp: remove redundant platform config code

core/arch/arm/plat-k3/conf.mk
All other SoCs have 4 cores per cluster, which is the default, or they only have one cluster in which case this value is unimportant.
=> plat-k3: Default to 2 core per cluster only for AM65x

scripts/sign_rproc_fw.py
Remove the __len__ method of the TLV class. It is not being used and uses an undefined variable TLV_INFO_SIZE. This method is a remnant of code that was removed during upstream reviews.
Fixes: e8ef53536 ("scripts: add remote processor firmware signature tool")
=> scripts: sign_rproc_fw: clean up unused TLV method

core/arch/arm/include/kernel/secure_partition.h, core/arch/arm/kernel/secure_partition.c
Add support for boot-order property specified in the SP manifest.
Boot order can be defined in the manifest via an entry like: 
boot-order = /bits/ 16 <0>; 
Also printing the endpoint ID-s when the SP-s are loaded so the order can be easily extracted from the SWD log.
=> core: spmc: implement boot-order support

core/arch/arm/include/kernel/thread_arch.h, lib/libutils/ext/include/fault_mitigation.h
Fix the issue of fault mitigation that won't work in interrupt handler function.
assertion 'ct >= 0 && ct < CFG_NUM_THREADS' failed at core/arch/arm/kernel/thread.c:799 <thread_get_id>
The problem is in  __ftmn_get_tsd_func_arg_pp whhich call thread_get_tsd which thread_get_id. The reason is that interrupt handler is not associated with any thread, so the ct (current_thread_id) value is -1 that would cause assert problem.
The fix is to add ftmn_arg to thread_core_local and the new variable would be used when current thread is < 0.
=> Core: support fault mitigations in non-threaded code

core/drivers/regulator/regulator.c, core/drivers/regulator/sub.mk, core/drivers/sub.mk, core/include/drivers/regulator.h, mk/config.mk
Introduces a voltage regulator driver framework for management of regulators and supply dependencies. The framework permits 1 regulator supply per regulator.
API function `regulator_register()` allows a regulator driver to register a regulator in the regulator framework.
Supported operation here are to enable, disable, get and set voltage level. They are all optional.
Registered regulators are referenced in a list for initialization resource release and debug purpose.
---
This change is the 1st commit reviewed in the scope of https://github.com/OP-TEE/optee_os/pull/6301.
One can refer to that P-R to get the full picture targeted by this regulator framework.
@GseoC, I've have added your A-b tag as you post it in P-R https://github.com/OP-TEE/optee_os/pull/6301.
=> drivers: regulator framework

core/arch/arm/include/sm/watchdog_smc.h, core/arch/arm/tee/entry_fast.c, core/drivers/wdt/watchdog_sm.c, mk/config.mk
Add a dedicated OP-TEE ID for a SMC fast call entry to manage the ARM watchdog service.
Recreating this pull request based on first review [https://github.com/OP-TEE/optee_os/pull/5947].
Too late for an update, comment has been taken and cleanup done to define a dedicated OP-TEE SMC ID.
=> Optee watchdog

core/drivers/regulator/regulator_dt.c, core/drivers/regulator/sub.mk, core/include/drivers/regulator.h, core/include/kernel/dt_driver.h, core/kernel/dt_driver.c, mk/config.mk
Adds `regulator_dt_register()` for regulator drivers to register regulator instances based on the DT description of the platform.
=> drivers: regulator: register to dt_driver

core/include/io.h
Implement Polling Read Register Interface inspired by linux kernel.
=> core: io: IO_READ32_POLL_TIMEOUT()

core/arch/riscv/kernel/thread_arch.c
RISC-V defines that xPP(previous privilege mode) field of CSR status indicates the previous privilege level prior to the trap. Since the encoding of user mode is 0, we should compare the xPP field with 0 here to know that the trap is from user mode.
=> core: riscv: Fix condition of is_from_user()

core/drivers/ns16550.c, core/include/drivers/ns16550.h
Implement ns16550_getchar() and ns16550_have_rx_data() for RX related serial operations into ns16550 UART driver.
=> drivers: ns16550: Implement RX related features

core/drivers/regulator/regulator_dt.c, core/include/drivers/regulator.h
Consider regulator DT binding properties `regulator-always-on` and `regulator-pull-down`.
=> drivers: regulator: DT bindings properties always-on & pull-down

core/drivers/regulator/regulator_dt.c
Adds missing header file for TEE extension macro
TEE_ERROR_DEFER_DRIVER_INIT.
Fixes: 6558b5657faf ("drivers: regulator: register to dt_driver")
=> drivers: regulator: include tee extensions

lib/libutils/ext/include/fault_mitigation.h
Indentation with tab instead of space.
Fixes: ce56605a0ede ("core: support fault mitigations in non-threaded code")
=> libutils: fault_mitigation.h: Fix indentation

.github/workflows/ci.yml
Two commits related to the Rust CI job. THe first one fixes the "no space left on device" issue, the other is a cleanup.
=> Fix Rust CI

core/arch/arm/plat-k3/drivers/sa2ul.c
On devices with PLATFORM=k3-am62x, there is only one SA2UL instance, which is being shared between TIFS and OP-TEE.
Blocking access to TRNG from all other entities other than OP-TEE is causing firewall exception when being accessed by TIFS.
Allow access to TIFS to use SA2UL TRNG along with OP-TEE.
While at it, correct values for FW_SECURE_ONLY and FW_NON_SECURE.
=> plat-k3: drivers: Open TRNG firewall for TIFS

core/drivers/atmel_saic.c, core/drivers/gic.c, core/drivers/hfic.c, core/drivers/plic.c, core/include/kernel/interrupt.h, core/kernel/interrupt.c
Before summer, few P-Rs, incl. #6087, #6088 and #6096 were merged to introduce interrupt controller devices in OP-TEE core, for staged controllers and interrupts multiplexing.
I let P-R https://github.com/OP-TEE/optee_os/pull/6113 stall before summer. This P-R presents the 3 first commits from #6113, in order to finalize the integration of the interrupt framework APIs (goal: pass an itrchip reference).
On can see in #6113 the next changes that [would follow this series](https://github.com/OP-TEE/optee_os/pull/6113/commits): upgrading the few core/drivers/ source files to use the _new API framework_ `interrupt_xxx()` functions then [remove the deprecated](https://github.com/OP-TEE/optee_os/pull/6113/commits/3f99a0fa3a1d21f91c05e6a4154d2c7dbf7340d3) `itr_xxx()` functions.
=> core interrupt: few new API functions

core/drivers/regulator/regulator_fixed.c, core/drivers/regulator/sub.mk, mk/config.mk
Implements fixed voltage level regulator driver to register DT compatible "regulator-fixed" devices into the regulator framework. These regulators may be enabled/disabled using a GPIO pin in which cases `CFG_DRIVERS_GPIO` shall be enabled.
This P-R is extracted from RFC https://github.com/OP-TEE/optee_os/pull/6301.
=> drivers: regulator: fixed regulator

core/drivers/regulator/regulator_dt.c, core/include/drivers/regulator.h
Implements `regulator_dt_get_supply()` API function for consumer drivers to get a regulator supply using the driver device DT node data. The function returns `TEE_ERROR_DEFER_DRIVER_INIT` when the target supply exists but is yet not initialized.
=> drivers: regulator: add regulator_dt_get_supply()

core/drivers/atmel_saic.c, core/drivers/hfic.c
=> Remove stubbed interrupt driver functions

core/arch/arm/mm/mobj_ffa.c
Prior to this patch there was a race condition when mobj_put() is calling ffa_inactivate().
D/TC:0 0 ffa_inactivate:525 cookie 0x100000000000
D/TC:0 1 mobj_ffa_get_by_cookie:401 cookie 0x100000000000 active: refc 1 D/TC:? 1 read_console:114 got 0xd
D/TC:0 1 ffa_inactivate:525 cookie 0x100000000000
D/TC:0 0 ffa_inactivate:525 cookie 0x100000000000
E/TC:0 0 Panic at core/arch/arm/mm/mobj_ffa.c:527 <ffa_inactivate> E/TC:0 0 TEE load address @ 0xe100000
E/TC:0 0  0x0e108c0c print_kernel_stack at ??:?
E/TC:0 0  0x0e115b8c __do_panic at core/kernel/panic.c:24 E/TC:0 0  0x0e10a238 ffa_inactivate at mobj_ffa.c:? E/TC:0 0  0x0e107318 __thread_std_smc_entry at ??:?
As now explained in ffa_inactivate():
/*
* pop_from_list() can fail to find the mobj if we had just
* decreased …
=> core: ffa: fix race in mobj_put() and ffa_inactivate()

core/arch/riscv/include/kernel/thread_private_arch.h, core/arch/riscv/include/riscv_macros.S, core/arch/riscv/include/sbi.h, core/arch/riscv/kernel/asm-defines.c, core/arch/riscv/kernel/entry.S, core/arch/riscv/kernel/thread_arch.c, core/arch/riscv/kernel/thread_optee_abi_rv.S
Based on https://github.com/OP-TEE/optee_os/pull/6268
And apply recommendations from patch v1 https://github.com/OP-TEE/optee_os/pull/6323
This PR implements SBI based protocol.
In SBI protocol, OP-TEE prepares function arguments in registers a0~a5.
The register a7 encodes SBI TEE extension ID, which is 0x544545(TEE), temporarily.
Then OP-TEE issues ecall to trap into higher privileged software, e.g., openSBI.
The higher privileged software will handle this call and execute OS context switch, etc.
OP-TEE also registers its vector table, which has address of entry functions for service, into higher privileged software. The higher privileged software can jump into OP-TEE according to this vector table.
=> [PATCH v2] RISC-V: Implement SBI based protocol 

core/drivers/regulator/regulator_dt.c, core/include/drivers/regulator.h
Defines regulator flag `REGULATOR_BOOT_ON` for regulators with the `regulator-boot-on` property in their DT node.
=> drivers: regulator: consider DT property regulator-boot-on

core/drivers/crypto/stm32/cipher.c
Changes SAES context allocation/release trace message from debug level to flow level otherwise each access to the secure storage emits debug messages.
=> drivers: crypto: stm32: lower verbosity on SAES key derivation

Makefile, ldelf/ta_elf.c, mk/checkconf.mk, mk/macros.mk, scripts/ts_bin_to_c.py, ta/arch/arm/ta.ld.S, ta/link.mk, ta/mk/ta_dev_kit.mk, ta/ta.mk
https://github.com/jenswi-linaro/optee_os/pull/10 applied to upstream instead of my private fork.
This is part of https://github.com/OP-TEE/optee_os/issues/6032
=> [v4] Relax location of ta head

CHANGELOG.md, mk/config.mk
Update CHANGELOG for 4.0.0 and collect Tested-by tags.
The 4.0.0-rc1 tag will be created on Friday October 13th (!) and the 4.0.0 release is expected on October 20th.
I will hold off merging the pull requests with "[v4]" in their subject [1] until the end of next week (just before -rc1), even the ones that have the proper review tags etc., so that people have more opportunities to comment.
[1] https://github.com/OP-TEE/optee_os/pulls?q=is%3Apr+is%3Aopen+in%3Atitle+%5Bv4%5D
=> Update CHANGELOG for 4.0.0

.gitignore, Makefile, scripts/gen_compile_commands.py
The Language Server Protocol (LSP) is a standard protocol used by many text editors and integrated development environments (IDEs) to enable advanced language features such as code completion, hover information, and diagnostics.
This commit introduces a script that simplifies the generation of LSP configuration JSON files. These JSON files describe how source files are compiled and linked together for use with LSP-enabled tools. The script is adapted from U-Boot and customized to work with the *.cmd files used by OP-TEE, making it easier to harness the power of LSP for development and code analysis.
Main changes to the original source is the `_LINE_PATTERN` regexp and the moving the try / except to cover a bit more code in the main function.
Note, this Python script has a GPL-2.0 license, …
=> scripts: Add script to support Language Server Protocol (LSP)

CHANGELOG.md
The link to GitHub pull requests merged into the 3.22.0 and 4.0.0 releases are broken (the start date is missing). Fix them.
=> CHANGELOG.md: fix links to pull requests in 3.22.0 and 4.0.0

core/drivers/plic.c
1. Move `interrupt_main_handler()` from platform specific source file to PLIC driver.
2. Ignore interrupt source ID 0 since it means "no interrupt".
=> RISC-V: Small modifications for PLIC driver

core/arch/riscv/include/kernel/thread_arch.h
The previous commit
ce56605a0ede ("core: support fault mitigations in non-threaded code") supports fault mitigations in non-threaded code for ARM architecture.
This commit adds the related modification for RISC-V architecture to support it too.
=> core: riscv: Support fault mitigations in non-threaded code

MAINTAINERS, mk/aosp_optee.mk
This change adds OPTEE_TA_DEV_KIT_MK target to replace OPTEE_BIN target in TA build process. It helps to build OPTEE_BIN with early TAs in one shot since the cyclic dependency between TAs and OPTEE_BIN is removed. It also allows to build TA with a preferred TA_TARGET that is not included in the CFG_USER_TA_TARGETS when building OPTEE_BIN. An AOSP common module for TAs in stripped elf format is added to be referred as early TA files when building OPTEE_BIN. For example, we can setup dependency and use the argument below to build OPTEE_BIN with an early TA.
EARLY_TA_PATHS=$(abspath $(PRODUCT_OUT))/unsigned/<ta_uuid>.ta.unsigned
=> mk/aosp_optee.mk: Allow building OPTEE_BIN with early TAs in one shot

core/include/kernel/dt_driver.h
Fixes the inline description comment for type get_of_device_func and API function dt_driver_device_from_parent().
Fixes: b357d34fe91f ("core: dt_driver: swap TEE_result and retrieved device reference")
=> core: kernel: interrupt: fix inline description

core/include/io.h
Adds missing include of kernel/delay.h for udelay() used in IO_READ32_POLL_TIMEOUT() macro.
Fixes: 97ea199a2ae8 ("core: io: IO_READ32_POLL_TIMEOUT()")
=> core: io: fix missing include of delay.h

.github/workflows/ci.yml, MAINTAINERS, core/arch/arm/dts/stm32mp25-pinctrl.dtsi, core/arch/arm/dts/stm32mp251.dtsi, core/arch/arm/dts/stm32mp253.dtsi, core/arch/arm/dts/stm32mp255.dtsi, core/arch/arm/dts/stm32mp257.dtsi, core/arch/arm/dts/stm32mp257f-ev1.dts, core/arch/arm/dts/stm32mp25xc.dtsi, core/arch/arm/dts/stm32mp25xf.dtsi, core/arch/arm/dts/stm32mp25xxai-pinctrl.dtsi, core/arch/arm/dts/stm32mp25xxak-pinctrl.dtsi, core/arch/arm/dts/stm32mp25xxal-pinctrl.dtsi, core/arch/arm/plat-stm32mp1/main.c, core/arch/arm/plat-stm32mp1/stm32_util.h, core/arch/arm/plat-stm32mp2/conf.mk, core/arch/arm/plat-stm32mp2/main.c, core/arch/arm/plat-stm32mp2/platform_config.h, core/arch/arm/plat-stm32mp2/stm32_util.h, core/arch/arm/plat-stm32mp2/sub.mk, core/drivers/stm32_gpio.c, core/drivers/stm32_uart.c, core/include/drivers/stm32_gpio.h
This P-R aims to bring minimal platform support for STM32MP25x 64 bits platforms in OP-TEE.
You'll find a resume of the features in the first commit on this series.
This P-R cleans some code in GPIO and UART driver as well that blocked the compilation of another platform using STM32 drivers.
A weak platform-specific plat_panic() is added to add platform-specific behavior in case of panic().
@etienne-lms As discussed in private, I put you as maintainer of the platform as well as myself.
@etienne-lms @tbourgoi, can you please review this P-R?
=> Introduce STM32MP25x platforms minimal support

core/arch/arm/plat-stm32mp1/conf.mk
Enables async notif using GIC PPI 15 as non-secure interrupt notifier for STM32MP13 variants.
This change depends on https://github.com/linaro-swg/linux/pull/116 and https://github.com/linaro-swg/linux/pull/115. It should not be merged before these 2 are merged unless what STM32MP13 kernel from linaro-swg/linux will fail to boot. This change is fine when using mainline kernel that already merges the changes from these 2 commits.
=> plat-stm32mp1: enable async notif on stm32mp13

.github/workflows/ci.yml, core/arch/arm/kernel/boot.c, core/include/kernel/transfer_list.h, core/include/mm/core_mmu.h, core/kernel/dt.c, core/kernel/sub.mk, core/kernel/transfer_list.c, core/mm/core_mmu.c, mk/config.mk
Add supports for Transfer List into core, which are compliant to the Firmware Handoff
specification v0.9 (https://github.com/FirmwareHandoff/firmware_handoff/releases/tag/v0.9).
The motivation for this patch set is to unify the way of arguments handoff between all boot stages (BL2/BL31/BL32/BL33).
In current practice, when the Transfer List is enabled between BL2 and BL33 (See the related patch sets for TF-A below for reference),
we need this patch to allow the DTB nodes appended by OP-TEE can be reflected into the Transfer List memory and passed to BL33.
Reference:
1. Patch to introduce Transfer List into TF-A: https://review.trustedfirmware.org/c/TF-A/trusted-firmware-a/+/22215
2. Patch to enable Transfer List between the handoff from BL2 to BL33 on qemu: …
=> Firmware handoff

lib/libutee/tee_api_operations.c
Commit https://github.com/OP-TEE/optee_os/commit/cf5c060cec76 introduced a check to enforce the `maxKeySize` parameter of digest operations to always be zero. This is a violation of the Global Platform specification.
Revert commit https://github.com/OP-TEE/optee_os/commit/cf5c060cec76 to allow `maxKeySize` to take any value for digest operations.
=> libutee: TEE_AllocateOperation(): maxKeySize of digests may take any value

core/arch/arm/kernel/stmm_sp.c, core/pta/attestation.c
Fixes calls to tee_pobj_get() that use boolean false are argument where a enum tee_pobj_usage argument is expected.
Function tee_pobj_get() used to take a boolean @temporary argument between old 2.4.0 and 3.11.0 release tags. Since commit [1] merged in release tag 3.11.0, function prototype changed but the commit missed few calls that since still use value false (0), treated as enumerated value TEE_POBJ_USAGE_OPEN. This change replaces these occurrences with use of TEE_POBJ_USAGE_OPEN argument.
Link: 6885abf2f7ef ("core: tee_pobj_get() takes an enum tee_pobj_usage") [1]
=> core: fix calls to tee_pobj_get() for object opening

ta/ta.mk
Commit 5c2c0fb31efb ("ftrace: change implementation to use binary circular buffer") added script ftrace_format.py which is required to analyze ftrace logs. So export it as part of TA dev kit as well.
=> TA dev kit: Export ftrace_format.py

ta/pkcs11/src/pkcs11_token.c
Make sure PIN check attempt is saved persistently before continuing with the actual PIN verification, improving counter and flags coherency in case of subsequent failure with persistent saving.
=> ta: pkcs11: Improve PIN counter handling robustness

lib/libutee/include/tee_arith_internal.h, lib/libutee/tee_api_arith_mpi.c
Removes references to libmpa removed since OP-TEE release tag 3.9.0, by commit 7fb525f1f8a6 ("Remove libmpa in favor of libmbedtls").
~~This change removes configuration switch CFG_TA_MBEDTLS_MPI and CFG_TA_MBEDTLS that are no more used by OP-TEE component.~~
(edited:  I removed to wrong stuf!!! Below is the expected commit message)
This change removes TEE_STRING_MODE_HEX_UC and TEE_STRING_MODE_HEX_LC
macros that relate to MPA_STRING_MODE_HEX_UC which is was removed
by the above mentioned commit.
=> tree wide: remove leftover references to libmap

core/kernel/trace_ext.c, lib/libutils/ext/include/trace.h, lib/libutils/ext/trace.c, scripts/symbolize.py
If CFG_NS_VIRTUALIZATION is enabled include the current guest ID on each log line. A number is added before the core number identifying the currently set guest ID, for example:
D/TC:2 0 0 call_initcalls:40 level 1 teecore_init_pub_ram()
Where the "2" indicates that this is done with guest ID 2 active.
=> core: print current guest ID in logs

core/arch/arm/kernel/thread_optee_smc.c, core/arch/arm/kernel/thread_spmc.c
In the SMC and FF-A ABIs check that a mobj representing a shared memory object isn't NULL before doing an RPC to free it in the normal world too. For the FF-A ABI it's harmless without this check, but the SMC ABI may cause an NULL pointer dereference in the OP-TEE kernel driver.
=> core: arm: check for NULL mobj before thread_rpc_free()

core/arch/arm/kernel/thread_spmc.c
Until now handle_mem_reclaim() was incorrectly returning the error value in a1 instead of a2 as mandated by the specification. Successful returns are not affected by this since they use the FFA_SUCCESS_32 FID. So fix this by supplying the error value in the right register.
Fixes: 1b302ac09816 ("core: enable FF-A with SPM Core at S-EL1")
=> core: ffa: fix mem reclaim error reporting

core/arch/arm/kernel/boot.c, core/arch/arm/plat-stm32mp1/main.c, core/arch/arm/plat-stm32mp1/shared_resources.c, core/arch/riscv/kernel/boot.c, core/arch/riscv/plat-spike/conf.mk, core/tee/tee_ree_fs.c, mk/config.mk
Changes STM32MP1 shared resources to allow insecure RCC protection with peripherals assigned to secure world when CFG_WARN_INSECURE is enabled. This means for example that some SoC resources can be assigned to OP-TEE without their clock and reset controllers being effectively protected from non-secure accesses. Such configuration can be useful for development and test purposes.
This change does not affect devices provisioned with secret that are in so-called SEC_CLOSED state (BSEC fuses). Indeed this device state currently requires RCC protection to be enabled as already implemented in function check_rcc_secure_configuration().
=> CFG_INSECURE deprecates CFG_WARN_INSECURE (+ stm32mp1 related change)

core/arch/arm/arm.mk
Fixes the inline comment that describes allowed values for CFG_CORE_ASYNC_NOTIF_GIC_INTID that can be a SPI or a secure PPI.
Fixes: 943972855082 ("core: notif: allow GIC_PPI usage for async notif")
=> core: arm: fix inline comment on async notif interrupt

core/arch/arm/dts/stm32mp157c-ed1.dts, core/arch/arm/dts/stm32mp15xx-dkx.dtsi, core/arch/arm/plat-stm32mp1/scmi_server.c
Fixes the return value when an SCMI regulator is already in the expected state. Prior this change the implementation returned SCMI_GENERIC_ERROR instead of SCMI_SUCCESS.
Changes also the SCMI return code in case of failure from SCMI_GENERIC_ERROR to SCMI_INVALID_PARAMETERS when the requested state is not one of the 2 supported SCMi voltage domain states supported (SCMI_VOLTAGE_DOMAIN_CONFIG_ARCH_ON or
SCMI_VOLTAGE_DOMAIN_CONFIG_ARCH_OFF).
Fixes: 23e200628dad ("plat-stm32mp1: scmi_server: use registered regulators")
=> plat-stm32mp1: scmi_server: fix case when regulator state is unchanged

core/arch/arm/include/mm/generic_ram_layout.h
Fixes case when a platform configuration defines CFG_TZSRAM_START but does not use the pager. CFG_TZSRAM_START defines the based address of the memory used for resident memory and page pool when CFG_WITH_PAGER is enabled.
Since below mentioned commit, TZSRAM_BASE being defined makes core_mmu.c to assume there are 2 secure memories for OP-TEE core internal use. This change ensures that when CFG_WITH_PAGER is disabled, TZSRAM is not defined even if the platform configuration sets CFG_TZSRAM_START.
An example of such issues is when testing an STM32MP15 variant of platform stm32mp1 with pager being disabled. Before this change, OP-TEE boot sequence fails with a error trace message like: E/TC:0 0 Panic 'Unexpected TZC configuration on secure region' at …
=> core: arm: allow CFG_TZSRAM_START being defined when pager is disabled

core/kernel/tee_ta_manager.c
Adds the TA UUID in open session error trace to allow to identify witch TA cause the issue when debug trace are not acitvated.
By the way, fix specifier for res argument that is a uint32_t.
=> core: kernel: tee_ta_manager.c: add uuid in open session error trace

mk/config.mk
CFG_REE_FS_ALLOW_RESET weakens rollback protection of REE FS secure storage and in turns breaks use-cases like rollback proteection of TAs etc. So explicitly warn user that CFG_REE_FS_ALLOW_RESET is intended for test purposes only and the added threat vectors if this option is enabled for release build.
=> mk: config.mk: Explicitly warn about CFG_REE_FS_ALLOW_RESET

mk/config.mk
Ensures that CFG_VIRTUALIZATION and CFG_NS_VIRTUALIZATION configuration settings do not conflict. If Both are set, they shall have the same value.
Clarifies CFG_VIRTUALIZATION is deprecated in mk/config.mk inline comments.
=> mk: config: clarify CFG_VIRTUALIZATION is deprecated

core/arch/arm/kernel/boot.c, core/arch/riscv/kernel/boot.c, core/include/kernel/dt.h, core/kernel/dt.c
Expand the data size of DTB transfer list entry to the max allocable size to reserve sufficient space for new nodes.
This fixes a potential issue that the amended DTB transfer entry overrides other entries followed by, when inserting new nodes.
=> core: fixup of transfer list entry overriding

core/tee/tee_svc.c
When calling `TEE_InvokeTACommand()` with a non-NULL memref of size zero, function `tee_svc_copy_param()` will return
`TEE_ERROR_BAD_PARAMETERS` resulting in a panic later on.
In regard to the `TEE_PARAM_TYPE_MEMREF_{INPUT,OUTPUT,INOUT}` types, the Global Platform specification says [1]:
> params[i].memref.size SHALL be initialized with a memory buffer that is accessible with the access rights described in the type. The buffer can be NULL, in which case size SHALL be set to 0 .
Note that the specification only specifies that `NULL` implies a size of zero. The reciprocal: _"a size of zero implies `NULL`"_ is undefined.
It is even more confusing considering that non-`NULL` buffer with a size of zero are explicitly allowed in the client API [2]:
> This design allows a non-NULL buffer with a …
=> core: tee_svc.c: allow to pass non-NULL memref of size 0

core/arch/arm/plat-hikey/main.c, core/arch/arm/plat-hikey/spi_test.c, core/arch/arm/plat-rockchip/platform.c, core/arch/arm/plat-rockchip/platform_px30.c, core/arch/arm/plat-rockchip/platform_rk3399.c, core/drivers/atmel_saic.c, core/drivers/bcm_hwrng.c, core/drivers/crypto/caam/hal/common/hal_jr.c, core/drivers/dra7_rng.c, core/drivers/imx_wdog.c, core/drivers/ls_dspi.c, core/drivers/ls_gpio.c, core/drivers/ls_i2c.c, core/drivers/regulator/regulator.c, core/drivers/smccc_trng.c, core/drivers/xiphera_trng.c, core/kernel/tpm.c, core/pta/bcm/gpio.c, lib/libmbedtls/core/ecc.c, lib/libutils/isoc/bget_malloc.c
The `*MSG()` macros take care of printing a newline. Adding a newline character '\n' is useless. Remove it.
The patch is mostly the result of this script:
```
git ls-files -z | xargs -0 sed -i -r 's/(MSG\(".*)\\n"/\1"/g'
```
with a bit of additional manual work to remove empty string literals. Example:
```c
DMSG("spi_base: 0x%" PRIxVA "\n", spi_base);
```
get transform by the script into:
```c
DMSG("spi_base: 0x%" PRIxVA "", spi_base);
```
and is then manually reworked into:
```c
DMSG("spi_base: 0x%" PRIxVA, spi_base);
```
=> tree-wide: do not print a newline at the end of the *MSG() macros

.github/workflows/ci.yml, core/drivers/clk/clk.c, core/include/drivers/clk.h, mk/config.mk
Adds clk_print_summary() to print the clock tree current state on core console using the info trace level. Clock framework spinlock is help while clock tree is printed.
=> drivers: clk: print clock tree summary

core/include/drivers/scmi-msg.h
Fix voltage domains inline comment header file.
=> scmi-msg: fix voltage domains inline comment header file

core/arch/arm/kernel/thread.c, core/drivers/atmel_piobu.c, core/drivers/atmel_wdt.c, core/drivers/gic.c, core/include/kernel/dt.h, core/include/kernel/dt_driver.h, core/include/kernel/interrupt.h, core/kernel/dt_driver.c, core/kernel/interrupt.c
Following changes done recently in the interrupt framework, this P-R is based on https://github.com/OP-TEE/optee_os/pull/6097. It provides means to use DT bindings to describe interrupts and their controllers.
2nd commit adds an API function (`dt_register_interrupt_provider()`)for interrupt controller drivers to register as itr_chip providers into the DT_DRIVER framework and few API functions for consumer driver to use DT info to find their interrupt (`interrupt_dt_get()`, `interrupt_dt_get_by_index()`, `interrupt_dt_get_by_name()`).
3rd commit Adds a API function to register a callback handler for an interrupt. 
`interrupt_create_handler()` differs from existing `interrupt_add_handler()` in that the former does not reconfigure the interrupt since already done by `interrupt_dt_get()` or …
=> core interrupt: use device tree data

core/arch/arm/dts/stm32mp131.dtsi, core/arch/arm/dts/stm32mp135f-dk.dts, core/arch/arm/plat-stm32mp1/conf.mk, core/arch/arm/plat-stm32mp1/drivers/stm32mp1_pwr.c, core/arch/arm/plat-stm32mp1/drivers/stm32mp1_pwr.h, core/arch/arm/plat-stm32mp1/drivers/stm32mp1_syscfg.c, core/arch/arm/plat-stm32mp1/drivers/stm32mp1_syscfg.h, core/arch/arm/plat-stm32mp1/platform_config.h, core/arch/arm/plat-stm32mp1/scmi_server.c, core/arch/arm/plat-stm32mp1/stm32_util.h, core/drivers/regulator/stm32mp13_regulator_iod.c, core/drivers/regulator/sub.mk, core/include/drivers/stm32mp13_regulator_iod.h
This series implements STM32MP1 variants IO domain feature.
- IO compensation for STM32MP13 variant
- High Speed Low Voltage for STM32MP13 and STM32MP15
- IO domain aware regulators for STM32MP13 variants
=> plat-stm32mp1: IO domains updates

ta/pkcs11/src/pkcs11_token.c
Fixes User PIN verification in ACL mode (protected authentication) so that it always returns PKCS11_CKR_USER_PIN_NOT_INITIALIZED when User PIN has not been initialized yet by the Security Officer. Before this change, this was tested only in the standard PIN path, not for the authenticated TEE identity mode (CFG_PKCS11_TA_AUTH_TEE_IDENTITY=y).
=> ta: pkcs11: prevent user ID verification when user PIN is not set

.github/workflows/ci.yml
Synchronize SCP-firmware Git repository revision on v2.13.0 release tag to avoid issues with latest merged changes in SCP-firmware that OP-TEE OS may not be compliant with.
=> ci: sync SCP-firmware on v2.13.0 release tag

.github/workflows/ci.yml, core/drivers/hisi_trng.c
Fixes error use of in IO_READ32_POLL_TIMEOUT() macro in hisi_trng
=> core: drivers: fix random number reading errors in hisi_trng

core/arch/arm/plat-stm32mp1/plat_tzc400.c
Fix build warning reported by recent toolchains when TZDRAM memory ends at the UINT32_MAX. This happends for example when building for the stm32mp1-157C_EV1 platform. In such case was GCC to emit the following warning trace:
core/arch/arm/plat-stm32mp1/plat_tzc400.c: In function ‘init_stm32mp1_tzc’: core/arch/arm/plat-stm32mp1/plat_tzc400.c:107:61: warning: conversion from ‘uint64_t’ {aka ‘long long unsigned int’} to ‘vaddr_t’ {aka ‘long unsigned int’} changes value from ‘4294967296’ to ‘0’ [-Woverflow]
107 |                 if (!tzc_region_is_non_secure(region_index, tzdram_end,
|                                                             ^~~~~~~~~~
Fixes: 59c253f92c6c ("plat-stm32mp1: check TZC400 configuration")
=> plat-stm32mp1: fix warning trace on TZC configuration check

core/arch/arm/plat-aspeed/conf.mk
AST2600 only supports VFPv3-D16, which should be speicifed by cflags to prevent undef-abort due to unsupoorted instructions generated by compilers.
=> arm: aspeed: Add cflags for AST2600 SoCs

core/arch/arm/dts/stm32mp157a-dk1.dts, core/arch/arm/dts/stm32mp157c-dk2.dts, core/arch/arm/dts/stm32mp157c-ed1.dts, core/arch/arm/dts/stm32mp15xx-dkx.dtsi
Enable STM32MP15 RCC secure hardening configuration on ST boards (DK1, DK2, ED1 and EV1) to assign SoC clocks, reset controllers and PWR regulators to OP-TEE secure world.
This change removes setting of &rcc node status property from stm32mp157a-dk1.dts, stm32mp157c-dk2.dts as the property is set from stm32mp15xx-dkx.dtsi that is included from the 2 former DTS files.
This change depends on https://github.com/OP-TEE/build/pull/701 for the OP-TEE distribution.
=> dts: stm32mp15: harden RCC secure configuration on ST boards

.github/workflows/ci.yml, core/drivers/regulator/regulator.c, core/include/drivers/regulator.h, mk/config.mk
Implementation of `regulator_print_tree()` as per @jenswi-linaro https://github.com/OP-TEE/optee_os/pull/6481#discussion_r1404590521 proposal.
Compared to #6481, this series only implements `regulator_print_tree()` and ensures it's built by CI. But not yet by CLang CI since it requires a fix as proposed by https://github.com/OP-TEE/optee_os/pull/6487.
=> drivers: regualtor: print tree

core/drivers/clk/clk.c, core/include/drivers/clk.h, mk/config.mk
This series mainly replaces the implementation of `clk_print_tree()` to not use recursive calls:
commit "drivers: clk: print tree without recursion".
There are 3 other minor changes added:
* use of SLIST instead of STAILQ list in clock tree print implementation;
* assert `clk_register()` argument is not NULL;
* stub `clk_print_tree()` when `CFG_DRIVERS_CLK_PRINT_TREE` is disabled.
This is a follow up of @jenswi-linaro proposal https://github.com/OP-TEE/optee_os/pull/6481#discussion_r1404590521, applied to the clock tree.
=> drivers: clk: print clock tree without recursive call

core/arch/arm/kernel/entry_a32.S
The NS entrypoint was originally backup from LR to R5. 
The commit f332e77c4b7c revises the register preservation to R8.
The way to retrieve the NS entrypoint for secondary cores should be updated as well.
Fixes: f332e77c4b7c ("core: arm: refactor boot argument handling")
=> core: arm: fix NS entrypoint for secondary cores

core/arch/arm/plat-aspeed/platform_ast2700.c, core/arch/arm/plat-aspeed/platform_config.h
Use gic_init_v3() with the GICR base address.
=> plat-aspeed: ast2700: use gic_init_v3()

core/include/mm/tee_mm.h, core/kernel/tee_ta_manager.c, core/mm/tee_mm.c, core/pta/stats.c, lib/libutee/include/pta_stats.h, lib/libutee/user_ta_entry.c, lib/libutils/ext/mempool.c, lib/libutils/isoc/bget_malloc.c, lib/libutils/isoc/include/malloc.h
Move definition of the statistics PTA API/ABI from various files (_pta/stats.c_, _tee_ta_manager.c_ and _malloc.h_) to a single header file (_lib/libutee/include/pta_stats.h_) exported to TA devkit. This changes make statistics PTA API definition more consistent regarding the definition of other the PTAs.
=> core: pta: stats: export and clarify statistics PTA API/ABI

.github/workflows/ci.yml, core/arch/arm/plat-stm32mp1/drivers/stm32mp1_pmic.c, core/arch/arm/plat-stm32mp1/scmi_server.c, core/drivers/regulator/regulator.c, core/drivers/regulator/stm32_vrefbuf.c, core/drivers/regulator/stm32mp13_regulator_iod.c, core/include/drivers/regulator.h
drivers: regulator: fix variable sized voltages fallback
Fix build issue reported by Clang on variable size field `desc` not being located at the end of `struct voltages_fallback`. The error was reported with a trace message like below:
````
core/include/drivers/regulator.h:118:4: warning: field 'voltages_fallback' with variable sized type 'struct voltages_fallback' not at the end of a struct or class is a GNU extension [-Wgnu-variable-sized-type-not-at-end]
} voltages_fallback;
^
core/drivers/regulator/regulator_fixed.c:27:19: warning: field 'regulator' with variable sized type 'struct regulator' not at the end of a struct or class is a GNU extension [-Wgnu-variable-sized-type-not-at-end]
struct regulator regulator;
^
2 warnings generated.
```
API function …
=> drivers: regulator: fix variable sized voltages fallback

core/arch/riscv/plat-virt/conf.mk
This commit updates the configurations for QEMU RISC-V virtual platform:
1. Enable CFG_RISCV_S_MODE and CFG_RISCV_SBI to run OP-TEE on S-mode and utilize SBI to communicate with M-mode firmware.
2. Do not force CFG_TEE_CORE_NB_CORE and CFG_NUM_THREADS to be 1, since we may run SMP system.
3. Disable CFG_BOOT_SYNC_CPU and CFG_BOOT_SECONDARY_REQUEST, since the boot sequence is controlled by M-mode firmware.
4. Enable CFG_WITH_STAT to build PTA for debug and statistics information.
5. Enable CFG_DT to parse the external DTB passed by M-mode firmware.
=> riscv: virt: Update the configurations

core/drivers/crypto/caam/include/caam_sm.h
Update return type of caam_sm_free() from TEE_Result to enum caam_status.
=> drivers: caam: update return type of caam_sm_free()

core/arch/arm/kernel/thread_optee_smc.c
Removes the size limit of 1 page imposed in
thread_rpc_alloc_kernel_payload(). The purpose of this limit was to error out early since the kernel doesn't supply a list of physical pages and the source of the error is not obvious at first glance. This is now about to change so remove the limit since the kernel now may supply the needed list of physical pages.
Link to corresponding kernel patch https://lore.kernel.org/lkml/20231026171650.515275-1-jens.wiklander@linaro.org/
=> core: arm: rpc_alloc: remove size limit for kernel payload

scripts/checkpatch_inc.sh
The following would fail with Zsh instead of Bash : $ source ./scripts/checkpatch_inc.sh
$ checkpatch HEAD
Unknown option: typedefsfile typedefs.checkpatch
Usage: .../scripts/checkpatch.pl [OPTION]... [FILE]
By setting xtrace in the _checkpatch() function, we can see the built command is interpreted differently depending on the shell:
$CHECKPATCH $CHECKPATCH_OPT $typedefs_opt -
In Zsh:
/scripts/checkpatch.pl '--typedefsfile typedefs.checkpatch' -
In Bash:
/scripts/checkpatch.pl --typedefsfile typedefs.checkpatch -
Bash differs from Zsh when it comes to word splitting for unquoted parameters expansions.
One solution is to use `eval` to execute the built command.
=> scripts: checkpatch: fix word splitting in the command

core/arch/arm/kernel/thread_spmc.c
Until now has FFA_PARTITION_INFO_GET always returned zero in w3, but FF-A v1.1 requires FFA_PARTITION_INFO_GET to return the size of each partition information descriptor returned if
FFA_PARTITION_INFO_GET_COUNT_FLAG isn't set. So fix this by returning the size of a FF-A v1.1 partition information descriptor in w3.
Fixes: a1c53023cc80 ("core: spmc: support FF-A 1.1")
=> core: ffa: return fpi size from FFA_PARTITION_INFO_GET

core/arch/arm/plat-aspeed/platform_ast2600.c, core/arch/arm/plat-aspeed/platform_ast2700.c, core/arch/arm/plat-corstone1000/main.c, core/arch/arm/plat-imx/main.c, core/arch/arm/plat-k3/main.c, core/arch/arm/plat-ls/main.c, core/arch/arm/plat-rcar/main.c, core/arch/arm/plat-rockchip/main.c, core/arch/arm/plat-rzn1/main.c, core/arch/arm/plat-stm/main.c, core/arch/arm/plat-stm32mp1/main.c, core/arch/arm/plat-stm32mp2/main.c, core/arch/arm/plat-sunxi/main.c, core/arch/arm/plat-ti/main.c, core/arch/arm/plat-zynq7k/main.c, core/drivers/gic.c, core/include/drivers/gic.h
@Amit-Radur, @b49020, @ChiaweiW, @clementfaure, @ememarar, @etienne-lms, @glneo, @grandpaul, @GseoC, @lorc, @MrVan, @Neal-liu, @pangupta, @sahilnxp, @sdininno 
Please check and ack your platforms. One difference for many platforms is that we rely on TF-A or the previous boot stage to initialize the GIC. I assume some unintended copy & paste error has led most platforms to reinitialize the GIC. If I'm wrong in that assumption, we'll see how we can fix it.
=> Remove git_cpu_init()

ta/pkcs11/src/object.c, ta/pkcs11/src/pkcs11_attributes.c, ta/pkcs11/src/pkcs11_attributes.h, ta/pkcs11/src/processing.c, ta/pkcs11/sub.mk
An attempt to support CKA_CHECK_VALUE attribute in PKCS 11 TA. For AES, the value of this attribute is derived from the key object by taking the first three bytes of the ECB encryption of a single block of null (0x00) bytes, using the default cipher associated with the key type of the secret key object. This is useful to detect that a key object has not tampered with. 
For now, we try to calculate the value when a symmetric key is randomly generated. Still need to add for (Create, Unwarp, Derive and Copy) in incoming commits.
Related issues: https://github.com/OP-TEE/optee_os/issues/6453, https://github.com/OP-TEE/optee_os/issues/6431
=> Add support of key check value CKA_CHECK_VALUE to PKCS11 TA

core/drivers/crypto/hisilicon/hisi_qm.c, core/drivers/crypto/hisilicon/include/hisi_qm.h
Flag in the qp structure is used to indicate whether the qp is occupied.The new task can find an unused qp and use it.
Fixes: c7f9abcee87f ("drivers: implement HiSilicon Queue Management (QM) module")
=> crypto: fix an issue of multiple tasks using the same qp

core/include/kernel/transfer_list.h
Add 4 reserved bytes at the tail of the transfer list header. This fixes a non-8-bytes aligned header when "flags" was introduced into the header.
Fixes: 508e2476b232 ("core: update transfer list header and signature")
=> core: fixup of transfer list header size

core/drivers/crypto/caam/caam_rng.c, core/drivers/crypto/caam/crypto.mk, core/drivers/crypto/caam/hal/common/hal_rng.c, core/drivers/crypto/caam/hal/common/registers/rng_regs.h, core/drivers/crypto/caam/include/caam_hal_rng.h
With CFG_NXP_CAAM_RNG_DRV enabled, OP-TEE will use the CAAM
to generate random numbers. Normal world access to the RNG is still
possible as the CAAM is TrustZone aware and provides multiple separate
job rings.
For complete isolation, however, access to CAAM reset and clocks need to
be managed as well. This could be done in theory by restricting access
to the reset and clock controller peripherals to the secure world and
exporting limited access to some resources via SCMI. There is no such
support yet for the i.MX and thus some setups may prefer to avoid using
the CAAM in OP-TEE to stay safe from normal world inducing glitches.
These setups may still need random numbers in OP-TEE. Therefore, access
so have them
access the CAAM only once at startup to initialize OP-TEE's PRNG and
defer …
=> caam: provide plat_rng_init if CFG_WITH_SOFTWARE_PRNG=y 

core/include/drivers/clk_dt.h
This header file does not include clk.h. Just declare `struct clk;` so that the dependency is handled.
=> Add missing clk.h include in clk_dt.h

lib/libutee/include/utee_defines.h, ta/remoteproc/Makefile, ta/remoteproc/include/ta_remoteproc.h, ta/remoteproc/src/elf_parser.c, ta/remoteproc/src/elf_parser.h, ta/remoteproc/src/remoteproc_core.c, ta/remoteproc/src/sub.mk, ta/remoteproc/src/user_ta_header_defines.h, ta/remoteproc/sub.mk, ta/remoteproc/user_ta.mk
This series introduces the remoteproc Trusted Application, which enables the authentication of signed images through the scripts/sign_rproc_fw.py script. 
The remote proc TA depends on a remoteproc PTA that must implement platform-specific requirements. To achieve this, a remoteproc PTA API is also introduced.
A ELF32 parser is also introduced. This parser, inspired from the Linux remoteproc parser,  get loadable sections and the resource table specific section.
For more details a presentation is available here: [LHR23-214 OP-TEE to extend the root of trust to the coprocessor](https://resources.linaro.org/en/resource/6c5bGvZwUAjX56fvxthxds)
Related pull request:
- https://github.com/OP-TEE/optee_os/pull/6027
Code associated to the Linux Kernel is proposed as RFC for upstream: …
=> Introduce remote proc trusted application

core/arch/arm/dts/stm32mp157a-dk1-scmi.dts, core/arch/arm/dts/stm32mp157c-dk2-scmi.dts, core/arch/arm/dts/stm32mp157c-ed1-scmi.dts, core/arch/arm/dts/stm32mp157c-ed1.dts, core/arch/arm/dts/stm32mp157c-ev1-scmi.dts, core/arch/arm/dts/stm32mp15xx-dkx.dtsi, core/arch/arm/plat-stm32mp1/conf.mk
For legacy reason and compatibility with existing platforms embedding OP-TEE with RCC secure hardening being disabled, introduce _-scmi.dts_ for the 4 ST boards STM32MP15x: DK1, DK2, ED1 and EV1 where we enable RCC security require non-secure world to use SCMI resources. Add platform flavors `157x_XXX_SCMI` to ease DTS selection.
_stm32mp15*-<board>.dts_ applies an insecure RCC configuration. _stm32mp15*-<board>-scmi.dts_ applies the secure RCC configuration. This better reflects the configurations supported in the Linux kernel and U-Boot source trees.
=> dts: add stm32mp15*-scmi.dts files for when RCC is secure

core/drivers/stm32_iwdg.c, core/include/drivers/stm32_iwdg.h
Fix configuration of the watchdog + enable service to get STM32 IWDG timeout range + prepare for watch early interrupt.
=> drivers: stm32_iwdg: fix config + prepare for watchdog early interrupt

core/arch/arm/kernel/thread_spmc_a64.S, core/arch/arm/plat-stm32mp2/main.c
* "core: arm: kernel_spmc: correct CFG_SECURE_PARTITION test"
Replace occurrences of `#if CFG_SECURE_PARTITION` to a `#ifdef` test as the
configuration switch is either defined or not defined.
* "plat-stm32mp2: fix test on CFG_STM32_UART"
Fix test directive on `CFG_STM32_UART` that is either defined or not defined.
=> core: fix #if CFG_xxx into #ifdef CFG_xxx

CHANGELOG.md
Hi,
I think this [commit](https://github.com/OP-TEE/optee_os/commit/3e8d5b1c6a3048671e687a35fd63dc11867ba06f) accidentally removed the correct section for 3.22.0, and the other section left is not having correct links
=> Fix links for 3.22.0

core/arch/arm/plat-sam/conf.mk
Fully disable the support of external device tree on SAM platforms because it isn't used, to fix the following warning:
`I/TC: Non-secure external DT found`
<s>And disable by default insecure configurations, to remove the following warning:
`I/TC: WARNING: This OP-TEE configuration might be insecure!`</s>
=> Fix some warnings on SAM platforms

core/arch/arm/include/arm64.h, core/drivers/crypto/hisilicon/hisi_qm.c, core/drivers/crypto/hisilicon/include/hisi_qm.h
1. mailbox operation need lock to ensure atomicity.
2. Optimize the mailbox read and write operations.
Fixes: c7f9abcee87f ("drivers: implement HiSilicon Queue Management (QM) module")
=> driver: crypto: hisilicon: Add the mailbox operation lock

core/arch/arm/include/kernel/tz_ssvce_pl310.h, core/arch/arm/kernel/tz_ssvce_pl310_a32.S, core/arch/arm/mm/core_mmu.c, core/arch/arm/plat-imx/imx_pl310.c
Hello!
I'm digging out an old issue with the PL310 cache controller : https://github.com/OP-TEE/optee_os/issues/4783
I'm not sure if I proceeded well for platform specific implementation.
Let me know what you think!
=> core: arm: allow cache_op_outer() to operate on non-secure buffers

ta/pkcs11/src/pkcs11_attributes.c, ta/pkcs11/sub.mk
This series fixes PKCS11 key check value implementation and default enable its support.
With these changes, PKCS11 key check value is now tested by OP-TEE CI tests and should succeed.
=> ta: pkcs11: fixes for key check value + default enable its support

core/arch/arm/kernel/spmc_sp_handler.c
Clear the memory descriptors in `FFA_MEM_RETRIEVE_RESP` calls in order to set the reserved fields to zero. The caller might check if the reserved fields are zero as it is stated in the FF-A spec. With FF-A v1.1 the memory transaction descriptor's 4 byte field at offset 24 has changed from reserved (MBZ) to Endpoint memory access descriptor size (non-zero). With the reserved field not cleared in the v1.0 descriptor, the caller cannot verify if it got the right version of the memory transaction descriptor.
This issue only affects the `FFA_MEM_RETRIEVE_RESP` call at the S-EL1 <-> S-EL0 interface, in all other cases the descriptors are cleared properly.
=> Clear FFA_MEM_RETRIEVE_RESP memory descriptor fields

core/drivers/crypto/hisilicon/hisi_qm.c, core/drivers/crypto/hisilicon/include/hisi_qm.h
When the mailbox operation times out, the software will free the temporary memory. The hardware does not cancel the mailbox operation and may continue to read and write the free memory.
To solve the problem, we alloc buffer which has the same lifecycle with qm.
Fixes: c7f9abcee87f ("drivers: implement HiSilicon Queue Management (QM) module")
=> driver: crypto: hisilicon: Fix temporary memory risk

ta/pkcs11/src/object.c, ta/pkcs11/src/pkcs11_attributes.c
Return `PKCS11_CKR_ATTRIBUTE_VALUE_INVALID` instead of a template inconsistency when the key check value attribute is wrong due to its size.
Preserve original object attributes when C_SetAttributeValue service fails instead of possibly changing object attributes before the whole new attribute set is validated.
=> ta: pkcs11: fixes for check value attribute

core/arch/arm/dts/sama5d2.dtsi, core/arch/arm/plat-sam/conf.mk, core/drivers/nvmem/atmel_sfc.c, core/drivers/nvmem/nvmem.c, core/drivers/nvmem/sub.mk, core/drivers/sub.mk, core/include/drivers/nvmem.h, core/include/kernel/dt_driver.h, core/kernel/dt_driver.c, mk/config.mk
Add support for nvmem devices using the existing device-tree bindings for nvmem cells.
Also provides a driver to expose hardware unique key and die id using this nvmem framework.
This allows to let the user of the SoC to specify were the key were written using "nvmem-cells".
The bindings for the nvmem-otp-key driver are not specify and might also be not the way to do
it since it does not really describe a hardware device but rather a software feature. Any ideas are
welcomed on that part.
=> drivers: nvmem: add DT API for nvmem provider and consumer

core/arch/arm/plat-stm32mp1/conf.mk
Correct platform flavor name 157C_EV1_SCMI, not 157F_EV1_SCMI.
Fixes: 36f1fd6d4930 ("dts: add stm32mp15*-scmi.dts files for when RCC is secure")
=> plat-stm32mp1: fix misnamed 157C_EV1_SCMI flavor

core/arch/arm/plat-rcar/conf.mk, core/arch/arm/plat-rcar/romapi.c
During repetitive testing I noticed that sometimes OP-TEE panics due to problems with Renesas HW random number generator. While proposed workaround seems to help, I believe it is better to disable this feature by default, at least until I can get some clarification from Renesas side, which can take quite time.
=> plat-rcar: disable HW RNG by default (and try to workaround the issue)

core/arch/arm/plat-imx/conf.mk
On imx8ulp and imx93, there is only one MU to comunicate with
ELE, which cannot be dedicated on OP-TEE side all the time.
There may be ELE services running on Linux side, which can
cause conflict with OP-TEE. So disablig ELE by default for now.
=> core: imx: disable ELE support on imx8ulp, imx93 by default

ldelf/ta_elf.c, lib/libutee/include/elf_common.h
Rust TAs built for no-std mode targeting 32-bit Arm architecture use ELFOSABI_ARM as the OS ABI within ELF header. So allow ldelf to load those Rust TAs built for 32-bit Arm.
=> ldelf: aarch32: Accept ELFOSABI_ARM as OS ABI

.github/workflows/ci.yml
Now that [1] is merged, Rust tests are enabled by default for QEMUv8 and there is no need for a separate Rust job in CI, so remove it.
Update the PATH so that the cargo command (which is installed locally during the build of the Rust SDK) can be found.
Disable Rust in the BTI+MTE+PAC test because the Rust examples fail to build with the supplied toolchain:
```
/usr/local/bin/../lib/gcc/aarch64-unknown-linux-uclibc/12.2.0/../../../../aarch64-unknown-linux-uclibc/bin/ld.bfd: /tmp/rustcmQty55/libcompiler_builtins-76fca0633b54e12b.rlib(45c91108d938afe8-cpu_model.o): in function `init_have_lse_atomics':
/cargo/registry/src/index.crates.io-6f17d22bba15001f/compiler_builtins-0.1.101/./lib/builtins/cpu_model.c:1075: undefined reference to `getauxval'
...
```
=> ci: Rust updates

CHANGELOG.md, mk/config.mk
Update CHANGELOG for 4.1.0 and collect Tested-by tags.
The 4.1.0-rc1 tag will be created on Friday January 12th and the 4.1.0 release is expected on January 19th.
=> Update CHANGELOG for 4.1.0

core/drivers/stm32_i2c.c
Main change: add missing load of stm32_i2c pinctrl state at driver init.
(Fixes: 73ba32eb0f6c ("drivers: stm32_i2c: support CFG_DRIVERS_PINCTRL"))
An preparatory commit simplifies local function `i2c_config_analog_filter()`.
=> drivers: stm32_i2c: apply pinctrl config at init

core/arch/riscv/mm/core_mmu_arch.c
According to RISC-V privileged ISA manual:
Each leaf PTE contains an accessed (A) and dirty (D) bit. The A bit indicates the virtual page has been read, written, or fetched from since the last time the A bit was cleared. The D bit indicates the virtual page has been written since the last time the D bit was cleared. When a virtual page is accessed and the A bit is clear, or is written and the D bit is clear, a page-fault exception is raised.
And the manual also suggests:
If the supervisor software does not rely on accessed and/or dirty bits, it should always set them to 1 in the PTE to improve performance.
Since OP-TEE does not rely on A/D bits, we by default set them to 1 to avoid unnecessary page-fault exceptions when OP-TEE touches those pages.
=> riscv: mm: Set A/D bits of PTE(page table entry) by default

core/arch/arm/kernel/thread_optee_smc.c, core/arch/arm/kernel/virtualization.c
There is standing issue with having two versions of OP-TEE binary: with virtualization enabled and without it. Correct variant needs to be present on board before booting rest of the system.
If non-virtualized variant is present and user tries to boot a hypervisor, hypervisor can (and should) detect that OP-TEE does not provide OPTEE_SMC_SEC_CAP_VIRTUALIZATION capability and fail gracefully.
On other hand, when virtualized variant of OP-TEE is booted, but user then boots directly into Linux (or any other OS), OP-TEE crashes:
E/TC:0 0 0 Core data-abort at address 0xffffffffffffffa0 (translation fault)
E/TC:0 0 0  esr 0x96000044  ttbr0 0x4418d000   ttbr1 0x00000000   cidr 0x0
E/TC:0 0 0  cpu #0          cpsr 0x00000184
E/TC:0 0 0  x0  0000000032000004 x1  0000000000000004
E/TC:0 0 0  x2 …
=> arm: virtualization: don't allow hypervisor to issue std calls

core/arch/arm/plat-rcar/conf.mk
Adjust the OP-TEE memory map for Gen4/S4 SoC to reflect changes of IPL layout made by Renesas. Now BL31 starts at 0x46400000, so we have less memory for OP-TEE.
(Rcar S4 is still not available for general public, so Renesas have time to experiments with IPL layouts. We are expecting S4SK board to be available soon, so I hope this is the last change to memory layout...  )
=> arm: plat: rcar: gen4: adjust memory map

core/arch/arm/plat-stm32mp2/conf.mk, core/drivers/stm32_rng.c
This P-R adds support for the hardware RNG of the STM32MP25.
It also reworks the way the RNG configuration is applied, as register values shouldn't be present in the device tree.
Having it in the compatible data seems acceptable as changing the RNG configuration would be uncommon.
=> drivers: stm32_rng: update RNG driver and support MP25

core/drivers/crypto/caam/hal/common/hal_rng.c, core/drivers/crypto/caam/hal/imx_8q/hal_rng.c
The SECO firmware enables the RNG prediction resistance by default. There is no need to read the CAAM RNG status registers.
=> drivers: caam: add caam_hal_rng_pr_enabled() for 8QX, 8DX platforms

core/arch/arm/plat-stm32mp1/shared_resources.c, core/include/drivers/stm32mp1_rcc.h
Disable RCC MCKPROT if not needed on STM32MP15 platforms to allow non-secure world to control Cortex-M coprocessor. This change is needed when RCC secure hardening is enabled (RCC[TZEN] control bit) as it also default enable RCC MCKPROT preventing non-secure world from accessing some coprocessor SoC resources.
=> plat-stm32mp1: shared_resource: disable MCKPROT if not needed

core/arch/riscv/kernel/kern.ld.S
Currently, the unclean .sbss section in RISC-V binary could be
problematic. This is because variables such as puts_lock may have
non-zero initial values, leading to failures in cpu_spin_trylock().
To address this issue, merge .sbss into .bss so that it is properly
cleared on boot. Both OpenSBI [1] and Linux [2] follow this approach.
Also, to benefit from global pointer relaxation, add .sdata after the
__global_pointer$ symbol.
Link: https://github.com/riscv-software-src/opensbi/blob/bb90a9ebf6d9a2fe7726978d594e82cdbaad7799/firmware/fw_base.ldS#L84 [1]
Link: https://github.com/torvalds/linux/blob/296455ade1fdcf5f8f8c033201633b60946c589a/include/asm-generic/vmlinux.lds.h#L1146 [2]
Signed-off-by: Yu Chien Peter Lin <peterlin@andestech.com>
Reviewed-by: Alvin Chang <alvinga@andestech.com>
=> core: riscv: Add .sbss and .sdata sections to linker script

.github/workflows/ci.yml
Since [1] there is no need to add $HOME/.cargo/bin to the user's PATH anymore. Therefore remove the corresponding lines from the CI scripts.
Link: https://github.com/OP-TEE/build/commit/xxxx [1]
=> ci: do not add $HOME/.cargo/bin to $PATH

core/arch/arm/plat-k3/drivers/sec_proxy.c
The trail bytes from the secure proxy driver were being overwritten, increase the count each time to not overwrite the existing data and not get the end data corrupted from secure proxy.
Fixes: cf20f0a4f77e ("plat-k3: drivers: Add secure proxy driver for communication with System Controller")
=> plat-k3: drivers: sec_proxy: increment while reading trail bytes

core/include/kernel/dt.h
When compiled with CFG_DT=n link the following error can occur: aarch64-linux-gnu-ld.bfd: out/arm/core/arch/arm/kernel/boot.o: in function `get_sec_mem_from_manifest': core/arch/arm/kernel/boot.c:1511: undefined reference to `dt_getprop_as_number' aarch64-linux-gnu-ld.bfd: core/arch/arm/kernel/boot.c:1519: undefined reference to `dt_getprop_as_number' aarch64-linux-gnu-ld.bfd: out/arm/core/mm/core_mmu.o: in function `collect_device_mem_ranges': core/mm/core_mmu.c:982: undefined reference to `dt_getprop_as_number' aarch64-linux-gnu-ld.bfd: core/mm/core_mmu.c:993: undefined reference to `dt_getprop_as_number'
Fix this by adding a stubbed version of dt_getprop_as_number() when CFG_DT=n.
Link: https://github.com/OP-TEE/optee_os/issues/6537
Fixes: 4e45454a85d3 ("core: add …
=> core: dt: provide stubbed dt_getprop_as_number()

.github/workflows/ci.yml
We recently hit a "No space left on device" error with the QEMUv8_Xen_check job. Apply the same workaround than in commit a03aafed30c2 ("ci: hafnium: fix "no space left on device" error") and commit 788069fa88ed ("ci: rust: fix "no space left in device" error").
=> ci: xen: fix "no space left in device" error"

core/drivers/crypto/stm32/stm32_saes.c
Correction selection of key in STM32 SAES driver that missed a left bit shift operation. The bug was not experienced before as current platform tests involve only the software key selection (_SAES_CR_KEYSEL_SOFT) which value is 0 and matches the SoC default key selection register value.
Fixes: 4320f5cf30c5 ("crypto: stm32: SAES cipher support")
=> drivers: crypto: stm32: fix SAES key selection

.github/workflows/ci.yml
Updatate the "checkout" action to fix the following warning:
Node.js 16 actions are deprecated. Please update the following
actions to use Node.js 20: actions/checkout@v3. [...]
=> ci: update actions/checkout@v3 to v4

core/arch/arm/kernel/timer_a64.c
read_cntfrq() can return a pretty large 32-bit number, multiplying that with a dealy of 1000 ms can overflow. Fix that by casting the result from read_cntfrq() to a uint64_t to avoid overflow during the calculation.
Fixes: ba6b29591828 ("core: arm64: Add Secure EL1 physical timer framework")
=> core: arm: fix integer overflow in generic_timer_handler()

core/arch/arm/dts/fsl-lx2160a.dtsi
With patch 8a6ca14 (core: arm: get DDR range from embedded DTB) now DDR ranges are taken from Embedded DTB if enabled and will ignore DDR ranges defined by register_ddr().
Since Dynamic shared memory and Embedded DTB config is enabled on LX2160A platforms, need to add the DDR ranges to the DTS.
=> core: dts: lx2160a: add memory region

.github/workflows/ci.yml
During my testing of build.git PR 731 ("optee_rust_examples_ext: Fix Rust toolchain conflicts"), I noticed that the "no space left on device" error was triggered yet again (obviously due to more size being taken on the disk by the Rust toolchain and the OP-TEE Rust examples).
Therefore, preventively apply the same fix as for other jobs. This way the CI should pass when 731 is merged.
Link: https://github.com/OP-TEE/build
=> ci: qemuv8: preventively avoid "no space left on device" error

core/include/crypto/crypto_impl.h
Correct definition of crypto_asym_get_ecc_keypair_ops() stub inline function when CFG_CRYPTO_ECC is disabled. The definition used a wrong function label.
Fixes: 5516c6cd78da ("core: ecc: support the crypto driver")
=> core: crypto: fix crypto_asym_get_ecc_keypair_ops() stub

ta/pkcs11/src/pkcs11_attributes.c
Add missing __maybe_unused attribute for function arguments not used when the pkcs11 TA is built with NDEBUG directive.
Fixes: 63f89caa9022 ("ta: pkcs11: attribute helper functions")
=> ta: pkcs11: fix build warning on unused variable

core/drivers/crypto/hisilicon/hisi_qm.c
1. support num = 0 in qm_set_vt_common().
2. release qp when qm_xqc_cfg() failed.
3. add check of msg and qp->num in hisi_qp_recv_sync().
=> driver: crypto: hisilicon: fix error handling

core/arch/arm/plat-stm32mp1/conf.mk, core/drivers/crypto/stm32/authenc.c, core/drivers/crypto/stm32/cipher.c, core/drivers/crypto/stm32/stm32_saes.c
Implement AES software operation for when AES key is 192 bit that is not supported by the STM32 SAES engine.
This P-R includes cleanup and preparatory patches followed by the above mentioned AES-192b software fallback implementation.
=> drivers: crypto: stm32_saes: fallback to software on 192bit AES keys

core/include/io.h
Fix detection of timeout condition in IO_READ32_POLL_TIMEOUT() that was never triggered when delay argument is 0us. Indeed 0 is not a useful increment value for a timeout counter.
Fixes: 97ea199a2ae8 ("core: io: IO_READ32_POLL_TIMEOUT()")
=> core: io: fix IO_READ32_POLL_TIMEOUT() when delay is 0us

core/crypto.mk, core/drivers/crypto/caam/acipher/caam_dh.c, core/drivers/crypto/caam/acipher/caam_dsa.c, core/drivers/crypto/caam/acipher/caam_ecc.c, core/drivers/crypto/caam/acipher/caam_prime_dsa.c, core/drivers/crypto/caam/acipher/caam_prime_rsa.c, core/drivers/crypto/caam/acipher/caam_rsa.c, core/drivers/crypto/caam/caam_ctrl.c, core/drivers/crypto/caam/caam_key.c, core/drivers/crypto/caam/caam_rng.c, core/drivers/crypto/caam/crypto.mk, core/drivers/crypto/caam/hash/caam_hash_mac.c, core/drivers/crypto/caam/include/caam_desc_defines.h, core/drivers/crypto/caam/include/caam_desc_helper.h, core/drivers/crypto/caam/include/caam_key.h, core/drivers/crypto/caam/include/caam_trace.h, core/drivers/crypto/caam/include/caam_utils_status.h, core/drivers/crypto/caam/sub.mk, mk/config.mk
The CAAM provides a key encapsulation mechanism called Black key. This is a protection of user keys against bus snooping attacks when the keys are being written or read from external memory (outside the SoC). The black key mechanism encapsulates/decapsulates keys on the fly in an encrypted data structure called a black key. Before copying the plain text key to memory, the CAAM automatically encrypts the key in the black key format using a key encryption key. This key encryption key is called JDKEK - Job ring descriptor key encryption key.
There are two different black key formats
- AES-ECB : The key is encrypted using AES-ECB. The resulting black key will a multiple of 16 bytes. => AES-ECB(plain text key + zero padding)
- AES-CCM : The key is encrypted using AES-CCM (slower than ECB). …
=> CAAM Black key support for asymmetric crypto

core/mm/core_mmu.c
Handle MEM_AREA_ROM_SEC in check_mem_map switch case.
Fixes: fc7e0cc38b99 ("core: MEM_AREA_ROM_SEC maps secure read only cached memory")
=> core: mmu: add MEM_AREA_ROM_SEC in check_mem_map

core/arch/riscv/mm/core_mmu_arch.c
In current implementation, we always set `PTE_V` bit when we create PTE by `core_mmu_pte_create()`.
But when OP-TEE wants to free the pages, we should set zero value into PTE.
This PR fixes this behavior.
The desired PTE bits are already translated from the memory attributes.
Therefore, it is unnecessary to explicitly set `PTE_V` bit in `core_mmu_pte_create()`.
=> RISC-V: Fix creation of PTE when OP-TEE frees the pages

.gitignore
Hello,
While coding, some IDE creates folder to stores tags or project settings.
Some developers even have development tools that can be configured by project once they find a specific dot file in the project source directory.
This patch aims to leave developer do what they want to do with their tools and project configuration by ignoring all dot files and dot folders.
=> .gitignore: Ignore all dot files and folder except the existing ones

core/drivers/clk/sam/at91_clk.h, core/drivers/clk/sam/at91_generated.c, core/drivers/clk/sam/at91_master.c, core/drivers/clk/sam/clk-sam9x60-pll.c, core/drivers/clk/sam/sama5d2_clk.c
=> drivers: clk: sam: update main, generic and PLL clocks for Microchip sama7g54

core/arch/arm/plat-sam/conf.mk
Disable the dynamic shared memory allocation that isn't used on SAM
platforms, otherwise the following issue occurs, since the commit
https://github.com/OP-TEE/optee_os/commit/8a6ca1480ddce97894e19bc3bcb57c79967e161c ("core: arm: get DDR range from embedded DTB"):
```
I/TC: Embedded DTB found
E/TC:0 0 check_phys_mem_is_outside:409 Non-sec mem (0x20800000:0x1f800000) overlaps map (type 18 0x21400000:0x1000)
E/TC:0 0 Panic at core/mm/core_mmu.c:413 <check_phys_mem_is_outside>
E/TC:0 0 TEE load address @ 0x20000000
E/TC:0 0  0x20005655 print_kernel_stack at core/arch/arm/kernel/unwind_arm32.c:109
E/TC:0 0  0x2001c52d __do_panic at core/kernel/panic.c:80
E/TC:0 0  0x200276c1 check_phys_mem_is_outside at core/mm/core_mmu.c:413
E/TC:0 0  0x2002780f …
```
=> plat-sam: fix static shared memory address and size

core/arch/arm/plat-stm32mp2/stm32mp_pm.c, core/arch/arm/plat-stm32mp2/stm32mp_pm.h, core/arch/arm/plat-stm32mp2/sub.mk, core/include/kernel/pm.h
This series add a preliminary support of low power mode on STM32MP25 SoC, including power off,
and perform the needed OP-TEE bookkeeping before PSCI stack in TF-A BL31 executes a power management sequence.
The pm function for STM32MP25 drivers  will use the generic HINTs to save the IP configuration 
(PM_HINT_CONTEXT_STATE) or stop their clock (PM_HINT_CLOCK_STATE).
Only the STPMIC25 driver should use the power level information, saved in the PLATFORM_STATE part of HINT 
(bit 16:31), to configure in the PMIC the requested supply configuration for the select low power mode.
So this series provide the needed macros, PM_HINT_IS_STATE()  and defines PM_.*_LEVEL
to implement the pm functions in STM32MP25 driver and in PMIC (STPMIC25) driver in next patches.
Regards
Patrick.
=> plat-stm32mp2: add pm support on stm32mp25 

core/drivers/clk/clk-stm32mp13.c, core/drivers/clk/clk.c, core/include/drivers/clk.h, core/include/drivers/clk_dt.h
Add an API function to get a clock duty cycle ratio.
Add an API function to get clock linear supported rates description.
Add a clock flag to pre-enable a parent clock before a clock a re-parented.
Update STM32MP13 clock driver.
=> drivers: clk: duty cycle, reparent pre-enable, linear rates description

core/arch/arm/plat-imx/conf.mk
This enables the TrustZone Address Space Controller (TZ380) driver for all members of the i.MX8M soc family. Enabling the driver ensures protection of the OP-TEE memory regions, so that only the secure world can access it.
=> core: imx: enable TZC380 driver for all i.mx8m socs

core/arch/arm/include/kernel/delay_arch.h, core/arch/riscv/include/kernel/delay_arch.h, core/arch/riscv/riscv.mk, core/include/kernel/delay.h, core/kernel/delay.c
This P-R adds API function `timeout_elapsed_us()` to measure the time since or until an initialized timeout reference is elapsing. This function relies on other `timeout_*()` API functions and therefore depends on `CFG_CORE_HAS_GENERIC_TIMER` being enabled.
While at it, I factorize the `timeout_*()` function between `arm` and `riscv` architectures and slightly touched `mdelay()`.
I also changed _arch/risc/risc.mk_ to force `CFG_CORE_HAS_GENERIC_TIMER` instead of relying on _mk/config.mk_ default enabling that switch.
=> core: kernel: add timeout_elapsed_us()

core/include/kernel/spinlock.h
cpu_spin_lock_xsave() masks exceptions, takes the spinlock and returns previous exception state to be restored by cpu_spin_unlock_xrestore(). The previously returned exception state must always be supplied so add the __must_check attribute to cpu_spin_lock_xsave() and its debug variants.
=> core: add __must_check attribute to cpu_spin_lock_xsave()

core/drivers/regulator/regulator.c, core/include/drivers/regulator.h
Always read current voltage level from the device instead of caching the level in struct regulator. This fixes issues for when the regulator level value depends on the parent regulator (supply). It is up the regulator driver to cache or not this value in their private data if applicable.
=> drivers: regulator: read current level from the device

core/arch/arm/plat-synquacer/rng_pta.c
Add missing initialization value to local variables in synquacer platform RNG driver to better comply with OP-TEE OS coding style and prevent developers from being confused when using this example as a example.
No functional change.
I propose this change because, when cleaning the patches related to https://github.com/OP-TEE/optee_os/pull/6729 I saw that driver infringes few OP-TEE OS coding style rules and deserve to be updates for the consistency of the source tree.
@b49020, please tell me if you're ok with such modifications.
=> plat-synquacer: add initialization value to local variables

core/drivers/clk/clk-stm32mp13.c
Fix oscillators struct clk instances for STM32MP13 clock driver. These clocks have 1 parent that is set during driver initialization, based on device tree content, whereas referred bugged commit defined 0 parents and did not allocate memory for the parent reference.
Fixes: 95f2142bf848 ("drivers: clk: clk-stm32mp13: don't gate/ungate oscillators not wired")
=> drivers: clk: clk-stm32mp13: fix memory corruption on oscillator parent

ta/pkcs11/src/processing_symm.c
Function step_symm_operation() defines a local variable to reference the session processing context but uses both session reference and this local variable which can be confusing when reading the code. Change the implementation to only use the local variable for consistency. No functional changes.
=> ta: pkcs11: Clarify context reference in step_symm_operation()

core/arch/arm/kernel/boot.c, core/arch/arm/kernel/entry_a64.S, core/include/kernel/boot.h
I wasn't able to reproduce the problem reported in https://github.com/OP-TEE/optee_os/issues/6649 with the FVP Foundation model or Base model. In the Foundation model, MTE was disabled, so not much to test. With the Base model, I was able to enable MTE with `-C cluster0.memory_tagging_support_level=2`, but it still didn't abort when clearing tags without MMU enabled.
I'm fixing the issue differently here since we're mapping the RO/RX parts with tags also. I'm not sure if that makes sense, but we don't want to risk having garbage in the memory tags or we could have problems.
@odeprez, @sichunqin does this fix the memtag issue for you?
=> Memtag fix

core/arch/riscv/include/kernel/thread_arch.h, core/arch/riscv/include/kernel/thread_private_arch.h, core/arch/riscv/include/riscv.h, core/arch/riscv/kernel/abort.c, core/arch/riscv/kernel/asm-defines.c, core/arch/riscv/kernel/thread_arch.c, core/arch/riscv/kernel/thread_optee_abi_rv.S, core/arch/riscv/kernel/thread_rv.S, core/arch/riscv/mm/core_mmu_arch.c
This series include some refactoring for thread control and SMP fixes:
1. Apply exception return to `thread_resume()` and `thread_exit_user_mode()`.
2. Save thread_core_local into CSR scratch, instead of saving kernel stack pointer, when thread is in user mode.
3. Add missing `thread_{mask/unmask}_exceptions()` during operations on page table.
=> RISC-V: Refactor thread control

core/arch/riscv/kernel/entry.S, core/arch/riscv/kernel/thread_optee_abi_rv.S, core/arch/riscv/plat-virt/conf.mk, core/arch/riscv/riscv.mk
In system of S-mode OP-TEE, M-mode firmware transfers control flow to OP-TEE during boot. M-mode runs one hart, which called boot hart, to executes system initialization and jumps into OP-TEE.
However, the ID of boot hart might not be always zero. That is, M-mode firmware may choose a hart, whose ID is non-zero, to jump into OP-TEE "_start" symbol to do OP-TEE initialization. Therefore, it is not feasible to let all harts enter "_start" symbol, and judge whether current hart is primary boot hart, by checking ID is zero or not. Fix it by letting non-boot hart enter "reset_secondary", in S-mode OP-TEE. So that all the harts can do their right things regardless of their hart ID.
Only OP-TEE runs in M-mode will judge primary hart by checking whether the hart ID is zero.
=> core: riscv: Modify S-mode boot flow to compatible with M-mode firmware

core/arch/arm/include/kernel/thread_private_arch.h
When adding "make check CFG_WITH_PAGER=y CFG_TEE_CORE_LOG_LEVEL=0" to the QEMUv8 CI job, I noticed that OP-TEE fails to boot and hangs with no message printed on the console. The root cause is memory corruption of the translation tables triggered by a stack overflow. Fix this by removing the particular case for log level 0.
Suggested-by: Jens Wikander <jens.wiklander@linaro.org>
=> core: arm64: increase STACK_ABT_SIZE from 1024 to 3072 when log level is 0

core/arch/riscv/include/mm/core_mmu_arch.h, core/arch/riscv/kernel/asm-defines.c, core/arch/riscv/kernel/entry.S, core/arch/riscv/mm/core_mmu_arch.c
To support multiple hart environment, each hart must have its dedicated root page table.
This series enlarges the root page table to be array, and allocates each root page for each hart.
Besides, the value of CSR SATP, which holds the base address of the root page table, is also prepared for each hart.
Each hart configures its SATP in `set_satp` macro at boot time, by getting value of SATP from `struct core_mmu_config`.
=> RISC-V: Allocate root page tables for multiple hart environment

core/arch/arm/include/kernel/thread_spmc.h, core/arch/arm/kernel/secure_partition.c, core/arch/arm/kernel/spmc_sp_handler.c, core/arch/arm/kernel/thread_spmc.c
When OP-TEE implements the S-EL1 SPMC, from an FF-A point-of-view the core OP-TEE functionality is running in a logical SP that resides at the same exception level as the SPMC. This means that the SPMC and the SP should have separate FF-A IDs, i.e. the SPMC ID and a normal endpoint ID for the SP. The SPMC ID is described in the SPMC manifest which gets parsed by the SPMD, so this ID should be queried from the SPMD. OP-TEE's endpoint ID is assigned by the SPMC.
Currently OP-TEE's FF-A endpoint ID and the SPMC ID are mixed together and hardcoded, this patch implements the correct ID handling mechanism as described above.
=> core: spmc, sp: cleanup FF-A ID handling

core/drivers/clk/clk.c, core/drivers/regulator/regulator.c, core/include/drivers/clk.h, core/include/drivers/regulator.h, core/include/kernel/mutex_pm_aware.h, core/include/kernel/spinlock.h, core/kernel/mutex.c
New proposal for the change posted in https://github.com/OP-TEE/optee_os/pull/6724.
This P-R propose a (somewhat) generic implementation for the "PM aware" mutex and apply it the the clock framework (to replace current spinning lock) and in the regulator framework (which already implements the sequence that was seen to weak during https://github.com/OP-TEE/optee_os/pull/6724 review.
=> drivers: mutex for clock and regulator valid during PM suspend/resume sequences

core/kernel/panic.c
Must be "preemption" instead of "prehemption".
=> core: kernel: Fix typo in __do_panic()

core/drivers/firewall/stm32_rifsc.c, core/drivers/stm32_rng.c
Remove use of `CFG_PM` config switch that is not defined in OP-TEE OS.
=> stm32 drivers: remove use of undefined CFG_PM

core/drivers/stm32_i2c.c, core/include/drivers/stm32_i2c.h
Protect concurrent accesses to an STM32 I2C bus with a PM aware mutex.
=> drivers: stm32_i2c: protect bus access with a mutex

.github/workflows/ci.yml
Add a job to build and run tests with QEMU for Arm v7 (32-bit). The build flags are imported from the IBART job definition [1] since IBART is being deprecated.
Link: https://github.com/jbech-linaro/ibart/blob/b585163626341864790398df6489c9556e0b20f1/jobdefs/examples/optee_qemu.yaml#L40C26-L40C176 [1]
=> ci: add QEMUv7 job

core/kernel/user_ta.c
Before this patch, the TA cancellation mask was only reset when the session was created, but the GP spec requires the cancellation mask to be reset each time a TA is entered via one of its entry points. So fix this by resetting the cancellation mask at the same time as when setting the cancellation request timeout.
Link: https://github.com/OP-TEE/optee_test/issues/731
Fixes: b01047730e77 ("Open-source the TEE Core")
Depends on https://github.com/OP-TEE/optee_test/pull/732
@bvalliere @c-auger please provide your email addresses if you want a `Reported-by:` tag for this patch.
=> core: reset cancellation mask on TA entry

core/drivers/atmel_wdt.c
In sama7g5 there's a DWDT (Dual Watchdog Timer) and the registers are not the same as the wdt for sama5d2. Here the DWD is handled as 2 watchdogs.
=> drivers: atmel_wdt: upgrade to support sama7g5 watchdog

CHANGELOG.md, mk/config.mk
The 4.2.0-rc1 tag will be created on Friday April 5th 2024 and the 4.2.0 release is expected on April 12th 2024.
=> Update CHANGELOG for 4.2.0

.github/workflows/ci.yml, core/arch/arm/kernel/thread_spmc.c, core/core.mk, mk/config.mk
tee_entry_get_os_revision() stores TEE_IMPL_GIT_SHA1 into a 32 or 64-bit register, depending on the platform. Unfortunately the command that creates TEE_IMPL_GIT_SHA1 does not provide any guarantee that the value will fit. For instance it can happen that 8 characters are not enough to disambiguate two commits in the repository, in which case git rev-parse --short=8 will happily return 9 or more characters. In this case a 32-bit build would display a warning and TEE_IMPL_GIT_SHA1 would be truncated in a way we don't want (discarding the most significant bits).
Therefore, make sure TEE_IMPL_GIT_SHA1 is exactly 8 or 16 hexadecimal characters (plus the leading 0x).
=> core: make sure tee_entry_get_os_revision() uses a proper TEE_IMPL_GIT_SHA1

core/include/kernel/mutex.h, core/include/kernel/notif.h, core/include/kernel/wait_queue.h, core/include/optee_rpc_cmd.h, core/kernel/mutex.c, core/kernel/notif.c, core/kernel/wait_queue.c
We have added a timeout parameter to the rpc notify for greater flexibility. The tee driver checks this parameter to decide which wait_for_completion will use. If the timeout is set to 0, it means waiting MAX_SCHEDULE_TIMEOUT.
The corresponding patch is here. [optee: support wq_sleep_timeout
](https://patchwork.kernel.org/project/linux-mediatek/patch/20240125052744.18866-1-gavin.liu@mediatek.com/)
=> add support timeout for notify and condvar

core/arch/riscv/include/riscv.h, core/arch/riscv/kernel/csr_detect.S, core/arch/riscv/kernel/sub.mk, core/arch/riscv/plat-virt/conf.mk, core/drivers/riscv_zkr_rng.c, core/drivers/sub.mk
The RISC-V Zkr entropy source extension provides NIST SP 800-90B or BSI AIS-31 compliant physical entropy source via seed CSR.
To allow OP-TEE OS (S-mode) to read the CSR, mseccfg.SSEED bit is expected to be set by M-mode. As we cannot read mseccfg here, use a test trap handler to verify the accessibility of seed.
=> drivers: Add RISC-V Zkr hardware random number generator support

ldelf/ta_elf.c
Fix the strange values of "pa" when TA ELF mappings is dumped.
The function argument of print_seg() should be explicit physical address of mapping rather than offset of the segment.
=> ldelf: Fix dumping physical address of ELF segment

core/arch/arm/plat-sam/conf.mk
When locking the PL310 cache, it behaves as disable which lead to poor performances in Linux.
The commit is cherry-picked and updated from https://github.com/linux4sam/optee_os-at91/commit/dfacffeb90f03c12dc3b2bbb13fbae6a154f8beb
=> plat-sam: remove CFG_PL310_LOCKED

core/include/drivers/stpmic1_regulator.h, core/lib/scmi-server/sub.mk
These changes apply to the SCP-firmware OP-TEE currently points to (v2.13.0). They'll need to be considered also when we'll upgrade to a more recent version of SCP-firmware, as proposed in P-R #6769.
=> Fixes for SCP-firmware support

lib/libutee/tee_api_operations.c
In tee_buffer_update, libutee currently delays processing an input block until more space is needed in the buffer, which is perfectly valid behavior, but doesn't match AOSP compatibility requirements.
Specifically, both CTS ([testKatEncryptOneByteAtATime](https://android.googlesource.com/platform/cts/+/refs/heads/main/tests/tests/keystore/src/android/keystore/cts/BlockCipherTestBase.java#779)) and VTS ([EncryptionOperationsTest.*OneByteAtATime](https://android.googlesource.com/platform/hardware/interfaces/+/refs/heads/main/security/keymint/aidl/vts/functional/KeyMintAidlTestBase.cpp#827)) expect block cipher implementations to produce an output block as soon as a full block of input has been received. Change libutee behavior to be AOSP compatible.
=> Make libutee buffering AOSP compatible

core/arch/arm/crypto/aes_modes_armv8a_ce_a64.S, lib/libutee/tee_api_operations.c
This includes "libutee: process a full buffer immediately" cherry-picked from https://github.com/OP-TEE/optee_os/pull/6791 so please ignore that while reviewing this PR.
This fixes an issue found with updated xtest regression tests, https://github.com/OP-TEE/optee_test/pull/741
=> Cipher buf fixes

core/drivers/crypto/hisilicon/crypto.mk, core/drivers/crypto/hisilicon/hpre_dh.c, core/drivers/crypto/hisilicon/hpre_main.c, core/drivers/crypto/hisilicon/include/hpre_dh.h, core/drivers/crypto/hisilicon/include/hpre_main.h, core/drivers/crypto/hisilicon/sub.mk
add operation of DH algorithm, including alloc_keypair, gen_keypair and shared_secret
=> drivers: crypto: hisilicon: add DH algorithm

core/drivers/crypto/hisilicon/include/sec_main.h, core/drivers/crypto/hisilicon/sec_main.c, core/drivers/crypto/hisilicon/sub.mk
HiSilicon SEC is used in security applications such as authentication and data encryption and decryption. This module implement the hardware initialization of the SEC.
=> drivers:implement HiSilicon Security Engine(SEC) module.

core/mm/core_mmu.c
The 6th parameter of add_phys_mem() has to be the size of memory region and not the end address of the region.
=> core: mmu: fix collect_device_mem_ranges() to pass size

core/kernel/callout.c
In callout_service_cb() when a timeout interrupt is received there's a check to see if this is the last scheduled CPU. If not the interrupt is ignored, but not disabled causing it to trigger again and again. So fix this by disabling the timeout too.
Fixes: cf707bd0d695 ("core: add callout service")
=> core: callout: disable obsolete timeouts

lib/libutils/ext/include/util.h
The macro has a problem when it is used in an assembly file: .e.g ".word GENMASK_32(15, 8)" will be compiled to ".word 0xffffff00"
The issue is caused by the compiler shift right a 64-bit ~0 instead of a 32-bit ~0. Fix it by using shift left.
Maybe it's a compiler issue and just do a workaround here.
The compiler I tested is `gcc-arm-8.2-2019.01-x86_64-arm-linux-gnueabi`.
```
Target: arm-linux-gnueabi
Configured with: /tmp/dgboter/bbs/rhev-vm2--rhe6x86_64/buildbot/rhe6x86_64--arm-linux-gnueabi/build/src/gcc/configure --target=arm-linux-gnueabi --prefix= --with-sysroot=/arm-linux-gnueabi/libc --with-build-sysroot=/tmp/dgboter/bbs/rhev-vm2--rhe6x86_64/buildbot/rhe6x86_64--arm-linux-gnueabi/build/build-arm-linux-gnueabi/install//arm-linux-gnueabi/libc --with-bugurl=https://bugs.linaro.org/ …
```
=> libutils: util.h: fix the GENMASK_32(h, l) macro for been used in assembly file

core/drivers/atmel_shdwc.c, core/drivers/pm/sam/at91_pm.c, core/include/drivers/atmel_shdwc.h, core/include/drivers/pm/sam/atmel_pm.h
=> drivers: sam: update drivers for sama7g5 pm support

core/arch/arm/kernel/thread_spmc.c
The FF-A direct request handling has an error: if the destination ID is the SPMC ID, the handler is trying to forward the message to an SP with this ID, which is obviously non-existent so this gives an error.
=> core: spmc: fix direct request handler

core/drivers/regulator/regulator.c
2 changes:
* Fix case when `.supported_voltages()` handler is supported to assert voltage description when the handler succeeds and to use pre-filled fallback description when the handler returns `TEE_ERROR_NOT_SUPPORTED` instead of asserting @*desc content while that pointer was likely not initialized with a valid address.
Fixes: af5b9881111c ("drivers: regulator: supported voltage consider levels bounds")
* Split assertions in `regulator_supported_voltages()` to ease debugging, providing a better indication of which condition is not fulfilled.
=> drivers: regulator: fix error case in regulator_supported_voltages() + split asserts

core/arch/arm/plat-vexpress/main.c, core/drivers/ffa_console.c, core/drivers/sub.mk, core/include/drivers/ffa_console.h, core/kernel/console.c, mk/config.mk
This console driver uses FFA_CONSOLE ABI to write the trace logs.
If CFG_FFA_CONSOLE is enabled, OP-TEE will try to initialize the FFA console driver.
=> drivers: Add FFA_CONSOLE based console driver for log

core/arch/riscv/kernel/entry.S
The thread_core_local flags is a 32-bit variable.
Thus, we must explicitly use "lw" and "sw" instructions, which mean load and store 32-bit value from specific memory address, to operate the thread_core_local flags.
=> core: riscv: Fix store 32-bit thread_core_local flags

core/crypto/signed_hdr.c
Prior to this patch, if SHDR_GET_SIZE() overflows it will return 0 and further down in the function lead to an out-of-bounds access. So fix this with an explicit test before using shdr_size in shdr_alloc_and_copy().
Fixes: 064663e8bd27 ("core: crypto: add struct shdr helper functions")
=> core: fix possible overflow in shdr_alloc_and_copy()

core/arch/arm/mm/tee_pager.c
It seems that the parameters are inverted. More of these are present in libtomcrypt.
Note: I haven't been able to test this patch yet as I don't have a board with me this week. Therefore, I didn't add the `Fixes:` yet.
=> core: pager: fix arguments passed to calloc in alloc_merged_pgt_array()

core/drivers/crypto/stm32/cipher.c
Remove assertions added by the commit referred below. They are useless since the handlers are registered only if the related device (stm32_cryp or stm32_saes) has its driver successfully probed. These assertion also prevent enabling both CFG_STM32_SAES and CFG_STM32_CRYP for a platform which is a valid configuration for when we rely on the DT to state which of both is enabled.
Fixes: 03de2c7bb316 ("drivers: crypto: stm32_saes: fallback to software on 192bit AES keys")
=> drivers: crypto: remove assertions on device handlers

lib/libutils/ext/include/fault_mitigation.h
Add a more compiler friendly 32-bit implementation of FTMN_FUNC_HASH(). This gives the same output as the previous 64-bit based implementation, but base the computation on 32-bit values.
=> core: compiler friendly 32-bit FTMN_FUNC_HASH() version

core/lib/libtomcrypt/aes_accel.c
Fix building OP-TEE with:
make PLATFORM=vexpress \
PLATFORM_FLAVOR=juno \
CFG_CRYPTOLIB_NAME=mbedtls \
CFG_CRYPTOLIB_DIR=lib/libmbedtls
...
core/lib/libtomcrypt/aes_accel.c: In function ‘aes_ctr_encrypt_nblocks’: core/lib/libtomcrypt/aes_accel.c:182:21: error: ‘CTR_COUNTER_LITTLE_ENDIAN’ undeclared (first use in this function)
182 |         if (mode == CTR_COUNTER_LITTLE_ENDIAN) {
=> core: ltc: Fix building with mbedtls

scripts/ftrace_format.py
When the time spent in a function is 1 second or more, display it as seconds not milliseconds in order to keep the output nicely aligned.
=> ftrace: ftrace_format.py: display seconds

core/include/kernel/user_ta.h
It seems that "ta_time_offs" member is unused now. Thus, remove it from user_ta_ctx structure.
=> core: kernel: Remove unused ta_time_offs in user_ta_ctx

mk/checkconf.mk
The combination of building with -g3 (which emits definitions of all defined preprocessor macros to the debug info) and using a full path to define the name of this preprocessor guard means that the output is not binary reproducible across different build hosts. For example, in my Yocto build, the string
__home_ravi_yocto_tmp_glibc_work_stm32mp135fdk_oe_linux_gnueabi_optee_os_stm32mp_3_19_0_stm32mp_r1_1_build_stm32mp135f_dk_include_generated_conf_h_
appears in several build artifacts. Another developer or buildbot would not build in some /home/ravi/... directory.
In order to increase binary reproducibility, only use the path sans the $(out-dir)/ prefix of the conf.h file.
=> checkconf.mk: do not use full path to generate guard symbol in conf.h

core/lib/scmi-server/sub.mk
=> core: lib: scmi-server: drop CFG_CROSS_COMPILE when compiling SCP firmware

.github/workflows/ci.yml
The newer version of Buildroot recently selected in the OP-TEE manifest [1] does not allow building as root by default (apparently this is not a Buildroot policy but rather defined in some packages included in Buildroot). While this makes sense in general, we could not care less in a CI container. Therefore set the appropriate environment variable to bypass this check. We could as well change the Docker image to build as a non-root user but let's just pick the easiest way for now.
Link: https://github.com/OP-TEE/manifest/pull/281 [1]
=> ci: set FORCE_UNSAFE_CONFIGURE=1

core/arch/arm/include/kernel/stmm_sp.h, core/arch/arm/kernel/stmm_sp.c, core/arch/riscv/include/kernel/stmm_sp.h, core/include/kernel/mutex.h, core/include/kernel/pseudo_ta.h, core/include/kernel/tee_ta_manager.h, core/include/kernel/user_mode_ctx_struct.h, core/include/kernel/user_ta.h, core/kernel/pseudo_ta.c, core/kernel/tee_ta_manager.c, core/kernel/user_ta.c
Fix race condition on single instance TA creation where several instances of a single instance TA could be created if invoked close enough that they are both created after tee_ta_init_session() calls tee_ta_init_session_with_context().
Closes: https://github.com/OP-TEE/optee_os/issues/6801
=> core: fix race condition on single instance TA loading

core/arch/arm/include/arm64.h, core/lib/zlib/sub.mk, lib/libutils/isoc/sub.mk
Small fixes required with Clang 18.1.6. To build OP-TEE with that version, please see https://github.com/OP-TEE/build/pull/762.
=> Clang fixes

core/arch/arm/plat-mediatek/conf.mk, core/arch/arm/plat-mediatek/platform_config.h
We will create the memory pool from MEM_AREA_RES_VASPACE.
When using the reserved virtual memory space, it is necessary to increase MAX_XLAT_TABLE based on its size.
=> plat-mediatek: add support to extend MAX_XLAT_TABLE

core/include/mm/pgt_cache.h, core/mm/pgt_cache.c, mk/config.mk
Add CFG_PGT_CACHE_ENTRIES to allow platforms to customize the page table cache size. This is needed for example when a platform is to support very large TAs of several dozen of Mbytes of private memory (code/data).
By the way, fix pgt_cache.h layout to have header files includes first followed by macro definitions.
=> core: mm: add CFG_PGT_CACHE_ENTRIES

core/arch/arm/include/ffa.h, core/arch/arm/include/kernel/spmc_sp_handler.h, core/arch/arm/kernel/spmc_sp_handler.c, core/arch/arm/kernel/thread_spmc.c
* Deny memory regions with zero pages
* Validate total page count field
* Validate total descriptor size including memory regions descriptors
* Deny unsupported fragmented operations
* Fix incorrect FFA_ERROR status codes
* Return transaction type flag in retrieve response
Added test cases to SPMC test SPs to cover error handling branches in the memory sharing related functions: https://review.trustedfirmware.org/c/TS/trusted-services/+/28384
=> core: ffa: Improve FF-A memory sharing compliance

core/include/dt-bindings/mfd/st,stpmic1.h
Change include/dt-bindings/mfd/st,stpmic1.h license model from GPLv2.0 only to dual GPLv2.0 or BSD-2-Clause. This change clarifies that this DT binding header file can be shared with software components as bootloaders and OSes that are not published under GPLv2 terms as OP-TEE OS is.
This change has been discussed and acked in the LKML [1].
Fixes: 1183a0aa2af0 ("stm32mp1: update DTS files to Linux kernel 5.2-rc1")
Link: https://lore.kernel.org/lkml/171941721004.2530174.778562710266249921.b4-ty@kernel.org/ [1]
=> dt-bindings: mfd: dual licensing for st,stpmic1 bindings

core/mm/core_mmu.c
Currently, OP-TEE OS on RISC-V platforms uses external device-tree located at 'Domain1 Next Arg1' passed by previous boot stages (i.e. U-Boot SPL and OpenSBI). For example:
Domain1 Name              : trusted-domain
...
Domain1 Next Address      : 0x0000000010000000 // OP-TEE OS
> Domain1 Next Arg1         : 0x000000000187f760 // device-tree
Domain1 Next Mode         : S-mode
In this case, 0x0187f760 lies in SHM_VASPACE, which is not yet mapped and not intended to load an external DT:
type TEE_RAM_RX   va 0x10000000..0x10092fff pa 0x10000000..0x10092fff
type TEE_RAM_RW   va 0x10093000..0x101fffff pa 0x10093000..0x101fffff
type RES_VASPACE  va 0x10200000..0x10bfffff pa 0x00000000..0x009fffff
> type SHM_VASPACE  va 0x10c00000..0x12bfffff pa 0x00000000..0x01ffffff
type TA_RAM       va …
=> core: mm: core_mmu: skip unmapped regions when searching by PA

core/arch/arm/kernel/thread_spmc.c, core/arch/arm/mm/sp_mem.c, core/lib/libtomcrypt/src/pk/asn1/der/sequence/der_decode_sequence_flexi.c, core/lib/libtomcrypt/src/pk/asn1/der/sequence/der_decode_sequence_multi.c, core/lib/libtomcrypt/src/pk/asn1/der/sequence/der_encode_sequence_multi.c
This change complements https://github.com/OP-TEE/optee_os/pull/6853.
Changes in libtomcrypt are under review in https://github.com/libtom/libtomcrypt/pull/647.
No functional changes.
=> fix use of calloc() against GCC 14.1 directive -Wcalloc-transposed-args

core/arch/riscv/include/kernel/thread_arch.h, core/arch/riscv/include/kernel/thread_private_arch.h, core/arch/riscv/kernel/asm-defines.c, core/arch/riscv/kernel/thread_arch.c, core/arch/riscv/kernel/thread_rv.S
In current RISC-V trap handler, we always save the context into `struct thread_trap_regs` first, and copy the saved context into another specific structure to handle that trap. For example, `thread_user_ecall_handler()` copies the `struct thread_trap_regs` to be `struct thread_scall_regs` before handling this system call.
In fact, such copies may drop the performance and they should be eliminated.
In this commit, the specific data structure used to save the context is determined early in the trap handler by checking the type of the trap from CSR XCAUSE. Thus, the copies between context structures are eliminated.
=> core: riscv: Improve the trap handler

core/drivers/rstctrl/stm32mp1_rstctrl.c
Fixes missing declaration of STM32MP1 reset controller compat data as unpaged resource since it is used  by stm32mp_rcc_reset_id_to_rstctrl() function called by fastcall service psci_system_reset() that requires to resized in the unpaged segment on STM32MP15 variant where pager is enabled.
Fixes: 3ef177b4f153 ("drivers: stm32_rstctrl: move stm32mp1x controller in stm32mp1_rstcrl.c")
=> drivers: stm32_rstctrl: fix unpaged resource

core/arch/arm/plat-stm32mp1/conf.mk
Remove reduced default heap size configuration of 48kB when pager is enabled on stm32mp1 platforms. 48kB of core heap may not always be enough to pass OP-TEE Test regression test 4011 related to Bleichenbacher attack since it consumes 4.5kB more memory on in OP-TEE core since we upgraded to Mbed TLS library 3.6.0. The platform now default uses the generic 64kB default heap size set from mk/config.mk.
=> plat-stm32mp1: conf: restore generic default heap size

core/drivers/hisi_trng.c
The file core/drivers/hisi_trng.c should not have been committed with a GPL-2.0 license. Relicense it as BSD-2-Clause.
Reported-by: Sahil Malhotra <sahil.malhotra@nxp.com>
Closes: https://github.com/OP-TEE/optee_os/issues/6834
=> core: drivers: relicense hisi_trng.c as BSD-2-Clause

core/drivers/firewall/firewall.c
When compiling with CFG_TEE_CORE_LOG_LEVEL=0 this warning is raised : core/drivers/firewall/firewall.c: In function ‘firewall_dt_probe_bus’: core/drivers/firewall/firewall.c:297:62: error: unused parameter ‘ctrl’ [-Werror=unused-parameter]
297 |                                  struct firewall_controller *ctrl)
=> core: firewall: fix warning when compiling with no trace.

lib/libutee/include/user_ta_header.h
Add missing TA_FLAG_DONT_CLOSE_HANDLE_ON_CORRUPT_OBJECT to TA_FLAGS_MASK.
Fixes: 138c5102ef4c ("GP131: Add TA property gpd.ta.doesNotCloseHandleOnCorruptObject")
Reported-by: Mikko Rapeli <mikko.rapeli@linaro.org>
=> Fix TA_FLAGS_MASK

core/arch/arm/crypto/sm4_armv8a_ce_a64.S
Fix compiling warning in sm4_armv8a_ce_a64.S when CFG_CORE_BTI=y:
aarch64-none-linux-gnu-ld.bfd: out/core/arch/arm/crypto/sm4_armv8a_ce_a64.o: warning:
BTI turned on by -z force-bti when all inputs do not have BTI in NOTE section.
=> core: arm64: fix compiling warning when enable BTI.

lib/libutils/isoc/arch/arm/sub.mk
When compiling the __aeabi functions, skip profiling if CFG_FTRACE_SUPPORT is enabled to avoid recursive calls.
Reported-by: Jerome Forissier <jerome.forissier@linaro.org>
Closes: https://github.com/OP-TEE/optee_os/issues/6870
=> arm32: ftrace: skip profiling of __aeabi functions

core/mm/core_mmu.c
When CFG_TEE_CORE_DEBUG=y and CFG_MEMTAG=y, core will crash, if there are some modules call virt_to_phys() or core_vbuf_is() and so on. Because the MM can not find map by the tagged VA, so strip the tag of VA when check_pa_matches_va().
Acked-by: Jens Wiklander <jens.wiklander@linaro.org>
=> TEE core will crash when CFG_TEE_CORE_DEBUG=y and CFG_MEMTAG=y

CHANGELOG.md, mk/config.mk
Update CHANGELOG for 4.3.0 and collect Tested-by tags.
The 4.3.0-rc1 tag will be created on Friday July 5th and the 4.1.0 release is expected on July 12th.
=> Update CHANGELOG for 4.3.0

core/arch/arm/dts/stm32mp13xc.dtsi, core/arch/arm/dts/stm32mp13xf.dtsi, core/drivers/crypto/stm32/cipher.c, core/drivers/crypto/stm32/stm32_saes.c
This PR adds support of power management in stm32 SAES driver.
We also properly manage the dependency between SAES and RNG.
=> Add support of power management for stm32 SAES peripheral

core/arch/arm/plat-stm32mp1/drivers/stm32mp1_pmic.c, lib/libutils/ext/include/util.h, lib/libutils/ext/qsort_helpers.c, lib/libutils/ext/sub.mk
Add `qsort_int()`, `qsort_uint()`, `qsort_u32()` and friends as `qsort()` helper functions to sort standard typed arrays.
I needed to use `qsort()` in few separated source files and needed to redefine locally the `cmp_xxx()` callback so I think it's worth having some generic helper functions.
=> libutils: qsort helper for standard types

core/kernel/user_access.c, core/lib/libtomcrypt/src/pk/ec25519/tweetnacl.c
1. Replace i64 with u64 in `lib/libtomcrypt/tweetnacl.c` to avoid `shift_out_of_bounds` 
error by UBSan.
2. Add null pointer checks in `kernel/user_access.c` before memcpy to avoid 
`nonnull_args` error by UBSan.
Signed-off-by: Abhishek Revadekar [abhishek.rvdkr@yahoo.com](mailto:abhishek.rvdkr@yahoo.com)
=> core: fix undefined behavior aborts during xtest

core/arch/riscv/mm/core_mmu_arch.c
If MMU is enabled, `core_mmu_pgt_alloc()` returns virtual address of PGT instead of physical address.
Thus, it leads to some errors when we invoke `pa_to_ppn()` with returned PGT which is actually the virtual address of that PGT.
Fix it by checking whether MMU is enabled or not.
If MMU is enabled, we translate the returned PGT to its physical address.
=> core: riscv: Translate to PA when allocating PGT with MMU enabled

core/arch/arm/dts/sama5d2.dtsi, core/drivers/nvmem/atmel_sfc.c, core/drivers/nvmem/nvmem_die_id.c, core/drivers/nvmem/nvmem_huk.c
- Fix the length of the HUK and die-id NVMEM cell.
- Allow the use of a larger NVMEM cell for the HUK.
- Redefine HUK and die id cells in sama5d2.dtsi.
- Fix the regression test 4013.
=> Add NVMEM improvements and fixes

core/arch/arm/kernel/boot.c, core/include/kernel/transfer_list.h
According to recently firmware handsoff spec [1]'s
"Register usage at handoff boundary", Transfer List's signature value
was changed from 0x40_b10b (3 bytes) to 4a0f_b10b (4 bytes).
As updating of TL's signature, register value of x1/r1 should be:
In aarch32's r1 value should be
R1[23:0]: set to the TL signature (4a0f_b10b->masked value: 0f_b10b)
R1[31:24]: version of the register convention ==  1
and
In aarch64's x1 value should be
X1[31:0]: set to the TL signature (4a0f_b10b)
X1[39:32]: version of the register convention ==  1
X1[63:40]: MBZ
(See the [2] and [3]).
Therefore, it requires to separate mask and shift value for register
convention version field when checking each r1/x1 value.
This patch fix two problems:
1. breaking X1 value with updated specification in aarch64
- change of …
=> core: kernel: Fix checking register convention r1/x1 value using transfer list.

mk/compile.mk
Some generated files get a __FILE_ID__ which include absolute build time paths. Remove the paths and use plain file name. Fixes yocto QA check.
=> mk/compile.mk: remove absolute build time paths

.github/workflows/ci.yml
Upgrade the "cache" action to address the CI warning:
"""
The following actions uses Node.js version which is deprecated and will be forced to run on node20: actions/cache@v3. For more info: [1] """
Link: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/ [1]
=> ci: upgrade actions/cache@v3 to v4

core/arch/arm/kernel/link.mk, core/arch/riscv/kernel/link.mk, mk/compile.mk
Default debug flag -g3 was already getting removed from version-o-cflags but on corstone1000 platform-cflags-debug-info is set to -gdwarf-2 and thus debug info was included in the generated version.o. This then included full absolute build time path which breaks "buildpaths" yocto QA check since the path is also in final tee.elf binary. Remove all debug flags from version-o-cflags as a fix/workaround.
Fixes yocto build reproducibility issues on corstone1000:
https://gitlab.com/jonmason00/meta-arm/-/jobs/7472950196
Cc: Jon Mason <jon.mason@arm.com>
=> Remove build time paths from version.o, use CFLAGS from build environment

core/arch/riscv/include/encoding.h, core/arch/riscv/mm/core_mmu_arch.c
The upper bits of page table entry may contain other fields such as PBMT and N bits, thus PPN field should be masked out with PTE_PPN.
=> core: riscv: core_mmu_arch: fix PPN field extraction from PTE

core/drivers/pm/sam/at91_pm.c, core/include/kernel/pm.h
The suspend level is platform dependent and can be set to various values depending on these platforms. In order to
allow platforms setting it in a generic way when entering suspend, reserve some bits in the suspend/resume hint to pass this information.
Also update sama5d2 platforms suspend mode to enter different levels of low power mode according to the suspend/resume hint to pass this information.
=> Add type of suspend operation

core/arch/riscv/kernel/entry.S, core/arch/riscv/kernel/thread_optee_abi_rv.S
Zeroize unused parameters before calling thread_return_to_udomain() to avoid leaking information to the untrusted domain unintentionally.
=> core: riscv: Zeroize unused parameters before thread_return_to_udomain()

lib/libmbedtls/core/hash.c
The macro 'MBEDTLS_INTERNAL_VALIDATE_RET()' was removed in upstream commit https://github.com/Mbed-TLS/mbedtls/commit/cc0fd47531ffeffb3185db77a17ee113ce874ea6
The macro was a no-op, so just remove the checks.
This fixes building OP-TEE with:
make PLATFORM=vexpress \
PLATFORM_FLAVOR=juno \
CFG_CRYPTOLIB_NAME=mbedtls \
CFG_CRYPTOLIB_DIR=lib/libmbedtls
...
lib/libmbedtls/core/hash.c: In function 'mbedtls_internal_sha1_process': lib/libmbedtls/core/hash.c:205:9: error: implicit declaration of function 'MBEDTLS_INTERNAL_VALIDATE_RET'
=> core: mbedtls: Fix build

.github/workflows/ci.yml
Build for the Juno platform with Mbed TLS as the core crypto library. This would have caught the issue fixed in commit 021fee0affe5 ("core: mbedtls: Fix build").
=> ci: add build with Mbed TLS and crypto extensions

core/arch/arm/plat-stm32mp1/drivers/stm32mp1_pmic.c
Fix PMIC regulator levels arrays handling that missed a pointer reset after the buffer is freed. At runtime, pmic_list_voltages() handler function uses that reference and is expected to allocate back the buffer in case non-secure world requests voltage enumeration for the related regulator.
Fixes: a7990eb02b82 ("plat-stm32mp1: set voltage list at pmic driver init")
=> plat-stm32mp1: fix use after free in PMIC driver

ta/pkcs11/src/processing_rsa.c
Fix RSA key attributes function load_tee_rsa_key_attrs() that badly checks that the 5 extended RSA attributes are found in the key object.
Link: https://github.com/OP-TEE/optee_test/issues/721#issuecomment-2068055537
Link: https://github.com/OP-TEE/optee_test/issues/721#issuecomment-2072064963
Fixes: 0442c956edfb ("ta: pkcs11: Add support for RSA signing & verification")
=> ta: pkcs11: correct RSA keys extended attributes sanitation

core/drivers/clk/sam/at91_cpu_opp.c, core/include/drivers/clk.h
Explicitly state in clk_get_rates_array() inline description comment that the output rates arrays is ordered by increasing frequency values. This change allows to better fit the sole consumer of this API function that is the SCMI server implementation. SCMI specification states that discrete clock rates list shall follow this order.
Update at91_cpu_opp clock driver to ensure it satisfy this constraint. The SAM platforms that embed this driver (sama7g5) already satisfy this constraints but only at its DTS level. This change ensures the driver will always.
=> drivers: clk: clk_get_rates_array() returns ordered rates

core/arch/arm/kernel/thread_a32.S
The AArch32 version of the native_intr_handler() macro has until now called C function without updating the core local flags to indicate that the temporary stack is in use. The can lead to errors with CFG_CORE_DEBUG_CHECK_STACKS=y so fix this by setting THREAD_CLF_TMP and THREAD_CLF_FIQ or THREAD_CLF_IRQ as needed.
=> core: arm32: update core local flags in  native_intr_handler

core/arch/arm/plat-sam/conf.mk, core/arch/arm/plat-sam/nsec-service/sm_platform_handler.c, core/arch/arm/plat-sam/nsec-service/smc_ids.h, core/arch/arm/plat-sam/sam_pl310.c, core/arch/arm/plat-sam/sam_pl310.h
When Linux runs in normal world, it expects the PL310 to be initially disabled, and then invokes SMCs to enable it.
Let CFG_PL310_SIP_PROTOCOL=y, and the L2 cache will be left untouched until the OS enables it.
=> plat-sam: implement PL310 SMC protocol

core/drivers/scmi-msg/clock.c, core/drivers/scmi-msg/voltage_domain.h
Fix the version ID of the implemented SCMI voltage domain protocol that is v2.0 (ID 0x20000), not v3.0 (ID 0x30000).
(Fixes: 006d89b8f49f ("drivers: scmi-msg: add SCMI Voltage Domain protocol"))
Fix value of remaining clocks to describe on SCMI clock protocol message CLOCK_DESCRIBE_RATES that does not take into account the number of returned clock in the response.
(Fixes: 90252e2a52c7 ("drivers: scmi-msg: clock adapts to output buffer size"))
=> drivers: scmi-msg: correct voltage domain protocol version & clock rates enumeration

core/arch/riscv/kernel/csr_detect.S
We want to set value of the register a0 to 1 here.
To set initial value of the register a0 to 1, the assembly code should be "li a0, 1" instead of "addi a0, a0, 1".
Otherwise, a0 will be any value greater than 1.
=> RISC-V: Fix initial value of a0 in "detect_csr" assembly macro

lib/libutee/sub.mk, lib/libutee/tee_api_property.c, lib/libutils/ext/base64.c, lib/libutils/ext/include/base64.h, lib/libutils/ext/sub.mk
Make the base64 routines publicly available by moving them from libutee to libutils. The _ prefix is removed from the public functions since they aren't internal to libutee any longer.
=> Move base64.{c,h} from libutee to libutils

core/tee/tee_svc_storage.c
Prior to this all errors except TEE_ERROR_OUT_OF_MEMORY from fops->read() was reported as TEE_ERROR_CORRUPT_OBJECT leading to removal of the object.
We should not treat all errors as corrupt, so remove the error code translation.
=> core: fix error handling in tee_svc_storage_read_head()

mk/compile.mk
Fixes the target in the pre-processed device tree dependency file
=> mk/compile.mk: fix pre-processed device tree dependencies file target

core/arch/arm/plat-k3/drivers/sa2ul.c, core/arch/arm/plat-k3/main.c
Since commit https://github.com/OP-TEE/optee_os/commit/11d8578d93f0aee793b28221b06187f62bb7b24b ("core: arm: call call_driver_initcalls()
late"), driver_init is deferred and thread_update_canaries tries to get
random_stack_canaries which requires the TRNG driver to be setup. Since
it was being setup as part of driver_init, it lead to crash on K3
platforms.
Change driver_init to service_init_crypto which is meant to be used for
initialization of crypto operations. Also, for the TISCI services to be
available before service_init_crypto, change init_ti_sci invocation to
early_init_late.
Some other driver vendors using driver_init for RNG initialization might 
also be affected.
Signed-off-by: Kamlesh Gurudasani <kamlesh@ti.com>
Signed-off-by: Manorit Chawdhry <m-chawdhry@ti.com>
=> plat-k3: drivers: Change SA2UL_init service to service_init_crypto

core/arch/riscv/include/kernel/thread_private_arch.h
To support CFG_CORE_DEBUG_CHECK_STACKS=y for RISC-V, we increase the following stacks:
- Set STACK_THREAD_SIZE as 10240 bytes
- Set STACK_ABT_SIZE as 4096 bytes
- Set STACK_CHECK_EXTRA as 1536 bytes, like what ARM does
=> RISC-V: Support CFG_CORE_DEBUG_CHECK_STACKS

core/arch/riscv/mm/core_mmu_arch.c
Fix misuse of `virt_to_phys()` and `phys_to_virt()` where is not aware MMU is disabled.
=> riscv: core_mmu_arch: fix address translation helpers

core/arch/arm/kernel/secure_partition.c, core/arch/arm/kernel/thread.c
- Enable BTI for binary SP-s via manifest (and provide info to the SP whether BTI/PAC are enabled by the OS)
- Enable PAC for SP-s (similar way as it is implemented for TA-s)
- Enable PAC before SP initialization and se atomic pauth keys at init, so the used keys will not change between the first SEL1->SEL0->SEL1 transition resulting in error
=> Required changes for PACBTI enablement in Trusted Services

core/arch/arm/kernel/entry_a32.S, core/arch/arm/kernel/entry_a64.S, mk/config.mk
Add CFG_CORE_STATIC_ASLR_SEED to override the used seed if CFG_CORE_ASLR=y. CFG_CORE_STATIC_ASLR_SEED is intended to help debugging ASLR related issues by using the same address layout each time.
CFG_CORE_STATIC_ASLR_SEED requires CFG_INSECURE=y.
=> core: add CFG_CORE_STATIC_ASLR_SEED

core/arch/riscv/plat-virt/conf.mk
On RISC-V QEMU virt platform, OP-TEE OS runs as S-mode.
There is a secure monitor runs as M-mode and controls the hart state of the secondary CPUs in SMP system (e.g., by SBI HSM extension) during OP-TEE OS secondary CPUs booting.
Thus, RISC-V virt platform does not need CFG_BOOT_SYNC_CPU.
=> riscv: plat-virt: Set CFG_BOOT_SYNC_CPU=n

core/drivers/remoteproc/stm32_remoteproc.c, core/include/drivers/stm32_remoteproc.h, core/pta/stm32mp/remoteproc_pta.c, lib/libutee/include/remoteproc_pta.h, ta/remoteproc/include/ta_remoteproc.h, ta/remoteproc/src/remoteproc_core.c
The sequence to start the remote processor consists of calling `TA_RPROC_CMD_LOAD_FW` to load the firmware and then starting the remote processor using the `TA_RPROC_CMD_START_FW` command.
Between the calls of these two commands, the user can perform several actions that may result in an error. In such cases, we need to revert from the `REMOTEPROC_LOADED` state to the `REMOTEPROC_OFF` state.
To address this issue, this pull request proposes implementing the `TA_RPROC_CMD_RELEASE_FW` command. This command can be called in case of an error or after stopping the remote processor to clean up the associated resources.
At the platform level, the `PTA_REMOTEPROC_RELEASE` command is introduced to implement the service. For the stm32mp1 platform, this service consists of cleaning the memory …
=> Remoteproc:  add command to release fw resources

core/arch/arm/kernel/boot.c, core/arch/arm/kernel/virtualization.c
Replace the preinit_early() guest heap initialization with function call in virt_guest_created().
=> core: virt: initialize heap from virt_guest_created()

core/arch/arm/kernel/thread.c, core/arch/riscv/kernel/thread_arch.c, core/include/kernel/thread.h, core/kernel/thread.c
The implementations of thread_init_stack() are identical and trivial for both arm and riscv. So simplify code further and open-code it where it's called from in core/kernel/thread.c.
=> core: open-code thread_init_stack()

core/arch/riscv/kernel/thread_arch.c
The parameter "regs" is the stack pointer which is allocated to store system call registers when calling thread_scall_handler().
Thus, we can simply get the original stack pointer by "regs + 1" equation, and use when exiting user mode.
The code is referenced from ARM's [setup_unwind_user_mode()](https://github.com/OP-TEE/optee_os/blob/9cb4152f1b0c297b964bdb7bd84b49615afd73fb/core/arch/arm/kernel/thread.c#L1099).
=> core: riscv: Simplify SP setup in setup_unwind_user_mode()

core/drivers/crypto/hisilicon/hpre_montgomery.c, core/drivers/crypto/hisilicon/hpre_montgomery.h, core/drivers/crypto/hisilicon/sub.mk
=> driver: crypto: hisilicon: add X25519 and X448 algorithm

core/arch/arm/kernel/thread.c
There are two lines of code to assign value of sp for ARM64.
Remove one of them.
```diff
-	regs->sp = user_sp;
regs->pc = entry_func;
regs->cpsr = spsr;
regs->x[13] = user_sp;	/* Used when running TA in Aarch32 */
regs->sp = user_sp;	/* Used when running TA in Aarch64 */
```
=> core: arm: Remove duplicated sp assignment for ARM64 in set_ctx_regs()

core/arch/riscv/include/kernel/thread_arch.h, core/arch/riscv/include/kernel/thread_private_arch.h, core/arch/riscv/include/riscv.h, core/arch/riscv/kernel/thread_arch.c, core/arch/riscv/kernel/thread_rv.S, core/arch/riscv/plat-spike/platform_config.h, core/arch/riscv/plat-virt/platform_config.h
Foreign interrupts are interrupts that assert during OP-TEE execution, but are not owned and handled by OP-TEE.
For example, in SMP system, if an Linux side interrupt assert during TA execution, OP-TEE can suspend current TA and yield the execution to Linux to handle that interrupt.
This PR implements such foreign interrupt handler for RISC-V architecture.
To determine whether the incoming interrupt is foreign interrupt or not, we leverage `THREAD_EXCP_FOREIGN_INTR`, which aliases bits of `mip` or `sip`.
The type of incoming taken interrupt can be determined by value of `XCAUSE` CSR.
First, we translate `XCAUSE` to corresponding `mip` or `sip` bit.
Then we compare it with `THREAD_EXCP_FOREIGN_INTR` to determine whether the incoming interrupt is foreign interrupt or not.
If yes, we call …
=> RISC-V: Implement foreign interrupt handler

core/arch/arm/include/mm/core_mmu_arch.h, core/arch/arm/mm/core_mmu_v7.c, core/arch/riscv/include/mm/core_mmu_arch.h, core/arch/riscv/mm/core_mmu_arch.c, core/arch/riscv/plat-virt/conf.mk, core/include/mm/core_mmu.h, core/mm/core_mmu.c
This series enables CFG_TEE_CORE_DEBUG, a crucial feature for early error detection on RISC-V platforms, such as assertions.
=> [RISC-V] Allow enabling CFG_TEE_CORE_DEBUG

core/include/kernel/delay.h
Fix timeout threshold that should return once the time expires, not 1 tick after it has expired. This change makes udelay(0) to immediately return and not wait a generic timer counter increment.
This change fixes an issue where a driver stops the counter feeding Arm generic timer counter and indirectly calls IO_READ32_POLL_TIMEOUT() with a delay of 0us. It that case, since counter never increments, the udelay(0) call in IO_READ32_POLL_TIMEOUT() never returns while we expect the macro to endlessly poll (as timeout would never be detected) until poll condition is met or system watchdog is triggered.
=> core: delay: fix timeout expiration threshold

core/arch/riscv/include/kernel/thread_private_arch.h, core/arch/riscv/kernel/abort.c, core/arch/riscv/kernel/thread_arch.c, core/arch/riscv/kernel/thread_rv.S
Currently, the user mode abort and some system calls return to kernel mode by thread_exit_user_mode().
Although this function creates a shorter path to return to kernel mode, it leads to some problems because the function does not update the core local flags.
Especially when CFG_CORE_DEBUG_CHECK_STACKS=y, some checks will fail due to wrong type of stack recorded in the core local flags.
Fix it by removing thread_exit_user_mode().
So that the core local flags can be correctly updated in the common trap handler.
=> core: riscv: Remove thread_exit_user_mode()

lib/libutils/ext/include/compiler.h, ta/user_ta_header.c
=> TA stack protector fix

.github/workflows/ci.yml
Exclude xtest case pkcs11_1007 from qemuv7 CI tests since we're facing sporadic failures on this test on PKCS#11 sessions opening and release. Occurrences of this issue have been found only on this Armv7-A platform. Once the issue is solved, we be able to restore this test.
Link: https://github.com/OP-TEE/optee_os/issues/6952
=> ci: qemuv7: exclude xtest pkcs11_1007

core/kernel/notif.c
Right now OP-TEE build fails if CFG_NS_VIRTUALIZATION=y and CFG_CORE_ASYNC_NOTIF=n with the following error:
core/kernel/notif.c: In function 'nex_init_notif': core/kernel/notif.c:185:42: error: 'notif_data_id' undeclared (first use in this function); did you mean 'notif_wait'?
185 |         return virt_add_guest_spec_data(&notif_data_id,
|                                          ^~~~~~~~~~~~~
|                                          notif_wait
core/kernel/notif.c:185:42: note: each undeclared identifier is reported only once for each function it appears in
core/kernel/notif.c:186:48: error: invalid application of 'sizeof' to incomplete type 'struct notif_data'
186 |                                         sizeof(struct notif_data), NULL);
| …
=> notif: fix build when NS_VIRTIALIZATION is enabled

core/drivers/crypto/stm32/stm32_saes.c
set_field_u32() is a function that allows you to change a specific bit in a register by using a mask. The function returns the full value of the register, which means that the use of bitwise OR here is a mistake. The current code works here only because the modified registers are initialized. Moreover, there is no need to shift the value as the function already doing it.
Fix the usage of the function in the SAES driver by replacing bitwise OR assignments with simple assignments.
=> crypto: stm32: fix SAES driver set_field_u32 usage

mk/config.mk
Set CFG_NOTIF_TEST_WD ?= y only when the features it needs are enabled. Fixes the following warning on platforms that enable CFG_ENABLE_EMBEDDED_TESTS but not CFG_CORE_ASYNC_NOTIF or CFG_CALLOUT:
mk/config.mk:1039: Warning: Disabling CFG_NOTIF_TEST_WD [requires CFG_CALLOUT CFG_CORE_ASYNC_NOTIF]
=> Default enable CFG_NOTIF_TEST_WD only when dependencies are enabled

core/arch/riscv/include/kernel/thread_private_arch.h, core/arch/riscv/kernel/asm-defines.c, core/arch/riscv/kernel/thread_rv.S
- Commit "core: riscv: Ensure XSTATUS is restored before XIE"
avoids accidental interrupt during register restoring.
- Commit "core: riscv: Improve thread user mode record"
improves register save/restore during entering/existing user mode.
=> More improvements for RISC-V

core/arch/arm/plat-imx/conf.mk
This pull request enable support for Attestation PTA and OTP DIE ID by default for i.MX platforms
=> Miscellaneous patches

.github/workflows/ci.yml
The CI image on the Docker Hub has been updated to contain Clang 18.1.7 in /usr/bin [1] [2]. Let's add a job to build OP-TEE with this compiler and run the test suite for arm64 (QEMUv8).
Link: https://github.com/jforissier/docker_optee_os_ci/commit/fdb34bcf25f1 [1]
Link: https://hub.docker.com/r/jforissier/optee_os_ci/tags?name=qemu_check [2]
=> ci: add a QEMUv8 check job built with Clang

core/drivers/clk/clk-stm32-core.c, core/drivers/clk/clk-stm32-core.h, core/drivers/clk/clk-stm32mp13.c
Correct STM32MP13 clock gates initialization regarding the enable reference counting. The fixed commit introduced side effect where clock gates with a disable init state overflow the gate refcount to -1 and clock gates with a enable init state take a refcount that is never released.
For this purpose, add stm32_gate_set_init_state() function in stm32 clock core driver for STM32MP13 gate clocks initialization expects to set some clock gate hardware state (enabled or disabled) before any refcount is considered.
Fixes: 2b028a2ba197 ("clk: implement multi-gate management at core level")
=> drivers: clk: stm32: fix stm32mp13 clock gates initialization

core/arch/arm/cpu/cortex-armv9.mk, core/arch/arm/cpu/neoverse-v2.mk, core/arch/arm/plat-rd1ae/conf.mk, core/arch/arm/plat-rd1ae/main.c, core/arch/arm/plat-rd1ae/platform_config.h, core/arch/arm/plat-rd1ae/rd1ae_core_pos.S, core/arch/arm/plat-rd1ae/sub.mk, core/drivers/gic.c
1- Add initial support for RD-1 AE platform, this includes:
a- GIC and console initialization functions.
b- Memory layout.
c- Make files.
d- Assembly function get_core_pos_mpidr to compute the linear core position from MPIDR.
2- Accept GIC version 4 if CFG_ARM_GICV3 is enabled
=> Introduce RD-1 AE Platform

core/arch/arm/plat-imx/conf.mk
On i.MX91, there is only one MU to communicate with ELE, which cannot be dedicated on OP-TEE side all the time. There may be ELE services running on Linux side, which can cause conflict with OP-TEE.
So disabling ELE by default for now.
=> core: imx: disable ELE support on i.MX91 by default

core/drivers/stm32_rng.c
Register stm32_rng device as non-secure when software PRNG is enabled instead of testing the firewall configuration that is applied from stm32mp1_init_final_shres() at driver_init_late initcall level, far after RNG initialization.
Fixes: d773ec0baf4c ("drivers: stm32_rng: update clock and power management")
=> drivers: stm32_rng: MP15 RNG is non-secure when PRNG is enable

mk/subdir.mk
Add global-cppflags-y as a new sub.mk variable. The content of the variable is added to the C preprocessor flags passed to all files compiled in the current submodule, $(sm), similarly to how the content of global-incdirs-y is passed on.
This flag is intended for libraries that in addition to exporting an include path also need certain defines set.
=> mk: add global-cppflags-y

core/mm/mobj_dyn_shm.c
Until this patch in mobj_reg_shm_get_by_cookie() there's a small window after cpu_spin_unlock_xrestore() before the reference counter is increased with mobj_get(). Fix that by calling mobj_get() before unlocking reg_shm_slist_lock.
Fixes: b96514926b8e ("core: reference count struct mobj")
=> core: fix race in mobj_reg_shm_get_by_cookie()

core/arch/riscv/kernel/thread_optee_abi_rv.S
Ensure we disable traps by clearing XIE CSR instead of clearing XSTATUS.IE which is global interrupt enable bit.
=> RISC-V small fix: Disable traps by clearing XIE CSR

core/drivers/crypto/caam/hal/common/hal_sm_dt.c, core/drivers/crypto/caam/hal/common/sub.mk
Implement caam_hal_sm_get_base_dt() function when CFG_DT=y
=> drivers: caam: hal: add caam_hal_sm_get_base_dt() implementation

core/drivers/clk/clk-stm32-core.c, core/drivers/clk/clk-stm32mp25.c
=> clk: stm32mp25: fix some error cases management

core/arch/arm/plat-k3/conf.mk
All K3 devices already have this enabled, remove the check and set this unconditionally.
=> plat-k3: set TRNG as enabled unconditionally

core/mm/mobj.c
Until this patch, for CFG_CORE_RWDATA_NOEXEC=n and CFG_CORE_ASLR=y there's an error in mobj_init() when the length of the combined TEE_RAM_RWX is calculated.
The relocatable address VCORE_UNPG_RW_PA is mixed with the absolute address TEE_RAM_START. Relocated addresses only changes with CFG_CORE_ASLR=y so before ASLR this expression was correct.
The combined TEE_RAM_RWX is only used with CFG_CORE_RWDATA_NOEXEC=n so that is also a perquisite for the error. The calculated length field is usually not more wrong than code depending on
mobj_tee_ram_rw/mobj_tee_ram_rx still works. So the error wasn't visible until length checks for phys_to_virt() was introduced with the commit c2e4eb43b7b7 ("core_mmu: fix phys_to_virt() to check length").
Fix this by using VCORE_START_VA instead of TEE_RAM_START …
=> core: mm: fix mobj_tee_ram_rw initialization

core/arch/arm/plat-stm32mp1/scmi_server.c, core/drivers/remoteproc/stm32_remoteproc.c, core/include/drivers/stm32_remoteproc.h
Changes for STM32 remote proc driver and SCMI server to expose remoteproc reset controllers through SCMI only when the secure loading of remoteproc firmware is disabled. When so, remoteproc reset and power sequence shall go through OP-TEE remoteproc services, not SCMI platform services.
=> plat-stm32: SCMI reset controllers on remoteproc are disabled on secure fmw loading

.github/workflows/ci.yml
Sync CI test SCP-firmware source tree with latest release tag v2.15.0 instead of the previously selected commit SHA1 that we synced on before a release tag integrating OP-TEE support latest changes was available in that repository.
By the way, clone the repo with a depth of 1 as since is enough for CI tests needs.
=> ci: bump scp-firmware to release tag v2.15.0

core/arch/arm/plat-stm32mp1/drivers/stm32mp1_pmic.c, core/arch/arm/plat-stm32mp1/stm32_util.h
Remove unused platform function stm32mp_nsec_can_access_pmic_regu().
Change-Id: I89a300e5f09ec1ab6e55bb10b06de306f094cbec
=> plat-stm32mp1: remove unused stm32mp_nsec_can_access_pmic_regu()

core/drivers/imx_csu.c
Add the CSU SA settings for i.MX6(Q/D). This setting ensures that no non-TrustZone aware master is able to read secure memory. Information on the CSU SA register values were taken from i.MX6 Security Reference Manual rev 0.
=> drivers: imx_csu: add settings for i.MX6

lib/libutils/ext/include/compiler.h
The `__attribute__((no_stack_protector))` was introduced in GCC 11. Building a TA with an older version of GCC would trigger a `-Wattributes` warning on the `ta/user_ta_header.c` file.
Use `__has_attribute()` to check for the support of the `no_stack_protector` attribute before using it. If not supported, define the `__no_stack_protector` alias as a NOP.
Fixes: e3fb2bd005f ("compiler.h: add __no_stack_protector")
**Note:** This `no_stack_protector` is the only troublesome attribute in my set up (GCC 9.4.0). Let me know if you want to also add a `__has_attribute()` guard to the other attributes and I will do so.
=> compiler.h: only use __no_stack_protector if supported by the compiler

core/arch/arm/plat-ls/main.c, core/drivers/cbmem_console.c, core/drivers/crypto/caam/hal/common/hal_cfg_dt.c, core/drivers/crypto/stm32/stm32_saes.c, core/drivers/firewall/stm32_rifsc.c, core/drivers/firewall/stm32_risaf.c, core/drivers/nvmem/nvmem.c, core/drivers/regulator/stm32_vrefbuf.c, core/drivers/remoteproc/stm32_remoteproc.c, core/drivers/stm32_bsec.c, core/drivers/stm32_gpio.c, core/include/kernel/dt.h, core/kernel/dt.c, core/lib/libfdt/fdt_ro.c, core/mm/core_mmu.c, mk/config.mk
This change supersedes https://github.com/OP-TEE/optee_os/pull/7067. Main difference is that we no more bisect into the cached node structure (since it does not speeds up boot time) and this change proposes a new helper function: `fdt_reg_info()` to look-up parent node once when retrieving the `reg` property base address and size.
Parse the embedded DTB prior using it and cache information that can take time for libdft functions to find. Cached info is stored in an array so that we can find the target info without parsing through the DTB. Cached information are:
- parent node of a node (see [`fdt_parent_offset()`](https://github.com/OP-TEE/optee_os/blob/master/core/lib/libfdt/include/libfdt.h#L924-L925)).
- possibly heavily used `#address-cells` and `#size-cells` properties of a parent …
=> core: cache some embedded DT info (take 2)

core/arch/arm/plat-stm32mp1/shared_resources.c, core/arch/arm/plat-stm32mp1/stm32_util.h, core/drivers/clk/clk-stm32mp15.c, core/drivers/firewall/stm32_etzpc.c, core/drivers/remoteproc/stm32_remoteproc.c
Refine configuration consistency of remoteproc firmware isolation on stm32mp15:
- stm32_etzpc firewall driver ensure MCKPROT isolation consistency vs RCC[MCKPROT],
- stm32_remoteproc driver ensures RCC[MCKPROT] is enabled when needed,
- remove useless verification of parent clock secure hardening since the remoteproc driver ensures MCKPROT is enabled.
=> plat-stm32mp1: secure remoteproc dependancies on RCC-MCKPROT

core/drivers/crypto/se050/core/storage.c
For SE05x, only private keys are stored in the secure element: the OP-TEE secure storage REE/RPMB retains the full public key but just a handle to the private key.
If the secure element's persistent storage is erased, but OP-TEE's secure storage remains, the public key can still be accessed while the private key is inaccessible. However, in such cases, the 'key' will still appear as present in the PKCS#11 database.
When CFG_CORE_SE05X_BLOCK_OBJ_DEL_ON_ERROR is enabled (not by default) and the key pointed to by the handle is not present in the secure element, OP-TEE PKCS#11 clients will encounter an error when attempting to delete the private key information held in the OP-TEE secure storage.
If the setting is disabled, the PKCS#11 storage clears the private key handle without errors.
This …
=> crypto: se05x: improve object deletion logs

core/arch/arm/include/arm.h, core/arch/arm/kernel/misc_a64.S
Secure hypervisor such as Hafnium can manipulate
MPIDR_EL1 to indicate VCPU ID.
This commit makes get_core_pos_mpidr() not calculate CPU ID with affinity bitfields of MPIDR_EL1 when
there is hypervisor in SEL2.
=> core: change get_core_pos_mpidr() to support hypervisor

core/drivers/crypto/caam/crypto.mk
CFG_CORE_BIGNUM_MAX_BITS should be 4576
4096 (RSA Max key size) +
8 * 60 (Header serialization and Black blob overhead in bytes)
=> drivers: caam: fix CFG_CORE_BIGNUM_MAX_BITS

core/drivers/crypto/caam/acipher/caam_rsa.c, core/drivers/crypto/caam/include/caam_desc_defines.h
operation variable has been updated after entering the
function so we cannot check against full RSA operations.
Updated to check only format bit in operation
=> drivers: caam: check only format bit in operation

core/arch/arm/plat-stm32mp1/main.c, core/arch/arm/plat-stm32mp1/platform_config.h, core/arch/arm/plat-stm32mp1/stm32_util.h, core/drivers/firewall/firewall.c, core/drivers/firewall/stm32_etzpc.c, core/drivers/remoteproc/stm32_remoteproc.c, core/include/drivers/firewall.h, core/include/drivers/firewall_device.h
Add `firewall_set_memory_config()` to STM32 ETZPC memory firewalls drivers and let platform use the firewall framework to configure SoC SYSRAM/SRAMs secure hardening.
This change add several changes the platform drivers:
- ensure SYSRAM/SRAMs used by MP15 pager is assigned to secure world
- check consistency of the STM32 ETZPC / RCC secure configurations
- permit ETZPC valid locked configuration
=> plat-stm32mp1: use the firewall framework to secufre or not SRAMs

.github/workflows/ci.yml
Add configurations to the QEMUv8 job to test shared library support with GCC as well as Clang. Shared libraries are somewhat already tested by xtest 1022 which performs dlopen()/dlsym() on a custom library, but CFG_ULIBS_SHARED=y will thoroughly test the loading and symbol resolution at TA load time.
=> ci: qemuv8: add configurations with CFG_ULIBS_SHARED=y

core/include/kernel/thread.h
The `thread_rpc_alloc_*_payload` APIs are consistent with the `thread_shm_type` enumerations, as seen in the `alloc_shm` function. However, the name and comments of `thread_rpc_alloc_payload` might be misleading, suggesting it is a universal API. To maintain backward compatibility, only the code comments have been updated for clarity.
=> refine code comments: clarify misleading names and comments for `thread_rpc_alloc_*_payload` APIs

core/drivers/clk/clk.c, core/drivers/regulator/regulator.c, core/include/drivers/clk.h, core/include/drivers/regulator.h, mk/config.mk
Change the clock and regulator trace level of the print tree functions so that they can be seen when requested by xtest without needing to activate all debug traces.
=> drivers: change tree trace level

lib/libutee/include/tee_internal_api.h, lib/libutee/tee_api.c
In all the published versions of the TEE Internal API Specification, the return type of `TEE_MemMove()` has always been `void`, not `void *`.
=> libutee: fix TEE_MemMove()'s return type

core/drivers/crypto/caam/caam_rng.c, core/drivers/crypto/caam/crypto.mk
Previous design of keeping RNG data in a buffer and giving random number
to user from that buffer is vulnerable to attacks and also not NIST/FIPS compliant.
So, to make it more secure and NIST/FIPS compliant, will get random
number from CAAM on each user request.
With prediction resistance enabled, on every random number request
CAAM is forced to do reseeding of DRBG, which is time taking process
which leads to lower Random number generation performance.
So to give use the flexibility to enable/disable this feature a flag
CFG_CAAM_RNG_RUNTIME_PR is introduced.
By default it will be disabled and user can enable it as per its
requirement.
=> Rework RNG driver design to get RNG from CAAM and introduce CONFIG flag for Prediction Resistance

core/mm/phys_mem.c
Check return value from tee_mm_init() function.
=> core: check return value from tee_mm_init()

core/drivers/crypto/caam/caam_sm.c, core/drivers/crypto/caam/hal/common/hal_sm.c
SM partition SMAG1 permissions were wrongly set for generating DEK blob which results in error while decapsulating DEK blob during HAB encrypted boot. Setting the permissions correctly fix this issue.
=> drivers: caam: sm: fix SM partition permission in SMAG registers

.devcontainer/Dockerfile.vscode, .devcontainer/devcontainer.json, .gitignore, .vscode/extensions.json
This will enable seamless Development of **optee_os** Project with VSCode inside Docker container.
The VSCode Container provides:
* Automatic Mapping of the host user UID/GID inside the container
* GCC Cross-Compilers (aarch64/armhf/riscv64)
* GDB Multiarch for Debugging
* Remote SSH on the Target with seamless ssh mapping of the Host inside the container (Linux/Windows WSL)
* Git and Git Extensions to work and send Patches
Note: This require Docker installation for Linux/or Windows :
[1] https://docs.docker.com/engine/install
VSCode Extensions (extensions.json) will be recommended for the installation
For more Information :
[2] https://code.visualstudio.com/docs/devcontainers/containers 
[3] https://www.youtube.com/watch?v=C_5tDWsWSj0
[4] https://www.youtube.com/watch?v=b1RavPr_878
=>  VSCode : Enable Development inside Docker Container

MAINTAINERS, core/arch/arm/plat-versal2/conf.mk, core/arch/arm/plat-versal2/main.c, core/arch/arm/plat-versal2/platform_config.h, core/arch/arm/plat-versal2/sub.mk
Add support for AMD Versal Gen 2 platform.
AMD Versal Gen 2 is a new SoC based on ARM A78AE with GICv3 and UART over pl011.
=> plat-versal2: add support for AMD Versal Gen 2

.github/workflows/ci.yml
Add a test for EL3 SPMC with SPMC_AT_EL=3 in the QEMUv8_check target. Note that the TF-A build must be removed before building with SPMC_AT_EL=3 since TF-A doesn't rebuild due to changed configuration flags.
=> ci: check EL3 SPMC in QEMUv8_check

.github/workflows/ci.yml
Split the QEMUv8_check job into two smaller jobs to allow them to run in parallel.
=> ci: split QEMUv8_check job

core/arch/arm/plat-imx/conf.mk
phyBOARD-Pollux i.MX 8M Plus is an SBC based on the i.MX 8M Plus SoC. Add the board to the mx8mp-flavorlist and set board specific configs.
=> Add phyBOARD-Pollux support

core/lib/libtomcrypt/ed25519.c
I was getting following errors when using pkcs11 library which determines the signature buffer length by first supplying nullpointer to signature buffer and 0 as size of that buffer in C_Sign and then calling C_Sign again without calling C_SignInit:
```
D/TA:  TA_InvokeCommandEntryPoint:143 PKCS11_CMD_SIGN_INIT p#0 24@0x200000, p#1 --- 0@0x0, p#2 --- 0@0x0
D/TA:  entry_processing_init:674 PKCS11 session 1: init processing EDDSA SIGN
D/TA:  TA_InvokeCommandEntryPoint:364 PKCS11_CMD_SIGN_INIT rc 0/OK
D/TA:  TA_InvokeCommandEntryPoint:143 PKCS11_CMD_SIGN_ONESHOT p#0 4@0x202000, p#1 in 327@0x201d60, p#2 out 0@0x200000
D/TA:  TA_InvokeCommandEntryPoint:364 PKCS11_CMD_SIGN_ONESHOT **rc 0/OK**
D/TA:  TA_InvokeCommandEntryPoint:143 PKCS11_CMD_SIGN_ONESHOT p#0 4@0x202000, p#1 in 327@0x201d60, p#2 …
```
=> Ed25519 sign correctly returns TEE_ERROR_SHORT_BUFFER

core/arch/riscv/include/riscv.h
Rename `set_csr` to `read_set_csr` and `clear_csr` to `read_clear_csr` because they perform atomic reads and set/clear bits in the CSR. These two macros will return the previous value of the CSR.
Introduce new macros `set_csr` and `clear_csr`: `set_csr` uses the RISC-V `csrs` assembler pseudoinstruction to set bits in the CSR when the old value is not needed, while `clear_csr` uses the `csrc` pseudoinstruction to clear bits in the CSR, also discarding the old value.
=> core: riscv: Improve macros for set/clear bits CSR operations

core/arch/arm/dts/stm32mp13-pinctrl.dtsi, core/arch/arm/dts/stm32mp131.dtsi, core/arch/arm/dts/stm32mp15-pinctrl.dtsi, core/arch/arm/dts/stm32mp151.dtsi, core/arch/arm/dts/stm32mp25-pinctrl.dtsi, core/arch/arm/dts/stm32mp251.dtsi, core/arch/arm/plat-stm32mp1/drivers/stm32mp1_pmic.c, core/arch/arm/plat-stm32mp1/shared_resources.c, core/arch/arm/plat-stm32mp1/stm32_util.h, core/drivers/stm32_gpio.c, core/drivers/stm32_i2c.c, core/drivers/stm32_uart.c, core/include/drivers/stm32_gpio.h, core/include/dt-bindings/gpio/stm32mp_gpio.h, core/include/dt-bindings/pinctrl/stm32-pinfunc.h
This P-R makes stm32mp platforms to OP-TEE secure DTB to manage STM32 GPIO access rights. It tried to nicely split changes but it now spreads on almost 20 commits.
* The series start with 7 patches in stm32mp platform DT source files to explicitly describe GPIOs and pins used by OP-TEE but accessible from non-secure world.
*"dt-bindings: gpio: stm32mp: flags for non-secure GPIOs"*
*"dt-bindings: pinctrl: stm32mp: flags for non-secure pins"*
*"dts: stm32: ..."*
* Follows 5 patches  to implement firewall support in stm32_gpio driver, for stm32mp1 and stm32mp2 platforms.
*"drivers: stm32_gpio: check GPIO is not already consumed"*
*"drivers: stm32_gpio: factorize apply_rif_config()"*
*"drivers: stm32_gpio: register to firewall framework"*
*"drivers: stm32_gpio: check secure state of consumed …
=> core: stm32_gpio: register firewall controllers for GPIO access rights

core/arch/arm/plat-rockchip/main.c
It's currently not possible to use `CFG_CORE_DYN_SHM` with the Rockchip platforms, because OP-TEE doesn't know what non-secure memory is available; Device tree is not used and no DDR ranges are registered.
This precludes interacting with OP-TEE from barebox and U-Boot, which currently only implement OP-TEE communication with dynamic shared memory.
Make it possible to use `CFG_CORE_DYN_SHM=y` by adding two sets of config variables to register memory:
* `CFG_DRAM_BASE, CFG_DRAM_SIZE`: For the main memory in the first 4G up to the MMIO range at the end of RAM
* `CFG_NSEC_DDR_1_BASE, CFG_NSEC_DDR_1_SIZE`: For the remainder of the main memory above the MMIO regions.
OP-TEE will take care to carve out the secure memory ranges.
This has been tested on an RK3399 with barebox using OP-TEE's HWRNG …
=> plat-rockchip: allow specifying DRAM via CFG options

core/arch/arm/plat-k3/drivers/ti_sci.c
Currently TI-SCI layer doesn't have any locks that can lead to race conditions, add locks in appropriate places to avoid race conditions.
Signed-off-by: Manorit Chawdhry <m-chawdhry@ti.com>
=> plat-k3: Add locks for TI-SCI protocol

core/arch/arm/dts/stm32mp157c-ed1.dts, core/arch/arm/dts/stm32mp15xx-dhcor-avenger96.dtsi
SD switch regulator is not used by OP-TEE on STM32MP15 based boards hence disable this node in the OP-TEE secure device tree for boards DHCOR Avenger96 (stm32mp15xx-dhcor-avenger96.dtsi) ST ED1/EV1 (stm32mp157c-ed1.dts).
This change fixes a issue related to the integration of stm32_gpio driver as a firewall controller, which is highlighted by ab error trace message like:
E/TC:0 0 stm32_gpio_get_dt:837 node regulator-sd_switch requests secure GPIO F14 that cannot be secured E/TC:0 0 Panic
Fixes: 4675225ed84f ("drivers: stm32_gpio: check secure state of consumed GPIOs")
=> dts: stm32: disable stm32mp15 SD switch regulator node

core/arch/arm/plat-vexpress/conf.mk, ta/pkcs11/sub.mk
Raw RSA signature (PKCS#11 mechanism CKM_RSA_X_509) is not a recommended scheme because unsafe when used with unsafe padding schemes. It's been added in the pkcs11 TA because needed for some TLS v1.2  scenario. I propose to disable it in the pkcs11 TA default config to prevent confusion but enable it in **plat-vexpress** default config so that it is tested (build + xtest).
=> ta: pkcs11: default disable raw RSA mechanism, default enable in plat-vexpress

core/drivers/crypto/hisilicon/crypto.mk, core/drivers/crypto/hisilicon/hpre_rsa.c, core/drivers/crypto/hisilicon/hpre_rsa.h, core/drivers/crypto/hisilicon/sub.mk
=> driver: crypto: hisilicon: add rsa algorithm

.github/workflows/ci.yml
Disable fTPM when testing with pager enabled, because execution is too slow otherwise and sometimes fails with a timeout error. For example I noticed that the execution time of "xtest regression 1006" may be increased from 5 to 10 minutes.
=> ci: QEMUv8: disable fTPM with pager

core/drivers/clk/clk-stm32-core.c, core/drivers/crypto/caam/utils/utils_dmaobj.c, core/drivers/crypto/caam/utils/utils_mem.c, core/drivers/crypto/stm32/stm32_cryp.c, core/kernel/tee_misc.c, core/kernel/transfer_list.c, core/mm/boot_mem.c, core/mm/core_mmu.c, core/mm/tee_mm.c, core/mm/vm.c, ldelf/ta_elf.c, lib/libutee/tee_api.c, lib/libutee/tee_api_operations.c, lib/libutils/ext/include/util.h
Correct inline description comments for ROUND*() macros that request an operand to be a power of 2, not a multiple of 2.
Assert this condition macros where assertion are applicable.
Propose a implementation for relax this constraint for `ROUNDUP()` and `ROUNDDOWN()` macros where we can't use assertions.
=> libutils: util.h: corrections on some ROUND*() macros

core/arch/arm/plat-sam/conf.mk, core/drivers/clk/sam/clk-sam9x60-pll.c, core/drivers/microchip_pit.c, core/drivers/sub.mk
=> drivers: sam: update PLL ready time, add driver for pit64b

ta/pkcs11/include/pkcs11_ta.h
PKCS#11 TA version ID is 0.1.0 since its early integration. Let's set it 1.0.0 since it now mature enough to deserve a non-zero major version number.
=> ta: pkcs11: set TA version ID to 1.0.0

lib/libutils/ext/include/util.h
Hello everyone,
I propose to add a clearer description of get and set field function at there misunderstanding can be error prone.
Cheers,
Maxime
commit message:
Added comments to get_field_u{32,64}() and set_field_u{32,64}() to improve understanding and reduce errors.
=> libutils: util.h: add usage description to {get,set}_field_u{32,64}()

core/kernel/ubsan.c
The following changes are done in ubsan subsystem:
1) `__ubsan_handle_invalid_builtin` callback was added. This ubsan handler
will be invoked when undefined behavior appears in `__builtin_*`
functions. That could happen if invalid arguments were provided.
E.g. passing 0 as the argument to `__builtin_ctz_` or `__builtin_clz_` invokes
undefined behavior and could be potentially caught by ubsan.
I was not able to build latest optee for **vexpress-qemu_armv8a** 
(CFG_CORE_SANITIZE_UNDEFINED=y)
without this change, because this callback was generated in
[libmbedtls code](https://github.com/OP-TEE/optee_os/blame/master/lib/libmbedtls/mbedtls/library/bignum_core.c#L36C23-L36C23)
2) It seems that signatures of ubsan functions are not compatible
with latest (or more or less fresh) gcc ubsan …
=> Fix linking problems/warnings in ubsan

core/arch/arm/kernel/virtualization.c, core/arch/arm/tee/entry_fast.c, core/kernel/notif_default.c
Certain SMCs such as OPTEE_SMC_VM_CREATED can send OPTEE to panic if guest ID passed is 0. 
P.S. sorry for the second PR, there was something really wrong with my branch.
=> core: check guest_id param passed when recieving SMC from NW

scripts/sign_encrypt.py
Fix the following bugs:
- The display command displays an incorrect tag value.
- The verify command requires --enc_key for encrypted TA, but an error occurs when --enc_key option is used.
=> sign_encrypt.py: fix bugs in 'verify' and 'display' with encrypted TA

lib/libutee/tee_api_arith_mpi.c
Fix TEE_BigIntComputeExtendedGcd() for when only one of u and v output coefficients reference if NULL as allowed by the GP TEE Internal Core API specification.
Reported-by: Stefan Schmidt <snst@meek.de>
Closes: https://github.com/OP-TEE/optee_os/issues/7217
=> libtuee: allow NULL output coefficients in TEE_BigIntComputeExtendedGcd()

core/arch/arm/plat-rockchip/platform_config.h, core/arch/arm/plat-rockchip/platform_rk3588.c
Add TRNG support for Rockchip rk3588, tested with `CFG_WITH_SOFTWARE_PRNG=n` using `optee_example_random` to confirm random UUID generation:
```
Invoking TA to generate random UUID...
TA generated UUID value = 0x11cbcccc9b2a7418b76969bd9f170e9
Invoking TA to generate random UUID...
TA generated UUID value = 0xfd54792ca98173c1cc93d21d225a7060
Invoking TA to generate random UUID...
TA generated UUID value = 0x9c2685d5907c20fa76b553072ed9ddd
Invoking TA to generate random UUID...
TA generated UUID value = 0xa7962854a2fb31db7f182129ce645db9
Invoking TA to generate random UUID...
TA generated UUID value = 0x15eb38897f43785f76ee49f7829e6d
Invoking TA to generate random UUID...
TA generated UUID value = 0xf520382614b52bce4fbce2374c677fd5
Invoking TA to generate random UUID...
TA generated UUID …
```
=> plat-rockchip: rk3588: add TRNG support

core/tee/tee_rpmb_fs.c
Fix mutex unlocking in rpmb_fs_dir_populate() that should protect fat_entry_dir_deinit() execution.
Fixes: 5f68d7848fe8 ("core: RPMB FS: Caching for FAT FS entries")
=> core: rpmb: fix mutex in directory populate

core/mm/tee_mm.c
Ensure phys_mem pool instance structure is zero initialized when created. This change fixes an issue where phys_mem pool max_allocated field may contain a fuzzy value.
Fixes: c596d8359eb3 ("core: add phys_mem allocation functions")
=> core: mm: zero initialize phys_mem pool instances

core/arch/arm/include/mm/core_mmu_arch.h, core/arch/arm/kernel/boot.c, core/arch/arm/mm/core_mmu_lpae.c, core/arch/arm/mm/core_mmu_v7.c, core/include/kernel/boot.h, core/mm/boot_mem.c, core/mm/core_mmu.c, mk/config.mk
=> Dynamic allocation of mmu translation tables

core/drivers/gic.c, core/include/drivers/gic.h
Add gic_spi_release_to_ns() API function in GIC driver to release an interrupt to Non secure settings. This functionality is essential for scenarios where a specific interrupt needs to be dynamically set to either Group 1 Secure (G1S) or Group 1 Non-Secure (G1NS) at different times.
=> drivers: gic: Dynamically assign interrupts to non-secure world

core/pta/device.c
TAs which depend on TEE_STORAGE_PRIVATE do need the TEE supplicant if REE FS is disabled (in which case secure storage can only be RPMB) and RPMB is not routed via the kernel.
Fixes: a96033ca7bee ("core: add flag to enumerate TAs when secure storage is ready")
=> core: pta: device: fix enumeration for PTA_CMD_GET_DEVICES_SUPP

core/mm/core_mmu.c
Fix the 5th parameter of add_phys_mem() in collect_device_mem_ranges() that has to be the size of memory region and not the end address of the region.
Fixes: b8ef8d0 ("core: mm: introduce struct memory_map")
=> core: mmu: fix memory regions found from ff-a manifest

core/include/tee/tee_fs.h, core/pta/stats.c, core/tee/tee_rpmb_fs.c, lib/libutee/include/pta_stats.h
Retrieve RPMB secure storage space allocation statistics from the stats PTA `STATS_CMD_ALLOC_STATS` command.
Provide explicit pool string IDs to reflect when pool statistics that meaningless (deprecated public DDR pool, possibly disabled nexus heap).
=> core: get RPMB secure storage allocation stats + PTA stats minor changes

core/arch/arm/dts/stm32mp15xx-dhcom-som.dtsi, core/arch/arm/dts/stm32mp15xx-dhcor-som.dtsi, core/arch/arm/plat-stm32mp1/drivers/stm32mp1_pmic.c, core/drivers/stm32_i2c.c, core/include/drivers/stm32_i2c.h
Update STM32 I2C driver use st,stm32mp15-i2c-non-secure specific DT compatible property for when the I2C bus is non-secure. Update STM32MP15 based DH boards accordingly.
=> drivers: stm32_i2c: use compatible st,stm32mp15-i2c-non-secure

core/kernel/transfer_list.c
Fix a potential panic when the roundup end-of-entry exceeds the boundary of the old end-of-transfer-list when setting the size of a transfer entry.
=> core: fix potential panic when setting transfer entry size

core/lib/libtomcrypt/src/modes/ctr/ctr_encrypt.c
In CTR mode the counter needs to be incremented upon completion of each block. Unfortunately, if there is no crypto acceleration (accel_ctr_encrypt == NULL) and if LTC_FAST is defined, this does not happen. Add the missing call to fix the issue.
Reported-by: Jork Loeser <jork.loeser@microsoft.com>
Closes: https://lists.trustedfirmware.org/archives/list/op-tee@lists.trustedfirmware.org/thread/J4MMZPCM2MNKC2KWAXZUMTVEJP56U6OI/
=> ltc: ctr: fix counter increment when LTC_FAST is defined

core/arch/arm/dts/stm32mp135f-dk.dts, core/arch/arm/dts/stm32mp13xc.dtsi, core/arch/arm/dts/stm32mp13xf.dtsi, core/arch/arm/plat-stm32mp1/conf.mk, core/drivers/crypto/stm32/common.h, core/drivers/crypto/stm32/crypto.mk, core/drivers/crypto/stm32/ecc.c, core/drivers/crypto/stm32/stm32_pka.c, core/drivers/crypto/stm32/stm32_pka.h, core/drivers/crypto/stm32/sub.mk
Add support of PKA peripheral for stm32mp13.
This PR : 
- fix the device tree node
- add the driver stm32-pka.c
- compile the driver by default
- enable pka on stm32mp135-dk
=> Add support of PKA peripheral on stm32mp13

core/drivers/counter/stm32_stgen.c
Cast the result of an operation in stm32_stgen_pm_resume() to fix a compilation warning.
=> drivers: stm32_stgen: fix type in debug trace

core/mm/core_mmu.c, core/pta/tests/misc.c
The commit 06a258064a92 ("core: mm: allow unmapping VCORE_FREE") allows unmapping page from the VCORE_FREE virtual memory range, but no bookkeeping is added apart from what's recorded in the translation tables. Later, the commit 7c9b85432343 ("core: allow partially unmapped MEM_AREA_TEE_RAM_RW") does lookups the translation tables using arch_va2pa_helper() to find out if pages in the VCORE_FREE virtual memory range are mapped. This works well on arm, but not on riscv which must traverse the translation tables in software and then is caught in an infinite recursive loop.
Fix this problem by using explicit bookkeeping in a bitstring representing each page in the VCORE_FREE virtual memory range with a bit and update the bits as needed.
Reported-by: Huang Borong <huangborong@bosc.ac.cn> …
=> core: fix partially unmapped MEM_AREA_TEE_RAM_RW

core/kernel/dt.c
Factorize fdt_get_reg_props_by_index() and fdt_reg_info() to add DT cache info support to the former.
=> core: dt: cached data for fdt_get_reg_props_by_index()

.github/workflows/ci.yml
Add a check entry for SPMC at S-EL1 and secure partitions.
=> ci: QEMUv8: check SPMC at S-EL1 and SPs

core/drivers/dra7_rng.c
Since commit 11d8578d93f0 ("core: arm: call call_driver_initcalls() late"), driver_init is deferred and thread_update_canaries tries to get random_stack_canaries which requires the TRNG driver to be setup. Since it was being setup as part of driver_init, it lead to crash on DRA7 platforms.
Change driver_init to service_init_crypto which is meant to be used for initialization of crypto operations.
While here, add an assert that checks for DRA7 TRNG being used before initialization is complete.
=> drivers: dra7_rng: Change dra7_rng_init to service_init_crypto

core/kernel/otp_stubs.c, core/tee/tee_cryp_utl.c
The weak functions plat_rng_init() and tee_otp_get_hw_unique_key() must be overwritten in a secure product, but it's easy
to forget this either by misconfiguration or lack of knowledge. Add some warnings in these functions to avoid this pitfall
=> print warnings on insecure configurations

.github/workflows/ci.yml
Add a CI job that builds and runs QEMUv8 tests (make check) on an arm64 host.
=> ci: add arm64 job

core/arch/arm/kernel/boot.c
Enable native interrupts on Arm architecture before initcalls handlers are called. This change allows drivers to leverage interrupts during OP-TEE core initialization, as for example detecting a firewall access violation when it happens. Before this change, OP-TEE needed to complete its initialization and return the secure monitor for secure interrupts to be handled.
The feature is embedded upon config switch CFG_UNMASK_NATIVE_INTR_AT_BOOT and applies only when CFG_NS_VIRTUALIZATION is disabled. When CFG_NS_VIRTUALIZATION is enabled, early/service/driver initcalls already execute with native interrupts unmasked, from a standard call entry when the non-secure guest is registered.
=> core: arm: enable native interrupts before init calls

core/arch/arm/kernel/thread_a64.S, core/arch/arm/kernel/thread_spmc.c, core/arch/arm/kernel/thread_spmc_a64.S, core/include/initcall.h
=> Xen+hafnium fixes

core/drivers/firewall/stm32_risab.c
Similarly to RISAF, update the driver to allow dynamic firewall reconfiguration.
=> (STM32) drivers: stm32_risab: add RISAB reconfiguration

core/arch/arm/plat-versal2/conf.mk
Disable ARM CE configs for SHA-512 and SHA3 as those are not available on the SoC.
Ensure that the ARM CE configuration can be overridden at runtime while the default value remains enabled.
=> plat-versal2: disable ARM CE v8.2

mk/compile.mk
Hello,
During tests in our CI we found that the dependency for header file is not correctly managed.
When we remove a header file and it's include from a source file without deleting the build directory the build fails.
You can reproduce the use case by building stm32mp135f-dk on `539836f97 core: arm: virt-aware FF-A thread_foreign_intr_exit()`
And then build `7d9d593df drivers: firewall: stm32_etzpc: remove header file` which remove `stm32_etzpc.h`
With @etienne-lms we found the option `-MP` in gcc and it fix the issue (you need to have the patch for the first build)
=> mk/compile.mk: fix dependency in .d file when removing a header file

core/mm/core_mmu.c
The commit 2f2f69df5afe ("core: mm: replace MEM_AREA_TA_RAM") uses MEM_AREA_SEC_RAM_OVERALL to map practically all secure memory. This conflicts with TEE_SDP_TEST_MEM:
1. MEM_AREA_SEC_RAM_OVERALL covers TEE_SDP_TEST_MEM and triggers a panic in verify_special_mem_areas().
2. TEE_SDP_TEST_MEM_BASE refers to physical memory only since it's only mapped in MEM_AREA_SEC_RAM_OVERALL.
So fix these problems.
Fixes: 2f2f69df5afe ("core: mm: replace MEM_AREA_TA_RAM")
=> core: fix panic with TEE_SDP_TEST_MEM

core/arch/arm/mm/core_mmu_lpae.c, core/arch/arm/mm/core_mmu_v7.c, core/arch/riscv/mm/core_mmu_arch.c, core/mm/core_mmu.c
When optee boots, the initial mapping for MEM_AREA_RES_VASPACE and MEM_AREA_SHM_VASPACE should be added into page tables and replicated to all CPU cores too. This fixes an issue when the VA of MEM_AREA_RES_VASPACE or MEM_AREA_SHM_VASPACE is not in a same 1GB region with other memory regions.
Link: https://github.com/OP-TEE/optee_os/issues/7275
=> core: mmu: Add dynamic VA regions' mapping to page table

core/arch/riscv/plat-virt/conf.mk
RISC-V has several standard interrupt controllers supported by QEMU virtual platform. For example: PLIC, APLIC, IMSIC, etc.
This commit removes enforcement of `CFG_RISCV_PLIC` so that `CFG_RISCV_PLIC` can be build time configurable for developer.
=> riscv: plat-virt: Let CFG_RISCV_PLIC be build time configurable

core/arch/arm/kernel/asm-defines.c, core/arch/arm/kernel/boot.c, core/arch/arm/kernel/entry_a32.S, core/arch/arm/kernel/entry_a64.S, core/arch/arm/kernel/thread.c, core/include/kernel/thread.h, core/kernel/thread.c, mk/config.mk
=> Prepare for dynamic boot configuration

core/arch/riscv/plat-virt/conf.mk, core/arch/riscv/plat-virt/main.c
Currently RISC-V virtual platform enforces 16550 UART to be console device. However, there are other console devices which can be chose by developer. Thus, we allow the configurations for console device to be overridden at build time while keeping the default value enabled.
Besides, fix CFG_SBI_CONSOLE to be CFG_RISCV_SBI_CONSOLE.
=> riscv: plat-virt: Let console devices be build time configurable

.github/workflows/ci.yml, core/lib/scmi-server/conf-optee-fvp.mk
OP-TEE scmi server on qemu_v8 doesn't boot with latest SCP-firmware when notification is enabled since the addition of clock notification in SCP. This come from that there is no notification channel supported yet for optee scmi server. Disable notification until notification support is added.
=> scmi: Fix qemu_v8 configuration

core/drivers/atmel_saic.c, core/drivers/gic.c, core/drivers/hfic.c, core/drivers/plic.c, core/include/kernel/interrupt.h, core/kernel/interrupt.c
Rename field `add` of `struct itr_ops` to `configure` for consistency since that handler is used the configure the interrupt. Update existing interrupt drivers accordingly.
That `configure` handler is not required for interrupt providers which consumer only use the DT to get and configure their interrupts (with `interrupt_dt_get_by_*()` and `interrupt_create_handler()`). Therefore change `itr_chip_is_valid()` to not enforce its support but add back that constraint for the interrupt main controller.
Plus few minor changes in inline comments in interrupt.h and interrupt.c.
=> core: interrupt: rename .add handler to .configure + minor inline comment changes

core/drivers/imx_rngb.c
The RNGB module must be ready during init_tee_runtime to provide a random stack canary value during bootup.
=> drivers: imx: rngb: early initialization

core/arch/arm/include/arm64.h, core/arch/arm/kernel/abort.c, core/arch/arm/mm/core_mmu_lpae.c, core/arch/arm/mm/core_mmu_v7.c, core/arch/arm/plat-stm32mp2/conf.mk, core/arch/arm/plat-stm32mp2/main.c, core/drivers/firewall/stm32_serc.c, core/include/drivers/stm32_serc.h, core/include/kernel/abort.h, core/include/mm/core_mmu.h, mk/config.mk
Implement a platform abort handler to handle use cases such as data aborts generated by peripherals on the bus.
These kinds of abort could be caused by platform-specific features, hence the weak function.
=> Core: add platform abort handler + stm32 SERC usage

core/arch/arm/kernel/link_dummies_paged.c, core/arch/riscv/kernel/boot.c, core/arch/riscv/kernel/entry.S, core/include/initcall.h, core/kernel/initcall.c
This PR aims to update RISC-V boot stages to be aligned with ARM, introduced in https://github.com/OP-TEE/optee_os/pull/6988.
- Introduce boot_init_primary_final() for RISC-V
- Remove unused call_initcalls()
=> RISC-V: Minor update RISC-V boot stages

core/arch/riscv/kernel/boot.c, core/arch/riscv/kernel/entry.S, core/arch/riscv/mm/core_mmu_arch.c, core/include/kernel/boot.h, core/include/mm/core_mmu.h, core/mm/core_mmu.c, core/mm/sub.mk, mk/config.mk
Refer to https://github.com/OP-TEE/optee_os/pull/7039 and https://github.com/OP-TEE/optee_os/pull/7192.
This PR supports boot mem and dynamic allocation of MMU translation tables for RISC-V architecture.
Also remove `CFG_BOOT_MEM` and relevant dead code, since both ARM and RISC-V explicitly support boot mem now.
=> RISC-V: Support boot mem and dynamic allocation of MMU translation tables

mk/compile.mk
Commit 61b2d6e460f7 ("mk/compile.mk: add -Ulinux -Uunix to dtb-cppflags") addresses some macro enabled by default by the compiler that could impact the pre-processing of the DTS files.
Instead of un-defining each of such macros, use the flag '-undef' and get rid of all of them in one shot.
Add the macro '__DTS__' specific for DTS pre-processing, as it is done in Linux and later ported to U-Boot with [1]. This could help sharing include files between DTS and C code.
Link: https://github.com/u-boot/u-boot/commit/f53932addd31 [1]
=> mk/compile.mk: add -undef and -D__DTS__ in dtb-cppflags

core/arch/arm/dts/stm32mp135f-dk.dts, core/arch/arm/plat-stm32mp1/conf.mk, core/drivers/crypto/stm32/common.h, core/drivers/crypto/stm32/crypto.mk, core/drivers/crypto/stm32/hash.c, core/drivers/crypto/stm32/hmac.c, core/drivers/crypto/stm32/stm32_hash.c, core/drivers/crypto/stm32/stm32_hash.h, core/drivers/crypto/stm32/sub.mk
Add support of HASH peripheral for stm32mp15 and stm32mp13.
This PR :
- add the driver stm32-hash.c
- enable hash on stm32mp135-dk
- compile the stm32_hash driver by default
Note:
HASH peripheral is allocated to non-secure on stm32mp15 boards , that's why it's not enable it in this PR.
=> Add support of HASH peripheral for stm32mp1

scripts/sign_encrypt.py
The value of enc_algo_name and flags_name was set to 'Unkown', should be 'Unknown' instead.
=> sign_encrypt.py: Fix typo from 'Unkown' to 'Unknown'

.github/workflows/ci.yml, core/arch/arm/kernel/boot.c, core/arch/arm/kernel/entry_a32.S, core/arch/arm/kernel/entry_a64.S, core/include/kernel/boot.h
Enable S-EL0 SP tests for the S-EL1 SPMC with BTI+MTE+PAC enabled.
=> ci: add S-EL0 SP tests to the BTI+MTE+PAC job

.github/workflows/ci.yml, core/drivers/remoteproc/stm32_remoteproc.c
Fix compilation error of core/drivers/remoteproc/stm32_remoteproc.c Move bool ns_loading from "struct stm32_rproc_instance" to "struct stm32_rproc_compat_data".
Fixes: a03044318866 ("drivers: stm32_remote_proc: add stm32_rproc_is_secure()")
=> drivers: stm32_remote_proc: fix definition of stm32_rproc_compat_data

core/arch/arm/kernel/link.mk, ldelf/link.mk, lib/libmbedtls/include/mbedtls_config_kernel.h, lib/libmbedtls/include/mbedtls_config_uta.h, lib/libutils/ext/include/asm.S, mk/config.mk, ta/link.mk, ta/link_shlib.mk, ta/ta.mk
Linking with libgcc makes it harder than necessary to test BTI, so make libgcc optional.
=> Deprecate libgcc

core/drivers/stm32_gpio.c
Remove test on CFG_DRIVERS_GPIO inside stm32_gpio.c C source file. CFG_* dependencies are addressed in makefile file (e.g. plat-*/conf.mk), not in the driver source file.
Fixes: 1001585e2e56 ("drivers: stm32_gpio: remove GPIO access specific API functions")
=> drivers: stm32_gpio: remove test on CFG_DRIVERS_GPIO

core/arch/arm/dts/stm32mp15xx-dhcor-avenger96.dtsi
As discussed in #7296, i2c1 and i2c2 on the STM32MP157a Avenger96 board are enabled because the device tree was copied from the linux kernel.
Both i2c interfaces are not consumed in OP-TEE and the clock tree is missing resulting in a panic on boot when the driver is probed.
=> dts: stm32: disable unused i2c1 and i2c2

core/arch/arm/kernel/entry_a32.S, core/arch/arm/kernel/entry_a64.S, core/kernel/thread.c, mk/config.mk
CFG_BOOT_INIT_THREAD_CORE_LOCAL0 is misleading since it's concerning the core id of the boot CPU. So rename the configuration flag to CFG_BOOT_INIT_CURRENT_THREAD_CORE_LOCAL and update the code as needed. Only thread_init_thread_core_local() has a change of behaviour where the boot CPU now can have any core id.
Fixes: b5ec8152f3e5 ("core: arm: refactor boot")
=> core: fix CFG_BOOT_INIT_THREAD_CORE_LOCAL0

core/arch/arm/kernel/boot.c
The functions page_alloc_init() and nex_page_alloc_init() depends on MEM_AREA_TEE_DYN_VASPACE and MEM_AREA_NEX_DYN_VASPACE, but the memory areas are only available with CFG_DYN_CONFIG so check that before calling the functions.
Fixes: 0e12fb0c2d75 ("core: arm: boot: call page_alloc_init()")
=> core: arm: boot: fix calling page_alloc_init()

.github/workflows/ci.yml, lib/libmbedtls/mbedtls/library/bignum.c, mk/config.mk
CFG_TA_"MEBDTLS"_UNSAFE_MODEXP is typo. This commit fixes it.
=> libmbedtls: Fix typo of CFG_TA_MBEDTLS_UNSAFE_MODEXP

core/arch/arm/kernel/asm-defines.c, core/arch/arm/kernel/entry_a32.S, core/arch/arm/kernel/entry_a64.S
THREAD_CORE_LOCAL_STACKCHECK_RECURSION was introduced in the commit b5ec8152f3e5 ("core: arm: refactor boot"). However, clearing the stackcheck_recursion flag from assembly during boot isn't needed since the stack pointer is set up in synch with the recorded information in thread_core_local. So remove the unnecessary clearing and remove THREAD_CORE_LOCAL_STACKCHECK_RECURSION.
Reported-by: Alvin Chang <alvinga@andestech.com>
Closes: https://github.com/OP-TEE/optee_os/commit/b5ec8152f3e5ad8cc111952f0483f5cf903aac7c#r154088026
=> core: arm: remove THREAD_CORE_LOCAL_STACKCHECK_RECURSION

core/arch/arm/plat-rockchip/platform_config.h, core/arch/arm/plat-rockchip/platform_rk3588.c
Add OTP_S support and HUK for Rockchip rk3588
=> plat-rockchip: rk3588: add OTP_S support and HUK

ta/mk/ta_dev_kit.mk, ta/ta.mk
Even though the `CFG_TA_STACK_PROTECTOR_STRONG` is default to `y`, the TA's random stack canary is not generated in `__ta_entry()`.
Issue is caused by `_CFG_TA_STACK_PROTECTOR` not exported to TA compilation.
This PR fixes this issue.
=> Export _CFG_TA_STACK_PROTECTOR for TA random stack canary

scripts/checkpatch.sh, scripts/checkpatch_inc.sh, ta/pkcs11/scripts/dump_ec_curve_params.sh, ta/pkcs11/scripts/verify-helpers.sh
Some distributions don't install bash inside of bash since the only program thats required to be available in /bin according to POSIX is sh. Consequently running scripts with #!/bin/bash fails on such systems. Use /usr/bin/env (which is required to be available according to POSIX) to run the correct bash binary.
=> scripts: use /usr/bin/env bash

core/arch/arm/plat-imx/conf.mk
Sorry for back and forth about the ELE support enablement.
On i.MX8ULP, there is only one MU to communicate with ELE,
which cannot be dedicated on OP-TEE side all the time.
There may be ELE services running on Linux side, which can
cause conflict with OP-TEE, So disabling ELE by default.
Moreover i.MX8ULP also has CAAM, so HUK and Random
number are coming from CAAM.
=> core: imx: disable ELE on i.MX8ULP by default

core/arch/arm/kernel/thread_spmc.c
With Xen version 4.20 released we can announce version 1.2 for OP-TEE when negotiating the version to use. So remove the special check for CFG_NS_VIRTUALIZATION=y when exchanging versions.
=> core: arm: ffa: enable FF-A version 1.2 for virtualization

core/drivers/firewall/stm32_rifsc.c
Remove the semaphore acquisition when applying the configuration so that they are taken, if necessary, during the firewall bus probe. This avoid semaphores being taken by OP-TEE when the peripheral isn't used.
=> drivers: stm32_rifsc: remove semaphore acquisition when applying the RIF conf

core/arch/arm/plat-imx/conf.mk
Commit fc80dabbd enabled CFG_CORE_HUK_SUBKEY_COMPAT_USE_OTP_DIE_ID by default
on every iMX target, causing an issue when se05x is enabled as it also implements
tee_otp_get_die_id, but it can only be used after the stack is properly initialized, not before.
=> core: imx: disable CFG_CORE_HUK_SUBKEY_COMPAT_USE_OTP_DIE_ID with se05x

lib/libutee/include/pta_stats.h, lib/libutils/isoc/bget.c, lib/libutils/isoc/bget_malloc.c
=> Heap frag metric

core/mm/core_mmu.c
When discovering or assigning available non-secure physical memory it's checked against overlaps with other memory types. Memory types reserving virtual memory space should be excluded including the two recently added types MEM_AREA_NEX_DYN_VASPACE and MEM_AREA_TEE_DYN_VASPACE. This was missed when the memory types where added so add the check to exclude them now.
This fixes an error like:
E/TC:0   check_phys_mem_is_outside:455 Non-sec mem (0:0x60000000) overlaps map (type 10 0:0x100000) E/TC:0   Panic at core/mm/core_mmu.c:459 <check_phys_mem_is_outside>
Fixes: 96f43358c593 ("core: add nex_dyn_vaspace and tee_dyn_vaspace areas")
=> core: fix discovered ns-mem check

lib/libmbedtls/mbedtls/include/mbedtls/ssl.h
Sync with the build warning fix related to DTLS connect ID that has been approved in Mbed TLS [1].
Link: https://github.com/Mbed-TLS/mbedtls/pull/10113 [1]
=> libmbedtls: sync with DTLS connect ID build fix

core/arch/arm/kernel/entry_a32.S, core/arch/arm/kernel/entry_a64.S
With CFG_CORE_ASLR=y, stored addresses must be updated after MMU has been enabled to match the map offset. In particular the recorded stack pointers in thread_core_local[] must be updated to match the new offset before any calls can be done into C code or check_stack_limits() with CFG_CORE_DEBUG_CHECK_STACKS=y might catch an inconsistent stack pointer.
Currently, boot_mem_relocate() is called before the recorded stack pointers have been updated and causes a crash with CFG_CORE_ASLR=y and CFG_CORE_DEBUG_CHECK_STACKS=y. So fix this by calling delaying the call to boot_mem_relocate() to after the stack pointers in thread_core_local[] has been updated.
Reported-by: Jerome Forissier <jerome.forissier@linaro.org>
Closes: https://github.com/OP-TEE/optee_os/issues/7363
Fixes: ea991d7459f6 ("core: …
=> core: arm: update recorded SP first after MMU is enabled

core/arch/arm/kernel/thread.c, core/kernel/thread.c, lib/libutils/ext/ftrace/ftrace.c
Syscall ftrace collects data during a syscall. get_fbuf() checks if thread_get_id_may_fail() != -1 to see if a function is called under normal thread execution. This can lead to an inconsistent state if a native interrupt occur while ftrace_enter() or ftrace_return() is recording data in the ftrace buffer. So fix this by using thread_is_in_normal_mode() to exclude ftrace during interrupt processing.
Reported-by: Jerome Forissier <jerome.forissier@linaro.org>
Closes: https://github.com/OP-TEE/optee_os/issues/7216
Fixes: 099918f6744c ("ftrace: Add support for syscall function tracer")
=> core: fix crash during syscall ftrace

CHANGELOG.md, mk/config.mk
Update CHANGELOG for 4.6.0 and collect Tested-by tags.
The 4.6.0-rc1 tag will be created on Friday, April 11, and the 4.6.0 release is expected on April 25.
=> Update CHANGELOG for 4.6.0

core/arch/arm/plat-k3/drivers/sa2ul.c, core/arch/arm/plat-k3/platform_config.h
Even though the SA2UL integration on the AM62Ax and AM62Px platforms are functionally identical to the AM62x platforms many, when building OP-TEE manually, are using the platform name they are building for and not 'am62x' which leaves SA2UL_BASE undefined and to failed builds:
In file included from core/include/mm/core_memprot.h:9,
from core/include/kernel/interrupt.h:10,
from core/arch/arm/plat-k3/drivers/sa2ul_rng.c:12:
core/arch/arm/plat-k3/./platform_config.h:91:34: error: ‘SA2UL_BASE’ undeclared here (not in a function); did you mean ‘SCU_BASE’?
91 | #define RNG_BASE                (SA2UL_BASE + 0x10000)
|                                  ^~~~~~~~~~
For now let's just define the AM62Ax and AM62Px platform flavors identical to how AM62x is defined and include an #else statement to …
=> plat-k3: drivers: add platform flavors for 62A and 62P devices

core/tee/fs_htree.c
Correct the hash size declared in AAD length declared in REE FS hash tree authentication sequence when CFG_REE_FS_HTREE_HASH_SIZE_COMPAT is enabled in which case the hash is truncated to the size of the FEK key (TEE_FS_HTREE_FEK_SIZE).
The issue has currently no impact since REE FS hash tree authentication is based on AES-GCM but it would be of importance if, for example, one moves to an AES-CCM scheme while still enabling
CFG_REE_FS_HTREE_HASH_SIZE_COMPAT (even if unlikely to happen). To prevent such issue in the future, let's declare the effectively used hash size.
Link: https://github.com/OP-TEE/optee_os/pull/7340/commits/087325faec7c057a638cca80f0549e9abe49f190#r2024716984
=> core: fs_htree: Fix AAD length when CFG_REE_FS_HTREE_HASH_SIZE_COMPAT=y

mk/clang.mk
Since commit 45fecab08117 ("Deprecate libgcc for OP-TEE core and ldelf") libgcc is not needed to link the TEE core and ldelf. Therefore, its Clang counterpart (compiler-rt) is not needed anymore either. Note that C++ in TAs has never been supported with Clang, therefore there is nothing to worry about in this regard (while we still have CFG_TA_LIBGCC for GCC).
=> clang: do not link against the compiler's compiler-rt library

core/arch/arm/kernel/stmm_sp.c, core/core.mk, core/lib/libefi/hob.c, core/lib/libefi/include/efi/efi_types.h, core/lib/libefi/include/efi/hob.h, core/lib/libefi/include/efi/hob_guid.h, core/lib/libefi/include/efi/mmram.h, core/lib/libefi/include/efi/mpinfo.h, core/lib/libefi/sub.mk, mk/config.mk
According to Platform Initialization (PI) Specification [1] and
Discussion on edk2 mailing list [2],
StandaloneMm shouldn't create Hob but it should be passed from TF-A.
That's why StandaloneMm in Arm wouldn't produce Hob by itself [3] but
other software stack should pass boot information via PHIT Hob.
To make compatible with edk2 patches [3], 
add HOB creation to load StandaloneMm properly.
Also, StandaloneMm doesn't support under FF-A v1.2 version ABI.
For this, update syscall handler with FF-A v1.2 compatiblity.
Links: https://uefi.org/sites/default/files/resources/PI_Spec_1_6.pdf [1]
Links: https://edk2.groups.io/g/devel/topic/103675962#114283 [2]
Links: https://github.com/tianocore/edk2/pull/6116 [3]
Tested-by: Ilias Apalodimas <ilias.apalodimas@linaro.org>
Acked-by: Ilias Apalodimas …
=> core: add HOB creation and Apply FF-A v1.2 in stmm_sp.

core/arch/riscv/kernel/boot.c, core/arch/riscv/kernel/entry.S, core/include/kernel/thread.h, core/kernel/thread.c, mk/config.mk
This PR tries to keep RISC-V's boot stage up-to-date with ARM's.
- Initialize `thread_core_local[primary_cpu_id]` in assembly code before calling C code
- Remove `CFG_BOOT_INIT_CURRENT_THREAD_CORE_LOCAL` since both architectures explicitly support this feature.
- Call `page_alloc_init()`
=> RISC-V: Keep boot stage up-to-date

.github/workflows/ci.yml
The "make check (QEMUv8, BTI+MTE+PAC)" CI job currently checks out an old version of QEMU. Not only is this workaround not necessary anymore, but worse it makes the check fail with the following output (from out/bin/serial0.log):
Starting kernel ...
**
ERROR:../target/arm/internals.h:742:regime_is_user: code should not be reached
Bail out! ERROR:../target/arm/internals.h:742:regime_is_user: code should not be reached
Aborted (core dumped)
send: spawn id exp9 not open
while executing
"send -- "root\r\r""
(file "/root/optee/build/../build/qemu-check.exp" line 129
Therefore, let the QEMU version from the manifest be used.
=> ci: do not override QEMU version

.github/workflows/ci.yml
Diaable the "make check (QEMUv8, Xem FF-A)" job until an issue is fixed in the OP-TEE and FF-A kernel drivers [1].
Link: https://github.com/OP-TEE/optee_os/issues/7394 [1]
=> ci: disable QEMUv8 Xen FF-A job

core/arch/arm/plat-k3/drivers/ti_sci.c, core/arch/arm/plat-k3/drivers/ti_sci.h, core/arch/arm/plat-k3/drivers/ti_sci_protocol.h
These are added for completeness with the full set of TI-SCI OTP revision calls[0]. These can be used from a TA should modifying these counters need be done in OP-TEE.
[0] https://software-dl.ti.com/tisci/esd/latest/2_tisci_msgs/security/otp_revision.html
=> Add K3 TI-SCI call functions for writing Software and Key Revision Counters

.github/workflows/ci.yml
Add a check entry for Arm Firmware Handoff.
This patch depends on:
https://github.com/OP-TEE/build/pull/821
https://github.com/OP-TEE/manifest/pull/321
https://github.com/OP-TEE/manifest/pull/325
=> ci: QEMUv8: check Firmware Handoff

core/drivers/crypto/caam/include/caam_ae.h
Fix undefined reference to `caam_ae_init` for CAAM enabled targets which do not use CAAM AE.
=> caam: fix compilation when CFG_NXP_CAAM_AE_* is not enabled

core/drivers/firewall/stm32_rifsc.c, core/drivers/firewall/stm32_risab.c, core/drivers/stm32_hpdma.c
When an AHB busy signal is inserted during a transaction, a ghost CID0 is generated on the bus. If the
compartment filtering is enabled on RISAB3/4/5, this transient CID0 is interpreted as a fault access by
RISAB3/4/5 which aborts current access and returns an IAC.
Link to errata (section 2.3.21): [https://www.st.com/resource/en/errata_sheet/es0598-stm32mp23xx25xx-device-errata-stmicroelectronics.pdf](url)
=> (STM32) drivers: Implement AHB RISAB3/4/5 illegal access due to ghost CID0 detection errata

lib/libmbedtls/mbedtls/library/common.h
Cherry-picking commit 7505c3588f44 ("libmbedtls: fix compilation warning with GCC14") which was lost in commit c3deb3d6f3b1 ("Squashed commit upgrading to mbedtls-3.6.3"). It should have been pushed onto the import/mbedtls-3.6.2 branch when it was accepted in master but that didn't happen and therefore it was unfortunately left aside when upgrading. This time it has been applied to import/mbedtls-3.6.3 [1] so it will hopefully not be forgotten in the next upgrade.
Link: https://github.com/OP-TEE/optee_os/commit/b526c146f87 [1]
=> libmbedtls: fix compilation warning with GCC14 (2)

core/arch/arm/kernel/entry_a32.S, core/arch/arm/kernel/entry_a64.S, core/arch/riscv/kernel/entry.S, core/include/kernel/thread.h, core/kernel/thread.c, mk/config.mk
This commit replaces CFG_DYN_STACK_CONFIG with CFG_DYN_CONFIG since now RISC-V also supports CFG_DYN_STACK_CONFIG.
=> core: replace CFG_DYN_STACK_CONFIG with CFG_DYN_CONFIG

core/arch/riscv/mm/core_mmu_arch.c
The user_vpn2_table_va[] stores several pointers pointing to the level 2 page tables used by user TA. When CFG_CORE_ASLR=y, these pointers must be relocated to ASLR VA as well. To fix this issue, we call boot_mem_add_reloc() onto each element of user_vpn2_table_va[], so that the pointers have a chance to be relocated by boot_mem_relocate() later.
Discussed in https://github.com/OP-TEE/optee_os/pull/7371#discussion_r2107604866
=> riscv: mm: fix relocation of pointers in user_vpn2_table_va[]

.github/workflows/ci.yml
The two QEMUv8 jobs (1/2 and 2/2) take roughly 90 minutes to run while the next longest job (QEMUv8, Xen) takes about 50 minutes. Split these jobs further to reduce the overall duration of the CI pipeline.
=> ci: further split QEMUv8 jobs

.github/workflows/ci.yml, MAINTAINERS, core/arch/arm/plat-versal2/conf.mk, core/drivers/amd/gpio_common.c, core/drivers/amd/gpio_private.h, core/drivers/amd/ps_gpio_driver.c, core/drivers/amd/sub.mk, core/drivers/sub.mk
Add PS GPIO Driver support for AMD Platforms.
The PS GPIO Controller is managed through the PS subsystem and can operate in either the Secure World or the Non-Secure World. The driver utilizes the Device Tree Blob (DTB) to determine whether the PS GPIO Controller should be supported in the Secure World.
=> drivers: amd: Add PS GPIO Support

core/include/kernel/dt_driver.h
While adding DT_DRIVER_PINCTRL, an incorrect word was reported by copy/paste from the existing comment for DT_DRIVER_RSTCTRL.
Drop the word 'reset' from the comment for DT_DRIVER_PINCTRL.
Fixes: b5aff6de7052 ("core: dt_driver: add support for DT_DRIVER_PINCTRL")
=> core: kernel: dt_driver: fix copy/paste comment

core/arch/arm/dts/stm32mp131.dtsi, core/arch/arm/dts/stm32mp135f-dk.dts, core/arch/arm/dts/stm32mp151.dtsi, core/arch/arm/dts/stm32mp15xx-dkx.dtsi, core/arch/arm/dts/stm32mp251.dtsi, core/arch/arm/dts/stm32mp257f-ev1.dts, core/drivers/stm32_gpio.c, core/drivers/stm32_rtc.c, core/drivers/stm32_tamp.c, core/include/drivers/stm32_gpio.h, core/include/drivers/stm32_rtc.h, core/include/drivers/stm32mp_dt_bindings.h, core/include/dt-bindings/tamper/st,stm32-tamp.h, core/include/dt-bindings/tamper/st,stm32mp13-tamp.h, core/include/dt-bindings/tamper/st,stm32mp21-tamp.h, core/include/dt-bindings/tamper/st,stm32mp25-tamp.h
The anti-tamper detection circuit is used to protect sensitive data from external attacks. On a tamper event detection, all or part of the secrets of the board are erased.
Add support for the tamper event detection with the wakeup capability and time stamping support. To be able to enable the wakeup capability, rely on the EXTI line for stm32mp13/25 SoCs instead of the GIC one. The EXTI makes the link with the GIC itself.
This series depends on: #7419
=> (STM32) Add support for tamper event detection

core/arch/riscv/kernel/entry.S
The hart ID is stored in s0 register not a0 register. This fixes multi-hart boot hang issue.
Fixes: 29661368f51d ("core: riscv: preserve hartid in s0 register at entry point")
=> core: riscv: fix hartid for primary hart when CFG_DYN_CONFIG=y

core/kernel/tee_ta_manager.c, lib/libutee/include/user_ta_header.h, ta/user_ta_header.c
Add the optee.ta.instanceKeepCrashed property to prevent a TA with gpd.ta.instanceKeepAlive=true to be restarted. This prevents unexpected resetting of the state of the TA.
Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>
Reviewed-by: Alex Lewontin <alex.lewontin@canonical.com>
=> Add optee.ta.instanceKeepCrashed property

ta/link.mk
When the TA signing key for OP-TEE was changed [1], the TA encryption key (which is a derived key) was not updated. As a result, CFG_ENCRYPT_TA=y is broken. Fix that by updating TA_ENC_KEY to reflect the output of tee_otp_get_ta_enc_key().
Fixes: 5d5d7d0b1c03 ("keys: increase default RSA key size to 4096 bits") [1]
=> ta/link.mk: update the default TA encryption key

.github/workflows/ci.yml, core/include/kernel/asan.h, core/kernel/asan.c, core/pta/tests/misc.c, lib/libutils/isoc/arch/arm/setjmp_a32.S, lib/libutils/isoc/arch/arm/setjmp_a64.S, lib/libutils/isoc/arch/riscv/setjmp_rv.S, lib/libutils/isoc/bget_malloc.c, lib/libutils/isoc/include/setjmp.h
Hi,
this MR proposes several improvements for **KASAN**.
**Adds runtime KASAN tests**
Added a dedicated KASAN self-test suite covering:
- Stack overflow
- Global buffer overflow
- Heap overflow
- Use-after-free
- Invalid accesses using memcpy / memset
These tests could help to track potential regression in KASAN functionality.
**Fixes check_access()**
It seems implementation didn't cover some corner cases, please see commit msg for details.
I borrowed some [freebsd code](https://github.com/freebsd/freebsd-src/blob/main/sys/kern/subr_asan.c) to rewrite [check_access](https://github.com/OP-TEE/optee_os/blob/master/core/kernel/asan.c#L169) in correct/optimized way.
**Some changes in heap tagging**
It seems in some cases it tag more memory as available than it should.
**Adds support for …
=> KASAN: several minor fixes / selftests

core/drivers/ffa_console.c
Some Hypervisor (including Hafnium under v2.9) does not support FFA_CONSOLE_LOG_64
so this change makes FFA console uses FFA_CONSOLE_LOG_32 when FFA_CONSOLE_LOG_64 isn't supported.
=> drivers: ffa_console: add support for multiple character at once

core/kernel/asan.c, core/pta/tests/misc.c, lib/libutils/isoc/newlib/strchr.c, lib/libutils/isoc/newlib/strcmp.c, lib/libutils/isoc/newlib/strcpy.c, lib/libutils/isoc/newlib/strlen.c
Hi,
This PR introduces two improvements related to AddressSanitizer (ASan) support:
- Redzones after global variables
Adds redzones after global variables, particularly benefiting `.rodata` variables. The shadow memory related to `.rodata` section is zeroed out in `init_asan()` (what is not true for `.data` or `.bss`), which can hide certain read overflows for constant variables whose size is aligned to `ASAN_BLOCK`. (see test-case)
- Disables certain optimized string functions in newlib under ASan
Disables the use of some optimized string manipulation functions from newlib when ASan is enabled. These versions use the `DETECTNULL` macro, which performs out-of-bounds reads. While this is generally safe due to word-aligned buffer starts, it causes ASan to panic. Notably, the issue was …
=> Several ASan fixes

core/arch/arm/plat-imx/conf.mk
This PR adds support for (remaining) PHYTEC i.MX 8M family based boards.
Mainly, their board flavour is added and CONFIG options deviating from the default are specified.
For the existing PHYTEC phyBOARD-Pollux i.MX 8M  board, the DDR_SIZE is brought in line with the newly introduced boards; i.e. use min RAM of each variant.
=> Imx8m phytec boards

core/arch/arm/kernel/boot.c, core/kernel/tpm.c
This pull request introduces several improvements to the handling of the TPM event log within OP-TEE.
- __Device Tree Mapping__: We’ve simplified the device tree mapping process by replacing conditional compilation with a unified get_dt() function. This enhances code readability and maintainability while ensuring the correct device tree source is selected.
- __TPM Log Area Zeroing__: A fix has been implemented to prevent a write permission fault during TPM log area zeroing when using the SPMC manifest device tree. The zeroing operation is now conditional on the device tree source.
- __TPM Log Address Parsing__: We’ve addressed a potential issue with ARM32 systems by ensuring the full 64-bit TPM event log address is parsed consistently across all ARM architectures. This resolves potential …
=> Fix TPM log area mapping, zeroing, and address parsing for improved stability and consistency.

core/mm/vm.c
Fix vm_check_access_rights() so it handles zero-length memory ranges consistently. Previously, the function had inconsistent behavior for zero-length checks:
- For page-aligned addresses: Would skip the page checking loop entirely and return TEE_SUCCESS.
- For unaligned addresses: Would round uaddr down to page boundary and return a result based on that page.
With this change flags = SECURE | NON_SECURE will still fail to preserve the sanity checking, but all other zero-length ranges result in TEE_SUCCESS.
Specifically this was required due to an interaction between OP-TEE and Rust where Keymint [0] would call the Teaclave [1] wrapper around TEE_MACComputeFinal with an empty temporary slice (pointer + length pair) as the final message (&[]). Rust always requires the pointer to be …
=> mm: fix zero-length access check inconsistency

core/arch/arm/plat-rockchip/conf.mk, core/arch/arm/plat-rockchip/platform_config.h, core/arch/arm/plat-rockchip/platform_rk3588.c, core/drivers/rockchip_otp.c, core/drivers/sub.mk, core/include/drivers/rockchip_otp.h
The OTP handling is useful outside the rk3588 platform implementation. For example, the fuses for secure boot are accessible via the OTP.
Extract the OTP write and read support to a separate driver to make it available for other modules.
=> drivers: rockchip: extract OTP driver from rk3588 platform

core/arch/arm/plat-rockchip/platform_rk3588.c
I observed timeout errors when OP-TEE reads the HUK from the OTP area
while running the optee-xtests (tests 1006 and 4013) or using the
pkcs#11 TA.
This issue is circumvented by reading the HUK once and caching it in
memory for later use. As a side effect, this reduces the accesses/reads
from the OTP area.
Unfortunately, I don't know the root cause for the timeout while reading
the fuses. I guess that there is a disabled clock which prevents the
read, but I didn't look further, since caching works fine.
While the documentation recommends to never process the HUK in software,
it is read and processed anyway if it can be read from the fuses. Thus,
I don't think that caching has an effect on the security of the HUK.
The caching is inspired by the HUK handling implemented in the nvmem
driver.
=> plat-rockchip: rk3588: cache HUK in memory
